- build.gradle
- deployment/aws/aws.tf
- deployment/aws/bootstrap.sh
- deployment/aws/installer/ansible.cfg
- deployment/aws/installer/data/variable_template.yml
- deployment/aws/installer/entry_point_template.yml
- deployment/aws/installer/roles/install-bk/tasks/main.yml
- deployment/aws/installer/roles/install-controller/tasks/main.yml
- deployment/aws/installer/roles/install-hosts/tasks/main.yml
- deployment/aws/installer/roles/install-prereqs/tasks/main.yml
- deployment/aws/installer/roles/install-zk/defaults/main.yml
- deployment/aws/installer/roles/install-zk/tasks/main.yml
- deployment/aws/installer/roles/install-zk/templates/zoo.cfg.j2
- deployment/aws/variable.tf
* Add license files to all files that can accommodate comments
* Exclude log files so that the build doesn't fail because some existing log files
* Exclude `deployment/aws/installer/hosts-template`
Fixes #1301 
Adds missing license headers and excludes one file that doesn't need (and I believe I can't have a comment there).
> Issue 1301: Add license headers to deployment/AWS

- segmentstore/contracts/src/main/java/io/pravega/service/contracts/AttributeUpdate.java
- segmentstore/contracts/src/main/java/io/pravega/service/contracts/AttributeUpdateType.java
- segmentstore/server/src/main/java/io/pravega/service/server/AttributeSerializer.java
- segmentstore/server/src/main/java/io/pravega/service/server/logs/OperationMetadataUpdater.java
- segmentstore/server/src/test/java/io/pravega/service/server/containers/StreamSegmentContainerTests.java
- segmentstore/server/src/test/java/io/pravega/service/server/containers/StreamSegmentMapperTests.java
- segmentstore/server/src/test/java/io/pravega/service/server/logs/OperationMetadataUpdaterTests.java
- segmentstore/server/src/test/java/io/pravega/service/server/logs/operations/StreamSegmentAppendOperationTests.java
Added `ReplaceIfEquals` as an `AttributeUpdateType`, which is effectively an atomic Compare-And-Set. This applies to both attributes updated as part of Appends, and stand-alone Attribute Updates.
Fixes #1316. This is required to ensure correctness of appends via the client in some scenarios.
New AttributeUpdateType added, as well as supporting code for it.
Unit tests updated to include the new update type.
> Issue 1316: (SegmentStore) Compare-And-Set Attribute Update Type

- test/integration/src/test/java/io/pravega/test/integration/ControllerStreamMetadataTest.java
Reduced timeout of test ControllerStreamMetadataTest.streamMetadata to 10seconds.
Fixes #789 
As described above.
ControllerStreamMetadataTest.streamMetadata test should pass, other behaviour is unchanged.
> Issue 789: Reduced ControllerStreamMetadataTest.streamMetadata test timeout

- client/src/main/java/io/pravega/client/stream/ReaderConfig.java
- client/src/main/java/io/pravega/client/stream/ReaderGroupConfig.java
- client/src/main/java/io/pravega/client/stream/impl/ClientFactoryImpl.java
- client/src/main/java/io/pravega/client/stream/impl/ReaderGroupStateManager.java
- client/src/test/java/io/pravega/client/stream/impl/ReaderGroupStateManagerTest.java
* Add an `initialAllocationDelay` parameter as part of the reader configuration. 
* Use the `groupRefreshTimeMillis` in the ReaderGroupConfiguration
To support https://github.com/pravega/flink-connectors/issues/15 more easily we can delay aquiring segments for a bit to allow for time for other readers to come online to acheive a more equal distribution.
Adds a config parameter that instructs the reader how long to wait on startup before acquiring any new segments. 
Run the scenario in https://github.com/pravega/flink-connectors/issues/15 with this paramerter set.
> Issue flink-connectors#15: Feature delay acquiring segments

- client/src/main/java/io/pravega/client/segment/impl/SegmentOutputStreamImpl.java
- client/src/main/java/io/pravega/client/state/impl/RevisionedStreamClientImpl.java
- gradle.properties
- gradle/findbugs.gradle
- segmentstore/contracts/src/main/java/io/pravega/segmentstore/contracts/AttributeUpdate.java
- segmentstore/contracts/src/main/java/io/pravega/segmentstore/contracts/AttributeUpdateType.java
- segmentstore/server/host/src/main/java/io/pravega/segmentstore/server/host/handler/AppendProcessor.java
- segmentstore/server/host/src/test/java/io/pravega/segmentstore/server/host/handler/AppendProcessorTest.java
- shared/protocol/src/main/java/io/pravega/shared/protocol/netty/Append.java
- shared/protocol/src/main/java/io/pravega/shared/protocol/netty/AppendDecoder.java
- shared/protocol/src/main/java/io/pravega/shared/protocol/netty/CommandEncoder.java
- shared/protocol/src/main/java/io/pravega/shared/protocol/netty/DelegatingReplyProcessor.java
- shared/protocol/src/main/java/io/pravega/shared/protocol/netty/FailingReplyProcessor.java
- shared/protocol/src/main/java/io/pravega/shared/protocol/netty/ReplyProcessor.java
- shared/protocol/src/main/java/io/pravega/shared/protocol/netty/WireCommandType.java
- shared/protocol/src/main/java/io/pravega/shared/protocol/netty/WireCommands.java
- shared/protocol/src/test/java/io/pravega/shared/protocol/netty/AppendEncodeDecodeTest.java
- shared/protocol/src/test/java/io/pravega/shared/protocol/netty/WireCommandsTest.java
- test/integration/src/test/java/io/pravega/test/integration/AppendTest.java
- test/integration/src/test/java/io/pravega/test/integration/MultiReadersEndToEndTest.java
- test/integration/src/test/java/io/pravega/test/integration/StateSynchronizerTest.java
- test/system/src/test/java/io/pravega/test/system/PravegaTest.java
* Take advantage of the compare and set update added in #1323 to make sure appends are going at the expected location.
* Rename connectionId to writerId (as this is how it is used)
* Added a call to flush that was causing unit tests to run slow.
See #1324 
Tracks the previous append to succeed in AppendProcessor so that when the next one is written it is conditional on that writer having not written any in the meantime. 
Everything should work as before, all tests should continue to pass. New tests have been added to verify the changes to AppendProcessor.
> Issue 1324: Use attributes to track event offsets.

- test/system/src/test/java/io/pravega/test/system/MultiSegmentStoreTest.java
It has been observed that Transaction Commits fail (causing failure of AutoScale tests) when the tests are run after SS failover tests (MultiSegmentStoreTest). 
Disabling this test temporarily to root cause the issue.
Fixes #1348 
> Issue 1348: Temporarily disable MultiSegmentStoreTest inside system tests.

- segmentstore/contracts/src/main/java/io/pravega/segmentstore/contracts/AttributeUpdateType.java
- segmentstore/server/host/src/main/java/io/pravega/segmentstore/server/host/handler/AppendProcessor.java
- segmentstore/server/host/src/main/java/io/pravega/segmentstore/server/host/handler/PravegaRequestProcessor.java
- segmentstore/server/host/src/test/java/io/pravega/segmentstore/server/host/handler/AppendProcessorTest.java
- segmentstore/server/host/src/test/java/io/pravega/segmentstore/server/host/handler/PravegaRequestProcessorTest.java
- segmentstore/server/src/main/java/io/pravega/segmentstore/server/SegmentMetadata.java
- segmentstore/server/src/main/java/io/pravega/segmentstore/server/logs/OperationMetadataUpdater.java
- shared/protocol/src/main/java/io/pravega/shared/protocol/netty/DelegatingReplyProcessor.java
- shared/protocol/src/main/java/io/pravega/shared/protocol/netty/DelegatingRequestProcessor.java
- shared/protocol/src/main/java/io/pravega/shared/protocol/netty/FailingReplyProcessor.java
- shared/protocol/src/main/java/io/pravega/shared/protocol/netty/FailingRequestProcessor.java
- shared/protocol/src/main/java/io/pravega/shared/protocol/netty/ReplyProcessor.java
- shared/protocol/src/main/java/io/pravega/shared/protocol/netty/RequestProcessor.java
- shared/protocol/src/main/java/io/pravega/shared/protocol/netty/WireCommandType.java
- shared/protocol/src/main/java/io/pravega/shared/protocol/netty/WireCommands.java
- shared/protocol/src/test/java/io/pravega/shared/protocol/netty/WireCommandsTest.java
* Adds GetSegmentAttribute and UpdateSegmentAttribute wire commands and server support. (Note this is a backwards compatible wire format change.)
* Exposes SegmentMetadata.NULL_ATTRIBUTE_VALUE to the client by duplicating the value in WireCommand.
This adds wire-protocol support for clients to use Attributes. This is a prerequisite for #1216 
Adds new requests and replies that are handled by PravegaRequestProcessor
Tests are added for serialization, and for the new processor methods.
> Issue 1216 part-1: Add client access to segment attributes

- test/system/src/test/java/io/pravega/test/system/MultiSegmentStoreTest.java
Re-enable MultiSegmentStore test, since system tests are successful with HDFS version 2.7.2 and 2.7.3. All the system tests now run on 2.7.3.
#1348 
Enable all the tests
System tests should succeed.
> Issue 1348: re-enable MultiSegmentStoreTest

- build.gradle
- gradle.properties
Prevents hadoop libraries from pulling in dependencies on log4j.
Updates the version of slf4jApiVersion and logback to the latest
Fix #1371 
Excludes slf4j-log4j12 from the dependencies pulled in from those packages that depend on it.
All tests should continue to pass and logging should work without warnings.
> Issue 1371: Exclude transitive dependencies on log4j

- test/testcommon/src/main/java/io/pravega/test/common/TestUtils.java
When we use TestUtils.getAvailableListenPort() from parallel processes this method starts scanning for ports in the same sequence and hence can cause port conflicts when they find the same port to be available. To avoid this we will now start scanning for ports from a randomized start index within the same range. The probability of port clashes will reduce significantly.
Fixes #1383 
Avoids port clashes.
Enable gradle parallel builds (Enable org.gradle.parallel=true in gradle properties) and execute ./gradlew clean build
> Issue 1383: Fixing port conflicts in parallel gradle builds. Also enabled gradle parallel builds by default

- build.gradle
- controller/src/main/java/io/pravega/controller/server/ControllerServiceMain.java
- standalone/src/main/java/io/pravega/local/InProcPravegaCluster.java
- standalone/src/main/java/io/pravega/local/LocalPravegaEmulator.java
- standalone/src/main/java/io/pravega/local/SingleNodeConfig.java
Starting a rest server along with other Pravega components in standalone gradle task.
Fixes #832 
Excludes com.sun.jersey dependency. 
./gradlew startStandalone 
Use curl/rest client to call rest apis on localhost:9091
eg.
`curl -i -X GET http://localhost:9091/ping`
```
HTTP/1.1 200 OK
content-length: 0
connection: keep-alive
```
> Issue 832: Start rest server in standalone gradle task

- .codecov.yml
Ignoring generated folders for generating code coverage
Fixes #1404 
Adds generated folder to codecov's ignore path
Check code coverage statistics
> Issue 1404: Remove generated folders from code coverage report

- client/src/main/java/io/pravega/client/admin/ReaderGroupManager.java
- client/src/main/java/io/pravega/client/admin/impl/ReaderGroupManagerImpl.java
- client/src/main/java/io/pravega/client/stream/impl/ControllerImpl.java
- client/src/test/java/io/pravega/client/stream/impl/ReaderGroupStateManagerTest.java
- client/src/test/java/io/pravega/client/stream/mock/MockController.java
- client/src/test/java/io/pravega/client/stream/mock/MockStreamManager.java
- test/integration/src/test/java/io/pravega/test/integration/MultiReadersEndToEndTest.java
- test/integration/src/test/java/io/pravega/test/integration/ReaderGroupTest.java
- test/system/src/test/java/io/pravega/test/system/MultiSegmentStoreTest.java
- test/system/src/test/java/io/pravega/test/system/PravegaTest.java
- test/system/src/test/java/io/pravega/test/system/ReadWithAutoScaleTest.java
* Add convenience method to delete a reader group.
Fixes #1211 
Adds a method to delete a reader group's stream
Calls to delete created reader groups have been added to the integration tests. All tests should pass.
> Issue 1211: Add convenience method to delete a reader group.

- README.md
Changed Travis build icon and URL to the one on Travis-ci.org
Just image URL change.
See the Github homepage for build icon and click it.
> Switched to Travis-CI.org

- client/src/main/java/io/pravega/client/segment/impl/SegmentMetadataClient.java
- client/src/main/java/io/pravega/client/segment/impl/SegmentMetadataClientImpl.java
- client/src/main/java/io/pravega/client/state/RevisionedStreamClient.java
- client/src/main/java/io/pravega/client/state/StateSynchronizer.java
- client/src/main/java/io/pravega/client/state/impl/RevisionedStreamClientImpl.java
- client/src/main/java/io/pravega/client/state/impl/StateSynchronizerImpl.java
- client/src/main/java/io/pravega/client/stream/impl/EventStreamReaderImpl.java
- client/src/main/java/io/pravega/client/stream/impl/ReaderGroupImpl.java
- client/src/main/java/io/pravega/client/stream/impl/ReaderGroupStateManager.java
- client/src/test/java/io/pravega/client/state/impl/SynchronizerTest.java
- client/src/test/java/io/pravega/client/stream/impl/ReaderGroupStateManagerTest.java
- test/integration/src/test/java/io/pravega/test/integration/StateSynchronizerTest.java
* Adds a close method to cleanup connections in RevisionedStreamClient and in StateSynchronizer on top of it. 
* Invokes these methods everywhere these classes are being used and the connections were not being cleaned up.
Fixes #1430 
Adds a close method to StateSynchronizer and RevisionedStreamClient
Close calls were added to the tests using these classes. All tests pass.
> Issue 1430: Add close to state synchronizer

- segmentstore/server/host/src/main/java/io/pravega/segmentstore/server/host/handler/AppendProcessor.java
- segmentstore/server/host/src/main/java/io/pravega/segmentstore/server/host/handler/PravegaRequestProcessor.java
- segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/bookkeeper/Metrics.java
- shared/metrics/src/main/java/io/pravega/shared/MetricsNames.java
- shared/metrics/src/main/java/io/pravega/shared/metrics/StatsProviderImpl.java
- shared/metrics/src/test/java/io/pravega/shared/metrics/MetricsProviderTest.java
Renaming metrics reported in pravega.
Fixes #1370 
Renames metrics in pravega. Removes 'DYNAMIC' from names. Adds relevant prefix controller, store, hdfs etc.
startStandlaone gradle task will start pravega services and some metrics can be seen in /tmp/csv/pravega folder.
> Issue 1370: Renaming Pravega Metrics

- segmentstore/server/src/main/java/io/pravega/segmentstore/server/containers/StreamSegmentContainerMetadata.java
- segmentstore/server/src/main/java/io/pravega/segmentstore/server/logs/ContainerMetadataUpdateTransaction.java
- segmentstore/server/src/test/java/io/pravega/segmentstore/server/logs/OperationMetadataUpdaterTests.java
Fixed a bug in the ContainerMetadataUpdateTransaction that could potentially create duplicate Segment Ids. SegmentIds should be generated starting from the current Operation Sequence number (which guarantees a unique id to begin with), however due to a bug in the code, this was being generated off the newly assigned sequence number (which would only be set during recovery, and always starts off at `Long.MIN_VALUE`). This has been fixed to work as before.
Fixes #1428. Please refer to this issue's comments for the complete steps to repro the problem.
Fixes a bug introduced by #1330 / #1391.
Look at the code, make sure unit tests pass. New assertion has been introduced to validate new segment id …
> Issue 1428: Fix duplicate Segment Id bug

- controller/src/test/java/io/pravega/controller/timeout/TimeoutServiceTest.java
Existing TimeoutServiceTest.testPingFailureMaxExecutionTimeExceeded attempts to fail lease renewal by supplying a lease value to pingTxn API that exceeds maxExecutionTime by 1ms. This test fails intermittently if pingTxn API gets executed 1ms before expectation. Fixing this problem by supplying a lease value that exceeds maxExecutionTime by much more than 1ms.
Fixes #1375 
As described above.
Test cases in TimeoutServiceTest.
> Issue 1375: Changes to TimeoutServiceTest.testPingFailureMaxExecutionTimeExceeded

- client/src/main/java/io/pravega/client/admin/StreamManager.java
- client/src/main/java/io/pravega/client/admin/impl/StreamManagerImpl.java
- client/src/main/java/io/pravega/client/stream/EventStreamReader.java
- client/src/main/java/io/pravega/client/stream/ReaderGroup.java
- client/src/main/java/io/pravega/client/stream/impl/Controller.java
- client/src/main/java/io/pravega/client/stream/impl/ControllerImpl.java
- client/src/main/java/io/pravega/client/stream/impl/ReaderGroupImpl.java
- client/src/test/java/io/pravega/client/stream/impl/ControllerImplTest.java
- client/src/test/java/io/pravega/client/stream/mock/MockController.java
- client/src/test/java/io/pravega/client/stream/mock/MockStreamManager.java
- controller/src/main/java/io/pravega/controller/server/ControllerService.java
- controller/src/main/java/io/pravega/controller/server/eventProcessor/LocalController.java
- controller/src/main/java/io/pravega/controller/server/rest/resources/StreamMetadataResourceImpl.java
- controller/src/main/java/io/pravega/controller/server/rpc/grpc/v1/ControllerServiceImpl.java
- controller/src/main/java/io/pravega/controller/task/Stream/StreamMetadataTasks.java
- controller/src/test/java/io/pravega/controller/rest/v1/StreamMetaDataTests.java
- controller/src/test/java/io/pravega/controller/server/eventProcessor/LocalControllerTest.java
- controller/src/test/java/io/pravega/controller/server/v1/ControllerServiceImplTest.java
- controller/src/test/java/io/pravega/controller/task/TaskTest.java
- docs/basic-reader-and-writer.md
- docs/pravega-concepts.md
- shared/controller-api/src/main/proto/Controller.proto
- test/integration/src/test/java/io/pravega/test/integration/controller/server/ControllerServiceTest.java
- test/integration/src/test/java/io/pravega/test/integration/controller/server/StreamMetadataTest.java
Alter stream and update stream are being used interchangeably in pravega code. Here we update the code and documentation to consistently use 'update' since its a standard terminology for modify APIs.
Fixes #588 
Replaces all occurrences of alter stream with update stream
No functionality change, all existing tests should pass.
> Issue 588: Renaming alterStream to updateStream to make the terminology consistent

- docker/bookkeeper/entrypoint.sh
Allow setting of the  `autoRecoveryDaemonEnabled` bookie setting that turns on the AutoRecovery daemons.
Fixes #1457
Allows turning on the AutoRecovery Daemons which will make sure all Bookkeeper segments are kept at their correct replication levels should a bookie fail.
Deploy Bookie with environment variable `BK_AUTORECOVERY=true` and the bookie logs will show the Auto Recovery Auditor starting :
```
....
2017-06-20 11:34:38,277 - INFO  - [main:BookieServer@395] - Register shutdown hook successfully
2017-06-20 11:34:39,574 - INFO  - [AuditorElector-172.16.28.4:3181:RackawareEnsemblePlacementPolicy@330] - Initialize rackaware ensemble placement policy @ <Bookie:172.16.28.4:0> : …
```
> Issue 1457: Added autoRecoveryDaemonEnabled setting to Bookie entry point

- segmentstore/server/host/src/main/java/io/pravega/segmentstore/server/host/ZKSegmentContainerMonitor.java
- segmentstore/server/host/src/test/java/io/pravega/segmentstore/server/host/ZKSegmentContainerMonitorTest.java
Using zookeeper watch to monitor segment container assignment to avoid delay in processing ownership changes.
In addition to a scheduled thread, we also watch zookeeper for any ownership changes so the processing can be done as soon as a change is detected.
Fixes #1086 
Registers a watch to zookeeper to listen for ownership changes
Reduced the wait timeouts in the existing test cases, since the updates now happen immediately.
./gradlew test
> Issue 1086: Reduce delay in reacting to segment container ownership changes.

- docs/mkdocs.yml
- Added REST API documentation link to the docs menu
- Added REST API documentation link to the docs menu
- Fixes #1406
Checkout the docs after generating it using mkdocs
> Issue 1406: Adds Rest API link to the docs page.

- controller/src/test/java/io/pravega/controller/timeout/TimeoutServiceTest.java
Test testUnknownTxnPingSuccess fails intermittently due to temporal dependencies among test steps. However, all of these temporal dependencies are redundant from the behavior being tested in this test. Hence removed redundant temporal dependencies from testUnknownTxnPingSuccess test. 
Fixes #1455.
As described above.
Test testUnknownTxnPingSuccess should always pass.
> Issue 1455: Removed temporal dependencies from testUnknownTxnPingSuccess test

- controller/src/main/java/io/pravega/controller/store/stream/ZKScope.java
- controller/src/main/java/io/pravega/controller/store/stream/ZKStoreHelper.java
- controller/src/test/java/io/pravega/controller/server/eventProcessor/ScaleRequestHandlerTest.java
- controller/src/test/java/io/pravega/controller/store/stream/StreamMetadataStoreTest.java
A few APIs in ZKStoreHelper was still using blocking ZK APIs.
Now replaced all of them with non-blocking equivalents using curator's inBackground() API.
Fixes #1366 
Removes all blocking calls to ZK.
The APIs are covered in existing test cases and should pass.
> Issue 1366: Remove usage of blocking ZK APIs

- segmentstore/server/src/test/java/io/pravega/segmentstore/server/logs/DataFrameBuilderTests.java
Fixed a sporadically-failing unit test due to unit-test-related sync issues: in some cases the number of attempts was double-decremented when failed, which could lead to the test believing fewer than actual operations were committed.
Fixes #1460.
Fixed unit test.
Unit test passes consistently.
> Issue 1460: (SegmentStore) Sporadic UnitTest failure in DataFrameBuilderTests

- controller/src/main/java/io/pravega/controller/fault/SegmentMonitorLeader.java
- controller/src/test/java/io/pravega/controller/fault/SegmentContainerMonitorTest.java
Using timeout heuristics to club multiple host events which happen in quick succession into one rebalance operation. This handle cases like node restart, fresh cluster start, multi-host start/failures, etc.
Fixes #201 
Uses the existing timeout values to wait for multi-host events before triggering rebalance operations.
Existing test cases present for handling host start/stop should succeed.
./gradlew test
> Issue 201: SegmentContainerMonitor: handle multiple host events

- segmentstore/server/src/main/java/io/pravega/segmentstore/server/logs/ContainerMetadataUpdateTransaction.java
- segmentstore/server/src/test/java/io/pravega/segmentstore/server/containers/StreamSegmentContainerTests.java
- segmentstore/server/src/test/java/io/pravega/segmentstore/server/logs/ContainerMetadataUpdateTransactionTests.java
Fixed a bug in ContainerMetadataUpdateTransaction where the ActiveSegmentCount would not refresh for a transaction when the ContainerMetadata's value changes.
This was done by calculating this value by referring to the real metadata, to which are added the counts of all newly mapped segments in the current chain of transactions.
Fixes #1448.
Fixed the bug, added a unit test to accurately reproduce it. Enhanced an existing unit test to reduce the likelihood of this happening again (since it needs to wait for some background async operations to complete which are opaque to the test).
New unit test added, existing unit test improved to reduce the likelihood of this hitting again.
> Issue 1448: (SegmentStore) Fixed ContainerMetadataUpdateTransaction.getActiveSegmentCount

- docker/bookkeeper/entrypoint.sh
Removes the old autoRecoveryDaemonEnabled setting from Bookkeeper configuration before adding new setting
Fix issue 1464 wereby the autoRecoveryDaemonEnabled was added to the end of the configuration when the entrypoint script was rerun
Removes the old `autoRecoveryDaemonEnabled` setting from Bookkeeper configuration before adding the setting
Run entrypoint multiple times, check configuration to make sure only one `autoRecoveryDaemonEnabled` is in the configuration
> Issue 1464: Remove old autoRecoveryDaemonEnabled setting before adding new one

- controller/src/main/java/io/pravega/controller/server/rest/generated/api/ScopesApi.java
- controller/src/main/java/io/pravega/controller/server/rest/generated/api/ScopesApiService.java
- controller/src/main/java/io/pravega/controller/server/rest/generated/api/impl/ScopesApiServiceImpl.java
- controller/src/main/java/io/pravega/controller/server/rest/generated/model/ScaleMetadata.java
- controller/src/main/java/io/pravega/controller/server/rest/generated/model/ScalingEventList.java
- controller/src/main/java/io/pravega/controller/server/rest/generated/model/Segment.java
- controller/src/main/java/io/pravega/controller/server/rest/resources/StreamMetadataResourceImpl.java
- controller/src/main/java/io/pravega/controller/server/rest/v1/ApiV1.java
- controller/src/test/java/io/pravega/controller/rest/v1/StreamMetaDataTests.java
- docs/rest/restapis.md
- shared/controller-api/src/main/swagger/Controller.yaml
Addition of new REST API - getScalingEvents. Returns a list of scaling events in desired period of time.
Fixes #1361
Adds a new REST API implementation.
Unit Test/ Call the api using a rest client by starting standalone pravega cluster.
Note: Please do not review auto-generated files /rest/generated/*.
> Issue 1361: GetScalingEvents REST API

- segmentstore/server/src/main/java/io/pravega/segmentstore/server/logs/DataFrameBuilder.java
- segmentstore/server/src/main/java/io/pravega/segmentstore/server/logs/OperationProcessor.java
- segmentstore/server/src/test/java/io/pravega/segmentstore/server/logs/OperationMetadataUpdaterTests.java
- segmentstore/server/src/test/java/io/pravega/segmentstore/server/logs/OperationProcessorTests.java
- segmentstore/server/src/test/java/io/pravega/segmentstore/server/logs/TestLogAddress.java
Fixed a bug in OperationProcessor where it could fail an operation with an incorrect exception (and hence shutdown with failure) if it shut down while a DataFrame is in flight. Please refer to Issue #1470 for steps to reproduce the problem.
Fixes #1470.
Checks to see if the OperatioProcessor is shutting down when processing a commit from a DataFrame - if so, it aborts the callback, instead of throwing an AssertionError.
New unit test added to verify behavior.
> Issue 1470: (SegmentStore) OperationProcessor shutdown bug

- controller/src/main/java/io/pravega/controller/task/Stream/StreamMetadataTasks.java
- controller/src/test/java/io/pravega/controller/task/Stream/StreamMetadataTasksTest.java
We are ignoring if stream metadata tasks does not have request stream writer initialized. 
Instead we should throw the exception and let the caller handle it if it needs to. 
Fixes #1480
Instead of ignoring we will now throw the ScaleRequestNotEnabledException
All unit tests should pass
> Issue 1480: Throw exception if request stream writer is not set

- docker/compose/docker-compose-nfs-mount.yml
- docker/compose/docker-compose-nfs.yml
- docker/pravega/entrypoint.sh
- segmentstore/server/src/main/java/io/pravega/segmentstore/server/store/ServiceConfig.java
The segment store container was failing to start because the entrypoint script requires the value to be set as FS but the ServiceStarter is attempting to convert the string to an enumeration that expects FILESYSTEM. With this change, the string storagetype and env variable are same.
Fixes #1486.
Changes the env value that is checked to "FILESYSTEM" from "FS". Replaces the enumeration FILESYSTEM("FS") with FILESYSTEM("FILESYSTEM").
Change the env value and start the docker container.
> Issue 1486: Having consistent string representing storagetype enum and env variable

- segmentstore/server/host/src/main/java/io/pravega/segmentstore/server/host/handler/AppendProcessor.java
- segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/bookkeeper/Metrics.java
- shared/metrics/src/main/java/io/pravega/shared/MetricsNames.java
* Records the incoming event count per segment as a metric in the SegmentStore.
* Corrects the metric name for `WRITE_LATENCY`stats logger.
Fixes #1346.
Records new metric. 
Fixes existing bug.
Run Pravega and verify metric is recorded.
> Issue 1346: Record event counts per segment

- controller/src/main/java/io/pravega/controller/store/stream/PersistentStreamBase.java
- controller/src/main/java/io/pravega/controller/store/stream/StoreException.java
The retry-able trait in OperationNotAllowed was lost due to PR merge #1382
Reintroduced the exception with the retry-able trait to prevent regression.
Fixes #1492 
Reintroduced the exception with the retry-able trait to prevent regression.
Existing tests should pass
> Issue 1492: Renabling retryable trait for operation not allowed exception

- controller/src/test/java/io/pravega/controller/server/eventProcessor/ScaleRequestHandlerTest.java
The test, on local runs in the debugger seems to be taking 15 seconds on average.
Hence increasing the timeout to 30 seconds for travis as 20 seconds could be elapsing if travis vm is resource crunched during build. 
fixes #1490 
increases timeout to 30 seconds
unit test should not timeout
> Issue 1490: Sporadic test failure ScaleRequestHandlerTest > testScaleRequest 

- controller/src/test/java/io/pravega/controller/server/eventProcessor/ScaleRequestHandlerTest.java
The core issue was, in the test we wanted to run a failure scenario where request handler would eventually fail the request. 
To achieve this we passed a request whose processing would result in retryable exception which would be retried several times before failing.
With several retries, this could go upto few seconds. 
We have also been changing our retry duration and number of attempts which has a side effect on the runtime of this test.. 
Its better to give an input that results in a non-retryable exception in which case we will observe processing failure as intended without spending too much time.
So changed the input which should result in non-retryable failure, hence the test will finish faster and will not be impacted if retry attempts are changed …
> Issue1490: sporadic build failure because of ScaleRequestHandlerTest getting timedout

- segmentstore/server/src/main/java/io/pravega/segmentstore/server/reading/StreamSegmentReadIndex.java
- segmentstore/server/src/main/java/io/pravega/segmentstore/server/writer/StorageWriter.java
Fixed a sporadic bug that would happen very rarely during the builds. This is not a "steady-state" bug, rather something that would happen due to various components shutting down asynchronously - so it may only happen upon container shutdown.
* Added proper checks to StreamSegmentReadIndex.readDirect (closed, not recovery). This will throw into the SegmentAggregator (at the readDirect's callsite), it will bubble all the way up to the StorageWriter, which will handle it appropriately.
* Updated StorageWriter to ignore ObjectClosedExceptions (along CancellationExceptions) if it's already shutting down.
Fixes #1505.
Handles a special case.
Unfortunately I can't repro this with a unit test due to …
> Issue 1505: (SegmentStore) Sporadic build failure due to StorageWriter/ReadIndex shutdown

- controller/src/main/java/io/pravega/controller/server/rest/resources/StreamMetadataResourceImpl.java
- controller/src/test/java/io/pravega/controller/rest/v1/StreamMetaDataTests.java
* Fixes the logic in `StreamMetadataResourceImpl` to process the list of scale records in descending order.
* Fixes the test case in `StreamMetadataTests` for getting scale events accordingly. 
Fixes #1513 
Fixes the bug reported in #1513 .
Run controller unit tests.
> Issue 1513: REST API for scaling events should report the last event before "from" timestamp

- controller/src/test/java/io/pravega/controller/rest/v1/StreamMetaDataTests.java
* Eliminates an unused import in `StreamMetaDataTests`
* Adds spaces to fix the remaining checkstyle errors
Fixes #1523 
Fixes checkstyle errors.
There is no major change, it is jut eliminating an import and adding space around braces.
> Issue 1523: Master build is broken due to checkstyle errors

- test/system/src/main/java/io/pravega/test/system/framework/services/PravegaSegmentStoreService.java
TIer2 storage is by default set to In memory. Change it to HDFS.
To point TIER2_STORAGE to HDFS  in system tests.
Fixes #1540 .
> Issue 1540: Set pravegaservice.storageImplementation to HDFS

- docs/pravega-concepts.md
* Clarify ordering guarantees.
* Move architecture discussion to below introduction of API level concepts.
The ordering guarantees as stated were inaccurate. 
Fixes #1511
> Issue 1511: Fix ordering guarantees in the documentation.

- controller/src/main/java/io/pravega/controller/store/stream/PersistentStreamBase.java
- controller/src/test/java/io/pravega/controller/store/stream/StreamMetadataStoreTest.java
We first set state to Updating following by updating the configuration.
If controller fails after setting the state but before updating the configuration, the setting of state to Updating is not idempotent as it checks and processes only if original state is Active.
Fixes #1538
Allows `updateStream` to run if state is updating. 
unit test added
> Issue 1538: Make updateStream's state update idempotent

- controller/src/main/java/io/pravega/controller/store/stream/AbstractStreamMetadataStore.java
- controller/src/main/java/io/pravega/controller/store/stream/StreamMetadataStore.java
- controller/src/test/java/io/pravega/controller/store/stream/ZKStreamMetadataStoreTest.java
Corrects reporting of segment splits and merges metrics.
Fixes #1512 
Doesn't assume the reporting order of underlying controller API and counts splits/merges.
./gradlew startStandalone task generates few metrics in /tmp/csv folder
> Issue 1512: Fix segment splits and merges metrics

- common/src/main/java/io/pravega/common/cluster/Cluster.java
- common/src/main/java/io/pravega/common/cluster/ClusterException.java
- common/src/main/java/io/pravega/common/cluster/zkImpl/ClusterZKImpl.java
- controller/src/main/java/io/pravega/controller/fault/ControllerClusterListener.java
- controller/src/main/java/io/pravega/controller/fault/SegmentMonitorLeader.java
- controller/src/main/java/io/pravega/controller/server/ControllerService.java
* Creates a `ClusterException` class to create a scope for the exceptions the `Cluster` interface throws.
* Makes `ClusterException` unchecked to follow the pattern used with `StoreException`.
Fixes #1433 
Address the comments here:
https://github.com/pravega/pravega/pull/1334#discussion_r121228541
The implementation of cluster based on zookeeper has calls that throw a generic exception. This happens because the Curator lib throws a generic exception on errors. This pull request basically reduces the scope of the exception and transforms it into a `ClusterException`, which is a class created in this pull request.
As mentioned above, I have made `ClusterException` unchecked to follow the pattern used in …
> Issue 1433: Modify Cluster interface to return specific exceptions

- client/src/main/java/io/pravega/client/netty/impl/ClientConnection.java
- client/src/main/java/io/pravega/client/netty/impl/ClientConnectionInboundHandler.java
- client/src/main/java/io/pravega/client/netty/impl/ConnectionFactoryImpl.java
- client/src/main/java/io/pravega/client/segment/impl/AsyncSegmentInputStream.java
- client/src/main/java/io/pravega/client/segment/impl/AsyncSegmentInputStreamImpl.java
- client/src/main/java/io/pravega/client/segment/impl/SegmentInputStreamImpl.java
- client/src/test/java/io/pravega/client/segment/impl/AsyncSegmentInputStreamTest.java
- client/src/test/java/io/pravega/client/segment/impl/SegmentInputStreamTest.java
- common/src/main/java/io/pravega/common/concurrent/FutureHelpers.java
Change read requests to use the threadPool for retries rather than relying on the caller's thread.
Fixes #1477
Switches from using a ReadFuture to a standard completablefuture. This simplifies the calling code and lets the connection library be explicit about failures on send.
Some of the unit tests needed changes to verify the new behaviour. All pass.
> Issue 1477: Async read retries

- controller/src/main/java/io/pravega/controller/store/stream/VersionedTransactionData.java
- controller/src/main/java/io/pravega/controller/task/Stream/TxnSweeper.java
A txn in host index may still be present while the actual txn may have completed and hence removed.
Since txnSweeper simply tries to read txn data, it may get DataNotFoundException.
It should gracefully handle such exceptions and ignore txn ownership transfer in such cases.
TxnSweeper calls getTxnData for all txns found in the host index.
GetTxnData can throw TxnNotFound which this should handle gracefully.
It captures DataNotFound exceptions and in such cases cleans up host index (removeTxnFromIndex)
Fixes #1553 
all unit tests should pass
> Issue 1553: TxnSweeper should handle txnNotFound

- controller/src/main/java/io/pravega/controller/store/stream/ZKStoreHelper.java
- controller/src/main/java/io/pravega/controller/store/stream/ZKStream.java
* Corrects the definition of `activeTxRoot` to include scope.
A txn is created in the following path: `<active-tx-path>/<active-epoch>/<txn-metadata>`
In the case two different scopes both have a stream with the same name, then without this fix, their txns will get mixed up and epoch deletion logic will be affected. Txns on one stream might end up stalling scale on a different stream
Adds scope to active txn path for the stream. 
Fixes #1551.
all tests should pass
> Issue 1551: Active Txn path does not have scope

- test/system/src/test/java/io/pravega/test/system/ReadWithAutoScaleTest.java
* Fixes an issue in `ReadWithAutoScaleTest`
* Ensures we pass the right scope to client factory. 
* Refactored the code to reuse the scope in AbstractScaleTests, but with a different stream name.
Fix the incorrect scope being passed to the client factory.
Fixes #1565 
Update: System test passes with this change.
> Issue 1565: ensure we pass the right scope to client factory

- common/src/main/java/io/pravega/common/concurrent/ServiceHelpers.java
- segmentstore/server/src/main/java/io/pravega/segmentstore/server/store/StreamSegmentContainerRegistry.java
- segmentstore/server/src/test/java/io/pravega/segmentstore/server/store/StreamSegmentContainerRegistryTests.java
1. Fixed a bug in `StreamSegmentContainerRegistry` where it could erroneously fail a container registration request if that container has just been shut down. This was due to the fact that the internal de-registration happens in a callback which may be executed after the Future returned externally does. The solution provided handles all three possible cases: when a container fails during startup, when it shuts down (and results in failure or no failure) or when it fails while running.
2. Fixed a bug in `ServiceHelpers` where it could be possible that callbacks passed to onStop() would never execute in certain cases.
Fixes #1536.
* `StreamSegmentContainerRegistry`: waits for a previous de-registration to happen …
> Issue 1536: (SegmentStore) Container de-registration sporadic issues.

- segmentstore/storage/impl/src/test/java/io/pravega/segmentstore/storage/impl/IdempotentStorageTestBase.java
- segmentstore/storage/impl/src/test/java/io/pravega/segmentstore/storage/impl/extendeds3/ExtendedS3StorageTest.java
- segmentstore/storage/impl/src/test/java/io/pravega/segmentstore/storage/impl/filesystem/FileSystemStorageTest.java
* Moves `IdempotentStorageTestBase` to under `imply` from under `filesystem`.
* Rewords the comment on top of the `IdempotentStorageTestBase` class.
Fixes #1574 
Moves IdempotentStorageTestBase and rewords comment.
Visual inspection
> Issue 1574: Move IdempotentStorageTestBase and update comment.

- segmentstore/storage/impl/src/test/java/io/pravega/segmentstore/storage/impl/bookkeeper/BookKeeperLogTests.java
Fixed a unit test bug in BookKeeperLogTests where it would incorrectly fail the test if the detected exception was a general write failure (which could very well be the case). 
The type of exception thrown for the first failure is less important (`DataLogNotAvailableException` vs `WriteFailureException`) than the fact that the `BookKeeperLog` auto-closes and properly cancels the remaining writes - that is being tested in the subsequent checks in the test.
Fixes #1509.
Updates the unit test to accept two types of exceptions as valid.
Unit test must pass.
> Issue 1509: (SegmentStore) Fixed spurious bug in BookKeeperLogTests

- segmentstore/server/src/main/java/io/pravega/segmentstore/server/reading/ContainerReadIndex.java
Fixed a bug in ContainerReadIndex where it would erroneously report ObjectClosedException in a corner case, thus failing an already committed operation.
Scenario:
- Consider a Transaction segment T1, with an Append/Seal and a Merge in the same batch of operations.
- These operations are written to Tier1, committed to in-memory metadata.
- Since an Append/Seal is involved, the ReadIndex will need to trigger future reads (if any) for T1
- However, if the Storage Writer is fast enough (which can happen in unit tests where everything is in memory), it could already process the merge, and thus close the ReadIndex for T1.
- In this case, it is possible that a pointer to T1's ReadIndex is obtained prior to this merge, but triggerFutureReads() is invoked after the …
> Issue 1525: (SegmentStore) Fixed spurious ReadIndex merge bug

- controller/src/main/java/io/pravega/controller/server/eventProcessor/ControllerEventProcessors.java
- controller/src/main/java/io/pravega/controller/store/stream/PersistentStreamBase.java
***Note This CL contains no functional changes***
Removes unnecessary anonymous future supplier.
Similar to #1155 this was spurred by eclipse's poor generic inference. Nevertheless, it is cleaner.
Fixes #1589 
Removes unneeded code.
This should have no effects what-so-ever.
> Issue 1589: Remove unneeded anonymous future supplier

- segmentstore/server/src/main/java/io/pravega/segmentstore/server/SegmentContainerRegistry.java
- segmentstore/server/src/main/java/io/pravega/segmentstore/server/store/StreamSegmentContainerRegistry.java
- segmentstore/server/src/test/java/io/pravega/segmentstore/server/store/StreamSegmentContainerRegistryTests.java
- Fixed a bug in `StreamSegmentContainerRegistry.getContainer()` that could incorrectly not throw `ContainerNotFoundException` if invoked with a container id for a container that was just shut down. This was changed to check if the container is currently in the process of shutting down (or already terminated), in which case it simply throws the exception.
- Removed `getRegisteredContainerIds` from `SegmentContainerRegistry` (and its implementing class - this is not used.
Fixes #1591.
Verifies if container is currently shutting down or shut down. If so, it throws an exception.
Unit test updated to verify this particular scenario.
> Issue 1591: (SegmentStore) Fixed bug in StreamSegmentContainerRegistry.getContainer

- controller/src/main/java/io/pravega/controller/server/eventProcessor/CommitEventProcessor.java
- controller/src/main/java/io/pravega/controller/store/stream/AbstractStreamMetadataStore.java
- controller/src/main/java/io/pravega/controller/store/stream/PersistentStreamBase.java
- controller/src/main/java/io/pravega/controller/store/stream/Stream.java
- controller/src/main/java/io/pravega/controller/store/stream/StreamMetadataStore.java
- controller/src/main/java/io/pravega/controller/store/stream/ZKStream.java
- controller/src/main/java/io/pravega/controller/task/Stream/StreamMetadataTasks.java
Once rpc call for manual scale is received on ControllerService, it calls into streamMetadataTask.manual scale method. 
Following is how manual scale is performed by streamMetadataTasks:
1. post scale request in Request event-processor's stream. 
2. start scale by performing the "store.startScale" step where new segments are created in the segment table followed by new epoch created in the history table. It also sets the stream state to 'scaling'. 
3. rest of the steps of scale operation are performed by the event in the stream. 
4. now the manual scale thread checks the stream state to see when it changes from scaling. 
(4) is done in a tight loop using FutureHelpers.loop without any delays. 
This leads to hammering of the store. We also set operation context …
> Issue 1584: Manual scale hammers store to check if scale has completed or not 

- client/src/main/java/io/pravega/client/stream/impl/ControllerResolverFactory.java
- client/src/test/java/io/pravega/client/stream/impl/ControllerImplLBTest.java
Updated the gRPC nameresolver to retry DNS resolution on network failures. Also attempting DNS resolution at regular intervals to detect change in address (when dynamic DNS is used)
Also addressed comments from PR #1534 
Fixes #1531 
Attempts DNS resolution on gRPC network failures and also at regular intervals (retained the earlier 2 mins scheduler used for controller discovery)
Existing ControllerImplLBTest.java covers network failure scenarios. Manually tested failure handling due to DNS propagation delays. Added unit tests for Controller URIs using IP addresses.
> Issue 1531: Controller gRPC client to retry DNS resolution on failures

- client/src/main/java/io/pravega/client/segment/impl/AsyncSegmentInputStreamImpl.java
AsyncSegmentInputStreamImpl closes ClientConnection in case of error based on the `ReplyProcessor` call backs.  It performs retries in case of exceptions during
* Fetching SegmentEndpoint from controller
* Establishing a connection to pravega node.
* Sending a read for the segment.
This change ensures we close the connection in case of error while establishing connection to pravega node, so that in the next retry we try to re-establish the connection to the pravega node (obtained from the controller)
Fixes #1582 
Close the connection in case of errors while establishing connection to pravega node.
Update: With this change MultiReaderWriterWithFailOverTest passed on my …
> Issue 1582: Update reader's error handling to handle failure to connect to Pravega node.

- client/src/main/java/io/pravega/client/stream/impl/Orderer.java
- client/src/test/java/io/pravega/client/stream/impl/OrdererTest.java
Fix use of negative in modulo operation.
Fixes #1596. Operator was returning values in a round-robin manner. This was done with a counter and a modulo operator. This broke when the integer wrapped around and the result became negative. 
Uses MathHelpers.abs to avoid the negative value. 
The stress tests should no longer fail with ArrayIndexOutOfBounds
> Issue 1596: Fix use of negative in modulo operation.

- test/system/src/main/java/io/pravega/test/system/framework/services/PravegaSegmentStoreService.java
- Sets the configuration through environment variables as the script `entrypoint.sh` uses in production deployment.
- Overrides defaults using `PRAVEGA_SEGMENTSTORE_OPTS` as required  specifically for system tests.
To ensure system test runs resembles the production runs.
To ensure that system tests are able to mount NFS directory when the tested with filesystem as tier2.
- Sets the configuration through environment variables as the script `entrypoint.sh` uses in production deployment.
- Overrides defaults using `PRAVEGA_SEGMENTSTORE_OPTS` as required  specifically for system tests.
Segmentstore comes up with the configured values.
> Issue 1580:  System tests should follow the same path through entrypoint.sh as production deployment

- client/src/main/java/io/pravega/client/segment/impl/SegmentMetadataClientImpl.java
- client/src/main/java/io/pravega/client/segment/impl/SegmentOutputStreamImpl.java
- client/src/test/java/io/pravega/client/segment/impl/SegmentMetadataClientTest.java
- common/src/main/java/io/pravega/common/ExceptionHelpers.java
- common/src/main/java/io/pravega/common/concurrent/FutureHelpers.java
- common/src/main/java/io/pravega/common/util/Retry.java
Upon error clear the connection before re-connecting so that any retries have the opportunity to go to a different host.
Fixes #1601. There was a case where ConnectionFailedException was being set on the future for the connection establishment, but the connection was not replaced when getConnection() was retried.
Rather than only catching known exceptions and assuming that exceptions are only wrapped once, it makes sure that all possible exception paths result in connectionClose being called. 
Run the System tests.
> Issue 1601: Bugfix for error handling

- controller/src/main/java/io/pravega/controller/fault/ControllerClusterListener.java
- controller/src/main/java/io/pravega/controller/server/ControllerServiceStarter.java
- controller/src/test/java/io/pravega/controller/fault/ControllerClusterListenerTest.java
```
Caused by: java.lang.NullPointerException: null
at io.pravega.controller.fault.ControllerClusterListener.lambda$null$10(ControllerClusterListener.java:136)
at io.pravega.common.concurrent.FutureHelpers.lambda$delayedFuture$24(FutureHelpers.java:458)
at java.util.concurrent.CompletableFuture.uniCompose(CompletableFuture.java:952)
... 10 common frames omitted
```
which is caused by a sweeper being null in this block of code:
```
private CompletableFuture<Void> sweepAll(Supplier<Set<String>> processes) {
return FutureHelpers.allOf(sweepers.stream().map(sweeper -> RetryHelper.withIndefiniteRetriesAsync(() -> {
if (!sweeper.isReady()) {
log.trace("sweeper not ready, retrying with exponential backoff");
throw new RuntimeException("sweeper not ready");
}
return …
```
> Issue1617: NullPointerExceptions from ControllerClusterListener

- build.gradle
- controller/src/test/java/io/pravega/controller/rest/v1/PingTest.java
Updated the PingTest to remove unnecessary jersey-netty dependency
Fixes #1203 
Update code to remove jersey-netty dependency
PingTest should continue to pass
> Issue 1203: Remove jersey-netty dependency from test code

- client/src/main/java/io/pravega/client/stream/impl/ControllerImpl.java
- client/src/test/java/io/pravega/client/stream/impl/ControllerImplTest.java
Increased keepalive timeout to 6 minutes from 1 minute. The earlier 1 minute keep-alives were being rejected by the gRPC server since it was less than the permissible server keep-alive limit of 5 minutes. 
Fixes #1621 
Increases keepalive timeout
Added test case to simulate long running RPC with different keep-alive timeout configuration
> Issue 1621: Increased gRPC client keepalive timeout to 6 minutes

- controller/src/main/java/io/pravega/controller/store/stream/AbstractStreamMetadataStore.java
`AbstractStreammetadataStore` has a `withCompletion` method that employs visitor pattern for futures so that callers do not perform any processing on store's executor.
However, along with it, it also logs all exceptions at log level ERROR.
The log level error should be callers discretion because they know if the error is handled or not.
Remove unnecessary log.error level messages.
Fixes #1630 
It removes logging of all errors in the store.. Logging is callers responsibility. 
All existing tests should pass
> Issue 1630: Remove unnecessary error level logging for all exceptions encountered by the StreamStore

- controller/src/main/java/io/pravega/controller/task/Stream/StreamTransactionMetadataTasks.java
- controller/src/test/java/io/pravega/controller/mocks/SegmentHelperMock.java
- controller/src/test/java/io/pravega/controller/task/Stream/StreamTransactionMetadataTasksTest.java
Currently, after creating a transaction record in controller's metadata, if the subsequent step of creating transaction segments fails, the new transaction does not get added to timeout service. This may cause the transaction to not abort on its timeout expiry. Modified the transaction creation method to ensure that partially created transactions get added to in-memory timeout service.
Fixes #1640 
Adds a newly created transaction to in-memory timeout service even if creation of few transaction segments fails.
All existing test cases should succeed. Added a new test case to test whether partially created transactions are added to timeout service.
> Issue 1640: Ensuring that partially created txns are aborted on lease expiry

- test/system/src/test/java/io/pravega/test/system/AbstractFailoverTests.java
- test/system/src/test/java/io/pravega/test/system/ReadWriteAndAutoScaleWithFailoverTest.java
- test/system/src/test/java/io/pravega/test/system/ReadWriteAndScaleWithFailoverTest.java
Passes the correct stream name to check if auto scaling is triggered.
getCurrentSegments is checked for wrong stream name in waitForScaling().
Fixes #1655 
> Issue 1655: Correct the stream name in waitForScaling() of ReadWriteAndAutoScaleWithFailoverTest

- client/src/main/java/io/pravega/client/stream/impl/CheckpointState.java
- client/src/main/java/io/pravega/client/stream/impl/EventStreamReaderImpl.java
- client/src/main/java/io/pravega/client/stream/impl/ReaderGroupState.java
- client/src/main/java/io/pravega/client/stream/impl/ReaderGroupStateManager.java
- client/src/test/java/io/pravega/client/stream/impl/CheckpointStateTest.java
- client/src/test/java/io/pravega/client/stream/impl/EventStreamReaderTest.java
- client/src/test/java/io/pravega/client/stream/impl/ReaderGroupStateManagerTest.java
Fix a race condition, that could result in an inconsistent checkpoint.
Fixes #1623. It was previously possible to have a checkpoint be inconsistent as a result of a race condition with a concurrent rebalance operation, because the ReaderGroupStateManager did not use its ability to perform a compare and set to enforce the invariant. 
ReaderGroupStateManager now performs checks when releasing and acquiring segments to make sure there is not a pending checkpoint for its reader. 
Two new tests were created that failed before the change and now pass. All existing tests should pass.
> Issue 1623: Use stateSynchronizer's consistency to enforce the consistency of checkpoints

- client/src/main/java/io/pravega/client/netty/impl/ClientConnectionInboundHandler.java
- client/src/main/java/io/pravega/client/segment/impl/AsyncSegmentInputStreamImpl.java
- client/src/main/java/io/pravega/client/segment/impl/SegmentMetadataClientImpl.java
- client/src/main/java/io/pravega/client/segment/impl/SegmentOutputStreamImpl.java
- client/src/test/java/io/pravega/client/segment/impl/SegmentOutputStreamTest.java
- client/src/test/java/io/pravega/client/stream/mock/MockConnectionFactoryImpl.java
- common/src/main/java/io/pravega/common/util/Retry.java
- segmentstore/server/host/src/main/java/io/pravega/segmentstore/server/host/handler/AppendProcessor.java
- segmentstore/server/host/src/main/java/io/pravega/segmentstore/server/host/handler/PravegaRequestProcessor.java
* Ensures SegmentOutputStream attempts to setup connection on netty connection errors.
* Additional logs to simplify debugging.
* Uses separate promises for each send on reconnect.  This ensures the caller will be notified on failure.
* Handles ContainerNotFoundException.
Fixes #1657
In case of errors during the net connection, ensures EventStreamWriter/SegmentOutputStreamImpl attempts to re-connect.
> Issue 1657: Bugfix - ensure EventStreamWriter retries on netty connection errors.

- deployment/aws/variable.tf
Delete default AWS region
Enter by user would be a better choice, and also align with installation menu.
sudo terraform apply
> Issue 1299: Delete default AWS region in pravega installer

- client/src/main/java/io/pravega/client/segment/impl/SegmentOutputStreamImpl.java
- client/src/test/java/io/pravega/client/segment/impl/SegmentOutputStreamTest.java
Fixes a race in SegmentOutputStreamImpl where if the connection failed after flush was called but reconnected before the future was used flush could get stuck retrying the connection even though it is connected and there are no events inflight.
Fix #1682. This should allow the system tests to pass.
Changes the CompletableFuture on empty inflight back to a reusable latch and does the reconnecting in the background thread pool. This simplifies the handling, and eliminates the possibility that there could be an exception left set on the future, as the latch is single purpose: tacking if their is anything inflight rather and trying to do two jobs as the future was.
Added a new test that reproduces …
> Issue 1682: Fix race between flush and connection failure

- deployment/aws/installer/entry_point_template.yml
- deployment/aws/installer/roles/install-hosts/tasks/main.yml
* Changes of the register IP address of controller for AWS deployment.
To assign only one ip address to the controller
Fixes #1699 
Deploying on aws cluster
> Issue 1699: Segmentstore publishedIPAddress is set to CONTROLLERNODE on AWS

- segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/extendeds3/ExtendedS3Storage.java
- segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/extendeds3/ExtendedS3StorageConfig.java
- segmentstore/storage/impl/src/test/java/io/pravega/segmentstore/storage/impl/extendeds3/ExtendedS3StorageTest.java
- Add code for put-if-absent based on a config setting.
This fixes #1638. 
Adds `setIfNoneMatch` to the `putObject` header, based on a config value.
> Issue 1638: Implement put-if-absent for ExtendedS3Storage which can be overridden with a config

- segmentstore/server/src/main/java/io/pravega/segmentstore/server/OperationLog.java
- segmentstore/server/src/main/java/io/pravega/segmentstore/server/containers/StreamSegmentContainer.java
- segmentstore/server/src/main/java/io/pravega/segmentstore/server/containers/StreamSegmentMapper.java
- segmentstore/server/src/main/java/io/pravega/segmentstore/server/logs/DurableLog.java
- segmentstore/server/src/main/java/io/pravega/segmentstore/server/logs/OperationProcessor.java
- segmentstore/server/src/main/java/io/pravega/segmentstore/server/logs/operations/CompletableOperation.java
- segmentstore/server/src/main/java/io/pravega/segmentstore/server/store/StreamSegmentService.java
- segmentstore/server/src/test/java/io/pravega/segmentstore/server/containers/StreamSegmentMapperTests.java
- segmentstore/server/src/test/java/io/pravega/segmentstore/server/logs/DurableLogTests.java
- segmentstore/server/src/test/java/io/pravega/segmentstore/server/logs/OperationLogTestBase.java
- segmentstore/server/src/test/java/io/pravega/segmentstore/server/logs/OperationProcessorTests.java
- segmentstore/server/src/test/java/io/pravega/segmentstore/server/logs/operations/CompletableOperationTests.java
Fixed a bug in SegmentStore where it would be possible to write two or more events received in a short timespan, in a different order than received from the caller. Please refer to #1659 for more details.
- `StreamSegmentService`: refactored all calls so they synchronously invoke the underlying Container's code vs via a CompletableFuture callback.
- `StreamSegmentMapper`: properly queueing up pending requests in the correct order (in which they were received) and then invoking them in the same order. This makes the invocation order predictable and no longer keeps us at the mercy of the JVM scheduler.
- `OperationLog/DurableLog`: add() returns a CompletableFuture<Void> since nobody cared about the result anyway. This enabled the simplification of some calls, thus …
> Issue 1659: (SegmentStore) BugFix for possible out-of order writes.

- controller/src/main/java/io/pravega/controller/server/eventProcessor/AutoScaleRequestHandler.java
- controller/src/test/java/io/pravega/controller/server/eventProcessor/ScaleRequestHandlerTest.java
- segmentstore/server/host/src/main/java/io/pravega/segmentstore/server/host/stat/AutoScaleProcessor.java
- segmentstore/server/host/src/test/java/io/pravega/segmentstore/server/host/stat/AutoScaleProcessorTest.java
The auto scale processor can request for number of splits as 1 if traffic/target Rate is between 1 and 2. 
Fixes issue 1704
added additional check on controller and segment store to use numOfSplits as minimum 2
unit tests added/updated.
> Issue 1704: Controller can recreate segment with identical range for scale up if traffic is less than double of target rate for over 10 minutes

- client/src/main/java/io/pravega/client/segment/impl/SegmentOutputStreamImpl.java
- client/src/test/java/io/pravega/client/segment/impl/SegmentOutputStreamTest.java
- common/src/main/java/io/pravega/common/util/ReusableFutureLatch.java
- common/src/main/java/io/pravega/common/util/ReusableLatch.java
- common/src/test/java/io/pravega/common/util/ReusableFutureLatchTests.java
- common/src/test/java/io/pravega/common/util/ReusableLatchTests.java
* Fixes a race condition described in #1697. 
* Changes the reconnect logic to be asynchronous to avoid tying up a thread and allow it to maintain exponential backoff even with after connection re-establishment.
Fixes #1697 
Creates a new class ReusableAsyncLatch which abstracts out the concept of having multiple futures waiting on a single state transition, and ensuring that one of them triggers the process that will result in the transition.
New tests are added to cover the new class and to reproduce the race condition. The later of which fails against master and is passing here.
> Issue 1697: Change client background reconnect logic to be asynchronous 

- segmentstore/server/src/main/java/io/pravega/segmentstore/server/reading/CacheManager.java
- segmentstore/server/src/test/java/io/pravega/segmentstore/server/reading/CacheManagerTests.java
Fixed a bug where the CacheManager would throw errors (harmless) if it has registered clients that have no data in them.
Fixes #1720.
CacheManager takes no action if either:
1. There are no registered clients (read indices) - this is pre-existing.
2. There are clients, but they have no data.
Added new unit test to verify scenario.
> Issue 1720: (SegmentStore) BugFix for CacheManager when Read Indices are empty

- common/src/main/java/io/pravega/common/SimpleMovingAverage.java
- common/src/test/java/io/pravega/common/SimpleMovingAverageTests.java
- segmentstore/server/src/main/java/io/pravega/segmentstore/server/logs/DataFrame.java
- segmentstore/server/src/main/java/io/pravega/segmentstore/server/logs/DataFrameBuilder.java
- segmentstore/server/src/main/java/io/pravega/segmentstore/server/logs/DataFrameOutputStream.java
- segmentstore/server/src/main/java/io/pravega/segmentstore/server/logs/DataFrameReader.java
- segmentstore/server/src/test/java/io/pravega/segmentstore/server/logs/DataFrameBuilderTests.java
- segmentstore/server/src/test/java/io/pravega/segmentstore/server/logs/DataFrameOutputStreamTests.java
- segmentstore/server/src/test/java/io/pravega/segmentstore/server/logs/DataFrameTests.java
- segmentstore/server/src/test/java/io/pravega/segmentstore/server/logs/DurableLogTests.java
Previously, every time we create a `DataFrame` a new 1MB buffer is allocated, regardless of how big the frame ends up being (whether 1KB or 1MB). This 1MB buffer is pointed to as long as the `DataFrame` exists, which is only "released" after it is written to BookKeeper. In case BookKeeper is backed up, a lot of these frames can exist at any given times, hence a lot of 1MB buffers.
In this change, we attempt to improve the situation by reusing the previously used buffer, if it still has capacity. Main points:
- We keep track of the length of the last 10 built `DataFrames`.
- DataFrames already take a `ByteArraySegment` as input. The `DataFrameOutputStream` has been changed to return a sub-segment of a physical byte array vs a `ByteArraySegment` that wraps a new …
> Issue 1716: (SegmentStore) Reuse physical buffers when creating new DataFrames

- controller/src/main/java/io/pravega/controller/eventProcessor/impl/EventProcessorCell.java
- controller/src/test/java/io/pravega/controller/eventProcessor/impl/EventProcessorTest.java
In the test we mock clientFactory for creating readers. 
We create 3 event processors but only 1 reader. 
ClientFactory mock returns a sequenceAnswer which only has one reader. This means two event processors are created with null reader. hence NPE during shutdown.  
Fixes issue 1706
We fix the test to create 3 readers. 
Also added precondition checks in eventprocessorCell contructor to check for null references. 
Unit test should pass consistently
> Issue 1706: Sporadic build failure: Test passes null readers to eventprocessor whereby causing NPE during shutdown

- segmentstore/server/src/test/java/io/pravega/segmentstore/server/containers/StreamSegmentMapperTests.java
Simplifying unit test so that it may pass on Jenkins
Fixes #1718.
Simplifies a unit test.
Unit test must pass. Build must pass on jenkins.
> Issue 1718: Fixing failing unit test on Jenkins

- segmentstore/server/src/test/java/io/pravega/segmentstore/server/containers/StreamSegmentContainerTests.java
Fixed a sporadically failing unit test. The test would fail because of two operations (append/seal) that were triggered, but were not awaited upon. Sometimes they would execute quickly enough for their effects to apply, but sometimes not.
Fixes #1727.
Nothing new.
Unit test must pass consistently.
> Issue 1727: Fix unit test StreamSegmentContainerMetadata.testMetadataCleanup

- common/src/main/java/io/pravega/common/util/Retry.java
Ensure we do not sleep after the last retry.
Fixes #1740 
> Issue 1740 : No need to sleep if we are on the last attempt of the retry.

- test/system/src/test/java/io/pravega/test/system/BookkeeperTest.java
- test/system/src/test/java/io/pravega/test/system/PravegaControllerTest.java
- test/system/src/test/java/io/pravega/test/system/PravegaSegmentStoreTest.java
- test/system/src/test/java/io/pravega/test/system/PravegaTest.java
- test/system/src/test/java/io/pravega/test/system/ZookeeperTest.java
Pravega Test (creates stream, writes, reads from a stream) is not getting timed out and stuck forever in cases like stream creation. Adding timeout to the pravega test and other tests where the timeout is missing.
Add missing timeouts
Fixes #1743 
> Issue 1743: Add the appropriate missing test timeouts  in system tests

- test/system/src/main/java/io/pravega/test/system/framework/LoginClient.java
- test/system/src/main/java/io/pravega/test/system/framework/marathon/AuthEnabledMarathonClient.java
- test/system/src/main/java/io/pravega/test/system/framework/metronome/AuthEnabledMetronomeClient.java
Update the auth mechanism used inside system tests to handle deployment in test cluster.
Fix 1751.
Basic authentication is disabled on the test cluster based on mesos, this change ensures system tests can interact with the newer cluster.
> Issue 1751 : Update authentication for system tests

- controller/src/main/java/io/pravega/controller/store/stream/PersistentStreamBase.java
- controller/src/main/java/io/pravega/controller/task/Stream/StreamMetadataTasks.java
- controller/src/test/java/io/pravega/controller/server/v1/ControllerServiceTest.java
- controller/src/test/java/io/pravega/controller/store/stream/StreamMetadataStoreTest.java
- controller/src/test/java/io/pravega/controller/store/stream/ZKStreamMetadataStoreTest.java
- controller/src/test/java/io/pravega/controller/store/stream/ZkStreamTest.java
- controller/src/test/java/io/pravega/controller/task/Stream/StreamMetadataTasksTest.java
- controller/src/test/java/io/pravega/controller/task/TaskTest.java
In manual scale we did two steps before returning to the caller -->
1. create new segments in metadata store
2. set stream state to scaling
The scale operation is picked and run concurrently with manual scale which checks if scale has been started (runonlyifstarted) and if so, it moved to subsequent steps like creating segments in SSS and adding partial record to history table. 
Since both these could happen concurrently, there was a race between setting state to SCALING and updating history table with partial record which expects state to be SCALING.
Hence we sporadically got Illegal State exception thrown by addPartialRecordToHistoryTable. 
This had few other problems: If controller instance handling manual scale crashed after creating the segments but before …
> Issue 1726: System test and sporadic build failure with timeouts:  Manual scale is stuck and never completes. 

- client/src/main/java/io/pravega/client/segment/impl/SegmentOutputStreamImpl.java
- client/src/main/java/io/pravega/client/stream/impl/ClientFactoryImpl.java
- client/src/main/java/io/pravega/client/stream/impl/EventStreamWriterImpl.java
- client/src/test/java/io/pravega/client/stream/impl/EventStreamWriterTest.java
- common/src/main/java/io/pravega/common/concurrent/ExecutorServiceHelpers.java
Moves the retransmission of inflight events from being performed on the connection threadpool to a dedicated on to avoid tying up the main pool.
Fixes #1747
Creates a new threadpool in the client that by default has 0 threads and can, on demand have up to one per stream.
System tests should not longer lock up with a constant write count.
> Issue 1747: Move retransmission on segment sealed to a background threadpool

- test/system/src/test/java/io/pravega/test/system/AbstractFailoverTests.java
- test/system/src/test/java/io/pravega/test/system/MultiReaderTxnWriterWithFailoverTest.java
- test/system/src/test/java/io/pravega/test/system/MultiReaderWriterWithFailOverTest.java
- test/system/src/test/java/io/pravega/test/system/ReadWriteAndAutoScaleWithFailoverTest.java
- test/system/src/test/java/io/pravega/test/system/ReadWriteAndScaleWithFailoverTest.java
Fixing the improper license format in the system tests.
The license header format is broken in some of the system tests.
Fixes #1758 
No change in code logic . Tests should run as they are now.
> Issue 1758: Correct broken license header format

- segmentstore/server/src/main/java/io/pravega/segmentstore/server/containers/StreamSegmentContainerMetadata.java
- segmentstore/server/src/main/java/io/pravega/segmentstore/server/logs/DurableLog.java
- segmentstore/server/src/main/java/io/pravega/segmentstore/server/logs/operations/MergeTransactionOperation.java
- segmentstore/server/src/test/java/io/pravega/segmentstore/server/containers/StreamSegmentContainerMetadataTests.java
- segmentstore/server/src/test/java/io/pravega/segmentstore/server/logs/DurableLogTests.java
Fixed a bug in StreamSegmentContainerMetadata where it would be possible to evict a Parent SegmentMetadata while at least one of its Transaction Metadatas was still active.
- This is possible if the `getEvictionCandidates` needs to trim off the result due to a max cap restriction (we are instructed to only clean up so many items at once)
- Repro case:
- We have Segment A with N transactions (A1->AN) 
- We have an eviction cap of M <= N
- A and A1..AN are all eligible for eviction, and A is not the Most Recently Used 
- Since we can only evict M (M <= N) and have N+1 segments eligible, we will only evict the least recently used M. In this case, this includes segment A and N-1 of its transactions, leaving one transaction orphaned in the metadata.
- This would not …
> Issue 1753: (SegmentStore) BugFix for Orphan Transaction Metadata

- shared/src/main/java/io/pravega/shared/NameUtils.java
- shared/src/test/java/io/pravega/shared/NameUtilsTest.java
Allows periods and hyphens in stream names.
Fixes #1363 
Adds these two characters to the supported regex.
All tests should pass. Code was also searched to make sure there weren't any other places duplicating the verification.
> Issue 1363: Allow period and hyphen in stream names

- client/src/main/java/io/pravega/client/netty/impl/ConnectionFactoryImpl.java
System property `pravega.client.internal.threadpool.size` can now be used to configure clients internal thread pool size.  This thread pool is used to handle connection failures / reconnects and handle processing of segment sealed exception.
Make the client's internal thread pool size configurable.
Fixes 1521
> Issue1521 : Create a system property to configure client's internal thread pool size

- build.gradle
- shared/src/test/java/io/pravega/shared/NameUtilsTest.java
We are using a try-catch block to spot expected exceptions in NameUtilsTest. I changed the test code to use AssertExtensions for better consistency.
Fix #1762 
Test if the name utilities methods work normally. The code I edited use the test common utilites in `io.pravega.test.common` package to avoid the repeat of try-catch block.
Run the test.
> Issue 1762: Use AssertExtensions utility in NameUtilsTest

- client/src/main/java/io/pravega/client/stream/ReaderGroupMetrics.java
- common/src/main/java/io/pravega/common/lang/ProcessStarter.java
- test/integration/src/main/java/io/pravega/test/integration/selftest/adapters/ExternalAdapter.java
- test/integration/src/main/java/io/pravega/test/integration/selftest/adapters/InProcessListenerWithRealStoreAdapter.java
- test/integration/src/main/java/io/pravega/test/integration/selftest/adapters/OutOfProcessAdapter.java
The license header format is incorrect in few files Process Starter.java , InProcessListenerWithRealStoreAdapter.java, OutOfProcessAdapter.java and ExternalAdapter.java .
There is no return value for ` long unreadBytes();` in ReaderGroupMetrics.java .
Resolve some build errors.  
Fixes #1770 
> Issue 1770: Fixing license header format and javadoc build errors

- test/system/src/test/java/io/pravega/test/system/MultiReaderWriterWithFailOverTest.java
- Changes executor used by controller client
- Adds a thread to the pool to handle controller-related retries
Fixes #1775
@ Cleanup annotation is used close the clientFactory which ensures ConnectionFactory.close() is invoked after all the operations within the test. Removed the try with resources statement.
Verified it by running system tests.
> Issue 1775: Ensure that thread pool is available for controller operations in multireaderwriterwithfailovertest

- test/system/src/test/java/io/pravega/test/system/AbstractFailoverTests.java
- test/system/src/test/java/io/pravega/test/system/ReadWriteAndAutoScaleWithFailoverTest.java
- test/system/src/test/java/io/pravega/test/system/ReadWriteAndScaleWithFailoverTest.java
* AbstractFailoverTests(`ReadWriteAndAutoScaleWithFailoverTest `and `ReadWriteAndScaleWithFailoverTest`) close ClientFactory( internally ConnectionFactory) in case of an exception before stopping the reader and writer threads. This causes some log noise. The change intends to reduce this noise.
Fixes #1782
- Stop readers and writers before closing connectionFactory
- Ensure over all execution of the the test and its setup methods are time limited to 15 mins.
- reduced log noise after test execution.
> Issue 1782: Ensure we close connectionFactory during the tear down of AbstractFailoverTest

- controller/src/main/java/io/pravega/controller/server/SegmentHelper.java
* Handles `noSuchSegment` response from the segment store for aborts
Fixes issue 1769
We fixed a similar issue in commitTransaction but missed fixing this for abort transaction. 
If abortTransaction returns noSuchSegment, controller should be idempotent to it. 
All existing tests should pass
> Issue 1769: Abort transaction is not idempotent if segment is already deleted on the segment store

- controller/src/main/java/io/pravega/controller/server/SegmentHelper.java
Create transaction is not idempotent wrt segmentAlreadyExists response. 
Fixes issue 1802
Treats segmentAlreadyExists as a successful response. 
All existing tests should pass, system tests should not observe this issue.
> Issue 1802: CreateTransaction does not handle segmentAlreadyExists response

- test/system/src/test/java/io/pravega/test/system/MultiReaderTxnWriterWithFailoverTest.java
* Fixes the asynchronous loop predicate to ping an ongoing txn, which is currently incorrect. The value is initialized to false and the loop is supposed to leave when it changes to true, so the logic needs to be the opposite of what we currently have.
Fixes #1800 
Fixes the predicate for an asynchronous loop in a system test case.
> Issue 1800: Loop predicate for pinging in MultiReaderTxnWriterWithFailoverTest 

- test/system/src/test/java/io/pravega/test/system/AbstractFailoverTests.java
- test/system/src/test/java/io/pravega/test/system/AbstractScaleTests.java
- test/system/src/test/java/io/pravega/test/system/ControllerFailoverTest.java
- test/system/src/test/java/io/pravega/test/system/ControllerRestApiTest.java
- test/system/src/test/java/io/pravega/test/system/MultiControllerTest.java
- test/system/src/test/java/io/pravega/test/system/MultiReaderTxnWriterWithFailoverTest.java
- test/system/src/test/java/io/pravega/test/system/MultiReaderWriterWithFailOverTest.java
- test/system/src/test/java/io/pravega/test/system/PravegaTest.java
- test/system/src/test/java/io/pravega/test/system/ReadWriteAndAutoScaleWithFailoverTest.java
- test/system/src/test/java/io/pravega/test/system/ReadWriteAndScaleWithFailoverTest.java
- The retry count for controller client is 1 . It needs to be increased since with the current configuration retry happens within 1 ms.
- Reduces the number of Additional writers created for ReadWriteAndAutoScaleWithFailoverTest. There is no need to have a total of 8 writers to trigger autoscale. 
Fixes #1794 
Fixes #1794 and reduces the number of additional writers to trigger autoscale.
Verified that system tests pass.
> Issue 1794: Update controller client retry configuration for failover tests.

- test/system/src/test/java/io/pravega/test/system/MultiReaderTxnWriterWithFailoverTest.java
* Changes exception handling for creating a txn.
* Removes create txn method.
* Adds error state references for reading and writing.
Fixes #1798 
Fixes exception handling in `MultiReaderTxnWriterWithFailoverTest`
> Issue 1798: Exception handling in MultiReaderTxnWriterWithFailoverTest 

- segmentstore/server/host/src/main/java/io/pravega/segmentstore/server/host/stat/AutoScaleProcessor.java
- segmentstore/server/host/src/test/java/io/pravega/segmentstore/server/host/stat/AutoScaleProcessorTest.java
A segment, for which traffic has not been seen for a while is expired from the cache in autoscale processor.
This results in a scale down request being sent for it. We use the same triggerScaleDown method for this purpose. This method, after posting the scale down request for a segment, updates the last posted timestamp for the segment in the cache.
This results in expired entry being added to the cache, when ideally it should have been expired to free up the cache.
Also, this causes unnecessary noise in the requeststream if the expired segment cannot be scaled at that point.
Fixes #1803
If the scale down is sent because of cache expiry, then the segment is not added back into the cache
Unit …
> Issue 1803: AutoScaleProcessor expired entries are put back into the cache after posting an event for them

- segmentstore/server/host/src/main/java/io/pravega/segmentstore/server/host/ServiceStarter.java
- segmentstore/server/src/main/java/io/pravega/segmentstore/server/containers/StreamSegmentContainer.java
- segmentstore/server/src/main/java/io/pravega/segmentstore/server/store/ServiceBuilderConfig.java
- segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/hdfs/CreateOperation.java
- segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/hdfs/FileSystemOperation.java
- segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/hdfs/HDFSStorage.java
- segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/hdfs/HDFSStorageConfig.java
- segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/hdfs/OpenWriteOperation.java
- segmentstore/storage/impl/src/test/java/io/pravega/segmentstore/storage/impl/hdfs/CreateOperationTests.java
- segmentstore/storage/impl/src/test/java/io/pravega/segmentstore/storage/impl/hdfs/HDFSStorageTest.java
- segmentstore/storage/impl/src/test/java/io/pravega/segmentstore/storage/impl/hdfs/MockFileSystem.java
- test/system/src/main/java/io/pravega/test/system/framework/services/PravegaSegmentStoreService.java
- `StreamSegmentContainer`: 
- Closing `Storage` when closing the `StreamSegmentContainer` object itself. Closing this also closes the `DFSClient` which closes any open streams (if we have any), thus releasing resources.
- `HDFSStorage`: 
- Disabling FS Cache. Each instance of HDFSStorage has exactly one instance of a `DistributedFileSystem` class (vs using a shared one across the process). This enables us to properly close that instance when the SegmentContainer shuts down, thus releasing resources.
- Added option to disable data node replacement if needed. According to the [documentation](https://hadoop.apache.org/docs/r2.7.1/hadoop-project-dist/hadoop-hdfs/hdfs-default.xml), this is recommended for very small clusters to prevent the exact issues we seem to be …
> Issue 1760: Fixing HDFSStorage for small clusters

- test/system/src/test/java/io/pravega/test/system/AbstractFailoverTests.java
- test/system/src/test/java/io/pravega/test/system/MultiReaderTxnWriterWithFailoverTest.java
- test/system/src/test/java/io/pravega/test/system/ReadWriteAndAutoScaleWithFailoverTest.java
- test/system/src/test/java/io/pravega/test/system/ReadWriteAndScaleWithFailoverTest.java
* Adds an executor service that is exclusive to the controller implementation on the client.
* The thread pool needs one thread for the RPC, which is invoked asynchronously. We add
one more to enable some parallelism.
Fixes #1792 
Adds an executor service to some system tests that is used exclusively by `ControllerImpl`.
> Issue 1792: Add executor service for controllerImpl in system tests.

- controller/src/main/java/io/pravega/controller/store/stream/PersistentStreamBase.java
- controller/src/main/java/io/pravega/controller/store/stream/tables/TableHelper.java
- controller/src/test/java/io/pravega/controller/store/stream/StreamTest.java
- controller/src/test/java/io/pravega/controller/store/stream/TableHelperTest.java
The issue was that while creating segments in segment table, we can supply an old timestamp (time when scale request was generated). This timestamp can be older than the previous scale operation's timestamp in the history table. 
This caused our search logic in history table to look include records which were older than segment creation record which broke the search logic. 
So as a fix, we have done two things here -> 
1. ensure that segment creation time is strictly greater than timestamp on previous scale record in history table. 
2. Ensure that even if segment start time is less than previous scale record in history table, our computation is able to handle it. 
Another low probability chance when we may find record in history table but not in segment table: …
> Issue 1692: Sporadic No Value Present error for getSuccessors call

- test/system/src/test/java/io/pravega/test/system/MultiReaderTxnWriterWithFailoverTest.java
* Swaps the completion check order of txns and writers in `MultiReaderTxnWriterWithFailoverTest`.
Fixes #1799 
If we wait for txns to complete before we do it for writers, then we can have a race where new txns are created and not accounted for. The ultimate result is a discrepancy the write/read counts. This code fixes this issue by swapping the wait order of txns and writers.
Run system test case.
> Issue 1799: Swap wait order of txns and writers

- controller/src/main/java/io/pravega/controller/store/stream/PersistentStreamBase.java
- controller/src/main/java/io/pravega/controller/store/stream/tables/TableHelper.java
- controller/src/test/java/io/pravega/controller/store/stream/StreamMetadataStoreTest.java
While completing a txn, we delete the old epoch if scale has been started and no other txns exist on the epoch. 
However, this check does not wait to ensure that old epoch is deleted only if new epoch is created. 
It can result in old epoch being deleted even before new segments are created..
which means txn creation will fail for a bit until scale creates new epoch (as attempts to create txns against old epoch will keep throwing DataNotFoundException upon which txn creation will retry for a while before failing).
Fixes issue #1725
Txn completion should delete old epoch and proceed to complete scale only after it is guaranteed that new segments are created successfully in SSS.
This can be determined by looking for …
> Issue 1725: Delete old epoch during Txn completion step iff new epoch has been created during the scale operation.

- controller/src/test/java/io/pravega/controller/eventProcessor/impl/ZKCheckpointStoreTests.java
* Multiply current timeout values by 1000 when creating the zk client in `ZKCheckpointStoreTests`.
Fixes #1819 
Changes time out values when creating a zk client in controller tests.
Run unit tests.
> Issue 1819: Change timeout values when creating a ZK client in controller tests

- test/system/src/main/java/io/pravega/test/system/framework/services/PravegaSegmentStoreService.java
*Correct the wrong value of backoffsecs used in segmentstore deployment.
Fixes #1816 
Backoffsecs used for pravega segmentstore deployment is incorrect.
> Issue 1816: Fix the wrong backoffsecs in segmentstore deployment with system test framework

- test/system/src/main/java/io/pravega/test/system/framework/services/MarathonBasedService.java
* Ensure the framework waits until tasks staging is complete and the tasks are running.
Fixes #1813
When tasks are being staged, `io.pravega.test.system.framework.services.MarathonBasedService#isRunning` should wait until all the tasks are staged before returning a value. (staging is a transient state and it should not decide the outcome of isRunning method.)
Update: ensuring the task running count is equal to desired instance count is a better way to fix this issue. 
> Issue 1813: Ensure staging is complete before returning status of pravega services

- controller/src/main/java/io/pravega/controller/eventProcessor/impl/EventProcessor.java
- controller/src/main/java/io/pravega/controller/server/eventProcessor/CommitEventProcessor.java
- controller/src/test/java/io/pravega/controller/server/eventProcessor/ControllerEventProcessorTest.java
-  Fix the error handling logic in CommitEventProcessor.writeEvent
Fixes #1826 
- Ensure WriteFailedException is thrown if there is an exception while writing CommitEvent.
> Issue 1826: Fix the error handling logic in CommitEventProcessor.writeEvent

- controller/src/main/java/io/pravega/controller/task/Stream/StreamTransactionMetadataTasks.java
- controller/src/main/java/io/pravega/controller/timeout/TimeoutService.java
- controller/src/main/java/io/pravega/controller/timeout/TimerWheelTimeoutService.java
- controller/src/test/java/io/pravega/controller/timeout/TimeoutServiceTest.java
The issue was that client can send pings to different controllers. 
A controller, upon receiving the ping, creates a fence using zk node to claim ownership for txn's timeout management. 
However, if client sends ping to Controller-1 followed by controller-2 and then back to controller-1, then controller-1 doesnt try to reacquire lease on the txn, falsely assuming it continues to own the lease even though the ownership had passed to controller-2. 
Controller-2, upon its timeout will attempt to abort the txn and will be able to successfully do so because it has the lease. This is incorrect because the clients intent was to renew the lease and it achieved this by pinging more times which landed on controller-1.
To fix this, we are now making all pings resulting in …
> Issue 1499: Ping txn can be received on different controller instances whereby abort can be performed by some controller with a stale ping. 

- test/system/src/test/java/io/pravega/test/system/ControllerFailoverTest.java
Instead of calling controllerImpl.scaleStream asynchronously, we call startScale and wait for acknowledgement from controller that it has started scale. Only then does it perform failover.
Fixes #1844
Uses startScale api and ensures scale is no complete before failover. 
This system test should always pass.
> Issue 1844: ControllerFailoverTest should wait for ack from controller scale that scale has started. 

- test/system/src/test/java/io/pravega/test/system/ControllerFailoverTest.java
Fixes problem in system-test where we call the shutdown controller. 
Fixes code regression introduced in previous fix for 1844
makes checkScaleStatus against new controller instance
System test should pass.
> Issue 1844: Call controller2 instead of controller1 as controller is stopped. 

- common/src/main/java/io/pravega/common/concurrent/FutureHelpers.java
- common/src/test/java/io/pravega/common/concurrent/FutureHelpersTests.java
- common/src/test/java/io/pravega/common/lang/ProcessStarterTests.java
- segmentstore/server/src/main/java/io/pravega/segmentstore/server/containers/SegmentState.java
- segmentstore/server/src/main/java/io/pravega/segmentstore/server/containers/SegmentStateStore.java
- segmentstore/server/src/main/java/io/pravega/segmentstore/server/containers/StreamSegmentMapper.java
- segmentstore/server/src/test/java/io/pravega/segmentstore/server/containers/InMemoryStateStore.java
- segmentstore/server/src/test/java/io/pravega/segmentstore/server/containers/SegmentStateStoreTests.java
- segmentstore/server/src/test/java/io/pravega/segmentstore/server/containers/StateStoreTests.java
- segmentstore/server/src/test/java/io/pravega/segmentstore/server/containers/StreamSegmentMapperTests.java
Added the ability to recover from an incomplete call to CreateSegment/CreateTransaction. Since a Segment is created using 3 calls to Storage (Create Segment, Create State File, Write State File), it is possible that a previous call executed the first 1 or 2 of these steps but not the rest, which means that the Segment might not be usable. A subsequent call to createSegment/createTransaction may be able to recover this in certain conditions.
- If the Segment exists, but the State File does not exist or is corrupted, a subsequent call to CreateSegment/CreateTransaction will attempt to rebuild the State File (and return success).
- If the Segment exists and has a non-zero length, and the State File does not exist or is corrupted, a subsequent call to …
> Issue 1829: (SegmentStore) Ability to recover incomplete Segment Creations.

- gradle.properties
* Changes pravegaVersion in gradle.properties to 0.2.0-SNAPSHOT
Fixes #1854 
No code changes, only configuration.
> Issue 1854: Change Pravega version to 0.2.0-SNAPSHOT

- gradle.properties
* Remove rc0 suffix from `pravegaVersion`.
Fixes #1856 . Remove unnecessary suffix.
There are no code changes.
> Issue 1856: Remove rc0 from pravegaVersion property

- standalone/src/main/java/io/pravega/local/InProcPravegaCluster.java
Update the controller URI generated for `InProcPravegaCluster` to match the expected scheme.
Fixes #1862 
The controller URI generated for standalone Pravega deployment right now does not have any scheme. The scheme should match the one defined in ControllerResolverFactory.
Update controller URI according to the scheme.
Check the controller URI during run of standalone.
> Update controller URI according to the scheme.

- common/src/main/java/io/pravega/common/concurrent/SequentialAsyncProcessor.java
- common/src/test/java/io/pravega/common/concurrent/SequentialAsyncProcessorTests.java
- segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/bookkeeper/BookKeeperLog.java
- segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/bookkeeper/BookKeeperServiceRunner.java
- segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/bookkeeper/ZooKeeperServiceRunner.java
- segmentstore/storage/impl/src/test/java/io/pravega/segmentstore/storage/impl/bookkeeper/BookKeeperLogTests.java
Fixed a bug in `BookKeeperLog` that could cause it to stall the Write Processor if an unhandled exception bubbled up to the main method.
- Both the `WriteProcessor` and `RolloverProcessor` use the `SequentialAsyncProcessor` to control their behavior. If either of their main methods would let an exception bubble out of them, it would be possible for them not to be reinvoked again, even if there was work left to do.
- `SequentialAsyncProcessor` has been fixed to catch all exceptions, run them through an exception handler and re-run the task if the handler indicates so.
- `BookKeeperLog` will auto-close if either the `WriteProcessor` or `RolloverProcessor` fail to execute more than a number of times in a row (based on an existing config value).
**Purpose of the …
> Issue 1865: (BugFix) BookKeeperLog can stop processing writes if an unhandled exception occurs

- client/src/main/java/io/pravega/client/stream/impl/SegmentTransactionImpl.java
* Remove a precondition check state that can be false in the event of a race condition.
Fix #1876
Removes the pre-condition mentioned in #1876 that can be incorrect in the event of a race.
Look at SegmentOutputStreamImp.flush() and ackUpTo() the inflight event can happen to be empty inducing flush to return immediately. This in turn causes the precondition to fail if the callback for the ack has not yet been invoked by ackUpTo().
> Issue 1876: Remove overzealous precondition.

- segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/bookkeeper/ZooKeeperServiceRunner.java
- standalone/src/main/java/io/pravega/local/InProcPravegaCluster.java
* Initializes zkService before starting it in InProcPravegaCluster, otherwise the start call fails on the 
temporary directory precondition.
* Adds initialization to the main method in ZooKeeperServiceRunner.
Fixes #1879 
Adds initialization to `zkService` for standalone. 
Run standalone Pravega.
> Issue 1879: Zookeeper service not initialized in standalone Pravega

- segmentstore/storage/impl/src/test/java/io/pravega/segmentstore/storage/impl/hdfs/HDFSStorageTest.java
Removed unnecessary calls that turn off logging while running `HDFSStorageTest` - they were ineffective
Fixes #589.
Removes calls to turning off logging.
> Issue 589: Do not turn off logging during HDFSStorageTest

- controller/src/main/java/io/pravega/controller/store/stream/AbstractStreamMetadataStore.java
- segmentstore/server/host/src/main/java/io/pravega/segmentstore/server/host/handler/PravegaRequestProcessor.java
- shared/metrics/src/main/java/io/pravega/shared/metrics/DynamicLogger.java
- shared/metrics/src/main/java/io/pravega/shared/metrics/DynamicLoggerImpl.java
- shared/metrics/src/main/java/io/pravega/shared/metrics/DynamicLoggerProxy.java
- shared/metrics/src/main/java/io/pravega/shared/metrics/NullDynamicLogger.java
- shared/metrics/src/test/java/io/pravega/shared/metrics/MetricsProviderTest.java
* Update metrics code to ensure that selected counters and gauges can be removed from reporting.
* Use the added features to ensure that dynamic counters and gauges are frozen as segments and streams are sealed/deleted
This fixes #1828.
Disables gauges/counters from syncing which will not change any further. 
Unit tests.
Verify the traffic in platform deployments.
> Issue 1828 : Sending too many metric updates on sealed segments

- standalone/src/main/java/io/pravega/local/InProcPravegaCluster.java
- standalone/src/main/java/io/pravega/local/LocalPravegaEmulator.java
Allows access to `metrics.enableStatistics` through `InProcPravegaCluster` API.
Enable/disable metrics collection for `InProcPravegaCluster` through `InProcPravegaCluster` builder interface.
Enable/disable metrics collection for `InProcPravegaCluster` through `InProcPravegaCluster` builder interface.
Metrics are not collected when the setting is disabled.
> Allow metrics configuration through `InProcPravegaCluster` API.

- standalone/src/main/java/io/pravega/local/LocalPravegaEmulator.java
- standalone/src/test/java/io/pravega/local/InProcPravegaClusterTest.java
Creates a `LocalPravegaEmulator` deployment 
Creates a sample scope and stream
To test Pravega standalone deployment. This fixes #1881 
Adds unit test for LocalPravegaEmulator.
The unit tests pass.
> Unit tests for `LocalPravegaEmulator`

- common/src/main/java/io/pravega/common/util/Retry.java
- common/src/test/java/io/pravega/common/util/RetryTests.java
- Reuse `CompletableFuture` returned by `FutureHelpers.loop` in `RetryAndThrowBase#runInExecutor`
Fixes #1660 
- Removes the redundant CompletableFuture created in `RetryAndThrowBase#runInExecutor`
- Junits should pass.
> Issue 1660: Optimize RetryAndThrowBase#runInExecutor

- shared/metrics/src/main/java/io/pravega/shared/metrics/Counter.java
- shared/metrics/src/main/java/io/pravega/shared/metrics/CounterProxy.java
- shared/metrics/src/main/java/io/pravega/shared/metrics/Gauge.java
- shared/metrics/src/main/java/io/pravega/shared/metrics/GaugeProxy.java
- shared/metrics/src/main/java/io/pravega/shared/metrics/Meter.java
- shared/metrics/src/main/java/io/pravega/shared/metrics/MeterProxy.java
- shared/metrics/src/main/java/io/pravega/shared/metrics/Metric.java
- shared/metrics/src/main/java/io/pravega/shared/metrics/MetricProxy.java
- shared/metrics/src/main/java/io/pravega/shared/metrics/NullStatsLogger.java
- shared/metrics/src/main/java/io/pravega/shared/metrics/OpStatsLogger.java
- shared/metrics/src/main/java/io/pravega/shared/metrics/OpStatsLoggerImpl.java
- shared/metrics/src/main/java/io/pravega/shared/metrics/OpStatsLoggerProxy.java
- shared/metrics/src/main/java/io/pravega/shared/metrics/StatsLoggerImpl.java
- shared/metrics/src/main/java/io/pravega/shared/metrics/StatsLoggerProxy.java
- shared/metrics/src/main/java/io/pravega/shared/metrics/StatsProviderImpl.java
- shared/metrics/src/test/java/io/pravega/shared/metrics/MetricsProviderTest.java
- shared/metrics/src/test/java/io/pravega/shared/metrics/StatsLoggerProxyTest.java
Made Metrics objects (Counters, Meters, OpStatsLoggers, Gauges) and their proxies implement `AutoCloseable` so that they may be unregistered when no longer needed.
Fixed a number of bugs in `StatsLoggerProxy`:
- Every time `setLogger` was invoked, all (four) meter lists would double in size.
- Every time `setLogger` was invoked, the existing elements in the meter list (proxies) would point to other proxies that were just created, while the newly created proxies would (correctly) point to Meter instances
- The correct behavior for this class would be: `setLogger` does not affect the size of the collections and each `MeterProxy` wraps around a `Meter` instance (not another `MeterProxy`)
Fixes #1733. Required for #1734 .
**What the code …
> Issue 1733: Metrics fixes

- test/system/src/test/java/io/pravega/test/system/AbstractFailoverTests.java
- test/system/src/test/java/io/pravega/test/system/MultiReaderTxnWriterWithFailoverTest.java
- test/system/src/test/java/io/pravega/test/system/MultiReaderWriterWithFailOverTest.java
`Assert.fail(" ")`  if any error in `writer.close()` or `reader.close()`
We are just logging the error when we confront an error while closing readers/writers.
Fixes #1695 
> Issue 1695: Fail the test if any error while closing the writer/reader in failover system tests

- client/src/main/java/io/pravega/client/stream/impl/ControllerResolverFactory.java
StreamManager.create(URI) gives array out of bound exception if Port is missing in URI.
Added precondition check to ensure that both ip and port are present in the uri. 
Fixes #1925.
Adds a precondition check. 
All exiting tests should continue to pass.
> Issue 1925: StreamManagerImpl gives ArrayIndexOutOfBoundsException for invalid URI [Port Missing in URI

- client/src/main/java/io/pravega/client/admin/impl/ReaderGroupManagerImpl.java
- client/src/main/java/io/pravega/client/admin/impl/StreamManagerImpl.java
- client/src/main/java/io/pravega/client/stream/impl/Controller.java
- client/src/main/java/io/pravega/client/stream/impl/ControllerImpl.java
- client/src/test/java/io/pravega/client/stream/mock/MockController.java
- controller/src/main/java/io/pravega/controller/server/eventProcessor/LocalController.java
- test/integration/src/test/java/io/pravega/test/integration/ControllerRestApiTest.java
- Ensure `io.pravega.client.stream.impl.Controller` closes resources (transport connections) after use.
Fixes #1688 
- Now Controller api implements autocloseable which enables closing of resources used by controller client.
> Issue 1688: Close transport connections used by controller client after use.

- test/system/src/test/java/io/pravega/test/system/AbstractFailoverTests.java
- test/system/src/test/java/io/pravega/test/system/MultiReaderTxnWriterWithFailoverTest.java
- test/system/src/test/java/io/pravega/test/system/MultiReaderWriterWithFailOverTest.java
- test/system/src/test/java/io/pravega/test/system/ReadTxnWriteAutoScaleFailoverTest.java
- test/system/src/test/java/io/pravega/test/system/ReadTxnWriteAutoScaleWithFailoverTest.java
- test/system/src/test/java/io/pravega/test/system/ReadTxnWriteScaleWithFailoverTest.java
- test/system/src/test/java/io/pravega/test/system/ReadWriteAndAutoScaleWithFailoverTest.java
- test/system/src/test/java/io/pravega/test/system/ReadWriteAndScaleWithFailoverTest.java
Two new failover system test cases with  txn writes and reads  and triggering scaling/auto-scaling are added.
Failover is performed before, during, after scaling/auto-scaling.
Failover consists of the following :
a. segmentstore failover
b. controller failover
c. segmentstore and controller failover
Currently, `multireaderwriterwithfailovertest` and `multireadertxnwriterwithfailovertest`   doesn't match with the other failover tests. They need to be modified.
1. Adding new system test cases with failover .
2. Using `AbstractFailoverTests` in all the failover tests to create uniformity across all the failover tests.
Fixes #1409 
System tests should pass
> Issue 1409: Failover System tests with transaction writes, reads triggering scaling/auto-scaling

- client/src/main/java/io/pravega/client/stream/impl/ControllerResolverFactory.java
Check for null before ControllerNameResolver#shutdown.
Fixes #1939 
Additional null check since an executor is not used in the direct scheme(tcp://) for controller, but is used only in a discover scheme (pravega://)
> Issue 1939: NPE during shutdown of ControllerNameResolver

- deployment/aws/installer/entry_point_template.yml
- docker/compose/docker-compose-extendeds3.yml
- docker/compose/docker-compose-nfs-mount.yml
- docker/compose/docker-compose-nfs.yml
- docker/compose/docker-compose.yml
- docker/compose/swarm/pravega.yml
- docker/compose/swarm/scale_segmentstore
This PR is my first stab at this project. I’ve simply verified launching with `docker compose`. Assuming the proposed changes make sense, I’d like to know what should be done to test it more throughly.
HTH
Add the following JVM flags
- `-XX:OnError="kill -9 p%"`
- `-XX:+HeapDumpOnOutOfMemoryError`
- `-XX:+ExitOnOutOfMemoryError`
- `-XX:+CrashOnOutOfMemoryError`
and reformat to avoid long lines.
_The last two options were added with JDK 8u92_
Address  #522 
Kills the JVM process on unrecoverable errors.
TBD
> Issue 522: Add error handling JVM options

- segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/extendeds3/ExtendedS3StorageFactory.java
- Use namespace while creating a S3 client.
Fixes #1953. Uses ECS namespace config while creating S3 client.
Use namespace while creating a S3 client.
Works with ECS configured with namespaces.
> Issue 1953: Extended S3 Storage uses ECS namespace from the config

- segmentstore/server/src/main/java/io/pravega/segmentstore/server/containers/StreamSegmentContainer.java
- segmentstore/server/src/main/java/io/pravega/segmentstore/server/containers/StreamSegmentMapper.java
- segmentstore/server/src/test/java/io/pravega/segmentstore/server/SegmentMetadataComparer.java
- segmentstore/server/src/test/java/io/pravega/segmentstore/server/containers/StreamSegmentContainerTests.java
- segmentstore/server/src/test/java/io/pravega/segmentstore/server/containers/StreamSegmentMapperTests.java
Changed the way `StreamSegmentService.getStreamSegmentInfo` works in the case when segments are not currently active. 
- If a segment is active, its info is returned directly from the in-memory Metadata
- If a segment is not active, its info is returned from Tier2 Storage, without activating it. This is different than before, when the Segment was activated prior to returning the result.
Benefits include:
- Shorter latencies for inactive segments by not having to wait on also writing to Tier1
- Not activating a segment simply for a `getInfo` means that fewer segments are currently loaded in memory, thus potentially reducing footprint in a situation when we need to just get info on segments without actually touching them (this may be useful when implementing …
> Issue 1923: (SegmentStore) GetSegmentInfo optimization

- segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/hdfs/WriteOperation.java
- segmentstore/storage/src/test/java/io/pravega/segmentstore/storage/StorageTestBase.java
Fixed a bug in `WriteOperation` where it was using the wrong overload of `IOUtils.copyBytes`. The previous call was passing "length" as buffer size, thus causing the method to copy the entire `InputStream` as opposed from just how much we wanted.
Updated `StorageTestBase` to test for this case as well.
Fixes #1961 .
Uses the correct overload of `IOUtils.copyBytes`.
Unit test updated to check this particular case. Also can verify the correct overload is used.
> Issue 1961: (BugFix) Use correct overload of IOUtils.copyBytes in HDFSStorage

- controller/src/test/java/io/pravega/controller/task/Stream/StreamMetadataTasksTest.java
StreamMetadataTasksTest.updatestream test has a test to concurrently call two updatestream api calls. 
The problem is since both of them are processed asynchronously, second one can be processed before the first, hence breaking the expectations in the test. 
Hence we need to make sure that the first one has started processing before we post the second one to ensure guaranteed order of processing so test can verify correctly. 
Fixes #1959 
After making first updateStream call, the test waits to see stream state being set to UPDATING ("first step" of update workflow) before making second update stream call.
This will ensure that first workflow is executed …
> Issue 1959: Sporadic build failure in new StreamMetadataTasksTest.updateStreamTest

- client/src/main/java/io/pravega/client/stream/ReaderGroupConfig.java
* Adds missing import to ReaderGroupConfig.
Fixes #1967 
Adds missing `lombok.Getter` import.
Build.
> Issue 1967: Missing Getter import

- controller/src/main/java/io/pravega/controller/store/checkpoint/ZKCheckpointStore.java
- controller/src/test/java/io/pravega/controller/eventProcessor/impl/ZkCheckpointStoreConnectivityTest.java
Throwing connectivity exception in case of zk session expiry.
In the test code, increased the session expiry time.
Fixes issue 1964
Transforms zk session expiry exception into store.connectivity excepiton
Said test should pass consistently
> Issue 1964: Sporadic build failure ZkCheckpointStoreConnectivityTest

- client/src/main/java/io/pravega/client/stream/ReaderGroupConfig.java
- test/integration/src/test/java/io/pravega/test/integration/ReaderGroupNotificationTest.java
Increase the timeout for reading an event.
Fixes #1970 
Fixes #1970 
> Issue 1970: Fix ReaderGroupNotificationTest failure.

- test/integration/src/test/java/io/pravega/test/integration/ReaderGroupNotificationTest.java
- test/integration/src/test/java/io/pravega/test/integration/endtoendtest/EndToEndWithScaleTest.java
Disable automatic checkpointing for ReaderGroup as it is not required by the tests.
Fixes #1982 , #1983 
Fixes flaky integration tests.
> Issue 1982: Fix ReaderGroupNotificationTest and EndToEndWithScaleTest failure

- client/src/main/java/io/pravega/client/stream/ReaderGroupConfig.java
- test/integration/src/test/java/io/pravega/test/integration/CheckpointTest.java
- test/integration/src/test/java/io/pravega/test/integration/ReadTest.java
- test/integration/src/test/java/io/pravega/test/integration/ReaderGroupNotificationTest.java
- test/integration/src/test/java/io/pravega/test/integration/endtoendtest/EndToEndWithScaleTest.java
* Adds a builder call to disable automatic checkpoints. Automatic checkpointing is enabled by default.
Fixes #1971 
It adds a call to `ReaderGroupConfigBuilder` to disable automatic checkpointing. Previously, we required the application to set the interval to -1.
Build and run unit tests.
> Issue 1971: Builder call to disable checkpoints

- common/src/main/java/io/pravega/common/concurrent/SequentialAsyncProcessor.java
- common/src/test/java/io/pravega/common/concurrent/SequentialAsyncProcessorTests.java
- segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/bookkeeper/BookKeeperLog.java
- segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/bookkeeper/BookKeeperServiceRunner.java
- segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/bookkeeper/Write.java
- segmentstore/storage/impl/src/test/java/io/pravega/segmentstore/storage/impl/bookkeeper/BookKeeperLogTests.java
- Updated `BookKeeperLog`'s WriteProcessor and RolloverProcessor to use a retry-with-backoff when they encounter errors.
- Updated `SequentialAsyncProcessor` to use a standard retry policy instead of the mechanism it had previously.
- Not counting write failures due to rollovers as "failed attempts", since they were caused by an action by us.
- BookKeeperLog unit tests: actually stopping Bookies completely (instead of just stopping their Netty interfaces). This more closely resembles a real-life failure.
Fixes #1997.
See Change Log Description.
Verify that the build passes consistently.
> Issue 1997: BookKeeperLog uses a Retry-with-Backoff

- test/integration/src/test/java/io/pravega/test/integration/endtoendtest/EndToEndTxnWithScaleTest.java
Disable automatic checkpointing in EndToEndTxnWIthScaleTest.
Fixes #2003 
Fixes flaky integration test.
> Issue 2003 : Disable automatic checkpointing in EndToEndTxnWithScaleTest 

- test/integration/src/test/java/io/pravega/test/integration/ReaderGroupNotificationTest.java
Ensure executors used for notification are closed.
Fixes #1982 
The older test code used to use InlineExecutor which internally created a `ScheduledThreadPoolExecutor(1)` for all delayed tasks. This executor was never closed by the test. 
Tests should pass. 
- Issue not seen locally with this change.
- `ReaderGroupNotificationTest` failures not observed on travis/jenkins for multiple runs.
> Issue 1982 : Ensure executors used for notification are closed.

- CODE_OF_CONDUCT.md
Adds language to the code of conduct to enable it to apply to things that take place outside of official Pravega spaces, but occurred as a result of the individuals involved interactions with Pravega.
Fixes #1973 
Manual inspection.
> Issue 1973: Update code of conduct

- test/integration/src/test/java/io/pravega/test/integration/endtoendtest/EndToEndTruncationTest.java
The test fails sporadically because we start truncation but do not wait for truncation to complete. 
Adds a wait on future. 
Test should pass consistently.
> Issue 2016: Sporadic test failure EndToEndTruncationTest

- client/src/main/java/io/pravega/client/segment/impl/SegmentOutputStreamImpl.java
- client/src/test/java/io/pravega/client/segment/impl/SegmentOutputStreamTest.java
- segmentstore/server/host/src/main/java/io/pravega/segmentstore/server/host/handler/AppendProcessor.java
- segmentstore/server/host/src/test/java/io/pravega/segmentstore/server/host/handler/AppendProcessorTest.java
- shared/protocol/src/main/java/io/pravega/shared/protocol/netty/WireCommands.java
- shared/protocol/src/test/java/io/pravega/shared/protocol/netty/WireCommandsTest.java
- test/integration/src/test/java/io/pravega/test/integration/AppendTest.java
This adds a new field previousEventNumber in the server response command DataAppended. The field represents the previously acknowledged event number. This is used on the client to verify that no acknowledgements have been missed. If a gap is detected, the connection is re-established.
Fixes #1858
Fixes #1858
Set of changes originally proposed by @moizsj in PR #1893 .
Unit and integration tests have been added.
> Issue 1858: DataAppended should have an event range for client validation

- segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/bookkeeper/BookKeeperLog.java
- segmentstore/storage/impl/src/test/java/io/pravega/segmentstore/storage/impl/bookkeeper/BookKeeperLogTests.java
Removed the following unit tests from `BookKeeperLogTests`
- `testAutoCloseOnZooKeeperFailure`
- `testAppendTransientZooKeeperFailure`
These were causing sporadic build failures due to timeouts since they were stopping and then quickly restarting ZooKeeper during the test. In case that didn't work out it would be possible for the unit test to not complete due to the ZK clients (ours, and the one in BK) endlessly trying to reconnect.
These unit tests do not test anything in addition to what their siblings do (the ones that stop/start BookKeeper) and rely on BookKeeper's internal mechanism for ZK reconnection to succeed. 
Also changed:
- Do not perform rollover in BookKeeperLog if the instance is closed. This was caught up in one of these failed runs and it would …
> Issue 2019: Removing unneeded and flaky unit tests

- client/src/main/java/io/pravega/client/stream/ReaderGroup.java
- client/src/main/java/io/pravega/client/stream/impl/ReaderGroupImpl.java
- client/src/main/java/io/pravega/client/stream/impl/StreamCut.java
- test/integration/src/test/java/io/pravega/test/integration/StreamCutsTest.java
* Adds a reader group call to obtain a stream cut.
Fixes #1995
Adds a new API call to `ReaderGroup` and a corresponding implementation in `ReaderGroupImpl`. It adds an integration test case to check for a correct implementation.
Run tests.
> Issue 1995: Stream cut API reader side

- gradle/application.gradle
- gradle/java.gradle
- Added sourceJar and javadocJar to the published artifacts, which is required for maven central publishing
- Added a check for the archiveTask property before comparing it to distZip,distTar.  When publishing with signatures the signature artifact does not have that property.
Allow the artifacts to be uploaded to maven central and be released.
I used these changes locally on the release branch in order to publish the 0.1.0 release of pravega to maven central.
Fixes #1929
> Issue 1929: Updated build with changes required to publish to maven central

- segmentstore/server/host/src/test/java/io/pravega/segmentstore/server/host/ExtendedS3IntegrationTest.java
- segmentstore/server/host/src/test/java/io/pravega/segmentstore/server/host/FileSystemIntegrationTest.java
- segmentstore/server/host/src/test/java/io/pravega/segmentstore/server/host/HDFSIntegrationTest.java
Reduced the number of bookies in integration tests from 3 to 1. Since they're all in process, there's no point in over-replicating the data, which just slows things down.
Fixes #2040.
Nothing different.
> Issue 2040: Reduced bookie count in SegmentStore integration test

- client/src/main/java/io/pravega/client/stream/impl/ReaderGroupStateManager.java
Signed-off-by: Tom Kaitchuck <Tom.Kaitchuck@emc.com>
Ensure only one reader acquires a segment.
Fixes #2042 .
The acquireSegment logic is broken. It has two possible early return paths in the update function. However these do not reset the result variable. This has the effect of keeping the result from a previous iteration of update.
It now resets the result immediately, so that regardless of where the function returns nothing is carried over from the previous iteration.
No tests, are added here. But as this is a pattern, I've filed #2043 to cover this pattern. Once this change is made it will be easy to prevent this pattern all together, and add tests for it.
> Issue 2042: Ensure only one reader aquires a segment.

- test/integration/src/main/java/io/pravega/test/integration/selftest/Reporter.java
- test/integration/src/main/java/io/pravega/test/integration/selftest/TestState.java
SelfTester reports operations per second, in addition to all other metrics it used to report.
Fixes #2050. Needed for performance benchmarks.
SelfTester reports new metric.
Sample output (check out newly added `Ops = <instant>/<overall>`):
(disregard actual numbers; this was done on a dev machine without controlling for the environment)
```
0:00:01.779 [SelfTest]: Started.
0:00:02.780 [Reporter]: (warmup); Ops = 0/35646; Data: 3.4 MB; TPut: 0.0/3.4 MB/s; TPools (Q/T/S): S = 4/5/30, T = 0/1/80, FJ = 0/0/0.
0:00:03.787 [Reporter]: (warmup); Ops = 141111/88882; Data: 17.0 MB; TPut: 13.5/8.5 MB/s; TPools (Q/T/S): S = 4/6/30, T = 115/1/80, FJ = 0/0/0.
0:00:04.787 [Reporter]: 162296/2000000; Ops = …
```
> Issue 2050: SelfTester reports operations per second

- test/system/src/main/java/io/pravega/test/system/framework/services/BookkeeperService.java
Ensure bookkeeper port is mentioned while setting the health check for bookkeeper service.
Fixes #2054 
Add port to Bookkeeper service healthcheck.
Tests on mesos should pass.
> Issue 2054: Ensure Bookkeeper port is mentioned in marathon healthCheck.

- client/src/main/java/io/pravega/client/netty/impl/ConnectionFactoryImpl.java
Removes redundant `channel.close()` call incase the bootstrap.connect() operation fails.
Fixes #2057 
Removes the redundant `close()` method call.
> Issue 2057 : (Bugfix) Remove redundant close() call in ConnectionFactoryImpl .

- docker/bookkeeper/Dockerfile
- docker/bookkeeper/entrypoint.sh
- docker/compose/Readme.md
This updates the bookkeeper docker image to be based on 4.5.0 to match the version of the
bookkeeper dependency. This also updates the version of zookeeper in the bookkeeper container to 3.5.3-beta, since that is what bookkeeper 4.5.0 uses.
Additionally, I moved the BK and ZK in the containers to be one level higher so there are no version numbers in the paths which would require more changes anytime the versions change:
```
/opt/bk_all/bookkeeper-server-<version> -> /opt/bookkeeper
/opt/zk/zookeeper-<version> -> /opt/zookeeper
```
Fixes #2005 
Bring the versions of bookkeeper and zookeeper in the containers in line with what is used by the code.
This pull request is based on the original PR #2007 submitted by …
> Issue 2005: Update bookkeeper to 4.5.0

- common/src/test/java/io/pravega/common/concurrent/FuturesTests.java
- common/src/test/java/io/pravega/common/io/FixedByteArrayOutputStreamTests.java
- common/src/test/java/io/pravega/common/util/ByteArraySegmentTests.java
- segmentstore/contracts/src/main/java/io/pravega/segmentstore/contracts/AttributeUpdateType.java
- segmentstore/contracts/src/main/java/io/pravega/segmentstore/contracts/StreamSegmentInformation.java
- segmentstore/server/host/src/main/java/io/pravega/segmentstore/server/host/ServiceStarter.java
- segmentstore/server/host/src/main/java/io/pravega/segmentstore/server/host/ZKSegmentContainerManager.java
- segmentstore/server/host/src/main/java/io/pravega/segmentstore/server/host/handler/AppendProcessor.java
- segmentstore/server/host/src/main/java/io/pravega/segmentstore/server/host/stat/AutoScaleProcessor.java
- segmentstore/server/host/src/main/java/io/pravega/segmentstore/server/host/stat/SegmentStatsFactory.java
- segmentstore/server/host/src/main/java/io/pravega/segmentstore/server/host/stat/SegmentStatsRecorder.java
- segmentstore/server/host/src/test/java/io/pravega/segmentstore/server/host/stat/AutoScaleProcessorTest.java
- segmentstore/server/src/main/java/io/pravega/segmentstore/server/containers/StreamSegmentContainer.java
- segmentstore/server/src/main/java/io/pravega/segmentstore/server/containers/StreamSegmentContainerMetadata.java
- segmentstore/server/src/main/java/io/pravega/segmentstore/server/logs/DataFrameBuilder.java
- segmentstore/server/src/main/java/io/pravega/segmentstore/server/logs/DataFrameReader.java
- segmentstore/server/src/main/java/io/pravega/segmentstore/server/logs/DurableLog.java
- segmentstore/server/src/main/java/io/pravega/segmentstore/server/logs/OperationMetadataUpdater.java
- segmentstore/server/src/main/java/io/pravega/segmentstore/server/reading/AsyncReadResultHandler.java
- segmentstore/server/src/main/java/io/pravega/segmentstore/server/reading/AsyncReadResultProcessor.java
- segmentstore/server/src/main/java/io/pravega/segmentstore/server/reading/CacheManager.java
- segmentstore/server/src/main/java/io/pravega/segmentstore/server/reading/ReadIndexEntry.java
- segmentstore/server/src/main/java/io/pravega/segmentstore/server/reading/StreamSegmentReadResult.java
- segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/bookkeeper/BookKeeperLog.java
- segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/bookkeeper/LogReader.java
- segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/LogAddress.java
- segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/mocks/InMemoryDurableDataLog.java
- segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/mocks/InMemoryStorage.java
- segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/rolling/RollingStorage.java
- test/testcommon/src/main/java/io/pravega/test/common/ErrorInjector.java
Fixed a number of compiler warnings reported by Intellij using various rules enabled. Sample changes include:
- Unused class-level fields
- Class-level fields that can be converted to local variables
- Casting warnings
- Javadoc warnings
- Accessing class-level fields outside of their declared guards (concurrency).
Fixes #2066.
Better looking code.
Build & tests must pass.
> Issue 2066: Compiler warnings

- test/system/src/main/java/io/pravega/test/system/framework/RemoteSequential.java
- test/system/src/main/java/io/pravega/test/system/framework/services/BookkeeperService.java
- test/system/src/main/java/io/pravega/test/system/framework/services/MarathonBasedService.java
- test/system/src/main/java/io/pravega/test/system/framework/services/PravegaControllerService.java
- test/system/src/main/java/io/pravega/test/system/framework/services/PravegaSegmentStoreService.java
- test/system/src/main/java/io/pravega/test/system/framework/services/ZookeeperService.java
- test/system/src/test/java/io/pravega/test/system/ReadTxnWriteAutoScaleWithFailoverTest.java
- test/system/src/test/java/io/pravega/test/system/ReadTxnWriteScaleWithFailoverTest.java
- test/system/src/test/java/io/pravega/test/system/ReadWriteAndAutoScaleWithFailoverTest.java
- test/system/src/test/java/io/pravega/test/system/ReadWriteAndScaleWithFailoverTest.java
- Ensure pravega docker images run on a mesos containerizer.
- Increase resources provided to test and pravega containers.
Fixes #2054 
- Ensure the we use mesos containerizer to obtain better performance on a mesos cluster.
- Ensure the tests pass on the latest marathon 1.5.
Update: Tested it on the latest cluster with marathon 1.5.0. The framework is behaving as expected.
> Issue 2054: (Bugfix) Additional health check is causing the failover tests to timeout/fail.

- client/src/main/java/io/pravega/client/segment/impl/SegmentOutputStreamImpl.java
- client/src/main/java/io/pravega/client/stream/impl/ReaderGroupState.java
Fix the error message pattern for `Preconditions`.
Fixes #2038 
Replace {} with %s.
Test should continue to pass.
> Issue 2038 : Use correct error message template for Preconditions.

- segmentstore/server/host/src/main/java/io/pravega/segmentstore/server/host/handler/PravegaRequestProcessor.java
- segmentstore/server/host/src/test/java/io/pravega/segmentstore/server/host/handler/PravegaRequestProcessorTest.java
In commitTransaction, we are bow capturing SegmentAlreadyMergedException and treating this as idempotent operation and returning TransactionCommitted in response. 
Fixes issue 2075
> Issue 2075: PravegaRequestProcessor.commitTransaction should handle SegmentAlreadyMergedException

- controller/src/main/java/io/pravega/controller/store/stream/InMemoryStreamMetadataStore.java
- controller/src/main/java/io/pravega/controller/store/stream/StreamMetadataStore.java
- controller/src/main/java/io/pravega/controller/store/stream/ZKStream.java
- controller/src/main/java/io/pravega/controller/store/stream/ZKStreamMetadataStore.java
- controller/src/main/java/io/pravega/controller/task/Stream/StreamMetadataTasks.java
- controller/src/test/java/io/pravega/controller/store/stream/StreamMetadataStoreTest.java
- controller/src/test/java/io/pravega/controller/task/Stream/StreamMetadataTasksTest.java
There are two issues:
1. Delete Scope fails. which is the root cause for test failure
Stream Deletion is done asynchronously. 
We used to check if delete is done by looking to access some property within the stream (like state) and on not being able to find such a property we would conclude that the stream was deleted. 
The stream may be in the process of being deleted, but not all of its data may have been deleted while a request for deletion of scope is received. 
Deletion of scopes fails with "container not empty" from zookeeper. 
2. delete stream under bucket gives NoNode
This is because we are not adding the node while creating the stream. 
Fixes #2080 …
> Issue 2080: Scope delete fails with directory not empty

- client/src/main/java/io/pravega/client/stream/impl/EventStreamReaderImpl.java
Ensure SegmentInputStream is closed inside method `io.pravega.client.stream.impl.EventStreamReaderImpl#read(Eventpointer pointer)
`
Fixes #2096 
Closes SegmentInputStream created inside read(EventPointer) method.
> Issue 2096: Ensure segmentInputStream closed inside method read(EventPointer pointer).

- test/system/src/main/java/io/pravega/test/system/framework/RemoteSequential.java
- test/system/src/main/java/io/pravega/test/system/framework/services/MarathonBasedService.java
- test/system/src/main/java/io/pravega/test/system/framework/services/PravegaControllerService.java
- test/system/src/main/java/io/pravega/test/system/framework/services/PravegaSegmentStoreService.java
- Ensure pravegalogs are stored in mesos sandbox directory.
- Remove sleep post test execution as we have a sleep before execution of tests.
- Check if service is running every 10seconds instead of 20seconds.
Fixes #2108
Ensure logs are stored in mesos sandbox directory and remove redundant waits in the system test framework.
> Issue 2108:  Ensure pravega logs are stored on Mesos Sandbox directory.

- client/src/main/java/io/pravega/client/stream/RetentionPolicy.java
- client/src/main/java/io/pravega/client/stream/ScalingPolicy.java
- client/src/main/java/io/pravega/client/stream/impl/ModelHelper.java
- client/src/test/java/io/pravega/client/stream/impl/ModelHelperTest.java
- client/src/test/java/io/pravega/client/stream/mock/MockController.java
- controller/src/main/java/io/pravega/controller/server/SegmentHelper.java
- controller/src/main/java/io/pravega/controller/server/eventProcessor/requesthandlers/AutoScaleTask.java
- controller/src/main/java/io/pravega/controller/server/rest/ModelHelper.java
- controller/src/main/java/io/pravega/controller/task/Stream/StreamMetadataTasks.java
- controller/src/test/java/io/pravega/controller/rest/v1/ModelHelperTest.java
- controller/src/test/java/io/pravega/controller/store/stream/StreamMetadataStoreTest.java
- controller/src/test/java/io/pravega/controller/task/Stream/StreamMetadataTasksTest.java
- shared/controller-api/src/main/proto/Controller.proto
* Adds javadocs to the public static classes in ScalingPolicy and RetentionPolicy
* Renames the type classes in ScalingPolicy and RetentionPolicy to be more specific
Fixes #2094
There is no functional change, it only adds javadocs to explain how to set the parameter values that creates a policy instance.
Tests should pass, but it is mostly visual inspection.
> Issue 2094: Improve retention and scaling policy classes

- controller/src/conf/logback.xml
- dist/conf/logback.xml
- segmentstore/server/host/src/config/logback.xml
Ensure pravega logs are compressed after rollover.
Fixes #2104 
Ensure logs are compressed during rollover.
Tested that the compression of logs does happen.
> Issue 2104: Ensure all the logs are compressed after rollover.

- segmentstore/server/host/src/main/java/io/pravega/segmentstore/server/host/handler/AppendProcessor.java
- segmentstore/server/host/src/test/java/io/pravega/segmentstore/server/host/handler/AppendProcessorTest.java
Ensure ack (WireCommands.DataAppended) is sent on wire before the next Append is written to the store.
Fixes #2114 
Ensures outstandingAppend is cleared only after the ack is sent over wire, there by ensuring Acks are not send out of order.
> Issue 2114 :  Ensure out of order acks are not sent by the append processor.

- client/src/main/java/io/pravega/client/segment/impl/SegmentOutputStreamImpl.java
Fixes a race condition that could (among other things) result in a null pointer exception. 
Fixes #2140 . 
When an AppendSeutp arrives pass the connection to the `connectionSetupComplete` method, that way there is no chance it could be failed before it is returned to the waiting caller. 
System tests should no longer see the NPE in #2140.
> Issue 2140: Fix race resulting in an NPE if connection is immediately failed after it is setup.

- gradle.properties
- segmentstore/server/host/src/main/java/io/pravega/segmentstore/server/host/handler/ServerConnectionInboundHandler.java
- test/integration/src/test/java/io/pravega/test/integration/AppendTest.java
Add workaround for https://github.com/netty/netty/issues/3246
Fixes https://github.com/pravega/pravega/issues/2114
In the netty code in `AbstractChannelHandlerContext.write()` there is a [very severe bug](https://github.com/netty/netty/issues/3246). This results in data being sent in a different order than it was written even when there is explicit external synchronization. (Even when, in our case, the second write is actually triggered by the completion of the first write). As this bug has not been fixed in 3 years, we cannot assume any fix will be forthcoming or that the netty team would accept a patch if we made one.
The work around code effectively removes …
> Issue 2114: Work around netty bug causing out of order acks

- client/src/main/java/io/pravega/client/segment/impl/SegmentInputStreamImpl.java
Ensure outstanding read requests are cancelled when sgmentInputStream#close() is invoked.
Fixes #2148 
Cancels outstanding requests.
> Issue 2148: Cancel outstanding read requests in SegmentInputStream#close().

- test/system/src/test/java/io/pravega/test/system/AbstractFailoverTests.java
- test/system/src/test/java/io/pravega/test/system/MultiReaderTxnWriterWithFailoverTest.java
- test/system/src/test/java/io/pravega/test/system/MultiReaderWriterWithFailOverTest.java
- test/system/src/test/java/io/pravega/test/system/ReadTxnWriteAutoScaleWithFailoverTest.java
- test/system/src/test/java/io/pravega/test/system/ReadTxnWriteScaleWithFailoverTest.java
- test/system/src/test/java/io/pravega/test/system/ReadWithAutoScaleTest.java
- test/system/src/test/java/io/pravega/test/system/ReadWriteAndAutoScaleWithFailoverTest.java
- test/system/src/test/java/io/pravega/test/system/ReadWriteAndScaleWithFailoverTest.java
1. Add retry logic around seal stream because it can fail if it conflicts with another stream operation (typically auto-scale).
2.   To verify if scaling has happened, look for scale operations rather than segment count.
3.    Increase timeout in ReadWithAutoScale test.
4. Unwanted test failure because clients threw exception after stream was deleted causing test failures.
Fixes #2133
Fixes system test issues
We should not observe these issues in system test
> Issue 2133: System test code issues

- test/system/src/test/java/io/pravega/test/system/ReaderCheckpointTest.java
Ensure the test method `io.pravega.test.system.ReaderCheckpointTest#readEvents` continues reading if event read is a checkpoint event. 
Related to #2152.
Ensure we continue reading if event read is a checkpoint event.
> Issue 2152 : BugFix, ensure the test does not stop reading if event read is a checkpoint.

- client/src/main/java/io/pravega/client/segment/impl/SegmentInputStreamFactory.java
- client/src/main/java/io/pravega/client/stream/EventPointer.java
- client/src/main/java/io/pravega/client/stream/EventStreamReader.java
- client/src/main/java/io/pravega/client/stream/impl/EventStreamReaderImpl.java
- client/src/test/java/io/pravega/client/stream/impl/EventStreamReaderTest.java
- controller/src/test/java/io/pravega/controller/mocks/EventStreamReaderMock.java
- test/integration/src/main/java/io/pravega/test/integration/selftest/adapters/ClientReader.java
- test/integration/src/test/java/io/pravega/test/integration/ReadTest.java
* Rename read(EventPointer) to fetchEvent()
Fixes https://github.com/pravega/pravega/issues/2157
Renames the method.
Should have no functional impact.
> Issue 2157: Rename read to fetchEvent

- client/src/main/java/io/pravega/client/stream/ScalingPolicy.java
* Clarifies that the we have a disjunction for scaling up and a conjunction for scaling down;
* Clarifies that the target rate is per segment;
* Mentions and explains the cool-down period.
Fixes #2160 
There is no code change, only javadoc changes.
> Issue 2160: Improvements to ScalingPolicy javadocs

- client/src/main/java/io/pravega/client/segment/impl/SegmentInputStreamImpl.java
- test/integration/src/test/java/io/pravega/test/integration/ReadTest.java
* Fixes a bug in SegmentInputStreamImpl that causes an NPE to be thrown when events are larger than the read length.
* Adds a call to issueRequestIfNecessary to the loop that handles the case in which the event is greater than the read length.
* Changes the sign in issueRequestIfNeeded from greater to greater or equal.
Fixes #2159 
In `SegmentInputStreamImpl.issueRequestIfNeeded`, in the case we are reading an event that is greater than read length, we end up with `buffer.capacityAvailable() <= readLength`, which causes the value of `outstandingRequest` to remain null and induces the NPE when handleRequest is invoked next. The solution to this scenario is to …
> Issue 2159: NPE in SegmentInputStreamImpl

- controller/src/main/java/io/pravega/controller/server/eventProcessor/requesthandlers/UpdateStreamTask.java
- controller/src/main/java/io/pravega/controller/store/stream/InMemoryStreamMetadataStore.java
- controller/src/main/java/io/pravega/controller/store/stream/ZKStreamMetadataStore.java
- controller/src/main/java/io/pravega/controller/task/Stream/StreamMetadataTasks.java
- controller/src/test/java/io/pravega/controller/server/retention/StreamCutServiceTest.java
- controller/src/test/java/io/pravega/controller/task/Stream/StreamMetadataTasksTest.java
* Does not add stream to the retention bucket if it has null retention policy.
* Checks during stream configuration updates whether retention policy is added or removed from previous configuration and add or remove stream from the bucket accordingly.
Fixes #2120
If a stream configuration has a null retention policy, then stream should not be considered for auto-retention. 
AutoRetention is performed on all streams that are part of some bucket. 
So we should not add stream to the bucket if it has null retention policy. 
Similarly, during configuration update, we should check if retention policy is added or removed from previous configuration and add or remove …
> Issue 2120: Handle StreamConfiguration with null retention policy

- test/system/src/test/java/io/pravega/test/system/MultiSegmentStoreTest.java
Ensure checkpoint events do not cause of failure of MultiSegmentstore test.
Fixes #2170 
Disables automatic checkpointing.
> Issue 2170: Bugfix: Ensure automatic checkpointing is disabled for MultiSegmentstoreTest.

- segmentstore/server/src/main/java/io/pravega/segmentstore/server/writer/SegmentAggregator.java
- segmentstore/server/src/test/java/io/pravega/segmentstore/server/writer/SegmentAggregatorTests.java
- segmentstore/server/src/test/java/io/pravega/segmentstore/server/writer/TestWriterDataSource.java
Fixed a bug in `SegmentAggregator` where it would fail post-recovery if an append was already partially written to Storage.
Details:
- Writes to Tier2 Storage are capped (to a configurable value, default 1MB). A single write can aggregate multiple appends to a Segment, and as such, an append can be split across multiple Storage Writes.
- As such, it is quite likely that an append may be split across multiple such Tier2 writes, and some complete but at least one does not (since the process may have crashed or we failed over to some other host).
- Upon recovery, the `StorageWriter` must handle this situation and ensure that only those bytes which haven't been written are added.
- Prior to this change, the `StorageWriter` would do no such thing, and it would …
> Issue 2168: (SegmentStore) StorageWriter can't handle recovery with partially written appends

- segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/extendeds3/ExtendedS3SegmentHandle.java
- segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/extendeds3/ExtendedS3Storage.java
- segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/filesystem/FileSystemStorage.java
- segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/hdfs/FileSystemOperation.java
- segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/hdfs/HDFSStorage.java
- segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/hdfs/UnsealOperation.java
- segmentstore/storage/impl/src/test/java/io/pravega/segmentstore/storage/impl/hdfs/UnsealOperationTests.java
- segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/SyncStorage.java
- segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/mocks/InMemoryStorage.java
- segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/rolling/RollingStorage.java
- segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/rolling/SegmentChunk.java
- segmentstore/storage/src/test/java/io/pravega/segmentstore/storage/rolling/RollingStorageTestBase.java
Fixed a corner case that would cause the Segment Store to create an excessive number of Segment Chunks when the Segment is made up entirely of transactions. Full repro case is detailed in the accompanying issue; here's a sample scenario:
- Segment S is initially empty (has no chunks)
- We have transactions T0..TN that need to be merged into S
- T0 is merged using header merge since S has no chunks. After this, S is made up of a number of chunks, the last of which is sealed (since transactions are sealed prior to merging).
- Subsequent mergers will still use header merge method since the last chunk of S is sealed, even if they could otherwise fit entirely into S's last chunk.
This change unseals the last chunk of a Segment after a successful header merge. This …
> Issue 2180: (SegmentStore) Reducing number of SegmentChunks during transaction merges

- controller/src/main/java/io/pravega/controller/server/ControllerServiceMain.java
- controller/src/main/java/io/pravega/controller/server/ControllerServiceStarter.java
- controller/src/main/java/io/pravega/controller/server/Main.java
If during shutdown in ControllerServiceStarter, some component's shutdown fails, an exception can be thrown all the way to Main.java whereby killing the main thread. 
However, if our executors have not been shutdown, then we have threads running for the process and the process itself is not terminated. 
This can cause controller process to continue running despite ZK session expiration. 
Note: this is a possible reason for the issue observed. But since we dont have logs to corroborate this line of reasoning, we are going with this fix and will see if the observed state reproduces. 
Fixes issue #2174
Controller process, upon encountering zk session expiry, is supposed to perform graceful shutdown of all its …
> Issue 2174: Controller instance does not exit upon receiving ZK session expiry

- config/config.properties
- segmentstore/server/host/src/main/java/io/pravega/segmentstore/server/host/ServiceStarter.java
- segmentstore/server/host/src/test/java/io/pravega/segmentstore/server/host/ExtendedS3IntegrationTest.java
- segmentstore/server/host/src/test/java/io/pravega/segmentstore/server/host/FileSystemIntegrationTest.java
- segmentstore/server/host/src/test/java/io/pravega/segmentstore/server/host/HDFSIntegrationTest.java
- segmentstore/server/host/src/test/java/io/pravega/segmentstore/server/host/handler/PravegaRequestProcessorTest.java
- segmentstore/server/src/main/java/io/pravega/segmentstore/server/containers/StreamSegmentMapper.java
- segmentstore/server/src/main/java/io/pravega/segmentstore/server/store/ServiceBuilder.java
- segmentstore/server/src/main/java/io/pravega/segmentstore/server/store/ServiceConfig.java
- segmentstore/server/src/main/java/io/pravega/segmentstore/server/writer/SegmentAggregator.java
- segmentstore/server/src/main/java/io/pravega/segmentstore/server/writer/StorageWriter.java
- segmentstore/server/src/test/java/io/pravega/segmentstore/server/writer/SegmentAggregatorTests.java
- test/integration/src/main/java/io/pravega/test/integration/selftest/adapters/SegmentStoreAdapter.java
Split the Common SegmentStore Thread Pool in two:
- Storage Pool: every operation executed in `Storage` (essentially what `SyncStorage` is run on). This is exclusively for the IO intensive operations that the Storage adapters run (all Storage adapters are non-async, and the `AsyncStorageWrapper` uses a thread pool to run those tasks on). 
- Core Pool: everything else (except BookKepeer and Netty - those haven't changed).
- This includes `StorageWriter`, which is a SegmentStore component that picks data from `DurableLog` and issues Storage requests (while the StorageWriter executes on the Core pool, the Storage requests are run on the Storage Pool (see bullet above)).
Updated some callbacks to better ensure that they are executed on the proper thread pool (in …
> Issue 2188: (SegmentStore) Split the common Thread Pool into Core and Storage

- segmentstore/server/src/main/java/io/pravega/segmentstore/server/containers/StreamSegmentContainerMetadata.java
- segmentstore/server/src/main/java/io/pravega/segmentstore/server/writer/SegmentAggregator.java
- segmentstore/server/src/main/java/io/pravega/segmentstore/server/writer/StorageWriterFactory.java
- segmentstore/server/src/main/java/io/pravega/segmentstore/server/writer/WriterDataSource.java
- segmentstore/server/src/test/java/io/pravega/segmentstore/server/containers/StreamSegmentContainerMetadataTests.java
- segmentstore/server/src/test/java/io/pravega/segmentstore/server/writer/TestWriterDataSource.java
Fixed a bug where the SegmentStore would incorrectly issue delete requests for transactions that have already been fully merged in Tier2 Storage or aborted (deleted). Such requests, while not harmful, would potentially create unnecessary load on the Storage adapter by issuing bogus delete requests, which may affect performance.
Details:
- `StreamSegmentContainerMetadata`: Fixed `deleteStreamSegment` to not include Transactions for a parent Segment that do not exist in Storage anymore (this includes deleted transactions and transactions that have been merged in Storage).
- `SegmentAggregator`: removed redundant call that would achieve the same effect as the code executing right before that.
Fixes #2191.
See …
> Issue 2191: (SegmentStore) Do not attempt to delete already deleted transactions

- build.gradle
- standalone/src/main/java/io/pravega/local/InProcPravegaCluster.java
Ensure REST APIs works on pravega container when started in standalone mode.
Fixes #2178 
Ensure, we have handle different JAX-RS (jersey) versions part of segmentstore and controller.
Verified that REST APIs work with container based standalone.
Steps to test it
```
* ./gradlew clean buildPravegaImage
* docker run --rm -it -e HOST_IP=10.0.2.15 -p 9090:9090 -p 12345:12345 -p 9091:9091 -p 10000:10000 pravega/pravega:latest standalone
*  curl http://localhost:9091/v1/scopes
Output :{"scopes":[{"scopeName":"_system"}]}
```
> Issue 2178: Ensure REST APIs works on container based pravega-standalone.

- gradle.properties
* Change Pravega version in gradle.properties to 0.3.0-SNAPSHOT.
Fixes #2205 
There is no functional change, only a property in `gradle.properties`.
> Issue 2205: Change Pravega version in master to 0.3.0-SNAPSHOT

- build.gradle
Added jersey dependency to the standalone project for the `InProcPravegaCluster` to work properly 
To resolve the build dependency for the `flink-connector` project which is using `InProcPravegaCluster` for running the test modules
Verified building `flink-connector` with the changes and it is working fine.
> Issue 2207: Fixed jersey dependency for the controller service

- gradle.properties
* Changes the Pravega version in gradle.properties to 0.2.1-SNAPSHOT
Fixes #2220 
There is no code change, only gradle configuration.
Build and verify that the version is as expected.
> Issue 2220: Change version to 0.2.1-SNAPSHOT in r0.2

- client/src/main/java/io/pravega/client/segment/impl/SegmentOutputStreamImpl.java
- client/src/test/java/io/pravega/client/segment/impl/SegmentOutputStreamTest.java
Ensure state.connection is cleared upon exceptions during `SegmentOutputStreamImpl#reconnect()`
Fixes #2211 
Ensure state.connection is cleared incase of ConnectionFailedException while sending WireCommand.SetupAppend.
> Issue 2211: Ensure state.connection is cleared incase of exceptions during SegmentOutputStreamImpl#reconnect()

- client/src/main/java/io/pravega/client/segment/impl/SegmentOutputStreamImpl.java
- client/src/test/java/io/pravega/client/segment/impl/SegmentOutputStreamTest.java
Ensure state.connection is cleared upon exceptions during SegmentOutputStreamImpl#reconnect()
Fixes #2211 
See PR #2212 
See PR #2212
> Issue 2211: Ensure state.connection is cleared upon exceptions during SegmentOutputStreamImpl#reconnect()

- docs/basic-reader-and-writer.md
Remove AckFuture references from documentation.
Fixes #2231 
Removes AckFuture reference from basic-reader-and-writer.md.
> Issue 2231: Remove redundant AckFuture reference from documentation.

- controller/src/main/java/io/pravega/controller/store/stream/AbstractStreamMetadataStore.java
If we recreate a stream, we can get a response from the store saying "Stream_exists" but we dont tackle this and set metrics values based on the configuration. This results in metrics being set to incorrect value. 
Fixes issue 2164
Adds a check that only for new stream creation do we add the metric. If its a recreation, then dont update the metric. 
All existing tests should pass.
> Issue 2164: Trying to recreate a stream can let stream specific metrics get reset to original values

- segmentstore/server/host/src/main/java/io/pravega/segmentstore/server/host/handler/PravegaConnectionListener.java
- test/integration/src/main/java/io/pravega/test/integration/demo/StartLocalService.java
- test/integration/src/main/java/io/pravega/test/integration/demo/StartReader.java
- test/integration/src/main/java/io/pravega/test/integration/demo/StartWriter.java
* Changes port in StartLocalService to 6000
* Replaces `localhost` in `StartReader` and `StartWriter`
* Changes the name in the constructor of `PravegaConnectionListener` to listen on all addresses.
Fixes #2229 
Changes the service port in`StartLocalService` and updates other classes that rely on the port constant.
To make it work with both `StartLocalService` and `standalone`, I have changed some of the host names. Specifically, `standalone` is picking my external IP, while `StarLocalService` ends up using `localhost` because of how `PravegaConnectionListener` initializes. Consequently, I have made the following changes:
* Give the local IP rather …
> Issue 2229: Fix ports in StartLocalService

- config/config.properties
- segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/bookkeeper/BookKeeperConfig.java
- segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/bookkeeper/BookKeeperLogFactory.java
Added the ability to configure the timeout for BookKeeper reads. Previously, this would be left as a BK default (5s) and the user would not be able to change it.
Fixes #2235 
Explicitly sets the BK Read timeout based on a config value.
Code review. This is just passing through a config value to the BK client.
> Issue 2235: Made BookKeeper read timeout configurable

- client/src/main/java/io/pravega/client/netty/impl/ConnectionFactoryImpl.java
- client/src/main/java/io/pravega/client/stream/impl/EventStreamReaderImpl.java
- test/integration/src/test/java/io/pravega/test/integration/endtoendtest/EndToEndChannelLeakTest.java
Ensure reader does not leak connection on encountering a sealed segment and during segment re-balance.
Fixes #2243 
* Uses `io.netty.channel.group.ChannelGroup` to track connections/open sockets to Segment store.
* Reader now does not leak a connection on encountering a sealed segment.
* Ensure reader closes connection when it releases a segment to other readers.
> Issue 2243: Ensure connections are closed by the reader 

- segmentstore/server/host/src/test/java/io/pravega/segmentstore/server/host/ExtendedS3IntegrationTest.java
- segmentstore/server/host/src/test/java/io/pravega/segmentstore/server/host/FileSystemIntegrationTest.java
- segmentstore/server/host/src/test/java/io/pravega/segmentstore/server/host/HDFSIntegrationTest.java
* Configures rocksdb to use a temporary directory in each of these test classes: HDFSIntegrationTest, FileSystemIntegrationTest, ExtendedS3IntegrationTest. 
Fixes #2246 
The code changes primarily configures rocksdb to use a temporary directory created for the test case. It also makes the use of `File` uniform across the end-to-end tests, and checks that the `File` reference is not null before trying to close it.
To avoid code redundancy, I tried to configure the rocksdb dir in `StreamSegmentStoreTestBase`, bout couldn't find a very clean way to do it without further changes.
Run tests in `segmentstore/server/host`
> Issue 2246: Create temporary directories for rocksdb in end-to-end tests

- client/src/main/java/io/pravega/client/batch/BatchClient.java
- client/src/main/java/io/pravega/client/batch/SegmentInfo.java
- client/src/main/java/io/pravega/client/batch/impl/BatchClientImpl.java
* Add Javadocs for SegmentInfo
* Remove confusing parameter "endingOffset"
* Fix bug where two argument readSegment would start from offset 0.
Fixes #2215
Attempts to remove some confusion sounding when iterators will stop when reading from the batch client.
Unfortunately there are no integration tests using the BatchApi at the moment.
> Issue 2215: [BatchClient] drop endingOffset parameter of readSegment, improved javadoc

- segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/bookkeeper/BookKeeperLog.java
- segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/bookkeeper/BookKeeperLogFactory.java
- segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/bookkeeper/LedgerMetadata.java
- segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/bookkeeper/Ledgers.java
- segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/bookkeeper/LogMetadata.java
- segmentstore/storage/impl/src/test/java/io/pravega/segmentstore/storage/impl/bookkeeper/BookKeeperLogTests.java
- segmentstore/storage/impl/src/test/java/io/pravega/segmentstore/storage/impl/bookkeeper/LogMetadataTests.java
* Keeps track of Ledger Status
* Removes empty ledgers from BookKeperLog metadata
* Deletes empty ledger removed in step 2 above.
Fixes #2234.
During each initialization, the `BookKeeperLog` creates a new BK Ledger and adds it to the BookKeeperLog metadata (stored in ZK). However, if, after this, the Container Recovery fails or otherwise succeeds but it doesn't write data to it until the next failover, we can end up with a lot of empty ledgers in the Log, which will significantly slow down future recoveries. The first scenario (recovery failure) is more likely to lead to such a situation, since whatever problem caused it to fail in the first place will occur every subsequent time.
To alleviate this, the …
> Issue 2234: (Segment Store) Cleaning up empty ledgers upon recovery

- controller/src/main/java/io/pravega/controller/eventProcessor/impl/EventProcessorGroupImpl.java
Disable automatic checkpoints for readergroups used in controller's event processors. 
Fixes #2254.
Uses disableAutomaticCheckpoints on readergroup config for creating controller readergroups.
All exiting tests should pass.
> Issue 2254: Disable auto-checkpointing for readers used in controller's event processor 

- segmentstore/contracts/src/main/java/io/pravega/segmentstore/contracts/TooManyAttributesException.java
- segmentstore/server/host/src/main/java/io/pravega/segmentstore/server/host/handler/AppendProcessor.java
- segmentstore/server/src/main/java/io/pravega/segmentstore/server/AttributeSerializer.java
- segmentstore/server/src/main/java/io/pravega/segmentstore/server/SegmentMetadata.java
- segmentstore/server/src/main/java/io/pravega/segmentstore/server/logs/SegmentMetadataUpdateTransaction.java
- segmentstore/server/src/test/java/io/pravega/segmentstore/server/logs/ContainerMetadataUpdateTransactionTests.java
1. Defined a hard limit on how many attributes a Segment can have at any given time.
2. Enforcing this limit upon Segment updates via any operation that can alter attributes (at this time: `append` and `updateAttributes`). If an operation would have the effect of exceeding this limit, it will be rejected with `TooManyAttributesException`.
NOTE: The Client and/or `PravegaConnectionListener`/`PravegaRequestProcessor`/`AppendProcessor` will need some updating to be able to handle this exception. Please refer to issue #2239. 
Fixes #2233.
Defined a hardcoded limit of Segment attributes and enforcing it in Operation pre-processing.
New unit test added.
> Issue 2233: (SegmentStore) Limiting maximum number of Segment Attributes

- common/src/main/java/io/pravega/common/concurrent/Services.java
- segmentstore/server/src/main/java/io/pravega/segmentstore/server/Container.java
- segmentstore/server/src/main/java/io/pravega/segmentstore/server/ContainerOfflineException.java
- segmentstore/server/src/main/java/io/pravega/segmentstore/server/OperationLog.java
- segmentstore/server/src/main/java/io/pravega/segmentstore/server/containers/ReadOnlySegmentContainer.java
- segmentstore/server/src/main/java/io/pravega/segmentstore/server/containers/StreamSegmentContainer.java
- segmentstore/server/src/main/java/io/pravega/segmentstore/server/logs/DurableLog.java
- segmentstore/server/src/main/java/io/pravega/segmentstore/server/logs/DurableLogConfig.java
- segmentstore/server/src/main/java/io/pravega/segmentstore/server/store/StreamSegmentContainerRegistry.java
- segmentstore/server/src/test/java/io/pravega/segmentstore/server/TestDurableDataLog.java
- segmentstore/server/src/test/java/io/pravega/segmentstore/server/containers/StreamSegmentContainerTests.java
- segmentstore/server/src/test/java/io/pravega/segmentstore/server/containers/StreamSegmentMapperTests.java
- segmentstore/server/src/test/java/io/pravega/segmentstore/server/logs/DurableLogTests.java
- segmentstore/server/src/test/java/io/pravega/segmentstore/server/logs/OperationProcessorTests.java
- segmentstore/server/src/test/java/io/pravega/segmentstore/server/store/StreamSegmentContainerRegistryTests.java
- segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/bookkeeper/BookKeeperLog.java
- segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/bookkeeper/LogMetadata.java
- segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/DataLogDisabledException.java
- segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/DurableDataLog.java
- segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/mocks/InMemoryDurableDataLog.java
- segmentstore/storage/src/test/java/io/pravega/segmentstore/storage/DurableDataLogTestBase.java
* Added the ability to take Segment Containers offline and back online
Fixes #208.
Added the ability to take Segment Containers offline and back online
- **Offline Mode**: Segment Container will appear as `Started` (so that the Controller doesn't try to bounce it again), but it will reject any external operations. In addition, no internal sub-services will function.
- Added the ability to enable or disable a Tier1 Data Log. 
- In `BookKeeperLog`, this will set a flag on the LogMetadata and immediately persist it to ZK.
- A disabled log will only load the metadata from ZK, but will not attempt to update it or otherwise perform fencing.
- Disabling it requires ownership (fence out), while enabling does not …
> Issue 208: (SegmentStore) Taking SegmentContainers Offline

- controller/src/main/java/io/pravega/controller/server/retention/StreamCutBucketService.java
Signed-off-by: Shivesh Ranjan <shivesh.ranjan@emc.com>
Fixes issue 2276 where NPE can be caused if dostop is called immediately after awaitStarted and it wins the race in accessing notificationLoop field before  it is set. 
Fixes #2276
Adds a new latch that waits on notification loop to be set. 
All existing tests should pass
> Issue 2276: Sporadic build failure, NPE in ZkStoreRetentionTest > testOwnershipOfExistingBucket 

- client/src/main/java/io/pravega/client/segment/impl/SegmentInputStreamImpl.java
- client/src/test/java/io/pravega/client/segment/impl/SegmentInputStreamTest.java
Previously if `AsyncSegmentInputStream` threw a `RetriesExhaustedException`, the `issueRequestIfNeeded()` method would get invoked creating a new request, then when `handleRequest()` was invoked by the `read()` call, the timeout would be ignored and the call would block. 
This changes the logic to not issue a new request inside of `handleRequest()` so it will instead throw rather than issuing a new request and blocking on it. This will prevent the reader from stalling on one segment following an extended connection failure.
Fixes #2273 
Throws the exception rather than re-issuing the request. This way the request is already completed in `handleRequest()`.
**How …
> Issue 2273: Prevent stalling reader following a connection failure. 

- test/system/src/main/java/io/pravega/test/system/framework/Utils.java
- test/system/src/main/java/io/pravega/test/system/framework/services/docker/PravegaControllerDockerService.java
- test/system/src/main/java/io/pravega/test/system/framework/services/marathon/PravegaControllerService.java
- test/system/src/test/java/io/pravega/test/system/RetentionTest.java
1. New system test is added, with focus on `retention`.
2. Controller is configured with `retention frequency` of `2 * 60 s`.
We need system tests where controller workflows like truncate, update is exercised.
Fixes #1960 
Adds a very simple retention test, where the controller is configured with `retention frequency` of  2mins, a stream is created with a retention policy of 1 min, an event is written to a stream and read after 4 mins of sleep. It is verified that data is lost. The reader only reads `null` event.
> Issue 1960: Simple retention system test

- controller/src/main/java/io/pravega/controller/server/eventProcessor/requesthandlers/TruncateStreamTask.java
- controller/src/main/java/io/pravega/controller/server/retention/StreamCutBucketService.java
- controller/src/main/java/io/pravega/controller/store/stream/ZKStoreHelper.java
- controller/src/main/java/io/pravega/controller/task/Stream/StreamMetadataTasks.java
- controller/src/test/java/io/pravega/controller/store/stream/ZKStoreHelperTest.java
1. ZkStoreHelper.createEphemeral node to actually create ephemeral node
2. Use map.computeIfAbsent instead of putIfAbsent in StreamCutBucketService while adding new stream. 
3. Add more info and debug logging for retention workflow
Fixes #2312.
There is a bug in ZkStoreHelper's helper method for creating ephemeral node where CreateMode.Ephemeral flag is not passed. 
Because of this issue retention buckets were not failed over in case of owning controller instance failures. So we faced system test failure. 
Apart from that, from the logs we noticed that two background processing for same stream was getting invoked because we were actually doing …
> Issue 2312: Create node with Ephemeral mode in ZkStoreHelper.createEphemeralZNode mode

- build.gradle
Remove deprecated Gradle features from `build.gradle`.
Fixes #2320
Update  `build.gradle `to remove the following warning observed during builds
```
Deprecated Gradle features were used in this build, making it incompatible with Gradle 5.0.
See https://docs.gradle.org/4.5/userguide/command_line_interface.html#sec:command_line_warnings
```
Verified that all the tests pass successfully.
> Issue 2320: Remove deprecated gradle api usage in build.gradle.

- client/src/main/java/io/pravega/client/state/StateSynchronizer.java
- client/src/main/java/io/pravega/client/state/impl/StateSynchronizerImpl.java
- client/src/main/java/io/pravega/client/stream/impl/CheckpointState.java
- client/src/main/java/io/pravega/client/stream/impl/ReaderGroupState.java
- client/src/main/java/io/pravega/client/stream/impl/ReaderGroupStateManager.java
- client/src/test/java/io/pravega/client/state/impl/SynchronizerTest.java
- client/src/test/java/io/pravega/client/stream/impl/ReaderGroupStateManagerTest.java
- client/src/test/java/io/pravega/client/stream/impl/StreamSegmentsTest.java
Add support for compaction in ReaderGroupState
Fixes #2222 . Should prevent the reader group state from growing over time. 
Adds a compact call to ReaderGroupState that serializes the object using Java serialization. 
This change also converts CheckpointState from a threadSafe class to one that is not-thread safe, as Java serialization does not play well with locks. This is OK to do because it was/is always only accessed from within ReaderGroupState under it's lock. 
Added a new test to cover compaction. All existing code paths should be unaffected.
> Issue 2222: Compact reader group state.

- client/src/main/java/io/pravega/client/stream/impl/ReaderGroupState.java
- client/src/main/java/io/pravega/client/stream/impl/ReaderGroupStateManager.java
- client/src/test/java/io/pravega/client/stream/impl/ReaderGroupStateManagerTest.java
- client/src/test/java/io/pravega/client/stream/impl/ReaderGroupStateTest.java
Fix bug that prevented reader groups from properly rebalancing.
Fixes #2298
There was a bug where the function to rank the readers in terms of ownership was using the wrong map, and was not taking into account the number of segments assigned. This fixes that bug and adds test coverage.
New tests should pass.
> Issue 2298: Fix reader rebalance bug, and add test coverage

- common/src/main/java/io/pravega/common/io/serialization/RevisionDataInput.java
- common/src/main/java/io/pravega/common/io/serialization/RevisionDataInputStream.java
- common/src/main/java/io/pravega/common/io/serialization/RevisionDataOutput.java
- common/src/main/java/io/pravega/common/io/serialization/RevisionDataOutputStream.java
- common/src/main/java/io/pravega/common/io/serialization/VersionedSerializer.java
- common/src/test/java/io/pravega/common/io/serialization/RevisionDataStreamCommonTests.java
- common/src/test/java/io/pravega/common/io/serialization/VersionedSerializerTests.java
Made a few improvements to VersionedSerialization
- Renamed `writeVersion()` to `getWriteVersion()` in `SingleType`
- Added support for encoding and decoding arrays.
Fixes #2345.
New code for encoding/decoding arrays.
Renamed `writeVersion` to `getWriteVersion`
Unit tests.
> Issue 2345: VersionedSerialization improvements 

- client/src/main/java/io/pravega/client/netty/impl/ConnectionFactoryImpl.java
- client/src/main/java/io/pravega/client/netty/impl/RawClient.java
- test/integration/src/main/java/io/pravega/test/integration/utils/SetupUtils.java
- test/integration/src/test/java/io/pravega/test/integration/SingleThreadEndToEndTest.java
Avoid calling connection.join() in the RawClient because it is running in the background thread pool.
This should prevent integration tests from failing on single core systems. See #2388
Uses compose instead of join.
New test added.
> Issue 2388: Prevent blocking in background threadpool.

- controller/src/test/java/io/pravega/controller/util/RetryHelperTest.java
We check for delay to be strictly greater than 1 second when we introduce a delay of one second. 
We should have a greater than or equal to check because the clock delay could be exactly equal when looking at time in millis. 
Fixes #2392
1. changes milli second precision to nano second precision. 
2. change the check to be greater than equal to one second as we request Scheduled Executor to introduce a delay of 1 second. 
Test should pass consistently.
> Issue 2392: RetryHelperTest.testLoopWithDelay sporadic failure

- client/src/main/java/io/pravega/client/stream/impl/ReaderGroupStateManager.java
- client/src/test/java/io/pravega/client/stream/impl/ReaderGroupStateManagerTest.java
Prevent an NPE in the logic to acquire a segment in the reader. 
Fixes #2407
Fix the broken build:
https://travis-ci.org/pravega/pravega/builds/359575090?utm_source=slack&utm_medium=notification
Returns an empty map instead of null.
> Issue 2407: Prevent NPE in acquireSegment logic.

- test/integration/src/test/java/io/pravega/test/integration/ReadTest.java
Fixed two read tests to expect Future reads when reading from the Store. These tests were failing intermittently and were caused due to a recent behavioral change in the Segment store where we ack earlier (after writing to Tier1 but before writing to the ReadIndex/cache) - see #1702. In that case, the Store will return a Future read, which will be fulfilled very soon - when the data is inserted into the cache.
This PR updates these two tests to expect such a behavior.
Fixes #2409.
Fixed two unit/integration tests.
Run the unit tests a sufficiently large number of times.
> Issue 2409: Fix intermittent failures with ReadTest integration tests

- segmentstore/server/src/main/java/io/pravega/segmentstore/server/logs/OperationProcessor.java
Reporting the whole size of the Operation Queue, including the items that were just fetched.
Previously we were only reporting the size of the queue after we fetched the items, thus consistently under-reporting its size.
Fixes #2412.
Better metric reporting.
Verify metrics in perf tests.
> Issue 2412: (SegmentStore) Fix operation_queue_size metric

- build.gradle
- gradle/mkdocs.gradle
**Changelog description**
* Adds a flag to enable mkdocs plugin to generate site documentation.
Fixes #2423
To support `flink-connector` build (https://github.com/pravega/flink-connectors/issues/112) where `pravega` is referenced as a git sub-module and the usage of `mkdocs` plugin is broken since the plugin is not able to find git configuration file (sub-modules don't keep the same configuration file as regular project) which is used to derive the `repoUri`.
This change adds a flag to enable the mkdocs plugin. If disabled, then the described problem won't manifest.
Build pravega and flink-connector project and make sure there is no error or side-effects due to this configuration
> Issue 2423: Flag to enable mkdocs plugin

- README.md
Some changes in `pravega.io`  website and directory structure of `.md` docs in pravega are causing some links in `README.md` to break. They are fixed. 
Fixes #2427 
Corrects the links pointed to `pravega.io` and  `.md` docs in pravega.
No functional change, the build should pass.
> Issue 2427: Fix broken links in README.md

- documentation/src/docs/state-synchronizer-design.md
- documentation/src/docs/state-synchronizer.md
- documentation/src/docs/transactions.md
Fixes #2445 
A few places in the docs had the old com[./]emc[./]pravega naming and old package structure for clients. This updates them.
I wanted to know how to do something with Pravega. Links in some of the docs were broken which made it difficult to follow along. This fixes them.
Go to the links in the diff view, they work.
> Issue 2245: Updated docs with io.pravega links (remove old com.emc.pravega)

- client/src/main/java/io/pravega/client/batch/SegmentRange.java
- client/src/main/java/io/pravega/client/batch/impl/SegmentRangeImpl.java
- client/src/test/java/io/pravega/client/batch/impl/SegmentRangeImplTest.java
* Changes the API call from getScopeName to getScope to be consistent with the Stream interface.
* Ensures SegmentRange.getScope() returns the scope of the stream.
Fixes #2425 
Updated SegmentRange apis to 
`io.pravega.client.batch.SegmentRange#getStream` and `io.pravega.client.batch.SegmentRange#getScope`.
All existing tests should continue to pass.
> Issue 2425: BugFix: Ensure SegmentRange.getScope() returns the scope of the stream

- client/src/main/java/io/pravega/client/stream/notifications/notifier/SegmentNotifier.java
- client/src/test/java/io/pravega/client/stream/notifications/SegmentNotifierTest.java
- test/integration/src/test/java/io/pravega/test/integration/ReaderGroupNotificationTest.java
Trigger a notification with the initial number of segments as soon as the user registers a Segment listener.
Fixes #2429 
Triggers a Segment Notification with the initial number of Segments as soon as the user registers a Segment Listener. Subsequent segment notifications are generated only if there is a change in the number of segments.
All tests should continue to pass.
> Issue 2429: Get initial number of segments via SegmentNotifier.

- docker/bookkeeper/Dockerfile
- gradle.properties
The current Version 4.6.1 which we use in docker file of bookkeeper unavailable. Modifying the repo to fetch  the version which is used in `grade.properties`
Changing Bookkeeper v4.6.1 to v4.5.0 and pull it from a different repo.
Fixes #2347 
* Changes bk version in 1. bookkeeper docker file
* Changing the repo from which bk server is downloaded in bookkeeper dockerfile.
Build and all tests should pass
> Issue 2347: Match the bookkeeper server version used for system tests with the one used for integration tests

- controller/src/main/java/io/pravega/controller/store/stream/ZKStream.java
- controller/src/test/java/io/pravega/controller/store/stream/ZkStreamTest.java
Handles DataNotFoundException in getCurrentTransactions store api. 
Removes all transactions for which DataNotFoundException was thrown and returns the remainder. 
Fixes #2481 
ZkStreamStore.getCurrentTxns is a two step process-
gets all txn ids by querying path for children of active epoch znode.
gets records for each txn id.
If between 1 and 2 txns records are deleted (by virtue of txn completing) then we can get DataNotFoundException
So in getCurrentTransactions, we check if DataNotFoundExcecption is thrown, and ignore it and remove such transactions from the response. 
Unit test added
> Issue 2481: ZkStreamStore.getCurrentTxns should not throw DataNotFoundException 

- client/src/main/java/io/pravega/client/ClientConfig.java
The env vars are generally in the format `pravega_client_auth_*`. The extractor code needs to replace `_` with `.`.
This fixes #2478.
Fix issue with extracting config from env vars.
Set env vars before running the client.
> Issue 2478: Fix issue with extracting config from env vars.

- segmentstore/server/host/src/main/java/io/pravega/segmentstore/server/host/ServiceStarter.java
- Ensure that the server process exits upon fatal startup error.
- Closes #2353 
- Improve the robustness of Pravega in container environments.
Manual test: 
1. Delete the BK ledger znode from BK, which will cause the segment store to fail during startup.  This replicates the valid scenario of BK and segment store being started simultaneously.
2. Start the segment store.
3. Observe that the segment store process exits as expected.   It is expected that the cluster manager will restart the segment store in this situation.
> issue-2353 ensure that the server process exits upon fatal startup error

- build.gradle
- gradle.properties
Signed-off-by: Eron Wright <eronwright@gmail.com>
- update boringssl dependency to 2.0.8.Final
- fix shading issue for flink connector
- Closes #2464
> [issue-2464] update boringssl dependency to 2.0.8.Final

- common/src/main/java/io/pravega/common/auth/AuthException.java
- common/src/main/java/io/pravega/common/auth/AuthorizationException.java
- controller/src/main/java/io/pravega/controller/server/rest/resources/StreamMetadataResourceImpl.java
- controller/src/main/java/io/pravega/controller/server/rpc/auth/PravegaAuthManager.java
- controller/src/main/java/io/pravega/controller/server/rpc/auth/TestAuthHandler.java
- controller/src/test/java/io/pravega/controller/rest/v1/Failing403StreamMetaDataTests.java
- controller/src/test/java/io/pravega/controller/rest/v1/FailingSecureStreamMetaDataTests.java
* Modifies the signature of the `authenticate` method in `StreamMetadataResourceImpl` to throw `AuthException` containing the appropriate return code.
Fixes #2450 
When a user calls a REST API,  a future course of action may depend on the type of authentication error. (a 401 error will suggest authentication error where as a 403 error will suggest authorization error).
In case of grpc this is not necessary as the caller need not know whether this is authorization error or authentication error as it may give rogue user a chance to advance attacks by validating his guessed password.
The changes here modify the signature of the `authenticate` method in …
> Issue 2450: Separate 401 and 403 returns for REST API.

- controller/src/test/java/io/pravega/controller/server/eventProcessor/ScaleRequestHandlerTest.java
This change set restructures the test code to perform one step at a time such that if there is a timeout, we will know the exact step that may have caused it.  
We have not been able to reproduce the issue. But the test was not well written and hence timeouts did not point to a potential source of problem. 
Restructure the test code:
Earlier we mocked the writer to receive and expect specific events and use futures to ensure coordination and signal the test code to proceed to subsequent steps. 
We have replaced the mock writer that used futures for coordination with a mock writer that simply has a queue. The test code checks to verify if an expected event has been posted or not at the end of a particular step. 
So …
> Issue 2402: Intermittent test failure. Timeout in ScaleRequestHandlerTest:testScaleRequest

- build.gradle
The suspend flag was turned on for debug option for `standalone` in one of the recent changes. Setting it back.
This fixes #2487.
Sets the flag to `suspend=n`
Build the standalone distribution and run the standalone process.
> Issue 2487: Remove suspend flag from debug options for standalone.

- build.gradle
- config/standalone-config.properties
- docker/pravega/entrypoint.sh
- standalone/src/main/java/io/pravega/local/InProcPravegaCluster.java
- standalone/src/main/java/io/pravega/local/LocalPravegaEmulator.java
- standalone/src/main/java/io/pravega/local/SingleNodeConfig.java
- standalone/src/test/java/io/pravega/local/InProcPravegaClusterTest.java
- Move security related config in standalone from hard coding to config.
- Update tests to use this.
This fixes #2466. The config can be specified through system properties. Currently standalone does not pick the config up from config properties.
Removes hard coding of security related config from `standalone` and accepts it from system properties.
1. Unit tests 
2. Specify properties through system properties and see them changed in the standalone/
> Issue 2466: Accept standalone config through system properties.

- segmentstore/server/host/src/test/java/io/pravega/segmentstore/server/host/S3ClientWrapper.java
- segmentstore/storage/impl/src/test/java/io/pravega/segmentstore/storage/impl/extendeds3/S3FileSystemImpl.java
- segmentstore/storage/impl/src/test/java/io/pravega/segmentstore/storage/impl/extendeds3/S3ImplBase.java
- segmentstore/storage/impl/src/test/java/io/pravega/segmentstore/storage/impl/extendeds3/S3JerseyClientWrapper.java
- segmentstore/storage/impl/src/test/java/io/pravega/segmentstore/storage/impl/extendeds3/S3ProxyImpl.java
- segmentstore/storage/src/test/java/io/pravega/segmentstore/storage/StorageTestBase.java
Implement `deleteObjects` function in `S3FileSystemImpl`.
Fixes #2493.
Implements `deleteObject` functionality.
The warning message `Unable to acknowledge already processed operation ...` is not observed during `ExtendedS3IntegrationTest`
> Issue 2493: Implement deleteObjects API in S3FileSystemImpl, call it in the wrapper.

- client/src/main/java/io/pravega/client/stream/EventWriterConfig.java
- test/integration/src/test/java/io/pravega/test/integration/endtoendtest/EndToEndTxnWithTest.java
Changes the default client config for transaction timeout. 
Fixes  #2491
Changes the default writer client configuration value for transaction timeout. Presently default is set to 1 hour. And transaction timeout has to be bounded by scale grace period.  
New integration test added which tests different combinations of transaction timeout and scale grace period and verifies them against controller's defaults.
> Issue 2491: EventWriterConfig.getTransactionTimeoutScaleGracePeriod defaults are larger than maximum allowed values on controller

- client/src/main/java/io/pravega/client/segment/impl/SegmentOutputStreamImpl.java
- client/src/main/java/io/pravega/client/stream/impl/ClientFactoryImpl.java
- client/src/main/java/io/pravega/client/stream/impl/EventStreamWriterImpl.java
- client/src/main/java/io/pravega/client/stream/impl/SegmentSelector.java
- client/src/main/java/io/pravega/client/stream/impl/StreamSegments.java
- client/src/test/java/io/pravega/client/stream/impl/EventStreamWriterTest.java
- common/src/main/java/io/pravega/common/concurrent/ExecutorServiceHelpers.java
- segmentstore/server/host/src/main/java/io/pravega/segmentstore/server/host/handler/PravegaRequestProcessor.java
Flush outstanding writes in response to a segment seal
Fixes at least one cause of #2470. In the event of a segment merge, when the first segment seal is encountered it is possible that a second segment has events inflight. If the segment is replaced in EventStreamWriter with its replacement, a new event could arrive and be published to the new segment before the segmentSealed response arrives for the old segment. This would result in the event written after the seal for the other segment and before the seal is received to be out of order.
When the segmentSealed arrives the EventStreamWriter now invokes flush. This should force any outstanding events to be processed (or result in their own segmentSealed) before …
> Issue 2470: Flush outstanding writes in response to a segment seal

- segmentstore/server/src/test/java/io/pravega/segmentstore/server/logs/ContainerMetadataUpdateTransactionTests.java
- segmentstore/server/src/test/java/io/pravega/segmentstore/server/writer/SegmentAggregatorTests.java
- segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/rolling/RollingStorage.java
- segmentstore/storage/src/test/java/io/pravega/segmentstore/storage/rolling/RollingStorageTests.java
Fixed a bug in `RollingStorage` where it was not possible to truncate a sealed segment if the given SegmentHandle was acquired after sealing the segment.
- When calling `openWrite` on a sealed segment, the returned handle is read-only (since no further changes are allowed on the segment)
- When calling `truncate`, `RollingStorage` expected a read-write handle, which was causing the problem described in the issue associated with this change.
- This was changed to accept a read-only handle, but only if the Segment is Sealed (otherwise a read-write handle is required.
- The only difference in truncation between a Sealed and Non-sealed segment is that for a Sealed segment we will not be able to fully truncate the whole segment. Since we cannot modify the header file …
> Issue 2438: (SegmentStore) Cannot truncate sealed segments

- segmentstore/server/src/test/java/io/pravega/segmentstore/server/reading/ContainerReadIndexTests.java
Signed-off-by: Flavio Junqueira <flavio.junqueira@emc.com>
* Increases the timeout of ContainerReadIndexTests to 20 seconds.
Fixes #2520 
Increases the global timeout of `ContainerReadIndexTests`.
Run unit tests.
> Issue 2520: Increase timeout of ContainerReadIndexTests

- client/src/main/java/io/pravega/client/batch/BatchClient.java
- client/src/main/java/io/pravega/client/batch/impl/BatchClientImpl.java
- client/src/test/java/io/pravega/client/batch/impl/BatchClientImplTest.java
Ensure BatchClient handles StreamCut.UNBOUNDED.
Fixes #2518 
Fixes the NPE thrown by BatchClient when StreamCut.UNBOUNDED is passed to `io.pravega.client.batch.BatchClient#getSegments`
All tests should continue to pass.
> Issue 2518: Ensure BatchClient handles StreamCut.UNBOUNDED (BugFix)

- client/src/main/java/io/pravega/client/stream/impl/ReaderGroupStateManager.java
Workaround bug in some versions of `javac`.
In some versions of `javac` the `ReaderGroupStateManager` class does not compile because the compiler is unable to correctly infer the return type of an anonymous function that is at some points returning a `Collections.emptyMap()`. For whatever reason this indirect type inference is causing problems.
Fixes #2505 
This code works around the compiler bug by adding generic type information to those calls even though it is not strictly needed.
There should be no functional changes.
> Issue #2505: Workaround compiler bug.

- client/src/main/java/io/pravega/client/stream/StreamCut.java
- client/src/main/java/io/pravega/client/stream/impl/UnboundedStreamCut.java
- client/src/test/java/io/pravega/client/stream/StreamCutTest.java
Enable `equals()` for StreamCut.UNBOUNDED.
Fixes #2502 
At present `StreamCut.UNBOUNDED` is defined as a lambda. Since equals() for a lambda uses a reference equals does not work for `StreamCut.UNBOUNDED`. Now `StreamCut.UNBOUNDED` is represented by a class which supports equals.
All existing tests should pass, new tests have been added to cover the new API
> Issue 2502: Enable `equals` for StreamCut.UNBOUNDED.

- client/src/main/java/io/pravega/client/segment/impl/AsyncSegmentInputStream.java
- client/src/main/java/io/pravega/client/segment/impl/AsyncSegmentInputStreamImpl.java
- client/src/test/java/io/pravega/client/segment/impl/AsyncSegmentInputStreamTest.java
- test/integration/src/test/java/io/pravega/test/integration/BoundedStreamReaderTest.java
Ensure SegmentTruncatedException is thrown by AsyncSegmentInputStream on receiving WireCommands.SegmentIsTruncated from SegmentStore.
Fixes #2441 
Fixes #2512 
The changes in this pull request ensures
- `AsyncSegmentInputStream `does not retry if `WireCommands.SegmentIsTruncated` message is sent by Segment Store.
- AsyncSegmentInputStream completes the read future with `SegmentTruncatedException`
- `TruncatedDataException` is thrown by `EventStreamReader.readNextEvent()`. On receiving this exception the next `readNextEvent() `api call will cause the reader to read from the next available event.
- `NoSuchEventException` is thrown when EventStreamReader.fetchEvent is …
> Issue 2441: Ensure SegmentTruncatedException is thrown by AsyncSegmentInputStream.

- segmentstore/server/src/main/java/io/pravega/segmentstore/server/attributes/SegmentAttributeIndex.java
- segmentstore/server/src/test/java/io/pravega/segmentstore/server/attributes/ContainerAttributeIndexTests.java
`SegmentAttributeIndex` checks if the main Segment's `isDeleted` flag has been set before making any changes to the Attribute Segment. If so, it automatically deletes the Attribute Segment file. This was originally done as a preemptive operation to make sure this file isn't left orphan.
It turns out that, in some scenarios, this is trying to prematurely delete this Segment. When doing so, the `StorageWriter` stubbornly tries to recreate it, however that operation clashes with this check (again) which tries to delete it. Since neither Create nor Delete are atomic operations in `RollingStorage`, it's possible that concurrent calls to these for the same segment will clash at one point and produce weird results. This is exactly what happened in the error reported in …
> Issue 2538: (SegmentStore) Do not auto-delete Attribute Segment if main Segment is deleted

- segmentstore/server/src/test/java/io/pravega/segmentstore/server/store/StreamSegmentStoreTestBase.java
Signed-off-by: Flavio Junqueira <flavio.junqueira@emc.com>
* Increases `TIMEOUT` constant in StreamSegmentStoreTestBase
* Removes explicit timeout parameter from test case as there is a global timeout set up
Fixes #2250 
This test case has been continuously failing in our internal jenkins build. I have been able to reproduce it on a VM with a single core, and increasing the timeout value makes the test case pass. There is also no indication of another problem, although it is suspicious that it is failing more often now. 
Run tests and jenkins build.
> Issue 2250: HDFSIntegrationTest.testEndToEnd failure

- standalone/src/main/java/io/pravega/local/InProcPravegaCluster.java
Sets the scheme for autoscaler configuration.
This fixes #2559.
Sets proper URI scheme for autoscaler config based on `enableTls` config.
The segmentstore is able to communicate to the controller in a standalone deployment.
> Issue 2559: Setting scheme to `tls` when `enableTls` is set `tcp` otherwise.

- test/system/src/test/java/io/pravega/test/system/RetentionTest.java
*  Asserts that readNextEvent throws `SegmentTruncatedException` 
Fixes #2562 
The system tests currently expects a null event, when a reader asks for the event,  after the expiry of retention time period. But the changes in the PR #2533 ensures a `truncated exception` to be thrown in such cases. 
This discrepancy in the validation of the test needs to be changed.
System tests should pass
> Issue 2562: Assert to truncatedexception while trying to read event after retention time period

- controller/src/main/java/io/pravega/controller/server/eventProcessor/requesthandlers/AutoScaleTask.java
- controller/src/test/java/io/pravega/controller/server/eventProcessor/ScaleRequestHandlerTest.java
- shared/controller-api/src/main/java/io/pravega/shared/controller/event/ScaleOpEvent.java
Signed-off-by: Shivesh <shivesh.ranjan@gmail.com>
We observed that there was a mismatch between range posted in auto-scale event and the range present in metadata store. This led to scale input being declared invalid and hence hot segment was never scaled. 
Fixes #2543
In autoscale task, to compute new ranges we actually did some computations using `double` which can cause precision loss and hence the ranges submitted in scale input did not match that in the metadata store.
The way we were earlier doing new range computation was as follows:
e.g. compute range for a segment S split in 2
```
delta = (s.keyEnd - s.keyStart)/2;
newRanges = [s.keystart, s.keyStart + delta) [s.keyStart + delta, s.keyStart + 2*delta)
``` …
> Issue 2543: Segment range mismatch between auto scale request and range in metadata store

- segmentstore/server/src/test/java/io/pravega/segmentstore/server/containers/StreamSegmentContainerTests.java
- segmentstore/server/src/test/java/io/pravega/segmentstore/server/logs/OperationLogTestBase.java
- Increased segment expiration time in one of the unit tests in `StreamSegmentContainerTests` since it was causing the test to timeout on very slow machines.
- The same pattern was applied on other tests in that class, however I left that expiration to the original value since they are passing correctly, and increasing this expiration would have led to a significant increase in unit test execution time.
- Fixed another set of unit tests by passing in the correct Executor in `OperationLogTestBase` (never use `ForkJoinPool` ...)
Fixes #2555. Note that this failure is due to a different reason than that already fixed by #2561. 
Increases segment expiration timeout in a unit test.
Unit test must …
> Issue 2555: (SegmentStore) Fixed sporadic timeout in unit test

- test/system/src/test/java/io/pravega/test/system/MultiControllerTest.java
As a part of the changes of the PR #2542 ,
`@cleanup` was introduced for controller client unintentionally. 
This is a problem because the createScope method returns a completable future, and we are closing the client before the future returns.
Fixes #2564 
*  Changes the return value of `createScope()`  and `createScopeWithSimpleRetry()` from `CompletableFuture<Boolean>` to `boolean`.
*  Creates `controllerclient` seperately for both `createScope()` and `createScopeWithSimpleRetry()`
as there is some issue in passing around the `controllerclient` from former to later.
* Using `@cleanup` in both the places to ensure client is closed after the scope creation is …
> Issue 2564: Fix the issue with using cleanUp for controller client in multicontroller system test

- segmentstore/server/src/test/java/io/pravega/segmentstore/server/reading/ContainerReadIndexTests.java
Fixed `ContainerReadIndexTests.testCacheEviction`:
- This is a pretty complex test, with a lot of subtleties, mostly due to the fact that it does not have visibility into all the Read Index's internals
- The cause for failure was that the `StreamSegmentReadIndex` class, when processing Tier2 Storage reads, it would execute events in this exact order (deliberately):
1. Successful Tier2 read
2. Ack the caller's Future with the data at hand (since it's already available)
3. Insert into the cache  - this is done after step 2 since the caller does not need to wait on cache insertion if we already have the data.
- The code above is correct, and the problem does not lie in the main code; it is a test issue, for the following reasons
- The test moves on as soon as an …
> Issue 2300: (SegmentStore) Fixed sporadically failing unit test

- client/src/main/java/io/pravega/client/ClientConfig.java
- use the correct default port in `ClientConfig`
- fix #2532 
- manual test using a sample program
Signed-off-by: Eron Wright <eronwright@gmail.com>
> Issue 2532: specify the default port

- client/src/main/java/io/pravega/client/segment/impl/SegmentMetadataClientImpl.java
- client/src/test/java/io/pravega/client/stream/impl/EventStreamReaderTest.java
Ensure `SegmentMetadataClient#getSegmentInfo` propagates NoSuchSegmentException.
Fixes #2594 
`EventStreamReader.readNext()` throws a `TruncatedDataException` if the stream is truncated based on its stream retention policy. Invoking the `readNext()` again will cause the reader to read from the new start offset of the segment.
In case of a lagging reader it can so happen that a reader can encounter `SegmentTruncatedException` and when it tries to fetch the segment's new start offset the segment might have been deleted. Since the segment is deleted the `SegmentMetadataClient#getSegmentInfo` will receive a `NoSuchSegmentException`. The change ensures that this exception is not wrapped inside a `CompletionException`. …
> Issue 2594: Ensure SegmentMetadataClient#getSegmentInfo propagates NoSuchSegmentException.

- segmentstore/contracts/src/main/java/io/pravega/segmentstore/contracts/StreamSegmentStore.java
- segmentstore/server/src/main/java/io/pravega/segmentstore/server/containers/StreamSegmentContainer.java
- segmentstore/server/src/test/java/io/pravega/segmentstore/server/containers/StreamSegmentContainerTests.java
Fixed a bug in `StreamSegmentContainer.getAttributes` where it would incorrectly try to re-cache an Attribute that has a value set to NULL_ATTRIBUTE_VALUE using a conditional update that ensures the value was not present.
Fixes #2596.
Fixes a bug.
Unit tests updated to cover this case.
> Issue 2596: (SegmentStore) Not able to re-cache Extended Attribute with a value of NULL_VALUE

- controller/src/main/java/io/pravega/controller/server/rpc/auth/PravegaInterceptor.java
In case of grpc based authentication, when an auth handler is not specified, the grpc handler code loops through all the handlers and then fails with `UNKNOWN` status. In case of no headers present, the handlers should throw exception.
This fixes #2460.
Throw exception when authentication method is not selected.
In case the method is not specified, authentication error is observed.
> Issue 2460: When sending no credentials, exception returned has UNKNOWN status

- client/src/main/java/io/pravega/client/ClientFactory.java
- client/src/main/java/io/pravega/client/admin/impl/ReaderGroupManagerImpl.java
- client/src/main/java/io/pravega/client/stream/impl/ClientFactoryImpl.java
- client/src/test/java/io/pravega/client/stream/impl/ClientFactoryTest.java
- controller/src/main/java/io/pravega/controller/server/rest/resources/StreamMetadataResourceImpl.java
- Ensure `ClientFactory.close()` always closes the controller client.
- Ensure `StreamMetadataResourceImpl` closes `ClientFactory` which is created while processing `getReaderGroup()` API.
Fixes #2547 
- Ensure `ClientFactory.close()` always closes the controller client, irrespective of whether the controllerclient is created internally or passed to it.
- Ensure `StreamMetadataResourceImpl` closes `ClientFactory` which is created while processing `getReaderGroup()` API.
All the existing tests should pass. Verified that the open sockets are closed after invocation of close() using netstat command.
> Issue 2547: Ensure ClientFactory.close() always closes the Controller client.

- segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/hdfs/HDFSStorage.java
The correct owner will get the owership after this loop goes on for a number equal to the number of segmentstore instances in the race. The upper bound for this is the number of segmentstores in the deployment.
It would be a major change in the segmentstore to determine and pass the number of segment store instances down to the Storage Adapter. Also these details are not necessary for a tier-2 stoarge to know.
I think a compromise can be where we keep the number of retries high enough that the number of segmentstores in a deployment never passes this number. It can be either a very high integer (e.g MAX_INT).
This fixes #2501.
Loop till the race for rename is …
> Issue 2501: Ensure that the race for rename is resolved

- build.gradle
Adding the `pluginlib` path to ensure that the plugin can load its config files and load these.
This PR fixes #2396.
Adds the `pluginlib` path to the classpath.
The plugin config gets picked.
> Issue 2396 : Adding pluginlib to classpath to pickup plugin config.

- documentation/src/docs/basic-reader-and-writer.md
- documentation/src/docs/metrics.md
- documentation/src/docs/reader-group-notifications.md
- documentation/src/docs/rest/restapis.md
- documentation/src/docs/state-synchronizer.md
- documentation/src/mkdocs.yml
The format of code blocks in the documentation is not appropriate and to the mark.
They are to be rendered with the language used in the code.
Fixes #2579 
*  Adds few markdown extensions to `mkdocs.yml`  - the config used for conversion of `.md` files to `.html` files.
*  Adds the required changes  to the code snippets in the documentation
Visit  www.pravega.io/docs/latest
> Issue 2579: Improve the color code and format of code snippets in pravega.io documentation

- segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/bookkeeper/BookKeeperLog.java
- segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/bookkeeper/WriteQueue.java
- segmentstore/storage/impl/src/test/java/io/pravega/segmentstore/storage/impl/bookkeeper/WriteQueueTests.java
- Fixed a condition in `BookKeeperLog.processPendingWrites` (Write Processor) where it would continuously invoke itself in cases when there was no work to be done.
- Even if it doesn't call itself directly, it always invokes the Rollover Processor, which, in turn, always invokes the Write Processor.
- This was fixed by not attempting to execute any writes or invoke the Rollover Processor if we currently have no writes to execute. 
- Fixed a condition in the Write Processor where it would log spurious, yet harmless `ObjectClosedException` or `NullPointerException` when closing the `BookKeeperLog` and there are still writes pending in the queue.
Fixes #2585.
1. Not attempting to execute writes or invoke the Rollover …
> Issue 2585: (SegmentStore) Reduce excessive logging in some situations

- client/src/main/java/io/pravega/client/stream/impl/UTF8StringSerializer.java
- client/src/test/java/io/pravega/client/stream/impl/UTF8StringSerializerTest.java
Signed-off-by: Claudio Fahey <claudio.fahey@emc.com>
Added UTF-8 string serializer.
Currently, events that consist of strings are serialized in Pravega using JavaSerializer. This is not ideal because it is difficult to use in non-Java environments and adds unnecessary framing. This change adds a new UTF-8 string serializer.
This change adds a new UTF-8 string serializer.
See UTF8StringSerializerTest.
> Issue 2606: Added UTF-8 string serializer.

- segmentstore/server/src/main/java/io/pravega/segmentstore/server/reading/ContainerReadIndex.java
- segmentstore/server/src/main/java/io/pravega/segmentstore/server/reading/StreamSegmentReadIndex.java
- segmentstore/server/src/main/java/io/pravega/segmentstore/server/writer/SegmentAggregator.java
- segmentstore/server/src/test/java/io/pravega/segmentstore/server/containers/StreamSegmentContainerTests.java
- segmentstore/server/src/test/java/io/pravega/segmentstore/server/reading/ContainerReadIndexTests.java
- segmentstore/server/src/test/java/io/pravega/segmentstore/server/writer/SegmentAggregatorTests.java
1. Fixed a bug in `SegmentAggregator` where it would swallow an exception thrown by the `ReadIndex` during recovery thus leading to a Segment Merge to not be completed (ever).
2. Fixed a bug  in `SegmentAggregator` where it would not take any action when processing an Merge operation for an empty Source Segment (in some situations).
3. Fixed a bug in the `ReadIndex` where `completeMerge` would incorrectly throw an exception if the Source Segment was empty (it should not, because its `beginMerge` counterpart takes no action on empty source Segments.
Reproduction steps for bug 1:
- In Container Epoch N, a `MergeSegmentOperation` is  received by the `StorageWriter` and applied to Tier2 Storage. The Container shuts down (or is fenced out) after the Tier2 concat …
> Issue 2621: (SegmentStore) Multiple bug fixes relating to merging segments

- common/src/test/java/io/pravega/common/io/serialization/RevisionDataOutputStreamTests.java
Change RevisionDataOutputStreamTests to avoid calling String.getBytes()  (because the default charset varies) and calculate length correctly.
RevisionDataOutputStreamTests was wrongly assuming that String.getBytes() would return arrays of the same length everywhere. 
Fixes the charset to utf-8.
Calculates the length of the compact Int properly, rather than just assuming it's length.
The unit test should pass everywhere reguardless of default charset.
> Issue 2626: Fix variable charset bug.

- client/src/main/java/io/pravega/client/ClientConfig.java
- client/src/test/java/io/pravega/client/CredentialsExtractorTest.java
- standalone/src/test/java/io/pravega/local/InProcPravegaClusterTest.java
- standalone/src/test/java/io/pravega/local/PartialSecurePravegaClusterTest.java
This brings parameters supplied via system properties/environment variables on the same page as defined by a `Credentials` object. Earlier the prefix was sent along with the configuration.
This fixes #2631.
Removes auth related prefix from auth parameters.
Unit tests are updated to cover this functionality. Unit tests should pass.
> Issue 2631: Remove prefix from system properties/env vars for auth parameters

- test/system/src/test/java/io/pravega/test/system/AutoScaleTest.java
- test/system/src/test/java/io/pravega/test/system/PravegaTest.java
- test/system/src/test/java/io/pravega/test/system/ReadTxnWriteScaleWithFailoverTest.java
- test/system/src/test/java/io/pravega/test/system/ReadWithAutoScaleTest.java
Ensure test timeouts are applicable to `@Before` and `@After` methods in system tests.
Fixes #2634 
This change ensures that the system test run does not wait indefinitely for `@Before` / `@After` method of system tests to complete.
The system test run should timeout incase `@After` / `@Before` methods never complete.
> Issue 2634: Ensure timeouts are applicable to @Before and @After methods in system tests.

- client/src/main/java/io/pravega/client/stream/impl/ReaderGroupState.java
- test/integration/src/test/java/io/pravega/test/integration/endtoendtest/EndToEndReaderGroupTest.java
Ensure RemoveReader handles empty `ownedsegments` similar to a null value.
Fixes #2642 
Ensure RemoveReader handles ownedSegments handles empty map.
All the existing tests and system tests should pass.
> Issue 2642: Fix IllegalStateException observed while removing reader.

- client/src/main/java/io/pravega/client/segment/impl/SegmentOutputStreamImpl.java
- client/src/test/java/io/pravega/client/segment/impl/SegmentOutputStreamTest.java
In the event SegmentOutputStream receives a `io.pravega.shared.protocol.netty.WireCommands.SegmentIsSealed`, ensure `SegmentOutpuStream.flush()` is blocked until the `segmentSealedCallback` is invoked.
Fixes #2628 
The `EventStreamWriterImpl#handleLogSealed()` replaces the sealed segment with its successors, resends all the inflight events of the sealed segment and invokes a `flush()` on all the current segment writers. Once a `flush()` is invoked on all the current writers it is possible that some of them also encounter a `SegmentIsSealed` at that time. Now these segments are appended to the sealedSegmentQueue  for sealed segment processing.
In older code the latch `state.waitingInflight` was released and …
> Issue 2628: Fix events out of sequence due to scaling.

- test/system/src/test/java/io/pravega/test/system/AbstractReadWriteTest.java
- test/system/src/test/java/io/pravega/test/system/StreamCutsTest.java
Implemented a system test for StreamCuts (test/system/test/StreamCutsTest.java).
Fixes #2540.
The test creates two streams with different number of segments and it writes some events in them. Given that, the system tests provides the following checks on the operation of StreamCuts API:
- The test checks the operation of `getStreamCuts` by creating a list of StreamCuts that encompasses both streams every certain number of events. 
- The test checks the operation of `endingStreamCuts` and `startingStreamCuts` by asserting that new groups of readers can be initialized at StreamCut intervals and that only events within that intervals are read. 
- The test also checks the operation of `resetReaderGroup` by resetting an …
> Issue 2540: StreamCuts system test

- client/src/main/java/io/pravega/client/stream/ScalingPolicy.java
- client/src/test/java/io/pravega/client/admin/impl/ScalingPolicyTest.java
- controller/src/test/java/io/pravega/controller/server/SegmentHelperTest.java
- controller/src/test/java/io/pravega/controller/server/eventProcessor/ScaleRequestHandlerTest.java
Added precondition checks prior to instantiate `ScalingPolicy` objects (`ScalingPolicy.java`). Moreover, a new test has been added (`ScalingPolicyTest.java`) and two tests have been modified as they were using wrong input parameters to instantiate scaling policies (`SegmentHelperTest.java` , `ScaleRequestHandlerTest.java`)
Fixes #2636.
The code checks that all input parameters to instantiate a `ScalingPolicy` are `>0`. This does not only include to check the number of segments (`numSegments`) as reported in the issue, but also:
- `scaleFactor`: A `scale factor` with value 0 would mean that no split will be created when the scaling event is processed. For actually performing a scale on a segment, this parameter …
> Issue 2636: Adding preconditions on input arguments in ScalingPolicy

- segmentstore/server/src/main/java/io/pravega/segmentstore/server/attributes/ContainerAttributeIndex.java
- segmentstore/server/src/main/java/io/pravega/segmentstore/server/attributes/ContainerAttributeIndexImpl.java
- segmentstore/server/src/main/java/io/pravega/segmentstore/server/attributes/SegmentAttributeIndex.java
- segmentstore/server/src/main/java/io/pravega/segmentstore/server/containers/StreamSegmentContainer.java
- segmentstore/server/src/main/java/io/pravega/segmentstore/server/writer/StorageWriterFactory.java
- segmentstore/server/src/test/java/io/pravega/segmentstore/server/attributes/ContainerAttributeIndexTests.java
- segmentstore/server/src/test/java/io/pravega/segmentstore/server/containers/StreamSegmentContainerTests.java
1. Fixed a bug where a Segment may not be deleted if it is not active in the metadata or if the metadata isDeleted() flag is out-of-sync with Tier2 Storage
- This would manifest itself by a `NullPointerException` being thrown when `StreamSegmentContainer.deleteSegment` is invoked on such a segment. 
- This is believed to be the cause of the system test runs since #2557 has been merged.
2. Fixed a bug where the `SegmentAttributeIndex` may incorrectly throw a `StreamSegmentMergedException`, `StreamSegmentSealedException` or `StreamSegmentNotExistsException` if it tries to create a snapshot and update that snapshot's location in the main segment's attributes, but the main segment is concurrently being merged, sealed or deleted.
- This would only happen in the …
> Issue 2655: (SegmentStore) Various bug fixes

- controller/src/main/java/io/pravega/controller/server/eventProcessor/ControllerEventProcessors.java
Fix the scaling policy of request stream.
Fixes #2648. 
*   Use the scaling policy configuration from `ControllerEventProcessorConfig`, while creating `_requeststream`.
Request stream should  be created with 2 segments.
> Issue 2648: Correct the number of segments for request stream

- documentation/src/docs/transactions.md
* Replaces the concepts link in the transactions documentation with the correct one.
Fixes #2661 
Click the link
> Issue 2661: Fix Pravega concepts broken link

- controller/src/main/java/io/pravega/controller/server/eventProcessor/requesthandlers/TruncateStreamTask.java
- controller/src/main/java/io/pravega/controller/server/eventProcessor/requesthandlers/UpdateStreamTask.java
- controller/src/test/java/io/pravega/controller/task/Stream/StreamMetadataTasksTest.java
There is a bug in TruncateStreamTask and UpdateStreamTask where, upon completion of processing, if we fail before resetting the state, when the processing is retried it will find that the work is already complete and it exits. It should also check and reset the state conditionally in such scenarios. (Note: we already handle this situation correctly for scale. but it is not handled in update and truncate stream tasks).
Fixes #2670 
In UpdateStreamTask and TruncateStreamTask we should never have the state set to UPDATING or TRUNCATING if the corresponding records are not in updating states. 
We can reach such situations if, in previous attempt to process the …
> Issue 2670: Reset state conditionally

- client/src/main/java/io/pravega/client/segment/impl/SegmentInputStreamImpl.java
This increases the default reader buffer size to 1MB, and the default read size to 256KB.
This should decrease the chances that the application reading data needs to have it's thread block while calling readNextEvent()
Changes size of the memory buffer from 128kb to 1mb.
Changes the size of the data fetched from 64kb to 256kb.
Performance tests.
> Issue #2609: Increase default buffer size to 1MB.

- segmentstore/server/src/main/java/io/pravega/segmentstore/server/reading/FutureReadResultEntryCollection.java
- segmentstore/server/src/main/java/io/pravega/segmentstore/server/reading/StreamSegmentReadIndex.java
- segmentstore/server/src/test/java/io/pravega/segmentstore/server/reading/ContainerReadIndexTests.java
- Fixed a bug in `StreamSegmentReadIndex` where it would incorrectly not trigger future reads for a Sealed Segment if that segment had no entries in the read index (this includes empty segments).
- Fixed a bug in `FutureReadResultEntryCollection` where it would incorrectly attempt to cancel an already completed `ReadResultEntry`, which would lead to sporadic build failures or log spam.
Fixes #2679.
Bug fix.
New unit test added.
> Issue 2679: (SegmentStore) Bug fix for future reads from empty segments

- client/src/main/java/io/pravega/client/stream/EventWriterConfig.java
* Fixes the description of the transaction timeout parameter in `EventWriterConfig`.
* Adds more detail about the semantics of the timeout parameter.
Fixes #2694 
No code change, only comments.
Visual inspection, it should have no impact on the build.
> Issue 2694: Fix documentation on transaction timeout parameter

- segmentstore/server/src/main/java/io/pravega/segmentstore/server/reading/FutureReadResultEntryCollection.java
- segmentstore/server/src/main/java/io/pravega/segmentstore/server/reading/PendingMerge.java
- segmentstore/server/src/main/java/io/pravega/segmentstore/server/reading/RedirectedReadResultEntry.java
- segmentstore/server/src/main/java/io/pravega/segmentstore/server/reading/StreamSegmentReadIndex.java
- segmentstore/server/src/main/java/io/pravega/segmentstore/server/writer/SegmentAggregator.java
- segmentstore/server/src/test/java/io/pravega/segmentstore/server/containers/StreamSegmentContainerTests.java
- segmentstore/server/src/test/java/io/pravega/segmentstore/server/logs/DataFrameBuilderTests.java
- segmentstore/server/src/test/java/io/pravega/segmentstore/server/logs/OperationLogTestBase.java
- segmentstore/server/src/test/java/io/pravega/segmentstore/server/logs/OperationProcessorTests.java
- segmentstore/server/src/test/java/io/pravega/segmentstore/server/reading/ContainerReadIndexTests.java
- segmentstore/server/src/test/java/io/pravega/segmentstore/server/reading/FutureReadResultEntryCollectionTests.java
- segmentstore/server/src/test/java/io/pravega/segmentstore/server/reading/PendingMergeTests.java
- segmentstore/server/src/test/java/io/pravega/segmentstore/server/reading/RedirectedReadResultEntryTests.java
- segmentstore/server/src/test/java/io/pravega/segmentstore/server/writer/SegmentAggregatorTests.java
- test/testcommon/src/main/java/io/pravega/test/common/TestUtils.java
Fixed a bug in the Segment Store where, in some scenarios, it would cancel a Read request with a `StreamSegmentNotExistsException` immediately after a `SegmentContainer` recovery.
**Background**
What happens during a Segment Merge (high-level steps; there's more detail underneath):
1. Consider two segments, S1, and S2. We want to merge S2 into S1 at offset N.
2. We request the merge into the Segment Store. The merge request is recorded in the Segment Store, and the Read Index for S1 is updated with `beginMerge(S2, N)`, which indicates that offsets [N, N+len(S2)) within S1 will be redirected to S2[0, len(S2)).
- This is because S2 is not yet merged into S1 in Tier2, hence we need this redirect.
3. Some time later, the StorageWriter picks up the operation and …
> Issue 2678: (SegmentStore) Bugfix for StreamSegmentNotExists after container failover

- segmentstore/server/host/src/main/java/io/pravega/segmentstore/server/host/handler/AppendProcessor.java
- segmentstore/server/host/src/main/java/io/pravega/segmentstore/server/host/handler/PravegaRequestProcessor.java
*  Increases the `segment_read_bytes` metric counter value in the `handleReadResult` method, rather than from `readResult` length. 
Fixes #2659 
*  Increases the `segment_read_bytes` metric counter value in the `handleReadResult` method, rather than from `readResult` length. 
`segment_ready_bytes`  should be reported correctly and match with `segment_write_bytes` in a period of time.
> Issue 2659: Fix segment read bytes metric issue

- segmentstore/server/src/main/java/io/pravega/segmentstore/server/logs/DataFrameBuilder.java
- segmentstore/server/src/main/java/io/pravega/segmentstore/server/logs/OperationProcessor.java
- segmentstore/server/src/test/java/io/pravega/segmentstore/server/logs/OperationProcessorTests.java
Fixed a (relatively harmless) bug in `OperationProcessor` that would incorrectly throw an `AssertionError` in certain conditions when a write failed to commit to memory.
- If a Tier1 write fails to commit to memory, a `DataCorruptionException` is thrown and the `OperationProcessor` needs to fail all operations in that write, all operations in subsequent writes, and shut down.
- Sometimes, due to lock acquisition reordering, the success callback for write N+1 would execute after the failed callback for write N (since the Tier1 write was already in flight and had nothing to do with our in-memory commit problem). 
- The callback for N would have already failed the operations for N+1 and canceled its associated `MetadataUpdateTransaction`, but it is possible that …
> Issue 2700: (SegmentStore) Fixed sporadic failures in OperationProcessorTests.testWithDataCorruptionFailures

- segmentstore/server/src/main/java/io/pravega/segmentstore/server/logs/DataFrameInputStream.java
- segmentstore/server/src/main/java/io/pravega/segmentstore/server/logs/DataFrameReader.java
- test/testcommon/src/main/java/io/pravega/test/common/ErrorInjector.java
1. Fixed a bug in `DataFrameInputStream` that was incorrectly wrapping a `DurableDataLogException` (Tier1 exception) into an `IOException`. 
- The upstream code treats all `IOException`s as critical failures and stops recovery with a `DataCorruptionException`.
- `DataCorruptionException` should only be thrown if there is something wrong with the data itself. It should not be thrown when there are transient Tier1 exceptions, such as timeouts.
2. Fixed a bug in `ErrorInjector` (Test code utils) that would incorrectly wrap exceptions in `CompletionException`, which could confuse exception handlers if they don't expect that.
- If this had been working properly before, the bug described above would have been caught by unit tests a long time ago.
**Purpose of the …
> Issue 2698: (SegmentStore) Incorrectly throwing DataCorruptionException for recoverable Tier1 errors

- controller/src/main/java/io/pravega/controller/server/eventProcessor/ControllerEventProcessors.java
- controller/src/main/java/io/pravega/controller/server/eventProcessor/requesthandlers/AbstractRequestProcessor.java
- controller/src/main/java/io/pravega/controller/server/eventProcessor/requesthandlers/CommitRequestHandler.java
- controller/src/main/java/io/pravega/controller/server/eventProcessor/requesthandlers/RequestProcessorBase.java
- controller/src/main/java/io/pravega/controller/server/eventProcessor/requesthandlers/StreamRequestHandler.java
- controller/src/main/java/io/pravega/controller/store/stream/AbstractStreamMetadataStore.java
- controller/src/main/java/io/pravega/controller/store/stream/InMemoryStream.java
- controller/src/main/java/io/pravega/controller/store/stream/PersistentStreamBase.java
- controller/src/main/java/io/pravega/controller/store/stream/Stream.java
- controller/src/main/java/io/pravega/controller/store/stream/StreamMetadataStore.java
- controller/src/main/java/io/pravega/controller/store/stream/ZKStream.java
- controller/src/test/java/io/pravega/controller/server/ControllerServiceWithZKStreamTest.java
- controller/src/test/java/io/pravega/controller/server/eventProcessor/ControllerEventProcessorTest.java
- controller/src/test/java/io/pravega/controller/server/eventProcessor/ScaleRequestHandlerTest.java
- controller/src/test/java/io/pravega/controller/server/eventProcessor/requesthandlers/RequestProcessorTest.java
- controller/src/test/java/io/pravega/controller/server/eventProcessor/requesthandlers/RequestProcessorWithInMemoryStore.java
- controller/src/test/java/io/pravega/controller/server/eventProcessor/requesthandlers/RequestProcessorWithZkStore.java
- controller/src/test/java/io/pravega/controller/server/v1/InMemoryControllerServiceImplTest.java
- controller/src/test/java/io/pravega/controller/server/v1/ZKControllerServiceImplTest.java
- controller/src/test/java/io/pravega/controller/task/Stream/StreamMetadataTasksTest.java
* Since CommitEventProcessor and StreamEventProcessor run concurrently, each trying to acquire processing rights by setting the state, we have introduced a fairness mechanism so that one processing does not starve another. 
Fixes #2696 
It introduces a common parent class for all request-processors called `AbstractRequestProcessor`.
This implements failing request processing for each type of event by default. It also provides a common method called `withCompletion` which ensures that a task is processed only if "fairness" allows for it. 
Fairness is ensured by making sure that if a task fails because it is unable to start processing due to conflict with other processing, it "tries" to set its processors name as …
> Issue 2696: Introduce fairness in processing on different event processors for same stream

- controller/src/test/java/io/pravega/controller/server/eventProcessor/requesthandlers/RequestProcessorTest.java
Fixes a race in test where it doesnt wait for processing to start before creating "waiting processor for 2nd processor". 
Fixes #2706 
The code posts an event for processing (on processor 1) and then simulates condition such that a processing on another processor (processor 2). Processor 2 duly registers itself a "waiting processor". 
However, if processing 1 starts after the waiting processor has been set, it gets postponed. 
The test's intent is to start processing 1 and then postpone processing 2. 
So i had added a future latch called "started" that is used to coordinate and ensure we start the processing before creating "waiting processor"
**How to …
> Issue 2706: Sporadic Unit test failure: RequestProcessorTest.testRequestProcessor 

- gradle.properties
Bumping version from 0.3.0-SNAPSHOT to 0.4.0-SNAPSHOT
Fixes #2717 
Release 0.3.0
Changes master to be defined in terms of the unreleased 0.4 version
Manually.
> Issue 2717: Bump version for release

- config/config.properties
Changing value of `bookkeeper.zkAddress` from `master.mesos` to `localhost.`
Fixes #2719.
Changing value of `bookkeeper.zkAddress` from `master.mesos` to `localhost.`
> Issue 2719: Changing default value for `bookkeeper.zkAddress`.

- build.gradle
Substitute jsr311-api with javax.ws.rs-api.
This is the same as #2723 but for the release branch.
see #2723
System tests.
> Issue 2718: Substitute jsr311-api with javax.ws.rs-api

- gradle.properties
Change pravegaVersion from 0.3.0 to 0.3.1-SNAPSHOT
Ensures any future changes are considered part of the 0.3.1 pre-release as opposed to being part of 0.3.0.
Changes the version used by gradle in it's tasks.
Manually
> Issue 2728: Change pravegaVersion to 0.3.1-SNAPSHOT

- test/system/src/test/java/io/pravega/test/system/StreamsAndScopesManagementTest.java
Creation of a new system test specifically addressed to check management operations on streams and scopes (`StreamsAndScopesManagementTest.java`).
Fixes #1850.
The test executes a series of metadata operations on streams and scopes to verify their correct operation. This includes:
* The creation and deletion of multiple scopes both in correct and correct situations. 
* For each scope, the test creates a range of streams and tries to create, update, seal and delete them in correct and incorrect situations. 
* The test performs metadata operations on empty and non-empty streams.
* The test also provides performance metrics on metadata operations.
Note: the test is prepared to check re-creation of streams …
> Issue 1850: Streams and scopes system test

- client/src/main/java/io/pravega/client/netty/impl/AppendBatchSizeTrackerImpl.java
Change the client batch target from 10ms to half server latency.
This is a replacement for #2531 by @ack72tdp
Fixes #2556.
When the server is under load, latency for the client increases rapidly. Depending on the event size this may cause the server to be CPU bound. This change automatically adjusts the batch size based on the server latency. This ensures the server has less work to perform when it is under load. This should lower append latency on moderately heavily loaded servers.
Changes the batch size target from 10ms fixed to a variable size based on how long the server takes to respond.
@ack72tdp performed performance tests.
> Issue 2556: Expand client batch size to half server latency

- client/src/main/java/io/pravega/client/stream/impl/EventStreamReaderImpl.java
- client/src/main/java/io/pravega/client/stream/impl/ReaderGroupStateManager.java
- client/src/test/java/io/pravega/client/stream/impl/EventStreamReaderTest.java
- test/integration/src/test/java/io/pravega/test/integration/ReaderGroupNotificationTest.java
This change ensures that we create a delegationToken for the metadata client before it is used.
This is for testing whether this is the reason for the current longetivity failures. There can be a better way of doing this. 
Try out setting `delegationToken` for `metadataclient` of a `readergroup` before it is used during truncation.
Extracts the latest delegation token for metadataclient before it is used in the scenario where segment is truncated.
The longetivity failures are not observed. Working on a unit test for this too. Will complete it before the merge.
> Issue 2658: Refresh `delegationToken` for metadataclient during truncation

- client/src/main/java/io/pravega/client/stream/impl/ByteBufferSerializer.java
- client/src/test/java/io/pravega/client/stream/impl/ByteSerializerTest.java
- shared/protocol/src/main/java/io/pravega/shared/protocol/netty/WireCommands.java
- test/integration/src/test/java/io/pravega/test/integration/IdleSegmentTest.java
* Allow serializers to produces a ByteBuffer not backed by an array.
* Add a ByteBufferSerializer
Fixes #2697. 
Previously if a ByteBuffer that did not allow calling .array() was emitted by a serializer it would result in an exception being thrown. 
This deals with that case by using a method provided by byteBuffer to write itself to an output stream. 
Unfortunately this involves a cast. (While it is always hold true, it cannot be avoided because there are multiple implementation for the output streams passed depending on the write which don't share a common super class)
The newly added integration test should pass. (It does not without the change)
> Issue 2697: Handle case where buffer returned from a serializer does not implement .array()

- client/src/test/java/io/pravega/client/segment/impl/SegmentInputStreamTest.java
- segmentstore/contracts/src/main/java/io/pravega/segmentstore/contracts/StreamSegmentStore.java
- segmentstore/server/host/src/main/java/io/pravega/segmentstore/server/host/handler/PravegaRequestProcessor.java
- segmentstore/server/host/src/test/java/io/pravega/segmentstore/server/host/handler/PravegaRequestProcessorTest.java
Ensure an empty `WireCommands.SegmentRead` is sent while cancelling pending read requests.
Fixes #2746
On receiving a `CancellationException` for a read request ensure PravegaRequestProcessor sends and empty SegmentRead message.
All the existing tests and newly added tests should pass.
> Issue 2746: PravegaRequestProcessor should send an empty Read result before cancelling Read request.

- test/system/src/test/java/io/pravega/test/system/StreamsAndScopesManagementTest.java
Increased timeout in `StreamsAndScopesManagementTest.java`, as it was too close to the actual duration of the experiment.
Fixes #2759. 
The timeout in `StreamsAndScopesManagementTest.java` was too close to the actual experiment duration. Therefore, minor fluctuations in the performance of the platform/system caused the test to time out. For instance, in the last successful system test build the experiment finished just `7s` before the timeout. This PR increases the test timeout to avoid sporadic failures due to system/platform performance fluctuations. 
The `StreamsAndScopesManagementTest` test should pass consistently.
> Issue 2759: Sporadic timeout error in StreamsAndScopesManagementTest

- controller/src/main/java/io/pravega/controller/server/ControllerService.java
- controller/src/main/java/io/pravega/controller/store/stream/AbstractStreamMetadataStore.java
- controller/src/main/java/io/pravega/controller/store/stream/PersistentStreamBase.java
- controller/src/main/java/io/pravega/controller/store/stream/Stream.java
- controller/src/main/java/io/pravega/controller/store/stream/StreamMetadataStore.java
- controller/src/main/java/io/pravega/controller/store/stream/tables/TableHelper.java
- controller/src/test/java/io/pravega/controller/store/stream/StreamMetadataStoreTest.java
- controller/src/test/java/io/pravega/controller/store/stream/TableHelperTest.java
- controller/src/test/java/io/pravega/controller/store/stream/ZkStreamTest.java
- test/integration/src/test/java/io/pravega/test/integration/endtoendtest/EndToEndTruncationTest.java
Controller has truncation record and the correct offsets. But it used to return default offsets for getSegmentsAt api. Now it sends default offsets only for segments that are not part of truncation point.  
Fixes #2644 
In `StreamMetadataStore`, we have the `getActiveSegments(time)` API, which takes active segments corresponding to the given time parameter, and then crosses them with the current truncation record to compute the actual active segments. Since this API call was designed before the truncation capability, it never sent the offsets, only the segment ids. Moreover, these offsets were defaulted to 0 by the `ControllerService` layer before responding …
> Issue 2644: Controller should send truncation offset instead of default 0

- client/src/main/java/io/pravega/client/ClientConfig.java
- client/src/main/java/io/pravega/client/stream/impl/Credentials.java
- client/src/main/java/io/pravega/client/stream/impl/DefaultCredentials.java
- client/src/main/java/io/pravega/client/stream/impl/PravegaCredsWrapper.java
- client/src/test/java/io/pravega/client/CredentialsExtractorTest.java
- common/src/main/java/io/pravega/common/auth/AuthConstants.java
- controller/src/main/java/io/pravega/controller/server/rest/resources/StreamMetadataResourceImpl.java
- controller/src/main/java/io/pravega/controller/server/rpc/auth/PasswordAuthHandler.java
- controller/src/main/java/io/pravega/controller/server/rpc/auth/PravegaAuthManager.java
- controller/src/main/java/io/pravega/controller/server/rpc/auth/PravegaInterceptor.java
- controller/src/main/java/io/pravega/controller/server/rpc/auth/TestAuthHandler.java
- controller/src/test/java/io/pravega/controller/rest/v1/Failing403StreamMetaDataTests.java
- controller/src/test/java/io/pravega/controller/rest/v1/SecureStreamMetaDataTests.java
- controller/src/test/java/io/pravega/controller/server/rpc/auth/PravegaAuthManagerTest.java
- segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/bookkeeper/ZooKeeperServiceRunner.java
- shared/authplugin/src/main/java/io/pravega/auth/AuthHandler.java
- test/testcommon/src/main/java/io/pravega/test/common/TestUtils.java
- Updated `AuthHandler` to use a single token rather than a map of values
- Updated `PasswordAuthHandler` to use RFC 7617 (Basic Auth) encoding
- Updated gRPC interceptor to use a single `Authorization` metadata header
Closes #2384 
This PR enhances the Pravega auth plugin system to support standard authentication schemes such as `Basic` (which is understood by ordinary HTTP clients), without loss of functionality. 
Shown here is an ordinary HTTP client making an authenticated request to the controller:
```
$ curl -v -u admin:1111_aaaa http://localhost:9091/v1/scopes/_system
*   Trying 127.0.0.1...
* Connected to localhost (127.0.0.1) port 9091 (#0)
* Server auth using Basic with user 'admin'
> GET /v1/scopes/_system HTTP/1.1
> …
```
> Issue 2384: Standardize use of `Authorization` header

- segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/rocksdb/RocksDBCache.java
This PR proposes a set of default configuration settings for RocksDB to preserve memory in the segment store process and allow longevity experiments to run for a longer period of time. All the default settings are in `RocksDBCache.java`, thus avoiding changes in `config.properties`. This has been done in purpose as this PR is intended to be cherry-picked for release `0.3.1`, so no major changes from a user perspective are expected.
Fixes #2754.
The code sets several RocksDB default parameters with conservative values to preserve memory:
- Cache block size has been set to 32KB (default 4KB) to reduce the memory usage of internal indexes of RocksDB. 
- Total space for memtables has been set to 64MB to reduce memory …
> Issue 2754: RocksDB off-heap memory consumption in segment store process (longevity runs)

- test/system/src/test/java/io/pravega/test/system/OffsetTruncationTest.java
- test/system/src/test/java/io/pravega/test/system/RetentionTest.java
Removed assertions expecting `TruncatedDataException` from `OffsetTruncationTest.java` and `RetentionTest.java`
Fixes #2776.
PR #2757 changes the way a reader interacts with the system after a truncation operation. Before, upon a stream truncation, a reader expected a `TruncatedDataException` on the first read attempt and got the correct truncation offsets on the second read attempt to continue reading data from the stream. Conversely, now the controller automatically sets the correct truncation offsets for the reader on the first read attempt without getting a `TruncatedDataException`. For this reason, assertions expecting `TruncatedDataException` need to be removed.
The involved system tests …
> Issue 2776: Wrong TruncatedDataException assertions

- test/system/src/test/java/io/pravega/test/system/BookieFailoverTest.java
This PR fixes the timeout error in `BookieFailoverTest` as follows: 
- Added a sleep in `BookieFailoverTest` to allow readers to get properly created. 
- Sleep intervals during failover have been set to match with other failovers in `AbstractFailoverTests`. 
Fixes #2779.
The code adds one sleep interval between the creation of readers and the bookie failover event. Without this sleep interval, not all the readers were created and, what is worse, some of them were assumed to be created by the test but never started due to the Bookie failure. Now, all the readers get properly created and consume events. 
Moreover, the sleep intervals during failover have been set in the same way than `AbstractFailoverTests` (shorter …
> Issue 2779: BookieFailoverTest timeout error

- gradle.properties
* Updates the Pravega version in gradle.properties in preparation for release 0.3.1.
Fixes #2784 
No code change, only a configuration change. It changes the Pravega version number.
Build should yield artifacts for 0.3.1.
> Issue 2784: Change version in r0.3 branch in preparation for release

- client/src/main/java/io/pravega/client/stream/impl/ControllerImpl.java
- client/src/main/java/io/pravega/client/stream/impl/SegmentWithRange.java
- client/src/main/java/io/pravega/client/stream/impl/StreamSegments.java
Add some precondition checks on StreamSegments returned from the controller.
Fixes #2798 
Adds some sanity checks for the data coming from the controller after a segment sealed.
Existing tests actually cover this fairly well.
> Issue 2798: Add precondition checks on splits and merges from the controller.

- client/src/main/java/io/pravega/client/segment/impl/SegmentOutputStreamFactory.java
- client/src/main/java/io/pravega/client/segment/impl/SegmentOutputStreamFactoryImpl.java
- client/src/main/java/io/pravega/client/segment/impl/SegmentOutputStreamImpl.java
- client/src/main/java/io/pravega/client/stream/impl/EventStreamWriterImpl.java
- client/src/test/java/io/pravega/client/segment/impl/SegmentOutputStreamTest.java
- client/src/test/java/io/pravega/client/stream/impl/EventStreamWriterTest.java
- client/src/test/java/io/pravega/client/stream/mock/MockSegmentStreamFactory.java
- test/integration/src/test/java/io/pravega/test/integration/endtoendtest/EndToEndTxnWithTest.java
- Remove redundant invocation of fetch successors during Abort Transaction.
- Fix incorrect logs on EventWriterClient for abort transaction.
Fixes #2801 
Currently in case of an abort transaction  due to a missing `io.pravega.client.stream.impl.Controller#pingTransaction` the transaction segment writer can receive a `WireCommandType.NO_SUCH_SEGMENT`. 
In such a scenario the current segmentwriter would trigger a fetch successor callback, which is redundant, as receiving a `WireCommandType.NO_SUCH_SEGMENT` implies that the transaction has been aborted.
This PR removes this redundant callback invocation.
There are no changes to the functionality/behavior. All the existing and newly added tests …
> Issue 2801: Remove redundant invocation of fetch successors during Abort transaction.

- test/system/src/main/java/io/pravega/test/system/framework/services/docker/BookkeeperDockerService.java
- test/system/src/main/java/io/pravega/test/system/framework/services/docker/DockerBasedService.java
- test/system/src/main/java/io/pravega/test/system/framework/services/docker/HDFSDockerService.java
- test/system/src/main/java/io/pravega/test/system/framework/services/docker/PravegaControllerDockerService.java
- test/system/src/main/java/io/pravega/test/system/framework/services/docker/PravegaSegmentStoreDockerService.java
- test/system/src/main/java/io/pravega/test/system/framework/services/docker/ZookeeperDockerService.java
*  Adds health checks to docker swarm services.
*  Listens for the traffic on the port, by running a command inside the container
Fixes #2796 
Ensures that the services deployed are healthy, before starting the execution of system tests.
When system tests are run using docker swarm based system test framework, the containers of the swarm services deployed should be healthy.
> Issue 2796: Health check for services deployed using docker system test framework

- build.gradle
- shared/metrics/src/test/java/io/pravega/shared/metrics/MetricRegistryUtils.java
- shared/metrics/src/test/java/io/pravega/shared/metrics/MetricsProviderTest.java
- test/integration/src/test/java/io/pravega/test/integration/MetricsTest.java
Move MetricRegistryUtils into shared:metrics to avoid a circular dependency.
Fixes #2810
Prevents `shared` from depending on `shared:metrics` and vice versa. By relocating 
MetricRegistryUtils into metrics, and changes the added dependencies to point to the new location.
> Issue 2810: Move MetricRegistryUtils to prevent circular dependency.

- segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/hdfs/HDFSExceptionHelpers.java
- segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/hdfs/HDFSStorage.java
HDFS implementation checks for data availability locally in the read stream. This ensures that there is enough data available to read without blocking.
The idea is that in case multiple reads are in process the threads are not blocked. This fails in case of longevity runs where data may not be cached ever after multiple calls. At that point it makes sense to block for the read to happen.
Fixes #2773.
Removes the availability check on the run.
ArrayOutOfBoundsException is not observed.
> Issue 2773: Do not check for data availability in the stream locally

- client/src/main/java/io/pravega/client/stream/impl/ReaderGroupState.java
- client/src/test/java/io/pravega/client/stream/impl/ReaderGroupStateManagerTest.java
- test/integration/src/test/java/io/pravega/test/integration/ReaderGroupStreamCutUpdateTest.java
- This PR allows `ReaderGroup.getStreamCuts()` to get updated values according to the checkpoints being processed in the reader group.
- Added unit test/integration test to verify the fix.
Fixes #2823.
This PR modifies `CheckpointReader.update()` method in `ReaderGroupState` to update `assignedSegments` offsets upon a checkpoint state update. This change allows `ReaderGroupState.getPositions()` to retrieve updated values, which are in turn used by `ReaderGroup.getStreamCuts()` to provide users with updated stream cuts.
- All test should be passing as before (unit, integration, system).
- Added a new unit test to check that `assignedSegments` are updated upon a checkpoint.
- Added a new …
> Issue 2823: Updated StreamCuts in ReaderGroup

- docker/bookkeeper/entrypoint.sh
* Stable BookieID is needed when running `sts` bookies.
* Modified bookkeeper's entrypoint
Closes #2832 
* Add useHostNameAsBookieID value to `bk_server.conf` to replace hostname with IP address so that bookie pods can process failover properly.
Deployment passed
> Issue 2832: Add useHostNameAsBookieID to bk_server.conf

- gradle.properties
* Removes the SNAPSHOT fix from the Pravega version property in gradle.properties as part of the preparation to release 0.3.2. 
Fixes #2888 
There is no code change, only a single change to the `gradle.properties` file.
Build and make sure that the new version is published locally  with `./gradlew install`.
> Issue 2888: Remove SNAPSHOT suffix for 0.3.2 release

- client/src/main/java/io/pravega/client/batch/impl/BatchClientImpl.java
Remove duplicate logic of fetching offsets for a Stream Head.
Fixes #2644 
With PR  #2757 Controller api `controller.getSegmentsAtTime(..)` now returns the updated offsets after truncation. Hence the duplicate logic of fetching offsets in the BatchClient is not required now.
> Issue 2644: Remove duplicate logic of fetching offsets for a Stream Head in BatchClient.

- .gitignore
Signed-off-by: Enrico Olivelli <eolivelli@apache.org>
Add Add .nb-gradle to .gitignore
Closes #2885
> Issue 2885: Add .nb-gradle to .gitignore

- client/src/main/java/io/pravega/client/stream/ReaderGroup.java
- client/src/main/java/io/pravega/client/stream/impl/ReaderGroupState.java
- client/src/test/java/io/pravega/client/stream/impl/ReaderGroupStateTest.java
- test/integration/src/test/java/io/pravega/test/integration/ControllerRestApiTest.java
- test/integration/src/test/java/io/pravega/test/integration/StreamCutsTest.java
- test/integration/src/test/java/io/pravega/test/integration/endtoendtest/EndToEndReaderGroupTest.java
- test/system/src/test/java/io/pravega/test/system/ControllerRestApiTest.java
- Ensure scoped stream name is returned by ReaderGroup#getStreamNames.
Fixes #2860 
Ensure the scoped stream name (e.g: scopeA/streamA) is returned by ReaderGroup#getStreamNames().
> Issue 2860:  Ensure scoped name of the stream is returned by ReaderGroup#getStreamNames

- test/system/src/test/java/io/pravega/test/system/AbstractFailoverTests.java
- test/system/src/test/java/io/pravega/test/system/AbstractReadWriteTest.java
- test/system/src/test/java/io/pravega/test/system/AbstractScaleTests.java
- test/system/src/test/java/io/pravega/test/system/AbstractSystemTest.java
- test/system/src/test/java/io/pravega/test/system/AutoScaleTest.java
- test/system/src/test/java/io/pravega/test/system/BatchClientSimpleTest.java
- test/system/src/test/java/io/pravega/test/system/BookieFailoverTest.java
- test/system/src/test/java/io/pravega/test/system/BookkeeperTest.java
- test/system/src/test/java/io/pravega/test/system/ControllerFailoverTest.java
- test/system/src/test/java/io/pravega/test/system/ControllerRestApiTest.java
- test/system/src/test/java/io/pravega/test/system/MultiControllerTest.java
- test/system/src/test/java/io/pravega/test/system/MultiReaderTxnWriterWithFailoverTest.java
- test/system/src/test/java/io/pravega/test/system/MultiReaderWriterWithFailOverTest.java
- test/system/src/test/java/io/pravega/test/system/MultiSegmentStoreTest.java
- test/system/src/test/java/io/pravega/test/system/OffsetTruncationTest.java
- test/system/src/test/java/io/pravega/test/system/PravegaControllerTest.java
- test/system/src/test/java/io/pravega/test/system/PravegaSegmentStoreTest.java
- test/system/src/test/java/io/pravega/test/system/PravegaTest.java
- test/system/src/test/java/io/pravega/test/system/ReadTxnWriteAutoScaleWithFailoverTest.java
- test/system/src/test/java/io/pravega/test/system/ReadTxnWriteScaleWithFailoverTest.java
- test/system/src/test/java/io/pravega/test/system/ReadWithAutoScaleTest.java
- test/system/src/test/java/io/pravega/test/system/ReadWriteAndAutoScaleWithFailoverTest.java
- test/system/src/test/java/io/pravega/test/system/ReadWriteAndScaleWithFailoverTest.java
- test/system/src/test/java/io/pravega/test/system/ReaderCheckpointTest.java
- test/system/src/test/java/io/pravega/test/system/RetentionTest.java
- test/system/src/test/java/io/pravega/test/system/StreamCutsTest.java
- test/system/src/test/java/io/pravega/test/system/StreamsAndScopesManagementTest.java
- test/system/src/test/java/io/pravega/test/system/ZookeeperTest.java
Code refactor of system tests:
- Better encapsulation of functionality in specific abstract classes.
- Removed redundant IO methods for writing/reading events.
- Removed redundant service initialization code.
- Added comments and minor style improvements in various tests.
Fixes #2715.
First of all, this PR attempts to clearly define the functionality that each `Abstract*` test class should contain. In this sense, now we find 4 abstract system test classes:
- `AbstractSystemTest` contains the functionalities to start service instances (e.g., controller, segment store, bookkeeper, zookeeper). This allows us to remove most of the duplicate code existing in most `initialize()` methods.
- `AbstractReadWriteTest` …
> Issue 2715: Refactor system tests

- controller/src/main/java/io/pravega/controller/server/ControllerService.java
- controller/src/main/java/io/pravega/controller/server/rpc/grpc/v1/ControllerServiceImpl.java
- controller/src/main/java/io/pravega/controller/store/stream/AbstractStreamMetadataStore.java
- controller/src/main/java/io/pravega/controller/store/stream/PersistentStreamBase.java
- controller/src/main/java/io/pravega/controller/store/stream/Stream.java
- controller/src/main/java/io/pravega/controller/store/stream/StreamMetadataStore.java
- controller/src/test/java/io/pravega/controller/server/v1/ControllerServiceImplTest.java
- controller/src/test/java/io/pravega/controller/store/stream/StreamMetadataStoreTest.java
- shared/controller-api/src/main/proto/Controller.proto
Signed-off-by: Shivesh Ranjan <Shivesh.Ranjan@gmail.com>
Introduced new gRPC api for stream cut validation. 
Fixes #2023 
Introduces a new gRPC api for stream cut validation. This api simply passes the stream cut to the metadata store where its validation is performed. Validation checks if entire keyspace range is covered and if it does not have any overlapping segments involved in the stream cut. 
Note: The current representation of stream cut has problems that we will tackle separately.
As part of this PR we have not changed the stream cut representation and validation logic. It simply introduces a new controller gRPC api for stream cut validation. 
Note: we have exposed this api but we are deliberately …
> Issue 2023: Controller gRPC api for stream cut validation

- client/src/main/java/io/pravega/client/segment/impl/SegmentInputStreamImpl.java
- client/src/main/java/io/pravega/client/segment/impl/SegmentMetadataClient.java
- client/src/main/java/io/pravega/client/segment/impl/SegmentMetadataClientImpl.java
- client/src/main/java/io/pravega/client/state/impl/RevisionedStreamClientImpl.java
- client/src/test/java/io/pravega/client/batch/impl/SegmentIteratorTest.java
- client/src/test/java/io/pravega/client/segment/impl/SegmentInputStreamTest.java
- client/src/test/java/io/pravega/client/segment/impl/SegmentMetadataClientTest.java
- client/src/test/java/io/pravega/client/stream/impl/EventStreamReaderTest.java
- client/src/test/java/io/pravega/client/stream/mock/MockSegmentIoStreams.java
- client/src/test/java/io/pravega/client/stream/mock/MockStreamManager.java
- test/integration/src/test/java/io/pravega/test/integration/endtoendtest/EndToEndTruncationTest.java
Skip over trailing bytes at the end of a segment if they are smaller than the length of an event header.
Fixes #2902. But does not actually identify why the truncate was leaving a single trailing byte.
Removes a redundant parameter to truncateSegment().
Adds a truncation integration test.
Skips over trailing bytes at the end of the segment if they can't form a full event.
Adds a test for this case.
> Issue 2902: Prevent NPE when truncate leaves trailing bytes in the segment (#2903)

- client/src/main/java/io/pravega/client/stream/ReaderGroupConfig.java
- client/src/main/java/io/pravega/client/stream/impl/CheckpointState.java
- client/src/main/java/io/pravega/client/stream/impl/MaxNumberOfCheckpointsExceededException.java
- client/src/main/java/io/pravega/client/stream/impl/ReaderGroupImpl.java
- client/src/test/java/io/pravega/client/stream/ReaderGroupConfigTest.java
- client/src/test/java/io/pravega/client/stream/impl/ReaderGroupImplTest.java
- test/integration/src/test/java/io/pravega/test/integration/CheckpointTest.java
Signed-off-by: Vijay Srinivasaraghavan <vijayaraghavan.srinivasaraghavan@emc.com>
- added configurable option to `readergroup` to limit outstanding checkpoint request
Fixes #2828
Upon initiating checkpoint request, it validates if the current outstanding checkpoint request has reached the maximum allowed limit and throws an exception.
Added test case to validate the configurable limits
> Issue 2828: Limit outstanding checkpoint request to ReaderGroup

- test/integration/src/test/java/io/pravega/test/integration/CheckpointTest.java
Signed-off-by: Vijay Srinivasaraghavan <vijayaraghavan.srinivasaraghavan@emc.com>
- Fixed failing test case that times out while waiting for the future to return a result 
Fixes #2935
- It makes an attempt to read the event (`readNextEvent()`) from both the readers before trying to get the result from the `future` instance. 
./gradlew :test:integration:test --tests io.pravega.test.integration.CheckpointTest should pass
> Issue 2935: Fix failing outstanding checkpoint validation test

- shared/metrics/src/main/java/io/pravega/shared/MetricsNames.java
- test/integration/src/test/java/io/pravega/test/integration/MetricsTest.java
* Adds a common prefix to every metric to enable users to easily spot the component exporting the metric.
* Adds a second level to the segment store to identify the specific sub-component that a specific metric is being exported by.
Fixes #2920 
In `io.pravega.shared.MetricsNames`, make sure that all metrics have a prefix that identifies the the component that is exporting the metrics.
It should not break the build.
> Issue 2920: Normalize format for metrics names

- segmentstore/server/src/main/java/io/pravega/segmentstore/server/store/ServiceConfig.java
Bringing `config.properties` and `ServiceConfig.java` in sync.
Fixes #2957.
Changes Pravega default tier2 to HDFS from INMEMORY.
Default Pravega deployment tries to connect to HDFS.
> Issue 2957: Setting default tier2 to HDFS.

- documentation/src/docs/deployment/run-local.md
The current link is to the html page of the yml file. It should point to the raw file.
Fixing the documentation.
No new code, just updating the documentation.
Try the link.
> Issue 2974: Update the docker-compose yml link in the documentation

- client/src/main/java/io/pravega/client/netty/impl/ClientConnectionInboundHandler.java
- client/src/main/java/io/pravega/client/netty/impl/ConnectionFactoryImpl.java
- client/src/test/java/io/pravega/client/netty/impl/ConnectionFactoryImplTest.java
- test/integration/src/test/java/io/pravega/test/integration/endtoendtest/EndToEndChannelLeakTest.java
Fix sporadic failures in EndToEndChannelLeakTest
Fixes #2523 
- Ensure inline executor is used for EndToEndChannelLeakTest.
- Ensure only channels which are in Active state are returned as part of `io.pravega.client.netty.impl.ConnectionFactoryImpl#getActiveChannelCount`
EndToEndChannelLeakTest should pass consistently.
Update: With the changes in the PR not able to simulate the issue for the last 8 hours.
> Issue 2523: Fix a race condition in EndToEndChannelLeakTest

- docker/compose/docker-compose-extendeds3.yml
- docker/compose/docker-compose-nfs-mount.yml
- docker/compose/docker-compose-nfs.yml
- docker/compose/docker-compose.yml
- docker/compose/swarm/zookeeper.yml
- test/system/src/main/java/io/pravega/test/system/framework/services/marathon/ZookeeperService.java
Update Zookeeper Docker image dependency from `jplock/zookeeper:3.5.2-alpha` to official `zookeeper:3.5.4-beta`. Newer versions of Zookeeper contain a significant number of bug fixes. Check the following link for a detailed change log: https://zookeeper.apache.org/releases.html
Fixes #2973
Update Zookeeper Docker image in compose files.
Signed-off-by: Adrian Moreno <adrian@morenomartinez.com>
> Issue 2973: Update Zookeeper Docker image dependency

- docker/bookkeeper/Dockerfile
- docker/pravega/Dockerfile
* Updates base docker image according to the suggestion in issue #2963 .
Fixes #2963 
Changes the docker base image in two places:
* `docker/pravega/Dockerfile`
* `docker/bookkeeper/Dockerfile`
Build and deploy docker images.
> Issue 2963: Update docker images to use OpenJDK image

- common/src/main/java/io/pravega/common/concurrent/ConcurrentDependentProcessor.java
- common/src/test/java/io/pravega/common/concurrent/ConcurrentDependentProcessorTests.java
- segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/AsyncStorageWrapper.java
- Extracted the logic in `AsyncStorageWrapper` where it would only let one instance of a task with a particular key run at any given time (and queue tasks with same keys) into its own class.
Fixes #2958.
- Created `ConcurrentDependentProcessor`
- This generalizes the task processor in `AsyncStorageWrapper` so that it can be reused in other parts of the code (coming up in #2878).
New unit tests added. Existing tests must pass.
> Issue 2958: (SegmentStore) Extracted Concurrent Dependent Processor into its own class.

- segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/hdfs/HDFSExceptionHelpers.java
Translate HDFS `AlreadyBeingCreatedException` as an equivalent for `StreamSegmentExistsException` so the fencing logic acts upon such exceptions too.
Fixes #2933.
The code translates HDFS `AlreadyBeingCreatedException` as an equivalent for `StreamSegmentExistsException` so that a segment store instance can react to concurrent attempts to operate on the same file that result in that exception. The rationale is that `AlreadyBeingCreatedException` is conceptually close to the existing `FileAlreadyExistsException`, which is translated into a Pravega exception called `StreamSegmentExistsException` and handled appropriately by the fencing logic. With the change of this PR, we attempt to handle …
> Issue 2933: Sporadic Failure in HDFSIntegrationTest.testEndToEndWithFencing

- documentation/src/docs/metrics.md
- shared/metrics/src/main/java/io/pravega/shared/MetricsNames.java
Issue-2986: update metrics.md to reflect the changes of metrics related PR 2921, PR 2676
Issue-2968: fixed Metrics typo of "Cache Get Latency"
For issue-2968: correction of the typo inside MetricsNames.java;
For issue-2986: updated metrics.md to reflect the recent metrics changes.
Fixes #2968, Fixes #2986.
Inside MetricsNames.java, the typo of "segment.store.cache.get_latency_ms" changed to "segmentstore.cache.get_latency_ms"
Inside metrics.md: many changes to reflect the changes made by PR 2921 and PR 2676.
For issue-2968: metric "segmentstore.cache.get_latency_ms" starts showing up
For issue-2986: metrics.md reflects the latest metrics …
>  Issue 2986, Issue 2968: Updates to metrics doc and names

- docker/bookkeeper/Dockerfile
- docker/bookkeeper/entrypoint.sh
- docker/compose/docker-compose.yml
- docker/pravega/Dockerfile
- docker/pravega/entrypoint.sh
- Replace base Docker images for Pravega and BookKeeper from `openjdk:8-jre` to `openjdk:8-jre:alpine` to use Alpine-based images. 
- Use `apk` instead of `apt-get` to install system packages.
- Reduce Pravega Docker image size from 758MB to 241MB (-68%)
- Reduce BookKeeper Docker image size from 777MB to 206MB (-73%)
- Add bash flag `set -eo pipefail` to Docker entrypoints to immediately fail if a command fails. 
- Append `|| :` to entrypoint commands that are allowed to fail.
- Fixes #2987
- Fixes #3008
Changes the Docker base image in:
- `docker/pravega/Dockerfile`
- `docker/bookkeeper/Dockerfile`
Build, deploy Docker images, and run all tests based on the new images.
Signed-off-by: …
> Issue 2987: Update Pravega base Docker images to Alpine

- segmentstore/server/src/main/java/io/pravega/segmentstore/server/containers/ReadOnlySegmentContainer.java
- segmentstore/server/src/test/java/io/pravega/segmentstore/server/store/StreamSegmentStoreTestBase.java
This PR adds retries to `ReadOnlySegmentContainer` read operations for tolerating failures in reads addressed to segments being concurrently truncated.
Fixes #2944, #3030.
`ReadOnlySegmentContainer` is special as it can only perform reads from Tier 2 storage. However, it may be the case that while one of those containers is reading a given segment, another ongoing operation deletes or truncates that segment, which may cause unexpected failures (e.g., `StreamSegmentNotExistsException`). This PR just adds retries to read operations in `ReadOnlySegmentContainer` with a twofold objective: i) handle concurrent Segment truncations/deletions while `ReadOnlySegmentContainer` is reading, and ii) handle reads related …
> Issue 2944: Sporadic failure HDFSIntegration.testendtoend

- test/system/src/test/java/io/pravega/test/system/ByteClientTest.java
New system test to check the basic IO functionality of Byte Client.
Fixes #3014.
The test instantiates writers and readers to write/read payloads of different sizes (from 1 byte to 100MB) multiple times. Moreover, the test gets the hash from the payload to ensure that the written data has been correctly read.
This test passed multiple times in a virtual cluster.
> Issue 3014: New system test for Byte Client

- gradle.properties
* Removes SNAPSHOT suffix from Pravega version as part of creating a release.
Fixes #3055 
No code changes, only version in gradle.properties.
Run `./gradlew install` and verify that it is publishing the artifacts under the right version.
> Issue 3055: Update Pravega version in r0.4 to 0.4.0

- controller/src/main/java/io/pravega/controller/store/stream/InMemoryStream.java
- controller/src/main/java/io/pravega/controller/store/stream/PersistentStreamBase.java
- controller/src/main/java/io/pravega/controller/store/stream/ZKStream.java
- controller/src/test/java/io/pravega/controller/store/stream/InMemoryStreamTest.java
- controller/src/test/java/io/pravega/controller/store/stream/StreamTestBase.java
- controller/src/test/java/io/pravega/controller/store/stream/ZooKeeperStreamTest.java
Unit test of all stream metadata operations with large number of epochs spilling over multiple chunks and shards of history time series chunks and sealed segment sizes map shards. 
Fixes #3058 
`PersistentStreamBase` is updated to expose new @VisibleForTesting` methods for setting unit testable chunk and shard map sizes. New unit tests are added to trigger scenarios where metadata spills over multiple chunks and shards.
Found three issues that have been fixed. 
1. reduce method in `getEpochsFromHistoryChunk` tried including identity twice if `first` was ahead of `from`, resulting in duplicate exception. Fixed it. 
2. `truncationTest` …
> Issue 3058: Additional unit tests for Controller Metadata Scalability work

- docker/compose/swarm/pravega.yml
Fixed HDFS configuration parameters in `pravega.yml`.
Fixes #3082 (original problems reported in #3051 and #2998). 
This PR contains two configuration fixes in `pravega.yml`:
1. It adds one missing configuration parameter to specify Tier 2 implementation (`TIER2_STORAGE`). Without this parameter, the Segment Store may fall back to `INMEMORY_STORAGE` and throw an out of memory exception.
2. Given that the current HDFS Docker image (`hdfs.yml`) is a single Docker with one namenode and one datanote, then we should set the replication factor of Tier 2 to 1 to avoid errors in the Segment Store (`HDFS_REPLICATION: 1`).
I run a Pravega Swarm by building new Docker images with the code in this …
> Issue 3082: HDFS misconfiguration in Docker Swarm deployment

- client/src/main/java/io/pravega/client/stream/impl/CheckpointState.java
- client/src/test/java/io/pravega/client/stream/impl/CheckpointStateTest.java
Silent checkpoints should not be considered while computing the number of outstanding checkpoints.
Addresses #3076 
Ensures that the outstanding checkpoint count does not include completed and silent checkpoints.
> Issue 3076: Bugfix for outstanding checkpoint count.

- docker/pravega/Dockerfile
- test/system/src/main/java/io/pravega/test/system/framework/services/docker/DockerBasedService.java
- test/system/src/main/java/io/pravega/test/system/framework/services/docker/HDFSDockerService.java
- test/system/src/main/java/io/pravega/test/system/framework/services/docker/ZookeeperDockerService.java
Docker Swarm system tests fail when deploying Bookkeeper. The current health check used for the Bookkeeper service (and other services using the default health check) is `ss -l | grep "+port+" || exit` ([ref](https://github.com/pravega/pravega/blob/592ea91c0b8067a752f07e2a57080f0d3b18f66d/test/system/src/main/java/io/pravega/test/system/framework/services/docker/DockerBasedService.java#L195)). The base image for Pravega and Bookkeper Docker containers was changed to use Alpine as part of #2987 and `ss` command is not pre-installed on the new Alpine-based images.
This PR makes the following changes:
- Changes the default health check task from using the `ss` command to `netstat`, which is present in all images except from the HDFS one.
- Changes the HDFS health …
> Issue 3078: Fix Swarm-based system tests

- client/src/main/java/io/pravega/client/netty/impl/ConnectionFactoryImpl.java
- shared/metrics/src/main/java/io/pravega/shared/metrics/OpStatsLoggerImpl.java
- shared/metrics/src/main/java/io/pravega/shared/metrics/StatsLoggerImpl.java
Signed-off-by: Enrico Olivelli <eolivelli@apache.org>
This change removes finalize() methods. All of the usages seem not useful
Fixes #3106 
It drops finalize() methods
Tests will pass
>  Issue 3106: Build fails on JDK10 due to the presence of "finalize" methods

- controller/src/main/java/io/pravega/controller/server/rest/generated/api/ScopesApi.java
Signed-off-by: Enrico Olivelli <eolivelli@apache.org>
Use suggested API Class#getConstructor()#newInstance() instead of Class#newInstance() 
see
https://docs.oracle.com/javase/10/docs/api/java/lang/Class.html#newInstance()
Fixes #3111 
Use suggested API Class#getConstructor()#newInstance() instead of Class#newInstance() 
Tests must pass
> Issue 3111: Remove usage of Class#newInstance deprecated since JDK10

- build.gradle
Signed-off-by: Flavio Junqueira <flavio.junqueira@emc.com>
* Renames script variables in build.gradle
Fixes #3144 
A bug was introduced in a previous PR such that the text of the windows script was being overwritten. This change renames some script variables to make sure that the windows BAT files have the right content.
Run `./gradlew clean distribution` and verify that the pravega zip contains the expected script files under `bin/`.
> Issue 3144: Windows script text overwritten

- docker/compose/docker-compose.yml
- docker/compose/swarm/hdfs.yml
- test/system/src/main/java/io/pravega/test/system/framework/services/docker/HDFSDockerService.java
Update HDFS Docker image reference from the outdated `dsrw/hdfs:2.7.3-1` to the newer `pravega/hdfs:2.7.7`.
- Fix #2975 
Update image reference in Docker Compose, Swarm, and Docker-based testing framework.
- Run a Docker Compose or Swarm Pravega cluster from `/docker/compose`.
- Run Docker-based system tests.
---
Signed-off-by: Adrian Moreno <adrian@morenomartinez.com>
> Issue 2975: Update HDFS Docker image to pravega/pravega:2.7.7

- docker/pravega/scripts/init_kubernetes.sh
- Update DNS name for accessing Kubernetes API from inside a container running on Kubernetes. The new DNS name used is `kubernetes.default.svc` instead of `kubernetes` as suggested in the [Kubernetes documentation](https://kubernetes.io/docs/tasks/access-application-cluster/access-cluster/#accessing-the-api-from-a-pod).
Fix https://github.com/pravega/pravega-operator/issues/104
Fixes #3167 
Update the DNS name in [`docker/pravega/scripts/init_kubernetes.sh`](https://github.com/pravega/pravega/blob/d2c856ae1bf611f75db0cedd488f2735ba22a805/docker/pravega/scripts/init_kubernetes.sh#L20) from `kubernetes` to `kubernetes.default.svc`
Deploy Pravega in a namespace different than `default` as …
> Issue 3167: Update DNS name for accessing Kubernetes API

- docker/compose/docker-compose-extendeds3.yml
- docker/compose/docker-compose-nfs-mount.yml
- docker/compose/docker-compose-nfs.yml
- docker/compose/docker-compose.yml
- docker/compose/swarm/pravega.yml
- docker/compose/swarm/scale_segmentstore
- segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/bookkeeper/BookKeeperConfig.java
* Changes the degree of replication of BK to 2
* Updates pravega.yml and scale_segmentstore
Fixes #3037 
The current swarm configuration is such that the number of bookies is three and the degree of replication is also three, which leaves no room for a bookie failure. It would be good to update the configuration such that we can tolerate at least one bookie failure, but the question is: should we update to make it look more the minimum we expect in production or leave numbers that are more appropriate for dev/testing? Concretely, the options I propose are:
1- **Dev/testing**: Change the degree of replication to two, and leave the number of …
> Issue 3037: BK degree of replication in Swarm

- client/src/main/java/io/pravega/client/segment/impl/AsyncSegmentInputStreamImpl.java
Ensure spurious warnings are not thrown by the AsyncSegmentInputStreamImpl for a planned close() invocation.
Fixes #2599 
When AsyncSegmentInputStreamImpl.close() is invoked ensure no spurious warnings are thrown.
The spurious warn message should be observed on closing the reader.
> Issue 2599: Ensure spurious warnings are not thrown by AsyncSegmentInputStreamImpl

- test/integration/src/test/java/io/pravega/test/integration/ControllerMetricsTest.java
Fixed ControllerMetricsTest problems when executed in Jenkins environment.
Fixes #3160.
Initialization of `StatsProvider` as an instance object for the test class (not statically initialized). This prevents problems if other processes interact with the metrics environment.
Jenkins builds are passing (branch builder 788, 789, 790).
> Issue 3160: streamMetricsTest failure in Jenkins environment

- client/src/main/java/io/pravega/client/ClientConfig.java
If no scheme is specified in the controller URI, rather than throwing an exception, it now defaults to TCP.
Fixes #2669
> Issue 2669: Prevent NPE by defaulting to no tls if no scheme is specified

- test/integration/src/test/java/io/pravega/test/integration/endtoendtest/EndToEndChannelLeakTest.java
* Make sure there is an event for each segment in EndToEndChannelLeakTest
Fixes #2523
`EndToEndChannelLeakTest.testDetectChannelLeakMultiReader()` was slow and mistakenly passing. It was asserting that the EventRead was null, when it was intended to assert that the Event itself was non-null. When this was changed the test failed because no events were being written to the segment. The test now sends events to the segment and asserts that the second reader actually gets one of these events.
> Issue 2523: Fix test bug in EndToEndChannelLeakTest

- client/src/main/java/io/pravega/client/netty/impl/RawClient.java
- client/src/main/java/io/pravega/client/segment/impl/ConditionalOutputStreamImpl.java
- client/src/main/java/io/pravega/client/segment/impl/SegmentMetadataClientImpl.java
Tone down logging on connection close .
Fixes #2208 
Reduce the amount of logging during connection close.
> Issue 2208: Tone down logging on connection close.

- client/src/main/java/io/pravega/client/admin/impl/StreamManagerImpl.java
- client/src/main/java/io/pravega/client/stream/impl/ControllerImpl.java
Ensure StreamManagerImpl does not throw a wrapped exception inside a RuntimeException.
Fixes #2361 
The older code would wrap all the exceptions inside a `RuntimeException`. This PR changes this behavior so that user of StreamManager can catch specific exceptions and handle it appropriately.
```
try (StreamManager streamManager = new StreamManagerImpl(controller, cf)) {
streamManager.createScope("testScope");
} catch (RetriesExhaustedException e) { // the controller api performs retries in case of a connect failure.
// connection failure exception handling
}
```
Also, the streamManger api throws `java.lang.IllegalArgumentException` in case of invalid arguments.
All other exceptions (if any) are of type …
> Issue 2361:Unwrap `CompletionException` in `StreamManagerImpl`

- bindings/src/main/java/io/pravega/storage/filesystem/FileSystemStorage.java
- bindings/src/test/java/io/pravega/storage/extendeds3/S3FileSystemImpl.java
- checkstyle/spotbugs-exclude.xml
- checkstyle/spotbugs-include.xml
- controller/src/test/java/io/pravega/controller/task/Stream/StreamTransactionMetadataTasksTest.java
- gradle/spotbugs.gradle
- test/system/src/test/java/io/pravega/test/system/AbstractScaleTests.java
- test/testcommon/src/main/java/io/pravega/test/common/AssertExtensions.java
Enables more, and more aggressive spotbugs checks
Fixes #3183
* Sets the analysis effort to 'max'
* Removes some of the filters on different types of bugs.
* Includes only high confidence bugs from the experimental filter set.
* Changes code to eliminate all the false positives that arose from the new filters.
* Removes one real 'useless variable' that was located.
> Issue #3183: Enable more spotbugs checks

- client/src/main/java/io/pravega/client/stream/impl/StreamSegments.java
- client/src/test/java/io/pravega/client/stream/impl/StreamSegmentsTest.java
* Prevents a bug in a rare edge case where events from a writer would be consistently sent to the 'incorrect' segment because the internal map was incorrect.
Hopefully fixes #3173
In the case where a segment was sealed and replaced unevenly (not a simple split or merge) and the uneven segments were sealed and replaced before any data was written to them, but and the writer saw the successor to the successor segment before one of the segments from the original generation was sealed AND the controller returned the replacement segments in a non-ascending order, then the writer would alter the end range for the final segment effectively expanding it's keyspace. 
This could lead to bad load-balancing or the …
> Issue 3173: Prevent mis-routing of events

- config/config.properties
- docker/pravega/scripts/init_controller.sh
- docker/pravega/scripts/init_segmentstore.sh
- documentation/src/docs/metrics.md
- shared/metrics/src/main/java/io/pravega/shared/metrics/MetricsConfig.java
- Use `HOSTNAME` environment variable as metrics prefix (re-apply changes made originally by @RaulGracia in #3141).
Fix #3138
Updates Docker init scripts to obtain the `HOSTNAME` environment variable and set it as the metrics prefix in case it is set. `HOSTNAME` is built-in variable that should be present and correctly set by default. 
Reported metrics should be prefixed with the host names.
---
Signed-off-by: Adrián Moreno <adrian@morenomartinez.com>
> Issue 3138: Use HOSTNAME envvar as metrics prefix

- controller/src/main/java/io/pravega/controller/store/stream/AbstractStreamMetadataStore.java
- controller/src/main/java/io/pravega/controller/store/stream/InMemoryStreamMetadataStore.java
- controller/src/test/java/io/pravega/controller/store/stream/StreamMetadataStoreTest.java
If a stream is only partially created, with no configuration created yet (or failed) then `liststreamsinscope` api fails to list streams. 
Fixes #1510 
Ignores streams for which we get data not found exception while doing getConfiguration. 
Unit test added.
> Issue 1510: List streams in scope throws exception if there is partially created stream with no configuration

- segmentstore/server/host/src/main/java/io/pravega/segmentstore/server/host/handler/PravegaRequestProcessor.java
Ensure Conditional attribute update failure is not logged at ERROR level.
Fixes #3164 
The method `io.pravega.segmentstore.server.host.handler.PravegaRequestProcessor#updateSegmentAttribute` used to invoke `handleException()` twice , once via `whenComplete(..)` and once via `exceptionally(...)` block.
This additional invocation of `handleException()` has been removed.
This change also ensures that the log spam during conditional appends is removed.
No changes to functionality, all the existing tests should continue to pass.
> Issue 3164: Remove redundant handleException invocation.

- shared/metrics/src/main/java/io/pravega/shared/MetricsNames.java
- shared/metrics/src/main/java/io/pravega/shared/metrics/OpStatsLoggerImpl.java
- shared/metrics/src/test/java/io/pravega/shared/MetricsNamesTest.java
…receding measurement as "_fail"; also added source for active_segments
moved "-fail" suffix out of container id and move into preceding measurement as "_fail"; also added source for active_segments.
Fixes #1931 
When fail metric is being created, instead of simply append "-fail" onto the metric name, the code checks if the last segment of metric is an integer (such as container id); if it is, then "_fail" is appended to the preceding measurement instead of the integer itself - this is to easy the filtering of metrics.
Metrics such as "pravega.segmentstore.segmentstore.container.operation.latency_ms.1-fail" now becomes …
> Issue 1931: moved "-fail" suffix out of container id and move into preceding measurement

- controller/src/main/java/io/pravega/controller/server/eventProcessor/requesthandlers/CommitRequestHandler.java
- controller/src/test/java/io/pravega/controller/server/eventProcessor/ControllerEventProcessorTest.java
SealStream with outstanding transactions in committing state had a bug found through spotBugs. 
This change adds a new unit test for sealing and commit transactions inter relationship and fixes the issue found.
Fixes #3122 
New unit test added to test seal stream with outstanding commits. 
1. create transaction on epoch 0. set txn to committing. 
2. scale stream
3. create transaction on epoch 1. set txn to committing. 
4. seal stream --> this should get postponed. 
5. commit transaction on epoch 1. This gets committed. 
6. commit transaction on epoch 0. This should get committed while rolling over. 
7. seal stream -> this should complete successfully …
> Issue 3122: Bug in Seal stream with commit

- test/system/src/main/java/io/pravega/test/system/framework/kubernetes/K8sClient.java
- test/system/src/main/java/io/pravega/test/system/framework/services/kubernetes/AbstractService.java
- test/system/src/test/java/io/pravega/test/system/AbstractScaleTests.java
- test/system/src/test/java/io/pravega/test/system/BatchClientSimpleTest.java
- test/system/src/test/java/io/pravega/test/system/PravegaTest.java
- test/system/src/test/java/io/pravega/test/system/ReadTxnWriteAutoScaleWithFailoverTest.java
- test/system/src/test/java/io/pravega/test/system/ReadWriteAndAutoScaleWithFailoverTest.java
- test/system/src/test/java/io/pravega/test/system/RetentionTest.java
- Ensure pravega operator version is configurable.
- Increase retries for log download.
- Fix bug in PravegaTest.
Fixes #3213
- On slower / resource starved clusters log download would fail as the pod creation would take a longer time. Now the framework retries for  a longer duration.
- A bug in PravegaTest has been fixed which caused the test to exit when the read timed out.
- Pravega operator is now configurable.
All the tests should continue to pass.
> Issue 3213: Fix System test framework and test issues.

- controller/src/main/java/io/pravega/controller/server/eventProcessor/requesthandlers/CommitRequestHandler.java
- controller/src/main/java/io/pravega/controller/store/stream/AbstractStreamMetadataStore.java
- controller/src/main/java/io/pravega/controller/store/stream/PersistentStreamBase.java
- test/integration/src/test/java/io/pravega/test/integration/ControllerMetricsTest.java
This PR reallocates the reporting logic of transaction commits metric, as it was not being used in its former location.
Fixes #3171.
Due to changes in PR #2971, the logic for reporting committed transactions metric (contained in `AbstractStreamMetadataStore.java`) was not being invoked. To fix this, this PR:
1.- Moves the reporting logic OF committed transactions metric to `CommitRequestHandler.java`.
2.- Minimizes the number of invocations to `getNumberOfOngoingTransactions()` upon commits, as it is an expensive metadata call. Now, instead of calling this method per transaction commit, we execute it once when a batch of transaction commits finishes in `AbstractStreamMetadataStore` …
> Issue 3171: Transaction commits metric not being reported

- controller/src/main/java/io/pravega/controller/server/Main.java
- controller/src/main/java/io/pravega/controller/store/stream/ZKStreamMetadataStore.java
This PR moves the initialization of metrics from `ZKStreamMetadataStore` to `Main` in the Controller. This change has been taken from PR #3117.
Fixes #3224.
Changes the location of initialization of metrics in the Controller to avoid problems on Controller restarts. Manifestations of these problems can be seen in issues #3077, #3170 (i.e., `java.lang.IllegalArgumentException: Reporter already started`).
All test should be passing as before. Checked in a local deployment that metrics are being reported by the Controller.
> Issue 3224: Fix metrics reporter start in r0.4

- client/src/main/java/io/pravega/client/segment/impl/SegmentInputStreamImpl.java
- client/src/test/java/io/pravega/client/segment/impl/SegmentInputStreamTest.java
- test/integration/src/test/java/io/pravega/test/integration/BoundedStreamReaderTest.java
Ensure the precondition check inside `SegmentInputStreamImpl` checks if `endOffset >= startOffset`
Fixes #3221 
Correct the precondition check.
All the tests should continue to pass. 
Verified that the `io.pravega.test.system.StreamCutsTest` passes on a PKS cluster.
> Issue 3221: Fix Invalid Precondition check in SegmentInputStreamImpl 

- client/src/main/java/io/pravega/client/stream/ReaderNotInReaderGroupException.java
- client/src/main/java/io/pravega/client/stream/impl/ControllerImpl.java
- client/src/main/java/io/pravega/client/stream/impl/EventStreamReaderImpl.java
- client/src/main/java/io/pravega/client/stream/impl/ReaderGroupStateManager.java
- client/src/test/java/io/pravega/client/stream/impl/EventStreamReaderTest.java
- client/src/test/java/io/pravega/client/stream/impl/ReaderGroupStateManagerTest.java
* Make ReinitializationRequiredException Runtime
* Always call close when ReinitializationRequiredException is thrown.
Fixes #2199 and Fixes #2200.
Moves the wrapping try-catch-rethrow from the site where the exception is generated to readNextEvent which is the only public method that can throw the exception. Because we need to explicitly handle this case internally but an external caller no longer needs to, the exception is split into two:
* The internal Cause ReaderNotInReaderGroupException which is checked an explicitly handled.
* The public exception ReinitializationRequiredException which is the same as before but now extends from RuntimeException …
> Issue 2200: Properly handle ReinitializationRequiredException in client

- checkstyle/spotbugs-exclude.xml
javac from JDK11+ adds a null-check in try-with-resources
Spotbugs reports this as a reduntant check
See the discussion at  https://github.com/spotbugs/spotbugs/issues/756
The only work-around is to disable the rules
Signed-off-by: Enrico Olivelli <eolivelli@apache.org>
Disable Redundant-Null-Check related rules
Fixes #3240
Disable Redundant-Null-Check related rules
JAVA_HOME=/path/to/jdk11 ./gradlew spotbugsMain spotbugsTest
(unfortunately current master cannot build on JDK11)
> Issue 3240: Disable Spotbugs rules not working on JDK11:

- checkstyle/checkstyle.xml
- gradle/checkstyle.gradle
The fix is to use an absolute path in order to refer to the suppressions.xml file.
See detailed explanation in #3244 
Fixes #3244
Compute the absolute path during the execution of the build configuration script and do not rely on relative paths
run this command without errors
`JAVA_HOME=/path/to/jdk11 ./gradlew checkstyleMain checkstyleTest
`
> Issue 3244: Checkstyle fails on JDK11 while using Gradle daemon - needs an absolute path

- common/src/test/java/io/pravega/common/util/CircularBufferTests.java
* Add tests for circular buffer
Fixes #3256
Adds tests that were not originally implemented. (Because they were covered by more complex tests)
> Issue 3256: Add more tests to circular buffer

- config/config.properties
- docker/pravega/scripts/init_segmentstore.sh
- segmentstore/server/src/main/java/io/pravega/segmentstore/server/store/ServiceConfig.java
Increase default size of storage thread pool.
Fixes #3249
The code changes the default value of number of storage threads.
Storage threads are mostly i/o bound and are blocked while i/o is pending. As such the throughput is constrained by available threads, so bigger the thread pool the better. 
The number is 10 times previous value. (Although during testing I have seen no negative impact with upto 1K threads.)
This is only a config change.
All usual tests should continue to pass.
Performance tests should show increased throughput.
> Issue 3249: Increase storage thread pool size.

- config/config.properties
- documentation/src/docs/metrics.md
- shared/metrics/src/main/java/io/pravega/shared/metrics/DynamicLoggerImpl.java
- shared/metrics/src/main/java/io/pravega/shared/metrics/MetricsConfig.java
- shared/metrics/src/main/java/io/pravega/shared/metrics/StatsProviderImpl.java
- test/integration/src/test/java/io/pravega/test/integration/ControllerMetricsTest.java
- test/integration/src/test/java/io/pravega/test/integration/MetricsTest.java
Enable `dynamicCacheEvictionDurationMs` to be configured in `config.properties` file (replaces the existing `dynamicTTLSeconds` entry in configuration).
Fixes #3252.
In `config.properties`, there is a metrics configuration parameter that is not used anywhere: `dynamicTTLSeconds`. The description of this parameter matches the purpose of `dynamicCacheEvictionDurationMs`, which is the actual one used in `MetricsConfig.java`. This PR just replaces the apparently mistaken parameter name by the correct one in the configuration.
No changes in the code. All the tests should be working as before.
> Issue 3252: Wrong metrics configuration parameter (dynamicTTLSeconds)

- test/system/src/test/java/io/pravega/test/system/AbstractScaleTests.java
Fix the initialization order in AbstractScaleTests.
Fixes #3269 
Correct the initialization order.
Verified that 
`io.pravega.test.system.AutoScaleTest.scaleTests` and 
`io.pravega.test.system.ReadWithAutoScaleTest.scaleTestsWithReader` work fine with this change.
> Issue 3269: Fix invalid initialization order in AbstractScaleTests.

- bindings/src/main/java/io/pravega/storage/extendeds3/ExtendedS3Storage.java
- bindings/src/main/java/io/pravega/storage/filesystem/FileSystemStorage.java
- bindings/src/main/java/io/pravega/storage/hdfs/HDFSStorage.java
- segmentstore/server/src/main/java/io/pravega/segmentstore/server/attributes/SegmentAttributeBTreeIndex.java
- segmentstore/server/src/main/java/io/pravega/segmentstore/server/containers/StorageMetadataStore.java
- segmentstore/server/src/main/java/io/pravega/segmentstore/server/writer/SegmentAggregator.java
- segmentstore/server/src/test/java/io/pravega/segmentstore/server/TestStorage.java
- segmentstore/server/src/test/java/io/pravega/segmentstore/server/containers/ReadOnlySegmentContainerTests.java
- segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/AsyncStorageWrapper.java
- segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/Storage.java
- segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/SyncStorage.java
- segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/mocks/InMemoryStorage.java
- segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/rolling/RollingStorage.java
- segmentstore/storage/src/test/java/io/pravega/segmentstore/storage/AsyncStorageWrapperTests.java
Segment create returns a read-write SegmentHandle . This  eliminates the redundant fencing/ checks.
Fixes [#3264](https://github.com/pravega/pravega/issues/3264)
All SyncStorage implementations now return  read-write SegmentHandle (and avoid redundant checks/file access)
All unit tests and integration tests should pass.
Some improvement in performance.
> Issue 3264: Return a SegmentHandle from Storage create method.

- test/system/src/main/java/io/pravega/test/system/framework/services/kubernetes/AbstractService.java
Set image pull policy to "Always" in k8 system test framework.
Fixes #3285.
Sets the default `IMAGE_PULL_POLICY` to `Always` in k8 system test framework. Otherwise, we could end up using an old (cached) image version unexpectedly. 
System tests should pass and use the latest version of the images available.
> Issue 3285: Always pull images in k8 system test framework

- gradle/rat.gradle
* Exclude passwd files from the build.
Fixes #3287
Changes the rat configuration to exclude all files ending in 'passwd' as opposed to just those named 'passwd'
> Issue #3287: Exclude "passwd" extensions from rat.

- client/src/main/java/io/pravega/client/stream/impl/StreamCutImpl.java
* Make a defensive copy of streamCut's position map
Fixes #2001
Makes a defensive copy. This shouldn't be needed, I verified all the call sites, but as there are now many, it's better to be careful.
> Issue 2001: Make a defensive copy of streamCut's position map

- bindings/src/main/java/io/pravega/storage/extendeds3/ExtendedS3Storage.java
- bindings/src/main/java/io/pravega/storage/filesystem/FileSystemStorage.java
- bindings/src/main/java/io/pravega/storage/hdfs/HDFSExceptionHelpers.java
- build.gradle
- client/src/main/java/io/pravega/client/admin/impl/ReaderGroupManagerImpl.java
- client/src/main/java/io/pravega/client/segment/impl/ConditionalOutputStreamImpl.java
- client/src/main/java/io/pravega/client/segment/impl/SegmentOutputStreamImpl.java
- common/src/main/java/io/pravega/common/Exceptions.java
- common/src/main/java/io/pravega/common/concurrent/Futures.java
- controller/src/main/java/io/pravega/controller/server/ControllerService.java
- controller/src/main/java/io/pravega/controller/store/checkpoint/ZKCheckpointStore.java
- controller/src/main/java/io/pravega/controller/store/stream/PersistentStreamBase.java
- controller/src/main/java/io/pravega/controller/store/stream/ZKGarbageCollector.java
- gradle.properties
- segmentstore/server/src/main/java/io/pravega/segmentstore/server/logs/OperationProcessor.java
- test/system/src/main/java/io/pravega/test/system/framework/kubernetes/K8sClient.java
* Changes Lombok, spotbugs-annotations, and jcip-annotations into compile time dependencies (as opposed to being required at runtime.
Fixes #3289.
Should have no functional impact.
We need to test the build on all appropriate environments.
> Issue #3289: Use compile-time dependencies where possible

- documentation/src/docs/metrics.md
- segmentstore/server/host/src/main/java/io/pravega/segmentstore/server/host/handler/AppendProcessor.java
- segmentstore/server/host/src/main/java/io/pravega/segmentstore/server/host/handler/PravegaConnectionListener.java
- segmentstore/server/host/src/main/java/io/pravega/segmentstore/server/host/handler/PravegaRequestProcessor.java
- segmentstore/server/host/src/test/java/io/pravega/segmentstore/server/host/handler/AppendProcessorTest.java
- segmentstore/server/host/src/test/java/io/pravega/segmentstore/server/host/handler/PravegaRequestProcessorAuthFailedTest.java
- segmentstore/server/host/src/test/java/io/pravega/segmentstore/server/host/handler/PravegaRequestProcessorTest.java
Made DYNAMIC_LOGGER of AppendProcessor and PravegaRequestProcessor non-static,  hence we don't have to overwrite static variable in test code which may cause race condition when concurrent tests run
Fixes #3239
Changed DYNAMIC_LOGGER of AppendProcessor and PravegaRequestProcessor from static to non-static, and added setter for it. 
In the test code, DYNAMIC_LOGGER is set up with mock object, which is of instance scope, to prevent race condition.
Unit tests passed. 
Need to observe further at Travis to ensure no race condition to happen.
> Issue-3239: make DYNAMIC_LOGGER non-static to avoid test code race condition

- client/src/main/java/io/pravega/client/stream/impl/ControllerImpl.java
- client/src/main/java/io/pravega/client/stream/impl/PravegaCredentialsWrapper.java
The class name ``PravegaCredsWrapper`` and variables ``creds`` were slightly confusing terms, and can tax a reader's memory. 
Fixes #2768. 
Note that the other change mentioned in #2768, i.e. relocating CredentialsExtractorTest.java, wasn't found necessary. This is because the test really exercises a method of ClientConfigBuilder class, which in turn happens to be the same package (``io.pravega.client``) as the test class. 
Renamed ``PravegaCredsWrapper`` class and ``creds`` variables to ``PravegaCredentialsWrapper`` and ``credentials`` respectively.
Manual inspection, apart from the successful run of automated tests.
> Issue #2768: Rename PravegaCredsWrapper class and its member variable

- controller/src/main/java/io/pravega/controller/server/retention/StreamCutService.java
- controller/src/main/java/io/pravega/controller/store/stream/AbstractStreamMetadataStore.java
- controller/src/main/java/io/pravega/controller/store/stream/InMemoryStreamMetadataStore.java
- controller/src/main/java/io/pravega/controller/store/stream/StreamMetadataStore.java
- controller/src/main/java/io/pravega/controller/store/stream/ZKStreamMetadataStore.java
- controller/src/test/java/io/pravega/controller/store/stream/ZKStreamMetadataStoreTest.java
Cherry pick changes from PR #3272 to branch `r0.4`.
Fixes #3223.
For a description, please check PR #3272.
For a description, please check PR #3272.
> Issue 3223: RetentionTest failure

- segmentstore/server/host/src/test/java/io/pravega/segmentstore/server/host/BookKeeperIntegrationTestBase.java
- segmentstore/server/src/main/java/io/pravega/segmentstore/server/store/ServiceBuilder.java
- segmentstore/server/src/main/java/io/pravega/segmentstore/server/store/ServiceConfig.java
- segmentstore/server/src/test/java/io/pravega/segmentstore/server/store/StreamSegmentStoreTestBase.java
- segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/rolling/RollingStorage.java
- Simplified the `StreamSegmentStoreTestBase.testEndToEndWithFencing` to do fewer fencing tests (4, down from 5) and to not do segment mergers or seals. 
- Added the ability to assign an Instance Id to a Segment Store instance, which will be output during logging. 
- Fixed two bugs in `RollingStorage` which could leave upstream code in a bad state.
Fixes #2933.
- Instance Id is useful if multiple Segment Store instances run in the same process or output to the same log files. This will be included in the Thread names so that log output can be properly associated with an instance.
- This is defaulted to empty string, which means for normal, production code, it will not add anything. It's just set for …
> Issue 2933: (SegmentStore) testEndToEndWithFencing fixes

- client/src/main/java/io/pravega/client/netty/impl/ClientConnection.java
- client/src/main/java/io/pravega/client/netty/impl/ClientConnectionInboundHandler.java
- client/src/main/java/io/pravega/client/netty/impl/RawClient.java
- client/src/main/java/io/pravega/client/segment/impl/AsyncSegmentInputStreamImpl.java
- client/src/test/java/io/pravega/client/admin/impl/StreamManagerImplTest.java
- client/src/test/java/io/pravega/client/batch/impl/BatchClientImplTest.java
- client/src/test/java/io/pravega/client/byteStream/ByteStreamReaderTest.java
- client/src/test/java/io/pravega/client/byteStream/ByteStreamWriterTest.java
- client/src/test/java/io/pravega/client/netty/impl/RawClientTest.java
- client/src/test/java/io/pravega/client/segment/impl/AsyncSegmentInputStreamTest.java
- client/src/test/java/io/pravega/client/segment/impl/ConditionalOutputStreamTest.java
- client/src/test/java/io/pravega/client/segment/impl/SegmentMetadataClientTest.java
- client/src/test/java/io/pravega/client/segment/impl/SegmentOutputStreamTest.java
- client/src/test/java/io/pravega/client/stream/mock/MockController.java
- controller/src/main/java/io/pravega/controller/server/SegmentHelper.java
- controller/src/test/java/io/pravega/controller/server/SegmentHelperTest.java
- enable ClientConnection callers to be notified of errors
- switch to ClientConnection#sendAsync in SegmentHelper and RawClient in order not to perform blocking calls inside Netty EventLoops
Fixes #3279
Add a CompletedCallback parameter to ClientConnection#sendAsync.
Replace calls to ClientConnection#send in SegmentHelper and RawClient with sendAsync, this way we won't perform a blocking operation inside the Netty event loop.
Tests must pass.
Cherry picking this change on top of #3192 will make tests which are failing due to BlockingOperationException pass
> Issue 3279: Client is performing blocking operations inside Netty Event Loop

- .travis.yml
- build.gradle
- gradle/java.gradle
Force java source and target version to be "8", by setting sourceCompatibility and targetCompatibily after project 'evaluation'.
Current configuration is not working correctly as it is not really applied to every project.
Fixes #3258 
Change Gradle configuration in order to force Java Bytecode compatibility level
`JAVA_HOME=/path/to/jdk11 ./gradlew build`
> Issue 3258: Build fails on JDK11: Bytecode is targeted jdk11 and not jdk8

- test/system/src/test/java/io/pravega/test/system/AbstractReadWriteTest.java
- test/system/src/test/java/io/pravega/test/system/ReadWithAutoScaleTest.java
Make ReadWithAutoScaleTest to wait for transactions to be in committed state before stopping the readers.
Fixes #3310.
Executes `waitForTxnsToComplete()` in `ReadWithAutoScaleTest` after signalling all the writers to stop for ensuring that all the transactions are in `committed` state before stopping the readers. This is the approach followed by the other tests working on transactions. We also deleted a useless flag in `AbstractReadWriteTest` related to transactional writers.
`ReadWithAutoScaleTest` should pass consistently in system tests (at the moment, 1 successful test execution).
> Issue 3310: Wait for transactions to be committed in ReadWithAutoScaleTest

- client/src/main/java/io/pravega/client/tables/impl/KeyVersion.java
- client/src/main/java/io/pravega/client/tables/impl/KeyVersionImpl.java
- client/src/main/java/io/pravega/client/tables/impl/TableEntryImpl.java
- client/src/main/java/io/pravega/client/tables/impl/TableKey.java
- client/src/main/java/io/pravega/client/tables/impl/TableKeyImpl.java
- client/src/test/java/io/pravega/client/tables/impl/KeyVersionTest.java
- controller/src/main/java/io/pravega/controller/server/SegmentHelper.java
- controller/src/main/java/io/pravega/controller/server/WireCommandFailedException.java
- controller/src/test/java/io/pravega/controller/server/SegmentHelperTest.java
- shared/protocol/src/main/java/io/pravega/shared/protocol/netty/FailingReplyProcessor.java
- shared/protocol/src/main/java/io/pravega/shared/protocol/netty/ReplyProcessor.java
- shared/protocol/src/main/java/io/pravega/shared/protocol/netty/WireCommands.java
Enable Tablestore apis on SegmentHelper. This will ensure the controller can access the TableStore apis.
Issue #2895 
- Implementation of interfaces `KeyVersion`, `TableKey` and `TableValue` on the client.
- Enable tablestore apis on SegmentHelper.
> Issue 2895: Enable Tablestore apis on SegmentHelper.

- client/src/main/java/io/pravega/client/stream/impl/ControllerImpl.java
- client/src/main/java/io/pravega/client/stream/impl/StreamSegments.java
- client/src/test/java/io/pravega/client/stream/impl/EventStreamWriterTest.java
- client/src/test/java/io/pravega/client/stream/impl/SegmentSelectorTest.java
- client/src/test/java/io/pravega/client/stream/impl/StreamSegmentsTest.java
- client/src/test/java/io/pravega/client/stream/impl/TransactionalEventStreamWriterTest.java
- client/src/test/java/io/pravega/client/stream/mock/MockController.java
- controller/src/main/java/io/pravega/controller/server/eventProcessor/LocalController.java
Add more tests and sanity checks on the client when dealing with splits and merges.
Adds assertions and more information to the in-memory structure which should prevent issues like #3173 from occurring and detect them quickly if they do. Adds more test coverage for this code path.
Adds more tests and assertions. Should not have functional changes.
*Caveat*: In the code before this change in a split followed by a merge where the segments were accessed in a staggered way, (Such as in `testOutOfOrderSplit` and `testOutOfOrderSplit2` which are included in this PR.) it previously could have included a new segment into the map for part of its range overlapping an old sealed segment. This is inconsistent and would …
> Issue 3173: Add assertions and tests

- test/integration/src/test/java/io/pravega/test/integration/BoundedStreamReaderTest.java
Fix a compilation issue caused due to a cherry pick of PR 3222.
Fixes #3326 
Fixes the build issue due to cherry pick.
No changes in functionality. All the existing tests should continue to pass.
> Issue 3326: Fix compilation issue in BoundedStreamReaderTest

- controller/src/main/java/io/pravega/controller/server/rpc/auth/PasswordAuthHandler.java
- controller/src/main/java/io/pravega/controller/server/rpc/auth/TestAuthHandler.java
- controller/src/main/java/io/pravega/controller/server/rpc/auth/UserPrincipal.java
- controller/src/test/java/io/pravega/controller/server/rpc/auth/UserPrincipalTest.java
Classes ``PasswordAuthHandler`` and ``TestAuthHandler`` were using ``com.sun.security.auth.UnixPrincipal`` as the principal identifying the user. ``UnixPrincipal`` is an internal implementation class of Oracle's JDK and is not intended to be used outside. Using it had the following disadvantages: 
* Being an internal implementation class, it can be changed or dropped any time. It may also cause issues due to modularization in JDK 9 or above. 
* It was a poor abstraction for the entity it was supposed to represent in Pravega. 
Besides, for what it's worth, presumably Java implementations other than Oracle/OpenJDK may not have this class. 
Resolves #2821. 
* Adds an implementation of …
> Issue 2821: Replace UnixPrincipal with a custom Principal implementation

- client/src/main/java/io/pravega/client/segment/impl/SegmentOutputStreamImpl.java
- segmentstore/server/host/src/main/java/io/pravega/segmentstore/server/host/stat/AutoScaleProcessor.java
- segmentstore/server/host/src/main/java/io/pravega/segmentstore/server/host/stat/SegmentStatsFactory.java
- segmentstore/server/host/src/test/java/io/pravega/segmentstore/server/host/stat/AutoScaleProcessorTest.java
This is the same as: https://github.com/pravega/pravega/pull/3323 but ported to the 0.4 branch.
* Adding a timeout/retry to flush in SegmentOutputStreamImpl.
* Putting AutoScaleProcessor's send in a background thread.
Provides a workaround for #3313 
Adds a timeout to the flush call inside of SegmentOutputStream so that in the event that the server does not reply, eventually the situation is resolved by restarting the connection.
Moves the logic in AutoScaleProcessor that calls into the client onto a background thread pool. This relates to the underlying issue in #3313 because there the ack was being held up because the thread on the server to ack the …
> Issue 3313: Add workaround for client blocking

- client/src/main/java/io/pravega/client/stream/impl/ReaderGroupState.java
- client/src/main/java/io/pravega/client/stream/impl/ReaderGroupStateManager.java
* Tolerate an incomplete Position (partial sets of segments in Position object).
Provides a workaround for #3333. **Note**: This is **not** a fix. There is still an issue, this just prevents an exception in the controller process.
Avoids throwing an exception.
The system tests should now no longer have issues with the built in streams.
> Issue 3333: Tolerate partial set of segments in Position object.

- test/system/src/main/java/io/pravega/test/system/framework/services/docker/BookkeeperDockerService.java
- test/system/src/main/java/io/pravega/test/system/framework/services/docker/HDFSDockerService.java
- test/system/src/main/java/io/pravega/test/system/framework/services/docker/PravegaControllerDockerService.java
- test/system/src/main/java/io/pravega/test/system/framework/services/docker/PravegaSegmentStoreDockerService.java
Renamed and standardize log volumes.
Fixes #3328.
This PR fixes the path used to mount the logs directory of Pravega services on the host machine. This allows us to persistently store Pravega logs in the host machine, so they can survive to the lifecycle of containers. 
Now logs are being persistently stored in the host machine:
```
[root@xxx-slave-2 ~]# ls /var/lib/docker/volumes/logs-volume/_data/
segmentstore_2019-01-30.0.log.gz  segmentstore_2019-01-30.1.log.gz  segmentstore_2019-01-30.2.log.gz  segmentstore_2019-01-30.3.log.gz  segmentstore.log
[root@xxx-slave-2 ~]# ls /var/lib/docker/volumes/volume-logs/_data/
controller_2019-01-30.0.log.gz  controller.log
```
> Issue 3328: Wrong target log path in Docker Swarm Pravega services

- test/system/src/main/java/io/pravega/test/system/framework/kubernetes/K8sClient.java
- test/system/src/main/java/io/pravega/test/system/framework/services/kubernetes/BookkeeperK8sService.java
- test/system/src/main/java/io/pravega/test/system/framework/services/kubernetes/K8SequentialExecutor.java
- test/system/src/main/java/io/pravega/test/system/framework/services/kubernetes/PravegaControllerK8sService.java
- test/system/src/main/java/io/pravega/test/system/framework/services/kubernetes/PravegaSegmentStoreK8sService.java
- test/system/src/main/java/io/pravega/test/system/framework/services/kubernetes/ZookeeperK8sService.java
- Ensure spurious stack traces are not logged for retry able errors.
- Ensure test logs are preserved across retries during log downloads.
- Wait for log download to complete before starting the next test.
Fixes #3329 
- Ensure spurious stack traces are not logged for retry able errors.
- Ensure test logs are preserved across retries during log downloads.
- Wait for log download to complete before starting the next test.
Update: verified with a system test run on PKS cluster.
> Issue 3329:  Remove spurious stacktraces from Kubernetes framework

- test/system/src/main/java/io/pravega/test/system/framework/kubernetes/K8sClient.java
Ensure networkInterceptors are cleared before invoking `io.kubernetes.client.apis.CoreV1Api#listNamespacedPodAsync`.
Fixes #3358
The stack overflow error is due to `com.squareup.okhttp.OkHttpClient#networkInterceptors` being repeatedly added during the invocation of `CoreV1Api#listNamespacedPodAsync` .
This adds a workaround to ensure we clear the network interceptors before invoking the `listNamespacedPodAsync` . This workaround can be removed once this issue is resolved in the kubernetes-client /okhttp library.
Verified that the tests run on the K8s cluster.
> Issue 3358: Fix stack overflow error caused by okhttp used by kubernetes-java client.

- standalone/src/test/java/io/pravega/local/TlsEnabledInProcPravegaClusterTest.java
Increase read timeouts (tripled) to avoid test failures under abnormal delays in build/test environments. 
Fixes #3342. 
Increases the read timeout. 
Tests in TlsEnabledInProcPravegaClusterTest pass consistently.
> Issue 3342: Increase the read timeout to avoid test failure 

- build.gradle
- docker/pravega/Dockerfile
Alpine images have recently switched from glibc to musl, making non-musl compatible libraries like RocksDB to suddenly fail. This PR installs the `gcompat` Alpine package to provide support for non-musl compatible libraries. Also, it removes the `libc6-compat` package as it is not needed anymore. `libc6-compat` provided support for musl libraries to run in a glibc environment.
This PR also makes sure that the base image is always up to date before building Pravega and BookKeeper images.
Fix #3363 
Updates Pravega Dockerfile to install the new package and build.gradle to make sure base images are always up to date.
---
Signed-off-by: Adrián Moreno …
> Issue 3363: Install musl compatibility library for glibc programs

- build.gradle
- client/src/main/java/io/pravega/client/admin/StreamInfo.java
- client/src/main/java/io/pravega/client/batch/StreamInfo.java
- client/src/main/java/io/pravega/client/byteStream/ByteStreamReader.java
- client/src/main/java/io/pravega/client/byteStream/ByteStreamWriter.java
- client/src/main/java/io/pravega/client/state/StateSynchronizer.java
- client/src/main/java/io/pravega/client/stream/Checkpoint.java
- client/src/main/java/io/pravega/client/stream/Position.java
- client/src/main/java/io/pravega/client/stream/StreamConfiguration.java
- client/src/main/java/io/pravega/client/stream/StreamCut.java
- client/src/main/java/io/pravega/client/stream/notifications/notifier/AbstractNotifier.java
* Fix some issues with Javadocs
* Import Lombok when generating Javadocs to reduce errors
* Suppress minor warnings.
Fixes #3341 
Removes 95% of out warnings from the `generateJavadoc` target and 100% for the `javadocs` target.
> Issue 3341: Remove many Javadoc warning

- test/system/src/main/java/io/pravega/test/system/framework/services/kubernetes/BookkeeperK8sService.java
Remove workaround of manually deleting pvc after scaling down Bookkeeper.
Fixes #3379 
Remove the workaround in BookkeeperK8sService.java of deleting pvc incase of Bookkeeper scale down.
pravega-operator `0.3.0-rc3` has the fix for automatically deleting the pvc.
Verified that the system test BookieFailoverTest works fine.
> Issue 3379: Remove workaround of deleting pvc after scaling down Bookkeeper.

- client/src/main/java/io/pravega/client/netty/impl/ConnectionFactoryImpl.java
- segmentstore/server/host/src/main/java/io/pravega/segmentstore/server/host/stat/AutoScaleProcessor.java
- standalone/src/main/java/io/pravega/local/InProcPravegaCluster.java
- standalone/src/test/java/io/pravega/local/TlsEnabledInProcPravegaClusterTest.java
Fix TLS-related bugs in code that was causing exceptions to be thrown and logged. Also resolve the root cause behind the flakiness of TlsEnabledInProcPravegaClusterTest test. 
Fixes #3372. 
* Fixes a bug in AutoScaleProcessor which led to multiple SSL-related errors. 
* The TlsEnabledInProcPravegaClusterTest test now checks for whether an event is a checkpoint event, before making a test assertion about the contents of the event. 
* Run TlsEnabledInProcPravegaClusterTest in a loop to check that the test runs successfully over several runs.
* Standalone mode works properly with TLS enabled configuration
> Issue 3372: Fix for TLS-related exceptions and test failure 

- client/src/main/java/io/pravega/client/netty/impl/ConnectionFactoryImpl.java
- segmentstore/server/host/src/main/java/io/pravega/segmentstore/server/host/stat/AutoScaleProcessor.java
- standalone/src/main/java/io/pravega/local/InProcPravegaCluster.java
- standalone/src/test/java/io/pravega/local/TlsEnabledInProcPravegaClusterTest.java
* Ports PR #3377 to branch `r0.4`
* Fixes a bug in AutoScaleProcessor which led to multiple SSL-related errors.
* The TlsEnabledInProcPravegaClusterTest test now disables automatic checkpoint events to avoid null events being read back.
Fixes #3372 
See #3377 
See #3377
> Issue 3372: Fix for TLS-related exceptions and test failure - r0.4 port  (#3377)

- segmentstore/server/host/src/main/java/io/pravega/segmentstore/server/host/stat/AutoScaleProcessor.java
Improved logging of AutoScaleProcessor for better tracking auto-scale events.
Fixes #3388.
This PR provides a couple fixes on the logging of `AutoScaleProcessor:writeRequest`:
- Use the actual `requestId` field of events in the logs (instead of the timestamp).
- Log the auto-scale events; this was missing before due to the lack of formatting anchors. 
No changes in logic, just logging. All tests should pass as before this PR. 
> Issue 3388: Fix AutoScaleProcessor logging

- .travis.yml
* Adds a stage to the Travis configuration to build Javadocs.
Fixes #3393 
There is no code change. It adds to the Travis configuration to build Javadocs and verify that the build isn't broken.
It should be triggered on every build.
> Issue 3393: Add javadocs stage to Travis

- build.gradle
Ensure that during a build the jvm version is logged and use the constants for specify the sourcecompatability and targetcompatability.
Fixes #3391 
Pravega docker containers can fail with `Caused by: java.lang.NoSuchMethodError: java.nio.ByteBuffer.position(I)Ljava/nio/ByteBuffer;` if we build pravega on JDK 9+ (with source and target as 1.8) and run on jre8. The docker containers for Pravega are configured to used openjre:8 and hence will face `java.lang.NoSuchMethodError`.
We are observing this error sporadically on our jenkins build system and this change would help to confirm the JVM version used during the build.
```
gradle build output:
> Configure project :
Build JVM Version is : 1.8.0_201 (Oracle …
```
> Issue 3391: Log the build JVM version during pravega build.

- client/src/main/java/io/pravega/client/tables/impl/IteratorState.java
- client/src/main/java/io/pravega/client/tables/impl/IteratorStateImpl.java
- client/src/main/java/io/pravega/client/tables/impl/KeyVersion.java
- client/src/main/java/io/pravega/client/tables/impl/TableKey.java
- client/src/main/java/io/pravega/client/tables/impl/TableSegment.java
- controller/src/main/java/io/pravega/controller/server/SegmentHelper.java
- controller/src/test/java/io/pravega/controller/server/SegmentHelperTest.java
- segmentstore/server/host/src/main/java/io/pravega/segmentstore/server/host/handler/PravegaRequestProcessor.java
Enable TableStore iterator apis on the SegmentHelper.
Fixes#2895
- This PR adds helper methods to enable the controller to access the table store iterator apis.
- It also ensures that the usage of `io.netty.buffer.ByteBuf#array` is used only if the backing array is present. If the backing array is not present (off heap buffer) then the netty api can throw an `UnsupportedOperationException`. Also, the first byte `io.netty.buffer.ByteBuf#array` need not correspond to the first byte of the buffer since the `ByteBuf` can be a slice of other buffer or a pooled Buffer.
All the newly added tests and existing tests should continue to pass.
> Issue 2895: Enable TableStore iterator apis on SegmentHelper.

- config/standalone-config.properties
- standalone/src/main/java/io/pravega/local/InProcPravegaCluster.java
Fix a bug that makes auth-related configuration item ``singlenode.passwdFile`` mandatory for TLS. 
Fixes #3398 
* Modifies the pre-conditions related to TLS parameters in `InProcPravegaCluster` class
* Changes the order of properties in `standalone-config.properties` file, to bring the auth-related config near auth-related config items
1. Configure standalone server to communicate using SSL/TLS. To do so, edit the TLS-related properties in ``standalone-config.properties`` as shown below:
```
singlenode.enableTls=true
singlenode.keyFile=../config/key.pem
singlenode.certFile=../config/cert.pem
singlenode.keyStoreJKS=../config/standalone.keystore.jks …
```
> Issue 3398: Fix a bug that makes auth configuration item required for TLS-enabled standalone mode

- segmentstore/server/host/src/main/java/io/pravega/segmentstore/server/host/ServiceStarter.java
- segmentstore/server/host/src/main/java/io/pravega/segmentstore/server/host/handler/PravegaConnectionListener.java
- segmentstore/server/host/src/main/java/io/pravega/segmentstore/server/host/handler/PravegaRequestProcessor.java
- segmentstore/server/host/src/main/java/io/pravega/segmentstore/server/host/stat/AutoScaleMonitor.java
- segmentstore/server/host/src/main/java/io/pravega/segmentstore/server/host/stat/TableSegmentStatsRecorder.java
- segmentstore/server/host/src/main/java/io/pravega/segmentstore/server/host/stat/TableSegmentStatsRecorderImpl.java
- segmentstore/server/host/src/test/java/io/pravega/segmentstore/server/host/handler/PravegaRequestProcessorAuthFailedTest.java
- segmentstore/server/host/src/test/java/io/pravega/segmentstore/server/host/handler/PravegaRequestProcessorTest.java
- segmentstore/server/host/src/test/java/io/pravega/segmentstore/server/host/stat/TableSegmentStatsRecorderTest.java
- shared/metrics/src/main/java/io/pravega/shared/MetricsNames.java
- shared/metrics/src/main/java/io/pravega/shared/metrics/DynamicLogger.java
- test/integration/src/main/java/io/pravega/test/integration/demo/EndToEndAutoScaleDownTest.java
- test/integration/src/main/java/io/pravega/test/integration/demo/EndToEndAutoScaleUpTest.java
- test/integration/src/main/java/io/pravega/test/integration/demo/EndToEndAutoScaleUpWithTxnTest.java
- test/integration/src/test/java/io/pravega/test/integration/MetricsTest.java
- test/integration/src/test/java/io/pravega/test/integration/ReadFromDeletedStreamTest.java
- test/integration/src/test/java/io/pravega/test/integration/endtoendtest/EndToEndStatsTest.java
- Added metrics for all Table Segment Operations in PravegaRequestProcessor.
Fixes #3412.
- Tracking elapsed time for table segment creation and deletion
- Tracking number of entries added and elapsed time for updates/conditional updates.
- Tracking number of keys removed and elapsed time for removals/conditional removals.
- Tracking number of items returned and elapsed time for retrievals and iterators.
Unit tests must pass.
> Issue 3412: Table Segment Metrics

- controller/src/main/java/io/pravega/controller/store/stream/BucketStore.java
- controller/src/test/java/io/pravega/controller/server/bucket/BucketServiceTest.java
- controller/src/test/java/io/pravega/controller/server/bucket/ZkStoreRetentionTest.java
* Changes the logic in `BucketStore.getBucket` to handle negative hash codes.
Fixes #3422 
Bucket store is changed to absolute value of java.hashcode() method
> Issue 3422: BucketStore.getBucket must return a positive bucket number

- controller/src/main/java/io/pravega/controller/store/stream/ZKGarbageCollector.java
- controller/src/test/java/io/pravega/controller/store/stream/ZkGarbageCollectorTest.java
Zk Garbage Collector had a bug where it did not update the version of the batch if it was on old version
Fixes #3433 
Moves fetchVersion after catching the exception. 
Unit test updated
> Issue 3433 : Zk garbage collector bug in fetch version update

- docker/bookkeeper/Dockerfile
* Updates the URL to fetch the ZooKeeper release in the BookKeeper Dockerfile to use the Apache archive.
Fixes #3446 
Updates the ZooKeeper release path in the BookKeeper Dockerfile (`docker/bookkeeper/Dockerfile`)  to use the Apache archive. Note that this is change in the `r0.4` branch.
`./gradlew buildBookkeeperImage`
> Issue 3446: Update path to ZK release in BK Dockerfile

- controller/src/main/java/io/pravega/controller/server/rest/resources/StreamMetadataResourceImpl.java
An HTTP status code `500` indicating `Internal Server Error` was encountered inside the integration test `ControllerRestApiTest.restApiTests`, upon invocation of the REST endpoint for listing streams: `/v1/scopes/<scope-name>/streams`. 
The error was due to a bug in the REST API controller method `StreamMetadataResourceImpl.listStreams()`, where the `Authorization` request header was being retrieved outside the HTTP request scope. This was causing the following exception: 
```
2019-03-13 12:59:56,798 118249 [controllerpool-1] WARN  i.p.c.s.r.r.StreamMetadataResourceImpl - listStreams for k3tQfG7LPO failed with exception: {}
java.util.concurrent.CompletionException: java.lang.IllegalStateException: Not inside a …
```
> Issue 3457: Fix for the ControllerRestApiTest.restApiTests test failure

- controller/src/main/java/io/pravega/controller/util/Config.java
- controller/src/test/java/io/pravega/controller/util/ConfigTest.java
- controller/src/test/resources/controller.config.properties
Fixing `Config.java#createMetricsConfig` to not prefix metrics-related config values with "metrics" - that is already done by the `MetricsConfig` builder.
Fixes #3458.
Instead of replacing `controllermetrics.` with `metrics.` it simply removes `controller.metrics.` from the property name. The `MetricsConfig.builder()` will take care of the prefix.
New unit test to verify metrics config for controller.
> Issue 3458: Controller Metrics Config Fix

- test/system/src/test/java/io/pravega/test/system/MetadataScalabilityTest.java
MetadataScalability test uses futures.await to wait for all scale and truncation to complete.
This means even if there is a failure during scale or truncation, the test will declare it success.
Fixes #3471 
Uses `future.join` instead of `Futures.await`
System test should pass
> Issue 3471: MetadataScalability test does future.await which can incorrectly declare test successful 

- shared/protocol/src/main/java/io/pravega/shared/protocol/netty/CommandEncoder.java
Fix Segment comparison check in CommandEncoder to use String.equals()
Fixes #3465 
Fix Segment comparison check in CommandEncoder to use String.equals(). This check is used to decide to break out from an AppendBlock.
> Issue 3465: Fix Segment comparision check in CommandEncoder.

- segmentstore/server/src/main/java/io/pravega/segmentstore/server/containers/ContainerConfig.java
- Increased the max number of active segments to 25000 (from 10000).
- Increased the max number of segments to be flushed at once to 2500 (from 250).
- Decreased the min amount of time to keep segments in memory that do not have an operation pointing at them to 1 minute (from 5 minutes).
Fixes #3470.
- Changed configuration to accommodate more demanding system tests that cycle through a large number of segments at once.
Unit tests must pass.
System tests must pass (or not have any trace of `TooManyActiveSegmentsException`). Two such runs executed so far.
> Issue 3470: (SegmentStore) Increasing max number of active segments.

- segmentstore/server/src/main/java/io/pravega/segmentstore/server/tables/WriterTableProcessor.java
- segmentstore/server/src/main/java/io/pravega/segmentstore/server/writer/AckCalculator.java
- segmentstore/server/src/main/java/io/pravega/segmentstore/server/writer/SegmentAggregator.java
- segmentstore/server/src/main/java/io/pravega/segmentstore/server/writer/StorageWriter.java
- segmentstore/server/src/test/java/io/pravega/segmentstore/server/writer/AckCalculatorTests.java
- Fixed a bug in `StorageWriter` where it wasn't correctly calculating the ack sequence number for Table Segments.
Fixes #3464.
- For Table Segments, there are two types of processors: `SegmentAggregator` (that moves data to Tier2) and `WriterTableProcessor` (which indexes table updates)
- When determining the Sequence Number (SN) that's appropriate to truncate Tier 1 at, for each Table Segment, it needs to get the minimum of the SNs that have not yet been processed. 
- If a particular processor is fully caught up, it returns a special value `Operation.NO_SEQUENCE_NUMBER`, which also happens to be negative, hence smaller than any real SN.
- The current code was confused about this and if the Table Processor …
> Issue 3464: (SegmentStore) Properly calculating StorageWriter acks

- docker/pravega/scripts/init_kubernetes.sh
- Replace "null" return values with "" (empty string) to consider the value as invalid and keep the process in the retry loop.
- Refactor how the external service endpoint is obtained to reduce duplicated code.
Fix #3462 
Updates the `init_kubernetes.sh` file.
@jkhalack will be able to test the change in an environment where this error can be easily reproduced. 
---
Signed-off-by: Adrián Moreno <adrian@morenomartinez.com>
> Issue 3462: Fix Segmentstore's Kubernetes bootstrapping

- build.gradle
- test/system/src/main/java/io/pravega/test/system/framework/services/kubernetes/AbstractService.java
- test/system/src/main/java/io/pravega/test/system/framework/services/kubernetes/ZookeeperK8sService.java
- Add ability to configure Docker images for Pravega operator, Zookeeper operator, Pravega, and BookKeeper
- Fix Zookeeper and Pravega CRD by adding the new Status subresource ([ref](https://github.com/pravega/pravega-operator/blob/0.3.0/deploy/crd.yaml#L26) and [ref](https://github.com/pravega/zookeeper-operator/blob/0.2.1/deploy/crds/zookeeper_v1beta1_zookeepercluster_crd.yaml#L36))
- Fix "bookeeper" typo
Fix #3487 
Updates `build.gradle` and K8-based testing classes.
Start a K8-based system tests with custom images with the following arguments:
```
./gradlew startK8SystemTests -DimageVersion=0.5.0 -DpravegaImageName=pravega2 -DbookkeeperImageName=bookeeper2 …
```
> Issue 3487: Make Docker images configurable for K8 system tests

- test/system/src/main/java/io/pravega/test/system/framework/kubernetes/K8sClient.java
- test/system/src/main/java/io/pravega/test/system/framework/services/kubernetes/K8SequentialExecutor.java
Monitor Pravega pod for restart during every system test run. A pod restart during the test run will fail the corresponding test and log the reason for the pravega pod failure.
Fixes #3467 
The code now fetches the container Status of Pravega pods during every system test run. Incase the restart count of the Pravega pod is greater than what was observed during the start of the test then the  corresponding test is failed with the details.
Example output while simulating a pod restart  (used `docker kill <containerId>`  to simulate a Pravega pod failure)
```
io.pravega.test.system.PravegaTest > simpleTest FAILED
java.lang.AssertionError: Failing test due to Pravega pod restart. …
```
> Issue 3467: Monitor Pravega pods for restart during a system test run.

- controller/src/main/java/io/pravega/controller/eventProcessor/impl/SerializedRequestHandler.java
- controller/src/main/java/io/pravega/controller/server/eventProcessor/requesthandlers/AbstractRequestProcessor.java
- controller/src/test/java/io/pravega/controller/eventProcessor/impl/SerializedRequestHandlerTest.java
- controller/src/test/java/io/pravega/controller/server/eventProcessor/requesthandlers/RequestProcessorTest.java
Signed-off-by: Shivesh Ranjan shivesh.ranjan@gmail.com
Fixes regression caused by a recent change #3444.
This regression causes system test failure for ScopesAndStreamsManagementSystemTest
Fixes #3513
We added a `hasStarted` call in `withCompletion` method of `AbstractProcessor`. If `hasStarted` fails exceptionally, the result future is never completed, which causes the processing for a stream to be stuck.
Also, fixed a cascading theoretical issue where if any synchronous termination occurs rather than future with asynchronous failure then serializedRequestProcessor will fall into same issue as above.
Unit tests added for both processors
> Issue 3513: Regression: AbstractRequestProcessor should complete future in withCompletion on all paths

- test/system/src/test/java/io/pravega/test/system/ControllerFailoverTest.java
* Refactors the test case to validate that scaling happens after stopping and restarting the controller.
Fixes #3515 
Controller failover test is stale. It was written at a time when scale waited for transactions on old epochs which was no longer the case with rolling transactions.
The test creates a transaction and then initiates a scale and expects the scale to stall.
it checks once if the scale is complete or not. And then goes on to invoke a controller failover.
So there are two problems here -
1.     assumption that the scale would wait on transaction.
This had been passing merely by luck as when we check isScaleDone in the test, the scale is not …
> Issue 3515: ControllerFailover test case is incorrect and stale 

- segmentstore/server/src/main/java/io/pravega/segmentstore/server/CacheManager.java
- segmentstore/server/src/main/java/io/pravega/segmentstore/server/attributes/SegmentAttributeBTreeIndex.java
- segmentstore/server/src/main/java/io/pravega/segmentstore/server/containers/StreamSegmentContainer.java
- segmentstore/server/src/main/java/io/pravega/segmentstore/server/containers/StreamSegmentContainerMetadata.java
- segmentstore/server/src/main/java/io/pravega/segmentstore/server/containers/StreamSegmentMetadata.java
- segmentstore/server/src/main/java/io/pravega/segmentstore/server/logs/ContainerMetadataUpdateTransaction.java
- segmentstore/server/src/main/java/io/pravega/segmentstore/server/logs/DurableLog.java
- segmentstore/server/src/main/java/io/pravega/segmentstore/server/reading/StreamSegmentReadIndex.java
- Changed some log messages from INFO to DEBUG.
- Removed duplicated log messages or irrelevant messages (i.e., when it said it didn't do anything).
- Fixed a spurious bug in `CacheManager` that would have caused a stack trace to be logged but with no side effects.
Fixes #3484.
See Change Log Description above. These are non-functional changes.
These changes were collected while parsing many GBs of logs during recent system test debugging sessions and are meant to reduce noise and improve accuracy.
Non-functional changes. Build must pass.
> Issue 3484: (SegmentStore) Cleaning up some log messages

- client/src/test/java/io/pravega/client/segment/impl/SegmentOutputStreamTest.java
Improve verification for junit test `SegmentOutputStreamTest.testFailOnClose `. Ensure multiple SetupAppend requests are verified.
Fixes #3521 
Improve the verification of the test to validate that `WireCommands.SetupAppend` is sent twice over the wire.
The tests should continue to pass without transient failures.
> Issue 3521: Improve verification for SegmentOutputStreamTest.testFailOnClose 

- test/system/src/main/java/io/pravega/test/system/framework/kubernetes/K8sClient.java
Fix issue with `K8sClient.waitUntilPodCompletes` method which causes the future returned by it to never complete.
Fixes #3527 
Currently K8sClient retries incase of an `IOException` while tracking the status of the test pod for completion and download individual test logs. Now after all the retries have been exhausted the method `K8sClient.waitUntilPodCompletes` did not complete the future returned by it exceptionally causing the framework to stall.
All the tests should continue to pass. Verified the error scenarios by simulating the `UnknownHostException`
> Issue 3527: Ensure K8sClient.waitUntilPodCompletes method completes when all retries are exhausted.

- bindings/src/main/java/io/pravega/storage/filesystem/FileSystemStorage.java
Call FileChannel.force() at the end of write and concat.
Call FileChannel.force() at the end of write and concat.
This prevents data loss if the server crashes before data is written to the disk. Without this the data written is not guaranteed to be written to disk immediately, as data is transferred only to the buffer cache. 
Fixes #3489 
Call FileChannel.force() at the end of write and concat.
System tests should pass. There is should be no DataCorruptionException in the logs.
> Issue 3489: FileSystemStorage should write data synchronously to avoid data loss

- controller/src/main/java/io/pravega/controller/server/rpc/auth/PasswordAuthHandler.java
- controller/src/main/java/io/pravega/controller/server/rpc/grpc/v1/ControllerServiceImpl.java
- controller/src/test/java/io/pravega/controller/auth/AuthFileUtils.java
- controller/src/test/java/io/pravega/controller/rest/v1/StreamMetaDataAuthFocusedTests.java
- controller/src/test/java/io/pravega/controller/server/rpc/auth/ControllerGrpcAuthFocusedTest.java
Some of the operations of the Controller gRPC interface require a higher permission level `READ_UPDATE`, even though they are read operations and do not modify the state of the resource. And then, there is one operation that does modify the state, but only requires `READ` permission. 
Fixes #3411. 
The code fixes the permissions required for the operations listed below. We continue to use the same serial numbers (S.No.) as mentioned in the issue so that it is easier for readers to keep track of the changes. 
|S.No.| Action |	Resource String for Auth (in this PR)  | Required Permission - "OLD" | Required Permission - "NEW"| gRPC method (in ``ControllerServiceImpl``) | REST controller method (in …
> Issue 3411: Improve permissions required for Controller gRPC API 

- controller/src/main/java/io/pravega/controller/util/Config.java
- test/system/src/test/java/io/pravega/test/system/MetadataScalabilityLargeNumSegmentsTest.java
- test/system/src/test/java/io/pravega/test/system/MetadataScalabilityLargeScalesTest.java
- test/system/src/test/java/io/pravega/test/system/MetadataScalabilityTest.java
Split metadata scalability test into two separate tests so that they are individually not resource hungry and test intended scenarios. 
Fixes #3495
1. Metadata operations on stream with large number of segments like scale and truncate
2. Metadata operation on stream with large number of epochs (perform 1000s of scales) and then truncate. 
One additional change of config file having incorrect default zookeeper port is fixed. 
PS: running truncation on large stream has a huge memory footprint because we loop over all segments in streamcut and that actually reads epoch record from cache and deserializes it for each segment. so that happens 10k times and puts a huge memory pressure on controller. I have fixed …
> Issue 3495: Split metadata scalability test into two separate tests

- build.gradle
- gradle.properties
* Updates gradle.properties to remove properties related tests that are needed only when running system tests.
Fixes #3104 
There is no code change. This pull request is removing a bunch of gradle properties from the `gradle.properties` file, which are specific to running tests and can be passed via command line.
Although I have removed those properties altogether (and posted them to the wiki), it would also be fine to leave them without any parameters. I removed because I felt that they are cluttering the properties file unnecessarily.
There is no functional change, but it should build regularly.
> Issue 3104: Clean up gradle properties

- test/system/src/test/java/io/pravega/test/system/MetadataScalabilityTest.java
* Fixes the assertion to be greater than 0.
Fixes #3546 
Fixes an assertion in `MetadataScalabilityTest` to validate that the number of successor segments is greater than 0.
System test should pass.
> Issue 3546: Incorrect assertion in MetadataScalability tests

- client/src/main/java/io/pravega/client/tables/impl/KeyVersion.java
- client/src/main/java/io/pravega/client/tables/impl/KeyVersionImpl.java
- client/src/test/java/io/pravega/client/tables/impl/KeyVersionTest.java
- controller/src/main/java/io/pravega/controller/server/SegmentHelper.java
- controller/src/test/java/io/pravega/controller/server/SegmentHelperTest.java
- segmentstore/server/host/src/main/java/io/pravega/segmentstore/server/host/handler/PravegaRequestProcessor.java
- segmentstore/server/host/src/test/java/io/pravega/segmentstore/server/host/handler/PravegaRequestProcessorTest.java
* If the key does not exist during the readTable Operation then the resulting TableEntry should have a version corresponding to `io.pravega.segmentstore.contracts.tables.TableKey#NOT_EXISTS`
Fixes #3547 
- When a `readTable` operation is performed on the TableStore and if the key does not exist then the resulting TableEntry will have a zero length value and the key version should be TableKey#NOT_EXISTS.
-  Since`TableStore`  does not throw `KeyNotExistsException` for `TableStore#get` , the `SegmentHelper#readTableupdated ` has been updated.
> Issue 3547 : Ensure the key version is set to NOT_EXISTS if the key is not present.

- controller/src/main/java/io/pravega/controller/task/Stream/StreamMetadataTasks.java
- controller/src/test/java/io/pravega/controller/task/Stream/StreamMetadataTasksTest.java
Fixes the cause for sporadic System test failure for ScopesAndStreamManagementTest where we send update followed by seal and if update is complete but state is not updated, then seal fails and test fails. 
So we need to have stricter checks and only declare workflow complete once the state has been reset. 
Fixes #3532
For each of the externally submitted workflows, it now says workflow is complete only after the state is also reset. For check scale, `isUpdated` and `isTruncated` until the final step of workflow (state is reset) is performed we will continue to return in-progress. 
CheckScaleDone:
Original condition: 
```
if (activeEpoch.referenceEpoch == …
```
> Issue 3532: User called workflow completion checks should be tighter and include state as well

- docker/compose/docker-compose-extendeds3.yml
- docker/compose/docker-compose-nfs-mount.yml
- docker/compose/docker-compose-nfs.yml
- docker/compose/docker-compose.yml
In the Docker Compose configuration file, add ZK_URL as env. variable so that the Controller is linked to the appropriate Zookeeper container. 
Fixes #3554. 
Adds `ZK_URL` environment variable to the Controller service definition in the Docker Compose application configuration file `docker-compose.yml`.
Here are the steps to verify the fix:
1. Clone Pravega into a VM that has Docker and Docker Compose installed: `git clone https://github.com/pravega/pravega.git`
2. Execute command to navigate to the directory containing the docker-compose.yml file: `cd ./pravega/docker/compose``
3. Execute this command to set an environment variable: …
> Issue 3554: Add Zookeeper environment variable for Controller service definition in Docker Compose Configuration file

- controller/src/main/java/io/pravega/controller/task/Stream/StreamTransactionMetadataTasks.java
- controller/src/test/java/io/pravega/controller/fault/ControllerClusterListenerTest.java
- controller/src/test/java/io/pravega/controller/server/eventProcessor/ControllerEventProcessorTest.java
- controller/src/test/java/io/pravega/controller/server/eventProcessor/RequestHandlersTest.java
- controller/src/test/java/io/pravega/controller/server/rpc/auth/ControllerGrpcAuthFocusedTest.java
- controller/src/test/java/io/pravega/controller/server/v1/InMemoryControllerServiceImplTest.java
- controller/src/test/java/io/pravega/controller/server/v1/ZKControllerServiceImplTest.java
- controller/src/test/java/io/pravega/controller/task/Stream/StreamMetadataTasksTest.java
- controller/src/test/java/io/pravega/controller/task/Stream/StreamTransactionMetadataTasksTest.java
- controller/src/test/java/io/pravega/controller/timeout/TimeoutServiceTest.java
- test/integration/src/test/java/io/pravega/test/integration/ControllerBootstrapTest.java
Fixes couple of issues in stream transaction metadata tasks -
1. Removes unnecessary checkready that results in IllegalState Exception. Replaces it with writer future. 
2. Fixes issue in inconsistent usage of routing key for writing events into commit and abort streams. 
Fixes #3533 
Earlier streamTransaction metadata tasks class would wait until writers were initialized before doing any operation. The writers are created externally and passed to this class (We will fix that part of it later in a technical debt issue). For now, it doesnt have to do that as `createTxn` and `pingTxn` do not depend on internal stream writer's initialization. They can proceed before initialization happens. 
And commit and abort …
> Issue 3533: Fix StreamTransactionMetadataTasks bugs

- documentation/src/docs/basic-reader-and-writer.md
- documentation/src/docs/state-synchronizer.md
- documentation/src/docs/streamcuts.md
- documentation/src/docs/transactions.md
Version number changed from 0.4.0 to 0.5.0 ih the hyperlink (https://github.com/pravega/pravega-samples/tree/v0.5.0/pravega-client-examples/src/main/java/io/pravega/example/streamcuts) in the following documents.
documentation/basic-reader-and-writer.md
documentation/state-synchronizer.md
documentation/transactions.md
documentation/streamcuts.md
(_e.g._, Fixes #3551, Closes #3551)
> Issue 3551: Version number changed in the hyperlinks in the documents 

- controller/src/main/java/io/pravega/controller/metrics/ZookeeperConnectionMetrics.java
- controller/src/main/java/io/pravega/controller/metrics/ZookeeperMetrics.java
- controller/src/main/java/io/pravega/controller/server/ControllerServiceMain.java
- documentation/src/docs/metrics.md
- shared/metrics/src/main/java/io/pravega/shared/MetricsNames.java
- test/integration/src/test/java/io/pravega/test/integration/ControllerMetricsTest.java
Created new metric to keep track of Zookeeper session expirations in the Controller.
Fixes #3493.
A Zookeeper session expiration may be problematic if not properly handled, and in some cases, could be an indication of an issue in the ZK cluster. To be able of rapidly detecting this kind of situations in a Pravega deployment via a dashboard or alerts, we added a new metric called `controller.zookeeper.session_expiration` to account for the number of session expirations experienced by Controller instances. In turn, a session expiration in the Controller indicates that it is going to perform a graceful restart.
Added a new test to verify that the metric works. All test should be passing …
> Issue 3493: Metric for counting ZK session expirations in the Controller

- client/src/test/java/io/pravega/client/stream/mock/MockConnectionFactoryImpl.java
- controller/src/test/java/io/pravega/controller/rest/v1/PingTest.java
- controller/src/test/java/io/pravega/controller/rest/v1/StreamMetaDataAuthFocusedTests.java
- controller/src/test/java/io/pravega/controller/rest/v1/StreamMetaDataTests.java
- controller/src/test/java/io/pravega/controller/server/SegmentHelperTest.java
- controller/src/test/java/io/pravega/controller/server/v1/ControllerServiceTest.java
- controller/src/test/java/io/pravega/controller/server/v1/InMemoryControllerServiceImplTest.java
- controller/src/test/java/io/pravega/controller/server/v1/ZKControllerServiceImplTest.java
- controller/src/test/java/io/pravega/controller/task/Stream/IntermittentCnxnFailureTest.java
- controller/src/test/java/io/pravega/controller/task/TaskTest.java
- controller/src/test/java/io/pravega/controller/timeout/TimeoutServiceTest.java
Closing connection factory at the end of the tests. 
Fixes #3404 
Closes ConnectionFactory at the end of tests
No more "too many open files" while running unit tests locally.
> Issue 3404: Unit tests: Controller tests use large number of connections 

- docker/compose/Readme.md
- docker/compose/docker-compose-extendeds3.yml
- docker/compose/docker-compose-nfs-mount.yml
- docker/compose/docker-compose-nfs.yml
- docker/compose/docker-compose.yml
- documentation/src/docs/deployment/run-local.md
This PR does the following: 
1. Exposes the Controller REST API in Docker Compose deployments.
2. Fixes the Bookeeper Container failures.
3. Updates Docker Compose deployment documentation to provide detailed information about how to use it. 
Resolves #3563. 
It does 3 things:
* Adds REST_SERVER_PORT environment variable to the Controller service definition.
* Adds `restart: always` Docker Compose option for the bookies.
* Updates documentation in `docker/compose/Readme.md` and `documentation/src/docs/deployment/run-local.md` files.
See steps mentioned in [PR 3555](https://github.com/pravega/pravega/pull/3555).
> Issue 3563: Docker Compose Config changes and doc update

- client/src/main/java/io/pravega/client/stream/impl/PendingEvent.java
Signed-off-by: Kurilov, Andrey <andrey.kurilov@emc.com>
Allow max event size payload = 1MB
Fixes #3550
Pravega v0.4.0 brakes the compatibility. It was possible to write events with size up to 1MB (including this value). Since v0.4.0 the upper limit is 8 bytes less due to the additional headers introduced to distinguish byte streams and event streams. 
Change the max *serialized* event size to 1MB + 8 bytes
Try to write an event with payload size = 1MB
> Issue 3550: Correct maximum event size

- client/src/main/java/io/pravega/client/ClientConfig.java
- client/src/main/java/io/pravega/client/stream/ScalingPolicy.java
- controller/src/main/java/io/pravega/controller/server/ControllerServiceStarter.java
- controller/src/main/java/io/pravega/controller/server/eventProcessor/impl/ControllerEventProcessorConfigImpl.java
- controller/src/main/java/io/pravega/controller/server/impl/ControllerServiceConfigImpl.java
- controller/src/main/java/io/pravega/controller/server/rest/impl/RESTServerConfigImpl.java
- controller/src/main/java/io/pravega/controller/server/rpc/grpc/impl/GRPCServerConfigImpl.java
- controller/src/main/java/io/pravega/controller/store/client/impl/StoreClientConfigImpl.java
- controller/src/main/java/io/pravega/controller/store/client/impl/ZKClientConfigImpl.java
- controller/src/main/java/io/pravega/controller/timeout/TimeoutServiceConfig.java
- controller/src/test/java/io/pravega/controller/server/rest/impl/RESTServerConfigImplTests.java
- controller/src/test/java/io/pravega/controller/server/rpc/grpc/impl/GRPCServerConfigImplTest.java
- controller/src/test/java/io/pravega/controller/store/client/impl/ZKClientConfigImplTests.java
- segmentstore/server/host/src/main/java/io/pravega/segmentstore/server/host/ServiceStarter.java
- segmentstore/server/host/src/main/java/io/pravega/segmentstore/server/host/stat/AutoScalerConfig.java
- segmentstore/server/host/src/test/java/io/pravega/segmentstore/server/host/stat/AutoScalerConfigTest.java
- segmentstore/server/src/main/java/io/pravega/segmentstore/server/store/ServiceConfig.java
- segmentstore/server/src/test/java/io/pravega/segmentstore/server/store/ServiceConfigTests.java
The PR addresses two things:
* Removes a log entry about missing credentials in ClientConfig which was erroneous and misleading (as explained in issue #3576)
* Logs controller and segment store configuration (including security configuration). For sensitive security configuration, it only tells whether the configuration is specified. 
Resolves #3576 
* Removes a log entry in ClientConfig that was causing problem no. 1 mentioned in the issue. 
* Adds custom toString() implementations to Controller and Segment Store configuration classes where security information present; for rest of the config classes, adds Lombok toString annotation. 
While the scope of the PR was logging for security debugging, it didn't …
> Issue 3576: Improve logging to make it easier to debug security issues

- controller/src/test/java/io/pravega/controller/timeout/TimeoutServiceTest.java
Fixes an issue in the test where we do not tear down timeoutservice from previous test which can interfere with subsequent test run. 
Fixes #3579 
We are not closing the timeout service from previous test in tear down
Unit test should consistently pass
> Issue 3579: Sporadic unit test failure in TimeoutServiceTest 

- controller/src/test/java/io/pravega/controller/store/client/StoreClientFactoryTest.java
- controller/src/test/java/io/pravega/controller/store/stream/ZKStoreHelperTest.java
- controller/src/test/java/io/pravega/controller/store/stream/ZkOrderedStoreTest.java
Increased zk session timeout in couple of tests where the timeout was set to as low as 100ms
Fixes #3582 
increases zk session timeout in tests. 
Also added test timeout to zksessionExpiration test. 
Unit tests should consistently pass
> Issue 3582: Sporadic unit test failures because of low zk timeouts 

- controller/src/main/java/io/pravega/controller/task/Stream/StreamMetadataTasks.java
- controller/src/test/java/io/pravega/controller/task/Stream/RequestSweeperTest.java
- controller/src/test/java/io/pravega/controller/task/Stream/StreamMetadataTasksTest.java
RequestSweeperTest.testRequestSweeper failed consistently on java 11 because we were completing a `Void` future in the test with a string. 
Fixes #3609
The test was failing because the mock EventWriter was throwing an exception because we were completing a CompletableFuture<Void> future with a string value that compiler cannot catch because of type erasure in the mock. 
In the course, we also realized that this synchronously throw exception causes writeEvent to not complete the future. 
Test should consistently pass. 
Added new test to verify future completion on synchronous failures during write event in …
> Issue 3609: RequestSweeperTest.testRequestSweeper fails on java 11

- client/src/main/java/io/pravega/client/netty/impl/ClientConnectionImpl.java
- client/src/main/java/io/pravega/client/netty/impl/Connection.java
- client/src/main/java/io/pravega/client/netty/impl/ConnectionPool.java
- client/src/main/java/io/pravega/client/netty/impl/ConnectionPoolImpl.java
- client/src/main/java/io/pravega/client/netty/impl/FlowHandler.java
- client/src/test/java/io/pravega/client/netty/impl/ConnectionPoolingTest.java
- client/src/test/java/io/pravega/client/netty/impl/FlowHandlerTest.java
- shared/protocol/src/main/java/io/pravega/shared/protocol/netty/Append.java
Rename session references in the code to flow.
Fixes #3619 
No changes to functionality. All the remaining `session` references are renamed to `flow`
All the tests should continue to pass.
> Issue 3619: Rename session to flow.

- documentation/src/docs/deployment/manual-install.md
- documentation/src/docs/security/securing-distributed-mode-cluster.md
The PR adds a new step-by-step guide about securing a distributed mode cluster, and links it from an existing document. 
Addresses part 1 of issue #3599.
* A new file has been added: `pravega/documentation/src/docs/security/securing-distributed-mode-cluster.md`. 
* It is linked by the last section titled "Running a Pravega Cluster with Security enabled" in `pravega/documentation/src/docs/deployment/manual-install.md`.
**Additional notes/questions for reviewers**
* Admittedly, it'll need a few revisions before it is publishable. The idea was to start getting review comments sooner rather than later. 
* This document can be made more readable by breaking it down into multiple pages. Suggestions/comments? 
* …
> Issue 3599: Part1 - Add documentation about securing distributed mode cluster 

- common/src/main/java/io/pravega/common/io/StreamHelpers.java
- common/src/main/java/io/pravega/common/util/BitConverter.java
- common/src/test/java/io/pravega/common/io/StreamHelpersTests.java
- segmentstore/contracts/src/main/java/io/pravega/segmentstore/contracts/tables/TableAttributes.java
- segmentstore/server/src/main/java/io/pravega/segmentstore/server/reading/AsyncReadResultProcessor.java
- segmentstore/server/src/main/java/io/pravega/segmentstore/server/tables/AsyncTableEntryReader.java
- segmentstore/server/src/main/java/io/pravega/segmentstore/server/tables/BucketUpdate.java
- segmentstore/server/src/main/java/io/pravega/segmentstore/server/tables/ContainerKeyIndex.java
- segmentstore/server/src/main/java/io/pravega/segmentstore/server/tables/ContainerTableExtensionImpl.java
- segmentstore/server/src/main/java/io/pravega/segmentstore/server/tables/EntrySerializer.java
- segmentstore/server/src/main/java/io/pravega/segmentstore/server/tables/IndexReader.java
- segmentstore/server/src/main/java/io/pravega/segmentstore/server/tables/IndexWriter.java
- segmentstore/server/src/main/java/io/pravega/segmentstore/server/tables/KeyUpdateCollection.java
- segmentstore/server/src/main/java/io/pravega/segmentstore/server/tables/TableBucketReader.java
- segmentstore/server/src/main/java/io/pravega/segmentstore/server/tables/TableCompactor.java
- segmentstore/server/src/main/java/io/pravega/segmentstore/server/tables/TableWriterConnector.java
- segmentstore/server/src/main/java/io/pravega/segmentstore/server/tables/WriterTableProcessor.java
- segmentstore/server/src/test/java/io/pravega/segmentstore/server/reading/AsyncReadResultProcessorTests.java
- segmentstore/server/src/test/java/io/pravega/segmentstore/server/tables/AsyncTableEntryReaderTests.java
- segmentstore/server/src/test/java/io/pravega/segmentstore/server/tables/BucketUpdateTests.java
- segmentstore/server/src/test/java/io/pravega/segmentstore/server/tables/ContainerKeyIndexTests.java
- segmentstore/server/src/test/java/io/pravega/segmentstore/server/tables/ContainerTableExtensionImplTests.java
- segmentstore/server/src/test/java/io/pravega/segmentstore/server/tables/EntrySerializerTests.java
- segmentstore/server/src/test/java/io/pravega/segmentstore/server/tables/IndexReaderWriterTests.java
- segmentstore/server/src/test/java/io/pravega/segmentstore/server/tables/KeyUpdateCollectionTests.java
- segmentstore/server/src/test/java/io/pravega/segmentstore/server/tables/ReadResultMock.java
- segmentstore/server/src/test/java/io/pravega/segmentstore/server/tables/SegmentMock.java
- segmentstore/server/src/test/java/io/pravega/segmentstore/server/tables/TableBucketReaderTests.java
- segmentstore/server/src/test/java/io/pravega/segmentstore/server/tables/TableCompactorTests.java
- segmentstore/server/src/test/java/io/pravega/segmentstore/server/tables/WriterTableProcessorTests.java
- Implemented Table Segment Compaction
- Defined two more Table Segment Attributes that aid in compaction: one for tracking utilization and one for tracking compaction progress.
- Compaction is not enabled for any segment yet (all have MIN_UTILIZATION set to 0, which means no compaction). This will change in a future PR.
Fixes #3274.
- Defined new `TableAttributes`
- `COMPACTION_OFFSET`: keeps track of the last offset that was processed for compaction. Subsequent compaction runs will resume from here. This offset is always at a `TableEntry` boundary.
- `MIN_UTILIZATION`: this is a user-set threshold that defines when compaction should be triggered. Utilization is defined as the ratio of `ENTRY_COUNT` to …
> Issue 3274: (SegmentStore) Table Segment Compaction

- test/integration/src/test/java/io/pravega/test/integration/ControllerMetricsTest.java
* Changes assertions in `ControllerMetricsTest` from `assertTrue` to `assertEquals`. 
Fixes #3626 
This PR only touches test code. We change in `ControllerMetricsTest` some of the assertions to use `assertEquals` rather than `assertTrue` so that in the case of test failure we observe the values compared.
`./gradlew :test:integration:test -Dtest.single=ControllerMetricsTest`
> Issue 3626: Change assertions in ControllerMetricsTest

- test/system/src/main/java/io/pravega/test/system/framework/services/docker/BookkeeperDockerService.java
- test/system/src/main/java/io/pravega/test/system/framework/services/docker/PravegaSegmentStoreDockerService.java
1. Changed bookkeeper.bkAckQuorumSize to `3` in segmentstore
2. Removed index-volumes mount from bookkeeper and explicitly set `BK_useHostNameAsBookieID` to `false`
Fixes #3630
Default bookkeeper.bkAckQuorumSize is changed from 3 to 2 in `r0.5`. So explicitly  setting to `3` in system tests.
Bookies were not scaling back as the index-volumes are not persisted and there is inconsistency between ZK metadata. 
> Issue 3630: Bookiefailovertest failure in docker swarm

- controller/src/test/java/io/pravega/controller/task/Stream/StreamMetadataTasksTest.java
* Adds a call to join to existing test futures to guarantee that the future completes before the assertion. 
Fixes #3635 
Fixes the test issue where we call a future but dont wait for its completion and check the status of what the future is supposed to do. 
> Issue 3635: Sporadic test failure PravegaTablesStreamMetadataTasksTest > checkTruncateCompleteTest 

- gradle.properties
* Updates Pravega version in master to 0.6.0-SNAPSHOT
Fixes #3641 
There is no code change. It updates the Pravega version in `gradle.properties`.
`./gradlew install` should produce the correct version.
> Issue 3641: Update Pravega version in master

- config/config.properties
- segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/rocksdb/RocksDBCache.java
- segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/rocksdb/RocksDBConfig.java
Allow RocksDB direct reads to be configurable.
Fixes #3645.
Allowing direct reads in RocksDB may be beneficial in terms of performance. However, not all the environments support direct IO. For this reason, we added a new configuration (`config.properties`) parameter in RocksDB (`rocksdb.directReads`) to be able of enabling this option. For safety reasons, we set direct reads disable by default. Advanced users that look for better performance may enable this option once they are sure that their platform support direct IO.
No code changes, all tests should be passing as before with no direct reads (as they were before with direct reads being enabled).
Signed-off-by: Raúl Gracia …
> Issue 3645: Allow direct reads in RocksDB to be configurable

- shared/protocol/src/main/java/io/pravega/shared/protocol/netty/CommandEncoder.java
- shared/protocol/src/main/java/io/pravega/shared/protocol/netty/WireCommands.java
- shared/protocol/src/test/java/io/pravega/shared/protocol/netty/WireCommandsTest.java
* Remove unneeded requestId on AppendBlock.
Fixes #3624
In #3562 a requestId was added to each wire command so that replies could be associated with the appropriate command. This was not strictly necessary (but should have been harmless) for AppendBlock as it gets combined with AppendBlockEnd before being processed and is never replied to individually. The problem was that the logic which was intended to check for the presence of the new field would incorrectly always detect it's presence. This meant that using an older client with a newer server would fail as soon as an append was attempted. This change removes the unneeded field altogether. This returns …
> Issue #3624: Fix backward compatibility issue with WireCommands.

- test/system/src/main/java/io/pravega/test/system/framework/services/kubernetes/AbstractService.java
Sets hdfs.replaceDataNodesOnFailure = false for SegmentStore in  .../kubernetes/AbstractService.java
Kubernetes system tests run against a single HDFS pod. This flag prevents datanode pipeline unavailability in case of any network glitch/delays by setting dfs.client.block.write.replace-datanode-on-failure.policy = NEVER in HDFS client
Fixes #3659 
set hdfs.replaceDataNodesOnFailure = false for SegmentStore in  .../kubernetes/AbstractService.java
Run system tests with HDFS tier-2. 
There should not be any of following exceptions in segment store logs.
> java.io.IOException: Failed to replace a bad datanode on the existing pipeline due …
> Issue 3659: Set hdfs.replaceDataNodesOnFailure = false in K8s system tests

- segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/rolling/RollingStorage.java
- segmentstore/storage/src/test/java/io/pravega/segmentstore/storage/rolling/RollingStorageTests.java
- Fixed a bug in `RollingStorage` where a write handle would not auto-refresh if used for reading offsets that are beyond its last cached offset.
Fixes #3665.
- The `StorageWriter`'s `SegmentAggregator` reuses a Write Handle for reconciliation. However, following a failed write that actually committed, the `SegmentAggregator` will attempt to read the extra data from Tier 2 Storage. But due to the write not registering a succeeded, the `SegmentHandle` does not know that the underlying segment has the extra data written and will reject the read because it's beyond the last known offset.
- Fixed `RollingStorage` to auto-refresh the Write Handle if receiving a read request beyond the last offset.
- This was …
> Issue 3665: (SegmentStore) Auto-refresh Storage Write Handle when reading beyond last known offset

- client/src/main/java/io/pravega/client/ClientConfig.java
- client/src/main/java/io/pravega/client/netty/impl/Connection.java
- client/src/main/java/io/pravega/client/netty/impl/ConnectionPoolImpl.java
- client/src/main/java/io/pravega/client/netty/impl/SessionHandler.java
- client/src/test/java/io/pravega/client/netty/impl/ConnectionPoolingTest.java
- test/integration/src/test/java/io/pravega/test/integration/endtoendtest/EndToEndChannelLeakTest.java
* Add first session to connection before the connection is established so the pool will know it is used.
Fixes #3632 
Previously the connection pool was adding the session to the connection once the connection was established. This meant that a concurrent call to open a connection could see the connection as unused if the session had not been added yet. This caused two sessions to be added to the same newly created connection, which made ConnectionLeakTest flaky because the same number of connections were not always used. This change splits out the connection future from the session handler on the connection object. This way the session can be added to the …
> Issue #3632: Add session to connection before it is established

- config/config.properties
Issue 3659: Update the config.properties file to document hdfs.replaceDataNodesOnFailure usage
Update the config.properties file to document hdfs.replaceDataNodesOnFailure usage
Related #3659 , #3400, #2967 
The configuration hdfs.replaceDataNodesOnFailure is not documented/exposed in the config.properties though HDFSStorageConfig makes use of this property.Need to fix the configuration file to include this property. 
> Issue 3659: Update the config.properties file to document hdfs.replaceDataNodesOnFailure usage

- build.gradle
- Ensure grgit plugin is invoked only if git repository is present.
Fixes #3649 
`grgit` plugin is used to fetch information about the git repository like the commit id and commit count.
Invoking `./gradlew distribution` on `branch-0.5` (`https://github.com/pravega/pravega/archive/branch-0.5.tar.gz`) release causes the grgit plugin to fail since it is not a git repository. This change ensures that commit id is fetched only in case grgit plugin is able to fetch details of the repository.
No changes to functionality. Verified that `./gradlew distribution` works when invoked on `branch-0.5` located @ `https://github.com/pravega/pravega/archive/branch-0.5.tar.gz`
> Issue 3649: Invoke grgit plugin only if git repository is present.

- controller/src/main/java/io/pravega/controller/store/host/ZKHostStore.java
- controller/src/test/java/io/pravega/controller/fault/SegmentContainerMonitorTest.java
- controller/src/test/java/io/pravega/controller/store/stream/HostStoreTest.java
Fixes the ZkHost store to initialize the segment container to host map field with initial value read in NodeCache. 
Fixes #3673
ZkHostStore was recently changed to use NodeCache. And we build initial node cache map but do not set the local field segmentcontainer-Host map with initialized value. This means the field is only updated if there is a change in segment store nodes. 
This means, in longevity, if a controller restarts, then it doesnt update its container-host map and has an empty map and any queries received by it are failed because it cannot find a host to container mapping. 
Unit test updated to verify that initial …
> Issue 3673: New controller instance is not updating segment container map unless there is an update

- segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/rolling/RollingStorage.java
- segmentstore/storage/src/test/java/io/pravega/segmentstore/storage/rolling/RollingStorageTests.java
- Cherry-picking PR #3668 into R0.5
- Fixed a bug in RollingStorage where a write handle would not auto-refresh if used for reading offsets that are beyond its last cached offset.
Backport PR #3668, Issue #3665.
Fixes #3695.
See #3668.
See #3668.
> Issue 3665: R0.5 - Cherry pick #3668 (SegmentStore-RollingStorage auto-refresh handle)

- client/src/main/java/io/pravega/client/ClientConfig.java
- client/src/main/java/io/pravega/client/netty/impl/Connection.java
- client/src/main/java/io/pravega/client/netty/impl/ConnectionPoolImpl.java
- client/src/main/java/io/pravega/client/netty/impl/FlowHandler.java
- client/src/test/java/io/pravega/client/netty/impl/ConnectionPoolingTest.java
- test/integration/src/test/java/io/pravega/test/integration/endtoendtest/EndToEndChannelLeakTest.java
- Cherry picking PR #3639 into R0.5
* Adds first session to connection before the connection is established so the pool will know it is used.
Backport PR #3639 , Issue #3632 
Fixes #3663
See #3639 
See #3639
> Issue 3663: R0.5 - Cherry pick #3639(Add session to connection before it is established)

- controller/src/test/java/io/pravega/controller/store/stream/HostStoreTest.java
Fixes sporadic failure in zkHostStoreTests.
Fixes #3708.
PR #3682 introduced a call to `updateMap()` in `ZKHostStore:tryInit()` that internally triggers the listener used for testing purposes. Such a listener is used to ensure that an update to the host store is completed before performing any assertion/check in a test case; an example of this use case is `zkHostStoreTests`.
However, the fact that the new `updateMap()` call introduced PR #3682 triggers the listener in `ZKHostStore`, breaks the logic of `zkHostStoreTests`. The reason is that `zkHostStoreTests` uses a `CompletableFuture` that is assumed to be completed when the listener is triggered after executing …
> Issue 3708: Sporadic failure of HostStoreTest.zkHostStoreTests

- segmentstore/server/src/main/java/io/pravega/segmentstore/server/tables/ContainerKeyCache.java
- segmentstore/server/src/main/java/io/pravega/segmentstore/server/tables/ContainerKeyIndex.java
- segmentstore/server/src/main/java/io/pravega/segmentstore/server/tables/ContainerTableExtensionImpl.java
- segmentstore/server/src/main/java/io/pravega/segmentstore/server/tables/SegmentKeyCache.java
- segmentstore/server/src/test/java/io/pravega/segmentstore/server/tables/ContainerKeyCacheTests.java
- segmentstore/server/src/test/java/io/pravega/segmentstore/server/tables/ContainerKeyIndexTests.java
- segmentstore/server/src/test/java/io/pravega/segmentstore/server/tables/ContainerTableExtensionImplTests.java
Fixed a bug in `ContainerKeyIndex` where it would incorrectly determine that a Table Segment is empty when it actually is not.
Fixes #3710.
Cause:
- The cause for this was an incorrect way of calculating the number of Table Entries in a Segment, given both indexed and non-indexed entries.
- The previous calculation methodology was incorrectly assuming that all Table Key removals recorded in the cache are for keys that actually exist. 
- While this may be true for conditional removals, unconditional removals perform no precondition checks and simply record the action (unconditionally removing an inexistent key is a valid operation)
- All removals were recorded in the `SegmentKeyCache` and when asked to …
> Issue 3710: (SegmentStore) Delete Segment if Empty Bug Fix

- client/src/main/java/io/pravega/client/stream/Transaction.java
- client/src/main/java/io/pravega/client/stream/impl/Controller.java
- client/src/main/java/io/pravega/client/stream/impl/ControllerImpl.java
- client/src/main/java/io/pravega/client/stream/impl/ModelHelper.java
- client/src/test/java/io/pravega/client/stream/impl/ControllerImplTest.java
- client/src/test/java/io/pravega/client/stream/impl/PingerTest.java
- client/src/test/java/io/pravega/client/stream/mock/MockController.java
- controller/src/main/java/io/pravega/controller/server/eventProcessor/LocalController.java
- controller/src/main/java/io/pravega/controller/task/Stream/StreamTransactionMetadataTasks.java
- controller/src/test/java/io/pravega/controller/task/Stream/StreamTransactionMetadataTasksTest.java
- shared/controller-api/src/main/proto/Controller.proto
Include more information in `Controller.PingTxnStatus` to indicate if the transaction is closed. 
Fixes #2830
`io.pravega.client.stream.impl.ControllerImpl#pingTransaction` api now indicates if the transaction is closed (if the state of the transaction is `COMMITTING` , `COMMITTED`, `ABORTED` or `ABORTING`). This change will enable Pravega to stop pinging closed transactions described in issue issue #3463 .
(In the process of adding newer tests.)
> Issue 2830: PingTxnStatus now informs if the Transaction is closed

- common/src/test/java/io/pravega/common/util/RetryTests.java
- controller/src/test/java/io/pravega/controller/server/ControllerServiceMainTest.java
- controller/src/test/java/io/pravega/controller/server/ControllerServiceStarterTest.java
- controller/src/test/java/io/pravega/controller/server/PravegaTablesControllerServiceMainTest.java
- controller/src/test/java/io/pravega/controller/server/PravegaTablesControllerServiceStarterTest.java
- controller/src/test/java/io/pravega/controller/server/ZKControllerServiceMainTest.java
- controller/src/test/java/io/pravega/controller/server/ZKControllerServiceStarterTest.java
- controller/src/test/java/io/pravega/controller/store/stream/HostStoreTest.java
- segmentstore/server/src/test/java/io/pravega/segmentstore/server/reading/ContainerReadIndexTests.java
- segmentstore/server/src/test/java/io/pravega/segmentstore/server/tables/TableBucketReaderTests.java
- test/integration/src/test/java/io/pravega/test/integration/ControllerBootstrapTest.java
- test/integration/src/test/java/io/pravega/test/integration/ReadTest.java
- test/system/src/test/java/io/pravega/test/system/MetadataScalabilityLargeNumSegmentsTest.java
- test/system/src/test/java/io/pravega/test/system/MetadataScalabilityLargeScalesTest.java
- test/system/src/test/java/io/pravega/test/system/PravegaTest.java
- test/system/src/test/java/io/pravega/test/system/ReaderCheckpointTest.java
* Prevent tests from suppressing exception stack traces 
Fixes #3702
Removes unneeded try catch code from tests. No functional changes.
> Issue 3702: Prevent suppression of stack traces in tests

- client/src/main/java/io/pravega/client/segment/impl/AsyncSegmentInputStreamImpl.java
- client/src/test/java/io/pravega/client/segment/impl/AsyncSegmentInputStreamTest.java
- Ensure AsyncSegmentInputStreamImpl closes the connection incase a `ConnectionFailedException` is observed during `io.pravega.client.netty.impl.ClientConnection#sendAsync()`
Related to issue #3638
AsycnSegmentInputStreamImpl invokes `ClientConnection.sendAsync(...)` to send commands like `WireCommand.ReadSegment`. This method can throw a `ConnectionFailedException` incase the underlying Netty Channel was set to null due to `channelUnregistered()` callback by netty. This can cause the AsyncSegmentInputStream to retry until the replyProcessor.connectionDropped() is invoked by `FlowHandler`.
> Issue 3638: Ensure the AsyncSegmentInputStreamImpl handles ConnectionFailedException during sendAsync.

- segmentstore/server/host/src/test/java/io/pravega/segmentstore/server/host/HDFSIntegrationTest.java
- segmentstore/server/src/main/java/io/pravega/segmentstore/server/writer/SegmentAggregator.java
- segmentstore/server/src/test/java/io/pravega/segmentstore/server/store/StreamSegmentStoreTestBase.java
- segmentstore/server/src/test/java/io/pravega/segmentstore/server/writer/SegmentAggregatorTests.java
Fixed a bug in SegmentAggregator where a MergeTransactionOperation followed by an UpdateAttributesOperation would cause the SegmentAggregator to request invalid data from the ReadIndex and prevent progress from being made.
Fixes #3726.
- The SegmentAggregator aggregates multiple operations of similar types together. This includes `UpdateAttributesOperation` and `SegmentAppendOperation`, but it does not include `MergeSegmentOperation`s.
- The first operation that is included will determine the starting offset of the resulting `AggregatedOperation`. For `SegmentAppendOperations` this works well, since `SegmentAppendOperation`s have well defined offsets. However, `UpdateAttributeOperations` do not, hence the …
> Issue 3726: (SegmentStore) StorageWriter can't handle updating attributes after a segment merge

- client/src/main/java/io/pravega/client/netty/impl/ClientConnectionImpl.java
- client/src/main/java/io/pravega/client/netty/impl/FlowHandler.java
- client/src/main/java/io/pravega/client/segment/impl/AsyncSegmentInputStreamImpl.java
- client/src/main/java/io/pravega/client/state/impl/RevisionedStreamClientImpl.java
- client/src/main/java/io/pravega/client/state/impl/StateSynchronizerImpl.java
- client/src/test/java/io/pravega/client/netty/impl/FlowHandlerTest.java
Defensive exception handling for netty callbacks and `io.pravega.shared.protocol.netty.ReplyProcessor` invocations.
Fixes #3596
This code does not modify/change any functionality, it enables defensive exception handling for netty related operations.
This enhancement request originally was to ensure `Throwable` is  caught for netty related operations. But on closer inspection of the code observed that catching `Throwable` is undesirable and catching `java.lang.Exception` is infact enough.
- `channel.writeAndFlush(..)` : This is now wrapped within  `try {} catch {}` block to handle any Exceptions.
- Reply processor invocation is now wrapped under a `try {} catch {}` block to ensure any exceptions (if thrown) …
> Issue 3596:  Improved Exception handling for ReplyProcessor.

- client/src/main/java/io/pravega/client/segment/impl/SegmentOutputStream.java
- client/src/main/java/io/pravega/client/segment/impl/SegmentOutputStreamImpl.java
- client/src/main/java/io/pravega/client/stream/EventWriterConfig.java
- client/src/main/java/io/pravega/client/stream/impl/EventStreamWriterImpl.java
- client/src/main/java/io/pravega/client/stream/impl/SegmentSelector.java
- client/src/test/java/io/pravega/client/stream/impl/EventStreamWriterTest.java
- client/src/test/java/io/pravega/client/stream/mock/MockSegmentIoStreams.java
- segmentstore/contracts/src/main/java/io/pravega/segmentstore/contracts/MergeStreamSegmentResult.java
- segmentstore/contracts/src/main/java/io/pravega/segmentstore/contracts/StreamSegmentStore.java
- segmentstore/server/host/src/main/java/io/pravega/segmentstore/server/host/handler/AppendProcessor.java
- segmentstore/server/host/src/main/java/io/pravega/segmentstore/server/host/handler/PravegaRequestProcessor.java
- segmentstore/server/host/src/test/java/io/pravega/segmentstore/server/host/handler/AppendProcessorTest.java
- segmentstore/server/host/src/test/java/io/pravega/segmentstore/server/host/handler/PravegaRequestProcessorTest.java
- segmentstore/server/src/main/java/io/pravega/segmentstore/server/containers/ReadOnlySegmentContainer.java
- segmentstore/server/src/main/java/io/pravega/segmentstore/server/containers/StreamSegmentContainer.java
- segmentstore/server/src/main/java/io/pravega/segmentstore/server/logs/operations/StorageOperation.java
- segmentstore/server/src/main/java/io/pravega/segmentstore/server/mocks/SynchronousStreamSegmentStore.java
- segmentstore/server/src/main/java/io/pravega/segmentstore/server/store/StreamSegmentService.java
- segmentstore/server/src/test/java/io/pravega/segmentstore/server/containers/StreamSegmentContainerTests.java
- segmentstore/server/src/test/java/io/pravega/segmentstore/server/store/StreamSegmentContainerRegistryTests.java
- segmentstore/server/src/test/java/io/pravega/segmentstore/server/store/StreamSegmentStoreTestBase.java
- segmentstore/server/src/test/java/io/pravega/segmentstore/server/tables/ContainerTableExtensionImplTests.java
- shared/protocol/src/main/java/io/pravega/shared/protocol/netty/WireCommands.java
- shared/protocol/src/test/java/io/pravega/shared/protocol/netty/WireCommandsTest.java
- test/integration/src/main/java/io/pravega/test/integration/selftest/adapters/InProcessMockClientAdapter.java
- test/integration/src/main/java/io/pravega/test/integration/selftest/adapters/SegmentStoreAdapter.java
- test/integration/src/test/java/io/pravega/test/integration/endtoendtest/EndToEndTxnWithTest.java
**NOTE: This is merging to the Watermarking branch not master.**
* Add server side support and new wirecommands needed for watermarking
* Add plumbing on the client to get the offsets where they are needed.
Sub item of #3344
Changes appends and segment merges to return the length of the segment after the data has been appended. This will be collected by the writer and passed to the controller when time is noted.
Not yet ready for end-to-end testing as client impl is not complete.
> Issue #3344: (Watermarking) Add server side support for watermarking

- segmentstore/server/host/src/main/java/io/pravega/segmentstore/server/host/ZKSegmentContainerMonitor.java
-  Changed `ZKSegmentContainerMonitor.checkAssignment` to only log if there is a pending task in progress or a Segment Container change desired. If none, then log every 10 minutes.
Fixes #3762.
This reduces the litter in the logs. It previously logged an entry every 10 seconds and filled up entire logs with exactly the same message.
Build and tests must pass.
> Issue 3762: Reduced frequency of logging in ZKSegmentContainerMonitor 

- test/integration/src/test/java/io/pravega/test/integration/endtoendtest/EndToEndStatsTest.java
Replaced the non-thread safe map inside the TestStatsRecorder with solid SimpleMeterRegistry to fix the sporadic multi-threading failure.
Fixes #3715 
1. Inside `EndToEndStatsTest.TestStatsRecorder`, replaces the non thread safe map with Micrometer `SimpleMeterRegistry`.
2. Use Micrometer API to retrieve counters, instead of the unsafe map get operation.
3. Added `SEGMENT_WRITE_BYTES` tests, in addition to the existing `SEGMENT_WRITE_EVENTS` tests.
4. Added a set to hold strong references to metric objects, to further consolidate the code for the most intensive runtime environment.
Integration test should pass, no matter how many times it repeats.
(The old implementation usually fails …
> Issue 3715: replaced the non thread safe map with SimpleMeterRegistry

- segmentstore/server/host/src/main/java/io/pravega/segmentstore/server/host/handler/AppendProcessor.java
- segmentstore/server/host/src/test/java/io/pravega/segmentstore/server/host/handler/AppendProcessorTest.java
- Correct the log level for `CancellationException ` inside AppendProcessor
Fixes #3736 
All outstanding operations are cancelled when the Operation Processor shuts down. Ensure the AppendProcessor logs this at INFO level. The PravegaRequestProcessor is already logging `CancellationException` at INFO level.
> Issue 3736: Reduce log severity for CancellationException inside AppendProcessor.

- test/system/kubernetes/setupTestPod.sh
- Increase timeout for test pod (`pod/task-pv-pod`) creation from 30 seconds (default value) to 1 minute
Fix #3768 
Applies the changes to the `test/system/kubernetes/setupTestPod.sh` script.
System test should pass consistently. 
---
Signed-off-by: Adrián Moreno <adrian@morenomartinez.com>
> Issue 3768: Increase timeout for pod/task-pv-pod creation

- segmentstore/server/host/src/main/java/io/pravega/segmentstore/server/host/handler/AppendProcessor.java
Signed-off-by: Vijay Srinivasaraghavan <vijayaraghavan.srinivasaraghavan@emc.com>
* increased the throttling limit by a factor of ~~10~~ 5 to ensure the clients are not blocked 
To address the issue https://github.com/pravega/pravega/issues/3479
Increased the throttling configuration setting in `AppendProcessor`  
test by writing more/frequent data with/without the fix and observe the write throughput difference
> Issue 3479: Increase client throttling limit

- segmentstore/server/src/test/java/io/pravega/segmentstore/server/containers/StreamSegmentContainerTests.java
- Fixed a unit test to recognize more types of exceptions indicative of a Segment Container shutting down.
Fixes #3538.
- Updated the test to recognize `ObjectClosedException`.
Uni test must pass.
> Issue 3538: Fixing unit test StreamSegmentContainerTests.testWriteFenceOut

- common/src/main/java/io/pravega/common/io/serialization/RevisionDataInput.java
- common/src/main/java/io/pravega/common/io/serialization/RevisionDataInputStream.java
- common/src/main/java/io/pravega/common/io/serialization/RevisionDataOutput.java
- common/src/main/java/io/pravega/common/io/serialization/RevisionDataOutputStream.java
- common/src/test/java/io/pravega/common/io/serialization/RevisionDataStreamCommonTests.java
- Added `RevisionDataOutput.writeCompactSignedLong()` and `RevisionDataInput.readCompactSignedLong()`.
- Improved Javadoc in `RevisionDataOutput` and `RevisionDataInput` by adding Javadoc links and fixing various references.
Fixes #3781.
- `writeCompactLong`/`readCompactLong` only supported non-negative numbers up to 2^62-1. This change adds support for negative numbers as well.
- Negative numbers require an extra bit to store the sign, as such only numbers within the range [2^61, 2^61) can be encoded (3 bits are reserved for sign and length).
New unit tests added.
> Issue 3781: VersionedSerializer support for Compacted Signed Longs

- client/src/main/java/io/pravega/client/stream/impl/ControllerImpl.java
- client/src/test/java/io/pravega/client/stream/impl/ControllerImplTest.java
- controller/src/main/java/io/pravega/controller/server/rpc/grpc/v1/ControllerServiceImpl.java
- controller/src/test/java/io/pravega/controller/server/v1/ControllerServiceImplTest.java
- shared/controller-api/src/main/proto/Controller.proto
* Changes call from getSegmentsImmediatlyFollowing to getSegmentsImmediatelyFollowing to fix a typo.
* Retains the old call for compatibility, to be removed in the PR for #3760.
Fixes #3758 
Changes the call name to fix a typo, but keeps the old call for compatibility. The changes affect the following files:
```
client/src/main/java/io/pravega/client/stream/impl/ControllerImpl.java
client/src/test/java/io/pravega/client/stream/impl/ControllerImplTest.java
controller/src/main/java/io/pravega/controller/server/rpc/grpc/v1/ControllerServiceImpl.java
controller/src/test/java/io/pravega/controller/server/v1/ControllerServiceImplTest.java …
```
> Issue 3758: Fix typo in controller API call name

- controller/src/main/java/io/pravega/controller/server/rpc/grpc/v1/ControllerServiceImpl.java
- controller/src/test/java/io/pravega/controller/server/v1/ControllerServiceImplTest.java
Added missing implementation for deprecated Controller call "getSegmentsImmediatlyFollowing".
Fixes #3793.
In PR #3759 we deprecated the method `getSegmentsImmediatlyFollowing` in favor of `getSegmentsImmediatelyFollowing`. However, that PR missed to add the deprecated method implementation in `ControllerServiceImpl`. This problem was not detected because a bug in the test code for the deprecated method, which was performing assertions over variables resulting from the new method name (in fact, the execution of `getSegmentsImmediatlyFollowing` was retrieving a response specifying that the method was unimplemented).
This PR fixes both `ControllerServiceImpl` and the associated test regarding the deprecated …
> Issue 3793: Fixed compatibility for deprecated Controller call (getSegmentsImmediatlyFollowing)

- controller/src/main/java/io/pravega/controller/server/rpc/grpc/v1/ControllerServiceImpl.java
- controller/src/test/java/io/pravega/controller/server/v1/ControllerServiceImplTest.java
* Adds missing implementation for deprecated Controller call "getSegmentsImmediatlyFollowing".
It fixes both `ControllerServiceImpl` and the associated test regarding the deprecated
`getSegmentsImmediatlyFollowing` method.
Fixes #3790 
In PR #3759 we deprecated the method `getSegmentsImmediatlyFollowing` in favor of `getSegmentsImmediatelyFollowing`. However, that PR missed to add the deprecated method implementation in `ControllerServiceImpl`. This problem was not detected because a bug in the test code for the deprecated method, which was performing assertions over variables resulting from the …
> Issue 3790: Fix compatibility for deprecated Controller call in r0.5

- segmentstore/server/src/main/java/io/pravega/segmentstore/server/writer/StorageWriter.java
- segmentstore/server/src/test/java/io/pravega/segmentstore/server/writer/StorageWriterTests.java
- segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/StorageNotPrimaryException.java
- Fixed a bug in `StorageWriter` where it would not shut down (at all) if it detected `StorageNotPrimaryException`.
Fixes #3805.
- Added `StorageNotPrimaryException` to the list of "critical" errors after which the `StorageWriter` must auto-shut down if it detects.
- This is already thrown correctly by `SegmentAggregator` and a `StorageWriter` shutdown is already correctly handled upstream (triggering an entire container shutdown).
Added unit test.
> Issue 3805: (SegmentStore) BugFix - StorageWriter not shutting down if Tier 2 fencing detected.

- segmentstore/server/src/main/java/io/pravega/segmentstore/server/attributes/SegmentAttributeBTreeIndex.java
- segmentstore/server/src/main/java/io/pravega/segmentstore/server/writer/SegmentAggregator.java
- segmentstore/server/src/test/java/io/pravega/segmentstore/server/writer/SegmentAggregatorTests.java
- Fixed a bug in `SegmentAggregator` where it was not able to properly recover from a Segment being created behind the scenes.
- Fixes a minor nuisance in `SegmentAttributeBTreeIndex` where `toString()` was not implemented, hence making log parsing more difficult.
Fixes #3724.
- Fixes the following bug: https://github.com/pravega/pravega/issues/3724#issuecomment-494099244
- If the `SegmentAggregator` gets a `StreamSegmentExistsException` while trying to create a new segment in Tier 2 Storage, it calls `openWrite` to get a handle to it. This will allow subsequent operations to continue executing.
- Note 1: If there is a fencing event, `openWrite` will throw the appropriate exception and the upstream code will …
> Issue 3724: (SegmentStore) BugFix - Creating an already existing Segment in Tier 2

- client/src/main/java/io/pravega/client/netty/impl/Connection.java
- client/src/main/java/io/pravega/client/netty/impl/FlowHandler.java
- client/src/main/java/io/pravega/client/segment/impl/SegmentOutputStream.java
- client/src/main/java/io/pravega/client/stream/impl/ReaderGroupImpl.java
- client/src/main/java/io/pravega/client/stream/impl/ReaderGroupState.java
- client/src/main/java/io/pravega/client/stream/impl/ReaderGroupStateManager.java
* Fix `BX_UNBOXING_IMMEDIATELY_REBOXED` spotBugs error observed on Java 11 based build. 
* Remove java doc warnings in Pravega client build.
Fixes #3811 
No changes in functionality. Fixes the spotbugs error observed with a Java 11 based build and java doc warnings.
> Issue 3811: Fix SpotBugs error on Java 11 build.
