pravega/pravega

test/integration/src/test/java/io/pravega/test/integration/ControllerFailoverTest.java

The test case failure mentioned in #1314 is very sporadic. Unmasking exception stack traces from test steps so as to ease debugging and finding error cause if the test fails again.
Improve error logging from ControllerFailoverTest integration test.
Helps find root cause of ControllerFailoverTest failure reported in #1314
No behaviour is changed.

Issue 1314: Avoid masking exception stack traces in ControllerFailover test so as to ease debugging

---

deployment/aws/aws.tf
deployment/aws/bootstrap.sh
deployment/aws/installer/roles/install-prereqs/tasks/main.yml
deployment/aws/variable.tf
docs/deployment/aws-install.md

Edit the aws deployment docs, and simplify deploy steps. Deploy a released pravega rather than latest master branch pravega.
Edit the aws deployment docs, and simplify deploy steps
Edit aws-install.md, and use wget rather than gradle.
sudo terraform apply

Issue 1299: Edit aws deployment docs

---

controller/src/main/java/io/pravega/controller/store/stream/InMemoryStream.java
controller/src/main/java/io/pravega/controller/store/stream/InMemoryStreamMetadataStore.java
controller/src/main/java/io/pravega/controller/task/Stream/StreamMetadataTasks.java
controller/src/test/java/io/pravega/controller/server/v1/ControllerServiceImplTest.java
controller/src/test/java/io/pravega/controller/server/v1/InMemoryControllerServiceImplTest.java
controller/src/test/java/io/pravega/controller/server/v1/ZKControllerServiceImplTest.java

Added test cases to cover missing APIs in ControllerServiceImpl
Fixes #1364 
Tests additional apis in ControllerServiceImpl
./gradlew test

Issue 1364: Improving test coverage for ControllerServiceImpl

---

shared/metrics/src/main/java/io/pravega/shared/metrics/DynamicLoggerImpl.java

Corrected reporting of gauge metrics.
Fixes #1298 
Corrects gauge metrics.
MetricsProviderTest

Issue 1298: Correct gauge metrics

---

test/system/src/main/java/io/pravega/test/system/framework/services/ZookeeperService.java

Updates Zookeeper version in system tests.
System tests are not currently using latest version of zookeeper.
Fixes #1483 

Issue 1483: Update zk version

---

controller/src/main/java/io/pravega/controller/store/stream/AbstractStreamMetadataStore.java
shared/metrics/src/main/java/io/pravega/shared/metrics/DynamicLogger.java
shared/metrics/src/main/java/io/pravega/shared/metrics/DynamicLoggerImpl.java
shared/metrics/src/main/java/io/pravega/shared/metrics/DynamicLoggerProxy.java
shared/metrics/src/main/java/io/pravega/shared/metrics/NullDynamicLogger.java

Corrected the reporting of segment metrics.
Fixes #1369 
Corrects the value types associated.
startStandlone gradle task creates a few metrics in /tmp/csv/pravega.

Issue 1369: Correct segment metrics

---

segmentstore/server/host/src/main/java/io/pravega/segmentstore/server/host/ZKSegmentContainerMonitor.java
segmentstore/server/host/src/test/java/io/pravega/segmentstore/server/host/ZKSegmentContainerMonitorTest.java

ZKSegmentContainerMonitor uses ScheduledExecutorService.scheduleWithFixedDelay() to setup up a monitor at regular intervals. The monitor is not scheduled if it throws any exception -
https://docs.oracle.com/javase/7/docs/api/java/util/concurrent/ScheduledExecutorService.html#scheduleWithFixedDelay(java.lang.Runnable,%20long,%20long,%20java.util.concurrent.TimeUnit)
Now handling all exceptions so the segmentcontainer monitor is not halted on exceptions.
Fixes #1532 
Handles all container start/stop exceptions so that they can be retries in the next schedule.
Added test case for startContainer throwing exception.

Issue 1532: ZKSegmentContainerMonitor should handle all exceptions

---

config/config.properties

Added extended S3 and filesystem configuration to config.properties.
Ensure that the configuration of extended S3 and filesystem is available through config.properties.
Adds the new properties to `config.properties` with explanation and defaults as applicable.

Issue 1590: Added extended S3 and filesystem configuration to config.properties.

---

controller/src/main/java/io/pravega/controller/store/index/ZKHostIndex.java
controller/src/main/java/io/pravega/controller/store/stream/InMemoryStream.java
controller/src/main/java/io/pravega/controller/store/stream/InMemoryStreamMetadataStore.java
controller/src/main/java/io/pravega/controller/store/stream/PersistentStreamBase.java
controller/src/main/java/io/pravega/controller/store/stream/StoreException.java
controller/src/main/java/io/pravega/controller/store/stream/ZKStoreHelper.java
controller/src/main/java/io/pravega/controller/store/stream/ZKStream.java
controller/src/main/java/io/pravega/controller/store/stream/ZKStreamMetadataStore.java
controller/src/main/java/io/pravega/controller/store/stream/tables/TableHelper.java
controller/src/test/java/io/pravega/controller/rest/v1/StreamMetaDataTests.java
controller/src/test/java/io/pravega/controller/store/stream/StreamMetadataStoreTest.java
controller/src/test/java/io/pravega/controller/store/stream/ZKStreamMetadataStoreTest.java
controller/src/test/java/io/pravega/controller/store/stream/ZkStreamTest.java

Few of the StoreException logs do not contain complete error description which is required for debugging.
Now updated the error description to contain as much information as possible.
Fixes #1629 
Adds more error description to StoreException logs
Check exception log messages and verify the error description

Issue 1629: Ensure detailed store exception error message is logged

---

test/system/src/test/java/io/pravega/test/system/MultiReaderTxnWriterWithFailoverTest.java

Remove delay.
Fixes issue #1642 

Issue 1642: Remove unnecessary delay while writing events to a transaction.

---

test/system/src/test/java/io/pravega/test/system/MultiReaderWriterWithFailOverTest.java

Handles the exception while closing readers in failover system test.
The test fails on the retries exhausted exception thrown by `reader.close()`.
Fixes #1651 

Issue 1651: Fix the issues while closing readers in multireaderwriterfailover system test

---

test/system/src/test/java/io/pravega/test/system/MultiReaderTxnWriterWithFailoverTest.java

Wait for all transaction status,  before comparing `post failover write count with pre failover write count`/ `write count with read count`.
While failover is happening it can take long to reach committed state. Hence, the assert fails when we 
compare the write count  immediately(40s) after failover.
Fixes #1653 

Issue 1653: Do a comparison on read, write count only after fetching all the transaction status

---

controller/src/main/java/io/pravega/controller/server/SegmentHelper.java

Txn Commit Segment should be idempotent
Fixes #1674 
Handles no such segment msg.

Issue 1674: Txn Commit Segment must be idempotent

---

segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/bookkeeper/BookKeeperLog.java

- Fixed an (async) infinite loop between `writeProcessor` and `rolloverProcessor`. 
- `writeProcessor`: picks writes from the write queue and sends them to BK, making sure that we don't exceed the concurrency quota; also cleans up the queue after writes are done.
- `rolloverProcessor`: checks if there's a need to rollover a Ledger into the next one, and triggers that action if needed.
- While this currently has no performance implications, it does tie up a CPU per SegmentContainer, so given enough such containers per host, eventually all CPUs would be busy with this.
- This was due to the fact that:
a. The `rolloverProcessor` is invoked after each iteration of the `writeProcessor`, AND 
b. The `writeProcessor` is invoked after each iteration of the …

Issue 1693: (SegmentStore) Bugfix - infinite loop in BookKeeperLog

---

docs/key-features.md

Making changes to improve the readability of the key-features doc.
Fixes #1677 
There is no code change, just doc changes.
Read it!

Issue 1677: Update key-features doc

---

.travis.yml
shared/controller-api/src/main/swagger/Controller.yaml

Using secure token for Travis and slack integration
Using secure token for Travis and slack integration.   Closes #1712.
Replaces the plain token with an encrypted secure token.
Slack channel `pravega-build` shows build notifications for the pull request.

Issue 1712: Use encrypted credentials for Travis integration with slack in .travis.yml

---

controller/src/main/java/io/pravega/controller/store/stream/PersistentStreamBase.java
controller/src/main/java/io/pravega/controller/store/stream/tables/State.java
controller/src/main/java/io/pravega/controller/task/Stream/StreamMetadataTasks.java
controller/src/main/java/io/pravega/controller/task/Stream/StreamTransactionMetadataTasks.java

Controller logging is inadequate for happy cases esp during scale operation. Add logs for each step at debug level.
Also found couple of minor issues:
1. incorrect log message, says 'failed to add-host index' when it indeed succeeded.
2. Incorrect state transition: Fix for sealing -> sealing, sealed [its incorrectly set as scaling, sealed]
Improves logging
Adds new logs. Fixes couple of minor issues
All existing tests should pass.

Issue1724 Improve controller logging for scale operation and fix few minor issues

---

client/src/main/java/io/pravega/client/stream/impl/ControllerImpl.java

Right now scaleStream and startScale both call scaleStreamInternal but handle the responses differently.
There should be consistency in the way the response is handled across both calls.
Fixes issue #1742
Refactored startScale to create handleScaleResponse method which logs and throws the exception.
We invoke this same method in scaleStream and wrap it under a try catch block and complete the cancellableRequest's future if startScale had thrown an exception.
All existing tests should pass.

Issue 1742: ControllerImpl methods scaleStream and startScale should be consistent in throwing same exceptions for similar responses

---

segmentstore/server/host/src/main/java/io/pravega/segmentstore/server/host/handler/PravegaRequestProcessor.java
segmentstore/server/host/src/test/java/io/pravega/segmentstore/server/host/handler/PravegaRequestProcessorTest.java

Made CommitTransaction idempotent with respect to Seals in PravegaRequestProcessor by ignoring the `StreamSegmentSealedException` that comes back from the SegmentStore (if it does). 
This happens because a `CommitTransaction` command issues two requests on the Server: Seal and Merge, and a failover could have happened between the two (in which case the Txn would be sealed but not merged). Upon failover, the command would attempt to re-seal the Txn, which is rejected by the SegmentStore. This change makes the command idempotent with respect to Seals.
Fixes #1772.
PravegaRequestProcessor: Ignores `StreamSegmentSealedException` when executing CommitTransaction.
Unit tests updated.

Issue 1772: PravegaRequestProcessor - Seal must be idempotent for Txns

---

controller/src/main/java/io/pravega/controller/server/eventProcessor/AutoScaleRequestHandler.java
controller/src/main/java/io/pravega/controller/server/eventProcessor/ConcurrentEventProcessor.java
controller/src/main/java/io/pravega/controller/server/eventProcessor/ScaleOperationRequestHandler.java
controller/src/main/java/io/pravega/controller/store/stream/PersistentStreamBase.java
controller/src/main/java/io/pravega/controller/task/Stream/StreamMetadataTasks.java

- Adds more info level logs during scale processing. 
Fixes #1778 
Adds more logs
All existing unit tests should continue to pass

Issue 1778: Improved INFO level logging in scale processing

---

segmentstore/server/src/main/java/io/pravega/segmentstore/server/writer/SegmentAggregator.java
segmentstore/server/src/test/java/io/pravega/segmentstore/server/writer/SegmentAggregatorTests.java
segmentstore/server/src/test/java/io/pravega/segmentstore/server/writer/TestWriterDataSource.java

Fixed a bug in `SegmentAggregator` where it would incorrectly throw `DataCorruptionException` if the Segment was deleted in the metadata (and ReadIndex cleared) while flush() was running.
Details:
The SegmentContainer deletes a segment with the following steps:
1. Delete from Metadata
2. Delete state files
3. Remove Read Indices
The `StorageWriter` will eventually pick up deleted Segments and remove their associated `SegmentAggregators`. However, there is a possibility that `#3` above happens while the corresponding `SegmentAggregator` executes `flush` (after the last check for `IsDeleted`). In this case, is is possible the `SegmentAggregator` would not be able to read from the ReadIndex (since it has been cleared out) and would incorrectly throw a …

Issue 1786: (SegmentStore) Fixed segment deletion race in StorageWriter 

---

test/system/src/test/java/io/pravega/test/system/MultiReaderTxnWriterWithFailoverTest.java

- Correct assert statement in MultiReaderTxnWriterWithFailoverTest.
Fixes #1823 
test should pass.

Issue 1823 : Correct assert statement in MultiReaderTxnWriterWithFailoverTest

---

common/Readme

Make the common readme more accurate
Fixes #1837
Fixes #1837
Read the readme.

Issue 1837 : Make common readme more accurate

---

segmentstore/server/host/src/main/java/io/pravega/segmentstore/server/host/handler/AppendProcessor.java
segmentstore/server/host/src/main/java/io/pravega/segmentstore/server/host/handler/PravegaRequestProcessor.java

Reduces log spam and increases usefulness of messages logged.
Fixes #1835
Changes log lines.
There should be no impact.

Issue 1835: Tone down log levels, for 'normal' errors.

---

client/src/main/java/io/pravega/client/netty/impl/ClientConnectionInboundHandler.java

*  Throw ConnectionFailedException to any late sends that arrive on a connection that has already failed.
Fixes #1785 
Throws an ConnectionFailedException (which is properly handled by the caller) instead of an IllegalStateException.
All existing tests should pass. Applications should no longer see this error coming from the writer as a race condition when connections are dropped.

Issue 1785: Throw ConnectionFailedException to any late sends 

---

gradle.properties

* Update pravegaVersion in gradle.properties to 0.1.1-SNAPSHOT
Fixes #1898 
No code change, only a configuration change.
`./gradlew install` and check that the correct version is published locally.

Issue 1898: Update pravega version in branch r0.1

---

segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/bookkeeper/LogReader.java
segmentstore/storage/src/test/java/io/pravega/segmentstore/storage/DurableDataLogTestBase.java

Fixed a bug in the BookKeeper `LogReader` where it would not open old ledgers with recovery, thus potentially not recovering all written items. 
Fixes #1900.
A BookKeeper ledger needs to be closed to guarantee agreement on the sequence of entries appended. If a ledger is left open and not recovered, then it is possible that not all entries will be read from the ledger, even in the case the writes have succeeded. Consequently, to guarantee that all successful reads of a ledger will be read when we use it for recovery, we need to open the ledger with recovery.
We must also be careful not to open all ledgers with recovery; the last ledger is our active one, and if we open it with recovery we will fence ourselves out. …

Issue 1900: (SegmentStore) BugFix for potential data loss upon BookKeeper recovery

---

client/src/main/java/io/pravega/client/admin/impl/ReaderGroupManagerImpl.java
client/src/main/java/io/pravega/client/admin/impl/StreamManagerImpl.java
client/src/main/java/io/pravega/client/stream/ReaderGroupConfig.java
client/src/main/java/io/pravega/client/stream/impl/ClientFactoryImpl.java
controller/src/main/java/io/pravega/controller/util/Config.java
segmentstore/server/host/src/main/java/io/pravega/segmentstore/server/host/ServiceStarter.java

* Log configuration of controller , segment store during startup.  
* Log the configuration passed to the client apis.
Fixes #1885 
Fixes #1885 
Tests should pass, no change in functionality.

Issue 1885:  Log configuration during startup at info level

---

test/system/src/test/java/io/pravega/test/system/ReaderCheckpointTest.java

- System test for checkpointing of stream.
Fixes #1908 
Initiate multiple checkpoints on a reader group and validate if we can restore to the check point. 
The test passes with latest pravega version `0.2.0-1620.0be1ccb`

Issue 1908: System test for checkpointing

---

client/src/main/java/io/pravega/client/admin/ReaderGroupManager.java

Change the Javadoc to reflect the actual behavior
There is no code change, only a javadoc change.
Fixes #1895 
Having correct JavaDoc

Issue 1895: Fix JavaDoc for ReaderGroupManager.withScope

---

CODE_OF_CONDUCT.md
gradle/rat.gradle

* Adds a code of conduct file
Fixes #1199.
There is no code change, it adds a code of conduct file.
Read it.

Issue 1199: Code of Conduct

---

docs/mkdocs.yml
docs/pravega-concepts.md
docs/segment-store-service.md

Updated Segment Store documentation. Linked it from Pravega Concepts.
Fixes #1987.
Read documentation.

Issue 1987: Updated pravega.io SegmentStore documentation

---

test/system/src/test/java/io/pravega/test/system/ReadWithAutoScaleTest.java
test/system/src/test/java/io/pravega/test/system/ReaderCheckpointTest.java

* Adds more debug logging to ReadWithAutoScaleTest and ReaderCheckpointTest to debug a reader issue.
Fixes #2086 
Adds more information to some assertions and some new log messages.
There is no functionality change.

Issue 2086: Add logging to system test cases

---

test/system/src/test/java/io/pravega/test/system/AbstractFailoverTests.java

Reduces number of events per transaction in System test
Fixes #2201
Reduces number of events from 500 to 50
System test should pass

Issue 2201: Reduce number of events per transaction in System test

---

segmentstore/server/host/src/test/java/io/pravega/segmentstore/server/host/handler/PravegaRequestProcessorTest.java

Expanded the `PravegaRequestProcessor.testCreateSealTruncateDelete` test to verify idempotence and handling of bad arguments.
Fixes #2203.
Added more tests to `testCreateSealTruncateDelete`.
Unit test must pass.

Issue 2203: Enhanced PravegaRequestProcessor to verify more truncation scenarios

---

gradle.properties

* Removes snapshot suffix in Pravega version
Fixes #2278 
There is no code change, it is only a parameter change.
Build.

Issue 2278: Change version in r0.2 branch for release candidate

---

gradle.properties

* Change version of r0.2 branch to `0.2.2-SNAPSHOT`
Fixes #2287 
There is no code change, only a configuration change in `gradle.properties`.
Build.

Issue 2287: Change r0.2 version to 0.2.2-SNAPSHOT

---

test/integration/src/test/java/io/pravega/test/integration/BatchClientTest.java

Integration tests for batch client.
Fixes #2217 
Creates a integration test to validate batch client apis.

Issue 2217: Integration tests for batch client.

---

client/src/main/java/io/pravega/client/stream/impl/Controller.java

* Adds some more detail to the javadocs of the controller interface and makes some other minor improvements. 
Fixes #2274 
There is no code change, only javadoc changes.
Javadocs build task should be successful.

Issue 2274: Improvements to controller interface javadocs

---

segmentstore/server/src/main/java/io/pravega/segmentstore/server/logs/DurableLog.java

Fixed the order of operations when shutting down the DurableLog due to a startup failure to ensure it is failed with the correct exception.
- Previously it was shutting down the `OperationProcessor` before calling `notifyFailed`. The `OperationProcessor` has an async shutdown listener which shuts down the `DurableLog` if it stops for whatever reason. It turns out that every now and then, that async listener would shut down the `DurableLog` before the call to `notifyFailed` went through.
Fixes #2131.
Fixed the order of operations when shutting down the DurableLog due to a startup failure to ensure it is failed with the correct exception.
Run the `DurableLogTests.testRecoveryWithMetadataCleanup` …

Issue 2131: (SegmentStore) Fixed sporadic unit test failure.

---

documentation/src/docs/segment-store-service.md

The SegmentStore [documentation in v0.2.1](http://pravega.io/docs/v0.2.1/segment-store-service/)has some formatting issues due to missing empty lines before bullet lists in markdown.
Also, made a minor update to the document to reflect the latest changes in the append path.
Fixes #2340.
Verify the doc has empty lines before bullet points.

Issue 2340: Fixed formatting issues for Segment Store documentation

---

test/system/src/test/java/io/pravega/test/system/ReadTxnWriteAutoScaleWithFailoverTest.java
test/system/src/test/java/io/pravega/test/system/ReadTxnWriteScaleWithFailoverTest.java
test/system/src/test/java/io/pravega/test/system/ReadWriteAndAutoScaleWithFailoverTest.java
test/system/src/test/java/io/pravega/test/system/ReadWriteAndScaleWithFailoverTest.java

Indentation of code in some of the system tests got disturbed with recent changes. 
Fixing the same.
Fixes #2362 
Corrects the wrongly indented lines of code.
No functional change. Build should pass

Issue 2362: Fixing incorrect indentation in system tests

---

segmentstore/server/src/main/java/io/pravega/segmentstore/server/writer/StorageWriter.java

Removed unnecessary use of `CompletableFuture.join()` in `StorageWriter`, thus preventing an entire extra thread from being blocked every time a new `SegmentAggregator` is initialized.
Fixes #2377.
Exactly the same thing, but with `CompletableFuture` chaining.
No functional changes. All unit tests must pass.

Issue 2377: (SegmentStore) Removed unneeded usage of CompletableFuture.join()

---

test/integration/src/main/java/io/pravega/test/integration/selftest/adapters/ClientReader.java
test/integration/src/main/java/io/pravega/test/integration/selftest/adapters/SegmentStoreReader.java

- Fixed a bug in ClientReader where it would prematurely stop reading due to a false positive regarding the end of the stream from the EventStreamReader.
- Fixed a bug in SegmentStoreReader where it would prematurely truncate the underlying Storage segment, thus interfering with the functioning of the StorageWriter during the test.
Fixes #2421.
Fixed SelfTester bugs.
SelfTester must be able to process tail reads when using Client and all types of reads when using SegmentStore direct.

Issue 2421: (SegmentStore) Fixed reading bugs in SelfTester

---

client/src/main/java/io/pravega/client/stream/impl/ReaderGroupStateManager.java

Add some debug logging to dump reader group state in various code paths.
Help diagnose #2381
Adds debug logging
No changes

Issue 2381: Add some debug logging

---

client/src/main/java/io/pravega/client/batch/SegmentRange.java
client/src/main/java/io/pravega/client/batch/impl/SegmentRangeImpl.java

Ensure SegmentRange is serializable.
Fixes #2433 
SegmentRange is now serializable.

Issue2433: Ensure SegmentRange is serializable.

---

documentation/src/docs/basic-reader-and-writer.md
documentation/src/docs/reader-group-notifications.md

Update ReaderGroup and BatchClient documentation to match the current API.
Fixes #2458 

Issue 2458 Update ReaderGroup and BatchClient documentation.

---

test/integration/src/test/java/io/pravega/test/integration/endtoendtest/EndToEndChannelLeakTest.java

Refactor and remove the race condition in EndToEndChannelLeakTest#testDetectChannelLeakMultiReader.
Fixes #2523 
Remove race condition while checking for open sockets.
The tests should continue to pass.

Issue 2523: Remove race condition in the EndToEndChannelLeakTest.

---

segmentstore/server/src/test/java/io/pravega/segmentstore/server/containers/StreamSegmentContainerTests.java

Fixed `StreamSegmentContainerTests.testExtendedAttributesConditionalUpdates` which was sporadically failing on the cloud build system.
Root cause:
- Either the segment or its attributes must have gotten evicted from memory before the final attribute verification. 
- As such, calling `getStreamSegmentInfo` did not include those extended attributes we were looking for (the returned value was NULL_VALUE, which is consistent with it not being cached)
Fix:
- Explicitly evict the segment from memory, then re-fetch the attributes and properly execute the tests.
Fixes #2555
Fixes unit test.
Unit test must pass.

Issue 2555: (SegmentStore) Fixed a sporadically failing unit test

---

documentation/src/docs/streamCuts.md
documentation/src/docs/streamcuts.md
documentation/src/mkdocs.yml

Documentation for using StreamCuts.
Fixes #2541 
Documentation regarding StreamCuts added.

Issue 2541: StreamCut Documentation

---

segmentstore/server/host/src/main/java/io/pravega/segmentstore/server/host/handler/AppendProcessor.java

Currently, transaction metrics are reported seperately similar to any other segment, after the txn is committed , in this format `pravega.segmentstore.segment_write_bytes.$scope.$stream.$segment#transaction.$txnId.Counter`
They should not be reported. They should be reported as part of parent segment metrics, which will be fixed in #2570 
Fixes #2526 
* Report the `segmentstore.segment_write_events`,  `segmentstore.segment_write_bytes` metrics  
only for a non transactional segment. 
Build should pass, txn specific metrics shoudl not longer get reported

Issue 2526: Do not report transaction specific metrics

---

.travis.yml

This PR address the issue https://github.com/pravega/pravega/issues/2615
To improve travis build time for the master brach when snapshots are require to be published 
The snapshot build stage perform publishing artifacts only after the `master` branch is successfully compiled and tested. 
Tested and confirmed on Travis for the PR branch
https://travis-ci.org/pravega/pravega/builds/382492364

[Issue-2615] Optimized travis build for snapshot artifacts publishing

---

client/src/test/java/io/pravega/client/stream/impl/ReaderGroupStateManagerTest.java

Add Junit to validate a readerShutdown scenario with null offset and ensure that the segments owned by the reader are rebalanced to other readers.
Fixes #2646 
Adds a Junit test case for the changes in PR#2643. This test
- Validates readerShutDown scenario with null offset.
- Validates that segments are rebalanced to the remaining reader.
- Validates the serialization and deserialization for ReaderGroupState for RemoveReader, AddReader and ReaderGroupStateInit.
No functionality changes, the newly added test should pass.

Issue 2646: Junits to validate readerShutdown with null offset.

---

segmentstore/server/src/main/java/io/pravega/segmentstore/server/containers/StreamSegmentContainer.java

Optimized two scenarios pertaining to fetching Extended Attributes.
1. If we are not instructed to cache any misses, then do not bother to execute the search using an asynchronous retry-loop. This will avoid the complexity of creating a runnable, scheduling it on a thread pool, and joining on its result.
2. If we were able to retrieve all sought Attributes from the Segment Metadata cache, then do not bother to invoke the Attribute Index lookup (with an empty collection). Even if it returns right away, since it's an asynchronous operation, it will take CPU cycles to schedule it on the thread pool and wait for its result.
Fixes #2713. Optimization. Not needed for EAP2.
Performance improvement when looking up …

Issue 2713: (SegmentStore) Extended Attributes retrieval optimization

---

test/system/src/test/java/io/pravega/test/system/BookieFailoverTest.java

Fix compiler error caused by merge conflict.
https://github.com/pravega/pravega/pull/2638 caused an error in the master build because it refereed to a method who's return type changed between the time the PR build went though and it's merge to master.
Changes the test to work with the new return type (long)
Tests should now build.

Issue 2750: Fix compiler error caused by merge conflict.

---

client/src/test/java/io/pravega/client/segment/impl/SegmentInputStreamTest.java

Add segment truncation check to orderer test.
Add a test to prevent regression of the support for truncation in #2742
Adds additional assertions to the Orderer test in SegmentInputSteamTest
The new test should pass.

Issue 2739: Add checks for truncated segments to SegmentInputSteamTest

---

client/src/main/java/io/pravega/client/segment/impl/AsyncSegmentInputStream.java
client/src/main/java/io/pravega/client/segment/impl/SegmentInputStream.java
client/src/main/java/io/pravega/client/segment/impl/SegmentInputStreamImpl.java
client/src/main/java/io/pravega/client/stream/impl/EventStreamReaderImpl.java
client/src/main/java/io/pravega/client/stream/impl/Orderer.java
client/src/main/java/io/pravega/client/stream/impl/ReaderGroupStateManager.java
client/src/test/java/io/pravega/client/segment/impl/SegmentInputStreamTest.java
client/src/test/java/io/pravega/client/stream/impl/EventStreamReaderTest.java
client/src/test/java/io/pravega/client/stream/impl/OrdererTest.java
client/src/test/java/io/pravega/client/stream/mock/MockSegmentIoStreams.java
common/src/main/java/io/pravega/common/util/CircularBuffer.java
segmentstore/contracts/src/main/java/io/pravega/segmentstore/contracts/StreamSegmentStore.java
segmentstore/server/host/src/main/java/io/pravega/segmentstore/server/host/handler/PravegaRequestProcessor.java
segmentstore/server/host/src/test/java/io/pravega/segmentstore/server/host/handler/PravegaRequestProcessorTest.java
segmentstore/server/src/main/java/io/pravega/segmentstore/server/containers/ReadOnlySegmentContainer.java
segmentstore/server/src/main/java/io/pravega/segmentstore/server/containers/StreamSegmentContainer.java
segmentstore/server/src/main/java/io/pravega/segmentstore/server/mocks/SynchronousStreamSegmentStore.java
segmentstore/server/src/main/java/io/pravega/segmentstore/server/store/StreamSegmentService.java
segmentstore/server/src/main/java/io/pravega/segmentstore/server/writer/SegmentAggregator.java
segmentstore/server/src/test/java/io/pravega/segmentstore/server/containers/StreamSegmentContainerTests.java
segmentstore/server/src/test/java/io/pravega/segmentstore/server/store/StreamSegmentContainerRegistryTests.java
segmentstore/server/src/test/java/io/pravega/segmentstore/server/store/StreamSegmentStoreTestBase.java
segmentstore/server/src/test/java/io/pravega/segmentstore/server/writer/SegmentAggregatorTests.java
test/integration/src/main/java/io/pravega/test/integration/selftest/adapters/InProcessMockClientAdapter.java
test/integration/src/main/java/io/pravega/test/integration/selftest/adapters/SegmentStoreAdapter.java

This pull bug fixes from master into 0.3 branch. 
In preparation for a release of a 0.3.1 version, merges existing bug fixes from master into the 0.3 branch. Fixes #2775.
See the individual commit / PR descriptions.
All pre-release testing needs to be run.

Issue 2775: Merge bugfixes into r0.3 branch for release of r0.3.1

---

segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/bookkeeper/ZooKeeperServiceRunner.java

Signed-off-by: Eron Wright <eronwright@gmail.com>
- cleanly stop `ZooKeeperServiceRunner`
Closes #2769 
Stops the NIO server before stopping the underlying ZK server.  Explicitly closes the ZK database (as seen in `TestingZooKeeperMain`).
- `io.pravega.local.InProcPravegaClusterTest`

Issue 2769: Standalone mode should cleanly shutdown the embedded ZK server

---

config/standalone-config.properties
standalone/src/main/java/io/pravega/local/InProcPravegaCluster.java
standalone/src/main/java/io/pravega/local/LocalPravegaEmulator.java
standalone/src/main/java/io/pravega/local/SingleNodeConfig.java
standalone/src/test/java/io/pravega/local/InProcPravegaClusterTest.java

Add the ability to enable or disable the REST server for standalone Pravega based on the [`InProcPravegaCluster.startRestServer`](https://github.com/pravega/pravega/blob/5f4d75b877dd1e5b5b6ab829d278e8aaae17e5d1/standalone/src/main/java/io/pravega/local/InProcPravegaCluster.java#L113) build option. 
Fix #2793 
Checks the value of the `startRestServer` boolean variable to decide whether to create the REST configuration or not. If the REST configuration is not created, the controller does not start the REST server.
Set the `startRestServer` to `false` when building the `InProcPravegaCluster` in the [`LocalPravegaEmulator.build()`](https://github.com/pravega/pravega/blob/0670ced0ceb67584edd1ea9244b …

Issue 2793: Ability to enable/disable REST server for standalone Pravega

---

.github/PULL_REQUEST_TEMPLATE.md

* Updates the PR template to give hints on the different sections of the description.
Fixes #2752 
No code change, only changes to the PR template.
Visualize the md file.

Issue 2752: Update PR template to give some hints on the different sections

---

client/src/main/java/io/pravega/client/stream/impl/Pinger.java

* Log and suppress exceptions when pinging transactions.
Fixes #2805
Refactors pingTransactions() to handle unexpected exceptions rather than letting them reach the thread pool which would cancel the recurring task.

Issue 2805: Improve resilience of Pinger

---

client/src/main/java/io/pravega/client/segment/impl/SegmentOutputStreamFactory.java
client/src/main/java/io/pravega/client/segment/impl/SegmentOutputStreamFactoryImpl.java
client/src/main/java/io/pravega/client/segment/impl/SegmentOutputStreamImpl.java
client/src/main/java/io/pravega/client/stream/impl/ControllerImpl.java
client/src/main/java/io/pravega/client/stream/impl/EventStreamWriterImpl.java
client/src/main/java/io/pravega/client/stream/impl/Pinger.java
client/src/main/java/io/pravega/client/stream/impl/ReaderGroupState.java
client/src/main/java/io/pravega/client/stream/impl/SegmentSelector.java
client/src/main/java/io/pravega/client/stream/impl/SegmentWithRange.java
client/src/main/java/io/pravega/client/stream/impl/StreamSegments.java
client/src/main/java/io/pravega/client/stream/impl/StreamSegmentsWithPredecessors.java
client/src/test/java/io/pravega/client/segment/impl/SegmentOutputStreamTest.java
client/src/test/java/io/pravega/client/stream/impl/EventStreamWriterTest.java
client/src/test/java/io/pravega/client/stream/impl/ReaderGroupStateManagerTest.java
client/src/test/java/io/pravega/client/stream/impl/StreamSegmentsTest.java
client/src/test/java/io/pravega/client/stream/mock/MockSegmentStreamFactory.java
segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/hdfs/HDFSStorage.java
test/integration/src/test/java/io/pravega/test/integration/ReaderGroupStreamCutUpdateTest.java
test/integration/src/test/java/io/pravega/test/integration/endtoendtest/EndToEndTxnWithTest.java

This pull bug fixes from master into 0.3 branch. 
In preparation for a release of a 0.3.2 version, merges existing bug fixes from master into the 0.3 branch. Fixes #2838
See the individual commit / PR descriptions.
All pre-release testing needs to be run.

Issue 2838: Merge bugfixes into r0.3 branch for release of r0.3.2

---

documentation/src/docs/deployment/docker-swarm.md
documentation/src/docs/streamcuts.md

Hyperlinks fixed
Fixes #2840, #2835

Issue 2840: Hyperlinks updated

---

documentation/src/docs/controller-service.md

Broken links fixed in controller-service.md
Formatting error fixed in controller-service.md
Fixes #2874

Issue 2874: Diagram links rendered in controller docs

---

controller/src/main/java/io/pravega/controller/server/rpc/grpc/v1/ControllerServiceImpl.java

Signed-off-by: Shivesh Ranjan <Shivesh.Ranjan@gmail.com>
Build failure because of merge (conflict) where authentication method was changed. 
Fixes #2917 
Authentication method for grpc calls was recently changed and a newly added grpc api conflicted with the previous change but since this was a new method added, it used the older (removed) method and hence the build failure. 

Issue 2917: Master built broken after merge

---

documentation/src/docs/index.md

1. Fixed formatting errors
2. Edited content
3. Fixed links
Fixes #2906, Closes #2922

Issue 2906:Document fix index.md

---

documentation/src/docs/segment-store-service.md

1. Fixed formatting Errors
2. Edited content
3. Lists rendered correctly
Fixes #2909, Closes #2919

Issue 2909: Document fix segment-store-service.md

---

documentation/src/docs/roadmap.md

1. Fixed formatting errors
2. Included hyperlinks
Fixes #2910, Closes #2914

Issue 2910: Document fix Roadmap.md

---

documentation/src/docs/streamcuts.md

1.Fixed formatting errors
2. Fixed Broken links
Fixes #2907, Closes #2912

Issue 2907:Document fix streamcuts.md

---

documentation/src/docs/controller-service.md

1. Fixed Formatting errors
2. Included hyperlinks
3. Edited content
Fixes #2908, Closes #2913

Issue 2908: Document fix controller-service.md

---

documentation/src/docs/controller-service.md
documentation/src/docs/index.md
documentation/src/docs/roadmap.md
documentation/src/docs/segment-store-service.md
documentation/src/docs/streamcuts.md

Merging #2929, #2928, #2927,#2926,#2925 into 0.3 release branch for 0.3.2.
Closes #2906,#2908,#2907,#2909,#2910.

Issue 2945:Merge fixes from master to r0.3 for release 0.3.2 (Documentation)

---

gradle.properties

* Changes the Pravega version to 0.3.3-SNAPSHOT
Fixes #2947 
No code change, only build property change.

Issue 2947: Bump release version in r0.3 branch

---

documentation/src/docs/auth/auth-plugin.md
documentation/src/docs/auth/client-auth.md
documentation/src/docs/deployment/manual-install.md
documentation/src/docs/deployment/run-local.md
documentation/src/docs/index.md
documentation/src/docs/security/pravega-security-authorization-authentication.md
documentation/src/docs/security/pravega-security-configurations.md
documentation/src/docs/security/pravega-security-encryption.md

1. Formatting completed
2. Hyperlinks included
3. Content edited
Fixes #2591

Issue 2591: Security Documentation

---

documentation/src/docs/deployment/manual-install.md
documentation/src/docs/security/pravega-security-encryption.md

1. Fixed the broken links
2. Corrected the typos
Fixes #2989 
Renders the links correctly

Issue 2989: Document fix in pravega-security-encryption.md and manual-install.md

---

build.gradle

Remove dependency on netty from common.
Fix #2995
Removes an unneeded dependency

Issue #2995: Remove dependency on netty from common

---

test/integration/src/test/java/io/pravega/test/integration/endtoendtest/EndToEndChannelLeakTest.java

* Allow leak detector test time to converge on correct value.
#2523 was the result of a flaky test which is in turn due to the fact connection creation can be performed in a background thread. This leaves a race condition where the test could incorrectly see a value that is to small when running the leak detector.
The code now runs in a loop with a small sleep to give the value time to converge on the correct result. This shouldn't slow the test down except in cases where the test would otherwise fail, and even then not by too much.

Issue #2523: Allow leak detector test time to converge on correct value.

---

documentation/src/docs/segment-store-service.md

1. Formats Fixed
2. Hyperlinks Fixed
Fixes #3012

Issue 3012: Document fix: segmentstore_service.md

---

documentation/src/docs/segment-containers.md

1. Minor content edits
2. Last few sections ends up with **This needs further review/discussion.**
@andreipaduroiu , please address this !
Fixes #3022

Issue 3022: Content Update: Segment-containers.md

---

documentation/src/docs/basic-reader-and-writer.md
documentation/src/docs/state-synchronizer.md
documentation/src/docs/transactions.md

1.  version number in the hyperlink updated to v0.4.0
Fixes #3032

Issue 3032: Version number updated in documents

---

documentation/src/mkdocs.yml

Created `Pravega Security` section and added the following 5 files  in mkdocs.yml
1. auth/client-auth.md
2. auth/auth-plugin.md
3. security/pravega-security-authorization-authentication.md
4. security/pravega-security-configuration.md
5. security/pravega-security-encryption.md
Fixes #3029

Issue 3029: Documents added to mkdocs.yml

---

documentation/src/docs/getting-started.md
documentation/src/docs/index.md

1.Fixed  formatting errors
2. Links checked
Fixes #2999

Issue 2999: Document fix index.md and getting started.md

---

documentation/src/docs/controller-service.md

1. Capitalization of Terms maintained according to Terminology.md
2. Misc HTML tags removed from section headings.
3. Minor content editing performed.
Fixes #3024

Issue 3024: Document format Fixed: controller-service.md

---

documentation/src/docs/reader-group-design.md

1. Format issues fixed
2. Minor content edition performed.
3. Hyperlinks checked
4. **Request the developers (Sandeep and Tom) to check for any inclusion.**
Fixes #3020

Issue 3020: Updating reader-group.md

---

documentation/src/docs/pravega-concepts.md

1. Major content revised
2. Few hyperlinks added
3. All hyperlinks checked.
4. Typos and formats corrected
Fixes #2966

Issue 2966: Document fix pravegaconcepts doc

---

documentation/src/docs/security/pravega-security-configurations.md
documentation/src/docs/security/pravega-security-encryption.md

Updates documentation to be in sync with changes introduced because of #2034.
Fixes #3096.
Updates the documentation to update ZK TLS information.
View the documentation.

Issue 3096: Updating documentation with ZK TLS information.

---

segmentstore/server/src/main/java/io/pravega/segmentstore/server/attributes/SegmentAttributeBTreeIndex.java
segmentstore/server/src/test/java/io/pravega/segmentstore/server/attributes/AttributeIndexTests.java

- Fixed the `SegmentAttributeBTreeIndex.AttributeIteratorImpl` class to auto-reinitialize the underlying BTree iterator when it detects a `StreamSegmentTruncatedException`.
Fixes #3124.
- Keeping track of the last Attribute Id processed by the iterator.
- If a `StreamSegmentTruncatedException` is detected upon calling `getNext()`, the underlying BTreeIndex iterator is reinvoked using the last processed attribute id, so that the iteration may proceed.
- This is the same mechanism employed by `get()` in the same class.
Existing unit tests must pass.
New unit tests added for this scenario.

Issue 3124: (SegmentStore) Segment Attribute Iterators can't handle BTree Auto Compaction

---

documentation/src/docs/pravega-concepts.md

1. Retention Policy content included in the last section of Pravega-concepts.md
Fixes #3133

Issue 3133: Document review Pravega concepts

---

build.gradle

Produce a spotbugs HTML report.
Fixes #3180 
Deploys workaround 1 mentioned here: https://github.com/spotbugs/spotbugs-gradle-plugin/issues/32
Workaround 2 did not work.

Issue #3180: Produce spotbugs HTML report using workaround.

---

documentation/src/docs/key-features.md

1. Minor content edits
2. New features to be included(TBD)
Fixes #3142

Issue 3142: Document update:  key-features.md

---

segmentstore/storage/src/test/java/io/pravega/segmentstore/storage/StorageTestBase.java

* Speed up HdfsStorageTest.testWrite()
Fixes #3198
Changes appendCount to 10 from 100.

Issue #3198: Speed up HdfsStorageTest.testWrite()

---

segmentstore/server/src/test/java/io/pravega/segmentstore/server/reading/ContainerReadIndexTests.java

Fixed a sporadically failing unit test.
Fixes #3208.
Using `CompletableFuture.get` instead of `CompletableFuture.isCancelled` since the cancellation is asynchronous and it may not have yet executed when the condition was checked. `.get` will block until that happens or until a timeout expires.
Unit test must pass.

Issue 3208: (SegmentStore) Sporadic test failure - testMergeReadCancelledOnClose 

---

controller/src/main/java/io/pravega/controller/server/eventProcessor/requesthandlers/CommitRequestHandler.java
controller/src/test/java/io/pravega/controller/server/eventProcessor/ControllerEventProcessorTest.java

Porting changes from issue 3122 to r0.4 branch
(_e.g._, Fixes #666, Closes #1234)

Issue 3122: Bug in commit transaction workflow for a stream in sealing state

---

documentation/src/docs/wire-protocol.md

1. Minor edits(Content)
2. Format Fix
Fixes #3200

Issue 3200: Document Review: wire-protocol.md

---

test/system/src/test/java/io/pravega/test/system/AbstractReadWriteTest.java

Use a shared (synchronized) map across readers in `AbstractReadWriteTest` to check correct sequence of events per routing key.
Fixes #3304.
Currently, system tests check the correct order of events per routing key locally. This inherently implies that a reader is assumed to read consecutive events for a given routing key. However, due to segment rebalances across readers, this assumption does not hold. Let us imagine a reader group with 2 readers: `reader1` is reading events of a routing key `a`, then it switches to read events of another routing key `b`, while `reader2` takes over key `a` due to a segment rebalance across readers. The problem comes if, after another rebalance, `reader1` is responsible again …

Issue 3304: AbstractReadWriteTest throws incorrect sequence error after segment rebalance between readers

---

README.md

* Updates badges in readme file to include license and version.
Fixes #3317 
No code change, only readme change.
Render the readme file by viewing it.

Issue 3317: Update badges

---

documentation/src/docs/wire-protocol.md

Merging #3201 into 0.4 release branch for 0.4.0.
Closes #3200

Issue 3305: Merge fixes from master to r0.4 for release v0.4.0 (Documentation) 

---

gradle.properties

* Updates Pravega version to 0.4.0
Fixes #3353 
No code change, only configuration.
Build and make sure that it produces the correct snapshot version.

Issue 3353: Update version post 0.4.0 release

---

test/integration/src/test/java/io/pravega/test/integration/ReaderGroupNotificationTest.java

Fix flaky SegmentNotification test.
Fixes #3376 
The test now checks and waits for Segment notification before scale and after scale.
The test should continue to pass. Verified that the test passes over multiple(100+) runs.

Issue 3376: Fix flaky SegmentNotification test.

---

documentation/src/docs/state-synchronizer-design.md

1. Minor Edits
2. format fix
Fixes #3284

Issue 3284: Document review state-synchronizer-design.md

---

documentation/src/docs/controller-service.md
documentation/src/docs/security/pravega-security-authorization-authentication.md
documentation/src/docs/security/pravega-security-encryption.md
documentation/src/docs/wire-protocol.md

Format issues related to Pravega.io were fixed in the following docs:
documentation/controller-service.md
documentation /security/Pravega-security-Authorization -authentication.md
documentation /security/Pravega-security-encryption.md
documentation/wire-protocol.md
( Fixes #3366, Closes #3366)
Format fixed

Issue 3366: Format issues fixed in documentation

---

documentation/src/docs/deployment/run-local.md

updating the document run-local.md
Fixes #3402

Issue 3402: Security document update (run-local.md)

---

gradle.properties

* Updates version in gradle.properties to 0.4.1
Fixes #3436 
No code change, only a property change in `gradle.properties`.
Run `./gradlew install` and make sure that the artifacts have the correct version.

Issue 3436: Update Pravega version in the r0.4 branch to 0.4.1

---

documentation/src/docs/basic-reader-and-writer.md

This file was not rendered properly in Pravega.io, hence formats were fixed to display correctly in the website.
Fixes #3416

Document Format fix: basic-reader-and-writer.md

---

controller/src/test/java/io/pravega/controller/store/client/StoreClientFactoryTest.java

Makes test wait until zookeeper client's state gets closed. 
Fixes #3271 
The test is sporadically able to make zk call despite injecting zk session expiration in zookeeper client. 
To mitigate this, after injecting session expiration and getting notification from curator, we still wait until the zookeeper client returns false for isAlive. 
The test should consistently pass

Issue 3271: StoreClientFactoryTest > testZkSessionExpiryRetry 

---

documentation/src/docs/deployment/manual-install.md

1. Format Fix
2.Zookeeper version changed to 3.5.4.-beta
3.Bookkeeper version changed to 4.7.0
Fixes #3461, Closes #3461)

Issue 3461: Zookeeper and Bookeeper version number changed in document manual-install.md

---

documentation/src/docs/deployment/run-local.md

1. Major content edits in the section Standalone
Fixes #3402

Issue 3402 : Updated section Running Pravega in Standalone Mode with SSL/TLS Enabled in  run-local.md

---

documentation/src/docs/deployment/manual-install.md

1.Bookkeeper version number changed from 4.7 to 4.7.3 in the document (manual-install.md):
2. Hyperlinks also edited
Fixes #3571, Closes #3571

Issue 3571: Bookkeeper version number changed in the document (manual-install.md)

---

documentation/src/docs/wire-protocol.md

1. Format Fix (Redesigned using Tables)
2. Many APIs were included
Fixes #3476, Closes #3476

Issue 3476: More APIs updated in the document  wire-protocol.md

---

HEADER
NOTICE
checkstyle/checkstyle.xml

* Adds a NOTICE file to state the coypright of the code contributed by Dell employees.
* Updates checkstyle rule to verify year of the copyright.
Subtask of #3508. This PR does not completely fix the issue.
There is no code change.
It should build regularly.

Issue 3508: Add NOTICE file and updates checkstyle rule.

---

documentation/src/docs/deployment/docker-swarm.md

1. Formats were fixed
2. @RaulGracia @shrids Please record your updates if any
Fixes #3473, Closes #3473

Issue 3473: Formats fixed in document docker-swarm.md

---

documentation/src/docs/security/pravega-security-configurations.md

This PR updates security configuration parameters documentation to reflect the latest set of parameters and (hopefully) describes the parameters better.
Addresses part 2 of issue #3599.
* Adds some missing params
* Removes/update the ones that have changed
* Updates descriptions with more details
* Organizes the document into two parts - distributed and standalone deployment mode
* Adds an additional column to reflect the pertinent feature 

Issue 3599: Part2 - Update documentation about security config parameters

---

controller/src/main/java/io/pravega/controller/server/SegmentHelper.java
controller/src/main/java/io/pravega/controller/store/host/HostControllerStore.java
controller/src/main/java/io/pravega/controller/store/host/InMemoryHostStore.java
controller/src/main/java/io/pravega/controller/store/host/ZKHostStore.java
controller/src/main/java/io/pravega/controller/store/stream/PravegaTableScope.java
controller/src/main/java/io/pravega/controller/store/stream/PravegaTablesScope.java
controller/src/main/java/io/pravega/controller/store/stream/PravegaTablesStoreHelper.java
controller/src/main/java/io/pravega/controller/store/stream/PravegaTablesStream.java
controller/src/main/java/io/pravega/controller/store/stream/PravegaTablesStreamMetadataStore.java
controller/src/test/java/io/pravega/controller/fault/SegmentContainerMonitorTest.java
controller/src/test/java/io/pravega/controller/mocks/SegmentHelperMock.java
controller/src/test/java/io/pravega/controller/server/SegmentHelperTest.java
controller/src/test/java/io/pravega/controller/store/stream/HostStoreTest.java
controller/src/test/java/io/pravega/controller/store/stream/PravegaTablesStreamTest.java
controller/src/test/java/io/pravega/controller/store/stream/StreamTest.java
shared/protocol/src/main/java/io/pravega/shared/segment/StreamSegmentNameUtils.java
shared/protocol/src/test/java/io/pravega/shared/segment/StreamSegmentNameUtilsTests.java

Currently the name scheme for table segments is `<scope>/table-<streamName>-<tableName>`.
The metrics generated on segment store for per segment generates metrics for these segments which can be visible to users as segments created under their scopes.
Instead, we have moved table segment name to `_system/_tables/<scope>{optional}/<stream>{optional}/<table-name>`
Fixes #3628 
The table name schema is changed such that all internal tables are created under system scope. 
StreamSegmentNameUtils has new utility functions to create fully qualified names for table segments which takes a scope and arbitrary number of tokens. Using these tokens, we compose the name such that its under …

Issue 3628 : Change Table Segment Name schema to include system scope

---

documentation/src/docs/metrics.md

Cherry picking PR #3485  into R0.5
Including the updated metrics.md
Closes #3475

 Issue 3707: R0.5 - Cherry pick #3485 (Metrics.md) 

---

documentation/src/docs/pravega-concepts.md

1. TOC included
2. Section on Connection Pooling included
Fixes #3655, Closes #3655

Issue 3655: TOC and section on connection pooling included in Pravega-concepts.md

---

segmentstore/server/src/test/java/io/pravega/segmentstore/server/logs/DurableLogTests.java

- Fixed a unit test that was assuming that acks coming from the DurableLog were issued only after all internal memory structures are updated. 
Fixes #3771.
- This unit test was assuming that acks from `DurableLog.add` were issued only after all internal memory structures were updated (the in-memory log, for example).
- However the DurableLog/OperationProcessor acks as soon as the operation is committed to Tier 1, and before it updates internal structures. As such, the in-memory log could be updated after a caller takes action on that ack.
- In this unit test, the action after the ack was to immediately truncate, which would have eliminated the operation from the log. However the operation was not there yet, …

Issue 3772: (SegmentStore) Fixed DurableLogTests.testTruncateWithoutRecovery

---

test/integration/src/test/java/io/pravega/test/integration/MetricsTest.java

Fixed the NullPointerException in the eventual assertions in the test.
Fixes #3725 
Added Null Pointer test into eventual assertion to avoid NPE.

Issue 3725: fixed the NullPointerException in the eventual assertions.

---

test/integration/src/test/java/io/pravega/test/integration/ControllerWatermarkingTest.java

Fixing build failure on merge with base branch. 
Fixes #3910 
Integration test to use WriterPosition as opposed to PositionImpl
Build and tests should pass.

Issue 3910: Fixing build failure on merge with base branch

---

test/system/src/main/java/io/pravega/test/system/framework/services/docker/PravegaControllerDockerService.java
test/system/src/main/java/io/pravega/test/system/framework/services/kubernetes/AbstractService.java
test/system/src/main/java/io/pravega/test/system/framework/services/marathon/PravegaControllerService.java
test/system/src/test/java/io/pravega/test/system/AbstractReadWriteTest.java
test/system/src/test/java/io/pravega/test/system/ControllerFailoverTest.java
test/system/src/test/java/io/pravega/test/system/MultiControllerTest.java

- Cherry picking PR #3956 into R0.5
* Fix AnnotatedNoRouteToHostException observed in docker swarm based Pravega system tests
Backport PR #3956, Issue #3440 
See #3956 
See #3956

Issue 3983: R0.5 - Cherry pick #3956(Issue 3440: Fix AnnotatedNoRouteToHostException observed in docker swarm based Pravega system tests)

---

client/src/main/java/io/pravega/client/netty/impl/ClientConnectionImpl.java
client/src/main/java/io/pravega/client/netty/impl/RawClient.java
client/src/main/java/io/pravega/client/segment/impl/SegmentInputStreamImpl.java
client/src/main/java/io/pravega/client/state/impl/RevisionedStreamClientImpl.java
client/src/main/java/io/pravega/client/state/impl/StateSynchronizerImpl.java
client/src/main/java/io/pravega/client/stream/impl/CheckpointState.java
client/src/main/java/io/pravega/client/stream/impl/EventStreamReaderImpl.java
client/src/main/java/io/pravega/client/stream/impl/ReaderGroupImpl.java
client/src/main/java/io/pravega/client/stream/impl/ReaderGroupStateManager.java
client/src/main/java/io/pravega/client/stream/impl/SegmentTransaction.java
client/src/main/java/io/pravega/client/stream/impl/StreamSegments.java
client/src/test/java/io/pravega/client/stream/impl/CheckpointStateTest.java

Add additional logs to Pravega client, no changes to functionality.
Fixes #4032 
Add additional logs to Pravega client, no changes to functionality.
All the tests should continue to pass as there are no changes to the functionality.

Issue 4032: Add additional logs to Pravega client.

---

client/src/main/java/io/pravega/client/segment/impl/EventSegmentReader.java
client/src/main/java/io/pravega/client/segment/impl/EventSegmentReaderImpl.java
client/src/main/java/io/pravega/client/segment/impl/SegmentInputStream.java
client/src/main/java/io/pravega/client/segment/impl/SegmentInputStreamImpl.java
client/src/test/java/io/pravega/client/stream/impl/OrdererTest.java
client/src/test/java/io/pravega/client/stream/mock/MockSegmentIoStreams.java

Improve the api of `fillBuffer` method in the reader.
Issue #4056 
**What the code does** 
This is related to a review comment that was suggested in PR #4082 
All the tests should pass, no changes to functionality.

Issue 4056: Improve the API for fillBuffer method in the reader.

---

checkstyle/checkstyle.xml
common/src/main/java/io/pravega/common/lang/Int96.java
common/src/main/java/io/pravega/common/util/ContinuationTokenAsyncIterator.java
controller/src/main/java/io/pravega/controller/server/SegmentStoreConnectionManager.java
controller/src/main/java/io/pravega/controller/server/rpc/auth/PasswordAuthHandler.java
controller/src/main/java/io/pravega/controller/store/host/ZKHostStore.java
controller/src/main/java/io/pravega/controller/store/stream/PravegaTablesScope.java
controller/src/main/java/io/pravega/controller/store/stream/PravegaTablesStoreHelper.java
controller/src/main/java/io/pravega/controller/store/stream/PravegaTablesStream.java
controller/src/main/java/io/pravega/controller/store/stream/Version.java
controller/src/main/java/io/pravega/controller/store/stream/VersionedMetadata.java
controller/src/main/java/io/pravega/controller/store/stream/ZKStreamMetadataStore.java
controller/src/main/java/io/pravega/controller/store/stream/records/CommittingTransactionsRecord.java
controller/src/main/java/io/pravega/controller/store/stream/records/HistoryTimeSeries.java
controller/src/main/java/io/pravega/controller/store/stream/records/HistoryTimeSeriesRecord.java
controller/src/main/java/io/pravega/controller/store/stream/records/RetentionSet.java
controller/src/main/java/io/pravega/controller/store/stream/records/SealedSegmentsMapShard.java
controller/src/main/java/io/pravega/controller/store/stream/records/StateRecord.java
controller/src/main/java/io/pravega/controller/store/stream/records/StreamCutReferenceRecord.java
controller/src/main/java/io/pravega/controller/store/stream/records/StreamSegmentRecord.java
controller/src/main/java/io/pravega/controller/task/Stream/RequestSweeper.java
gradle.properties
segmentstore/server/src/main/java/io/pravega/segmentstore/server/store/ServiceConfig.java
test/system/src/test/java/io/pravega/test/system/MetadataScalabilityTest.java

Signed-off-by: tison <wander4096@gmail.com>
Enable checkstyle rule `InvalidJavadocPosition` and fix conflicts.
Mainly get rid of dangling Javadoc comments.
Enable checkstyle rule `InvalidJavadocPosition` and fix conflicts.
`./gradlew checkstyleMain checkstyleTest` until no errors report.
ref #4106 
cc @fpj

Issue 4106: Enable checkstyle rule InvalidJavadocPosition

---

gradle.properties

* Changes version to 0.5.1 in r0.5 in preparation to release.
Fixes #4133
There is no code change, only a configuration change to update the version.
There is no functional change, so it should build as usual. Generated artifacts should have the new version in the names. Run `./gradlew install` to generate the artifacts.

Issue 4133: Change version to 0.5.1

---

controller/src/main/java/io/pravega/controller/server/rpc/auth/PasswordAuthHandler.java
controller/src/main/java/io/pravega/controller/server/rpc/auth/StrongPasswordProcessor.java
controller/src/test/java/io/pravega/controller/auth/PasswordValidatorTool.java
controller/src/test/java/io/pravega/controller/server/rpc/auth/StrongPasswordProcessorTest.java
shared/metrics/src/main/java/io/pravega/shared/metrics/MetricsConfig.java
shared/metrics/src/main/java/io/pravega/shared/metrics/RegistryConfigUtil.java

- Improve password handling inside Pravega.
Fixes #4161 
Improve the password handling inside `PasswordAuthHandler` by zeroing out the password

Issue 4161: Improve password handling based on static code analysis report.

---

documentation/src/docs/security/pravega-security-configurations.md

Update security configuration items list. 
Resolves #4184. 
* Adds missing configuration items. 
* Also, lists the corresponding environment variables that may be used instead of the properties. 
N/A.

Issue 4184: Update security configuration documentation

---

documentation/src/docs/rest/restapis.md
shared/controller-api/src/main/swagger/README.md

Ensure the autogenerated REST Api documentation is updated
Fixes #4197 
- Ensure the documentation reflects the latest code. e.g: ScaleMetadata information.
- Update the swagger2markup-cli jar version to 1.3.3.

Issue 4197:  Fix Controller REST api Documentation.

---

controller/src/main/java/io/pravega/controller/server/eventProcessor/requesthandlers/StreamRequestHandler.java

Added logging in StreamRequestHandler whenever an event is picked for processing and as processing completes successfully.
Fixes #4200
Adds logs in StreamRequestHandler before and after each events processing, logging the request type and request id
All existing tests should pass

Issue 4200: Additional logs in StreamRequestHandler before and after every event processing 

---

client/src/main/java/io/pravega/client/stream/EventWriterConfig.java

Change default status of connection pooling on append to off. 
This is to mitigate the impact of #4252 
Changes the default connection pooling value.

Issue 4252: Change connection pooling to default to off on append path.

---

segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/rocksdb/RocksDBCache.java

Cherry-pick #4320 to branch r0.6. 
Fixes #4321.
For details, please see #4320.
All tests should work as normal.

Issue 4319: Conflicting RocksDB config option in Windows (lib linkage problem)

---

segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/rocksdb/RocksDBCache.java

Cherry-picks #4326 to branch `0.6`.
Fixes #4327.
See details in #4326.
See details in #4326.

Issue 4325: Sporadic OOMKilled in Segment Store under moderate workloads

---

controller/src/main/java/io/pravega/controller/server/rpc/auth/AuthHandlerManager.java
controller/src/main/java/io/pravega/controller/server/rpc/auth/GrpcAuthHelper.java
controller/src/main/java/io/pravega/controller/server/rpc/auth/RESTAuthHelper.java
controller/src/main/java/io/pravega/controller/server/rpc/grpc/v1/ControllerServiceImpl.java
controller/src/test/java/io/pravega/controller/server/rpc/auth/ControllerGrpcAuthFocusedTest.java
shared/authplugin/src/main/java/io/pravega/auth/AuthException.java
test/integration/src/test/java/io/pravega/test/integration/BatchClientAuthTest.java

Cherry-picks #4336  to branch `r0.6`.
Fixes #4334. 
See details in #4336. 
See details in #4336.

Issue 4334: Fix auth and related exception handling (#4336)

---

controller/src/main/java/io/pravega/controller/store/stream/AbstractStreamMetadataStore.java
controller/src/main/java/io/pravega/controller/store/stream/PravegaTablesScope.java
controller/src/test/java/io/pravega/controller/store/stream/PravegaTablesStreamMetadataStoreTest.java

Cherry pick commit #4350  for issue 4349 into 0.6 branch
Fixes #4354
Cherry picks commit id cd9993b 
Everything should pass

Issue 4354: Complete partially created scopes before throwing ScopeExists (#4350)

---

client/src/main/java/io/pravega/client/security/auth/DelegationTokenProvider.java
client/src/main/java/io/pravega/client/security/auth/EmptyTokenProviderImpl.java
client/src/main/java/io/pravega/client/security/auth/JwtTokenProviderImpl.java
client/src/main/java/io/pravega/client/security/auth/StringTokenProviderImpl.java
client/src/main/java/io/pravega/client/segment/impl/AsyncSegmentInputStreamImpl.java
client/src/main/java/io/pravega/client/segment/impl/ConditionalOutputStreamImpl.java
client/src/main/java/io/pravega/client/segment/impl/SegmentMetadataClientImpl.java
client/src/main/java/io/pravega/client/segment/impl/SegmentOutputStreamImpl.java
client/src/test/java/io/pravega/client/security/auth/DelegationTokenProviderFactoryTest.java
client/src/test/java/io/pravega/client/security/auth/JwtTokenProviderImplTest.java
client/src/test/java/io/pravega/client/segment/impl/SegmentOutputStreamTest.java

Cherry-picks #4356 to r0.6.
Fixes #4352
See details in #4356
See details in #4356

Issue 4352: Turn retrieve token operation of DelegationTokenProvider asynchronous (#4356)

---

gradle.properties

Change pravega version in r0.6 branch from 0.6.1-snapshot to 0.6.1
Fixes #4364 
Change pravega version in r0.6 branch from 0.6.1-snapshot to 0.6.1

Issue 4364:  Change pravega version in r0.6 branch from 0.6.1-snapshot to 0.6.1

---

client/src/main/java/io/pravega/client/segment/impl/SegmentMetadataClientImpl.java
client/src/test/java/io/pravega/client/segment/impl/SegmentMetadataClientTest.java

Cherry-pick https://github.com/pravega/pravega/pull/4382 to r0.6
Fixes #4383 
See details in https://github.com/pravega/pravega/pull/4382 .
See details in https://github.com/pravega/pravega/pull/4382

Issue 4383: Fix exception handling during state synchronizer compaction. 

---

segmentstore/server/host/src/test/java/io/pravega/segmentstore/server/host/handler/PravegaRequestProcessorTest.java
segmentstore/server/src/main/java/io/pravega/segmentstore/server/reading/CompletableReadResultEntry.java
segmentstore/server/src/main/java/io/pravega/segmentstore/server/reading/FutureReadResultEntry.java
segmentstore/server/src/main/java/io/pravega/segmentstore/server/reading/FutureReadResultEntryCollection.java
segmentstore/server/src/main/java/io/pravega/segmentstore/server/reading/ReadResultEntryBase.java
segmentstore/server/src/main/java/io/pravega/segmentstore/server/reading/RedirectedReadResultEntry.java
segmentstore/server/src/main/java/io/pravega/segmentstore/server/reading/StreamSegmentReadIndex.java
segmentstore/server/src/main/java/io/pravega/segmentstore/server/reading/StreamSegmentReadResult.java
segmentstore/server/src/test/java/io/pravega/segmentstore/server/reading/ContainerReadIndexTests.java
segmentstore/server/src/test/java/io/pravega/segmentstore/server/reading/FutureReadResultEntryCollectionTests.java

Cherry-pick #4373
See #4373 for more details.
See #4373 for more details.
See #4373 for more details.

Issue 4369: (SegmentStore) Fix memory leak with Future Reads

---

client/src/main/java/io/pravega/client/segment/impl/SegmentMetadataClientImpl.java
client/src/main/java/io/pravega/client/segment/impl/SegmentOutputStreamImpl.java
client/src/test/java/io/pravega/client/segment/impl/SegmentMetadataClientTest.java
client/src/test/java/io/pravega/client/segment/impl/SegmentOutputStreamTest.java
segmentstore/server/host/src/test/java/io/pravega/segmentstore/server/host/handler/AppendProcessorAuthFailedTest.java
segmentstore/server/host/src/test/java/io/pravega/segmentstore/server/host/handler/PravegaRequestProcessorAuthFailedTest.java
shared/authplugin/src/main/java/io/pravega/auth/TokenException.java
shared/security/src/main/java/io/pravega/shared/security/token/JsonWebToken.java
shared/security/src/test/java/io/pravega/shared/security/token/JsonWebTokenTest.java
test/integration/src/test/java/io/pravega/test/integration/DelegationTokenTest.java

Cherry-picks #4391 to r0.6.
Fixes #4390. 
See details in #4391 
See details in #4391

Issue 4390: Ensure retries by client when delegation token expires (#4391)

---

config/config.properties
segmentstore/server/src/main/java/io/pravega/segmentstore/server/CacheManager.java
segmentstore/server/src/main/java/io/pravega/segmentstore/server/CacheUtilizationProvider.java
segmentstore/server/src/main/java/io/pravega/segmentstore/server/logs/DataFrameBuilder.java
segmentstore/server/src/main/java/io/pravega/segmentstore/server/logs/MemoryStateUpdater.java
segmentstore/server/src/main/java/io/pravega/segmentstore/server/logs/OperationProcessor.java
segmentstore/server/src/main/java/io/pravega/segmentstore/server/logs/Throttler.java
segmentstore/server/src/main/java/io/pravega/segmentstore/server/logs/ThrottlerCalculator.java
segmentstore/server/src/main/java/io/pravega/segmentstore/server/reading/ContainerReadIndex.java
segmentstore/server/src/test/java/io/pravega/segmentstore/server/CacheManagerTests.java
segmentstore/server/src/test/java/io/pravega/segmentstore/server/TestDurableDataLog.java
segmentstore/server/src/test/java/io/pravega/segmentstore/server/logs/MemoryStateUpdaterTests.java
segmentstore/server/src/test/java/io/pravega/segmentstore/server/logs/OperationProcessorTests.java
segmentstore/server/src/test/java/io/pravega/segmentstore/server/logs/ThrottlerCalculatorTests.java
segmentstore/server/src/test/java/io/pravega/segmentstore/server/logs/ThrottlerTests.java
segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/bookkeeper/BookKeeperConfig.java
segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/bookkeeper/BookKeeperLog.java
segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/bookkeeper/DebugLogWrapper.java
segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/bookkeeper/WriteQueue.java
segmentstore/storage/impl/src/test/java/io/pravega/segmentstore/storage/impl/bookkeeper/BookKeeperConfigTest.java
segmentstore/storage/impl/src/test/java/io/pravega/segmentstore/storage/impl/bookkeeper/BookKeeperLogTests.java
segmentstore/storage/impl/src/test/java/io/pravega/segmentstore/storage/impl/bookkeeper/WriteQueueTests.java
segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/DurableDataLog.java
segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/ThrottleSourceListener.java
segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/WriteSettings.java
segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/mocks/InMemoryDurableDataLog.java
segmentstore/storage/src/test/java/io/pravega/segmentstore/storage/DurableDataLogTestBase.java
segmentstore/storage/src/test/java/io/pravega/segmentstore/storage/WriteSettingsTests.java
segmentstore/storage/src/test/java/io/pravega/segmentstore/storage/mocks/InMemoryDurableDataLogTests.java

- Cherrypick #4402 to r.0.6
Cherrypick.
See #4402.
See #4402.

Issue 4399: BookKeeper Write Throttling (cherrypick to 0.6)

---

client/src/main/java/io/pravega/client/security/auth/JwtTokenProviderImpl.java
client/src/main/java/io/pravega/client/stream/impl/ControllerImpl.java
client/src/test/java/io/pravega/client/security/auth/JwtTokenProviderImplTest.java

Cherry-picks #4410 to r0.6
Fixes #4409. 
See details in #4410 
See details in #4410

Issue 4409: Cherry-pick PR 4410 to r0.6

---

bindings/src/main/java/io/pravega/storage/filesystem/FileSystemStorage.java
bindings/src/test/java/io/pravega/storage/filesystem/FileSystemMockTests.java

Fix bug in FileSystemStorage.doRead
Fix bug in FileSystemStorage.doRead
Fixes #4453
Fixes bug with offset.

Issue 4453: Fix bug in FileSystemStorage.doRead

---

NOTICE
docker/bookkeeper/Dockerfile
docker/bookkeeper/entrypoint.sh

Cherry picks PR #4420 (upgrades Bookeeper server from 4.7.3 to 4.8.2) to r0.6. 
Resolves #4425 
See details in PR #4420. 
See details in PR #4420.

Issue 3696: Cherry pick PR 4420 to r0.6

---

client/src/main/java/io/pravega/client/state/impl/StateSynchronizerImpl.java

* Lower log level on segment truncated
Fixes #4538
No function change

Issue 4538: Adjust log level on segment truncated

---

segmentstore/server/src/main/java/io/pravega/segmentstore/server/writer/AttributeAggregator.java

- Fixing logging verbosity when unable to persist root pointers in `AttributeAggregator` due to the segment having been deleted or merged into another.
Fixes #4574.
Logging as `INFO` for merged or deleted segments, keeping `ERROR` for anything else.
Code review. Build must pass.

Issue 4574: (SegmentStore) Fixing logging verbosity in AttributeAggregator

---

client/src/main/java/io/pravega/client/netty/impl/ClientConnectionImpl.java
client/src/main/java/io/pravega/client/netty/impl/FlowHandler.java
client/src/test/java/io/pravega/client/netty/impl/FlowHandlerTest.java
shared/metrics/src/main/java/io/pravega/shared/MetricsTags.java
shared/protocol/src/main/java/io/pravega/shared/NameUtils.java
shared/protocol/src/main/java/io/pravega/shared/protocol/netty/CommandEncoder.java
shared/protocol/src/test/java/io/pravega/shared/protocol/netty/CommandEncoderTest.java

Cherry pick PR #4598 to 0.7.
Fixes #4607.
See #4598 for details.
See #4598 for details.

Issue 4607: (0.7-CherryPick) Optimization of String splits for Metrics

---

client/src/main/java/io/pravega/client/segment/impl/EventSegmentReaderImpl.java
client/src/main/java/io/pravega/client/stream/impl/ControllerImpl.java
client/src/main/java/io/pravega/client/stream/impl/TransactionalEventStreamWriterImpl.java
client/src/test/java/io/pravega/client/segment/impl/EventSegmentReaderImplTest.java
client/src/test/java/io/pravega/client/stream/impl/TransactionalEventStreamWriterTest.java
controller/src/main/java/io/pravega/controller/server/ControllerService.java
controller/src/main/java/io/pravega/controller/server/eventProcessor/LocalController.java
controller/src/main/java/io/pravega/controller/server/rpc/grpc/v1/ControllerServiceImpl.java
controller/src/test/java/io/pravega/controller/timeout/TimeoutServiceTest.java

Cherry-pick PR #4599 to 0.7.
Fixes #4613.
See #4599 for details.
See #4599 for details.

Issue 4613: (0.7-CherryPick) Fix Transaction related logs.

---

client/src/main/java/io/pravega/client/stream/impl/ControllerImpl.java

Cherry-pick PR #4634 to 0.7.
Fixes #4633
See #4634 for details.
See #4634 for details.

Issue 4633: (CherryPick-0.7) Improve controller client logs #4634

---

controller/src/main/java/io/pravega/controller/server/eventProcessor/requesthandlers/CommitRequestHandler.java

Cherry-pick PR #4632 to 0.7.
Fixes #4631
See #4632 for details.
See #4632 for details.

Issue 4631: (CherryPick-0.7) Failed transactions metric incorrectly reported (#4632)

---

client/src/test/resources/logback-test.xml
client/src/test/resources/logback.xml
config/logback.xml
controller/src/conf/logback.xml
controller/src/test/resources/logback.xml
dist/conf/logback.xml
segmentstore/server/host/src/config/logback.xml
segmentstore/storage/impl/src/test/resources/logback.xml
segmentstore/storage/src/test/resources/logback.xml
test/integration/src/main/resources/logback-test.xml
test/integration/src/test/resources/logback.xml
test/system/src/test/resources/logback-test.xml

Cherry-picks PR #4626 to r0.7. 
Resolves #4347. 
See details in PR #4626.
See details in PR #4626.

Issue 4347: (CherryPick-0.7) Enable auto-reload of modified logging configuration at runtime (#4626)

---

controller/src/main/java/io/pravega/controller/server/ControllerService.java
controller/src/main/java/io/pravega/controller/store/stream/PravegaTablesStoreHelper.java
controller/src/test/java/io/pravega/controller/server/v1/ControllerServiceTest.java
controller/src/test/java/io/pravega/controller/store/stream/PravegaTablesStoreHelperTest.java

Cherry picks #4638 and #4639 into r0.7.
Fixes #4662 
Cherry picks

Issue 4662: Cherry pick 4638 and 4639 to 0.7 

---

gradle.properties

- Changed release to 0.7.1 in branch r0.7.
Fixes #4660.
Verify release says 0.7.1

Issue 4660: (0.7) Changed version to 0.7.1 in r0.7

---

common/src/main/java/io/pravega/common/TimeoutTimer.java
common/src/test/java/io/pravega/common/TimeoutTimerTest.java
segmentstore/server/src/main/java/io/pravega/segmentstore/server/SegmentStoreMetrics.java
segmentstore/server/src/main/java/io/pravega/segmentstore/server/logs/Throttler.java
segmentstore/server/src/test/java/io/pravega/segmentstore/server/SegmentStoreMetricsTests.java
segmentstore/server/src/test/java/io/pravega/segmentstore/server/logs/ThrottlerTests.java
shared/metrics/src/main/java/io/pravega/shared/MetricsTags.java
shared/metrics/src/test/java/io/pravega/shared/MetricsTagsTest.java

Cherry-picks #4273 .
Cherry-picks #4273 .
#4273 .

Issue 4273: Revised Throtting Metrics (Cherry-Pick). (#4646)

---

gradle.properties

Cherry-picks PR #4674 to r0.7.
Resolves #4673.  
See details in PR #4674.  
See details in PR #4674.

Issue 4673: (Cherry-pick-r0.7) Bump up versions of some of the dependencies (#4674)

---

client/src/main/java/io/pravega/client/stream/impl/PositionImpl.java
client/src/test/java/io/pravega/client/stream/impl/SerializationTest.java

Cherry-picks PR #4672 to r0.7.
Resolves #4669.  
See details in PR #4672.  
See details in PR #4672 .

Issue 4669: (Cherry-pick-r0.7) Fix serialization in PositionImpl. #4672

---

common/src/main/java/io/pravega/common/util/ReusableLatch.java
common/src/test/java/io/pravega/common/util/ReusableLatchTests.java
segmentstore/server/src/main/java/io/pravega/segmentstore/server/CacheManager.java
segmentstore/server/src/main/java/io/pravega/segmentstore/server/reading/StreamSegmentReadIndex.java
segmentstore/server/src/main/java/io/pravega/segmentstore/server/writer/SegmentAggregator.java
segmentstore/server/src/test/java/io/pravega/segmentstore/server/CacheManagerTests.java
segmentstore/server/src/test/java/io/pravega/segmentstore/server/reading/ContainerReadIndexTests.java
segmentstore/server/src/test/java/io/pravega/segmentstore/server/writer/SegmentAggregatorTests.java
segmentstore/server/src/test/java/io/pravega/segmentstore/server/writer/TestWriterDataSource.java
segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/cache/CacheStorage.java
segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/cache/DirectMemoryCache.java
segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/cache/NoOpCache.java
segmentstore/storage/src/test/java/io/pravega/segmentstore/storage/cache/DirectMemoryCacheTests.java

- Cherrypick #4702 / #4703 into r0.7.
- Cherrypick #4652 / #4711 into r0.7.
Fixes #4714.
- Cherrypick #4702 / #4703 into r0.7.
- Cherrypick #4652 / #4711 into r0.7.
Validate commit hashes.

Issue 4714: (0.7.1) Cherrypick 4702 and 4652 into r0.7

---

segmentstore/server/src/main/java/io/pravega/segmentstore/server/SegmentStoreMetrics.java
segmentstore/server/src/test/java/io/pravega/segmentstore/server/SegmentStoreMetricsTests.java
segmentstore/server/src/test/java/io/pravega/segmentstore/server/logs/ThrottlerTests.java

Incorporates #4706 into this release branch.
Fix failing test.
Removes metric conflict.
Execute the unit test and system build.

Issue 4717: Cherry Pick #4706 into r0.7.

---

docker/pravega/scripts/common.sh
docker/pravega/scripts/init_tier2.sh

Cherry pick the following two PRs into r0.7:
https://github.com/pravega/pravega/pull/4651
https://github.com/pravega/pravega/pull/4719
Fixes #4728 
Cherry pick the following two PRs into r0.7:
https://github.com/pravega/pravega/pull/4651
https://github.com/pravega/pravega/pull/4719
Validate commit hashes

Issue 4728: (0.7.1) Cherry pick 4642 (ECS TLS) into r0.7

---

segmentstore/server/src/main/java/io/pravega/segmentstore/server/logs/DurableLog.java
segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/bookkeeper/BookKeeperLog.java
segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/bookkeeper/DebugLogWrapper.java
segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/bookkeeper/LedgerMetadata.java
segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/bookkeeper/Ledgers.java
segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/bookkeeper/LogMetadata.java
segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/bookkeeper/LogReader.java
segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/bookkeeper/ReadOnlyLogMetadata.java
segmentstore/storage/impl/src/test/java/io/pravega/segmentstore/storage/impl/bookkeeper/BookKeeperLogTests.java
segmentstore/storage/impl/src/test/java/io/pravega/segmentstore/storage/impl/bookkeeper/LogMetadataTests.java
segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/DataLogCorruptedException.java

- Cherry pick #4724.
- Cherry pick #4431.
Fixes #4731.
- Cherry pick #4724.
- Cherry pick #4431.
Verify commits match the ones to master.

Issue 4731: (0.7) Cherry pick 4724 and 4431

---

client/src/main/java/io/pravega/client/stream/impl/PositionImpl.java
client/src/test/java/io/pravega/client/stream/impl/SerializationTest.java

Revert PR #4672 
Fixes #4738 
Revert changes to PositionImpl serialization.
Verify all system tests work with this change.

Issue 4738: Revert Position serialization fix

---

client/src/main/java/io/pravega/client/segment/impl/SegmentOutputStreamImpl.java
client/src/main/java/io/pravega/client/stream/impl/CheckpointState.java
client/src/main/java/io/pravega/client/stream/impl/EventStreamReaderImpl.java
client/src/main/java/io/pravega/client/stream/impl/Orderer.java
client/src/main/java/io/pravega/client/stream/impl/PositionImpl.java
client/src/test/java/io/pravega/client/stream/impl/EventStreamReaderTest.java
common/src/main/java/io/pravega/common/ExponentialMovingAverage.java
controller/src/test/java/io/pravega/controller/store/stream/StreamMetadataStoreTest.java
segmentstore/server/host/src/test/java/io/pravega/segmentstore/server/host/handler/AppendProcessorTest.java
segmentstore/storage/src/test/java/io/pravega/segmentstore/storage/noop/NoOpStorageUserDataWriteOnlyTests.java

Merge of https://github.com/pravega/pravega/pull/4707
into the r0.7 release branch.

Issue 4720: Reduce cpu use on client - r0.7

---

documentation/src/docs/watermarking.md
documentation/src/mkdocs.yml

Adding watermarking documentation.
Fixes #3316
Explains watermarking.

Issue 3316: added new watermarking doc

---

client/src/main/java/io/pravega/client/stream/impl/PositionImpl.java
client/src/test/java/io/pravega/client/stream/impl/SerializationTest.java

Cherry-picks PR #4746to r0.7.
Resolves #4669.  
See details in PR #4746.  
See details in PR #4746.

Issue 4669: (Cherry-pick-r0.7) Fix serialization in PositionImpl.(#4746)

---

gradle.properties

Changed version to 0.7.1 in gradle.properties.
Fixes #4772.
Changed version to 0.7.1 in gradle.properties.
Review change.

Issue 4772: (Release 0.7.1) Changed version to 0.7.1

---

bindings/src/test/java/io/pravega/storage/extendeds3/ExtendedS3SimpleStorageTests.java

Issue 5010: (SLTS) Fix leak in ExtendedS3SimpleStorageTests.
Fix leak in ExtendedS3SimpleStorageTests.
Fixes #5014 
Fix leak in ExtendedS3SimpleStorageTests.
Build with no leak.

Issue 5010: (SLTS) Fix leak in ExtendedS3SimpleStorageTests.

---

gradle.properties

Bumping version to 0.7.2.
Release process.
Bumping version to 0.7.2.
Code review. Build passes.

Release 0.7.2: Bump Version.

---

client/src/main/java/io/pravega/client/byteStream/impl/ByteStreamClientImpl.java
client/src/main/java/io/pravega/client/stream/impl/ControllerImpl.java
client/src/main/java/io/pravega/client/stream/impl/SegmentSelector.java
client/src/main/java/io/pravega/client/stream/impl/StreamSegments.java
client/src/main/java/io/pravega/client/stream/impl/TransactionalEventStreamWriterImpl.java
client/src/test/java/io/pravega/client/stream/impl/ClientFactoryTest.java
client/src/test/java/io/pravega/client/stream/impl/ControllerImplTest.java
client/src/test/java/io/pravega/client/stream/impl/SegmentSelectorTest.java
client/src/test/java/io/pravega/client/stream/impl/TransactionalEventStreamWriterTest.java
test/integration/src/test/java/io/pravega/test/integration/endtoendtest/EndToEndTruncationTest.java

Cherry-pick fixes for
-    Issue #4815 PR: #4814
-    Issue #4847 PR: #4848
Fixes #5036 
Cherry-pick the fixes from master to r0.7.
Verify commits match the ones to master.

Issue 5036: (Cherry-pick-r0.7) Cherry-pick 4815 and 4817

---

segmentstore/server/src/main/java/io/pravega/segmentstore/server/tables/SegmentKeyCache.java
segmentstore/server/src/test/java/io/pravega/segmentstore/server/tables/ContainerKeyCacheTests.java

Handling a situation where a Cache Eviction evicts a Cache Entry that was going to be a target of a Tail Index Migration.
Fixes #5038.
The Table Segment Key Cache is made up of two parts: Tail Section (for those updates that have not yet been fully indexed) and Cache Section (where we group multiple keys together and store them in the Cache).
During the migration process from Tail Index to full cache (`SegmentKeyCache.setLastIndexedOffset`), it is possible that a concurrent cache eviction evicts the Cache Entry that we have identified as a target for the migration. If this happens, an exception is thrown that prevents subsequent Keys from being migrated which could lead to a slight memory leak.
This change …

Issue 5038: (SegmentStore) Fixing a race condition in SegmentKeyCache.

---

client/src/main/java/io/pravega/client/segment/impl/SegmentOutputStreamImpl.java
client/src/test/java/io/pravega/client/segment/impl/SegmentOutputStreamTest.java
segmentstore/server/host/src/main/java/io/pravega/segmentstore/server/host/handler/AppendProcessor.java
segmentstore/server/host/src/test/java/io/pravega/segmentstore/server/host/handler/AppendProcessorTest.java
segmentstore/server/src/main/java/io/pravega/segmentstore/server/containers/StreamSegmentContainer.java

Issue 5081: Cherry-pick issue 5062 into r0.7 
Issue 5062: Handle SegmentSealedException during Append Setup (#5061)
Fixes: #5081 
Cherry-pick.
Code review.

Issue 5081: (R0.7) cherry-pick Issue (#5062) to r0.7

---

segmentstore/server/src/main/java/io/pravega/segmentstore/server/CacheManager.java
segmentstore/server/src/main/java/io/pravega/segmentstore/server/SegmentStoreMetrics.java
segmentstore/server/src/test/java/io/pravega/segmentstore/server/SegmentStoreMetricsTests.java

* Cherry pick #5092 
Fixes #5058 
Fixes #5058 

Issue 5058: Cache Manager Metrics Fix (#5092) [Cherry-Pick]

---

docker/pravega/scripts/init_kubernetes.sh

Signed-off-by: prabhaker24 <prabhaker.saxena@dell.com>
Cherry-pick PR #5148 to r0.8.
Fixes #5147 
See PR #5148 
See PR #5148

Issue 5147: Added check for service in init_kubernetes.sh script (#5148)

---

client/src/main/java/io/pravega/client/connection/impl/RawClient.java
client/src/main/java/io/pravega/client/security/auth/DelegationTokenProvider.java
client/src/main/java/io/pravega/client/security/auth/EmptyTokenProviderImpl.java
client/src/main/java/io/pravega/client/security/auth/JwtTokenProviderImpl.java
client/src/main/java/io/pravega/client/security/auth/StringTokenProviderImpl.java
client/src/main/java/io/pravega/client/segment/impl/AsyncSegmentInputStreamImpl.java
client/src/main/java/io/pravega/client/segment/impl/ConditionalOutputStreamImpl.java
client/src/main/java/io/pravega/client/segment/impl/SegmentMetadataClientImpl.java
client/src/main/java/io/pravega/client/segment/impl/SegmentOutputStreamImpl.java
client/src/main/java/io/pravega/client/tables/impl/TableSegmentImpl.java
client/src/test/java/io/pravega/client/security/auth/JwtTokenProviderImplTest.java
client/src/test/java/io/pravega/client/segment/impl/AsyncSegmentInputStreamTest.java
client/src/test/java/io/pravega/client/segment/impl/ConditionalOutputStreamTest.java
client/src/test/java/io/pravega/client/tables/impl/TableSegmentImplTest.java
controller/src/main/java/io/pravega/controller/server/SegmentHelper.java
controller/src/test/java/io/pravega/controller/server/SegmentHelperTest.java

Cherry-pick PR #5145 to r0.8.
Fixes #5144 
See PR #5145.
See PR #5145.

Issue 5144: Force token refresh when segment store indicates token expiry 

---

segmentstore/server/host/src/main/java/io/pravega/segmentstore/server/host/handler/PravegaRequestProcessor.java
segmentstore/server/host/src/test/java/io/pravega/segmentstore/server/host/handler/PravegaRequestProcessorTest.java
segmentstore/server/src/main/java/io/pravega/segmentstore/server/tables/TableBucketReader.java
segmentstore/server/src/test/java/io/pravega/segmentstore/server/tables/TableBucketReaderTests.java
segmentstore/server/src/test/java/io/pravega/segmentstore/server/tables/TableCompactorTests.java

Cherry pick PR #5156 into branch r0.8.
Fixes #5157.
See #5156.
See #5156.

Issue 5157: (SegmentStore) Cherry pick PR 5156 into branch r0.8

---

client/src/main/java/io/pravega/client/connection/impl/ConnectionPoolImpl.java
client/src/main/java/io/pravega/client/connection/impl/TcpClientConnection.java
client/src/main/java/io/pravega/client/control/impl/ControllerImpl.java
client/src/main/java/io/pravega/client/control/impl/ControllerResolverFactory.java
client/src/main/java/io/pravega/client/stream/impl/ClientFactoryImpl.java

Cherry pick PR #5146 into branch r0.8.
Fixes #5163 
See #5146 
See #5146

Issue 5163: Cheryypick PR #5146 into r0.8 

---

.travis.yml

Revert PR #4776 
Fixes #5172 
Revert the commit `d5016dbcf0cebde4ecc6bd04333996dec5611442`
The travis build passes

Issue 5172: Revert release branch snapshot stage fix

---

.travis.yml

Cherry-pick the commit to `r0.8` for reverting release branch snapshot stage fix
Fixes #5172 
Cherry-pick #5173 
The travis build passes

Issue 5172: (R0.8) Revert release branch snapshot stage fix

---

controller/src/main/java/io/pravega/controller/task/Stream/StreamMetadataTasks.java

Signed-off-by: Shivesh Ranjan shivesh.ranjan@gmail.com
Cherry picks 5181 for 0.8 branch. 
Fixes #5181
Fixes NPE in log message. 
Cherry pick from master to 0.8. all tests should pass

Issue 5189: Cherry pick #5181: Fix Null Pointer Exception in the log message to 0.8

---

client/src/main/java/io/pravega/client/connection/impl/RawClient.java
client/src/main/java/io/pravega/client/segment/impl/ConditionalOutputStreamImpl.java
client/src/test/java/io/pravega/client/connection/impl/RawClientTest.java
test/integration/src/test/java/io/pravega/test/integration/endtoendtest/EndToEndWithScaleTest.java

Cherry pick PR 5185 into r0.8
Fixes #5194 
See PR #5185 
See #5185 
See #5185

Issue 5194: Cherry pick PR 5185 into r0.8

---

controller/src/main/java/io/pravega/controller/server/eventProcessor/requesthandlers/CommitRequestHandler.java
controller/src/main/java/io/pravega/controller/store/stream/AbstractStreamMetadataStore.java
controller/src/main/java/io/pravega/controller/store/stream/InMemoryStream.java
controller/src/main/java/io/pravega/controller/store/stream/PersistentStreamBase.java
controller/src/main/java/io/pravega/controller/store/stream/PravegaTablesStream.java
controller/src/main/java/io/pravega/controller/store/stream/Stream.java
controller/src/main/java/io/pravega/controller/store/stream/StreamMetadataStore.java
controller/src/main/java/io/pravega/controller/store/stream/ZKStream.java
controller/src/test/java/io/pravega/controller/server/eventProcessor/ControllerEventProcessorTest.java
controller/src/test/java/io/pravega/controller/server/eventProcessor/RequestHandlersTest.java
controller/src/test/java/io/pravega/controller/store/stream/PravegaTablesStreamMetadataStoreTest.java
controller/src/test/java/io/pravega/controller/store/stream/StreamMetadataStoreTest.java
controller/src/test/java/io/pravega/controller/store/stream/StreamTestBase.java
controller/src/test/java/io/pravega/controller/task/Stream/StreamTransactionMetadataTasksTest.java

Cherry picks 5197 fix into r0.8 branch. 
Fixes #5205 
Cherry picks 5197 fix into r0.8 branch. 

Issue 5205: Limit number of transactions in a commit batch (#5198)

---

gradle.properties

Change version to 0.7.3 in r0.7
Fixes #5214.
Change version to 0.7.3 in r0.7
Change version to 0.7.3 in r0.7

Issue 5214: Change version to 0.7.3 in r0.7

---

segmentstore/server/src/main/java/io/pravega/segmentstore/server/reading/StreamSegmentReadIndex.java
segmentstore/server/src/test/java/io/pravega/segmentstore/server/reading/ContainerReadIndexTests.java

Fixed a deadlock situation in `StreamSegmentReadIndex` that can affect a recently merged Segment (into a parent one).
Fixes #5269.
Moved the invocation of `StreamSegmentReadIndex.createRedirectedReadResult` outside of the lock. This should be safe since all data it is working with is immutable at that point and there should be no risk in it changing while executing.
This eliminates one of the locks that were involved in the deadlock situation (see #5269 for details), which should prevent the deadlock from recurring.
New unit test added. This unit test would have hung (timed out due to deadlock) with the old code.

Issue 5269: (SegmentStore) Fixed a deadlock in StreamSegmentReadIndex.

---

segmentstore/server/src/main/java/io/pravega/segmentstore/server/reading/StreamSegmentReadIndex.java
segmentstore/server/src/test/java/io/pravega/segmentstore/server/reading/ContainerReadIndexTests.java

Cherry-pick #5269 into r0.8.
Fixes #5275.
Cherry-pick #5269 into r0.8.

Issue 5275: (R0.8) Cherry-pick #5269 into r0.8.

---

segmentstore/server/src/main/java/io/pravega/segmentstore/server/reading/StreamSegmentReadIndex.java
segmentstore/server/src/test/java/io/pravega/segmentstore/server/reading/ContainerReadIndexTests.java

Cherrypick #5269 into r0.7.
Fixes #5278.
Cherrypick #5269 into r0.7.

Issue 5278: (R0.7) Cherry-pick #5269 into r0.7.

---

.travis.yml

Signed-off-by: Brian Zhou <brian.zhou@emc.com>
Cherrypick #5273 into `r0.8`
Fixes #4775 
This will benefit to have `0.8.1-SNAPSHOT` artifacts.
Cherrypick #5273  into 0.8
**How to verify it** 
Build passes

Issue 4775: (R0.8) Cherry-pick #5273

---

common/src/main/java/io/pravega/common/concurrent/Futures.java
common/src/test/java/io/pravega/common/concurrent/FuturesTests.java
controller/src/main/java/io/pravega/controller/server/ControllerServiceStarter.java
controller/src/main/java/io/pravega/controller/server/SegmentHelper.java
controller/src/main/java/io/pravega/controller/util/Config.java
controller/src/test/java/io/pravega/controller/mocks/SegmentHelperMock.java
controller/src/test/java/io/pravega/controller/server/SegmentHelperTest.java
controller/src/test/java/io/pravega/controller/server/v1/ControllerServiceTest.java
controller/src/test/java/io/pravega/controller/task/Stream/IntermittentCnxnFailureTest.java

Cherry pick issue 4915 into r0.7
fixes #5311 
cherry picks timeouts to segment store 

Issue 5311: Cherry pick 4915 into r0.7

---

segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/bookkeeper/BookKeeperLogFactory.java
segmentstore/storage/impl/src/test/java/io/pravega/segmentstore/storage/impl/bookkeeper/BookKeeperLogTests.java

Cherry pick PR #5317 into r0.8.
Fixes #5334.
See #5317.
See #5317.

Issue 5334: Cherry-pick PR 5317 to branch r0.8

---

segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/bookkeeper/BookKeeperLogFactory.java
segmentstore/storage/impl/src/test/java/io/pravega/segmentstore/storage/impl/bookkeeper/BookKeeperLogTests.java

Cherry pick PR #5317 into r0.7.
Fixes #5333.
See #5317.
See #5317.

Issue 5333: Cherry-pick PR 5317 to branch r0.7

---

controller/src/main/java/io/pravega/controller/server/bucket/PeriodicWatermarking.java
controller/src/main/java/io/pravega/controller/server/eventProcessor/requesthandlers/DeleteStreamTask.java
controller/src/test/java/io/pravega/controller/server/bucket/WatermarkWorkflowTest.java
controller/src/test/java/io/pravega/controller/server/eventProcessor/RequestHandlersTest.java

Cherry pick #5341 and #4757 into r0.7
Fixes #5342 
cherry picks commits.

Issue 5342: Cherry pick 5341 and 4757 in r0.7

---

controller/src/main/java/io/pravega/controller/server/bucket/PeriodicWatermarking.java
controller/src/test/java/io/pravega/controller/server/bucket/WatermarkWorkflowTest.java

Cherry pick #5341 into r0.8
Fixes #5352 
cherry picks
all tests should pass

Issue 5341: Fix thread leak in controller (#5343)

---

client/src/main/java/io/pravega/client/connection/impl/ConnectionPoolImpl.java

Cherrypick Issue #5414 into r0.8
Fixes #5418 
PR: #5415 cherry picked into r0.8
see #5415

Issue 5418: Cherrypick Issue 5414 into r0.8

---

controller/src/main/java/io/pravega/controller/store/stream/PersistentStreamBase.java
controller/src/test/java/io/pravega/controller/store/stream/StreamMetadataStoreTest.java

Cherry pick #5417 
Fixes #5426 
cherry picks fix for #5417 
all tests should pass

Issue 5426: Cherry pick fix for 5417 - Transaction commit order should take 'limit' elements from ordered list 

---

gradle.properties

Change version on master branch to 0.10
Fix #5549 
Change version on master branch to 0.10

Issue 5549: Change version on master branch to 0.10.

---

controller/src/main/java/io/pravega/controller/task/Stream/StreamTransactionMetadataTasks.java
controller/src/main/java/io/pravega/controller/util/Config.java
controller/src/test/java/io/pravega/controller/task/Stream/StreamTransactionMetadataTasksTest.java

Cherry pick #5542 into 0.9
Fixes #5571 
Cherry picks fix for #5542 

Issue 5571: Cherry pick 5468, 5469 in 0.9

---

.github/workflows/gradle.yml
.travis.yml
README.md

Cherry pick PR #5563 in branch r0.9.
Fixes #5573.
See #5563.
See #5563.

Issue 5573: Cherry pick PR 5563 in branch r0.9

---

client/src/main/java/io/pravega/client/connection/impl/CommandEncoder.java
client/src/main/java/io/pravega/client/connection/impl/FlowHandler.java
client/src/main/java/io/pravega/client/connection/impl/FlowToBatchSizeTracker.java
client/src/main/java/io/pravega/client/connection/impl/TcpClientConnection.java
client/src/test/java/io/pravega/client/connection/impl/ClientConnectionTest.java
client/src/test/java/io/pravega/client/connection/impl/FlowToBatchSizeTrackerTest.java

Cherry-picks PR #5567 to `r0.9`.
Fixes #5594.
See #5567.
See #5567.

Issue 5594: Cherry-pick PR 5567 to r0.9

---

docker/bookkeeper/Dockerfile

Cherry-picks PR #5588 to r0.9.
Fixes #5592.
See #5588.
See #5588.

Issue 5592: Cherry-pick PR 5588 to branch r0.9

---

build.gradle
gradle/maven.gradle

Cherry-pick https://github.com/pravega/pravega/pull/5631
Cherry pick #5631 
Cherry pick #5631 

Cherry-pick 5631 to 0.9 branch

---

segmentstore/server/src/main/java/io/pravega/segmentstore/server/logs/SegmentMetadataUpdateTransaction.java
segmentstore/server/src/test/java/io/pravega/segmentstore/server/logs/ContainerMetadataUpdateTransactionTests.java
test/testcommon/src/main/java/io/pravega/test/common/TestUtils.java

Cherry-picks a fix for #5679  into 0.9.0 version 
Fixes #5681
See details in PR #5680 
See details in PR #5680

Issue 5681: Cherry-pick a fix for issue 5679

---

client/src/main/java/io/pravega/client/state/SynchronizerConfig.java

Cherry pick PR #5668 into `r0.9` branch
Fixes #5667 in 0.9.0 version 
See details in PR #5668 
See details in PR #5668

Issue 5675: Cherry pick of Issue Fix the default configuration for StateSyncrhonizer. (#5668)

---

controller/src/main/java/io/pravega/controller/eventProcessor/impl/EventProcessorGroupImpl.java
controller/src/main/java/io/pravega/controller/task/KeyValueTable/TableMetadataTasks.java
controller/src/main/java/io/pravega/controller/task/Stream/StreamMetadataTasks.java
controller/src/main/java/io/pravega/controller/task/Stream/StreamTransactionMetadataTasks.java
segmentstore/server/host/src/main/java/io/pravega/segmentstore/server/host/stat/AutoScaleProcessor.java

Cherrypick PR #5611 in r0.9 branch
Fixes #5648 
See #5611 
See #5611

Issue 5648: CherryPick PR 5611 into r0.9

---

client/src/main/java/io/pravega/client/admin/impl/ReaderGroupManagerImpl.java
client/src/main/java/io/pravega/client/control/impl/Controller.java
client/src/main/java/io/pravega/client/control/impl/ControllerImpl.java
client/src/main/java/io/pravega/client/control/impl/ModelHelper.java
client/src/main/java/io/pravega/client/stream/ReaderGroupConfig.java
client/src/test/java/io/pravega/client/admin/impl/ReaderGroupManagerImplTest.java
client/src/test/java/io/pravega/client/control/impl/ControllerImplTest.java
client/src/test/java/io/pravega/client/stream/mock/MockController.java
controller/src/main/java/io/pravega/controller/server/ControllerService.java
controller/src/main/java/io/pravega/controller/server/eventProcessor/LocalController.java
controller/src/main/java/io/pravega/controller/server/eventProcessor/requesthandlers/CreateReaderGroupTask.java
controller/src/main/java/io/pravega/controller/server/rest/ModelHelper.java
controller/src/main/java/io/pravega/controller/server/rpc/grpc/v1/ControllerServiceImpl.java
controller/src/main/java/io/pravega/controller/store/PravegaTablesScope.java
controller/src/main/java/io/pravega/controller/store/stream/PravegaTablesStreamMetadataStore.java
controller/src/main/java/io/pravega/controller/task/Stream/StreamMetadataTasks.java
controller/src/test/java/io/pravega/controller/server/ControllerServiceWithStreamTest.java
controller/src/test/java/io/pravega/controller/server/eventProcessor/LocalControllerTest.java
controller/src/test/java/io/pravega/controller/server/rpc/auth/ControllerGrpcAuthFocusedTest.java
controller/src/test/java/io/pravega/controller/server/rpc/grpc/v1/ControllerServiceImplTest.java
controller/src/test/java/io/pravega/controller/task/Stream/StreamMetadataTasksTest.java
shared/controller-api/src/main/proto/Controller.proto
test/integration/src/test/java/io/pravega/test/integration/StreamMetricsTest.java
test/integration/src/test/java/io/pravega/test/integration/controller/server/ControllerServiceTest.java

This PR is for cherry picking fix for Controller CreateReaderGroup API to branch r0.9
Fixes #5650
Fix the race condition with createReaderGroup API.
All unit, integration & system tests should pass

Issue 5650: Controller CreateReaderGroup API race condition fix - cherrypick to r0.9

---

client/src/main/java/io/pravega/client/connection/impl/FlowHandler.java
client/src/test/java/io/pravega/client/connection/impl/FlowHandlerTest.java
segmentstore/server/host/src/main/java/io/pravega/segmentstore/server/host/handler/AppendProcessor.java
segmentstore/server/host/src/test/java/io/pravega/segmentstore/server/host/handler/AppendProcessorTest.java
shared/protocol/src/main/java/io/pravega/shared/protocol/netty/FailingReplyProcessor.java
shared/protocol/src/test/java/io/pravega/shared/protocol/netty/FailingReplyProcessorTest.java

Cherry pick PR #5652
Fixes #5686 
See PR #5652 
See PR #5652

Issue 5686: Cherry pick PR 5652 into r0.9

---

common_server/src/test/java/io/pravega/common/util/btree/BTreeIndexTests.java
segmentstore/server/src/main/java/io/pravega/segmentstore/server/attributes/SegmentAttributeBTreeIndex.java
segmentstore/server/src/main/java/io/pravega/segmentstore/server/containers/MetadataCleaner.java
segmentstore/server/src/main/java/io/pravega/segmentstore/server/containers/StreamSegmentContainer.java
segmentstore/server/src/main/java/io/pravega/segmentstore/server/tables/ContainerKeyIndex.java
segmentstore/server/src/main/java/io/pravega/segmentstore/server/tables/ContainerTableExtensionImpl.java
segmentstore/server/src/main/java/io/pravega/segmentstore/server/tables/SegmentKeyCache.java
segmentstore/server/src/test/java/io/pravega/segmentstore/server/TestStorage.java
segmentstore/server/src/test/java/io/pravega/segmentstore/server/attributes/AttributeIndexTests.java
segmentstore/server/src/test/java/io/pravega/segmentstore/server/containers/MetadataCleanerTests.java
segmentstore/server/src/test/java/io/pravega/segmentstore/server/containers/StreamSegmentContainerTests.java
segmentstore/server/src/test/java/io/pravega/segmentstore/server/tables/ContainerKeyCacheTests.java
segmentstore/server/src/test/java/io/pravega/segmentstore/server/tables/ContainerTableExtensionImplTests.java
segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/AsyncStorageWrapper.java
segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/Storage.java
segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/cache/CacheFullException.java
segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/chunklayer/ChunkedSegmentStorage.java
segmentstore/storage/src/test/java/io/pravega/segmentstore/storage/AsyncStorageWrapperTests.java
segmentstore/storage/src/test/java/io/pravega/segmentstore/storage/chunklayer/ChunkedSegmentStorageTests.java

Cherry-pick PRs #5521, #5660 and #5654 into r0.9.
Fixes #5707.
Cherry-pick PRs #5521, #5660 and #5654 into r0.9

Issue 5707: Cherry-pick PRs #5521, #5660 and #5654 into r0.9

---

segmentstore/server/host/src/main/java/io/pravega/segmentstore/server/host/handler/AppendProcessor.java
segmentstore/server/host/src/test/java/io/pravega/segmentstore/server/host/handler/AppendProcessorTest.java
shared/protocol/src/main/java/io/pravega/shared/protocol/netty/WireCommands.java

Cherry-picks fix for #5677 into `r0.9` branch 
Fixes #5718
See details in #5678 
See details in #5678

Cherry-pick #5677 into r0.9 branch

---

client/src/main/java/io/pravega/client/byteStream/impl/ByteStreamClientImpl.java

Cherry-picks a second change as part of #5667 
Fixes #5675 
See details in #5691 
See details in #5691

Cherry-pick #5667 into r0.9 branch (second part)

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/documentation.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/ISSUE_TEMPLATE/question.md

This pull request introduces issue templates: bug report, feature request, documentation, and question.
Fixes #5761

Issue 5761: Enable issue templates

---

client/src/main/java/io/pravega/client/admin/impl/ReaderGroupManagerImpl.java
client/src/main/java/io/pravega/client/control/impl/Controller.java
client/src/main/java/io/pravega/client/control/impl/ControllerImpl.java
client/src/main/java/io/pravega/client/control/impl/ReaderGroupConfigRejectedException.java
client/src/main/java/io/pravega/client/stream/impl/ReaderGroupImpl.java
client/src/test/java/io/pravega/client/admin/impl/ReaderGroupManagerImplTest.java
client/src/test/java/io/pravega/client/control/impl/ControllerImplTest.java
client/src/test/java/io/pravega/client/stream/impl/ReaderGroupImplTest.java
client/src/test/java/io/pravega/client/stream/mock/MockController.java
client/src/test/java/io/pravega/client/stream/mock/MockStreamManager.java
controller/src/main/java/io/pravega/controller/server/ControllerService.java
controller/src/main/java/io/pravega/controller/server/eventProcessor/LocalController.java
controller/src/main/java/io/pravega/controller/server/eventProcessor/requesthandlers/DeleteReaderGroupTask.java
controller/src/main/java/io/pravega/controller/server/rpc/grpc/v1/ControllerServiceImpl.java
controller/src/main/java/io/pravega/controller/task/Stream/StreamMetadataTasks.java
controller/src/test/java/io/pravega/controller/server/eventProcessor/LocalControllerTest.java
controller/src/test/java/io/pravega/controller/task/Stream/StreamMetadataTasksTest.java
shared/controller-api/src/main/java/io/pravega/shared/controller/event/DeleteReaderGroupEvent.java
shared/controller-api/src/test/java/io/pravega/shared/controller/event/ControllerEventSerializerTests.java
test/integration/src/test/java/io/pravega/test/integration/StreamMetricsTest.java
test/integration/src/test/java/io/pravega/test/integration/controller/server/ControllerServiceTest.java
test/integration/src/test/java/io/pravega/test/integration/endtoendtest/EndToEndReaderGroupTest.java

The changes for solving the issues #5777 and #5776 are cherry picked.
Fixes #5784 
It contains the changes made in #5778 and #5779 
All tests should pass and build must succeed.

Issue 5784: Cherry pick fixes for issue 5776 and 5777 from master to r0.9

---

client/src/main/java/io/pravega/client/connection/impl/CommandEncoder.java
client/src/main/java/io/pravega/client/connection/impl/IoBuffer.java
client/src/main/java/io/pravega/client/control/impl/Controller.java
client/src/main/java/io/pravega/client/control/impl/ControllerImpl.java
client/src/main/java/io/pravega/client/control/impl/ModelHelper.java
client/src/main/java/io/pravega/client/segment/impl/ConditionalOutputStreamImpl.java
client/src/main/java/io/pravega/client/stream/impl/ReaderGroupImpl.java
client/src/main/java/io/pravega/client/stream/impl/ReaderGroupState.java
controller/src/main/java/io/pravega/controller/server/rpc/grpc/v1/ControllerServiceImpl.java

*  Ensure requestTags are propagated from the client to the Controller over GRPC for remaining APIs.
*  Ensure writer ids are logged by the ConditionalOutputStream, this will help to correlate the requests on the Segment store. and the client.
Fixes #5774 
*  Ensure `requestTags` are propagated from the client to the Controller over GRPC for remaining APIs.
*  Ensure writer ids are logged by the ConditionalOutputStream, this will help to correlate the requests on the Segment store. and the client.
All the existing tests should pass, simplify tracking of requests between the controller and client.

Issue 5774 : Ensure RequestTags are sent by the Client to Pravega Controller. 

---

client/src/main/java/io/pravega/client/control/impl/ControllerImpl.java

Fix log noise in GetCurrentSegments Controller API
Fixes #5797 
Fix log noise in GetCurrentSegments Controller API
No changes to functionality, all the tests should continue to pass.

Issue 5797: Fix log noise in GetCurrentSegments Controller API.

---

gradle.properties

Change pravegaVersion to 0.9.1-SNAPSHOT
Change pravegaVersion to 0.9.1-SNAPSHOT
Change pravegaVersion to 0.9.1-SNAPSHOT

Issue 5814: (r.0.9) Change pravegaVersion to 0.9.1-SNAPSHOT.

---

controller/src/test/java/io/pravega/controller/task/Stream/StreamTransactionMetadataTasksTest.java

Increased lease time for transaction and pings in StreamTransactionMetadataTasksTest.writerInitializationTest.
Fixes #5728.
We have found that the root cause for the sporadic failures of this test are due to the short lease times configured (100ms). Thus, in slow environments, it could be that the different steps in the test (e.g., between txn creation and ping) took longer and therefore they could be candidate to be aborted by `TimerWheelService`. Once aborted the transaction, the test naturally fails. This PR increases the lease timeouts for both transactions and pings so that this race condition does not happen even in slow environments.
Executed the following without problem:
`for …

Issue 5728: Sporadic failure in test StreamTransactionMetadataTasksTest.writerInitializationTest

---

client/src/main/java/io/pravega/client/segment/impl/SegmentOutputStreamImpl.java
client/src/test/java/io/pravega/client/segment/impl/SegmentOutputStreamTest.java

Cherry-pick PR #5735 into r0.9
Fixes #5818 
See PR #5735 
See PR #5735

Issue 5818: Cherry-pick PR 5735 into r0.9

---

client/src/main/java/io/pravega/client/admin/impl/ReaderGroupManagerImpl.java
client/src/main/java/io/pravega/client/control/impl/ControllerImpl.java
client/src/main/java/io/pravega/client/control/impl/ModelHelper.java
client/src/main/java/io/pravega/client/stream/ReaderGroupConfig.java
client/src/main/java/io/pravega/client/stream/impl/ReaderGroupImpl.java
client/src/main/java/io/pravega/client/stream/impl/ReaderGroupNotFoundException.java
client/src/test/java/io/pravega/client/admin/impl/ReaderGroupManagerImplTest.java
client/src/test/java/io/pravega/client/control/impl/ControllerImplTest.java
client/src/test/java/io/pravega/client/stream/impl/ReaderGroupImplTest.java
client/src/test/java/io/pravega/client/stream/impl/ReaderGroupStateManagerTest.java
client/src/test/java/io/pravega/client/stream/mock/MockController.java
client/src/test/java/io/pravega/client/stream/mock/MockStreamManager.java
controller/src/main/java/io/pravega/controller/server/eventProcessor/LocalController.java
controller/src/main/java/io/pravega/controller/server/eventProcessor/requesthandlers/CreateReaderGroupTask.java
controller/src/main/java/io/pravega/controller/task/Stream/StreamMetadataTasks.java
controller/src/test/java/io/pravega/controller/server/ControllerServiceWithStreamTest.java
controller/src/test/java/io/pravega/controller/server/eventProcessor/LocalControllerTest.java
controller/src/test/java/io/pravega/controller/server/rpc/auth/ControllerGrpcAuthFocusedTest.java
controller/src/test/java/io/pravega/controller/server/rpc/grpc/v1/ControllerServiceImplTest.java
controller/src/test/java/io/pravega/controller/store/stream/StreamMetadataStoreTest.java
controller/src/test/java/io/pravega/controller/task/Stream/StreamMetadataTasksTest.java
test/integration/src/test/java/io/pravega/test/integration/StreamMetricsTest.java
test/integration/src/test/java/io/pravega/test/integration/controller/server/ControllerServiceTest.java
test/integration/src/test/java/io/pravega/test/integration/endtoendtest/EndToEndReaderGroupTest.java

Cherry pick PR for issue 5693 to branch r0.9
Fixes #5824
All unit, integration and system tests should pass.

Issue 5824: Cherry pick fix for issue 5693 to r0.9

---

client/src/main/java/io/pravega/client/stream/RetentionPolicy.java
controller/src/main/java/io/pravega/controller/store/stream/AbstractStreamMetadataStore.java
controller/src/main/java/io/pravega/controller/store/stream/PersistentStreamBase.java
controller/src/main/java/io/pravega/controller/store/stream/Stream.java
controller/src/main/java/io/pravega/controller/store/stream/StreamCutComparison.java
controller/src/main/java/io/pravega/controller/store/stream/StreamMetadataStore.java
controller/src/main/java/io/pravega/controller/task/Stream/StreamMetadataTasks.java
controller/src/test/java/io/pravega/controller/rest/v1/ModelHelperTest.java
controller/src/test/java/io/pravega/controller/store/stream/StreamMetadataStoreTest.java
controller/src/test/java/io/pravega/controller/task/Stream/StreamMetadataTasksTest.java
controller/src/test/java/io/pravega/controller/task/Stream/ZkStreamMetadataTasksTest.java

Ref issue #5622 
Fixes #5868
Ref PR #5623 
All Unit, Integration, System tests should pass.

Issue 5868: Cherrypick fix for issue 5622 to branch r0.9

---

build.gradle
test/system/src/main/java/io/pravega/test/system/framework/Utils.java

Cherry pick system test configs to r0.9
Fix #5872 
Cherry pick

Issue 5872: Cherry pick system test configs(issue 5638, 5763) to r0.9 branch

---

controller/src/main/java/io/pravega/controller/store/stream/AbstractStreamMetadataStore.java
controller/src/main/java/io/pravega/controller/store/stream/PersistentStreamBase.java
controller/src/main/java/io/pravega/controller/store/stream/PravegaTablesStreamMetadataStore.java
controller/src/main/java/io/pravega/controller/store/stream/Stream.java
controller/src/main/java/io/pravega/controller/store/stream/records/EpochRecord.java
controller/src/test/java/io/pravega/controller/server/eventProcessor/PravegaTablesScaleRequestHandlerTest.java
controller/src/test/java/io/pravega/controller/server/eventProcessor/ScaleRequestHandlerTest.java
controller/src/test/java/io/pravega/controller/store/stream/TestStreamStoreFactory.java
controller/src/test/java/io/pravega/controller/store/stream/records/ControllerMetadataRecordSerializerTest.java
controller/src/test/java/io/pravega/controller/store/stream/records/RecordHelperTest.java

Cherry-pick PR for issue 5802 to r0.9
Fixes #5897
See #5802
All Unit, Integration and System Tests should pass.

Issue 5897 Cherry-pick fix for issue 5802 to branch r0.9

---

.github/workflows/gradle.yml

Wrong commit count number of the artifact name
Fixes #5947
Add a `fetch-depth` configuration
Build and all tests must pass. Such changes have done and verified in pravega/flink-connectors#492

Issue 5947: Wrong commit count number of the artifact name

---

segmentstore/contracts/src/main/java/io/pravega/segmentstore/contracts/Attributes.java
segmentstore/server/host/src/test/java/io/pravega/segmentstore/server/host/ExtendedS3IntegrationTest.java
segmentstore/server/host/src/test/java/io/pravega/segmentstore/server/host/FileSystemIntegrationTest.java
segmentstore/server/host/src/test/java/io/pravega/segmentstore/server/host/HDFSIntegrationTest.java
segmentstore/server/host/src/test/java/io/pravega/segmentstore/server/host/NonAppendExtendedS3IntegrationTest.java
segmentstore/server/src/main/java/io/pravega/segmentstore/server/containers/ContainerConfig.java
segmentstore/server/src/main/java/io/pravega/segmentstore/server/containers/StreamSegmentContainer.java
segmentstore/server/src/test/java/io/pravega/segmentstore/server/containers/StreamSegmentContainerTests.java
segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/chunklayer/ChunkedSegmentStorage.java
segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/chunklayer/ChunkedSegmentStorageConfig.java
segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/chunklayer/SnapshotInfo.java
segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/chunklayer/SnapshotInfoStore.java
segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/chunklayer/SystemJournal.java
segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/chunklayer/TruncateOperation.java
segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/chunklayer/WriteOperation.java
segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/metadata/BaseMetadataStore.java
segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/metadata/MetadataTransaction.java
segmentstore/storage/src/test/java/io/pravega/segmentstore/storage/chunklayer/ChunkedSegmentStorageTests.java
segmentstore/storage/src/test/java/io/pravega/segmentstore/storage/chunklayer/SystemJournalOperationsTests.java
segmentstore/storage/src/test/java/io/pravega/segmentstore/storage/chunklayer/SystemJournalTests.java
segmentstore/storage/src/test/java/io/pravega/segmentstore/storage/metadata/ChunkMetadataStoreTests.java
segmentstore/storage/src/test/java/io/pravega/segmentstore/storage/mocks/InMemorySnapshotInfoStore.java
shared/protocol/src/main/java/io/pravega/shared/NameUtils.java
shared/protocol/src/test/java/io/pravega/shared/NameUtilsTest.java

Cherry pick 5904 into 0.9.
Cherry pick 5904 into 0.9
Fixes #5961 
Cherry picks following changes
- Issue 5698: SLTS - SystemJournal should create new snapshots periodically ( #5904 )

Issue 5961: Cherry pick 5904 into 0.9 #5961

---

.codecov.yml
segmentstore/server/src/main/java/io/pravega/segmentstore/server/SegmentContainer.java
segmentstore/server/src/main/java/io/pravega/segmentstore/server/containers/ReadOnlySegmentContainer.java
segmentstore/server/src/main/java/io/pravega/segmentstore/server/containers/StreamSegmentContainer.java
segmentstore/server/src/main/java/io/pravega/segmentstore/server/logs/Throttler.java
segmentstore/server/src/main/java/io/pravega/segmentstore/server/logs/operations/CachedStreamSegmentAppendOperation.java
segmentstore/server/src/main/java/io/pravega/segmentstore/server/logs/operations/Operation.java
segmentstore/server/src/main/java/io/pravega/segmentstore/server/tables/ContainerTableExtensionImpl.java
segmentstore/server/src/test/java/io/pravega/segmentstore/server/containers/StreamSegmentContainerTests.java
segmentstore/server/src/test/java/io/pravega/segmentstore/server/store/StreamSegmentContainerRegistryTests.java
segmentstore/server/src/test/java/io/pravega/segmentstore/server/tables/TableContext.java

Cherry-pick #5999/#6000 into r0.9.
Fixes #6015.
Cherry-pick #5999/#6000 into r0.9.

Issue 6015: Cherry-pick #5999/#6000 into r0.9

---

documentation/src/docs/bindings.md

Fix the broken links.
Fix #6022

Issue 6022: Fix broken links

---

documentation/src/docs/getting-started.md

* Add note about serializers in the getting started guide.
Fixes #6029.
No code changes

Issue 6029: Add note about Serializers

---

client/src/main/java/io/pravega/client/stream/impl/CheckpointImpl.java

Cherry pick PR 5933 into r0.9
Fix #6071

Issue 6071: Cherry pick PR 5933 into r0.9

---

controller/src/main/java/io/pravega/controller/metrics/TransactionMetrics.java
controller/src/main/java/io/pravega/controller/server/SegmentHelper.java
controller/src/main/java/io/pravega/controller/server/SegmentStoreConnectionManager.java
controller/src/main/java/io/pravega/controller/server/eventProcessor/requesthandlers/CommitRequestHandler.java
controller/src/main/java/io/pravega/controller/task/Stream/StreamMetadataTasks.java
controller/src/test/java/io/pravega/controller/mocks/SegmentHelperMock.java
controller/src/test/java/io/pravega/controller/server/SegmentStoreConnectionManagerTest.java
segmentstore/server/host/src/main/java/io/pravega/segmentstore/server/host/handler/PravegaRequestProcessor.java
shared/metrics/src/main/java/io/pravega/shared/MetricsNames.java
shared/protocol/src/main/java/io/pravega/shared/protocol/netty/DelegatingRequestProcessor.java
shared/protocol/src/main/java/io/pravega/shared/protocol/netty/FailingReplyProcessor.java
shared/protocol/src/main/java/io/pravega/shared/protocol/netty/FailingRequestProcessor.java
shared/protocol/src/main/java/io/pravega/shared/protocol/netty/ReplyProcessor.java
shared/protocol/src/main/java/io/pravega/shared/protocol/netty/RequestProcessor.java
shared/protocol/src/main/java/io/pravega/shared/protocol/netty/WireCommandType.java
shared/protocol/src/main/java/io/pravega/shared/protocol/netty/WireCommands.java
test/integration/src/main/java/io/pravega/test/integration/demo/EndToEndAutoScaleUpWithTxnTest.java

(2-3 concise points about the changes in this PR. When committing this PR, the committer is expected to copy the content of this section to the merge description box)
(_e.g._, Fixes #666, Closes #1234)

Merge poc branch into perf test branch

---

segmentstore/server/src/test/java/io/pravega/segmentstore/server/logs/OperationProcessorTests.java
segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/bookkeeper/BookKeeperLog.java
segmentstore/storage/impl/src/test/java/io/pravega/segmentstore/storage/impl/bookkeeper/BookKeeperLogTests.java

Cherry-pick #6085 into r0.9.
Fixes #6097.
See #6085.
See #6085.

Issue 6097: Cherry-pick 6085 into r0.9

---

client/src/main/java/io/pravega/client/stream/EventStreamWriter.java
client/src/main/java/io/pravega/client/stream/EventWriterConfig.java

Improve EventWriter javadocs in case of connectivity failures.
Fixes #6100 
Improve EventWriter javadoc in case of connectivity failures.
All the existing test should continue to pass.

Issue 6100: Improve EventWriter javadocs.

---

cli/user/src/main/java/io/pravega/cli/user/Command.java
cli/user/src/main/java/io/pravega/cli/user/kvs/KeyValueTableCommand.java
cli/user/src/test/java/io/pravega/cli/user/TestUtils.java
cli/user/src/test/java/io/pravega/cli/user/kvs/KVTCommandsTest.java
cli/user/src/test/java/io/pravega/cli/user/kvs/SecureKVTCommandsTest.java

Fixing KVT CLI User commands that were previously broken and disabled in this feature branch.
Fixes #5942.
Re-enabled unit tests for these commands.
Fixed them to use the new KVT API.

Issue 5942: (KVT Beta2) Fixing CLI User Commands

---

documentation/src/docs/controller-service.md

Ensure Stream Tag option, which is now a part of the StreamConfiguration is updated as part of the Controller documentation.
Fixes #6147 
Ensure Stream Tag option, which is now a part of the StreamConfiguration is updated as part of the Controller documentation
Note: REST API related documentation is auto-generated and will be updated by PR #6143 

Issue 6147: Stream Tag documenation updates.

---

config/config.properties

Make CHUNKED_STORAGE default storage option.
Fixes #6121 
Make CHUNKED_STORAGE default storage option.

Issue 6121: SLTS - Make CHUNKED_STORAGE default.

---

README.md

1. Updates snapshot builds section with the new public token
2. Mentions alternative option for pre-release artifacts 
3. Fixes a broken link to Quick Start page 
Fixes #6132 

Issue 6132: Update README with new public token

---

gradle.properties

Signed-off-by: Sachin Joshi sachin.joshi@emc.com
Change pravegaVersion to 0.9.2-SNAPSHOT
Change pravegaVersion to 0.9.2-SNAPSHOT
Change pravegaVersion to 0.9.2-SNAPSHOT

Issue 6168: (r0.9) change version 0.9.2-SNAPSHOT

---

test/system/src/test/java/io/pravega/test/system/StreamsAndScopesManagementTest.java

Added a new system test for the new feature System Tags.
Fixes #6012 
Create the streams
Perform tests on empty and non-empty streams
Update streams with tags
Update a stream tag and verify if it is reflected
Seal and Delete the Stream
check if list streams is updated
All tests and system tests must pass

Issue 6012: System test for Stream Tags

---

segmentstore/server/src/main/java/io/pravega/segmentstore/server/logs/OperationProcessor.java
segmentstore/server/src/test/java/io/pravega/segmentstore/server/logs/OperationProcessorTests.java
segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/bookkeeper/BookKeeperLog.java

Cherry-pick PR #6220 to branch r0.9.
Fixes #6256.
See #6220.
See #6220.

Issue 6256: Cherry-pick PR #6220 to branch r0.9

---

segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/chunklayer/SystemJournal.java
segmentstore/storage/src/test/java/io/pravega/segmentstore/storage/chunklayer/SystemJournalOperationsTests.java

Cherry-pick 6252 to r0.9
Issue 6252: SLTS -Add robustness to system journal scan.
Instead of stopping journal scan at first gap, code should stop after gap greater than maxJournalWriteAttempts
Code should use optimistic approach to read journals and remove redundant calls
Fix unit test bug by properly injecting failures in doCreateWithContent and doCreate
Fixes #6262.
Cherry-pick https://github.com/pravega/pravega/pull/6253 to r0.9
build should pass

Issue 6262: Cherry-pick 6253 to r0.9

---

client/src/main/java/io/pravega/client/connection/impl/RawClient.java
client/src/main/java/io/pravega/client/stream/impl/ClientFactoryImpl.java
client/src/main/java/io/pravega/client/stream/impl/EventStreamWriterImpl.java
client/src/main/java/io/pravega/client/stream/impl/LargeEventWriter.java
client/src/test/java/io/pravega/client/stream/impl/EventStreamWriterTest.java
client/src/test/java/io/pravega/client/stream/impl/LargeEventWriterTest.java
common/src/main/java/io/pravega/common/util/RetriesExhaustedException.java

Add client side support for large appends
Fixes #6259
Implements large event support in the client
TODO: We need to add an integration test to make sure this works with the server implementation.

Issue 6259: Large Appends in Client

---

gradle.properties

Update pravegaVersion in gradle.properties to `0.11.0-SNAPSHOT`
Fixes #6300

Issue 6300: Update pravegaVersion in master to 0.11.0

---

gradle.properties

Update pravegaVersion for 0.10 branch
Fixes #6298

Issue 6298: pravega version change for 0.10 branch

---

docker/bookkeeper/entrypoint.sh

Signed-off-by: SrishT <Srishti.Thakkar@dell.com>
Cherry-pick PR #6222 to branch r0.10
Fixes #6318 
See #6222 
See #6222

Issue 6318: Cherry-pick PR #6222 to branch r0.10

---

segmentstore/server/src/main/java/io/pravega/segmentstore/server/containers/ContainerEventProcessorImpl.java
segmentstore/server/src/test/java/io/pravega/segmentstore/server/containers/StreamSegmentContainerTests.java

Cherry pick PR #6317 to r0.10.
Fixes #6323.
See #6317.
See #6317.

Issue 6323: Cherry pick PR 6317 to r0.10

---

test/system/src/main/java/io/pravega/test/system/framework/services/kubernetes/AbstractService.java

Signed-off-by: SrishT <Srishti.Thakkar@dell.com>
Cherry-pick PR #6267 to branch r0.10
Fixes #6328 
See #6267 
See #6267

Issue 6328: Cherry-pick PR #6267 to branch r0.10

---

controller/src/main/java/io/pravega/controller/server/eventProcessor/LocalController.java

Fix incorrect logs in Local Controller and few other classes.
Fixes #6338
Change log statements.

Issue 6338: Controller log improvements

---

docker/bookkeeper/entrypoint.sh

Signed-off-by: SrishT <Srishti.Thakkar@dell.com>
Cherry-pick PR #6222 to branch r0.10
Fixes #6318 
See #6222 
See #6222

Issue 6318: Cherry-pick PR #6222 to branch r0.10 (#6222)

---

controller/src/main/java/io/pravega/controller/server/SegmentHelper.java
controller/src/test/java/io/pravega/controller/server/SegmentHelperTest.java
docker/bookkeeper/entrypoint.sh
segmentstore/server/host/src/main/java/io/pravega/segmentstore/server/host/handler/PravegaRequestProcessor.java
segmentstore/server/host/src/test/java/io/pravega/segmentstore/server/host/handler/PravegaRequestProcessorTest.java
segmentstore/server/src/main/java/io/pravega/segmentstore/server/containers/ContainerEventProcessorImpl.java
segmentstore/server/src/test/java/io/pravega/segmentstore/server/containers/StreamSegmentContainerTests.java
segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/chunklayer/ChunkedSegmentStorage.java
segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/chunklayer/ConcatOperation.java
segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/chunklayer/SystemJournal.java
segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/chunklayer/TruncateOperation.java
segmentstore/storage/src/test/java/io/pravega/segmentstore/storage/chunklayer/SystemJournalTests.java
test/system/src/main/java/io/pravega/test/system/framework/services/kubernetes/AbstractService.java

Added entries for expected and failing replies for WireCommands.GetTableSegmentInfo in SegmentHelper.
Cherry pick for PR #6316 to r0.10
Fixes #6332 

Issue 6332: Cherry pick for PR #6316 to r0.10

---

common/src/main/java/io/pravega/common/concurrent/ExecutorServiceHelpers.java
common/src/main/java/io/pravega/common/concurrent/ThreadPoolScheduledExecutorService.java
common/src/test/java/io/pravega/common/concurrent/ExecutorServiceHelpersTests.java
segmentstore/server/src/test/java/io/pravega/segmentstore/server/SegmentStoreMetricsTests.java

Cherry-pick PR #6336 to branch r0.10.
Fixes #6352.
See #6336.
See #6336.

Issue 6352: Cherry-pick PR 6336 to branch r0.10.

---

controller/src/main/java/io/pravega/controller/server/eventProcessor/requesthandlers/StreamRequestHandler.java
controller/src/main/java/io/pravega/controller/server/eventProcessor/requesthandlers/UpdateReaderGroupTask.java
controller/src/test/java/io/pravega/controller/task/Stream/StreamMetadataTasksTest.java
controller/src/test/java/io/pravega/controller/task/Stream/ZkStreamMetadataTasksTest.java

Cherry pick for PR 6343 to r0.10
Fixes #6353
Cherry pick to r0.10

Issue 6353: Cherry pick for PR 6343 to r0.10

---

controller/src/main/java/io/pravega/controller/store/stream/PravegaTablesStream.java
controller/src/main/java/io/pravega/controller/store/stream/PravegaTablesStreamMetadataStore.java
controller/src/main/java/io/pravega/controller/store/stream/records/ActiveTxnRecord.java
controller/src/test/java/io/pravega/controller/mocks/SegmentHelperMock.java
controller/src/test/java/io/pravega/controller/server/eventProcessor/ControllerEventProcessorPravegaTablesStreamTest.java
controller/src/test/java/io/pravega/controller/server/eventProcessor/ControllerEventProcessorTest.java

Cherry pick PR #6355 to r0.10
Fixes #6358
Cherry pick PR 6355 to r0.10

Issue 6358: Cherry pick PR 6355 to r0.10

---

build.gradle
test/system/kubernetes/setupTestPod.sh
test/system/src/main/java/io/pravega/test/system/framework/services/kubernetes/K8SequentialExecutor.java

Cherry-pick PR #6342 to branch r0.10
Fixes #6363 
See #6342

Issue 6363: Cherry-pick PR #6342 to branch r0.10

---

segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/chunklayer/ChunkedSegmentStorage.java
segmentstore/storage/src/test/java/io/pravega/segmentstore/storage/chunklayer/ChunkedSegmentStorageMockTests.java
shared/metrics/src/main/java/io/pravega/shared/MetricsNames.java

Issue 6389: LTS - Report percentage used space.
Fixes #6389 
Report percentage value for space used.

Issue 6389: LTS - Report percentage used space.

---

segmentstore/server/src/main/java/io/pravega/segmentstore/server/tables/ContainerKeyIndex.java
segmentstore/server/src/main/java/io/pravega/segmentstore/server/tables/TableExtensionConfig.java
segmentstore/server/src/test/java/io/pravega/segmentstore/server/tables/ContainerKeyIndexTests.java
segmentstore/server/src/test/java/io/pravega/segmentstore/server/tables/TableExtensionConfigTests.java

Cherry-pick #6452 into r0.10.
Fixes #6489.
See #6452.
See #6452.

Issue 6489: Cherry-pick 6452 into r0.10

---

segmentstore/server/src/main/java/io/pravega/segmentstore/server/logs/DurableLog.java
segmentstore/server/src/main/java/io/pravega/segmentstore/server/logs/DurableLogConfig.java
segmentstore/server/src/main/java/io/pravega/segmentstore/server/logs/OperationProcessor.java
segmentstore/server/src/main/java/io/pravega/segmentstore/server/logs/ThrottlerCalculator.java
segmentstore/server/src/main/java/io/pravega/segmentstore/server/logs/ThrottlerPolicy.java
segmentstore/server/src/test/java/io/pravega/segmentstore/server/logs/OperationProcessorTests.java
segmentstore/server/src/test/java/io/pravega/segmentstore/server/logs/ThrottlerCalculatorTests.java
segmentstore/server/src/test/java/io/pravega/segmentstore/server/logs/ThrottlerTests.java

Cherry-pick PR #6508 to r0.10.
Fixes #6518.
See #6508.
See #6508.

Issue 6518: Cherry-pick PR 6508 to r0.10

---

.github/workflows/gradle.yml

Cherry-pick PR #6533 to branch r0.10.
Fixes #6535.
See #6533.
See #6533.

Issue 6535: Cherry-pick PR 6533 to branch r0.10

---

cli/admin/src/main/java/io/pravega/cli/admin/AdminCommand.java
cli/admin/src/main/java/io/pravega/cli/admin/AdminCommandState.java
cli/admin/src/main/java/io/pravega/cli/admin/segmentstore/tableSegment/GetTableSegmentEntryCommand.java
cli/admin/src/main/java/io/pravega/cli/admin/segmentstore/tableSegment/GetTableSegmentInfoCommand.java
cli/admin/src/main/java/io/pravega/cli/admin/segmentstore/tableSegment/ListTableSegmentKeysCommand.java
cli/admin/src/main/java/io/pravega/cli/admin/segmentstore/tableSegment/ModifyTableSegmentEntry.java
cli/admin/src/main/java/io/pravega/cli/admin/segmentstore/tableSegment/PutTableSegmentEntryCommand.java
cli/admin/src/main/java/io/pravega/cli/admin/segmentstore/tableSegment/SetSerializerCommand.java
cli/admin/src/main/java/io/pravega/cli/admin/segmentstore/tableSegment/TableSegmentCommand.java
cli/admin/src/main/java/io/pravega/cli/admin/serializers/AbstractSerializer.java
cli/admin/src/main/java/io/pravega/cli/admin/serializers/ContainerKeySerializer.java
cli/admin/src/main/java/io/pravega/cli/admin/serializers/ContainerMetadataSerializer.java
cli/admin/src/main/java/io/pravega/cli/admin/serializers/SltsKeySerializer.java
cli/admin/src/main/java/io/pravega/cli/admin/serializers/SltsMetadataSerializer.java
cli/admin/src/main/java/io/pravega/cli/admin/utils/AdminSegmentHelper.java
cli/admin/src/test/java/io/pravega/cli/admin/segmentstore/AbstractSegmentStoreCommandsTest.java
cli/admin/src/test/java/io/pravega/cli/admin/serializers/ContainerKeySerializerTest.java
cli/admin/src/test/java/io/pravega/cli/admin/serializers/ContainerMetadataSerializerTest.java
cli/admin/src/test/java/io/pravega/cli/admin/serializers/SerializerTest.java
cli/admin/src/test/java/io/pravega/cli/admin/serializers/SltsKeySerializerTest.java
cli/admin/src/test/java/io/pravega/cli/admin/serializers/SltsMetadataSerializerTest.java
controller/src/main/java/io/pravega/controller/server/SegmentHelper.java
segmentstore/server/src/main/java/io/pravega/segmentstore/server/containers/MetadataStore.java

Cherry-pick PR #6303 to r0.10.
Fixes #6529.
See #6303.
See #6303.

Issue 6529: Cherry pick PR #6303 to r0.10

---

cli/admin/src/test/java/io/pravega/cli/admin/AbstractAdminCommandTest.java

Signed-off-by: Bhupender-Y <Bhupender.Y@dell.com>
Cherry-pick PR #6548 to branch r0.10
N/A
N/A
N/A

Issue 6550 : Cherry-pick PR #6548 to branch r0.10

---

cli/admin/src/test/java/io/pravega/cli/admin/AbstractAdminCommandTest.java
gradle.properties

Signed-off-by: Bhupender-Y <Bhupender.Y@dell.com>
Cherry pick PR 6548 to branch r0.11
Fixes #6552 
N/A
N/A

Issue 6552 : Cherry pick PR 6548 to branch r0.11

---

segmentstore/server/src/main/java/io/pravega/segmentstore/server/tables/ContainerKeyIndex.java
segmentstore/server/src/test/java/io/pravega/segmentstore/server/containers/StreamSegmentContainerTests.java
segmentstore/server/src/test/java/io/pravega/segmentstore/server/tables/ContainerKeyIndexTests.java
segmentstore/server/src/test/java/io/pravega/segmentstore/server/tables/EntrySerializerTests.java

Cherry-pick #6538 to r0.11.
Fixes #6560.
See #6538.
See #6538.

Issue 6560: Cherry-pick 6538 to r0.11

---

segmentstore/server/src/main/java/io/pravega/segmentstore/server/SegmentStoreMetrics.java
segmentstore/server/src/main/java/io/pravega/segmentstore/server/logs/DurableLog.java
segmentstore/server/src/main/java/io/pravega/segmentstore/server/logs/OperationProcessor.java
segmentstore/server/src/test/java/io/pravega/segmentstore/server/SegmentStoreMetricsTests.java

Cherry-pick https://github.com/pravega/pravega/pull/6564 to r0.11.
Fixes #6590
See #6564 
See #6564

Issue 6590: Cherry-pick #6564 to r0.11.

---

segmentstore/server/src/test/java/io/pravega/segmentstore/server/SegmentStoreMetricsTests.java

Cherry-pick PR #6594 to r0.11
Fixes #6595 
See #6594
See #6594

Issue 6595: Cherry-pick #6594 to r0.11

---

segmentstore/server/src/main/java/io/pravega/segmentstore/server/SegmentStoreMetrics.java
segmentstore/server/src/main/java/io/pravega/segmentstore/server/logs/DurableLog.java
segmentstore/server/src/main/java/io/pravega/segmentstore/server/logs/OperationProcessor.java
segmentstore/server/src/test/java/io/pravega/segmentstore/server/SegmentStoreMetricsTests.java

Cherry pick PR #6602 to r0.11.
Fixes #6606.
See #6602
See #6602

Issue 6606: Cherry pick PR#6602 to r0.11

---

segmentstore/server/src/main/java/io/pravega/segmentstore/server/SegmentStoreMetrics.java
segmentstore/server/src/main/java/io/pravega/segmentstore/server/tables/ContainerKeyIndex.java
segmentstore/server/src/test/java/io/pravega/segmentstore/server/SegmentStoreMetricsTests.java
shared/metrics/src/main/java/io/pravega/shared/MetricsNames.java
shared/metrics/src/main/java/io/pravega/shared/MetricsTags.java
shared/metrics/src/test/java/io/pravega/shared/MetricsTagsTest.java

Cherry-pick #6517 to `r0.10`.
Fixes #6631.
See #6517.
See #6517.

Issue 6631: Cherry-pick PR 6517 to r0.10

---

segmentstore/server/src/main/java/io/pravega/segmentstore/server/tables/ContainerKeyIndex.java
segmentstore/server/src/test/java/io/pravega/segmentstore/server/tables/ContainerKeyIndexTests.java

Cherry-pick PR #6613 r0.10.
Fixes #6633.
See #6613.
See #6613.

Issue 6633: Cherry-pick PR 6613 r0.10

---

segmentstore/server/src/main/java/io/pravega/segmentstore/server/SegmentStoreMetrics.java
segmentstore/server/src/main/java/io/pravega/segmentstore/server/tables/ContainerKeyIndex.java
segmentstore/server/src/test/java/io/pravega/segmentstore/server/SegmentStoreMetricsTests.java
shared/metrics/src/main/java/io/pravega/shared/MetricsNames.java
shared/metrics/src/main/java/io/pravega/shared/MetricsTags.java
shared/metrics/src/test/java/io/pravega/shared/MetricsTagsTest.java

Cherry-pick https://github.com/pravega/pravega/pull/6517 to r0.11.
Fixes #6638.
See https://github.com/pravega/pravega/pull/6517.
See https://github.com/pravega/pravega/pull/6517.

Issue 6638: Cherry-pick PR 6517 to r0.11

---

segmentstore/server/src/main/java/io/pravega/segmentstore/server/ContainerEventProcessor.java
segmentstore/server/src/main/java/io/pravega/segmentstore/server/SegmentMetadata.java
segmentstore/server/src/main/java/io/pravega/segmentstore/server/containers/ContainerConfig.java
segmentstore/server/src/main/java/io/pravega/segmentstore/server/containers/ContainerEventProcessorImpl.java
segmentstore/server/src/main/java/io/pravega/segmentstore/server/containers/MetadataStore.java
segmentstore/server/src/main/java/io/pravega/segmentstore/server/containers/StorageEventProcessor.java
segmentstore/server/src/main/java/io/pravega/segmentstore/server/containers/StreamSegmentContainer.java
segmentstore/server/src/main/java/io/pravega/segmentstore/server/containers/StreamSegmentContainerMetadata.java
segmentstore/server/src/main/java/io/pravega/segmentstore/server/containers/StreamSegmentMetadata.java
segmentstore/server/src/main/java/io/pravega/segmentstore/server/logs/ContainerMetadataUpdateTransaction.java
segmentstore/server/src/test/java/io/pravega/segmentstore/server/containers/ContainerEventProcessorTests.java
segmentstore/server/src/test/java/io/pravega/segmentstore/server/containers/MetadataCleanerTests.java
segmentstore/server/src/test/java/io/pravega/segmentstore/server/containers/MetadataStoreTestBase.java
segmentstore/server/src/test/java/io/pravega/segmentstore/server/containers/StreamSegmentContainerTests.java

Cherry pick #6527 and #6628 to r0.10.
Fixes #6635.
See #6527 and #6628.
See #6527 and #6628.

Issue 6635: Cherry pick 6527 and 6628 to r0.10

---

segmentstore/server/src/main/java/io/pravega/segmentstore/server/containers/ContainerEventProcessorImpl.java
segmentstore/server/src/main/java/io/pravega/segmentstore/server/containers/MetadataStore.java
segmentstore/server/src/main/java/io/pravega/segmentstore/server/containers/StreamSegmentContainer.java
segmentstore/server/src/test/java/io/pravega/segmentstore/server/containers/MetadataCleanerTests.java
segmentstore/server/src/test/java/io/pravega/segmentstore/server/containers/MetadataStoreTestBase.java
segmentstore/server/src/test/java/io/pravega/segmentstore/server/containers/StreamSegmentContainerTests.java
segmentstore/server/src/test/java/io/pravega/segmentstore/server/logs/operations/OperationTestsBase.java

Cherry pick https://github.com/pravega/pravega/pull/6628 to r0.11.
Fixes #6642.
See #6628.
See #6628.

Issue 6642: Cherry pick 6628 to r0.11

---

cli/admin/src/main/java/io/pravega/cli/admin/controller/ControllerDescribeStreamCommand.java
cli/admin/src/test/java/io/pravega/cli/admin/controller/ControllerCommandsTest.java
cli/admin/src/test/java/io/pravega/cli/admin/controller/SecureControllerCommandsTest.java

Updated controller describe-stream command to use rest api to fetch the required details.
Fixes #6653
Changes to use rest api for getting stream details.
Admin-cli command `controller describe-stream <scope-name> <stream-name>` can be used to verify the same

Issue 6653: Pravega-Admin CLI controller describe-stream throws Exception accessing the metadata store

---

cli/admin/src/main/java/io/pravega/cli/admin/controller/ControllerDescribeStreamCommand.java
cli/admin/src/test/java/io/pravega/cli/admin/controller/ControllerCommandsTest.java
cli/admin/src/test/java/io/pravega/cli/admin/controller/SecureControllerCommandsTest.java

Cherry pick https://github.com/pravega/pravega/pull/6654 to r0.11.
Fixes https://github.com/pravega/pravega/issues/6680.
See https://github.com/pravega/pravega/pull/6654.
See https://github.com/pravega/pravega/pull/6654.

Issue 6680: Cherry pick 6654 to r0.11

---

segmentstore/storage/src/test/java/io/pravega/segmentstore/storage/chunklayer/ChunkedSegmentStorageMockTests.java

Cherry pick #6626 to r0.11
Fix #6695
See #6626
See #6626

Issue 6695: Cherry pick PR 6626 to r0.11

---

segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/chunklayer/TruncateOperation.java
segmentstore/storage/src/test/java/io/pravega/segmentstore/storage/chunklayer/ChunkedSegmentStorageTests.java
segmentstore/storage/src/test/java/io/pravega/segmentstore/storage/mocks/InMemorySimpleStorageTests.java

Cherry pick #6691 to r0.11
Fixes #6697 
See https://github.com/pravega/pravega/pull/6691
All tests must pass

Issue 6697: Cherry pick PR 6691 to r0.11

---

segmentstore/server/src/main/java/io/pravega/segmentstore/server/logs/Throttler.java
segmentstore/server/src/test/java/io/pravega/segmentstore/server/logs/ThrottlerTests.java

Cherry pick PR #6646 to r0.11
Fixes #6708
See #6646 
See #6646

Issue 6708: Cherry pick PR #6646 to r0.11

---

gradle.properties

Increment version to 0.11.1-SNAPSHOT
Closes #6729

Issue 6729: Bump version to 0.11.1-SNAPSHOT

---

common/src/main/java/io/pravega/common/concurrent/ThreadPoolScheduledExecutorService.java
common/src/test/java/io/pravega/common/concurrent/ThreadPoolScheduledExecutorServiceTest.java

Cherry pick [6715 ](https://github.com/pravega/pravega/pull/6715 ) to r0.11.
Fix issue [6714](https://github.com/pravega/pravega/issues/6714)
See  [6715 ](https://github.com/pravega/pravega/pull/6715 )
See [6715 ](https://github.com/pravega/pravega/pull/6715 )

Issue 6718: Cherry pick PR 6715 to r0.11 (#6718)

---

gradle.properties

Increment version to 0.10.3-SNAPSHOT
Closes #6728

Issue 6728: Bump version to 0.10.3-SNAPSHOT

---

controller/src/main/java/io/pravega/controller/store/client/StoreClientFactory.java
controller/src/test/java/io/pravega/controller/store/client/StoreClientFactoryTest.java

Cherry-Pick PR #6745 to r0.12
Fixes #6751
See #6745
See #6745

Issue 6751: Cherry Pick PR #6745 to r0.12

---

controller/src/main/java/io/pravega/controller/store/client/StoreClientFactory.java
controller/src/test/java/io/pravega/controller/store/client/StoreClientFactoryTest.java

Cherry-Pick PR #6745 to r0.11
Fixes #6756 
See #6745
See #6745

Issue 6756: Cherry Pick PR #6745 to r0.11

---

segmentstore/server/src/main/java/io/pravega/segmentstore/server/logs/DataFrame.java
segmentstore/server/src/main/java/io/pravega/segmentstore/server/logs/DataFrameReader.java
segmentstore/server/src/main/java/io/pravega/segmentstore/server/logs/RecoveryProcessor.java
segmentstore/server/src/test/java/io/pravega/segmentstore/server/logs/DataFrameReaderTests.java

Cherry pick PR #6741 to r0.12.
Fixes #6761.
See #6741.
See #6741.

Issue 6761: Cherry pick PR 6741 to r0.12 (#6741)

---

gradle/wrapper/gradle-wrapper.properties
segmentstore/server/src/main/java/io/pravega/segmentstore/server/logs/DataFrame.java
segmentstore/server/src/main/java/io/pravega/segmentstore/server/logs/DataFrameReader.java
segmentstore/server/src/main/java/io/pravega/segmentstore/server/logs/RecoveryProcessor.java
segmentstore/server/src/test/java/io/pravega/segmentstore/server/logs/DataFrameReaderTests.java

Cherry-pick PR #6741 to r0.11.
Fixes #6762.
See #6741.
See #6741.

Issue 6762: Cherry-pick PR 6741 to r0.11 (#6741)

---

gradle/wrapper/gradle-wrapper.properties
segmentstore/server/src/main/java/io/pravega/segmentstore/server/logs/DataFrame.java
segmentstore/server/src/main/java/io/pravega/segmentstore/server/logs/DataFrameReader.java
segmentstore/server/src/main/java/io/pravega/segmentstore/server/logs/RecoveryProcessor.java
segmentstore/server/src/test/java/io/pravega/segmentstore/server/logs/DataFrameReaderTests.java

Cherry-pick PR https://github.com/pravega/pravega/pull/6741 to r0.10.
Fixes https://github.com/pravega/pravega/issues/6763.
See https://github.com/pravega/pravega/issues/6741.
See https://github.com/pravega/pravega/issues/6741.

Issue 6763: Cherry-pick PR 6741 to r0.10

---

segmentstore/server/src/main/java/io/pravega/segmentstore/server/logs/OperationProcessor.java
segmentstore/server/src/test/java/io/pravega/segmentstore/server/logs/OperationProcessorTests.java

Cherry-pick PR #6758 to r0.12.
Fixes #6768.
See #6758.
See #6758.

Issue 6768: Cherry-pick PR 6758 to r0.12

---

segmentstore/server/src/main/java/io/pravega/segmentstore/server/writer/WriterConfig.java
segmentstore/server/src/test/java/io/pravega/segmentstore/server/writer/WriterConfigTest.java

Cherry-pick PR #6726 to r0.12
Fixes #6775 
See #6726 
See #6726

Issue 6775: Cherry-pick PR 6726 to r0.12

---

test/system/src/main/java/io/pravega/test/system/framework/services/kubernetes/AbstractService.java

Cherry pick https://github.com/pravega/pravega/pull/6733 to r0.12.
Fixes https://github.com/pravega/pravega/issues/6732.
See https://github.com/pravega/pravega/pull/6733.
See https://github.com/pravega/pravega/pull/6733.

Issue 6780: Cherry pick 6733 to r0.12

---

documentation/src/mkdocs.yml

Fix typo of bingings -> bindings in documentation
Fixes https://github.com/pravega/pravega/issues/6801.
Signed-off-by: David Maddison <david.maddison@dell.com>

Issue 6801: Fixed spelling of bindings

---

client/src/main/java/io/pravega/client/segment/impl/SegmentOutputStreamFactoryImpl.java
client/src/main/java/io/pravega/client/segment/impl/SegmentOutputStreamImpl.java
client/src/main/java/io/pravega/client/stream/EventWriterConfig.java
client/src/test/java/io/pravega/client/segment/impl/SegmentOutputStreamTest.java
common/src/main/java/io/pravega/common/util/Retry.java
common/src/test/java/io/pravega/common/util/RetryTests.java
segmentstore/server/src/test/java/io/pravega/segmentstore/server/containers/StreamSegmentContainerTests.java
shared/protocol/src/main/java/io/pravega/shared/protocol/netty/WireCommands.java
shared/protocol/src/test/java/io/pravega/shared/protocol/netty/WireCommandsTest.java

Signed-off-by: Shashwat Sharma <shashwat_sharma@dell.com>
This PR reverts changes from PR #6528 due to introduction of a regression.
Fixes #6836 
reverts changes from PR #6528 because of a regression found in a scenario

Issue 6836: Temporarily revert PR 6528

---

client/src/main/java/io/pravega/client/segment/impl/SegmentOutputStreamFactoryImpl.java
client/src/main/java/io/pravega/client/segment/impl/SegmentOutputStreamImpl.java
client/src/main/java/io/pravega/client/stream/EventWriterConfig.java
client/src/test/java/io/pravega/client/segment/impl/SegmentOutputStreamTest.java
common/src/main/java/io/pravega/common/util/Retry.java
common/src/test/java/io/pravega/common/util/RetryTests.java
shared/protocol/src/main/java/io/pravega/shared/protocol/netty/WireCommands.java
shared/protocol/src/test/java/io/pravega/shared/protocol/netty/WireCommandsTest.java

Cherry-pick PR #6837 to r0.12.
Fixes #6836 
See #6836 
See #6836

Issue 6843: Cherry-pick PR 6837 to r0.12

---

gradle.properties

Cherry-pick PR #6865 to r0.12
Fixes #6866

Issue 6866: Cherry-pick PR 6865 to r0.12

---

test/system/src/test/java/io/pravega/test/system/LargeEventTest.java

- Enabling large events in `EventStreamWriter` in `LargeEventTest.largeEventSimpleTest`
- Closes #6861 
- Enables large events in `EventWriterConfig` for `EventStreamWriter` so that LargeEvent logic may be executed.
- Successful system test run: pravega-development-system-tests-2/2275.

Issue 6861: Refactor LargeEventTest in System Tests

---

documentation/src/docs/getting-started/quick-start.md

Update quick start guide to 0.12.0
Fixes #6910

Issue 6910: Update quick start guide to 0.12.0

---

documentation/src/docs/getting-started/pravega-on-kubernetes-101.md

Update bookkeeper bookie pod names in k8s doc
Fixes #6914

Issue 6914: Update pods names in k8s doc

---

bindings/src/main/java/io/pravega/storage/filesystem/FileSystemStorageConfig.java
client/src/main/java/io/pravega/client/segment/impl/ConditionalOutputStreamImpl.java
client/src/main/java/io/pravega/client/tables/impl/KeyValueTableImpl.java
common/src/test/java/io/pravega/common/util/CompositeByteArraySegmentTests.java
gradle.properties
lombok.config
segmentstore/server/src/test/java/io/pravega/segmentstore/server/store/StreamSegmentStoreTestBase.java
segmentstore/storage/src/test/java/io/pravega/segmentstore/storage/AsyncStorageWrapperTests.java

Cherry-pick PR #6947 to r0.12.
Fixes #6952 
See #6947 
See #6947

Issue 6952: Cherry-pick #6947 to 0.12

---

bindings/src/main/java/io/pravega/storage/filesystem/FileSystemStorageConfig.java
client/src/main/java/io/pravega/client/segment/impl/ConditionalOutputStreamImpl.java
client/src/main/java/io/pravega/client/tables/impl/KeyValueTableImpl.java
common/src/test/java/io/pravega/common/util/CompositeByteArraySegmentTests.java
gradle.properties
lombok.config
segmentstore/server/src/test/java/io/pravega/segmentstore/server/store/StreamSegmentStoreTestBase.java
segmentstore/storage/src/test/java/io/pravega/segmentstore/storage/AsyncStorageWrapperTests.java

Cherry-pick PR #6947 to r0.13.
Fixes #6951 
See #6947 
See #6947

Issue 6951: Cherry-pick #6947 to r0.13

---

documentation/src/docs/recovery-procedures/enable-durable-data-log.md

Fix grammar typos in enable-durable-data-log.md
Fixes #6938

Issue 6938: Fix grammar typos in enable-durable-data-log.md

---

build.gradle
gradle.properties

Fixed the security related CVEs which were reported for 0.13.
Fixes https://github.com/pravega/pravega/issues/6985.
See https://github.com/pravega/pravega/issues/6985.
See https://github.com/pravega/pravega/issues/6985.

Issue 6987 : Cherry-pick PR 6986 to r0.13

---

test/integration/src/main/java/io/pravega/test/integration/compatibility/CompatibilityChecker.java

Signed-off-by: a6dulaleem [abdul.aleem1@dell.com](mailto:abdul.aleem1@dell.com)
Here in this PR we are trying to exercise Transaction related apis. 
Closes https://github.com/pravega/pravega/issues/6989
**How to test the changes**
1- start pravega standalone by ./gradlew startStandalone
2- test the compatibility by running ./gradlew compatibilityCheck -DcontrollerUri=tcp://localhost:9090

Issue 6989: Exercised transaction related APIs to check compatibility

---

client/src/main/java/io/pravega/client/stream/impl/CheckpointState.java
client/src/main/java/io/pravega/client/stream/impl/EventStreamReaderImpl.java
client/src/main/java/io/pravega/client/stream/impl/ReaderGroupImpl.java
client/src/test/java/io/pravega/client/stream/impl/CheckpointStateTest.java
client/src/test/java/io/pravega/client/stream/impl/ReaderGroupImplTest.java

see #6974 
Fixes #6995 
see #6974 

Issue 6995: Cherry-pick PR #6994 to r0.13

---

test/integration/src/main/java/io/pravega/test/integration/compatibility/CompatibilityChecker.java

Extends the capability of CompatibilityChecker class it generally does this :-
1. Adding method to write and read large events (16MB) and validating them.
2. Exercising Key Value tables related API and validating them.
3. Its trying to create some streams and putting stream tags and validating them.
Closes #6992 
Here in this PR  trying to extend the capability of compatibility checker class by exercising the KVTables, Large event and Stream tags related API.
created specific methods to exercise related api to each topics. 
1- start pravega standalone by ./gradlew startStandalone
2- test the compatibility by running ./gradlew compatibilityCheck -DcontrollerUri=tcp://localhost:9090

Issue 6992: Exercise KVTables, Large event and Streamtags related API.

---

controller/src/conf/controller.config.properties
controller/src/main/java/io/pravega/controller/task/Stream/StreamMetadataTasks.java
controller/src/main/java/io/pravega/controller/util/Config.java
controller/src/test/java/io/pravega/controller/task/Stream/StreamMetadataTasksTest.java

Add default retention policy per stream at global level
Fixes #7021 
See #7013 
See #7013

Issue 7021: Cherry-pick PR 7013 to r0.13

---

cli/admin/src/main/java/io/pravega/cli/admin/AdminCommand.java
cli/admin/src/main/java/io/pravega/cli/admin/dataRecovery/RecoverFromStorageCommand.java
cli/admin/src/main/java/io/pravega/cli/admin/utils/TableSegmentUtils.java
cli/admin/src/test/java/io/pravega/cli/admin/dataRecovery/DataRecoveryTest.java
docker/pravega/scripts/pravega_recovery_setup.sh
documentation/src/docs/recovery-procedures/lts-recovery-steps.md
documentation/src/mkdocs.yml
segmentstore/server/src/main/java/io/pravega/segmentstore/server/containers/ContainerRecoveryUtils.java
segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/bookkeeper/DebugBookKeeperLogWrapper.java
segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/DebugDurableDataLogWrapper.java

Pravega LTS based recovery onto r0.13 branch.
Fixes #7025 
See #7012 
See #7012

Issue 7025: Cherry-Pick PR #7012 to r0.13

---

cli/admin/src/main/java/io/pravega/cli/admin/segmentstore/FlushToStorageCommand.java
cli/admin/src/test/java/io/pravega/cli/admin/segmentstore/AbstractSegmentStoreCommandsTest.java

Cherry-pick PR #7041 to r0.13
Fixes #7045 
See #7041 
See #7041

Issue 7045: Cherry-pick PR 7041 to r0.13

---

cli/admin/src/main/java/io/pravega/cli/admin/dataRecovery/RecoverFromStorageCommand.java

Cherry-pick #7043 to r0.13
Fixes #7051
See #7043
See #7043

Issue 7051: Cherry-pick PR#7043 to r0.13

---

segmentstore/server/src/main/java/io/pravega/segmentstore/server/reading/StreamSegmentReadIndex.java

See #7029  
Fixes #7053 
See #7029  
See #7029

Issue 7053: Cherry-Pick PR #7029 to r0.13

---

cli/admin/src/main/java/io/pravega/cli/admin/dataRecovery/RecoverFromStorageCommand.java
cli/admin/src/test/java/io/pravega/cli/admin/dataRecovery/DataRecoveryTest.java

Cherry-pick PR #7050 
Fixes #7055 
See #7050 
See #7050

Issue 7055: Cherry-pick PR 7050 to r0.13

---

cli/admin/src/main/java/io/pravega/cli/admin/segmentstore/FlushToStorageCommand.java

Modifies FlushToStorageCommand.java to increase the flush to flush to storage timeout.
Fixes #7059 
Increases the flush to storage timeout.
While calling flush to storage via admin cli

Issue 7059: Increasing flush to storage timeout

---

cli/admin/src/main/java/io/pravega/cli/admin/segmentstore/FlushToStorageCommand.java

Modifies FlushToStorageCommand.java to increase the flush to flush to storage timeout.
Fixes #7066 
See #7060 
See #7060

Issue 7066: Cherry-Pick PR 7060 to r0.13

---

cli/admin/src/main/java/io/pravega/cli/admin/dataRecovery/RecoverFromStorageCommand.java
cli/admin/src/test/java/io/pravega/cli/admin/dataRecovery/DataRecoveryTest.java

Handles the case during validation in the recover-from-strorage CLI where we avoid querying for segments/chunks that we know have been deleted.
Fixes #7069 
See #7061
See #7061

Issue 7069: Cherry-pick PR#7061 to r0.13 

---

controller/src/main/java/io/pravega/controller/eventProcessor/impl/EventProcessorCell.java

cherry-pick PR #7103 to r0.13
#7106 
Add more logs in EventProcessorCell. It will help to identify the cause of failure if happens in any event processor. 
N/A

Issue 7106: Cherry-pick PR 7103 to r0.13

---

client/src/main/java/io/pravega/client/segment/impl/EventSegmentReaderImpl.java
client/src/main/java/io/pravega/client/stream/impl/EventStreamReaderImpl.java
client/src/main/java/io/pravega/client/stream/impl/Orderer.java

Add more logs in read path in client.
( Fixes #7143)
(Add more logs in read path in client. It will help to debug the read path of reader with extra information.)
N/A

Issue 7143 : Add more logs in read path in client.

---

client/src/main/java/io/pravega/client/segment/impl/EventSegmentReaderImpl.java
client/src/main/java/io/pravega/client/stream/impl/EventStreamReaderImpl.java

Cherry-pick PR #7142 to r0.13
( Closes #7145 )
(see #7142 )
N/A

Issue 7145 : Cherry-pick PR #7142 to r0.13

---

segmentstore/server/host/src/main/java/io/pravega/segmentstore/server/host/handler/IndexRequestProcessor.java

Add support for search offset in index segment using main segment offset.
Provide offset in index segment using main segment offset.
N/A

Add search for index offset.

---

client/src/main/java/io/pravega/client/batch/impl/BatchClientFactoryImpl.java
segmentstore/server/host/src/main/java/io/pravega/segmentstore/server/host/handler/IndexAppendProcessor.java
segmentstore/server/host/src/main/java/io/pravega/segmentstore/server/host/handler/IndexRequestProcessor.java
segmentstore/server/host/src/test/java/io/pravega/segmentstore/server/host/handler/IndexAppendProcessorTest.java
segmentstore/server/host/src/test/java/io/pravega/segmentstore/server/host/handler/IndexRequestProcessorTest.java

If index segment doesn't have any entry then return length of main segment as result. 
It will return length of main segment as result if index segment doesn't have any entry.

If index segment doesn't have any entry then return length of main segment as result

---

cli/admin/src/test/java/io/pravega/cli/admin/segmentstore/StorageCommandsTest.java

Signed-off-by: Kuldeep Kumar <kuldeep.kumar3@dell.com>
Adding new unit test
Add coverage
NA
NA

Adding new unit test

---

build.gradle
segmentstore/server/src/main/java/io/pravega/segmentstore/server/containers/StreamSegmentContainer.java
segmentstore/server/src/test/java/io/pravega/segmentstore/server/containers/StreamSegmentContainerTests.java
segmentstore/storage/impl/src/test/java/io/pravega/segmentstore/storage/impl/bookkeeper/BookKeeperLogTests.java
segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/mocks/InMemoryDurableDataLog.java

Code-coverage for Pravega Backup & Recover
Code-coverage for Pravega Backup & Recover
Adds unit tests for the Backup & Recover feature
Junit Runs

Adding unit tests for Pravega Backup & Recover

---

client/src/main/java/io/pravega/client/state/RevisionedStreamClient.java
client/src/main/java/io/pravega/client/state/impl/RevisionedStreamClientImpl.java
client/src/test/java/io/pravega/client/state/impl/RevisionedStreamClientTest.java
client/src/test/java/io/pravega/client/state/impl/SynchronizerTest.java
controller/src/test/java/io/pravega/controller/server/bucket/WatermarkWorkflowTest.java

Cherry-pick PR https://github.com/pravega/pravega/pull/7004 to r0.13
Fixes https://github.com/pravega/pravega/issues/7234
(see https://github.com/pravega/pravega/pull/7004 )
N/A

Issue 7234: Cherry-pick PR #7004 to r0.13

---

client/src/main/java/io/pravega/client/ClientConfig.java
client/src/main/java/io/pravega/client/segment/impl/SegmentOutputStreamImpl.java
client/src/main/java/io/pravega/client/segment/impl/ServerTimeoutException.java
client/src/main/java/io/pravega/client/state/impl/RevisionedStreamClientImpl.java
client/src/main/java/io/pravega/client/stream/impl/ClientFactoryImpl.java
client/src/main/java/io/pravega/client/stream/impl/EventStreamReaderImpl.java
client/src/test/java/io/pravega/client/segment/impl/SegmentOutputStreamTest.java
client/src/test/java/io/pravega/client/state/impl/RevisionedStreamClientTest.java
client/src/test/java/io/pravega/client/stream/impl/EventStreamReaderTest.java
common/src/main/java/io/pravega/common/concurrent/Futures.java
common/src/test/java/io/pravega/common/concurrent/FuturesTests.java
test/system/src/main/java/io/pravega/test/system/framework/Utils.java
test/system/src/test/java/io/pravega/test/system/BookieFailoverTest.java
test/system/src/test/java/io/pravega/test/system/MultiReaderTxnWriterWithFailoverTest.java
test/system/src/test/java/io/pravega/test/system/MultiReaderWriterWithFailOverTest.java
test/system/src/test/java/io/pravega/test/system/ReadTxnWriteAutoScaleWithFailoverTest.java

Cherry-pick PR https://github.com/pravega/pravega/pull/7177 and  https://github.com/pravega/pravega/pull/7211 to r0.13
Fixes https://github.com/pravega/pravega/issues/7237
(see https://github.com/pravega/pravega/pull/7177 and https://github.com/pravega/pravega/pull/7211 )
N/A

Issue 7237: cherrypick #7177 and #7211 to r0.13

---

docker/pravega/scripts/init_kubernetes.sh

Cherry-pick PR #7174 
Fixes #7241 
See #7174
N/A

Issue 7241: Cherry-pick PR #7174 to r0.13

---

cli/admin/src/test/java/io/pravega/cli/admin/segmentstore/StorageCommandsTest.java

Addressing review comment
Addressing review comment
Addressing review comment

Addressing review comment

---

client/src/main/java/io/pravega/client/batch/impl/BatchClientFactoryImpl.java
client/src/test/java/io/pravega/client/batch/impl/BatchClientImplTest.java

Fixes to to issues uncovered in review of 
https://github.com/pravega/pravega/pull/7230/

Fixes for PDP-55 branch

---

segmentstore/server/src/main/java/io/pravega/segmentstore/server/containers/EpochInfo.java
segmentstore/server/src/main/java/io/pravega/segmentstore/server/containers/StreamSegmentContainer.java
segmentstore/server/src/main/java/io/pravega/segmentstore/server/containers/StreamSegmentContainerMetadata.java
segmentstore/server/src/main/java/io/pravega/segmentstore/server/writer/AttributeAggregator.java
segmentstore/server/src/test/java/io/pravega/segmentstore/server/containers/StreamSegmentContainerMetadataTests.java
segmentstore/server/src/test/java/io/pravega/segmentstore/server/containers/StreamSegmentContainerTests.java

Cherry-pick PR #7313 to r0.14
Fixes #7315 
See #7313 
See #7314

Issue #7315: Cherry-pick PR #7313 to r0.14

---

documentation/src/docs/gateways.md
documentation/src/docs/join-community.md
documentation/src/docs/releasenotes.md
documentation/src/docs/roadmap.md
documentation/src/mkdocs.yml

Updates the Pravega roadmap page and fixes few minor points in the documentation.
Fixes #7319.
Updates the Pravega roadmap page and fixes few minor points in the documentation.
n/a

Issue 7319: Update Pravega roadmap

---

gradle.properties
test/integration/src/test/java/io/pravega/test/integration/IdleSegmentTest.java

This PR is Upgrading the following dependencies in the pravega
Dependency | Current Version | CVE fix Version
-- | -- | --
apacheAvro | 1.11.1 | 1.11.3
jackson| 2.14.1 | 2.15.3
marathonClient | 0.6.2 | 0.6.3
netty | 4.1.94.Final | 4.1.100.Final
to fix https://github.com/pravega/pravega/issues/7330
The code is just upgrading the version of pravega dependencies in gradle properties
Run the entire system test

Issue 7330: Update pravega dependencies version to fix the CVEs.

---

gradle.properties
test/integration/src/test/java/io/pravega/test/integration/IdleSegmentTest.java

Cherry-pick PR https://github.com/pravega/pravega/pull/7331 to r0.14
Fixes https://github.com/pravega/pravega/issues/7332
(see https://github.com/pravega/pravega/pull/7331)
N/A

Issue 7330: Cherry-pick PR #7331 to r0.14

---

test/integration/src/test/java/io/pravega/test/integration/SegmentReaderTest.java

Add an integration test for SegmentReader.
Closes #7370 
This integration test will verify the segment reader functionality.
Integration test should be successful.

Issue 7370: Add an integration test for SegmentReader.

---

client/src/main/java/io/pravega/client/segment/impl/EventSegmentReader.java
client/src/main/java/io/pravega/client/segment/impl/EventSegmentReaderImpl.java
client/src/main/java/io/pravega/client/segment/impl/SegmentInputStream.java
client/src/main/java/io/pravega/client/segment/impl/SegmentInputStreamImpl.java
client/src/main/java/io/pravega/client/stream/SegmentReader.java
client/src/main/java/io/pravega/client/stream/SegmentReaderSnapshot.java
client/src/main/java/io/pravega/client/stream/SegmentReaderSnapshotInternal.java
client/src/main/java/io/pravega/client/stream/impl/SegmentReaderImpl.java
client/src/main/java/io/pravega/client/stream/impl/SegmentReaderSnapshotImpl.java
client/src/main/java/io/pravega/client/stream/impl/SegmentReaderSnapshotInternal.java
client/src/test/java/io/pravega/client/stream/impl/OrdererTest.java
client/src/test/java/io/pravega/client/stream/impl/SegmentReaderTest.java
client/src/test/java/io/pravega/client/stream/mock/MockSegmentIoStreams.java

Add an API to get current reader info in SegmentReader.
(Closes #7368)
Add an API in SegmentReader which will give current reader position and weather it reaches to end of segment or not.
All test cases related to this functionality should success.

Issue 7368: Add an API to get current reader info in SegmentReader.

---

gradle.properties

As we have created a release branch, we need to bump up the version in gradle.properties.
Fixes #7373 
Bump up the pravega master version.
Build should have higher version.

Issue 7373: Bump up master version.

---

test/integration/src/test/java/io/pravega/test/integration/SegmentReaderTest.java

Add an integration test for SegmentReaderSnapshot.
Closes #7378 
Add an integration test for SegmentReaderSnapshot which will verify the segment reader snapshot functionality.
Integration test should be successful.

Issue 7378: Add an integration test for SegmentReaderSnapshot.

---

gradle.properties

Cherry-pick PR #7345 to r0.14
Fixes #7381 
See #7345
See #7345

Issue 7381: Cherry-pick PR #7345 to r0.14

---

client/src/main/java/io/pravega/client/segment/impl/EventSegmentReader.java
client/src/main/java/io/pravega/client/segment/impl/EventSegmentReaderImpl.java
client/src/main/java/io/pravega/client/stream/impl/Orderer.java
client/src/test/java/io/pravega/client/segment/impl/SegmentInputStreamTest.java

Cherry pick PR #7342 to r0.14
Fixes #7383 
Cherry pick PR #7342 to r0.14
NA

Issue 7383: Cherry pick PR #7342 to r0.14

---

client/src/main/java/io/pravega/client/batch/impl/BatchClientFactoryImpl.java
client/src/main/java/io/pravega/client/connection/impl/FlowHandler.java
client/src/main/java/io/pravega/client/connection/impl/RawClient.java
client/src/main/java/io/pravega/client/segment/impl/AsyncSegmentInputStreamImpl.java
client/src/test/java/io/pravega/client/batch/impl/BatchClientImplTest.java
client/src/test/java/io/pravega/client/connection/impl/FlowHandlerTest.java
client/src/test/java/io/pravega/client/stream/mock/MockConnectionFactoryImpl.java
common/src/main/java/io/pravega/common/concurrent/Futures.java
test/integration/src/main/java/io/pravega/test/integration/utils/LocalServiceStarter.java

Cherry pick PR #7323  to r0.14
Fixes #7385 
Cherry pick PR #7323  to r0.14
See #7323

Issue 7385: Cherry pick PR #7323 to r0.14

---

test/integration/src/test/java/io/pravega/test/integration/AppendTest.java
test/integration/src/test/java/io/pravega/test/integration/ReadTest.java

Cherry-pick PR #7371 to r0.14
Fixes #7402
See #7371
See #7371

Issue 7402: Cherry-pick PR #7371 to r0.14

---

segmentstore/server/src/main/java/io/pravega/segmentstore/server/containers/StreamSegmentContainer.java
segmentstore/server/src/test/java/io/pravega/segmentstore/server/containers/StreamSegmentContainerTests.java

Cherry pick PR https://github.com/pravega/pravega/pull/7356 to r0.14
Fixes https://github.com/pravega/pravega/issues/7412
Cherry pick PR https://github.com/pravega/pravega/pull/7356 to r0.14
See https://github.com/pravega/pravega/pull/7356

Issue 7412: Cherry pick PR #7356 to r0.14

---

test/system/src/test/java/io/pravega/test/system/SegmentReaderTest.java

Add a system test to verify segment reader functionality.
Fixes #7376 
Add a system test to verify segment reader functionality.
System test should pass.

Issue 7376: Add a system test to verify segment reader functionality.
