- test/system/src/main/java/io/pravega/test/system/framework/services/docker/BookkeeperDockerService.java
- test/system/src/main/java/io/pravega/test/system/framework/services/docker/ZookeeperDockerService.java
- test/system/src/test/java/io/pravega/test/system/BookieFailoverTest.java
Fixes a sporadic problem in BookieFailoverTest (Docker Swarm system tests) that prevented the Bookkeeper service to scale up from 2 to 3 replicas.
Fixes #3816.
This PR contains 2 changes that improve the situation of the Bookkeeper service in Docker Swarm:
- _Increase retries in the Bookkeeper restart policy_: Before, the `RestartPolicy` of Bookkeeper tasks was set to `maxAttempts=1`. However, in an unfortunate case, a Bookie may fail more than once to get started. We increased restart retries to `3`, which seems to be enough in most cases.
- _Remove unused volume for Bookies_: `BookkeeperDockerService` was mounting a volume referring to a non-existing location in the Bookkeeper image …
> Issue 3816: Sporadic failure of BookieFailoverTest in Docker Swarm system tests

- bindings/src/main/java/io/pravega/storage/hdfs/HDFSStorage.java
Fixing exception thrown from concat as it always has source segment name instead of target.
Fixes #3823
Uses separate try catch blocks for validating target and source so correct exception with correct message can be thrown.
All tests should continue to pass.
> Issue 3823: Fix incorrect segment name in exception thrown.

- bindings/src/main/java/io/pravega/storage/hdfs/HDFSStorage.java
- client/src/main/java/io/pravega/client/netty/impl/Connection.java
- client/src/main/java/io/pravega/client/netty/impl/FlowHandler.java
- client/src/main/java/io/pravega/client/segment/impl/SegmentOutputStream.java
- client/src/main/java/io/pravega/client/stream/impl/ClientFactoryImpl.java
- client/src/main/java/io/pravega/client/stream/impl/EventStreamWriterImpl.java
- client/src/main/java/io/pravega/client/stream/impl/Pinger.java
- client/src/main/java/io/pravega/client/stream/impl/ReaderGroupImpl.java
- client/src/main/java/io/pravega/client/stream/impl/ReaderGroupState.java
- client/src/main/java/io/pravega/client/stream/impl/ReaderGroupStateManager.java
- client/src/main/java/io/pravega/client/stream/impl/TransactionalEventStreamWriterImpl.java
- client/src/test/java/io/pravega/client/stream/impl/EventStreamWriterTest.java
- client/src/test/java/io/pravega/client/stream/impl/PingerTest.java
- client/src/test/java/io/pravega/client/stream/impl/TransactionalEventStreamWriterTest.java
- segmentstore/server/src/main/java/io/pravega/segmentstore/server/attributes/SegmentAttributeBTreeIndex.java
- segmentstore/server/src/main/java/io/pravega/segmentstore/server/writer/SegmentAggregator.java
- segmentstore/server/src/main/java/io/pravega/segmentstore/server/writer/StorageWriter.java
- segmentstore/server/src/test/java/io/pravega/segmentstore/server/writer/SegmentAggregatorTests.java
- segmentstore/server/src/test/java/io/pravega/segmentstore/server/writer/StorageWriterTests.java
- segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/StorageNotPrimaryException.java
- test/system/src/main/java/io/pravega/test/system/framework/services/docker/BookkeeperDockerService.java
- test/system/src/main/java/io/pravega/test/system/framework/services/docker/ZookeeperDockerService.java
* Cherry-picks recent commits fixing bugs from master to r0.5.
Fixes #3826
Cherry-picks the following commits:
```
Issue 3823: Fix incorrect segment name in exception thrown. (#3824)
Issue 3816: Sporadic failure of BookieFailoverTest in Docker Swarm system tests (#3818)
Issue 3811: Fix SpotBugs error on Java 11 build (#3812)
Issue 3724: (SegmentStore) BugFix - Creating an already existing Segment in Tier 2 (#3804)
Issue 3463: Ensure completed transactions are not pinged by the client. (#3767)
Issue 3805: (SegmentStore) BugFix - StorageWriter not shutting down if Tier 2 fencing detected. (#3806)
```
Check the git log to make sure it contains the expected set of commits and make sure …
> Issue 3826: Cherry-pick commits from master to r0.5

- client/src/test/java/io/pravega/client/segment/impl/SegmentOutputStreamTest.java
* Fix flaky junit test testSegmentSealedFollowedbyConnectionDrop
Fixes #3830 
The test now waits until the `connectionDrop()` netty callback execution is completed.
This also removes unchecked warnings while building the `SegmentOutputStreamTest` file.
All the tests should continue to pass.
> Issue 3830:  Fix flaky test testSegmentSealedFollowedbyConnectionDrop

- client/src/main/java/io/pravega/client/segment/impl/SegmentOutputStreamImpl.java
- client/src/test/java/io/pravega/client/segment/impl/SegmentOutputStreamTest.java
- shared/protocol/src/main/java/io/pravega/shared/protocol/netty/AppendDecoder.java
- shared/protocol/src/test/java/io/pravega/shared/protocol/netty/AppendEncodeDecodeTest.java
* Fixes in r0.5 a bug in event writers to prevent connections from being established to sealed / truncated segments.
* Fixes flaky junit test testSegmentSealedFollowedbyConnectionDrop
Fixes #3828
See PR #3820 and #3831. 
It should contain the commits for PRs #3820 and #3831, and should build correctly.
> Issue 3624: BugFix - Segment Seal and reconnect race causes io.netty.util.IllegalReferenceCountException

- shared/metrics/src/main/java/io/pravega/shared/metrics/DynamicLoggerImpl.java
- shared/metrics/src/main/java/io/pravega/shared/metrics/Gauge.java
- shared/metrics/src/main/java/io/pravega/shared/metrics/GaugeProxy.java
- shared/metrics/src/main/java/io/pravega/shared/metrics/NullStatsLogger.java
- shared/metrics/src/main/java/io/pravega/shared/metrics/StatsLogger.java
- shared/metrics/src/main/java/io/pravega/shared/metrics/StatsLoggerImpl.java
- shared/metrics/src/main/java/io/pravega/shared/metrics/StatsLoggerProxy.java
- shared/metrics/src/test/java/io/pravega/shared/metrics/BasicMetricTest.java
- shared/metrics/src/test/java/io/pravega/shared/metrics/MetricsProviderTest.java
- shared/metrics/src/test/java/io/pravega/shared/metrics/StatsLoggerProxyTest.java
Gauge handling is different than other metrics type because it passes a function into metrics registry. Because the function is immutable, in order to update gauge, the legacy code just delete existing gauge and insert a new one.
Hence a race condition is introduced - if the gauge value is retrieved after the old object is deleted but before the new object is registered, the gauge will report 0 or NaN.
This change is to add an AtomicReference into Gauge which points to a function. To update Gauge value, simply replace the function inside the reference.
Fixes #3786
Added an AtomicReference into Gauge object to hold a reference to a Supplier<Number>.
Changed the Gauge …
> Issue 3786: improved the gauge handling to prevent gauge object loss

- segmentstore/server/src/main/java/io/pravega/segmentstore/server/logs/ContainerMetadataUpdateTransaction.java
- segmentstore/server/src/main/java/io/pravega/segmentstore/server/logs/operations/CheckpointOperationBase.java
- segmentstore/server/src/test/java/io/pravega/segmentstore/server/logs/ContainerMetadataUpdateTransactionTests.java
- segmentstore/server/src/test/java/io/pravega/segmentstore/server/logs/DurableLogTests.java
- segmentstore/server/src/test/java/io/pravega/segmentstore/server/logs/OperationProcessorTests.java
- segmentstore/server/src/test/java/io/pravega/segmentstore/server/logs/operations/CheckpointOperationTests.java
- `MetadataCheckpointOperation`s and `StorageMetadataCheckpointOperation`s no longer keep a reference to their serialized contents after being serialized and/or processed.
Fixes #3801.
Fixes #3803.
- Anything inheriting from `CheckpointOperationBase` will have its contents cleared after processing, as there is no need for these byte serializations after writing them to Tier 1.
- Checkpoint operations are used to snapshot the in-memory metadata to Tier 1. 
- They are queued just like any other operation.
- During pre-processing, they are assigned a byte array containing the serialization of everything in the container metadata
- After pre-processing, they are serialized to Tier 1 (just like any other op)
- …
> Issue 3801, 3803: (SegmentStore) Do not keep checkpoint operations' serializations in memory

- shared/protocol/src/test/java/io/pravega/shared/segment/ScaleTypeTests.java
- shared/protocol/src/test/java/io/pravega/shared/segment/StreamSegmentNameUtilsTests.java
* Adds some simple unit tests to classes in shared/segment to improve code coverage.
* Specifically, adds tests for ScaleType and StreamSegmentNameUtils
Fixes #3809 
This PR adds new unit test cases to improve the test coverage in the shared/segment package. Codecov is declaring that the package has low coverage and there are two classed only primarily contributing to the low coverage. 
New unit tests must pass and code coverage must go up.
> Issue 3809: Add unit tests for shared/segment classes

- test/system/src/main/java/io/pravega/test/system/framework/services/kubernetes/AbstractService.java
- test/system/src/test/resources/pravega.properties
- test/system/src/test/resources/pravega_withAuth.properties
Recently we made a change that requires config values being passed through pravega.properties file.
This broke existing system tests for HDFS as config values for segment store were no more getting passed.
fixing it.
Fixes #3843
- add config values to this file 
- delete options from AbstractService.java as it is no more needed. 
Hdfs system tests should see  hdfs.replaceDataNodesOnFailure=false passed to segment store.
**Recent failures that were caused by this issue**
io.pravega.test.system.AutoScaleTest.scaleTests
io.pravega.test.system.BookieFailoverTest.bookieFailoverTest
io.pravega.test.system.ByteClientTest.byteClientTest …
> Issue 3843 : Add missing config values required for for HDFS system tests to test/resources/pravega.properties file.

- segmentstore/server/src/main/java/io/pravega/segmentstore/server/attributes/SegmentAttributeBTreeIndex.java
- segmentstore/server/src/main/java/io/pravega/segmentstore/server/writer/SegmentAggregator.java
- segmentstore/server/src/test/java/io/pravega/segmentstore/server/attributes/AttributeIndexTests.java
- The Segment Attribute Index is now created only when writing to it for the first time.
Fixes #3832.
- #3148 ensured that all segments are created in Tier 2 only when we transfer the first byte to them, however that did not address Attribute Segments (which reside only in Tier 2 and cannot be accessed from the outside). Furthermore, these were created even if we did not intend to write anything to them (when we want to get the value of an attribute, for example), which significantly increased the latency of certain external operations that relied on attributes (file creates (some cases) and setting up appends for new segments).
- The `SegmentAttributeBTreeIndex` has been modified in a similar fashion to …
> Issue 3832: (SegmentStore) Lazily creating the Attribute Index only on the first write.

- segmentstore/server/src/main/java/io/pravega/segmentstore/server/containers/MetadataStore.java
- segmentstore/server/src/main/java/io/pravega/segmentstore/server/containers/StreamSegmentContainer.java
- segmentstore/server/src/test/java/io/pravega/segmentstore/server/containers/MetadataStoreTestBase.java
- segmentstore/server/src/test/java/io/pravega/segmentstore/server/containers/TableMetadataStoreTests.java
1. Fixed a bug in `MetadataStore` where a pending assignment would never complete a returned future if a sync exception is thrown.
2. Always closing the `MetadataStore` when shutting down the owning Segment Container.
Fixes #3851.
- Context: 
- Everything inside the Segment Container uses Segment Ids (not names) to operate.
- A Segment Id is assigned the first time a segment is used, and is stored either in the in-memory metadata or in the Container Metadata Table.
- If not in memory, the Segment Container delegates to the `MetadatStore` to get-or-assign its id, which is an async operation.
- Multiple requests for the same segment may arrive at or around the same time (while the first one is executing), in …
> Issue 3851: (SegmentStore) Bugfix for Segment Id assignment never completing

- segmentstore/server/src/main/java/io/pravega/segmentstore/server/containers/StreamSegmentMetadata.java
- segmentstore/server/src/main/java/io/pravega/segmentstore/server/logs/SegmentMetadataUpdateTransaction.java
- segmentstore/server/src/main/java/io/pravega/segmentstore/server/reading/ContainerReadIndex.java
- segmentstore/server/src/main/java/io/pravega/segmentstore/server/reading/StreamSegmentReadIndex.java
- segmentstore/server/src/test/java/io/pravega/segmentstore/server/reading/ContainerReadIndexTests.java
Fixed a bug in `ContainerReadIndex` where it would incorrectly manage Segment Read Indices when those segments have been evicted or are in the process of being evicted.
Fixes #3855.
- `ContainerReadIndex.cleanup()`
- This method has been modified to check the `SegmentMetadata` that a candidate `SegmentReadIndex` actually points to (not the instance just served from `ContainerMetadata`). 
- If this is no longer the case, then the Read Index is closed.
- This ensures that if a segment has just been evicted and immediately reactivated, we won't have a case when the Read Index is in disagreement with the metadata.
- `ContainerReadIndex.getOrCreateIndex()`
- This is used by every operation concerning the Read …
> Issue 3855: (SegmentStore) Bugfix for segment eviction in Read Index

- standalone/src/main/java/io/pravega/local/InProcPravegaCluster.java
Fix the condition that leads to auth failure in internal communications from AutoScaleProcessor in standalone mode server. 
Fixes #3296.
The code sets the correct auth params via system properties so that that the CientConfig used in `AutoScaleProcessor` has the specified credentials to work with. Previously, wrong params were being set and the params were not propagated, so the `ClientConfig` used there could not obtain credentials. 
* All tests should pass. 
* If you run Standalone mode server with auth enabled, you should not encounter the exception mentioned in the issue description.
> Issue 3296: Fix auth failure in internal communications in Standalone Mode server

- client/src/main/java/io/pravega/client/stream/impl/SegmentSelector.java
- client/src/test/java/io/pravega/client/stream/impl/SegmentSelectorTest.java
Ensure `ControllerFailureException` is thrown in case Pravega Controller is not reachable while the writers are trying to retransmit inflight events to successor segments.
Fixes #3835 
Before this PR the writer would fail all pending writes/ inflight events with `NoSuchSegmentException` when the client is not able to reach the Pravega controller.
With this PR the writers will fail all pending writes with 
* `ControllerFailureException` incase controller is not reachable.
* `NoSuchSegmentException` incase the stream is deleted.
> Issue 3835: Improve exception handling to handle Controller is not available.

- test/integration/src/test/java/io/pravega/test/integration/MetricsTest.java
- test/testcommon/src/main/java/io/pravega/test/common/AssertExtensions.java
- test/testcommon/src/main/java/io/pravega/test/common/TestUtils.java
There is a bug inside AssertExtension::assertEventuallyEquals() - when compare two incoming objects, it uses == (address comparison) which fails in most cases unless the two objects are the same. Then it keeps trying until timed out and eventually hands it over to org.junit.Assert.assertEquals which correctly uses objA.equals(objB). 
The effect of this bug is that it will hold things up to timeout and then call assertEquals.
Fixes #3785 
This PR fixes a bug in `AssertExtensions`, by testing null equals and then call equals of object, instead of using address comparison.
With the fix above, the test inside `MetricsTest` still failed because there's no more holding so the cache eviction didn't get chance to …
> Issue 3785: Fixes bug inside AssertExtensions

- segmentstore/server/src/test/java/io/pravega/segmentstore/server/logs/OperationProcessorTests.java
- test/testcommon/src/main/java/io/pravega/test/common/AssertExtensions.java
- Fixed a unit test that needed to wait on a condition to eventually become true.
- Added `AssertExtensions.assertEventuallyEquals(message, ...)` to include custom messages in failures.
Fixes #3718.
- The unit test was relying on some value that was set asynchronously by the `OperationProcessor`. In some conditions, those values would either be delayed substantially or arrive out of order, so they would not be ready for reading when the test required them.
- Replacing `Assert.assertEquals` with `assertEventuallyEquals` changed the unit test to wait up to a specified amount of time for the condition to become true.
Run these unit tests 20K+ times and verify they don't fail.
> Issue 3718: Fixed flaky unit tests in OperationProcessorTests.

- controller/src/main/java/io/pravega/controller/task/Stream/RequestSweeper.java
- controller/src/test/java/io/pravega/controller/task/Stream/RequestSweeperTest.java
RequestSweeper had incorrect check in do while loop whereby 
1) if all entities for a host had already been failed over, then it gets stuck in an infinite loop
2) if there are more than "limit" number of entities in the host, it exited prematurely. 
Fixes #3867
Instead of `list.IsEmpty` we need to check `!list.isEmpty` to continue the doWhile loop. 
Added unit test to test the functionality. 
Parametrized the limit on number of entities to fetch from zookeeper in one pass. 
Unit test added.
> Issue 3867: RequestSweeper has incorrect exit check in doWhile loop 

- controller/src/main/java/io/pravega/controller/fault/ControllerClusterListener.java
- controller/src/test/java/io/pravega/controller/fault/ControllerClusterListenerTest.java
ControllerClusterListenerTest does `when(mock.method(qualifiers)).thenAnswer(x -> answer)`. This causes the underlying method to be invoked while mock is being instantiated. 
Changing it to `doAnswer(x -> answer).when(mock).method(qualifiers)` ensures the mocks are set and only they are invoked. Underlying method is not invoked. 
Fixes #3882 
After verifying the behaviour with `when(mock.method(qualifiers)).thenAnswer(x -> answer)` I observed that the actual method is called during the initialization. 
Sometimes, and this is something i am not sure when, the invocation count for the mock is incremented with actual method invocation. 
Thats when the …
> Issue 3882: ControllerClusterListener test mocks invoke the method once with null/empty values

- client/src/main/java/io/pravega/client/ClientConfig.java
- client/src/test/java/io/pravega/client/CredentialsExtractorTest.java
Adds null checks to prevent errors in extracting client credentials from environment variables. 
Fixes #3847. 
* Adds null checks in ClientConfig `extractCredentials(...)` to prevent errors in extracting credentials from environment variables. It also adds some log statements for easier debugging. 
* Adds some tests and refactors existing one in `CredentialsExtractorTest` class for verifying client credentials extraction logic more comprehensively. 
> Issue 3847: Fix issues causing error in extracting client credentials 

- segmentstore/server/src/main/java/io/pravega/segmentstore/server/SegmentMetadata.java
- segmentstore/server/src/main/java/io/pravega/segmentstore/server/containers/SegmentAttributeIterator.java
- segmentstore/server/src/main/java/io/pravega/segmentstore/server/containers/StreamSegmentMetadata.java
- segmentstore/server/src/main/java/io/pravega/segmentstore/server/logs/SegmentMetadataUpdateTransaction.java
- segmentstore/server/src/test/java/io/pravega/segmentstore/server/containers/StreamSegmentMetadataTests.java
- Fixed a bug in `SegmentAttributeIterator` where the `StreamSegmentMetadata` attribute iteration was not thread safe and was prone to `ConcurrentModificationException`s.
Fixes #3853.
- Created `StreamSegmentMetadata.getAttributes(Filter)` which iterates and filters while holding the same lock used for modifying its contents.
- Updated `SegmentAttributeIterator` to use this method for retrieving desired attributes.
- Concurrency cannot be easily tested in unit tests.
- Updated a `StreamSegmentMetadata` unit test to verify new method.
> Issue 3853: (SegmentStore) Bugfix for ConcurrentModificationException in SegmentAttributeIterator

- client/src/main/java/io/pravega/client/stream/impl/ReaderGroupImpl.java
* Makes getRemainingBytes asynchronous
Fixes #1478 
`getRemainingBytes` will return a `CompletableFuture<Long>` instead of `long`. 
`getUnreadBytes` will collect and compute results when all the `CompletableFuture<Long>` are finished.  
Test should pass
Signed-off-by: wenqimou <wenqimou@gmail.com>
> Issue 1478: Make getRemainingBytes asynchronous

- controller/src/test/java/io/pravega/controller/task/Stream/StreamMetadataTasksTest.java
Fixes sporadic build failure in PravegaTablesStreamMetadataTasksTest.sealStreamWithTx because the transaction lease is set to only 100 ms and the timeout is executed before we could commit.
This test starts timerwheel service by default, which is racing with the test to abort the transaction as we attempt to commit it. 
Fixes #3907
Increases transaction lease during transaction creation in the test. 
> Issue 3907: Sporadic build failure in PravegaTablesStreamMetadataTasksTest.sealStreamWithTx

- client/src/main/java/io/pravega/client/segment/impl/SegmentOutputStreamImpl.java
- client/src/main/java/io/pravega/client/stream/impl/EventStreamWriterImpl.java
- client/src/main/java/io/pravega/client/stream/impl/SegmentSelector.java
- client/src/test/java/io/pravega/client/segment/impl/SegmentOutputStreamTest.java
- client/src/test/java/io/pravega/client/stream/impl/SegmentSelectorTest.java
Ensure `SegmentOutputStream#flush` of a sealed segment throws a `SegmentSealedException` in the case of a zero inflight events.
Fixes #3425
`EventStreamWriter.flush()` invokes a `flush()` on all the Segment writers. Now if any of the segment writers threw a `SegmentSealedException` during a `SegmentOutputStream.flush()` the event stream writer will fetch the latest segment writers again and perform a flush over each of them, thereby ensuring all the inflight events are written/durably persisted.
For this logic to work we need to remove the older writer only after we have resent the inflight events to the successor segments. This was not the case earlier and could cause a flush to prematurely stop blocking …
> Issue 3425: Ensure the Sealed segment writer is removed after all inflight events are resent to the newer segment writers.

- controller/src/test/java/io/pravega/controller/server/v1/ControllerServiceImplTest.java
- controller/src/test/java/io/pravega/controller/store/task/TaskStoreFactoryForTests.java
* Adds more log messages to test code to enable debugging in the case the issue hits again.
* Resets the latch variable once both threads have requested lock concurrently in TaskMetadataStoreForTests  implementations.
Fixes #3889 
Even though the test failures have happened on Jenkins, I have not been able to reproduce the issue locally or on Jenkins even with branch builds. This PR is proposing two defensive changes:
- It adds more log messages so that we get a better sense of the flow in the case the problem hits again.
- It resets the latch variable once we have that both threads have requested the lock concurrently.
The changes are in both `ZKTaskMetadataStoreForTests` and …
> Issue 3889: Improve test code for ControllerServiceImplTest to enable debugging and avoid false positives

- segmentstore/server/host/src/main/java/io/pravega/segmentstore/server/host/handler/AppendProcessor.java
- segmentstore/server/host/src/main/java/io/pravega/segmentstore/server/host/handler/PravegaRequestProcessor.java
- segmentstore/server/host/src/main/java/io/pravega/segmentstore/server/host/handler/ServerConnectionInboundHandler.java
- Reduced logging verbosity of `IllegalContainerStateException` when logged from `AppendProcessor`, `PravegaRequestProcessor` or `ServerConnectionInboundHandler`.
Fixes #3916.
- Logging `IllegalContainerStateException` as a WARN instead of an ERROR and not showing the stack trace.
Run system tests and verify these don't show up as errors, but other errors still show up
> Issue 3916: (SegmentStore) Reduce logging verbosity of IllegalContainerStateException

- docker/compose/swarm/scale_segmentstore
* Ensures `publishedIPAddress` configuration is read from the docker configuration.
* Adds missing configuration for HDFS.
Fixes #3859 #3874 
`scale_segmentStore ` is a helper script which is used to scale segment stores (with HDFS as tier2) instances with external access. This enables Pravega to be accessed by clients outside the docker swarm cluster. The user uses the system property `PUBLISHED_ADDRESS` to convey the ip to be used by the external clients to access Pravega.
The script ensures it reads the configuration from the running segment store docker service 
via `docker service inspect pravega_segmentstore` and uses the same properties to create newer segment store service instances.
**How to verify …
> Issue 3859: Fix scale_segmentStore script for external access

- segmentstore/server/src/main/java/io/pravega/segmentstore/server/reading/StreamSegmentReadIndex.java
- segmentstore/server/src/test/java/io/pravega/segmentstore/server/reading/ContainerReadIndexTests.java
- Fixed a bug in `StreamSegmentReadIndex` where it could erroneously evict a cache entry if it had an EntryLength of 1 and a SegmentOffset equaling to the Segment's StorageLength.
Fixes #3929.
- Fixed a bug in `StreamSegmentReadIndex` where it could erroneously evict a cache entry if it had an EntryLength of 1 and a SegmentOffset equaling to the Segment's StorageLength.
- By definition, no Cache Entry which has at least one byte that hasn't been moved to Tier 2 can be evicted.
- The eviction logic was checking the `Entry.getLastStreamSegmentOffset` which was calculated as `Offset+Length-1`. As such `<` should be used instead of `<=`.
Updated the …
> Issue 3929: (SegmentStore) Cache eviction bug fix

- build.gradle
Add JAXB API and reference implementation dependencies to the `shared/security` subproject.
Resolves #3937. 
The code changes add JAXB API and reference implementation dependencies to shared security subproject. 
See Jesper de Jong's excellent [article](https://www.jesperdj.com/2018/09/30/jaxb-on-java-9-10-11-and-beyond/) for detailed information about the context.
Run the failed tests mentioned in the issue (#3937) description on a host running Java SE 11.
> Issue 3937: Resolve JsonWebToken test failures in Java 11 builds

- controller/src/main/java/io/pravega/controller/server/SegmentHelper.java
- controller/src/test/java/io/pravega/controller/server/SegmentHelperTest.java
Signed-off-by: huide9 <huide9@gmail.com>
Modify to throw correct exception instead using an unmatching exception info.
fixes #3921
* change to use matching exception for TableSegmentIsEmpty reply
* add WireCommandType info into exception so can get find out the operation type
UT case modified to verify the changes. The matching excpetion reason: *WireCommandFailedException.Reason.TableSegmentNotEmpty*  should be caught correctly.
> Issue 3921: SegmentHelper should not throw a ConnectionFailedException incase of TableSegmentIsEmpty response for deleteTableSegment

- segmentstore/server/host/src/main/java/io/pravega/segmentstore/server/host/stat/SegmentStatsRecorderImpl.java
- segmentstore/server/host/src/test/java/io/pravega/segmentstore/server/host/stat/SegmentStatsRecorderTest.java
- shared/metrics/src/main/java/io/pravega/shared/metrics/DynamicLoggerImpl.java
- Stopped deleting counter of parent segment when delete or seal transaction segment.
- Added metrics registry level activity logs.
Fixes #3692 
Inside SegmentStatsRecorderImpl, when delete or seal segment, first check if it is transaction segment.
If it is txn segment, then do not close the counter, because there is no associated counter for txn segment.
Unit tests should pass.
In particular, longevity small-tx and other txn related tests should now see the metrics of committed txn.
> Issue 3692: Do not remove counter of parent segment when delete or seal txn segment

- segmentstore/server/host/src/main/java/io/pravega/segmentstore/server/host/handler/ServerConnectionInboundHandler.java
- shared/protocol/src/main/java/io/pravega/shared/protocol/netty/FailingRequestProcessor.java
- shared/protocol/src/main/java/io/pravega/shared/protocol/netty/Request.java
- shared/protocol/src/main/java/io/pravega/shared/protocol/netty/WireCommands.java
- Logging `WireCommand.KeepAlive` as `TRACE`
Fixes #3948.
See description.
> Issue 3948: Log KeepAlives at Trace level

- client/src/main/java/io/pravega/client/ClientConfig.java
- segmentstore/server/host/src/main/java/io/pravega/segmentstore/server/host/handler/AppendProcessor.java
The default max connections per segment store is set to 10 and in the append processor netty channel water marking low and high values are set to 640KB And 1MB respectively.
Fixes #3774
Since the current value of DEFAULT_MAX_CONNECTIONS_PER_SEGMENT_STORE is 5 and its not adequate to keep at least 10 writers ;  so, its set as 10 to improve the throughput.
Similarly, due to connection pooling a single netty channel is expected to more data due to multiple writers/reader, hence the netty channel water marking low and high values are set to 640KB And 1MB respectively.
Pravega is tested with unit tests and integration tests.
Pravega is tested with bare-metal deployment with 1 controller and …
> Issue 3774: Update the default max connection and Netty channel water marking for performance Improvement

- controller/src/main/java/io/pravega/controller/server/rpc/grpc/v1/ControllerServiceImpl.java
- controller/src/test/java/io/pravega/controller/server/rpc/auth/ControllerGrpcAuthFocusedTest.java
Fix auth resource representation in Controller gRPC list streams operation to ensure that streams that the user has access to are returned in the filtered list of streams. 
Fixes #3940. 
1. Fixes the auth resource representation for stream by using `AuthResourceRepresentation.ofStreamInScope(scopeName, streamName)` to create it. 
By doing that, it changes auth resource representation used for stream in list streams operation to a fully qualified stream name of the form "scope1/stream1`. Earlier the resource string for the stream used in this operation was of the form "stream1".
2. Adds some tests to ControllerGrpcAuthFocusedTest for verifying the operation.
All test should pass.
> Issue 3940: Fix auth resource representation used for stream in list streams operation

- client/src/main/java/io/pravega/client/ClientConfig.java
- client/src/main/java/io/pravega/client/netty/impl/ClientConnectionImpl.java
- client/src/main/java/io/pravega/client/netty/impl/ConnectionPoolImpl.java
- client/src/main/java/io/pravega/client/netty/impl/Flow.java
- client/src/main/java/io/pravega/client/netty/impl/FlowHandler.java
- client/src/test/java/io/pravega/client/netty/impl/FlowHandlerTest.java
- controller/src/main/java/io/pravega/controller/server/rpc/grpc/v1/ControllerServiceImpl.java
- controller/src/test/java/io/pravega/controller/server/rpc/auth/ControllerGrpcAuthFocusedTest.java
- segmentstore/server/host/src/main/java/io/pravega/segmentstore/server/host/handler/AppendProcessor.java
- segmentstore/server/host/src/main/java/io/pravega/segmentstore/server/host/handler/PravegaRequestProcessor.java
- segmentstore/server/host/src/main/java/io/pravega/segmentstore/server/host/handler/ServerConnectionInboundHandler.java
- segmentstore/server/src/main/java/io/pravega/segmentstore/server/tables/ContainerKeyCache.java
- segmentstore/server/src/main/java/io/pravega/segmentstore/server/tables/ContainerKeyIndex.java
- segmentstore/server/src/main/java/io/pravega/segmentstore/server/tables/ContainerTableExtensionImpl.java
- segmentstore/server/src/main/java/io/pravega/segmentstore/server/tables/SegmentKeyCache.java
- segmentstore/server/src/test/java/io/pravega/segmentstore/server/tables/ContainerKeyCacheTests.java
- segmentstore/server/src/test/java/io/pravega/segmentstore/server/tables/ContainerKeyIndexTests.java
- segmentstore/server/src/test/java/io/pravega/segmentstore/server/tables/ContainerTableExtensionImplTests.java
- shared/protocol/src/main/java/io/pravega/shared/protocol/netty/CommandEncoder.java
- shared/protocol/src/main/java/io/pravega/shared/protocol/netty/FailingRequestProcessor.java
- shared/protocol/src/main/java/io/pravega/shared/protocol/netty/Request.java
- shared/protocol/src/main/java/io/pravega/shared/protocol/netty/WireCommands.java
- shared/protocol/src/test/java/io/pravega/shared/protocol/netty/AppendEncodeDecodeTest.java
- test/system/src/test/java/io/pravega/test/system/AbstractReadWriteTest.java
* Cherry-picks commits from `master` to `r0.5`
Fixes #3983
The following is the list of commits that we are cherry-picking in this PR:
```
Issue 3948: Log KeepAlives at Trace level. (#3949) 
Issues 3918, 3919, 3920: Throttle Transactional Writers in System Tests (#3950)
Issue 3774: Update the default max connection and Netty channel watermarking for performance Improvement (#3959)
Issue 3940: Fix auth resource representation used for stream in listStreams operation
Issue 3909: AppendBatchSizeTracker bug fix (#3863)
Issue 3918: (SegmentStore) Table Segment Pre-Caching (#3928)
```
> Issue 3983: Cherry-pick commits from master to r0.5

- controller/src/main/java/io/pravega/controller/store/stream/ZKScope.java
- controller/src/main/java/io/pravega/controller/store/stream/ZKStreamMetadataStore.java
- controller/src/test/java/io/pravega/controller/store/stream/StreamMetadataStoreTest.java
1. Changes znode store/streamsInScope to store/_streamsInScope
2. Filters streamsInScope when listing scopes 
Fixes #3442 
Changes znode store/streamsInScope to store/_streamsInScope so that it can be ignored from list scopes call. 
Unit test updated
> Issue 3442: Ensure znode store/streamsInScope is ignored when listing scopes for Zk based stream store

- controller/src/main/java/io/pravega/controller/store/index/HostIndex.java
- controller/src/main/java/io/pravega/controller/store/index/InMemoryHostIndex.java
- controller/src/main/java/io/pravega/controller/store/index/ZKHostIndex.java
- controller/src/main/java/io/pravega/controller/store/task/TxnResource.java
- test/integration/src/test/java/io/pravega/test/integration/endtoendtest/EndToEndStatsTest.java
* Fixes license headers that accidentally included the last paragraph of the ALv2, which was excluded by our legal.
Fixes #3989 
There is no code change, only changes to license headers.
It should build correctly as usual.
> Issue 3989: Fix license headers

- docker/pravega/scripts/init_kubernetes.sh
Retrieve load balancer's external endpoint by host-name if IP is not available. 
Fixes #4002 . 
If the load balancer's external endpoint's IP isn't available, retrieves the endpoint's hostname. IP address of the load balancer is available in PKS. For AWS, the endpoint address is accessed via hostname. See issue #4002 for additional details. 
Verify that a Kubernetes cluster with external access enabled works for both PKS and AWS.
> Issue 4002: Use load balancer's external endpoint hostname if IP isn't available

- client/src/main/java/io/pravega/client/segment/impl/AsyncSegmentInputStreamImpl.java
- common/src/main/java/io/pravega/common/util/ContinuationTokenAsyncIterator.java
- controller/src/main/java/io/pravega/controller/metrics/StreamMetrics.java
- controller/src/main/java/io/pravega/controller/server/eventProcessor/ControllerEventProcessors.java
- controller/src/main/java/io/pravega/controller/server/eventProcessor/requesthandlers/AbstractRequestProcessor.java
- controller/src/main/java/io/pravega/controller/server/eventProcessor/requesthandlers/CommitRequestHandler.java
- controller/src/main/java/io/pravega/controller/server/eventProcessor/requesthandlers/ScaleOperationTask.java
- controller/src/main/java/io/pravega/controller/store/index/HostIndex.java
- controller/src/main/java/io/pravega/controller/store/index/InMemoryHostIndex.java
- controller/src/main/java/io/pravega/controller/store/index/ZKHostIndex.java
- controller/src/main/java/io/pravega/controller/store/stream/ZKGarbageCollector.java
- controller/src/main/java/io/pravega/controller/store/stream/ZKScope.java
- controller/src/main/java/io/pravega/controller/store/stream/ZKStoreHelper.java
- controller/src/main/java/io/pravega/controller/store/stream/ZKStreamMetadataStore.java
- controller/src/main/java/io/pravega/controller/store/stream/ZkOrderedStore.java
- controller/src/main/java/io/pravega/controller/store/task/TxnResource.java
- controller/src/test/java/io/pravega/controller/server/eventProcessor/ControllerEventProcessorsTest.java
- controller/src/test/java/io/pravega/controller/server/eventProcessor/ScaleRequestHandlerTest.java
- controller/src/test/java/io/pravega/controller/store/index/ZkHostIndexTest.java
- controller/src/test/java/io/pravega/controller/store/stream/StreamMetadataStoreTest.java
- controller/src/test/java/io/pravega/controller/store/stream/ZKStoreHelperTest.java
- controller/src/test/java/io/pravega/controller/store/stream/ZKStreamMetadataStoreTest.java
- controller/src/test/java/io/pravega/controller/store/stream/ZkGarbageCollectorTest.java
- controller/src/test/java/io/pravega/controller/store/stream/ZkOrderedStoreTest.java
- docker/pravega/scripts/init_kubernetes.sh
- segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/bookkeeper/BookKeeperLog.java
- shared/metrics/src/main/java/io/pravega/shared/MetricsNames.java
- test/integration/src/test/java/io/pravega/test/integration/StreamMetricsTest.java
- test/integration/src/test/java/io/pravega/test/integration/endtoendtest/EndToEndStatsTest.java
* Cherry-picks commits from master to r0.5
Fixes #4006
All code changes are from cherry-picking the following merges to `master`:
```
Issue 3442: Ensure znode store/streamsInScope is ignored when listing scopes for Zk based stream store (#3988)
Issues 3958, 3755: Adding sync before zookeeper reads for ZK orderer and ZK Host Index (#3985)
Issue 3978: (BookKeeperLog) Fetching appropriate ZNode version. (#3990)
Issue 3989: Fix license headers (#3991)
Issue 3686: Reduce stacktrace upon exceptional AsyncSegmentInputStreamImpl connection close (#3996)
Issue 3999: Soft handle expected exception logs (#3997)
Issue 4002: Use load balancer external endpoint hostname if IP isn't available (#4004)
Issue 3556: Changed …
```
> Issue 4006: Cherry-pick merges from master to r0.5

- client/src/main/java/io/pravega/client/byteStream/ByteStreamClient.java
- client/src/main/java/io/pravega/client/byteStream/ByteStreamReader.java
- client/src/main/java/io/pravega/client/byteStream/ByteStreamWriter.java
- client/src/main/java/io/pravega/client/byteStream/impl/BufferedByteStreamWriterImpl.java
- client/src/main/java/io/pravega/client/byteStream/impl/ByteStreamClientImpl.java
- client/src/main/java/io/pravega/client/byteStream/impl/ByteStreamReaderImpl.java
- client/src/main/java/io/pravega/client/byteStream/impl/ByteStreamWriterImpl.java
- client/src/main/java/io/pravega/client/stream/TransactionalEventStreamWriter.java
- client/src/test/java/io/pravega/client/byteStream/ByteStreamReaderTest.java
- client/src/test/java/io/pravega/client/byteStream/ByteStreamWriterTest.java
- client/src/test/java/io/pravega/client/state/impl/SerializationTest.java
- client/src/test/java/io/pravega/client/stream/impl/ByteSerializerTest.java
- client/src/test/java/io/pravega/client/stream/impl/SerializationTest.java
- common/src/test/java/io/pravega/common/util/ByteBufferUtilsTests.java
- controller/src/conf/logback.xml
- test/integration/src/test/java/io/pravega/test/integration/ByteStreamTest.java
- test/integration/src/test/java/io/pravega/test/integration/IdleSegmentTest.java
- test/integration/src/test/java/io/pravega/test/integration/StreamMetricsTest.java
* Removes year from copyright from remaining files.
It is part of #3508 , but does not close it.
There is no code change, it only updates the license header across some files.
There is no change of behavior, it should build correctly.
> Issue 3508: Remove year from copyright in r05

- segmentstore/server/src/main/java/io/pravega/segmentstore/server/logs/ThrottlerCalculator.java
- Fixed ThrottlerCalculator.Delay.toString()
Fixes #4011.
- Wrong formatting used in `toString`. Without this, any throttling delay recording is useless.
Run a test where DEBUG logging is enabled and verify `Processing delay` outputs something readable.
> Issue 4011: Fixed ThrottlerCalculator.Delay.ToString()

- segmentstore/server/src/main/java/io/pravega/segmentstore/server/SegmentStoreMetrics.java
- segmentstore/server/src/main/java/io/pravega/segmentstore/server/logs/OperationProcessor.java
- segmentstore/server/src/main/java/io/pravega/segmentstore/server/logs/ThrottlerCalculator.java
- shared/metrics/src/main/java/io/pravega/shared/MetricsNames.java
* Cherry-picks changes from master to r0.5
Fixes #4025 
Cherry-picks:
```
Issue 4011: (SegmentStore) Making Commit Backlog Throttler more aggressive (#4016)
Issue 4011: Fixed ThrottlerCalculator.Delay.ToString() (#4023)
```
> Issue 4025: Cherry-pick changes from master to r0.5

- config/config.properties
- segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/rocksdb/RocksDBCache.java
- segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/rocksdb/RocksDBConfig.java
* Enables RocksDB direct reads to be configurable via rocksdb.directReads
* Sets the default value rocksdb.directReads=true
Fixes #3645 
Makes RocksDB direct reads configurable, as not all OS/environments support this option. See also PR #3647 .
No code changes, all tests should be passing as before.
> Issue 3645: Make direct reads configurable in RocksDB

- build.gradle
- test/system/src/main/java/io/pravega/test/system/framework/services/kubernetes/K8SequentialExecutor.java
It will accept the test pod image as Input parameter rather than hard cording
Fixes #4040
Test pod image for system tests is passed as a parameter.
Verified system tests, with different test pod images.
> Issue 4040: Enable test pod image configuration for system tests 

- segmentstore/server/src/main/java/io/pravega/segmentstore/server/logs/DataFrameInputStream.java
- segmentstore/server/src/test/java/io/pravega/segmentstore/server/logs/DataFrameInputStreamTests.java
- segmentstore/server/src/test/java/io/pravega/segmentstore/server/logs/DurableLogTests.java
- Fixed a bug in `DataFrameInputStream` where it was possible to skip over (parts of) a valid operation if the previous operation was only partially committed to Tier 1.
Fixes #4046.
- The `DataFrameInputStream` provides an InputStream-like interface on top of `DataFrame Entries`  that make up the Tier 1 `DurableDataLog`. Every call to `DataFrameInputStream.read` may either read from the currently loaded `DataFrameEntry` or fetch another one (via `fetchNextEntry`).
- However, in certain exceptional cases (such as when an Operation has been split but only one part was successfully written to Tier 1 (BK or Segment Store crashed), we may have had to request more DataFrameEntries in order to figure out the …
> Issue 4046: (SegmentStore) Segment Container Recovery bug with partial operations

- gradle.properties
* Removes `-SNAPSHOT` suffix from Pravega version in gradle.properties in preparation to release 0.5.0.
Fixes #4059 
There is no code change, only a change to the Pravega version in `gradle.properties`.
Build should succeed regularly and artifacts should not contain the commit id suffix.
> Issue 4059: Change Pravega version to 0.5.0

- controller/src/main/java/io/pravega/controller/server/rest/resources/StreamMetadataResourceImpl.java
- controller/src/test/java/io/pravega/controller/rest/v1/StreamMetaDataTests.java
Ensure query parameter validation is performed for scaling-events api.
Fixes #4033 
The scaling events REST api `/{scopeName}/streams/{streamName}/scaling-events` expects two mandatory parameters `from` and `to` . If these parameters are not supplied the `JAX-RS` sets these parameters as NULL . Also, `JAX-RS` does not have a way to configure these parameters as mandatory to ensure the 400 response code response.
The PR validates the queryparameters and sends a `BAD_REQUEST` (http error code 400) incase of missing parameters.
The existing and newly added tests should continue to pass.
> Issue 4033: Ensure query parameters are validated for scaling-events api.

- client/src/main/java/io/pravega/client/ClientConfig.java
- client/src/main/java/io/pravega/client/netty/impl/FlowHandler.java
- client/src/main/java/io/pravega/client/segment/impl/SegmentOutputStreamFactoryImpl.java
- client/src/main/java/io/pravega/client/segment/impl/SegmentOutputStreamImpl.java
- client/src/main/java/io/pravega/client/state/SynchronizerConfig.java
- client/src/main/java/io/pravega/client/stream/EventWriterConfig.java
- client/src/test/java/io/pravega/client/netty/impl/ConnectionFactoryImplTest.java
- client/src/test/java/io/pravega/client/segment/impl/SegmentOutputStreamFactoryTest.java
- client/src/test/java/io/pravega/client/segment/impl/SegmentOutputStreamTest.java
- test/integration/src/test/java/io/pravega/test/integration/endtoendtest/EndToEndChannelLeakTest.java
* Backports issue #3951 to `r0.5`
Fixes #4038 
See #3952 
Build must succeed.
> Issue 4038: Add connection pooling switch for event writers in r0.5

- client/src/main/java/io/pravega/client/stream/impl/ReaderGroupImpl.java
Remove `lombok.var` usage which causes a compilation failure 
Fixes #4075 
Related to https://github.com/pravega/pravega/issues/4078 
No changes to functionality. 
As of Java release 10, 'var' is a restricted local variable type and cannot be used for type declarations. This causes the jenkins build job on Java 11 to fail. The PR removes the usage of `lombok.var`.
The java 11 based jenkins build should succeed.
> Issue 4075: Remove `lombok.var` usage.

- client/src/main/java/io/pravega/client/netty/impl/FlowHandler.java
- client/src/main/java/io/pravega/client/stream/impl/ReaderGroupImpl.java
- client/src/test/java/io/pravega/client/netty/impl/FlowHandlerTest.java
- Ensure all the `ReplyProcessor`s are intimated immediately in the case that sending a `WireCommands.KeepAlive` fails.
Fixes #4079 
Pravega client sends periodic `KeepAlives` and sending a `KeepAlive` will fail if the connection is dropped. Also, netty invokes `io.pravega.client.netty.impl.FlowHandler#channelUnregistered` as soon as the connection is disconnected.
It was observed during a system test run( https://jenkins-server/jenkins/job/test-pravega-continuous/2182/)  that `channelUnregistered()`, which is used to communicate the connection failure, was never invoked as the `KeepAliveTask` task failed. This can cause writers waiting for the connection setup to complete (waiting for `SetupAppend`) to wait …
> Issue 4079: Keep Alive failure should invoke `ProcessingFailure` for all clients immediately.

- config/config.properties
- segmentstore/server/src/main/java/io/pravega/segmentstore/server/CacheManager.java
- segmentstore/server/src/main/java/io/pravega/segmentstore/server/CachePolicy.java
- segmentstore/server/src/main/java/io/pravega/segmentstore/server/CacheUtilizationProvider.java
- segmentstore/server/src/main/java/io/pravega/segmentstore/server/logs/MemoryStateUpdater.java
- segmentstore/server/src/main/java/io/pravega/segmentstore/server/logs/OperationProcessor.java
- segmentstore/server/src/main/java/io/pravega/segmentstore/server/logs/ThrottlerCalculator.java
- segmentstore/server/src/main/java/io/pravega/segmentstore/server/reading/ContainerReadIndex.java
- segmentstore/server/src/main/java/io/pravega/segmentstore/server/store/ServiceConfig.java
- segmentstore/server/src/test/java/io/pravega/segmentstore/server/CacheManagerTests.java
- segmentstore/server/src/test/java/io/pravega/segmentstore/server/logs/MemoryStateUpdaterTests.java
- segmentstore/server/src/test/java/io/pravega/segmentstore/server/logs/ThrottlerCalculatorTests.java
- segmentstore/server/src/test/java/io/pravega/segmentstore/server/reading/ContainerReadIndexTests.java
- segmentstore/server/src/test/java/io/pravega/segmentstore/server/store/ServiceBuilderConfigTests.java
- Logging max-delay throttling and Commit Backlog throttling as WARN (everything else stays as DEBUG).
- Changed Commit Backlog Throttling slightly to begin at 100 and reach max delay at 500.
- Changed the Cache Utilization Throttling to begin throttling at 90% and reach a max delay at 98%.
- Changed the Cache Manager to begin evicting items from the cache when it reaches a target utilization (85%)
- Both the Cache Manager and the Cache Utilization Throttler are now pegged to the same configuration value (`pravegaservice.cacheTargetUtilzationPercent`) which defines both when the throttling begins and what the Cache Manager should aim to keep the cache at. 
Fixes #4034.
- Logging will help us spot slowdowns …
> Issue 4034: (SegmentStore) Throttling and Cache Management Tweaks

- client/src/main/java/io/pravega/client/segment/impl/EventSegmentReader.java
- client/src/main/java/io/pravega/client/segment/impl/EventSegmentReaderImpl.java
- client/src/main/java/io/pravega/client/segment/impl/SegmentInputStream.java
- client/src/main/java/io/pravega/client/segment/impl/SegmentInputStreamImpl.java
- client/src/test/java/io/pravega/client/stream/impl/OrdererTest.java
- client/src/test/java/io/pravega/client/stream/mock/MockSegmentIoStreams.java
(Longevity tests are still in progress)
Reduce the creation of new `java.util.concurrent.CompletionStage` inside `SegmentInputStreamImpl#fillBuffer()`
Fixes #4056 
If a reader attempts to read from a Segment which has no data then a new `java.util.concurrent.CompletionStage` is created for every execution of `SegmentInputStream#fillBuffer`.  These new `CompletionStage`s will never be garbage collected and can lead to increased usage of heap memory in a long running application.
All the existing tests should continue to pass. 
Also, we should verify that the memory consumption by the readers is reduced in the case of segments with no new data. e.g: this scenario can arise when events …
> Issue 4056: Reduce creation of new CompletionStage while trying to fill read buffer.

- shared/protocol/src/main/java/io/pravega/shared/protocol/netty/AppendDecoder.java
- shared/protocol/src/test/java/io/pravega/shared/protocol/netty/AppendEncodeDecodeTest.java
- Invoking `ByteBuf.copy()` so that we eliminate excess padding around appends.
Fixes #4069 
- An append on the Segment Store side may be received from multiple append blocks. With connection pooling, the actual usable data in these blocks may be significantly less than the allocated size of the buffers (with the excess being padding).
- What we pass to the downstream Segment Store is a ByteBuf that is either sliced off a single Append Block or a composite of (slices) of multiple Append Block. As such, we can end up with an Append ByteBuf of length N which actually holds pointers to ByteBufs allocating significantly more memory than N. 
- This can be a problem if the Append ByteBuf is required for a …
> Issue 4069: (AppendDecoder) Trimming excess allocated memory in decoded appends.

- client/src/main/java/io/pravega/client/stream/impl/ReaderGroupImpl.java
- client/src/test/java/io/pravega/client/stream/impl/ReaderGroupImplTest.java
- test/testcommon/src/main/java/io/pravega/test/common/AssertExtensions.java
Prevent canceling of future returned from initiateCheckpoint() from impacting the checkpoint.
Fixes #4101, Closes #2258
Adds an additional stage to the returned future to prevent the call to cancel from influencing the computation.
Added a test to verify the effectiveness and also fixed a test code bug introduced in #3844 which prevented verification.
> Issue 4101: Prevent users from canceling checkpoint completion

- shared/metrics/src/main/java/io/pravega/shared/MetricsTags.java
- shared/metrics/src/main/java/io/pravega/shared/metrics/StatsProviderImpl.java
- shared/metrics/src/test/java/io/pravega/shared/MetricsTagsTest.java
This is a bug fix: missed the env var lookup for hostname in the previous PR.
Also add hostname lookup key as input parameter of createHostTag(), so in the future we could make the lookup key configurable.
Fixes #4054 
Changed createHostTag method signature, added hostnameLookupKey as input parameter. This is to make the lookup key configurable in the future.
Added env var lookup in the createHostTag method. This scenario was tested but the code was missed in the previous PR.
Updated the corresponding unit test to reflect the changes.
Metric dashboard should see consistent and short hostname …
> Issue 4054: Lookup Metrics Hostname in Env Var in case it's not defined as a system property

- client/src/main/java/io/pravega/client/stream/impl/ReaderGroupImpl.java
- client/src/test/java/io/pravega/client/stream/impl/ReaderGroupImplTest.java
- test/testcommon/src/main/java/io/pravega/test/common/AssertExtensions.java
* Prevents canceling of future returned from initiateCheckpoint() from impacting the checkpoint completion.
fixes #4101 
See PR #4102 
The problem reported in the issue manifests when maxing out the number of outstanding checkpoints and cancelling each one of them. Such case happens, for example, during a network partition, which prevents the checkpoints from completing. The number of outstanding checkpoints never decrements, even when the outstanding checkpoints are able to complete.
The unit test added should cover this scenario.
> Issue 4101: Prevent users from canceling checkpoint completion. (#4102)

- HEADER
- controller/src/main/java/io/pravega/controller/server/rpc/auth/GrpcAuthHelper.java
- controller/src/main/java/io/pravega/controller/server/rpc/grpc/v1/ControllerServiceImpl.java
Adds logging statements in the Controller to aid debugging of failure scenarios where delegation token might be null or empty. 
Resolved #4135 
Adds logging statements that will emit log entries under these circumstances:
1. When an auth handler plugin throws `RuntimeException` upon invocation of authorization operation.
2.  When auth is enabled, but the delegation token being generated is observed as null or empty, at some key points in the Controller gRPC service implementation class. 
The new logging statements being added log at `WARN` level, so it can be alarming for the admins/operators if the logging is unnecessary and excessive. The conditions mentioned above should be few if any, and therefore the …
> Issue 4135: Additional logging in Controller for easier debugging of missing delegation token issues

- gradle.properties
Changes the Pravega version in gradle.properties to 0.5.2-SNAPSHOT
Fixes #4144 
There is no code change, only a configuration change in `gradle.properties`. Any other change is an spurious change and should not be part of this PR.
`./gradlew install` should push artifacts to the local maven with the correct version.
> Issue 4144: Change version in gradle properties to 0.5.2-SNAPSHOT in r0.5

- client/src/main/java/io/pravega/client/state/impl/StateSynchronizerImpl.java
- client/src/test/java/io/pravega/client/state/impl/SynchronizerTest.java
Ensure the StateSynchronizer retries in case of multiple TruncatedDataException observed when trying to fetch updates on the state.
Fixes #4122 
It was observed that when a ReaderGroup has a large number of readers (1000 in case of the issue) multiple readers can trigger a compaction. This will lead to multiple `TruncatedDataException` being thrown when the StateSyncronizer is trying to fetch updates. This PR ensures the client retries in case of such repeated `TruncatedDataException`.
> Issue 4122: Retry in case of multiple TruncatedDataException are thrown during StateSynchronizer.fetchUpdates()

- client/src/main/java/io/pravega/client/ClientConfig.java
- client/src/main/java/io/pravega/client/netty/impl/ConnectionPoolImpl.java
- client/src/main/java/io/pravega/client/stream/impl/ControllerImpl.java
- client/src/test/java/io/pravega/client/ClientConfigTest.java
- common/src/main/java/io/pravega/common/util/BooleanUtils.java
- common/src/test/java/io/pravega/common/util/BooleanUtilsTests.java
- controller/src/main/java/io/pravega/controller/server/ControllerServiceConfig.java
- controller/src/main/java/io/pravega/controller/server/ControllerServiceStarter.java
- controller/src/main/java/io/pravega/controller/server/Main.java
- controller/src/main/java/io/pravega/controller/server/SegmentHelper.java
- controller/src/main/java/io/pravega/controller/server/impl/ControllerServiceConfigImpl.java
- controller/src/main/java/io/pravega/controller/util/Config.java
- segmentstore/server/host/src/main/java/io/pravega/segmentstore/server/host/stat/AutoScaleProcessor.java
- segmentstore/server/host/src/test/java/io/pravega/segmentstore/server/host/stat/AutoScaleProcessorTest.java
Adds support for enabling TLS for segment store while keeping it disabled for Controller. 
See the description section of issue #4157 to understand the motivation. 
Resolves #4157  
1. Adds an optional Controller configuration to declare that Segment Store has TLS enabled, even while it is not so for the Controller. This can be set by declaring using one of the following: 
* Java system property `controller.auth.segmentStoreTlsEnabled=true` via the manifest (containerized deployments) or command line (manual deloyments)
* `controller.auth.segmentStoreTlsEnabled=true` in Controller config file
* Environment variable `TLS_ENABLED_FOR_SEGMENT_STORE=true`
2. Adds additional flags in Client Config to support …
> Issue 4157: Support for Divergent TLS configuration for Controller and Segment Store

- client/src/main/java/io/pravega/client/stream/EventWriterConfig.java
Increase the default transaction timeout from 30 seconds to 90 seconds.
Related to #4147 
It was observed in mid scale longevity workloads that transactions could be aborted due to shorter transaction timeouts. When the controller receives the ping request the controller is already racing to abort the transaction. The shorter transaction timeout would lead to aborted transactions in scenario of Segment container fail-overs too.
The PR changes the default transaction timeout to 90 seconds to handle this.
> Issue 4147 : Increase default Transaction timeout.

- client/src/main/java/io/pravega/client/stream/impl/ControllerImpl.java
- client/src/test/java/io/pravega/client/stream/impl/ControllerImplTest.java
Pass timestamp to controller on txn commit
Allow timestamps to advance when written via transactional writers.
Passes the timestamp to the controller on the commit call. It also improves error handling by preserving more information in the event one of the txn calls to the controller fails. 
We should independently add a integration test of watermarking that uses transactional writers.
> Issue 3344: Pass timestamp to controller on txn commit

- client/src/main/java/io/pravega/client/segment/impl/SegmentOutputStreamImpl.java
* Update writer position before acking write.
In the event that a user chains a `noteTime` call off of an ack of an append, this change will allow the watermark bound to be tighter by including the event that was just appended. (This is not a question of correctness, as watermarks are by definition conservative. However it increases accuracy and is somewhat less surprising)
Updates the writer's position before it invokes the callback to notify the application of the ack. (As opposed to after)
> Issue 3344: Update offset order before acking.

- test/system/src/test/java/io/pravega/test/system/WatermarkingTest.java
Fixes following issues in WatermarkingSystemTest
1.     Watermarking system test's assertion on watermark.lowerTimebound <watermark.upperTimebound should be made <=
2.    We start two controllers but take uri of only one of them that we pass around. Use composite uri.
3.    Remove assertion for TimeWindow.upperbound with respect to event time bound.
Fixes #4182 
System test has 2 sets of incorrect assertions that are fixed. 
It also creates two controllers and shutsdown one of them. However, it uses a controller uri which takes IP of one of them arbitrarily. So if the controller with the specified uri is shutdown then any client instantiated after that is unable to connect to controller. 
So we use the …
> Issue 4182: Feature watermarking fix system test

- test/integration/src/test/java/io/pravega/test/integration/AppendTest.java
- test/integration/src/test/java/io/pravega/test/integration/ReadTest.java
- test/integration/src/test/java/io/pravega/test/integration/ReaderGroupTest.java
- test/integration/src/test/java/io/pravega/test/integration/StreamMetricsTest.java
- test/integration/src/test/java/io/pravega/test/integration/TransactionTest.java
- test/integration/src/test/java/io/pravega/test/integration/controller/server/DebugStreamSegmentsTest.java
- test/integration/src/test/java/io/pravega/test/integration/endtoendtest/AbstractEndToEndTest.java
Add timeouts to integration tests
Fixes #4189.
Adds timeouts to tests. No functional changes.
> Issue 4189: Add timeouts to integration tests

- config/config.properties
- segmentstore/server/src/main/java/io/pravega/segmentstore/server/CacheManager.java
- segmentstore/server/src/main/java/io/pravega/segmentstore/server/CacheUtilizationProvider.java
- segmentstore/server/src/main/java/io/pravega/segmentstore/server/logs/MemoryStateUpdater.java
- segmentstore/server/src/main/java/io/pravega/segmentstore/server/logs/OperationProcessor.java
- segmentstore/server/src/main/java/io/pravega/segmentstore/server/logs/Throttler.java
- segmentstore/server/src/main/java/io/pravega/segmentstore/server/logs/ThrottlerCalculator.java
- segmentstore/server/src/main/java/io/pravega/segmentstore/server/reading/ContainerReadIndex.java
- segmentstore/server/src/main/java/io/pravega/segmentstore/server/store/ServiceConfig.java
- segmentstore/server/src/test/java/io/pravega/segmentstore/server/CacheManagerTests.java
- segmentstore/server/src/test/java/io/pravega/segmentstore/server/TestCacheManager.java
- segmentstore/server/src/test/java/io/pravega/segmentstore/server/logs/MemoryStateUpdaterTests.java
- segmentstore/server/src/test/java/io/pravega/segmentstore/server/logs/ThrottlerTests.java
- Changed `CacheManager` to run every 1 second (down from 5). 
- This will cause more frequent cache evictions and with higher granularity.
- Added the ability to cancel a throttling delay, if that delay was due to the cache being over-utilized and if the cache utilization has since dropped below the throttling threshold.
- This will enable us to more quickly resume the ingestion pipeline if the data in the cache has been moved to Tier 2 before the throttling delay expired.
Fixes #4164.
- `CacheManager` will now accept `CacheCleanupListeners`; anyone interested in being notified when the cache evicts at least one item can register itself here. The `CacheManager` will notify these listeners after every …
> Issue 4164: (SegmentStore) Bugfix for possible ingestion pipeline starvation due to throttling

- controller/src/main/java/io/pravega/controller/store/stream/ZookeeperBucketStore.java
- controller/src/test/java/io/pravega/controller/store/stream/BucketStoreTest.java
- controller/src/test/java/io/pravega/controller/store/stream/InMemoryBucketStoreTest.java
- controller/src/test/java/io/pravega/controller/store/stream/ZkBucketStoreTest.java
For each note time from writer, we call `createIfNotExists` on zookeeper to add stream to the bucket for background watermarking processing. 
With this change we now call checkExists before calling `create` on zookeeper as reads to zk are cheap but writes are expensive. 
Fixes #4160
Whenever writer calls noteTime controller first attempts to add stream under watermarking bucket idempotently by calling `createIfNotExists` on zookeeper. 
Note: The actual WriterMark is stored in pravega tables and we are not optimizing on that. However, we can avoid writing to zookeeper and merely do a read from zookeeper by calling checkExists before calling create. …
> Issue 4160: Avoid writing to zookeeper for every NoteTime call

- shared/protocol/src/main/java/io/pravega/shared/protocol/netty/CommandDecoder.java
- shared/protocol/src/main/java/io/pravega/shared/protocol/netty/CommandEncoder.java
- shared/protocol/src/test/java/io/pravega/shared/protocol/netty/CommandDecoderTest.java
* In CommandDecoder: advance readerIndex to reflect data read.
Fixes #4211
Ensures that is there is an extra field in a wire command from the server to the client that the client does not attempt to interpret these extra bytes as a separate command.
> Issue 4211: Fix backward compatibility bug allowing unread fields

- segmentstore/server/src/main/java/io/pravega/segmentstore/server/logs/SegmentMetadataUpdateTransaction.java
- Fixing error message for `AttributeUpdateType.ReplaceIfEquals`.
Fixes #4213.
- The previous message format swapped the value of the expected and given values of an attribute. This change rephrases the error message to make it correct.
Not verifiable via any tests. Verify the `String.format` looks ok.
> Issue 4213: (SegmentStore) Fixing error message for `ReplaceIfEquals`

- client/src/main/java/io/pravega/client/stream/impl/ControllerImpl.java
- test/integration/src/test/java/io/pravega/test/integration/WatermarkingTest.java
Controller client is not using the writerId while calling commit grpc to controller. 
Fixes #4222
Fixes issue where controller client does not send writer id to controller. 
Added integration test to test transaction watermarking scenario.
> Issue 4222: In ControllerImpl transaction.commit should also send writer id to controller

- client/src/main/java/io/pravega/client/stream/EventStreamWriter.java
- client/src/main/java/io/pravega/client/stream/TimeWindow.java
- client/src/main/java/io/pravega/client/stream/impl/EventStreamWriterImpl.java
- client/src/main/java/io/pravega/client/stream/impl/WriterPosition.java
- client/src/test/java/io/pravega/client/stream/impl/EventStreamWriterTest.java
- test/testcommon/src/main/java/io/pravega/test/common/CollectingExecutor.java
* Support automatically noting time
* Cleanup some watermarking related Javadocs
Fixes #4217
If the user has configured automatic noting of time, the event reader runs a background task every 5 seconds to call the controller to note the time.
Note that this does not resolve: https://github.com/pravega/pravega/issues/4218 which is being put off until the next release.
> Issue 4217: Support automatically noting time

- docker/compose/swarm/scale_segmentstore
Scaling the segment store, for external deployment of Pravega on Docker Swarm, would result in image mismatch with the latest segment store image being pulled. Solved this by pulling segment store image consistent with the current deployment. 
Fixes #3982 
**What the code does**   
- Format the docker service list command and filter the segment stores.
- Used regex to determine image of the first segment store for the existing deployment. 
- Then modified the docker create service call by adding the image for the segment store. 
Deploy Pravega on Docker Swarm using Published IP (external) and scale the segment store.
> Issue 3982: Docker Swarm - scale segmentstore with correct version.

- test/integration/src/test/java/io/pravega/test/integration/StreamSeekTest.java
Fixes the test to not create mark stream, which it should never do explicitly.
Fixes #4238
I have explained the problem here: #4238 (comment)
The fix it to not create mark stream using the local controller explicitly by the test which will race with creation of original stream and its corresponding mark stream and hence cause BadKeyVersion errors.
The test should pass consistently
> Issue 4238: StreamSeekTest.testStreamSeek fails sporadically because it attempts to create mark stream explicitly 

- segmentstore/server/src/test/java/io/pravega/segmentstore/server/logs/operations/DeleteSegmentOperationTests.java
Make sure test does not generate invalid segmentId. Earlier the DeleteSegmentOperationTests created a DeleteSegmentOperation with a segment id between [0-1000). This generated invalid id 0, every once in a while.
Fixes #4230 
Makes sure test does not generate invalid segmentId by selecting segment ids between [1-1001)
Unit tests should continue to pass.
> Issue 4230: Fix flaky test DeleteSegmentOperationTests.

- segmentstore/server/src/main/java/io/pravega/segmentstore/server/containers/MetadataStore.java
- segmentstore/server/src/test/java/io/pravega/segmentstore/server/containers/MetadataStoreTestBase.java
- Fixed a "bug" in `MetadataStore.getOrAssignStreamSegmentId` where repeated, continuous invocations on the same segment would incorrectly report it as inexistent even after it gets created.
Fixes #4169.
Fixes the following scenario, which is induced by how the Controller is bootstrapping its metadata.
0. The segment does not currently exist.
1. The segment is queried (and `MetadataStore.getOrAssignStreamSegmentId` returns StreamSegmentNotExistsException)
2. The segment is immediately created afterwards.
3. The segment is queried again (and `MetadataStore.getOrAssignStreamSegmentId` should return its id).
The problem is that `MetadataStore.getOrAssignStreamSegmentId` needs to guarantee call ordering while …
> Issue 4169: (SegmentStore) Fixed a concurrency issue with segment id assignment when it doesn't exist.

- .travis.yml
- shared/metrics/src/test/java/io/pravega/shared/MetricsTagsTest.java
Switch from OracleJDK 8 to OpenJDK 8 in our Travis builds.
Fixes #4254.
This PR changes the JDK version used in our Travis builds from OracleJDK 8 to OpenJDK 8. The reason is twofold:
- Travis is apparently not allowing anymore the use of OracleJDK 8 in the image we are using (`xenial`).
- We are already using OpenJDK in other builds.
Travis builds should be passing.
> Issue 4254: Use OpenJDK 8 in Travis builds

- shared/metrics/src/test/java/io/pravega/shared/MetricsTagsTest.java
(2-3 concise points about the changes in this PR. When committing this PR, the committer is expected to copy the content of this section to the merge description box)
. Un-ignore MetricsTagsTest:testCreateHostTag which was failing due to switching from OracleJDK to openJDK 8.
. No further change yet as local test with openJDK is working.
Fixes #4256 
Un-ignore MetricsTagsTest:testCreateHostTag which was failing due to switching from OracleJDK to openJDK 8
All unit tests should pass.
> Issue 4256: bring back the ignored test with openJDK 8

- build.gradle
Ensure ePoll native transport is used by Pravega client on linux_x86_64.  
Fixes #4263
The Pravega client already has a dependency on `netty-transport-native-epoll`, which provides platform-specific transports i.e the jar already contains the shared library files. Also, the client dynamically switches back to NIO if EPOLL transport is not available. 
The PR ensures the `classifier ` is set `x86_64` to ensure epoll is used on linux based x86_64 systems.
All the tests should continue to pass. Inspect the pravega-client logs to ensure ePoll is infact used.
e.g: log snippets
```
2019-10-10 01:50:21,812 2273 [epollEventLoopGroup-4-1] INFO  i.p.s.p.netty.FailingReplyProcessor - Received …
```
> Issue 4263: Ensure Epoll transport is used by Pravega client.

- build.gradle
- gradle/java.gradle
- The custom gradle task `generateJavadoc` now depends on `delombok` task.
-  `lombok.Lombok` class missing related warnings are not generated by the SpotBugs check.
Fixes #4258 
No changes to functionality. 
This PR ensures  the following:
- Custom gradle task `generateJavadoc` also depends on `delombok` task similar to the javadoc task.
- `lombok.Lombok` classes are missing warnings are not generated by the SpotBugs check.
All the tests should pass and Lombok missing warnings should not be generated.
> Issue 4258: Fix Lombok related warnings during javadoc generation and spotbug check.

- client/src/main/java/io/pravega/client/stream/impl/ReaderGroupState.java
- client/src/test/java/io/pravega/client/stream/impl/SerializationTest.java
Ensure `UpdateDistanceToTail` updates `ReaderGroupState` only if `lastReadPosition` exists.
Fixes #4249 
During an upgrade, it was observed that `ReaderGroupState.UpdateDistanceToTail#update` method was attempting to update `lastReadPosition` even though `lastReadPositions` value after deserialization returned a null. This PR fixes this issue. 
> Issue 4249: Ensure UpdateDistanceToTail updates ReaderGroupState only if lastReadPosition exists.

- client/src/main/java/io/pravega/client/stream/impl/ControllerImpl.java
- client/src/test/java/io/pravega/client/stream/impl/ControllerImplTest.java
Send Long.MIN instead of 0 as default value if txn.commit does not supply time. 
Fixes #4291 
Transaction writers have two apis for committing - commit() and commit(time).
If first is called, it currently does not set the time in the TxnRequestBuilder which results in Long.default value to be serialized by protobuf whereby sending 0L as the time.
The controller records this time as writer's mark because it checks for greater than equal to 0.
This results in an unnecessary watermark being emitted which is completely avoidable.
Unit test added
> Issue 4291: txn.commit without time should default to Long.Min instead of 0

- test/system/src/test/resources/pravega_withAuth.properties
Auto scale system test was failing when authentication was enabled this was happening because the token and method that autoscale processor uses to communicate with the controller were not specified.
fixes #3777
It specifies both the token and the method for the autoscale processor to use for authentication with the controller
Run the AutoScale test with Auth Enabled
> Issue 3777: Fixed Auth enabled AutoScale Test

- segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/rocksdb/RocksDBCache.java
- segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/rocksdb/RocksDBMetrics.java
- shared/metrics/src/main/java/io/pravega/shared/MetricsNames.java
This PR improves RocksDB configuration, specially to prevent compaction to be a bottleneck. Moreover, we have added few metrics to better understand the behavior of the cache.
Fixes #4158. 
This PR adds some settings to RocksDB configuration to improve its performance in various aspects, but specially regarding data compaction. In the following, we specify the motivation behind each of the changes in configuration:
_Improvement of reads/read amplification_:
- `setBlockCache(new LRUCache(readCacheSizeMB * 1024L * 1024L, 4))`: In our current configuration, we are missing the to instantiate an actual cache. While if we leave this unset RocksDB internally uses an 8MB cache, it is better to expose it as we can …
> Issue 4158: Potential starvation of Tier 2 writes with unthrottled clients

- gradle.properties
Removes -SNAPSHOT suffix from Pravega version in gradle.properties in preparation to release 0.6.0.
Fixes #4312
There is no code change, only a change to the Pravega version in gradle.properties.
Build should succeed regularly and artifacts should not contain the commit id suffix.
> Issue 4312: Change pravega version to 0.6.0

- gradle.properties
Updates Pravega version in master to 0.7.0-SNAPSHOT
Fixes #4310 
There is no code change. It updates the Pravega version in gradle.properties.
./gradlew install should produce the correct version.
> Issue 4310: Change Pravega version in master to 0.7.0-SNAPSHOT

- segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/rocksdb/RocksDBCache.java
Remove RocksDB option that induces library linkage conflicts in Windows.
Fixes #4319.
Removes a RocksDB config option that seems to induce a library linkage problem in Windows. All our tests in Linux-based OS did not show that problem.
All tests should be passing as usual.
> Issue 4319: Conflicting RocksDB config option in Windows (lib linkage problem)

- gradle.properties
Change pravega version in r0.6 branch to 0.6.1-SNAPSHOT
Fixes #4343 
Changes pravega version in gradle.properties
> Issue 4343: Change pravega version in r0.6 branch to 0.6.1-SNAPSHOT

- controller/src/main/java/io/pravega/controller/server/rpc/auth/AuthHandlerManager.java
- controller/src/main/java/io/pravega/controller/server/rpc/auth/GrpcAuthHelper.java
- controller/src/main/java/io/pravega/controller/server/rpc/auth/RESTAuthHelper.java
- controller/src/main/java/io/pravega/controller/server/rpc/grpc/v1/ControllerServiceImpl.java
- controller/src/test/java/io/pravega/controller/server/rpc/auth/ControllerGrpcAuthFocusedTest.java
- segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/rocksdb/RocksDBCache.java
- shared/authplugin/src/main/java/io/pravega/auth/AuthException.java
- test/integration/src/test/java/io/pravega/test/integration/BatchClientAuthTest.java
Improve exception handling and logging in gRPC interface to distinguish clearly among these three error conditions: 
1. A condition representing an authentication failure
2. A condition representing an authorization failure
3. A condition representing an internal failure
This enables easier debugging of issues, as well as enables the client to handle these different conditions properly. For example, the client can retry upon encountering the 3rd failure, but avoid doing that for the 1st and the 2nd.
Fixes #4334 & #3814. 
The code does the following: 
* Makes `AuthException` (the parent of both `AuthenticationException` and `AuthorizationException`) abstract, so that it cannot be thrown (but can be caught in …
> Issue 4334: Fix auth and related exception handling

- controller/src/main/java/io/pravega/controller/store/stream/AbstractStreamMetadataStore.java
- controller/src/main/java/io/pravega/controller/store/stream/PravegaTablesScope.java
- controller/src/test/java/io/pravega/controller/store/stream/PravegaTablesStreamMetadataStoreTest.java
Complete creation of partially created scopes on pravega tables. 
Fixes #4349 
On Pravega tables, scope creation has two steps -
1. add new `scope` to scopes table with a unique id
2. create streamsInScope table for the new scope
If scope creation failed after step 1, subsequent attempts to create scope returned SCOPE_EXISTS status because it simply checked the presence of scope in scopes table. 
The fix is to perform all idempotent steps of scope creation upon each request and not throw DataExists if the entry exists in the first table. 
So in `PravegaTableScopes.createScope` method, we catch DataExists and continue creating the `streamsInScope` table …
> Issue 4349: Complete partially created scopes before throwing ScopeExists

- segmentstore/server/host/src/main/java/io/pravega/segmentstore/server/host/handler/ConnectionTracker.java
- Removed an assertion check that could incorrectly fire in concurrent tests.
Fixes #4133 
- Removed an assertion check that was meant to perform a sanity check, enabled only during tests.
- In a concurrent environment, it would have been possible that two or more calls for the same "connection" (`AppendProcessor`) would update the `AppendProcessor`'s outstanding bytes in one order yet invoke `ConnectionTracker.updateOutstandingBytes` in a different order. Even though the resulting data is correct, such a sequence of events would have this assertion incorrectly fire if the `AppendProcessor`'s outstanding value is greater than the total outstanding value
- Example:
- Call 1: …
> Issue 4351: Removed assertion check from ConnectionTracker

- client/src/main/java/io/pravega/client/security/auth/DelegationTokenProvider.java
- client/src/main/java/io/pravega/client/security/auth/EmptyTokenProviderImpl.java
- client/src/main/java/io/pravega/client/security/auth/JwtTokenProviderImpl.java
- client/src/main/java/io/pravega/client/security/auth/StringTokenProviderImpl.java
- client/src/main/java/io/pravega/client/segment/impl/AsyncSegmentInputStreamImpl.java
- client/src/main/java/io/pravega/client/segment/impl/ConditionalOutputStreamImpl.java
- client/src/main/java/io/pravega/client/segment/impl/SegmentMetadataClientImpl.java
- client/src/main/java/io/pravega/client/segment/impl/SegmentOutputStreamImpl.java
- client/src/test/java/io/pravega/client/security/auth/DelegationTokenProviderFactoryTest.java
- client/src/test/java/io/pravega/client/security/auth/JwtTokenProviderImplTest.java
- client/src/test/java/io/pravega/client/segment/impl/SegmentOutputStreamTest.java
Make the `DelegationTokenProvider` interface operation `retrieveToken()` asynchronous and make its invocations in client non-blocking, in order to avoid client-side deadlocks. 
Fixes #4352 
* Makes the `retrieveToken()` operation of the `DelegationTokenProvider` interface asynchronous, and modifies the following implementation classes accordingly: 
* `JwtTokenProviderImpl` 
* `EmptyTokenProviderImpl` 
* `StringTokenProviderImpl`
* Modifies the following client classes to avoid blocking, by leveraging `CompletableFuture`'s `CompletionStage` tasks: 
* `AsyncSegmentInputStreamImpl`
* `ConditionalOutputStreamImpl.java`
* `SegmentMetadataClientImpl.java`
* `SegmentOutputStreamImpl.java`
* Modifies existing tests …
> Issue 4352: Turn retrieve token operation of DelegationTokenProvider asynchronous

- controller/src/main/java/io/pravega/controller/server/ControllerServiceStarter.java
- controller/src/main/java/io/pravega/controller/task/Stream/StreamMetadataTasks.java
- controller/src/main/java/io/pravega/controller/task/Stream/StreamTransactionMetadataTasks.java
Split controller thread pools on the controller to avoid a potential deadlock.
Fix #4372 on r0.6
* `SegmentSelector.refreshSegmentEventWriters` is invoking the controller and blocking on it in the current thread. If this code is executed on the controller this might cause a potential deadlock.
* StreamMetadataTasks and StreamMetadataTransaction tasks invoke writes on the ForkJoinPool threads. With this PR the invocation is performed on the eventExecutor threadpool.
> Issue 4372: Split controller thread pools to avoid potential deadlock.

- controller/src/main/java/io/pravega/controller/store/stream/PersistentStreamBase.java
- controller/src/test/java/io/pravega/controller/store/stream/StreamTestBase.java
* Call noteWriterMark once per writer after committing a batch of transactions. 
Fixes #4357 
We run commit workflow for multiple tranasctions in a single batch at the end of which we used to call noteWriterMark corresponding to each transaction. 
This is suboptimal for two reasons - 
1. we make mutliple calls for the same writer overwriting the just written previous value
2. since all the marks for same writer was updated concurrently, there was a possibility of WriteConflict which would be unnecessarily retried. 
The fix we have performed is as follows:
1. group transactions by writer ids
2. take the latest transaction for each writer and use the …
> Issue 4357: Call noteWriterMark once per writer after committing a batch of transactions

- client/src/main/java/io/pravega/client/segment/impl/SegmentMetadataClientImpl.java
- client/src/test/java/io/pravega/client/segment/impl/SegmentMetadataClientTest.java
Ensure we do not retry if the segment is already truncated while attempting to truncate a segment.
Fixes #4383 
Ensure `SegmentIsTruncated` response from the Segmentstore is handled while attempting to truncate segments using SegmentMetadataClient.
> Issue 4383: Fix exception handling during state synchronizer compaction.

- shared/protocol/src/main/java/io/pravega/shared/segment/StreamSegmentNameUtils.java
- shared/protocol/src/test/java/io/pravega/shared/segment/StreamSegmentNameUtilsTests.java
Signed-off-by: Andrey Kurilov <andrey.kurilov@emc.com>
Optimize the `updateSegmentTags()` method for better small events write performance.
Avoid using `String.split` in `updateSegmentTags`, use the precompiled regexp instead.
Fixes #4374
Basic testing shows that the updateSegmentTags takes twice less CPU time. The resulting small (1 byte) events rate is higher by 7%.
> Issue 4374: Optimize the updateSegmentTags method

- segmentstore/server/host/src/test/java/io/pravega/segmentstore/server/host/handler/PravegaRequestProcessorTest.java
- segmentstore/server/src/main/java/io/pravega/segmentstore/server/reading/CompletableReadResultEntry.java
- segmentstore/server/src/main/java/io/pravega/segmentstore/server/reading/FutureReadResultEntry.java
- segmentstore/server/src/main/java/io/pravega/segmentstore/server/reading/FutureReadResultEntryCollection.java
- segmentstore/server/src/main/java/io/pravega/segmentstore/server/reading/ReadResultEntryBase.java
- segmentstore/server/src/main/java/io/pravega/segmentstore/server/reading/RedirectedReadResultEntry.java
- segmentstore/server/src/main/java/io/pravega/segmentstore/server/reading/StreamSegmentReadIndex.java
- segmentstore/server/src/main/java/io/pravega/segmentstore/server/reading/StreamSegmentReadResult.java
- segmentstore/server/src/test/java/io/pravega/segmentstore/server/reading/ContainerReadIndexTests.java
- segmentstore/server/src/test/java/io/pravega/segmentstore/server/reading/FutureReadResultEntryCollectionTests.java
- Fixed a memory leak that can be triggered by abandoning Future Reads without any segment write activity.
Fixes #4369.
- Every `FutureReadResultEntry` gets assigned a callback to invoke when it is completed (successfully or not). This is assigned when being registered into the `FutureReadResultEntryCollection` (of the Read Index) and unassigned when being polled from that collection.
- This callback, when invoked, will cause that entry to be unregistered from the collection.
- The callback should be unregistered when polled out of the collection because the next step that the Read Index would take is to complete it, which means it would have caused the collection to unnecessarily search for it.
- This has …
> Issue 4369: (SegmentStore) Fix memory leak with Future Reads

- controller/src/main/java/io/pravega/controller/store/stream/AbstractStreamMetadataStore.java
- controller/src/main/java/io/pravega/controller/store/stream/PersistentStreamBase.java
- controller/src/main/java/io/pravega/controller/store/stream/Stream.java
- controller/src/main/java/io/pravega/controller/store/stream/StreamMetadataStore.java
- controller/src/test/java/io/pravega/controller/store/stream/StreamMetadataStoreTest.java
To expose additional apis on StreamMetadataStore interface to get all relevant metadata
Fixes #4020 
There are three metadata record types that are part of internal metadata schema but are not exposed over StreamMetadataStore interface. 
However, for purposes of pravega cli, we need to expose all such records so that they can be accessed by the admin tool. 
Unit test added
> Issue 4020: Expose additional apis on StreamMetadataStore interface for Pravega Cli

- client/src/main/java/io/pravega/client/segment/impl/SegmentMetadataClientImpl.java
- client/src/main/java/io/pravega/client/segment/impl/SegmentOutputStreamImpl.java
- client/src/test/java/io/pravega/client/segment/impl/SegmentMetadataClientTest.java
- client/src/test/java/io/pravega/client/segment/impl/SegmentOutputStreamTest.java
- segmentstore/server/host/src/test/java/io/pravega/segmentstore/server/host/handler/AppendProcessorAuthFailedTest.java
- segmentstore/server/host/src/test/java/io/pravega/segmentstore/server/host/handler/PravegaRequestProcessorAuthFailedTest.java
- shared/authplugin/src/main/java/io/pravega/auth/TokenException.java
- shared/security/src/main/java/io/pravega/shared/security/token/JsonWebToken.java
- shared/security/src/test/java/io/pravega/shared/security/token/JsonWebTokenTest.java
- test/integration/src/test/java/io/pravega/test/integration/DelegationTokenTest.java
Ensure that the client retries the request to segment store if the segment store throws an error indicating token expiry. Doing so will ensure that a new delegation token will be obtained after reauthentication and reauthorization with the Controller and used in the retried request. 
Resolves #4390. 
- Modifies `io.pravega.client.segment.impl.SegmentMetadataClientImpl` class to throw `ConnectionFailedException` upon receiving a response from the segment store indicating delegation token expiry. This will ensure that the request is retried. 
- Modifies `io.pravega.client.segment.impl.SegmentOutputStreamImpl` class to not release the connection upon encountering token expiry indicator from the segment store. …
> Issue 4390: Ensure retries by client when delegation token expires

- client/src/main/java/io/pravega/client/stream/impl/ModelHelper.java
- client/src/main/java/io/pravega/client/stream/impl/Pinger.java
- client/src/test/java/io/pravega/client/stream/impl/ControllerImplTest.java
- client/src/test/java/io/pravega/client/stream/impl/PingerTest.java
- controller/src/main/java/io/pravega/controller/task/Stream/StreamTransactionMetadataTasks.java
- controller/src/test/java/io/pravega/controller/task/Stream/StreamTransactionMetadataTasksTest.java
For completed transactions, `pingTransaction` calls into controller will no longer throw exception, instead it will either return the completion status (COMMITTED or ABORTED) or if the transaction is not found it will return UNKNOWN. 
Fixes #4396 
In StreamTransactionMetadataTask.pingTransaction method, if it gets DNF exception while attempting to read activeTxnRecord, it fetches the completed txn record for the given txn and returns the txn status accordingly. If completedTxn does not have the record for the transaction, return status.UNKNOWN. 
Controller Client:
Controller client translates the status.UNKNOWN to throw NOT_FOUND exception. 
Pinger, …
> Issue 4396: Respond with meaningful status to ping transaction if transaction is already committed or aborted

- client/src/main/java/io/pravega/client/stream/EventWriterConfig.java
- client/src/main/java/io/pravega/client/stream/impl/EventStreamWriterImpl.java
- client/src/main/java/io/pravega/client/stream/impl/ModelHelper.java
- client/src/main/java/io/pravega/client/stream/impl/Pinger.java
- client/src/main/java/io/pravega/client/stream/impl/TransactionalEventStreamWriterImpl.java
- client/src/test/java/io/pravega/client/stream/EventWriterConfigTest.java
- client/src/test/java/io/pravega/client/stream/impl/ControllerImplTest.java
- client/src/test/java/io/pravega/client/stream/impl/EventStreamWriterTest.java
- client/src/test/java/io/pravega/client/stream/impl/PingerTest.java
- client/src/test/java/io/pravega/client/stream/impl/TransactionalEventStreamWriterTest.java
- controller/src/main/java/io/pravega/controller/task/Stream/StreamTransactionMetadataTasks.java
- controller/src/test/java/io/pravega/controller/task/Stream/StreamTransactionMetadataTasksTest.java
- test/integration/src/test/java/io/pravega/test/integration/endtoendtest/EndToEndTxnWithTest.java
Cherry-picks changes from master to r0.6
Fixes #4406
Cherry picks :
```
Issue 4396: For completed transactions the ping fails with DataNotFoundException (#4397)
Issue 4147: Adjust txn ping to perform multiple pings per transaction (#4400)
```
> Issue 4406: Cherry pick 4396 and 4147 into r0.6

- config/config.properties
- segmentstore/server/src/main/java/io/pravega/segmentstore/server/CacheManager.java
- segmentstore/server/src/main/java/io/pravega/segmentstore/server/CacheUtilizationProvider.java
- segmentstore/server/src/main/java/io/pravega/segmentstore/server/logs/DataFrameBuilder.java
- segmentstore/server/src/main/java/io/pravega/segmentstore/server/logs/MemoryStateUpdater.java
- segmentstore/server/src/main/java/io/pravega/segmentstore/server/logs/OperationProcessor.java
- segmentstore/server/src/main/java/io/pravega/segmentstore/server/logs/Throttler.java
- segmentstore/server/src/main/java/io/pravega/segmentstore/server/logs/ThrottlerCalculator.java
- segmentstore/server/src/main/java/io/pravega/segmentstore/server/reading/ContainerReadIndex.java
- segmentstore/server/src/test/java/io/pravega/segmentstore/server/CacheManagerTests.java
- segmentstore/server/src/test/java/io/pravega/segmentstore/server/TestDurableDataLog.java
- segmentstore/server/src/test/java/io/pravega/segmentstore/server/logs/MemoryStateUpdaterTests.java
- segmentstore/server/src/test/java/io/pravega/segmentstore/server/logs/OperationProcessorTests.java
- segmentstore/server/src/test/java/io/pravega/segmentstore/server/logs/ThrottlerCalculatorTests.java
- segmentstore/server/src/test/java/io/pravega/segmentstore/server/logs/ThrottlerTests.java
- segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/bookkeeper/BookKeeperConfig.java
- segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/bookkeeper/BookKeeperLog.java
- segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/bookkeeper/DebugLogWrapper.java
- segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/bookkeeper/WriteQueue.java
- segmentstore/storage/impl/src/test/java/io/pravega/segmentstore/storage/impl/bookkeeper/BookKeeperConfigTest.java
- segmentstore/storage/impl/src/test/java/io/pravega/segmentstore/storage/impl/bookkeeper/BookKeeperLogTests.java
- segmentstore/storage/impl/src/test/java/io/pravega/segmentstore/storage/impl/bookkeeper/WriteQueueTests.java
- segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/DurableDataLog.java
- segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/ThrottleSourceListener.java
- segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/WriteSettings.java
- segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/mocks/InMemoryDurableDataLog.java
- segmentstore/storage/src/test/java/io/pravega/segmentstore/storage/DurableDataLogTestBase.java
- segmentstore/storage/src/test/java/io/pravega/segmentstore/storage/WriteSettingsTests.java
- segmentstore/storage/src/test/java/io/pravega/segmentstore/storage/mocks/InMemoryDurableDataLogTests.java
- Changed configuration defaults: `bookkeeper.bkWriteTimeoutMillis=60000`, `bookkeeper.readTimeoutMillis=30000`
- Added another throttler to the Segment Store that manages the in-flight data sent to BookKeeper.
Fixes #4399.
- Increased the defaults for BK Write and Read timeouts to larger values. This helps reduce instability in those deployments where BK is very slow. A write timeout would cause a Ledger to be closed, thus triggering an avalanche of Ledger Rollovers and retries, further overwhelming the system.
- Added a new Throttler in the Segment Store's `OperationProcessor` that works along the following lines
- Throttling is triggered only if the recent BK Write Latencies exceed 10% of …
> Issue 4399: BookKeeper Write Throttling

- client/src/main/java/io/pravega/client/security/auth/JwtTokenProviderImpl.java
- client/src/main/java/io/pravega/client/stream/impl/ControllerImpl.java
- client/src/test/java/io/pravega/client/security/auth/JwtTokenProviderImplTest.java
Fix a bug that prevents `tokenRefreshFuture` from getting reset, preventing the `DelegationTokenProvider` from working properly after errors such as a failed attempt to obtain a new delegation token.  The `tokenRefreshFuture` remained in `iscompletedExceptionally` state forever, and therefore the `JwtTokenProviderImpl` failed to retrieve token post that event. 
Fixes #4409 
Resets `tokenRefreshFuture` shared variable to `null` if there is an exception in obtaining a new delegation token, so that the logic to refresh the token will be executed again on next attempt. 
All existing and new tests must pass. 
System tests must pass, with and without `auth` enabled.
> Issue 4409: Reset tokenRefreshFuture upon exception in obtaining a new delegation token

- segmentstore/server/host/src/main/java/io/pravega/segmentstore/server/host/handler/AppendProcessor.java
- segmentstore/server/host/src/main/java/io/pravega/segmentstore/server/host/handler/WriterState.java
- segmentstore/server/host/src/test/java/io/pravega/segmentstore/server/host/handler/AppendProcessorTest.java
- segmentstore/server/host/src/test/java/io/pravega/segmentstore/server/host/handler/WriterStateTests.java
- Changed the AppendProcessor to send error messages back to the client only after all appends initiated prior to that error complete.
Fixes #4393.
- Moved `WriterState` out of `AppendProcessor` in order to write unit tests against it.
- Upon encountering a failed append, the `AppendProcessor` will take note of the current `lastStoredEventNumber` and delay handling the exception until after all Appends with Event Numbers up to that one are completed (successfully or not). 
- The `AppendProcessor` will record all failed appends and send error message for each such failure. 
- The `AppendProcessor` will keep a `WriterState` registered until there are no more in-flight requests or errors to be handled. This …
> Issue 4393: Fixing error sequencing in AppendProcessor

- client/src/main/java/io/pravega/client/stream/Serializer.java
- shared/protocol/src/main/java/io/pravega/shared/protocol/netty/WireCommands.java
- test/integration/src/test/java/io/pravega/test/integration/AppendTest.java
- test/system/src/test/java/io/pravega/test/system/LargeEventTest.java
* Increases the size limit for an event from 1MB to 8MB
* Increases the wire command size limit from 8MB to 16MB
Address low hanging fruit on #3679
Changes size limit constants.
Everything should continue to work as normal. We should complete system tests runs before merging.
> Issue 3679: Increase maximum event size limit.

- segmentstore/server/host/src/test/java/io/pravega/segmentstore/server/host/HDFSIntegrationTest.java
Issue 3503: Disable HDFSIntegrationTest.
The HDFSIntegrationTest has been unstable and fails with intermittent failures. This causes builds with changes unrelated to HDFS to fail. 
Disabling HDFSIntegrationTest for a short while until it gets completely rewritten/replaced as part of PDP-34.
Short term mitigation for #3503 until HDFSIntegrationTest gets completely rewritten/replaced as part of PDP-34
Disable HDFSIntegrationTest.
HDFSIntegrationTest should not be invoked.
> Issue 3503: Disable HDFSIntegrationTest.

- bindings/src/main/java/io/pravega/storage/extendeds3/ExtendedS3StorageConfig.java
- bindings/src/test/java/io/pravega/storage/extendeds3/ExtendedS3StorageTest.java
Current logic in ExtendedS3StorageConfig incorrectly assumes that root has a trailing '/' character. If this is not the case then the S3 storage is wrongly initialized and results in invalid paths/urls.
This change fixes the bug by adding the / char when it is missing.
Fix bug in ExtendedS3StorageConfig to correctly handle missing trailing `/` in root.
Fixes #4412 
This change fixes it by adding the / char when it is missing.
> Issue 4412: Fix bug in ExtendedS3StorageConfig to correctly handle missing trailing `/` in root.

- segmentstore/server/src/main/java/io/pravega/segmentstore/server/CacheManager.java
- segmentstore/server/src/main/java/io/pravega/segmentstore/server/attributes/SegmentAttributeBTreeIndex.java
- segmentstore/server/src/main/java/io/pravega/segmentstore/server/reading/ReadIndexSummary.java
- segmentstore/server/src/main/java/io/pravega/segmentstore/server/tables/ContainerKeyCache.java
- segmentstore/server/src/main/java/io/pravega/segmentstore/server/tables/SegmentKeyCache.java
- segmentstore/server/src/test/java/io/pravega/segmentstore/server/CacheManagerTests.java
- segmentstore/server/src/test/java/io/pravega/segmentstore/server/reading/ReadIndexSummaryTests.java
- Fixed a bug in `CacheManager` where it could excessively evict items from the cache as soon as they become eligible even if there was no cache pressure present.
Fixes #4204.
- Unified the reporting logic of all Cache Clients (`StreamSegmentReadIndex`, `SegmentAttributeBTreeIndex` and `SegmentKeyCache`) into a common method that is now subject to unit tests.
- Updated the `Cache Manager` to
- Better handle inconsistent input from its clients
- This is slightly redundant with the unification logic above, but it provides a failsafe in case we add new types of clients in the future which may exhibit this bug.
- Be more active in case the cache utilization exceeds configured thresholds.
- Previously, the cache …
> Issue 4204: (SegmentStore) Fixed excessive cache eviction bug

- client/src/main/java/io/pravega/client/stream/impl/ControllerImpl.java
- client/src/test/java/io/pravega/client/stream/impl/ControllerImplTest.java
Adds deadline to each grpc call individually. 
Fixes #4448 
With #4403 we introduced a bug where the deadline was added to the client stub as opposed to each request. This meant that after deadline expiration, all requests on the stub would fail. 
So with this we have added deadline to all individual calls and removed it from the constructor. 
Unit test updated.
> Issue 4448: Add `withDeadlineAfter` to each rpc call in controller client

- test/system/src/test/java/io/pravega/test/system/LargeEventTest.java
Signed-off-by: anishakj <anisha.kj@emc.com>
Two of the tests were using the same name, due to that docker swarm system tests were failing.
`io.pravega.test.system.LargeEventTest.simpleTest`
`io.pravega.test.system.LargeEventTest.simpleTest`
#4458
Renamed the `simpleTest` to `largeEventSimpleTest`
Docker swarm system tests are  passed
> Issue 4458: Fixed docker swarm system test failure

- controller/src/test/java/io/pravega/controller/server/bucket/WatermarkWorkflowTest.java
Fixes the test issue where active writer is checked with a very small timeout which makes it flaky.
Fixes #4368 
The test wants to check that a writer has not timed out, however, it checks with a very small timeout value of 1 ms which makes the test flaky.  
Changed the timeout value to 1000 ms. 
Test should pass consistently
> Issue 4368: Sporadic failure in Watermark workflow test

- controller/src/main/java/io/pravega/controller/store/stream/PersistentStreamBase.java
- controller/src/test/java/io/pravega/controller/server/bucket/WatermarkWorkflowTest.java
- controller/src/test/java/io/pravega/controller/server/eventProcessor/ScaleRequestHandlerTest.java
- controller/src/test/java/io/pravega/controller/store/stream/PravegaTablesStreamMetadataStoreTest.java
- controller/src/test/java/io/pravega/controller/store/stream/StreamMetadataStoreTest.java
- controller/src/test/java/io/pravega/controller/store/stream/StreamTestBase.java
- controller/src/test/java/io/pravega/controller/store/stream/ZKStreamMetadataStoreTest.java
- controller/src/test/java/io/pravega/controller/store/stream/ZkStreamTest.java
- test/integration/src/test/java/io/pravega/test/integration/endtoendtest/EndToEndTruncationTest.java
Enforce stream configuration for minimum number of segments before scale workflow execution. 
Fixes #4445 
Currently the check for ensuring that a stream does not scale below minimum number of segments is only performed during auto-scale. 
And even that had a bug where if two concurrent auto-scale requests are processed, then two scale events are submitted, each independently thinking it will honor the minimum segment count. 
This had two problems:
1. there is no min segment enforcement for manual scale
2. two auto scale requests could result in two submissions. The request that will be executed second should be rejected.  
So the fix for both these is …
> Issue 4445: Check to ensure a stream does not scale below minimum configured segments

- client/src/main/java/io/pravega/client/stream/impl/ControllerImpl.java
- client/src/test/java/io/pravega/client/stream/impl/ControllerImplTest.java
- client/src/test/resources/mockito-extensions/org.mockito.plugins.MockMaker
* Ensure the client waits before the termination is completed.
* Ensure exceptions related to the credential plugin are handled and the channel is closed.
Fixes #4471
`io.grpc.ManagedChannel#shutdownNow` only triggers a forceful shutdown. Although forceful, the shutdown process is still not instantaneous. The fix ensures `io.grpc.ManagedChannel#awaitTermination` is used to handle this. 
> Issue 4471: Fix controller client channel termination logic.

- gradle.properties
Change pravega version in r0.6 branch from 0.6.1 to 0.6.2-snapshot
Fixes #4473 
Changes version to 0.6.2-SNAPSHOT in gradle.properties file
Subsequent builds should be generated with 0.6.2-SNAPSHOT as pravega version
> Issue 4473:  Bump snapshot version in 0.6.1 to 0.6.2-SNAPSHOT 

- controller/src/main/java/io/pravega/controller/eventProcessor/EventProcessorConfig.java
- controller/src/main/java/io/pravega/controller/eventProcessor/EventProcessorSystem.java
- controller/src/main/java/io/pravega/controller/eventProcessor/RequestHandler.java
- controller/src/main/java/io/pravega/controller/eventProcessor/impl/ConcurrentEventProcessor.java
- controller/src/main/java/io/pravega/controller/eventProcessor/impl/EventProcessorGroupImpl.java
- controller/src/main/java/io/pravega/controller/eventProcessor/impl/EventProcessorSystemImpl.java
- controller/src/main/java/io/pravega/controller/eventProcessor/impl/SerializedRequestHandler.java
- controller/src/main/java/io/pravega/controller/server/eventProcessor/ControllerEventProcessorConfig.java
- controller/src/main/java/io/pravega/controller/server/eventProcessor/ControllerEventProcessors.java
- controller/src/main/java/io/pravega/controller/server/eventProcessor/impl/ControllerEventProcessorConfigImpl.java
- controller/src/test/java/io/pravega/controller/eventProcessor/impl/ConcurrentEventProcessorTest.java
- controller/src/test/java/io/pravega/controller/eventProcessor/impl/EventProcessorTest.java
- controller/src/test/java/io/pravega/controller/eventProcessor/impl/SerializedRequestHandlerTest.java
- controller/src/test/java/io/pravega/controller/server/eventProcessor/ControllerEventProcessorsTest.java
- controller/src/test/java/io/pravega/controller/server/eventProcessor/RequestHandlersTest.java
- controller/src/test/java/io/pravega/controller/server/eventProcessor/ScaleRequestHandlerTest.java
- controller/src/test/java/io/pravega/controller/server/eventProcessor/requesthandlers/RequestProcessorTest.java
- controller/src/test/java/io/pravega/controller/task/Stream/StreamTransactionMetadataTasksTest.java
- test/integration/src/test/java/io/pravega/test/integration/controller/server/EventProcessorTest.java
1. Adds logic in EventProcessorGroup to identify idle and overloaded readers in readergroup and perform.
2. While shutting down an overloaded reader cancel any outstanding request on its event processor cell.
3. In Concurrent event processor, complete the shutdown only after all outstanding requests have been terminated. 
Fixes #2183
When a readergroup has idle as well as overloaded readers, a rebalance is triggered. 
The EventProcessor group, which owns the readergroup for the eventprocessor, periodically checks if there are idle readers in the readergroup. If there are idle readers and this instance of EventProcessorGroup owns an overloaded reader …
> Issue 2183: Rebalance readers in event processors when new controllers are added

- controller/src/main/java/io/pravega/controller/store/stream/PersistentStreamBase.java
- controller/src/test/java/io/pravega/controller/store/stream/StreamTestBase.java
Cherry-picks changes from master to r0.6
Fixes #4481 
Cherry picks :
`Issue 4357:` Call noteWriterMark once per writer after committing a batch of transactions (#4378 )
> Issue 4481: Cherry-pick PR 4378 to r0.6

- test/integration/src/test/java/io/pravega/test/integration/StreamMetricsTest.java
Ensure that metrics are available in StreamMetricsTest.testTransactionMetrics before performing assertions.
Fixes #4467.
In `StreamMetricsTest`, the new `testTransactionMetrics` adds assertions about whether Transaction metrics are being correctly published or not. However, the assertions on Transactions metrics are immediately performed after transaction operations. This induces a race condition that, especially on Travis, metrics are not yet published when we execute the assertions on them, thus leading to a NPE. This PR makes the test to wait for the metrics to exist prior asserting their values. 
Executed multiple Travis builds (+10) and we have not observed this test to fail yet.
> Issue 4467: Observed NPE in StreamMetricsTest on travis

- common/src/main/java/io/pravega/common/util/BufferedIterator.java
- common/src/test/java/io/pravega/common/util/BufferedIteratorTests.java
- config/config.properties
- segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/bookkeeper/BookKeeperConfig.java
- segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/bookkeeper/LogReader.java
- segmentstore/storage/impl/src/test/java/io/pravega/segmentstore/storage/impl/bookkeeper/BookKeeperConfigTest.java
- When performing a Ledger Read (Segment Container Recovery) the Ledger is now read in batches, as opposed from all at once.
Fixes #4454.
- `LedgerHandle.readEntries` loads all the entries in the Java Heap before returning them as an `Enumeration`. This can cause Java Heap OOM if there is significant memory pressure and we need to load a full ledger (1GB).
- `LogReader` has been changed to read the ledger in batches (configurable via setting `bookkeeper.readBatchSize`, defaulted to 64 (entries at once)) instead of the whole thing at once. Nothing is changed from the POV of the upstream code.
- Introduced a `BufferedIterator` in `common` that enables this behavior (for purposes of reuse and proper testing). …
> Issue 4454: Reading BK Ledger Entries in batches

- segmentstore/server/src/main/java/io/pravega/segmentstore/server/reading/StreamSegmentReadIndex.java
- segmentstore/server/src/test/java/io/pravega/segmentstore/server/reading/ContainerReadIndexTests.java
- Fixed a bug in `StreamSegmentReadIndex` where it would have been possible for an append data to get lost if the `append` method was invoked concurrently with a cache eviction (`updateGenerations`).
Fixes #4452.
- See parent issue comment for reproduction scenario (https://github.com/pravega/pravega/issues/4452#issuecomment-566168592)
- If a cache eviction occurs during a call to `append`, it would have been possible to append to a `ReadIndexEntry` that was just evicted or about to be. This would have led to temporary data unavailability and an eventual segment container restart (which would have addressed the issue).
- The bug was caused because even though we updated the Read Index Structure under its …
> Issue 4452: (SegmentStore) Fixed Read Index Append Concurrency bug

- client/src/main/java/io/pravega/client/batch/impl/BatchClientFactoryImpl.java
- client/src/main/java/io/pravega/client/security/auth/JwtTokenProviderImpl.java
- client/src/test/java/io/pravega/client/batch/impl/BatchClientImplTest.java
- test/integration/src/test/java/io/pravega/test/integration/DelegationTokenTest.java
Use DelegationTokenProvider for BatchClient.
Fixes #4443 
Leverage DelegationTokenProvider to retrieve the delegation token on BatchClient.
> Issue 4443: Use DelegationTokenProvider for BatchClient.

- build.gradle
- dist/conf/logback.xml
- shared/metrics/src/main/java/io/pravega/shared/MetricsNames.java
- shared/metrics/src/main/java/io/pravega/shared/MetricsTags.java
- shared/metrics/src/main/java/io/pravega/shared/metrics/MetricsLogAppender.java
- shared/metrics/src/test/java/io/pravega/shared/MetricsTagsTest.java
- shared/metrics/src/test/java/io/pravega/shared/metrics/MetricsLogAppenderTests.java
- Recording all WARNs and ERRORs as metrics with logging class name and exception name as tags.
Fixes #4495.
- Created a new Log Appender to intercept all log entries that have severity set to WARN or ERROR. 
- All these are reported into metrics via 2 distinct counters (one for WARN, one for ERROR), and using the source class/log name as a tag, and exception name (if any) as another tag.
Unit tests updated. A longevity with metrics should also be run to verify this.
> Issue 4495: Recording WARN and ERROR log entries as metrics.

- controller/src/main/java/io/pravega/controller/server/bucket/PeriodicWatermarking.java
- controller/src/test/java/io/pravega/controller/server/bucket/WatermarkWorkflowTest.java
- test/integration/src/test/java/io/pravega/test/integration/WatermarkingTest.java
Revisioned stream clients for watermark stream are cached on controller instance. When a stream is deleted and recreated, the cached client could get no such segment exception. 
Fixes #4478 
If noSuchSegmentException is thrown when trying to reinitialize the cached client, invalidate the cache for the stream. 
integration test added for deleting and recreating the stream.
> Issue 4478: Remove cached watermarking client for deleted stream

- gradle.properties
Removes -SNAPSHOT suffix from Pravega version in gradle.properties in preparation to release 0.6.2.
Fixes #4534 
There is no code change, only a change to the Pravega version in gradle.properties.
Build should succeed regularly and artifacts should not contain the commit id suffix.
> Issue 4534: Change pravega version to 0.6.2

- controller/src/main/java/io/pravega/controller/server/eventProcessor/requesthandlers/SealStreamTask.java
- controller/src/test/java/io/pravega/controller/task/Stream/StreamMetadataTasksTest.java
SealStreamTask now calls `abortTransaction` for transactions that are marked as aborting, such that an abort event is submitted for them. 
Partial fix for #4529
When seal stream task is executed, it used to attempt to abort transactions that were open. Due to an unidentified bug, we have observed that in flink longevity there was a transaction for which the txn was marked for abort but corresponding event was not posted in the abort stream.
This prevented seal stream to complete as the transaction was never aborted. 
Now we call abort transaction for transactions that are Open as well as those that are already aborting. 
Unit …
> Issue 4529: From Seal Stream workflow, call abort Txn even for transactions that are in Aborting state

- client/src/main/java/io/pravega/client/stream/StreamConfiguration.java
Signed-off-by: Bibin Sebastian <bibinvamattathil@gmail.com>
Fixing method syntax of EventStreamReader#getCurrentTimeWindow(Stream) method in javadoc
Fixes #4532 
No code changes, only javadoc is updated
Run './gradlew clean javadocs' command to verify that the javadoc warning for io.pravega.client.stream.StreamConfiguration doesn't appear anymore.
> Issue 4532: Typo in Javadoc for io.pravega.client.stream.StreamConfiguration

- client/src/main/java/io/pravega/client/segment/impl/EventSegmentReader.java
- client/src/main/java/io/pravega/client/segment/impl/EventSegmentReaderImpl.java
- client/src/main/java/io/pravega/client/segment/impl/SegmentInputStream.java
- client/src/main/java/io/pravega/client/segment/impl/SegmentInputStreamImpl.java
- client/src/main/java/io/pravega/client/state/impl/RevisionedStreamClientImpl.java
- client/src/main/java/io/pravega/client/stream/impl/EventStreamReaderImpl.java
- client/src/test/java/io/pravega/client/segment/impl/EventSegmentReaderImplTest.java
- client/src/test/java/io/pravega/client/state/impl/RevisionedStreamClientTest.java
- client/src/test/java/io/pravega/client/stream/impl/OrdererTest.java
- client/src/test/java/io/pravega/client/stream/mock/MockSegmentIoStreams.java
(Under discussion)
- Ensure Revisioned Stream resends the read request if the Segment store does not respond within 30 seconds after confirmation that the write-offset is greater than the current read-offset.
- Ensure the Event Stream Reader resends the read request if the complete WireCommand frame is not received within 30 seconds.
Fixes #
This PR is in continuation of PR #4430. During the longevity testing of Pravega, we have observed scenarios where part of the WireCommand is never received by the client. This is observed post a network glitch on a Pravega cluster deployment that uses SDN with load balancers. The underlying network connection was never dropped nor did the packet arrive at the client. …
> Issue:  Prevent readers from waiting indefinitely if there is a partial/no response from the Segment Store.

- gradle.properties
Change pravega version to 0.6.3-SNAPSHOT in gradle.properties
Fixes #4543 
Changes pravega version to 0.6.3-SNAPSHOT in gradle.properties
new artifacts should be produced with 0.6.3-SNAPSHOT
> Issue 4543: Change pravega version to 0.6.3-SNAPSHOT

- common/src/main/java/io/pravega/common/util/ByteArraySegment.java
- common/src/main/java/io/pravega/common/util/btree/BTreePage.java
- common/src/test/java/io/pravega/common/util/ByteArraySegmentTests.java
- common/src/test/java/io/pravega/common/util/btree/BTreeIndexTests.java
- segmentstore/server/src/main/java/io/pravega/segmentstore/server/logs/DataFrame.java
- segmentstore/server/src/main/java/io/pravega/segmentstore/server/reading/StorageReadManager.java
- segmentstore/server/src/main/java/io/pravega/segmentstore/server/tables/AsyncTableEntryReader.java
- segmentstore/server/src/test/java/io/pravega/segmentstore/server/logs/DataFrameTests.java
- segmentstore/server/src/test/java/io/pravega/segmentstore/server/tables/SegmentMock.java
- segmentstore/storage/src/test/java/io/pravega/segmentstore/storage/cache/BenchmarkTests.java
Signed-off-by: co-jo <Colin.Hryniowski@emc.com>
* Search and replace instances of `ByteArraySegment.subSegment` with its `.slice` method.
* Rename some test methods to reflect this replacement.
* Closes #4318 
* No logic changes; a straightforward search and replace operation.
> Issue 4318: Replace `ByteArraySegment.subSegment()` with `ByteArraySegment.slice()`.

- segmentstore/server/host/src/main/java/io/pravega/segmentstore/server/host/handler/AppendProcessor.java
Signed-off-by: co-jo <Colin.Hryniowski@emc.com>
* Remove @Slf4j annotation and replace the logger (as is done in `PravegaRequestProcessor.java`).
* As with `PravegaRequestProcessor.java`, supply the error/warn logs with a `requestId`, via the first parameter (the logs 'marker').
* Closes #4527 
* Enhances the error/warning logging of the `AppendProcessor` class to include the `requestId` as the log marker.
> Issue 4527: Include RequestIDs in the AppendProcessor error/warning logs.

- .travis.yml
- build.gradle
Signed-off-by: anishakj <anisha.kj@emc.com>
On Travis CI the default behaviour is to use a clone-depth of 50. Due to that pravega build version is coming as `0.6.0-50.23b7340-SNAPSHOT` instead of `0.6.0-2386.23b7340-SNAPSHOT`
Fixes #4549 
Remove the default git clone depth
Build version is coming fine
> Issue 4549: Removed the default git-clone depth

- test/system/src/main/java/io/pravega/test/system/framework/services/docker/DockerBasedService.java
Signed-off-by: anishakj <anisha.kj@emc.com>
Added a new health check for zookeeper service
Fixes #4338 
Added new health check `ruok` for zookeeper service. `netstat` got removed from `zookeeper:3.5.5` onwards.
> Added new healthcheck for zookeeper

- build.gradle
- client/src/main/java/io/pravega/client/admin/ReaderGroupManager.java
- client/src/main/java/io/pravega/client/admin/impl/StreamManagerImpl.java
- client/src/main/java/io/pravega/client/stream/ReaderGroup.java
- client/src/main/java/io/pravega/client/stream/impl/Controller.java
- client/src/main/java/io/pravega/client/stream/impl/ReaderGroupStateManager.java
- client/src/main/java/io/pravega/client/tables/impl/TableSegment.java
- common/src/main/java/io/pravega/common/io/serialization/RevisionDataOutput.java
- common/src/main/java/io/pravega/common/io/serialization/VersionedSerializer.java
- common/src/main/java/io/pravega/common/util/BufferedIterator.java
- common/src/main/java/io/pravega/common/util/btree/ByteArrayComparator.java
- segmentstore/server/src/main/java/io/pravega/segmentstore/server/CacheManager.java
- segmentstore/server/src/main/java/io/pravega/segmentstore/server/DirectSegmentAccess.java
- segmentstore/server/src/main/java/io/pravega/segmentstore/server/SegmentMetadata.java
- segmentstore/server/src/main/java/io/pravega/segmentstore/server/store/ServiceBuilderConfig.java
- shared/authplugin/src/main/java/io/pravega/auth/AuthHandler.java
- shared/protocol/src/main/java/io/pravega/shared/NameUtils.java
- test/testcommon/src/main/java/io/pravega/test/common/AssertExtensions.java
Signed-off-by: Bibin Sebastian <bibinvamattathil@gmail.com>
Fixing Javadoc errors
Fixes #4552 
No code changes. 
- Multiple method syntax fixes in javadocs comments
- Multiple javadoc tag syntax fixes
- Multiple changes to format code snippets
run `./gradlew clean build -x test` or `./gradlew clean javadoc` 
you shouldn't see any error in javadoc generation step.
> Issue 4552: Reduce Javadoc errors

- build.gradle
Signed-off-by: Bibin Sebastian <bibinvamattathil@gmail.com>
Enabling doclint on all modules as all existing javadoc errors are fixed as part of #4555 
Fixes #4556 
enable doclint in gradle build scripts
Make a javadoc error intentionally and run `gradlew javadoc` should fail
> Issue 4556: Turn on DocLint

- config/config.properties
- segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/bookkeeper/BookKeeperConfig.java
- segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/bookkeeper/Ledgers.java
- segmentstore/storage/impl/src/test/java/io/pravega/segmentstore/storage/impl/bookkeeper/BookKeeperConfigTest.java
- test/integration/src/main/java/io/pravega/test/integration/selftest/adapters/BookKeeperAdapter.java
Add configuration option for Bookkeeper digest type.
Fixes #4558.
This PR enables us to configure the digest type used in Bookkeeper. The type of digest has an important impact on performance, so we have also changed the default one to `CRC32C` (formerly, it was `MAC`). Note that this change is reasonable, given that the `MAC` digest may protect from "byzantine Bookies", which may not be an expected adversarial model in many environments.
We have observed a 2x throughput increase writing to a single ledger via the `SelfTester` tool on AWS just changing the digest type:
_MAC_
```
sudo ./gradlew clean selftest -Dtarget=BookKeeper -Dbkc=3 -Dc=1 -Ds=1 -Dp=10 -Dpp=10 -Dws=1000000 -Do=10000 …
```
> Issue 4558: Low single segment write performance

- segmentstore/server/src/main/java/io/pravega/segmentstore/server/CacheManager.java
- segmentstore/server/src/main/java/io/pravega/segmentstore/server/tables/SegmentKeyCache.java
- segmentstore/server/src/test/java/io/pravega/segmentstore/server/CacheManagerTests.java
- Fixed a bug in CacheManager where it would incorrectly calculate the Newest Generation of a CacheStatus collection if at least one of them has no meaningful data.
- Fixed a bug in CacheManager where it would not refresh the client status after an eviction which could lead to over-increasing the Oldest Generation, leading to excessive cache eviction.
Fixes #4576.
The Cache Manager relies on all of its clients to accurately report their state (Oldest & Newest generations). It uses that to determine if the Oldest Generation should be increased which should force an eviction.
1. There was a bug in how some of these were aggregated into a single state. If a collection of `CacheStatus` instances contained at …
> Issue 4576: (SegmentStore) Fixed Cache Manager bugs

- bindings/src/main/java/io/pravega/storage/extendeds3/ExtendedS3StorageConfig.java
- bindings/src/main/java/io/pravega/storage/extendeds3/ExtendedS3StorageFactory.java
- bindings/src/test/java/io/pravega/storage/extendeds3/ExtendedS3StorageConfigTest.java
- bindings/src/test/java/io/pravega/storage/extendeds3/ExtendedS3StorageTest.java
- config/config.properties
- docker/pravega/scripts/common.sh
- docker/pravega/scripts/init_tier2.sh
- segmentstore/server/host/src/test/java/io/pravega/segmentstore/server/host/ExtendedS3IntegrationTest.java
Started using s3 rest style configUri for majority of extendeds3 storage client config.
Closes #4561 
config.properties now contains configUri, bucket and prefix for extendedS3 storage.
ExtendedS3StorageConfig takes configUri and construct s3Config from it.
ExtendedS3StorageFactory handles configUri now.
ExtendedS3StorageConfigTest is added.
ExtendedS3StorageTest is updated to work with the new configUri
ExtendedS3IntegrationTest is updated to work with the new configUri
No functional changes. All tests (unit, integration, system and …
> Issue 4561: Using S3 Rest Style Config URI for Extended S3 client construction

- docker/pravega/scripts/common.sh
This is a bugfix of issue 4561
The approach used before in the script was only able to test substring successfully in some cases.
Changed the approach to use "grep" to test substring, which works in all cases.
Fixes #4561 
Use "grep" to test substring in the function add_system_property_ecs_config_uri() inside common.sh, which is used by init_tier2.sh
In case of ECS used as tier-2, if the ECS configUri contains "identity", which means the credential is provided, then the configUri is passed to Pravega Java process directly; 
Otherwise, it append ECS credentials (from env vars) onto the configUri
> Issue 4561 - bugfix of docker script inside common.sh

- segmentstore/server/src/main/java/io/pravega/segmentstore/server/CachePolicy.java
- segmentstore/server/src/main/java/io/pravega/segmentstore/server/reading/StreamSegmentReadIndex.java
- segmentstore/server/src/test/java/io/pravega/segmentstore/server/reading/ContainerReadIndexTests.java
Fixed a bug in StreamSegmentReadIndex where it would have been possible for two concurrent Storage read requests to override one another, resulting in potential (in-memory) data loss should there be an append executed in between the two.
Fixes #4590.
When the Read Index receives concurrent reads for the same range in a Segment that is not cached, it may issue only one Tier 2 read and serve all such reads from it. However sometimes it may happen that each such read will trigger its own Tier 2 read, which will be accompanied by its own callback, when the data is inserted into the Cache. If such a scenario happens, the callback that is invoked later will override the data (and entry) inserted by the callback …
> Issue 4590: (SegmentStore) Fixed Read Index concurrent Tier 2 read bug

- bindings/src/main/java/io/pravega/storage/extendeds3/ExtendedS3Storage.java
- bindings/src/test/java/io/pravega/storage/extendeds3/ExtendedS3StorageTest.java
This change uses getObjectMetadata instead of listObjects to implement exists.
This fixes the current problem where listObject based check behaves incorrectly when prefix instead of full path is provided as parameter.
Fixes #4591 
This change uses getObjectMetadata instead of listObjects to implement exists.
Unit tests, System Tests and longevity tests should pass and should not show the incorrect behavior anymore.
> Issue 4591: Fixed ExtendedS3 exists()

- gradle.properties
Changed `pravegaVersion` to 0.8.0-SNAPSHOT.
Fixes #4594.
Look at the file.
> Issue 4594: Changed `pravegaVersion` to 0.8.0-SNAPSHOT in master

- segmentstore/server/src/main/java/io/pravega/segmentstore/server/reading/StreamSegmentReadIndex.java
- segmentstore/server/src/test/java/io/pravega/segmentstore/server/reading/ContainerReadIndexTests.java
- segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/cache/CacheStorage.java
Fixed a (second) bug in StreamSegmentReadIndex where it would have been possible for two concurrent Storage read requests to override one another, resulting in potential (in-memory) data loss should there be an append executed in between the two.
Fixes #4590.
See #4592 for details on the first bug.
#4592 handled the case when the concurrent reads began at  exactly the same Segment offset. This PR covers an additional case when two or more concurrent Tier 2 reads (resulting from cache misses) do not necessarily start at the same offset, but have at least one overlapping byte.
This PR aims to completely eliminate duplicated data in the Read Index due to such situations. Having Read Index entries that overlap …
> Issue 4590: (SegmentStore) Fixed Read Index concurrent Tier 2 read bug (Part 2)

- bindings/src/test/java/io/pravega/storage/extendeds3/ExtendedS3StorageTest.java
- bindings/src/test/java/io/pravega/storage/extendeds3/S3ProxyImpl.java
- segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/rolling/RollingStorage.java
- segmentstore/storage/src/test/java/io/pravega/segmentstore/storage/StorageTestBase.java
- segmentstore/storage/src/test/java/io/pravega/segmentstore/storage/rolling/RollingStorageTestBase.java
S3 client consumes whole InputStream and causes java.lang.IllegalArgumentException.
With this change, RollingStorage.write sends in BoundedInputStream to storage adapters to prevent reading more data.
Also, S3 client mocks simulate this InvalidRange behavior to match how real ECS bahaves.
Fixes #4601 
RollingStorage.write sends in BoundedInputStream to storage adapters to prevent reading more data.
S3 client mocks simulate this range behavior to match how real ECS bahaves.
> Issue 4601: (RollingStorage/ExtendedS3) S3 client consumes whole InputStream and causes java.lang.IllegalArgumentException

- client/src/main/java/io/pravega/client/netty/impl/ClientConnectionImpl.java
- client/src/main/java/io/pravega/client/netty/impl/FlowHandler.java
- client/src/test/java/io/pravega/client/netty/impl/FlowHandlerTest.java
- shared/metrics/src/main/java/io/pravega/shared/MetricsTags.java
- shared/protocol/src/main/java/io/pravega/shared/NameUtils.java
- shared/protocol/src/main/java/io/pravega/shared/protocol/netty/CommandEncoder.java
- shared/protocol/src/test/java/io/pravega/shared/protocol/netty/CommandEncoderTest.java
Uses single-character input in String.split() for efficiency reasons.
Fixes #4597.
This PR attempts to use a variant of the `String.split()` method implementation, which is optimized for single-character split patterns. There are several occurrences in `NameUtils` class that can exploit this approach, but by some reason a reggex expression is used. This PR just replaces these occurrences, as some of them are on the hot write path.
We have executed a micro benchmark to compare both approaches. Improvement in performance of `String.split()` is consistently between 2x and 4x:
```
public static void main(String[] args) {
String toSplit = "this/is/a/segment";
long iterations = 1000000;
long …
```
> Issue 4597: Optimization of String splits for Metrics

- client/src/main/java/io/pravega/client/segment/impl/EventSegmentReaderImpl.java
- client/src/main/java/io/pravega/client/stream/impl/ControllerImpl.java
- client/src/main/java/io/pravega/client/stream/impl/TransactionalEventStreamWriterImpl.java
- client/src/test/java/io/pravega/client/segment/impl/EventSegmentReaderImplTest.java
- client/src/test/java/io/pravega/client/stream/impl/TransactionalEventStreamWriterTest.java
- config/logback.xml
- controller/src/main/java/io/pravega/controller/server/ControllerService.java
- controller/src/main/java/io/pravega/controller/server/eventProcessor/LocalController.java
- controller/src/main/java/io/pravega/controller/server/rpc/grpc/v1/ControllerServiceImpl.java
- controller/src/test/java/io/pravega/controller/timeout/TimeoutServiceTest.java
- Simplify debugging in case of deadline exceed exception on the controller client.
- Reduce logging on the client.
- Improve transaction related logs on the controller.
- Ensure an empty response from SSS should not log a WARN message.
Fixes #4600 
- Simplify debugging in case of exceptions on the controller client. Ensure the parameters like the transaction ids are logged immediately instead of logging it along with a `RetriesExhaustedException`.
- Reduce logging on the client in case of an empty response from SSS.
- Ensure the txn UUID is logged instead of low and high bits of the transaction.
No changes to functionality. All the existing tests should continue to pass.
> Issue 4600: Fix Transaction related logs.

- segmentstore/server/src/main/java/io/pravega/segmentstore/server/reading/StreamSegmentReadIndex.java
- segmentstore/server/src/test/java/io/pravega/segmentstore/server/TestCacheManager.java
- segmentstore/server/src/test/java/io/pravega/segmentstore/server/reading/ContainerReadIndexTests.java
Fixed a bug where a concurrent segment merge and cache eviction could corrupt the Read Index.
Fixes #4610.
In the Read Index, Segments are merged into each other in a two-step process. Step 1 (BeginMerge) is performed when the request is received externally and involves adding a Redirect placeholder in the index for the merged byte range. Step 2 (CompleteMerge) is performed when the merge is performed in Tier 2 and involves atomically removing the Redirect placeholder and copying over the entire Read Index of the source segment.
With the current implementation, Step 2 has a short period of time where, if a Cache Manager eviction executes, it can effectively delete the data from the cache. That is because the …
> Issue 4610: (SegmentStore) Read Index data corruption during concurrent segment merge and cache eviction.

- segmentstore/server/src/main/java/io/pravega/segmentstore/server/writer/SegmentAggregator.java
- segmentstore/server/src/test/java/io/pravega/segmentstore/server/writer/SegmentAggregatorTests.java
Fixed a bug in SegmentAggregator where it could enter an infinite async loop if it receives an empty append.
Fixes #4618.
See #4618 for a scenario that can lead to a situation like this.
Currently, if a `SegmentAggregator` is sitting on an Append of length 0 **and** it receives a non-append operation (such as Merge, Truncate, Seal), it will try to flush that 0-length append and end up in an infinite loop, without any chance of exiting it (short of a container restart). This was due to some short-circuit in the `flushPendingAppends` method that was exiting early from the call if there was nothing to flush, without invoking the `updateStatePostFlush` callback which would have removed that empty append from the …
> Issue 4618: (SegmentStore) Fixed a possible infinite loop in StorageWriter for empty appends.

- bindings/src/main/java/io/pravega/storage/extendeds3/ExtendedS3Metrics.java
- bindings/src/main/java/io/pravega/storage/extendeds3/ExtendedS3Storage.java
- bindings/src/main/java/io/pravega/storage/extendeds3/ExtendedS3StorageConfig.java
- bindings/src/test/java/io/pravega/storage/extendeds3/ExtendedS3StorageTest.java
- config/config.properties
- segmentstore/storage/src/test/java/io/pravega/segmentstore/storage/StorageTestBase.java
- shared/metrics/src/main/java/io/pravega/shared/MetricsNames.java
Currently ExtendedS3Storage implements all concat operations as multi-part uploads. ( target = target+ source ). This is inefficient when source segments are small.
With this change , for smaller source segments, concat should read complete source segment and append it to target instead of using multi-part upload.
For larger source segments continue using current method.
Fixes #4609 
For smaller source segments, concat should read complete source segment and append it to target instead of using multi-part upload.
For larger source segments continue using current method.
All tests should be green.
> Issue 4609: ExtendedS3Storage.concat using appends when source segment is small

- bindings/src/main/java/io/pravega/storage/extendeds3/ExtendedS3Metrics.java
- bindings/src/main/java/io/pravega/storage/extendeds3/ExtendedS3Storage.java
- bindings/src/main/java/io/pravega/storage/extendeds3/ExtendedS3StorageConfig.java
- bindings/src/test/java/io/pravega/storage/extendeds3/ExtendedS3StorageTest.java
- config/config.properties
- segmentstore/storage/src/test/java/io/pravega/segmentstore/storage/StorageTestBase.java
- shared/metrics/src/main/java/io/pravega/shared/MetricsNames.java
With this change , for smaller source segments, concat should read complete source segment and append it to target instead of using multi-part upload.
For larger source segments continue using multi part upload method.
Cherry picks  #4617 
Fixes #4609.
See  #4617.
See  #4617.
See  #4617.
> Issue 4609: (CherryPick-0.7) ExtendedS3Storage.concat using appends when source segment is small (#4617)

- client/src/test/resources/logback-test.xml
- client/src/test/resources/logback.xml
- config/logback.xml
- controller/src/conf/logback.xml
- controller/src/test/resources/logback.xml
- dist/conf/logback.xml
- segmentstore/server/host/src/config/logback.xml
- segmentstore/storage/impl/src/test/resources/logback.xml
- segmentstore/storage/src/test/resources/logback.xml
- test/integration/src/main/resources/logback-test.xml
- test/integration/src/test/resources/logback.xml
- test/system/src/test/resources/logback-test.xml
Enable logging configuration re-load upon configuration file modification. 
Resolves #4347. 
Adds `scanPeriod` attribute to Logback configuration element `configuration` with `scan` enabled, so that logging configuration changes are reloaded. 
Currently,  the logging configuration specifies `<configuration scan="true">`, which in theory should automatically reload logging configuration changes at runtime with a default scan period of 1 minute ([source](http://logback.qos.ch/manual/configuration.html)). However, the version of logback we use (`1.2.3`) has a bug, which deactivates `scan` if `scanPeriod` is left unspecified: https://jira.qos.ch/browse/LOGBACK-1194. 
Alternatively, we could upgrade the Logback …
> Issue 4347: Enable auto-reload of modified logging configuration at runtime

- controller/src/main/java/io/pravega/controller/server/eventProcessor/requesthandlers/CommitRequestHandler.java
Report failed transaction commit metric only in case of non-retryable failures.
Fixes #4631.
`CommitRequestHandler` was previously reporting any failure in the execution of a transaction commit batch as a failure in metrics. However, some situations are expected to trigger a "transient" failure, like committing transactions on a segment that is in the process of scaling. In this case, the Controller will internally retry and the transaction commit will eventually succeed. In such "retryable" or transient failures, we should not report any transaction commit failure in metrics. Only permanent transaction commit failures should.
All the tests should be passing as before.
> Issue 4631: Failed transactions metric incorrectly reported

- client/src/main/java/io/pravega/client/stream/impl/ControllerImpl.java
Ensure the txn id is logged in case of failed transaction commit / abort.
Fixes #4633 
Improves the logging to speed up debugging.
No changes in functionality.
> Issue 4633:  Improve controller client logs

- test/system/src/main/java/io/pravega/test/system/framework/services/kubernetes/ZookeeperK8sService.java
Signed-off-by: anisha.kj <anisha.kj@dell.com>
Since `replicas` field is not set, system tests were deploying `3` instances of `zk` instead of `1`. Set the replicas correctly to fix the issue
Fixes  #4648
Changed the deprecated size field to replicas
System tests should pass
> Issue 4648: System tests are failing with zookeeper-operator 0.2.6-rc1

- controller/src/main/java/io/pravega/controller/store/stream/PravegaTablesStoreHelper.java
- controller/src/test/java/io/pravega/controller/store/stream/PravegaTablesStoreHelperTest.java
For table update calls, retry should be done only for WrongHost and auth failed but not for other store connection failure exceptions.
Fixes #4639 
While interacting with segment store for table queries, we retry on store exceptions for all requests.
This can have undesired effect for conditional updates because they can now fail with write conflict exception.
Unit test added.
> Issue 4639: Table store helper to retry only on unknownhost and auth failure for update requests

- common/src/main/java/io/pravega/common/util/OrderedItemProcessor.java
- common/src/test/java/io/pravega/common/util/OrderedItemProcessorTests.java
- config/config.properties
- segmentstore/server/host/src/main/java/io/pravega/segmentstore/server/host/ServiceStarter.java
- segmentstore/server/host/src/main/java/io/pravega/segmentstore/server/host/ZKSegmentContainerManager.java
- segmentstore/server/host/src/main/java/io/pravega/segmentstore/server/host/ZKSegmentContainerMonitor.java
- segmentstore/server/host/src/test/java/io/pravega/segmentstore/server/host/ZKSegmentContainerManagerTest.java
- segmentstore/server/host/src/test/java/io/pravega/segmentstore/server/host/ZKSegmentContainerMonitorTest.java
- segmentstore/server/src/main/java/io/pravega/segmentstore/server/store/ServiceConfig.java
Enforces sequential start of containers to prevent multiple concurrent container recoveries from overloading the cache.
Fixes #4653.
Until now, a Segment Store could start Segment Containers in parallel, which also includes the process of recovery in the case that the Segment Container to start is not new. However, if we think about a Segment Store recovering in parallel multiple Segment Containers, it may be the case that the data to process for each container is larger than the size of the cache (not to mention that the cache can still be used by other containers). This PR mainly serializes the execution of Segment Container starts with the main objective of preventing overloading the cache.
To this end, …
> Issue 4653: Control rate of parallel Segment Container recoveries

- docker/pravega/scripts/common.sh
- docker/pravega/scripts/init_tier2.sh
In the initialization of segmentstore container, certificates mounted under /etc/ssl/certs/java/ecs-certs are added into the default Java truststore for TLS enabled connection. 
Closes #4642 
The init scripts scans /etc/ssl/certs/java/ecs-certs, and add each certificates found into Java truststore which is located at $JAVA_HOME/jre/lib/security/cacerts.
The certificates should be added into the truststore, and the TLS connection based on ECS self-signed certificate could be established.
> Issue-4642: Added certificates into Java truststore for ECS TLS connections.

- segmentstore/server/src/main/java/io/pravega/segmentstore/server/writer/StorageWriter.java
- segmentstore/server/src/test/java/io/pravega/segmentstore/server/writer/StorageWriterTests.java
Include DataLogWriterNotPrimaryException as a critical exception for Storage Writer to be restarted.
Fixes #4605 
This PR justs considers `DataLogWriterNotPrimaryException` as one of the critical exceptions that will induce the shutdown of the Storage Writer and the restart of a container on the same host if it applies. If we don't include that exception in the critical ones, the Storage Writer may get stuck getting `DataLogWriterNotPrimaryException` from the Bookkeeper log indefinitely. The expectation is that with the restart of the container, the Storage Writer can start working with the right Bookkeeper log version stored in Zookeeper, and prevent this exception from happening again. 
**How to verify …
> Issue 4654: DataLogWriterNotPrimaryException thrown indefinitely

- segmentstore/server/src/main/java/io/pravega/segmentstore/server/writer/StorageWriter.java
- segmentstore/server/src/test/java/io/pravega/segmentstore/server/writer/StorageWriterTests.java
Cherry-pick PR #4666 to 0.7.
Fixes #4654.
See #4666 for details.
See #4666 for details.
> Issue 4654: (CherryPick-0.7) DataLogWriterNotPrimaryException thrown indefinitely (#4666)

- docker/pravega/scripts/common.sh
- docker/pravega/scripts/init_tier2.sh
This is the cherry-pick of https://github.com/pravega/pravega/pull/4682
Instead of hard-coding, now the Java Truststore path and password get mounted from pravega manifest by pravega-operator.
This change is to start using the mounted path and password in the script to add ECS certificate into Java truststore.
To include the feature into r0.7
Inside docker/pravega/scripts/common.sh:
Retrieve password from /etc/ssl/certs/java/ecs-certs/JAVA_TRUST_STORE_PASSWORD
Retrieve truststore file path from /etc/ssl/certs/java/ecs-certs/JAVA_TRUST_STORE_PATH
Then scan /etc/ssl/certs/java/ecs-certs to add all the found PEM files into Java Truststore.
With …
> Issue 4642 - cherry-pick into r0.7 for ECS TLS support

- build.gradle
- gradle/java.gradle
Include `LICENSE` and `NOTICE` files in the binary artifacts 
Fixes #4628 
Copies `LICENSE` and `NOTICE` files into `META-INF` directory in every jar file generated. And also includes the same files in tgz and zip versions of Pravega and Pravega Client distributions 
Build should pass. The generated artifacts should have both LICENSE and NOTICE files included.
> Issue 4628: Add license copy to binary artifacts

- docker/pravega/scripts/common.sh
- docker/pravega/scripts/init_tier2.sh
This reverts commit 8f3dc1c8b1688112480fde0976ace568eb3b52c3.
This reverts commit 8f3dc1c8b1688112480fde0976ace568eb3b52c3.
Decision made that no ECS TLS changes go to r0.7 and operator 0.4.4
Fixes #4642 
This reverts commit 8f3dc1c8b1688112480fde0976ace568eb3b52c3.
It removes the changes made into common.sh and init_tier2.sh
The changes should be removed.
> Revert "Issue 4642 - cherry-pick into r0.7 for ECS TLS support (#4684)"

- client/src/main/java/io/pravega/client/stream/impl/PositionImpl.java
- client/src/test/java/io/pravega/client/stream/impl/SerializationTest.java
Fix `io.pravega.client.stream.Position#toBytes` to ensure serialization works if the offset is -1L.
Fixes #4669
The older revision of the client does not support serialization/deserialization with -1L as an offset.
This PR uses `io.pravega.common.io.serialization.RevisionDataOutput#writeCompactSignedLong` instead of `io.pravega.common.io.serialization.RevisionDataOutput#writeCompactLong` tofix the issue.
Both forward and backward compatibility is maintained with this change.
> Issue 4669: (Bugfix) Fix serialization in PositionImpl.

- common/src/main/java/io/pravega/common/util/ReusableLatch.java
- common/src/test/java/io/pravega/common/util/ReusableLatchTests.java
- segmentstore/server/src/main/java/io/pravega/segmentstore/server/CacheManager.java
- segmentstore/server/src/main/java/io/pravega/segmentstore/server/reading/StreamSegmentReadIndex.java
- segmentstore/server/src/test/java/io/pravega/segmentstore/server/CacheManagerTests.java
- segmentstore/server/src/test/java/io/pravega/segmentstore/server/reading/ContainerReadIndexTests.java
- segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/cache/CacheStorage.java
- segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/cache/DirectMemoryCache.java
- segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/cache/NoOpCache.java
- segmentstore/storage/src/test/java/io/pravega/segmentstore/storage/cache/DirectMemoryCacheTests.java
- Changed the `CacheManager` to reject additional concurrent cache cleanup requests if one is ongoing (as opposed from using a mutex to serialize them).
- Changed the `DirectMemoryCache` to use an exp backoff retry if it cannot clean up the cache after it detected the cache was full.
Fixes #4702.
See #4702 for a description of a scenario that leads to this. 
The problem arises if 2 concurrent Storage reads complete at about the same time, and both want to insert into a full cache at the same time. Each callback would execute on its own thread, acquire the Read Index lock associated with their segment, then acquire the Cache Manager eviction lock …
> Issue 4702: (SegmentStore) Fixed a deadlock condition in the Read Index.

- segmentstore/server/src/main/java/io/pravega/segmentstore/server/reading/StreamSegmentReadIndex.java
- segmentstore/server/src/main/java/io/pravega/segmentstore/server/writer/SegmentAggregator.java
- segmentstore/server/src/test/java/io/pravega/segmentstore/server/writer/SegmentAggregatorTests.java
- segmentstore/server/src/test/java/io/pravega/segmentstore/server/writer/TestWriterDataSource.java
Fixed a bug in SegmentAggregator where it would be unable to resume flush operations after reconciling a partially flushed append.
Fixes #4652.
- Upon successfully reconciling an append operation, the `SegmentAggregator` would correctly update the Segment's metadata to reflect the Storage offset, however it would not trim the reconciled operation's that has been reconciled. After this, when resuming normal operations, the SegmentAggregator would ask the Read Index to provide data for the reconciled offsets, but the Read Index would correctly reject the request since the StorageWriter is not allowed to request data that has already been moved to Storage.
- This fix changes the SegmentAggregator to update its …
> Issue 4652: (SegmentStore) Fixed Reconciliation of partially-flushed Storage append

- build.gradle
- gradle/java.gradle
Cherrypick #4628 / #4675 into r0.7
Fixes #4628 in Pravega  0.7.1
Copies LICENSE and NOTICE files into META-INF directory in every jar file generated. And also includes the same files in tgz and zip versions of Pravega and Pravega Client distributions
Build should pass. The generated artifacts should have both LICENSE and NOTICE files included.
> Issue 4628: Add license copy to binary artifacts (#4675)

- segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/bookkeeper/BookKeeperLog.java
- segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/bookkeeper/LedgerMetadata.java
- segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/bookkeeper/ReadOnlyLogMetadata.java
- segmentstore/storage/impl/src/test/java/io/pravega/segmentstore/storage/impl/bookkeeper/BookKeeperLogTests.java
- segmentstore/storage/impl/src/test/java/io/pravega/segmentstore/storage/impl/bookkeeper/LogMetadataTests.java
- BookKeeperLog.persistMetadata will auto-reconcile the metadata if it gets a `NodeExistsException` or `BadVersionException` from ZooKeeper while doing a CAS update. 
Fixes #4721.
- See #4721 for why this is needed.
- The `BookKeeperLog` will attempt to read the metadata from ZK and compare it to what it wanted to persist in the first place. If identical (except for versions), it will consider the update to have gone through, otherwise it will rethrow the original exception.
New unit test added.
> Issue 4721: Auto-reconciliation of BookKeeperLog Metadata.

- common/src/main/java/io/pravega/common/util/OrderedItemProcessor.java
- common/src/test/java/io/pravega/common/util/OrderedItemProcessorTests.java
- config/config.properties
- segmentstore/server/host/src/main/java/io/pravega/segmentstore/server/host/ServiceStarter.java
- segmentstore/server/host/src/main/java/io/pravega/segmentstore/server/host/ZKSegmentContainerManager.java
- segmentstore/server/host/src/main/java/io/pravega/segmentstore/server/host/ZKSegmentContainerMonitor.java
- segmentstore/server/host/src/test/java/io/pravega/segmentstore/server/host/ZKSegmentContainerManagerTest.java
- segmentstore/server/host/src/test/java/io/pravega/segmentstore/server/host/ZKSegmentContainerMonitorTest.java
- segmentstore/server/src/main/java/io/pravega/segmentstore/server/store/ServiceConfig.java
This PR temporarily reverts PR #4655, as it shows sporadic instability in system tests.
Fixes #4730.
Temporarily reverts changes in #4655.
System tests should pass consistently.
> Issue 4730: Temporarily revert control rate of parallel Segment Container recoveries (#4655)

- segmentstore/server/src/main/java/io/pravega/segmentstore/server/writer/SegmentAggregator.java
- segmentstore/server/src/test/java/io/pravega/segmentstore/server/writer/SegmentAggregatorTests.java
- segmentstore/server/src/test/java/io/pravega/segmentstore/server/writer/TestWriterDataSource.java
Fixed a bug in SegmentAggregator where it was possible to enter an infinite loop if deleting a segment while flushing.
Fixes #4743.
Exiting the flush loop if a segment deletion is detected.
New unit test added. The unit test would have never finished (timed out) if the fix hadn't been there.
> Issue 4743: (SegmentStore) Infinite loop in StorageWriter if deleting a segment while flushing.

- segmentstore/server/src/main/java/io/pravega/segmentstore/server/writer/SegmentAggregator.java
- segmentstore/server/src/test/java/io/pravega/segmentstore/server/writer/SegmentAggregatorTests.java
- segmentstore/server/src/test/java/io/pravega/segmentstore/server/writer/TestWriterDataSource.java
Cherry-pick #4743 into r0.7:
- Issue 4743: (SegmentStore) Infinite loop in StorageWriter if deleting a segment while flushing (#4744)
- Fixed a bug in SegmentAggregator where it was possible to enter an infinite loop if deleting a segment while flushing.
Fixes #4747.
See #4743.
Verify commits.
> Issue 4747: Cherry-pick #4743 into r0.7.

- client/src/test/java/io/pravega/client/segment/impl/SegmentOutputStreamTest.java
- client/src/test/java/io/pravega/client/stream/impl/EventStreamWriterTest.java
- shared/protocol/src/test/java/io/pravega/shared/protocol/netty/AppendEncodeDecodeTest.java
- test/integration/src/test/java/io/pravega/test/integration/AppendReconnectTest.java
- test/integration/src/test/java/io/pravega/test/integration/AppendTest.java
- test/integration/src/test/java/io/pravega/test/integration/ReadTest.java
- test/integration/src/test/java/io/pravega/test/integration/StateSynchronizerTest.java
- test/integration/src/test/java/io/pravega/test/integration/TransactionTest.java
- test/testcommon/src/main/java/io/pravega/test/common/LeakDetectorTestSuite.java
- Created `LeakDetectorTestSuite`, a base class that hooks into Netty's ResourceLeakDetector and fails any test for which a resource leak is detected.
- Wired up all existing tests that make use of `ResourceLeakDetector` to inherit from this base class.
Fixes #4088.
No functional code changes.
Build must complete successfully.
> Issue 4088: Failing all tests that leak Netty resources

- client/src/main/java/io/pravega/client/batch/impl/SegmentIteratorImpl.java
- client/src/test/java/io/pravega/client/batch/impl/SegmentIteratorTest.java
Ensure the batch client retries in case a partial event is received from SegmentStore.
Fixes #4766 
BatchClient reads from a Segment using `io.pravega.client.segment.impl.EventSegmentReaderImpl#read()` where the first-byte timeout is set to `Long.MAX_VALUE` .
The EventSegmentReader waits for 30seconds (`PARTIAL_DATA_TIMEOUT`) after receiving the first byte to get the remaining part of the event. In the case, the reader does not receive the complete event a newer request is sent by the EventSegmentReader.
The BatchClient client should retry in such a scenario and try to obtain the complete event before de-serializing the ByteBuffer received.
All the existing and newly added tests should …
> Issue 4766: Ensure BatchClient handles partial response from SSS.

- build.gradle
- common/src/main/java/io/pravega/common/io/BufferViewSink.java
- common/src/main/java/io/pravega/common/io/serialization/RevisionDataOutput.java
- common/src/main/java/io/pravega/common/io/serialization/RevisionDataOutputStream.java
- common/src/main/java/io/pravega/common/util/BufferView.java
- common/src/main/java/io/pravega/common/util/ByteArraySegment.java
- common/src/main/java/io/pravega/common/util/CompositeArrayView.java
- common/src/main/java/io/pravega/common/util/CompositeBufferView.java
- common/src/main/java/io/pravega/common/util/CompositeByteArraySegment.java
- common/src/test/java/io/pravega/common/io/serialization/RevisionDataOutputStreamTests.java
- common/src/test/java/io/pravega/common/util/ByteArraySegmentTests.java
- common/src/test/java/io/pravega/common/util/CompositeBufferViewTests.java
- common/src/test/java/io/pravega/common/util/CompositeByteArraySegmentTests.java
- segmentstore/server/src/main/java/io/pravega/segmentstore/server/logs/DataFrame.java
- segmentstore/server/src/main/java/io/pravega/segmentstore/server/logs/DataFrameOutputStream.java
- segmentstore/server/src/test/java/io/pravega/segmentstore/server/logs/DataFrameTests.java
- shared/protocol/src/main/java/io/pravega/shared/protocol/netty/Append.java
- shared/protocol/src/main/java/io/pravega/shared/protocol/netty/AppendDecoder.java
- shared/protocol/src/main/java/io/pravega/shared/protocol/netty/ByteBufWrapper.java
- shared/protocol/src/main/java/io/pravega/shared/protocol/netty/WireCommands.java
- shared/protocol/src/test/java/io/pravega/shared/protocol/netty/AppendEncodeDecodeTest.java
- shared/protocol/src/test/java/io/pravega/shared/protocol/netty/ByteBufWrapperTests.java
- shared/protocol/src/test/java/io/pravega/shared/protocol/netty/WireCommandsTest.java
- test/integration/src/main/java/io/pravega/test/integration/selftest/adapters/InProcessMockClientAdapter.java
- test/integration/src/main/java/io/pravega/test/integration/selftest/adapters/TruncateableArray.java
- test/testcommon/src/main/java/io/pravega/test/common/LeakDetectorTestSuite.java
- Optimized AppendDecoder to make fewer buffer copies from Netty to the Segment Store.
- Optimized the ingestion path in the Segment Store to choose the most efficient method of copying data based on the source and target buffer types.
Fixes #4764.
`AppendDecoder`, in conjunction with `WireCommands.AppendBlock/AppendBlockEnd/ConditionalAppend/Event/PartialEvent`, is responsible for translating between Wire Commands and an `Append` that can be processed by the Segment Store it's sitting on top of.
However all these classes make numerous buffer allocations and copies for data to get from Netty's network bufs to the Segment Store:
- Netty -> AppendBlockEnd -> Append
- Netty -> AppendBlock/AppendBlockEnd -> …
> Issue 4764: Optimized AppendDecoder to make fewer buffer copies

- controller/src/main/java/io/pravega/controller/server/SegmentHelper.java
- segmentstore/server/host/src/test/java/io/pravega/segmentstore/server/host/handler/PravegaRequestProcessorTest.java
- shared/protocol/src/main/java/io/pravega/shared/protocol/netty/WireCommandType.java
- shared/protocol/src/main/java/io/pravega/shared/protocol/netty/WireCommands.java
- shared/protocol/src/test/java/io/pravega/shared/protocol/netty/WireCommandsTest.java
* Stub out new APIs.
Addresses #4792 .
This code defines new (and refactors old) APIs that will allow the various teams to begin work on supporting offset/version based TableSegment reads.
* Run WireCommandTests.
> Issue 4792: API stubs for supporting offset/version based TableSegment reads.

- client/src/main/java/io/pravega/client/netty/impl/ClientConnectionImpl.java
- client/src/main/java/io/pravega/client/netty/impl/FlowHandler.java
- client/src/test/java/io/pravega/client/netty/impl/ClientConnectionTest.java
- client/src/test/java/io/pravega/client/netty/impl/ConnectionPoolingTest.java
- client/src/test/java/io/pravega/client/netty/impl/FlowHandlerTest.java
- segmentstore/server/host/src/test/java/io/pravega/segmentstore/server/host/handler/AppendProcessorTest.java
- shared/protocol/src/main/java/io/pravega/shared/protocol/netty/CommandEncoder.java
- shared/protocol/src/main/java/io/pravega/shared/protocol/netty/FlushingMessageToByteEncoder.java
- shared/protocol/src/test/java/io/pravega/shared/protocol/netty/AppendEncodeDecodeTest.java
- shared/protocol/src/test/java/io/pravega/shared/protocol/netty/CommandEncoderTest.java
- test/integration/src/test/java/io/pravega/test/integration/AppendTest.java
- test/testcommon/src/main/java/io/pravega/test/common/LeakDetectorTestSuite.java
* Merge 4785 into R0.7 branch
Fixes #4784
Merge 4785 into R0.7 branch
> Merge 4785 into R0.7 branch

- build.gradle
- common/src/test/java/io/pravega/common/security/JwtUtilsTest.java
- gradle.properties
- test/testcommon/src/main/java/io/pravega/test/common/JwtBody.java
- test/testcommon/src/main/java/io/pravega/test/common/JwtTestUtils.java
- test/testcommon/src/test/java/io/pravega/test/common/JwtBodyTest.java
Replaces Gson with Jackson Databind, in order to avoid mysterious version conflicts caused by explicitly added Gson dependency and implicitly brought in transitively by third-party libraries. 
Fixes #4811 
Replaces usage of Gson with Jackson Databind. 
All unit, integration, and system tests pass.
> Issue 4811: Replace object-json mapping library for JWT

- build.gradle
- common/src/test/java/io/pravega/common/security/JwtUtilsTest.java
- controller/src/main/java/io/pravega/controller/server/rpc/grpc/v1/ControllerServiceImpl.java
- controller/src/main/java/io/pravega/controller/task/Stream/StreamMetadataTasks.java
- controller/src/main/java/io/pravega/controller/util/RetryHelper.java
- controller/src/test/java/io/pravega/controller/server/v1/PravegaTablesControllerServiceImplTest.java
- controller/src/test/java/io/pravega/controller/task/Stream/StreamMetadataTasksTest.java
- controller/src/test/java/io/pravega/controller/util/RetryHelperTest.java
- gradle.properties
- test/testcommon/src/main/java/io/pravega/test/common/JwtBody.java
- test/testcommon/src/main/java/io/pravega/test/common/JwtTestUtils.java
- test/testcommon/src/test/java/io/pravega/test/common/JwtBodyTest.java
Add timeout to workflow completion check and throw timeout exception if the workflow is not finished within that time. 
Fixes #4783 
StreamMetadataTasks.java `checkDone` method was checked for in a loop indefinitely. Added timeout which will throw the timeout exception to the caller. 
ControllerServiceImpl.java will throw DEADLINE_EXCEEDED response to the client upon receiving timeout exception. 
RetryHelper.java adds a new helper method that terminates the loop if timeout elapses. 
Unit tests added
> Issue 4783: Timebound check for completion of workflow to avoid log flooding

- client/src/main/java/io/pravega/client/stream/impl/TransactionalEventStreamWriterImpl.java
- client/src/test/java/io/pravega/client/stream/impl/TransactionalEventStreamWriterTest.java
Ensure TxnFailedException is thrown only if the Transaction is not in an open state
Fixes #4815 
Ensure TxnFailedException is thrown only if the Transaction is not in an open state
All the existing and newly added tests should pass
> Issue 4815: (Bugfix) Ensure TxnFailedException is thrown only if Transaction is not in an open state

- segmentstore/server/host/src/main/java/io/pravega/segmentstore/server/host/stat/SegmentAggregates.java
- segmentstore/server/host/src/test/java/io/pravega/segmentstore/server/host/stat/SegmentAggregatesTest.java
Calls the delay function for each silent period between two update notifications on segmentaggregates.  
#4813 
The weighted average rate computation takes the instant rate as events / time between two subsequent update calls. If there is a long delay between the two calls, then it calls the decay function with a small instant rate which effectively decays the rate by a very small factor without accounting for additional decays for silent periods.
So what we do now instead is to take the instant rate as the rate in the latest tick. And all ticks between current update call and the last update call are treated as silent periods and rate is decayed for …
> Issue 4813: Rate computation in SegmentAggregates should account for silent period 

- NOTICE
* Updates NOTICE file with the year range `2017-2020`.
Fixes #4849 
No code change, only a change to the NOTICE file to update the range of years the copyright applies to.
It should build as usual.
> Issue 4849: Update NOTICE

- client/src/main/java/io/pravega/client/byteStream/impl/ByteStreamClientImpl.java
- client/src/main/java/io/pravega/client/stream/impl/ControllerImpl.java
- client/src/main/java/io/pravega/client/stream/impl/SegmentSelector.java
- client/src/main/java/io/pravega/client/stream/impl/StreamSegments.java
- client/src/test/java/io/pravega/client/stream/impl/ClientFactoryTest.java
- client/src/test/java/io/pravega/client/stream/impl/ControllerImplTest.java
- client/src/test/java/io/pravega/client/stream/impl/SegmentSelectorTest.java
- test/integration/src/test/java/io/pravega/test/integration/endtoendtest/EndToEndTruncationTest.java
Improve sealed stream handling for EventStreamWriter and ByteStreamWriter.
Fixes #4817 
- Ensure EventStreamWriter does not attempt to send inflight events if the Controller returns an empty successor segments since the stream is sealed.
- Ensure writes via EventStreamWriter on a sealed stream throws an exception.
- Ensure the creating a ByteStreamWriter and EventStreamWriter on a sealed stream throws an exception.
All the existing and newly added tests should pass
> Issue 4817: Improve sealed stream handling of EventStreamWriter and ByteStreamWriter.

- common/src/main/java/io/pravega/common/util/TypedProperties.java
- common/src/test/java/io/pravega/common/util/TypedPropertiesTests.java
Modify the name resolution strategy for configuration properties to use legacy names first, for backward compatibility.
Resolves #4875. 
Previously, the properties were resolved in a way that if a property with a new name was present, it'd override any property specified using the old name. For example, if you specified both `metrics.enableStatistics=true` (old name) and `metrics.statistics.enable=false` (new name), segment store metrics would be `enabled`. These properties may be specified either via properties file (`config.properties`) or Java system properties (say, via the deployment manifest file). 
However, this behavior doesn't work in some cases. For example, Segment Store loads all the properties …
> Issue 4875: Modify name resolution strategy of configuration properties for backward compatibility

- common/src/main/java/io/pravega/common/io/StreamHelpers.java
- common/src/test/java/io/pravega/common/io/StreamHelpersTests.java
- test/testcommon/src/main/java/io/pravega/test/common/AssertExtensions.java
Not null precondition checks in `StreamHelpers#readAll` were testing the `stream` param twice.
To fix a bug where the NPE for null `target` param would be thrown 1 line late with the wrong error message.
Fixes #4901
Makes second not null precondition check match its error message. Makes null `target` throw NPE with a better error message.
Negative tests in `StreamHelpers` unit tests were added to confirm the correct exception is thrown when `target` param is left null. Negative tests were implemented for the other preconditions, which resulting in improving exception text for `maxLength` parameter and for `assertThrows` failures.
> Issue 4901: Fix not null check on target param in StreamHelpers#readAll

- controller/src/main/java/io/pravega/controller/metrics/StreamMetrics.java
- controller/src/main/java/io/pravega/controller/server/ControllerService.java
- controller/src/test/java/io/pravega/controller/task/Stream/IntermittentCnxnFailureTest.java
- shared/metrics/src/main/java/io/pravega/shared/MetricsNames.java
- test/integration/src/test/java/io/pravega/test/integration/StreamMetricsTest.java
Adds metrics for created and deleted scopes.
Fixes #4893.
This PR extends `StreamMetrics` class to also take care of reporting a couple of new metrics related to scopes creation and deletion.
New test checking that the new metrics (and some former ones) are reported.
> Issue 4893: Add Scopes Metrics

- segmentstore/server/host/src/main/java/io/pravega/segmentstore/server/host/stat/SegmentStatsRecorderImpl.java
- shared/metrics/src/main/java/io/pravega/shared/MetricsNames.java
Adds two new metrics to report the size distribution of appends and reads.
Fixes #4910.
This PR adds a couple of `OpStatsLogger` metrics in `SegmentStatsRecorderImpl` to report the size distribution of appends and reads. This information can give us important insights about the kind of writes and reads that Pravega is serving.
All tests should be working as before.
> Issue 4910: Added new metrics to report the distribution of client appends and reads

- controller/src/main/java/io/pravega/controller/task/KeyValueTable/TableMetadataTasks.java
- controller/src/test/java/io/pravega/controller/mocks/EventHelperMock.java
- controller/src/test/java/io/pravega/controller/task/KeyValueTable/TableMetadataTasksTest.java
1. Added implementation for test testWorkflowCompletionTimeout() in class "controller/src/test/java/io/pravega/controller/task/KeyValueTable/TableMetadataTasksTest.java"
which tests the usecase where Create and DeleteAPI events timeout and never complete.
2. Changed the handling for event timeout in CreateAPI to throw the timeout exception so it can be retried till DEADLINE_EXCEEDED. This makes Create and Delete APIs consistent with respect to their event timeout behavior.
Changed necessary tests for this change.
Fixes #4925
> Issue 4925: Unit Test fix for TableMetadataTasksTest in Controller

- client/src/main/java/io/pravega/client/tables/KeyValueTable.java
- client/src/main/java/io/pravega/client/tables/impl/KeyFamilySerializer.java
- client/src/main/java/io/pravega/client/tables/impl/KeyValueTableImpl.java
- client/src/main/java/io/pravega/client/tables/impl/TableSegment.java
- client/src/main/java/io/pravega/client/tables/impl/TableSegmentImpl.java
- client/src/test/java/io/pravega/client/tables/impl/KeyValueTableImplTests.java
- client/src/test/java/io/pravega/client/tables/impl/KeyValueTableMapImplTests.java
- client/src/test/java/io/pravega/client/tables/impl/KeyValueTableTestBase.java
- client/src/test/java/io/pravega/client/tables/impl/KeyValueTableTestSetup.java
- client/src/test/java/io/pravega/client/tables/impl/MockTableSegmentFactory.java
- client/src/test/java/io/pravega/client/tables/impl/TableSegmentImplTest.java
- common/src/main/java/io/pravega/common/concurrent/OrderedProcessor.java
- common/src/test/java/io/pravega/common/concurrent/OrderedProcessorTests.java
- segmentstore/server/host/src/main/java/io/pravega/segmentstore/server/host/handler/PravegaRequestProcessor.java
- segmentstore/server/host/src/test/java/io/pravega/segmentstore/server/host/handler/PravegaRequestProcessorTest.java
- test/integration/src/test/java/io/pravega/test/integration/KeyValueTableTest.java
- Enforcing the maximum Key Length, maximum Value Length and maximum Key Family Length for all KeyValueTable operations.
- Max Key Length is 4KB, Max Value Length is 1MB-1KB, Max Key Family Length is 2KB.
- Ensuring no KeyValueTable wire command exceeds the maximum wire command size.
Fixes #4933.
- KeyValueTable
- Exposed constants that define the maximum key length and maximum value length
- Exposed a constant that defines the maximum number of items that can be updated, removed or retrieved at any given time.
- Exposed a constant that defines the maximum serialization size for any multi-key operations (even though each key and value are subject to their own constraints, we enforce that a batch of these …
> Issue 4933: (Key-Value Tables) Enforcing Key and Value serialization limits

- build.gradle
Javadoc task for all projects operates on delomboked source code and produces the complete javadoc including methods generated by Lombok. However the same is not true for javadoc distribution, it works on the source code as-is that includes Lombok annotations and produces incomplete javadoc bundle. 
The change is to ensure the javadoc distribution uses delomboked source code. 
Fixes #4919 
Javadoc distribution task is updated to use delomboked source code for javadoc generation.
Running `javadocDistZip` or `javadocDistTar` tasks would produce a javadoc bundle which would have method generated by Lombok included as well
> Issue 4919: Use delomboked source code in javadoc distribution

- controller/src/main/java/io/pravega/controller/task/Stream/StreamMetadataTasks.java
Added info logs to track execution of controller's periodic retention.
Fixes #4985
New log messages added
Logs should be noticed when periodic retention is invoked or cannot be invoked because truncation record is not found.
> Issue 4985: Additional Logs for tracking controller periodic retention 

- controller/src/main/java/io/pravega/controller/server/ControllerServiceConfig.java
- controller/src/main/java/io/pravega/controller/server/ControllerServiceStarter.java
- controller/src/main/java/io/pravega/controller/server/Main.java
- controller/src/main/java/io/pravega/controller/server/impl/ControllerServiceConfigImpl.java
- controller/src/main/java/io/pravega/controller/task/Stream/StreamMetadataTasks.java
- test/integration/src/main/java/io/pravega/test/integration/demo/ControllerWrapper.java
- test/integration/src/test/java/io/pravega/test/integration/endtoendtest/RetentionTest.java
- test/system/src/test/java/io/pravega/test/system/RetentionTest.java
Adds system and integration tests for size based retention policy
Fixes #4989 
Makes retention frequency part of ControllerServiceConfig instead of the static value in Config.java. This allows integration tests to set much smaller value than the default of 30 minutes. 
Adds new integration and system test which test size and time based retentions. 
> Issue 4989: Add integration and system test for size based retention policy

- client/src/main/java/io/pravega/client/connection/impl/TcpClientConnection.java
- client/src/test/java/io/pravega/client/connection/impl/ClientConnectionTest.java
Ensure ConnectionFailedException is thrown incase the connection is already closed.
Fixes #5005 
Ensure `ConnectionFailedException ` is thrown when the connection is dropped right before the writer sends out a `WireCommands.SetupAppend`. This will ensure the SegmentWriters attempt to reconnect by fetching the correct SSS URI from the controller.
All the existing  tests should continue to pass.
> Issue 5005: Ensure ConnectionFailedException is thrown incase the connection is closed.

- bindings/src/test/java/io/pravega/storage/extendeds3/ExtendedS3SimpleStorageTests.java
- segmentstore/server/src/test/java/io/pravega/segmentstore/server/store/StreamSegmentStoreTestBase.java
Ignore flaky testEndToEndWithFencingWithChunkedStorage test.
Ignore flaky testEndToEndWithFencingWithChunkedStorage test.
Fixes #5010 
Ignore flaky test. 
Clean build.
> Issue 5010: (SLTS) Ignore flaky tests - testEndToEndWithFencingWithChunkedStorage.

- test/integration/src/test/java/io/pravega/test/integration/SingleThreadEndToEndTest.java
- test/integration/src/test/java/io/pravega/test/integration/endtoendtest/EndToEndTransactionOrderTest.java
- test/testcommon/src/main/java/io/pravega/test/common/TestUtils.java
Fix free TCP port generation logic
Fixes #5008 
- Fixes the random free TCP port logic. This should prevent sporadic integration failures due to 
`java.net.BindException: Address already in use`
- Ensure tests uses TestUtils.getAvailableListenPort()
All the existing tests should pass.
> Issue 5008: Fix free TCP port generation logic

- bindings/src/main/java/io/pravega/storage/extendeds3/ExtendedS3SimpleStorageFactory.java
- bindings/src/main/java/io/pravega/storage/extendeds3/ExtendedS3StorageFactoryCreator.java
- bindings/src/main/java/io/pravega/storage/filesystem/FileSystemSimpleStorageFactory.java
- bindings/src/main/java/io/pravega/storage/filesystem/FileSystemStorageFactoryCreator.java
- bindings/src/main/java/io/pravega/storage/hdfs/HDFSSimpleStorageFactory.java
- bindings/src/main/java/io/pravega/storage/hdfs/HDFSStorageFactoryCreator.java
- bindings/src/test/java/io/pravega/storage/StorageFactoryTests.java
- config/config.properties
- segmentstore/server/host/src/test/java/io/pravega/segmentstore/server/host/FileSystemIntegrationTest.java
- segmentstore/server/host/src/test/java/io/pravega/segmentstore/server/host/HDFSIntegrationTest.java
- segmentstore/server/host/src/test/java/io/pravega/segmentstore/server/host/StorageLoaderTest.java
- segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/chunklayer/ChunkedSegmentStorage.java
- segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/chunklayer/ChunkedSegmentStorageConfig.java
- segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/chunklayer/SystemJournal.java
- segmentstore/storage/src/test/java/io/pravega/segmentstore/storage/chunklayer/ChunkedSegmentStorageConfigTests.java
Ability to initialize ChunkedSegmentStorageConfig values from config file or properties.
Ability to initialize ChunkedSegmentStorageConfig values from config file or properties.
Fixes #5033  SLTS - Ability to initialize ChunkedSegmentStorageConfig values from config file or properties.
Read values from config file or properties and use them during initialization.
Clean build. Manual testing.
> Issue 5033: (SLTS) - Read ChunkedSegmentStorageConfig from properties.

- README.md
- documentation/src/docs/basic-reader-and-writer.md
- documentation/src/docs/controller-service.md
- documentation/src/docs/wire-protocol.md
- documentation/src/mkdocs.yml
- gradle/maven.gradle
- shared/controller-api/src/main/swagger/Controller.yaml
Update Website URL references to `https://pravega.io` (from `http` to `https`). 
Fixes #5063. 
Updates Pravega website URLs in documentation and config. 
> Issue 5063: Update Pravega Website references to `https` URL

- controller/src/main/java/io/pravega/controller/server/eventProcessor/ControllerEventProcessors.java
- controller/src/main/java/io/pravega/controller/task/Stream/StreamMetadataTasks.java
- controller/src/test/java/io/pravega/controller/server/eventProcessor/ControllerEventProcessorsTest.java
Truncate internal streams used by controller periodically using the event position from the event that has been successfully processed.
Truncate internal streams to reclaim storage space (#5044)
Fixes #5070 
Cherry pick PR 5044 into branch r0.7
All Unit and integration tests should pass.
> Issue 5070: Cherry pick fix for issue 4476 to branch r0.7

- shared/controller-api/src/main/java/io/pravega/shared/controller/tracing/RPCTracingHelpers.java
- shared/controller-api/src/test/java/io/pravega/shared/controller/tracing/RPCTracingHelpersTest.java
Cherypicks PR #5069 to r0.7 for v0.7.2. 
Fixes #5068. 
See details in PR #5069. 
See PR #5069.
> Issue 5068: (Cherry-pick to r0.7) Sanitize gRPC call metadata before logging (#5069)

- shared/protocol/src/main/java/io/pravega/shared/NameUtils.java
- shared/protocol/src/test/java/io/pravega/shared/NameUtilsTest.java
Signed-off-by: Atharva Joshi <Atharva.Joshi@dell.com>
Character length limit check is added for scope and stream name.
Fixes #5080 
Adds a precondition check to the validateStreamName & validateUserStreamName methods in NameUtils.java class to ensure that stream and scope name do not exceed 255 characters.
Attempt to add a scope or stream with a name having more than 255 characters.
> Issue 5080: Adding character length checks for scope and stream name.

- gradle.properties
Prepare r0.8 branch for release.
Fixes #5089 
Modifies `pravegaVersion` property in `gradle.properties` to `0.8.0` (from `0.8.0-SNAPSHOT`
Inspect the file.
> Issue 5089: Prepare r0.8 branch for release

- shared/protocol/src/main/java/io/pravega/shared/NameUtils.java
- shared/protocol/src/test/java/io/pravega/shared/NameUtilsTest.java
Issue 5080 put restriction on the length of the name. This adds different restrictions to internal and external names.
Fixes #5093
takes prefix or suffix into consideration when internal names are created.
added unit-tests
> Issue 5093: validate internal and external names

- config/config.properties
- shared/metrics/src/main/java/io/pravega/shared/metrics/MetricsConfig.java
Signed-off-by: Kevin Han <kevinhan88@gmail.com>
Set the default value of StatsD reporter to false to prevent accidental switching on
Closes #5096 
config.properties: #metrics.statsD.reporter.enable=false 
MetricsConfig: ENABLE_STATSD_REPORTER defaultValue was set to false
By default, StatsD metric reporter should be turned off.
> Issue 5096: set the default value of StatsD reporter to false

- segmentstore/server/src/main/java/io/pravega/segmentstore/server/reading/StreamSegmentReadIndex.java
- segmentstore/server/src/main/java/io/pravega/segmentstore/server/reading/StreamSegmentStorageReader.java
- segmentstore/server/src/main/java/io/pravega/segmentstore/server/reading/TruncatedReadResultEntry.java
- segmentstore/server/src/main/java/io/pravega/segmentstore/server/tables/ContainerTableExtensionImpl.java
- segmentstore/server/src/test/java/io/pravega/segmentstore/server/tables/ContainerTableExtensionImplTests.java
- Fixed a bug where the `Attributes.ROLLOVER_SIZE` is not properly set for Table Segments.
Fixes #5102 .
- Making sure we actually set the `DEFAULT_COMPACTION_ATTRIBUTES` on the underlying segment.
- Improved the `StreamSegmentReadIndex` to explicitly state the segment name and truncation offset if it throws a `StreamSegmentTruncatedException`.
All existing and new unit tests must pass.
> Issue 5102: (SegmentStore) TableSegment Rollover Size not properly set.

- segmentstore/server/src/main/java/io/pravega/segmentstore/server/reading/StreamSegmentReadIndex.java
- segmentstore/server/src/main/java/io/pravega/segmentstore/server/reading/StreamSegmentStorageReader.java
- segmentstore/server/src/main/java/io/pravega/segmentstore/server/reading/TruncatedReadResultEntry.java
- segmentstore/server/src/main/java/io/pravega/segmentstore/server/tables/ContainerTableExtensionImpl.java
- segmentstore/server/src/test/java/io/pravega/segmentstore/server/tables/ContainerTableExtensionImplTests.java
Cherrypick #5103 into 0.7.
- Issue 5102: (SegmentStore) TableSegment Rollover Size not properly set.
Fixes #5016.
Cherrypick #5103 into 0.7.
> Issue 5106: (R0.8) Cherry-pick #5103 

- client/src/test/java/io/pravega/client/control/impl/ControllerImplTest.java
- controller/src/main/java/io/pravega/controller/server/ControllerService.java
- controller/src/test/java/io/pravega/controller/server/ControllerServiceWithKVTableTest.java
- controller/src/test/java/io/pravega/controller/server/ControllerServiceWithPravegaTablesKVTableTest.java
- test/integration/src/test/java/io/pravega/test/integration/KeyValueTableTest.java
- test/integration/src/test/java/io/pravega/test/integration/controller/server/ControllerServiceTest.java
Integration tests use "LocalController" implementation of "Controller" interface, which is not used by the client.
The Client uses ControllerImpl implementation of Controller interface which has a check for partitionCount and hence the table creation errors out when using ControllerImpl with '0' partitionCount.
However, LocalController does not have this check and so creates the KVTable successfully even with a parititonCount=0.
Fixes #5100
Added a check to ControllerService to check for partitionCount > 0 and throw and IllegalArgumentException if it is <=0.
Added a new UT to ControllerServiceImplTest to cover the 0 partitionCount …
> Issue 5100: In Integration Tests, KVTable Creation should fail when partition count is 0

- controller/src/test/java/io/pravega/controller/task/Stream/IntermittentCnxnFailureTest.java
- shared/metrics/src/main/java/io/pravega/shared/metrics/MetricsConfig.java
- shared/metrics/src/test/java/io/pravega/shared/metrics/RegistryConfigUtilTest.java
- shared/metrics/src/test/java/io/pravega/shared/metrics/StatsProviderTest.java
- test/integration/src/test/java/io/pravega/test/integration/ControllerMetricsTest.java
- test/integration/src/test/java/io/pravega/test/integration/MetricsTest.java
- test/integration/src/test/java/io/pravega/test/integration/StreamMetricsTest.java
Signed-off-by: Kevin Han <kevinhan88@gmail.com>
We disabled metrics inside config.properties, expecting metrics is off for scenario such as system tests, unless it's enabled explicitly.
This config only works for Segmentstore but not controller, due to a bug in Controller's config propagation mechanism.
We recently disabled StatsD by default, hence Controller in system test hit an obvious illegal situation - metrics is enabled, but no exporter is defined.
This change is to disable metrics by default inside source code MetricsConfig.java, so the bug above will not have negative impact.
Long term solution is to be addressed separately.
Fixes #5126 
Disabled ENABLE_STATISTICS by default. …
> Issue 5126: disabled metrics by default to prevent misconfigs

- segmentstore/contracts/src/main/java/io/pravega/segmentstore/contracts/ReadResult.java
- segmentstore/server/host/src/test/java/io/pravega/segmentstore/server/host/handler/PravegaRequestProcessorTest.java
- segmentstore/server/src/main/java/io/pravega/segmentstore/server/reading/StreamSegmentReadIndex.java
- segmentstore/server/src/main/java/io/pravega/segmentstore/server/reading/StreamSegmentReadResult.java
- segmentstore/server/src/main/java/io/pravega/segmentstore/server/reading/StreamSegmentStorageReader.java
- segmentstore/server/src/main/java/io/pravega/segmentstore/server/tables/TableCompactor.java
- segmentstore/server/src/main/java/io/pravega/segmentstore/server/tables/WriterTableProcessor.java
- segmentstore/server/src/test/java/io/pravega/segmentstore/server/reading/AsyncReadResultProcessorTests.java
- segmentstore/server/src/test/java/io/pravega/segmentstore/server/reading/ContainerReadIndexTests.java
- segmentstore/server/src/test/java/io/pravega/segmentstore/server/reading/StreamSegmentReadResultTests.java
- segmentstore/server/src/test/java/io/pravega/segmentstore/server/tables/ReadResultMock.java
- segmentstore/server/src/test/java/io/pravega/segmentstore/server/tables/SegmentMock.java
- segmentstore/server/src/test/java/io/pravega/segmentstore/server/tables/TableCompactorTests.java
Updated the ReadResult interface with the ability to specify "copy-on-read" behavior for any data that is returned from the cache. If set, any data that is returned from the cache is copied into a heap buffer and served from there. Default is not set.
Updated TableCompactor to make use of this functionality.
Co-authored-by: Sachin Jayant Joshi <44757683+sachin-j-joshi@users.noreply.github.com>
Fixes https://github.com/pravega/pravega/issues/5131
Cherry picks https://github.com/pravega/pravega/pull/5120
> Issue 5119: (SegmentStore) Copy-on-Read for Table Segment Compaction (#5120) [Cherry-pick]

- build.gradle
Remove dependency on netty-transport-native-epoll.
Fixes #5137 
Remove dependency for epoll-native-transport on the client as it is redundant.
No changes to functionality. All the tests should continue to pass.
[client.deps_PR_5138.txt](https://github.com/pravega/pravega/files/5166257/client.deps_PR_5138.txt)
> Issue 5137:  Remove dependency on netty-transport-native-epoll

- test/integration/src/test/java/io/pravega/test/integration/RestoreBackUpDataRecoveryTest.java
The PR which explains about DR Integration test in detail is: #4716 
A short summary: It tests the scenario when durable data log fails after all the segments have been flushed to the long term storage. In such a situation, debug segment container(s) are started to restore the data in a new durable data log.
In this PR, tests have been included to start multiple debug segment containers and use transactions for writing events.
Partially fixes #5095 
There are two tests which have been included here:
1. Tests the DR scenario when 4 containers are used in running normal segment store and then 4 debug segment containers are created for data restoration.
2. Tests the scenario when events are written in the form …
> Issue 5095: DR Integration tests included for multiple containers and Transactional writers

- .travis.yml
Signed-off-by: Brian Zhou <brian.zhou@emc.com>
Cherrypick #4776 into 0.8
- Issue 4775: Add snapshot stage for all release branches
Fixes #4775 
This will benefit after the 0.8.0 release when `r0.8` branch change the version into `0.8.1-SNAPSHOT`
Cherrypick #4776 into 0.8
Build passes
> Issue 4775: (R0.8) Cherry-pick #4776

- docker/pravega/scripts/init_kubernetes.sh
Signed-off-by: prabhaker24 <prabhaker.saxena@dell.com>
init_kubernetes.sh script is not handling the case where ss pod might come up before the service when External Access is enabled and that's causing a problem when domainName is specified in the pravega manifest as in that case ss pods might get the wrong publishedIPAddress. 
Fixes #5147 
Script checks for the presence of service in case we deploy pravega with external service enabled and when it finds the service then only it will set the publishedIPAddress.
When a service doesn't exists segment store pod will go into **CrashLoopBackOff** state and will be in that state only till the External service comes up post the service starts segment store pod …
> Issue 5147: Added check for service in init_kubernetes.sh script

- build.gradle
- client/src/main/java/io/pravega/client/connection/impl/RawClient.java
- client/src/main/java/io/pravega/client/security/auth/DelegationTokenProvider.java
- client/src/main/java/io/pravega/client/security/auth/EmptyTokenProviderImpl.java
- client/src/main/java/io/pravega/client/security/auth/JwtTokenProviderImpl.java
- client/src/main/java/io/pravega/client/security/auth/StringTokenProviderImpl.java
- client/src/main/java/io/pravega/client/segment/impl/AsyncSegmentInputStreamImpl.java
- client/src/main/java/io/pravega/client/segment/impl/ConditionalOutputStreamImpl.java
- client/src/main/java/io/pravega/client/segment/impl/SegmentMetadataClientImpl.java
- client/src/main/java/io/pravega/client/segment/impl/SegmentOutputStreamImpl.java
- client/src/main/java/io/pravega/client/tables/impl/TableSegmentImpl.java
- client/src/test/java/io/pravega/client/security/auth/JwtTokenProviderImplTest.java
- client/src/test/java/io/pravega/client/segment/impl/AsyncSegmentInputStreamTest.java
- client/src/test/java/io/pravega/client/segment/impl/ConditionalOutputStreamTest.java
- client/src/test/java/io/pravega/client/tables/impl/TableSegmentImplTest.java
- controller/src/main/java/io/pravega/controller/server/SegmentHelper.java
- controller/src/test/java/io/pravega/controller/server/SegmentHelperTest.java
Force token refresh when the Segment Store indicates token expiry.
Fixes #5144 
Implements a signaling mechanism such that the client can signal the DelegationTokenProvider of the token expiry so that it refreshes the token upon the next call to `retrieveToken()`. 
> Issue 5144: Force token refresh when segment store indicates token expiry

- segmentstore/server/host/src/main/java/io/pravega/segmentstore/server/host/handler/PravegaRequestProcessor.java
- segmentstore/server/host/src/test/java/io/pravega/segmentstore/server/host/handler/PravegaRequestProcessorTest.java
- segmentstore/server/src/main/java/io/pravega/segmentstore/server/tables/TableBucketReader.java
- segmentstore/server/src/test/java/io/pravega/segmentstore/server/tables/TableBucketReaderTests.java
- segmentstore/server/src/test/java/io/pravega/segmentstore/server/tables/TableCompactorTests.java
- Enabling copy-on-read for all Segment Reads from the client.
- Enabling copy-on-read for all Segment Reads as a result of Table Segment Entry reads (TableBucketReader calls).
Fixes #5155.
- Please see #5155 for a description of the bug being resolved that includes the scenario that can lead to it.
- PR #4841 has reduced the number of memory copies that were performed on the read path from a segment, however it has eliminated one too many such copies. 
- #5119 and #5120 have introduced a mechanism that tells the Read Index to return a pointer to a copy of the data in the cache instead of a direct view of the cache data. This would prevent the scenario described in #5155 from happening (i.e., a subsequent …
> Issue 5155: (SegmentStore) Enabling copy-on-read for all Segment Reads

- segmentstore/server/src/main/java/io/pravega/segmentstore/server/CacheManager.java
- segmentstore/server/src/main/java/io/pravega/segmentstore/server/reading/ReadIndexSummary.java
- segmentstore/server/src/main/java/io/pravega/segmentstore/server/reading/StreamSegmentReadIndex.java
Fixed a concurrency bug in StreamSegmentReadIndex which could allow index summaries to get out of sync, thus causing the Cache Manager to evict more than needed.
Fixes #5154.
The Cache Manager relies on accurate data from its clients to determine whether to advance its "Oldest Generation" (i.e., tell clients to evict data) or not. If the reported Oldest Generation from the clients does not change as a result of this process, it will  keep advancing it in subsequent iterations until it can no longer do it (equals Current Generation). If Oldest Generation == Current Generation, then cache entries will not live too long in the cache, thus rendering it mostly useless.
The StreamSegmentReadIndex keeps a parallel …
> Issue 5154: (SegmentStore) Fixed a stats concurrency bug in the Read Index

- segmentstore/server/src/main/java/io/pravega/segmentstore/server/CacheManager.java
- segmentstore/server/src/main/java/io/pravega/segmentstore/server/reading/ReadIndexSummary.java
- segmentstore/server/src/main/java/io/pravega/segmentstore/server/reading/StreamSegmentReadIndex.java
CherryPick #5170.
Issue 5154: (SegmentStore) Fixed a stats concurrency bug in the Read Index (#5170)
Fixed a concurrency bug in StreamSegmentReadIndex which could allow index summaries to get out of sync, thus causing the Cache Manager to evict more than needed.
Fixes #5186.
CherryPick #5170.
> Issue #5186: CherryPick #5170 into r0.8

- segmentstore/server/host/src/main/java/io/pravega/segmentstore/server/host/handler/PravegaRequestProcessor.java
- segmentstore/server/host/src/test/java/io/pravega/segmentstore/server/host/handler/PravegaRequestProcessorTest.java
- segmentstore/server/src/main/java/io/pravega/segmentstore/server/reading/CompletableReadResultEntry.java
- segmentstore/server/src/main/java/io/pravega/segmentstore/server/reading/StreamSegmentReadIndex.java
- segmentstore/server/src/main/java/io/pravega/segmentstore/server/reading/StreamSegmentReadResult.java
- segmentstore/server/src/main/java/io/pravega/segmentstore/server/tables/TableBucketReader.java
- segmentstore/server/src/main/java/io/pravega/segmentstore/server/tables/TableCompactor.java
- segmentstore/server/src/test/java/io/pravega/segmentstore/server/reading/ContainerReadIndexTests.java
- segmentstore/server/src/test/java/io/pravega/segmentstore/server/reading/StreamSegmentReadResultTests.java
- segmentstore/server/src/test/java/io/pravega/segmentstore/server/tables/ReadResultMock.java
- segmentstore/server/src/test/java/io/pravega/segmentstore/server/tables/SegmentMock.java
- segmentstore/server/src/test/java/io/pravega/segmentstore/server/tables/TableBucketReaderTests.java
- shared/controller-api/src/generated/.gitignore
1. Setting `ReadResult.isCopyOnRead` to `true` by default. This will cause any upstream code reading from the cache to get a a copy of that data instead of a view. 
2. Fixed a bug in `StreamSegmentReadIndex.insertEntriesToCacheAndIndex` where it would incorrectly insert an entry if an existing entry that is a subset of the new one already exists.
Fixes #5207.
- Copy-on-Read
- Enable Copy-On-Read for any reads that end up getting data from the Cache. #5155 missed one case (in `WriterTableProcessor.readFromInMemorySegment`, which could lead to data corruption for Table Segments upon indexing).
- By setting it to true by default, upstream code will have to explicitly opt-out (instead of opt-in), so any other …
> Issue 5207: (SegmentStore) Read Index Bug Fixes

- gradle.properties
As part of the release process post-release activity and in preparation of the next version in this release line, this PR updates release branch from `0.8.0` to `0.8.1-SNAPSHOT`.
Resolves #5222.  
Modifies the target version in `gradle.properties`. 
> Issue 5222: Update target Pravega version from 0.8.0 to 0.8.1-SNAPSHOT

- build.gradle
Cherry-pick PR#5138 which fixes #5137 into r0.8
Fixes #5225 
See #5138 
See #5138
> Issue 5525:  Cherry-pick PR 5138 into r0.8

- controller/src/main/java/io/pravega/controller/server/Main.java
- standalone/src/test/resources/logback-test.xml
- test/integration/src/main/java/io/pravega/test/integration/selftest/Event.java
- test/integration/src/main/java/io/pravega/test/integration/selftest/Reporter.java
1. Reducing the amount of output during each build:
- Controller: not outputting GC details
- Standalone: not outputting the entire log
2. Fixed a bug in SelfTester that prevented it from working properly with tail reads.
Fixes #5219.
See "Change log description".
Build must pass. Build must have less output than `master` build.
> Issue 5219: Reducing build log output

- client/src/main/java/io/pravega/client/stream/impl/TransactionalEventStreamWriterImpl.java
- client/src/test/java/io/pravega/client/stream/impl/TransactionalEventStreamWriterTest.java
Clear SegmentTransaction  references from TransactionImpl
Fixes #5229 
Clear SegmentTransaction  references from TransactionImpl.
All the existing tests should pass.
> Issue 5229: Ensure references to SegmentTransaction are cleared post a transaction commit/abort.

- segmentstore/server/src/main/java/io/pravega/segmentstore/server/DebugSegmentContainer.java
- segmentstore/server/src/main/java/io/pravega/segmentstore/server/containers/ContainerRecoveryUtils.java
- segmentstore/server/src/main/java/io/pravega/segmentstore/server/containers/DebugStreamSegmentContainer.java
- segmentstore/server/src/test/java/io/pravega/segmentstore/server/containers/DebugStreamSegmentContainerTests.java
API to copy the contents of a segment to another segment.
Fixes #5192 
A method which takes in the names of the `source` & `target` segment as parameters, creates the `target` segment using the `storage` API and then copies the contents of the `source` segment to the `target` segment. Copy is done by filling the buffer with bytes to be read and then writing it. Buffer size is 8MB.
> Issue 5192: Copying a segment

- segmentstore/server/src/main/java/io/pravega/segmentstore/server/writer/SegmentAggregator.java
- segmentstore/server/src/test/java/io/pravega/segmentstore/server/writer/SegmentAggregatorTests.java
Fixed a bug in `SegmentAggregator.deleteUnmergedSourceSegments` where it may enter an infinite loop if the outstanding operation list contains at least one non-`MergeSegmentOperation` in it.
Fixes #5240.
Reworked the `deleteUnmergedSourceSegments` to :
- Simply iterate through the entire list and pick the operations it cares about. 
- Do not try to alter this list. It will be cleared immediately after this method exits.
Context:
- `deleteUnmergedSourceSegments` is invoked when a Segment is deleted in order to delete any (transaction) segments that have recently been merged into it but whose merger has not yet been applied to LTS. 
- Not deleting this would leave a lot of garbage around in LTS in situations …
> Issue 5240: (SegmentStore) Fixed a possible infinite loop in SegmentAggregator

- cli/admin/src/main/java/io/pravega/cli/admin/password/PasswordFileCreatorCommand.java
- cli/admin/src/test/java/io/pravega/cli/admin/password/PasswordFileCreatorCommandTest.java
- controller/src/test/java/io/pravega/controller/auth/PasswordFileCreatorTool.java
Modifies the credentials and ACL handling code to look for only three splits based on character `:`. 
Fixes #5254. 
Modifies the logic to look for only three splits based on character `:`, so that the same character used in ACLs don't end up generating additional splits. 
All unit, integration and system tests must pass. 
Note: A new unit test was added for the change in `PasswordFileCreatorCommand.java` file. 
In addition, the change was also manually verified via the `PasswordFileCreatorTool` like this: 
1. Run the tool using Intellij. Pass a file path as a program argument. 
2. On the command line, input a line containing ACLs in the new format. For example, …
> Issue 5254: Update credentials and ACL handling tools to work with the new resource format

- cli/admin/src/main/java/io/pravega/cli/admin/password/PasswordFileCreatorCommand.java
- cli/admin/src/main/java/io/pravega/cli/admin/password/PasswordFileEntryParser.java
- cli/admin/src/test/java/io/pravega/cli/admin/password/PasswordFileEntryParserTest.java
Modify Credentials and ACL handling code in CLI to parse ACLs in new format. 
Fixes #5271. 
* Fixes the bug. 
* Extracts out parsing logic to a utility class and reuses the same everywhere in the CLI code. 
All unit and integration tests should pass. 
Also, here's a test I ran manually: 
```bash
./gradlew distTar
cd build/distributions/
tar -xzvf pravega-0.9.0-2668.410b69b-SNAPSHOT.tgz
cd pravega-0.9.0-2668.410b69b-SNAPSHOT
./bin/pravega-admin password create-password-file /home/<uname>/temp/passwd "super-admin:1111_aaaa:prn::*,READ_UPDATE"
```
Now inspect the file /home/<uname>/temp/passwd. It should contain an entry  that looks like below:
```
super-admin:35...:prn::*,READ_UPDATE; …
```
> Issue 5271: Fix credentials and ACL parsing in Pravega CLI

- cli/admin/src/test/java/io/pravega/cli/admin/bookkeeper/BookkeeperCommandsTest.java
BookkeeperCommandsTest class now iterates over the available network interfaces to start the Bookkeeper test process if the default start up method fails.
Fixes #5281.
After some investigation, we realized that the `BookkeeperTestClusterCase` class fails to initiate the Bookkeeper cluster in specific situations, concretely when it cannot find the local host on the selected network interface. For this reason, we added a new defensive mechanism to the `BookkeeperCommandsTest` class: if the default `startUp()` logic fails, we retry to execute it over the available network interfaces. By doing this, we have successfully executed the tests in environments where it was failing before.
Apart from that, we have set …
> Issue 5281: Bookkeeper CLI tests failing to start up in some environments

- segmentstore/server/src/main/java/io/pravega/segmentstore/server/containers/ContainerRecoveryUtils.java
- segmentstore/server/src/test/java/io/pravega/segmentstore/server/containers/DebugStreamSegmentContainerTests.java
- segmentstore/server/src/test/java/io/pravega/segmentstore/server/store/StreamSegmentStoreTestBase.java
- test/integration/src/test/java/io/pravega/test/integration/RestoreBackUpDataRecoveryTest.java
Using timeout as a parameter to the methods in `ContainerRecoveryUtils.java`.
Fixes #5285 
Several methods in `ContainerRecoveryUtils.java` use a fixed timeout defined in the class. It's better that these methods have their own timeouts, because situations can vary. 
- `recoverAllSegments` can have different numbers of segments to recover
- `getExistingSegments` from container metadata segment can have different numbers of segments
-  `recoverSegment` can have different sizes of segment to delete
-  `deleteMetadataAndAttributeSegments` can have different sizes of segments to delete.
-  `copySegment` can have different sizes of segments to copy
> Issue 5285: Timeouts in ContainerRecoveryUtils

- segmentstore/server/src/main/java/io/pravega/segmentstore/server/containers/ContainerRecoveryUtils.java
- segmentstore/server/src/test/java/io/pravega/segmentstore/server/containers/DebugStreamSegmentContainerTests.java
- test/integration/src/test/java/io/pravega/test/integration/RestoreBackUpDataRecoveryTest.java
Avoiding newly created container metadata segment to be flushed to the Long Term Storage while recovery is in progress.
Fixes #5325 
Using config parameters which doesn't allow truncations from DurabeLog, and very infrequent flushing to the Long Term Storage. 
> Issue 5325: DR integration test does not work with FileSystem storage

- test/integration/src/test/java/io/pravega/test/integration/RestoreBackUpDataRecoveryTest.java
The PR speeds up the data recovery integration tests.
Time reduction in running tests.
- Writes lesser number of events to verify recovery. 
- Creates just one stream to write events and read back.
- Removed redundant immediate read after writing the events, as the final read is enough to verify the successfulness of the test.
- Makes flushing of Tier1 to the long term storage faster using updated writer config.
> Reducing time in DR integration tests

- segmentstore/server/src/main/java/io/pravega/segmentstore/server/reading/StreamSegmentReadIndex.java
- Fixed the error logging in `StreamSegmentReadIndex.queueStorageRead` to log the exception, not just the message.
Fixes #5375.
Added the exception as an argument to the error log.
> Issue 5375: (SegmentStore) Logging the exception in StreamSegmentReadIndex.queueStorageRead

- controller/src/main/java/io/pravega/controller/server/rpc/grpc/v1/ControllerServiceImpl.java
- controller/src/test/java/io/pravega/controller/server/rpc/grpc/v1/InMemoryControllerServiceImplTest.java
Allow retrieving delegation tokens with write access for watermark streams. 
Fixes #5379.  
Removes the check that prevents clients from obtaining delegation tokens with write access for watermark streams. 
All unit and integration tests must pass.
> Issue 5379: Allow retrieving delegation tokens with write access for watermark streams

- build.gradle
- test/system/kubernetes/setupTestPod.sh
- test/system/src/main/java/io/pravega/test/system/framework/services/kubernetes/AbstractService.java
Signed-off-by: anishakj <anisha.kj@dell.com>
Added one more param in build.gradle to accept bookkeeper  version, so that it can be added in operator configmap.
Fixes #5392
Added one param that accepts the desired bookkeeper version to be installed and update the bookkeeper-operator configmap
System tests should pass with the changes.
> Issue 5392: Adapt Gradle script to accommodate specific Bookkeeper images in system tests

- gradle.properties
Signed-off-by: rsharda <ravi.sharda@emc.com>
Changed version to `0.8.1` in `gradle.properties`.
Fixes #5408. 
Changed version to `0.8.1` in `gradle.properties`.
Inspect the change.
> Issue 5408: Remove 'snapshot' from version in preparation of releasing r0.8.1

- client/src/main/java/io/pravega/client/connection/impl/ConnectionPoolImpl.java
Ensure getClientConnection throws an exception incase the connection pool is closed.
Fixes #5414 
Ensure getClientConnection throws an exception in case the connection pool is closed. It need to attempt to obtain a lock incase connection pool is closed.
All the existing tests should continue to pass. Verified that batchclientfactory cleanup does happen on the spark connector repository where this issue is reproduced.
> Issue 5414: Ensure getClientConnection throws an exception incase the connection pool is closed.

- segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/chunklayer/ReadOperation.java
- segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/chunklayer/WriteOperation.java
List of small improvements  in ReadOperator and WriteOperator.
- Fix incorrectly reported scan counting and log messages in ReadOperator
- Fix incorrect/incomplete log messages.
- Skip chunk lookup when data is in last chunk.
Fixes #5411 
- Fix incorrectly reported scan counting and log messages in ReadOperator
- Fix incorrect/incomplete log messages.
- Skip chunk lookup when data is in last chunk.
build should pass.
> Issue 5390: SLTS - Improve logging. Shortcut findChunk for reading last chunk.

- controller/src/main/java/io/pravega/controller/store/stream/PersistentStreamBase.java
- controller/src/test/java/io/pravega/controller/store/stream/StreamMetadataStoreTest.java
Fixes transaction commit order regression introduced by #5197 where we took first n elements from an unsorted list whereby breaking the order. 
Fixes #5416 
There were two regressions introduced by 5197. 
1. We took the "limit" number of elements from an unordered list which could break the order.
2. in subsequent iterations of the loop (if some elements were filtered out), we were reading from wrong index in the loop. 
Unit test added
> Issue 5416: Transaction commit order should take 'limit' elements from ordered list

- cli/admin/src/main/java/io/pravega/cli/admin/dataRecovery/DurableLogRecoveryCommand.java
- cli/admin/src/main/java/io/pravega/cli/admin/dataRecovery/StorageListSegmentsCommand.java
Instead of using `close` from `AutoClosable`, using `@CleanUp` to clean up the resources. Instead of creating a thread pool, using thread from the command state. 
Fixes #5430 #5428 
Using lombok `@CleanUp` to clean up the resources in `DurableLogRecoveryCommand` & `StorageListSegmentsCommand` implementation.
> Issue 5430: Resource leak in Data Reovery CLI Tool Implementation

- client/src/main/java/io/pravega/client/batch/impl/SegmentIteratorImpl.java
- client/src/main/java/io/pravega/client/segment/impl/SegmentInputStreamFactory.java
- client/src/main/java/io/pravega/client/segment/impl/SegmentInputStreamFactoryImpl.java
- client/src/main/java/io/pravega/client/stream/impl/Pinger.java
- client/src/test/java/io/pravega/client/batch/impl/SegmentIteratorTest.java
- client/src/test/java/io/pravega/client/stream/mock/MockSegmentStreamFactory.java
Remove redundant read request sent by the BatchClient reader.
Fixes #5433 
Remove redundant read request sent by the BatchClient reader.
> Issue 5433: Remove redundant read request sent by the BatchClient reader.

- client/src/main/java/io/pravega/client/stream/impl/DefaultCredentials.java
- client/src/test/java/io/pravega/client/CredentialsExtractorTest.java
Make `DefaultCredentials` implement the legacy `io.pravega.client.stream.impl.Credentials` interface instead of `io.pravega.shared.security.auth.Credentials`. Since, the legacy interface, in turn, extends the new interface, `DefaultCredentials` may be assigned to both those interfaces, improving its backward compatibility. 
Resolves #5435. 
* Changes the interface that `DefaultCredentials` implements from `io.pravega.shared.security.auth.Credentials` to `io.pravega.client.stream.impl.Credentials`. 
All unit and integration tests must pass.
> Issue 5435: Allow DefaultCredentials to be assigned to both new and legacy Credentials interface

- controller/src/main/java/io/pravega/controller/server/security/auth/StreamAuthParams.java
- controller/src/test/java/io/pravega/controller/server/security/auth/StreamAuthParamsTest.java
- test/integration/src/test/java/io/pravega/test/integration/ReadWithReadPermissionsTest.java
Enable clients with read access to a stream obtain delegation tokens with write access to the corresponding internal watermark stream. 
Fixes #5420.  
Here's what the code does: 
* Allows clients with `READ` access to a stream to obtain delegation token with `READ_UPDATE` permission on the corresponding watermark stream. 
All unit, integration and system tests must pass.
> Issue 5420: Enable clients with read access to a stream obtain delegation tokens with write access to the `_MARK` stream

- client/src/main/java/io/pravega/client/control/impl/ControllerImpl.java
- client/src/main/java/io/pravega/client/control/impl/ModelHelper.java
- client/src/test/java/io/pravega/client/control/impl/ControllerImplTest.java
- controller/src/main/java/io/pravega/controller/server/ControllerService.java
- controller/src/main/java/io/pravega/controller/server/eventProcessor/LocalController.java
- controller/src/main/java/io/pravega/controller/server/eventProcessor/requesthandlers/CreateReaderGroupTask.java
- controller/src/main/java/io/pravega/controller/server/eventProcessor/requesthandlers/StreamRequestHandler.java
- controller/src/main/java/io/pravega/controller/server/rpc/grpc/v1/ControllerServiceImpl.java
- controller/src/main/java/io/pravega/controller/store/PravegaTablesScope.java
- controller/src/main/java/io/pravega/controller/store/stream/AbstractReaderGroup.java
- controller/src/main/java/io/pravega/controller/store/stream/InMemoryStreamMetadataStore.java
- controller/src/main/java/io/pravega/controller/store/stream/PravegaTablesStreamMetadataStore.java
- controller/src/main/java/io/pravega/controller/store/stream/StreamMetadataStore.java
- controller/src/main/java/io/pravega/controller/store/stream/ZKStreamMetadataStore.java
- controller/src/main/java/io/pravega/controller/store/stream/records/ReaderGroupConfigRecord.java
- controller/src/main/java/io/pravega/controller/store/stream/records/StreamCutRecord.java
- controller/src/main/java/io/pravega/controller/task/Stream/StreamMetadataTasks.java
- controller/src/test/java/io/pravega/controller/server/eventProcessor/LocalControllerTest.java
- controller/src/test/java/io/pravega/controller/server/rpc/grpc/v1/ControllerServiceImplTest.java
- controller/src/test/java/io/pravega/controller/store/stream/StreamMetadataStoreTest.java
- controller/src/test/java/io/pravega/controller/task/Stream/StreamMetadataTasksTest.java
- shared/controller-api/src/main/java/io/pravega/shared/controller/event/CreateReaderGroupEvent.java
- shared/controller-api/src/main/java/io/pravega/shared/controller/event/RGStreamCutRecord.java
- shared/controller-api/src/main/proto/Controller.proto
- shared/controller-api/src/test/java/io/pravega/shared/controller/event/ControllerEventSerializerTests.java
- test/integration/src/test/java/io/pravega/test/integration/controller/server/ControllerServiceTest.java
This PR has the following changes:
1. createReaderGroup() method in streamMetadataTasks has been changed to do only 1 metadata operation instead of multiple. The the rest of the create operations have been moved to the CreateReaderGroupTask.
2. createReaderGroup() for internal reader groups created by ControllerEventProcessor should not use events as it leads to cyclic dependency, so changed LocalController::createReaderGroup() to invoke a createReaderGroupInternal() method on StreamMetadataTasks for creating a reader group without using events.
3. Changed updateReaderGroup API to return updated generation of the ReaderGroup in addition to update operation status.
Fixes #5447
All Unit …
> Improvements to createReaderGroup and updateReaderGroup APIs

- .github/workflows/gradle.yml
- build.gradle
- cli/admin/src/test/java/io/pravega/cli/admin/utils/ConfigUtilsTest.java
- cli/admin/src/test/resources/admin-cli.properties
- cli/user/src/test/java/io/pravega/cli/user/stream/StreamCommandTest.java
Adds build and test/coverage for Java 11. Runs Rat, Checkstyle and SpotBugs before tests.
To test the Gradle build against Java 11. To more reliably upload coverage reports to Codecov. To transition off of Travis CI. To run source checks prior to tests.
Fixes #4977
Adds a workflow to run compilation against a matrix of Java versions (currently only 11) and tests against a single Java version (11) on a simulated merge.
Actions CI is running in this PR. It also runs in my fork here: https://github.com/derekm/pravega/pull/4
**Open questions**
1. Should this incorporate release or system test stages from the Travis build?
> Issue 4977: Add Actions CI for Gradle, Codecov, Java 11

- test/integration/src/test/java/io/pravega/test/integration/CheckpointTest.java
- test/integration/src/test/java/io/pravega/test/integration/ReadWithReadPermissionsTest.java
Fix flaky testCheckpointAndRestore test.
Fix flaky testCheckpointAndRestore test. reported as part of #4998 
The test was flaky since an automatic checkpointing was enabled and the test never expected it.
The test should continue to work.
> Issue 4998: Fix flaky testCheckpointAndRestore test.

- controller/src/main/java/io/pravega/controller/task/KeyValueTable/TableMetadataTasks.java
- controller/src/test/java/io/pravega/controller/task/KeyValueTable/TableMetadataTasksTest.java
Ensure that final deletion check of KVTable deletion fetches information from store.
Fixes #5470.
In some scenarios, we observed consistent failures on tests that create and subsequently delete a KVTable. The reason is that the final check for the deletion operation was relying exclusively on the already cached data in the Controller. In some situations, such data may be stale and the Controller is stuck retrying getting the stale state from the KVTable. We need to always enforce the final deletion check in `TableMetadataTasks:isDeleted` to fetch the state from the store to prevent this situation.
Previously failing tests are now consistently passing …
> Issue 5470: Final check for KVTable deletion may cache incorrect value

- client/src/main/java/io/pravega/client/control/impl/ModelHelper.java
- controller/src/main/java/io/pravega/controller/server/eventProcessor/LocalController.java
- controller/src/main/java/io/pravega/controller/server/eventProcessor/requesthandlers/CreateReaderGroupTask.java
- controller/src/main/java/io/pravega/controller/store/stream/PravegaTablesReaderGroup.java
- controller/src/main/java/io/pravega/controller/store/stream/PravegaTablesStream.java
- controller/src/main/java/io/pravega/controller/store/stream/records/ReaderGroupConfigRecord.java
- controller/src/main/java/io/pravega/controller/task/Stream/StreamMetadataTasks.java
- shared/controller-api/src/main/java/io/pravega/shared/controller/event/CreateReaderGroupEvent.java
- shared/controller-api/src/test/java/io/pravega/shared/controller/event/ControllerEventSerializerTests.java
- test/integration/src/test/java/io/pravega/test/integration/controller/server/ControllerServiceTest.java
This PR fixes the following:
1. If a Reader Group is created on Controller and then deleted and then recreated again with same scope/name the new create fails with an exception.
2. Fix minor review comments in PR 5462
Fixes #5465
The issue occurs because deleteReaderGroup API did not clean the Reader group cache after the ReaderGroup was deleted hence the old ReaderGroupId from cache was used for creating table for the new ReaderGroup cause conflict on Segment Store.
All Unit and Integration tests should pass.
Added a new test to verify ReaderGroup recreation works post delete as long as it is recreated with a new UUID.
> Issue 5465 Re-creating Reader Group with same name fails

- client/src/main/java/io/pravega/client/control/impl/ModelHelper.java
- client/src/test/java/io/pravega/client/control/impl/ModelHelperTest.java
- controller/src/main/java/io/pravega/controller/server/eventProcessor/requesthandlers/CreateReaderGroupTask.java
Added a check to identify `StreamCut.UNBOUNDED` cases and deal with them separately.
Fixes #5476 
Currently when a `ReaderGroupConfig` is converted into a controller side `ReaderGroupConfiguration`, the UNBOUNDED cases are stored as empty lists.
In both the `ModelHelper` and `CreateReaderGroupTask`, when an empty stream-cut list is found, we store it as an `UNBOUNDED` instead.
> Issue 5476: ReaderGroupConfiguration to ReaderGroupConfig conversion support for UNBOUNDED StreamCuts

- shared/metrics/src/main/java/io/pravega/shared/metrics/MetricProxy.java
Removed logging message that was called upon an incorrect condition.
Fixes #5478.
As described in #5478, PR #5422 introduced a logging message to warn about the use of a metric after being closed. The main problem is that the logic to write that log message is not correct, which makes the system to log many useless warnings.
While we could reverse the logic condition that logs that message, we propose to completely remove it given that it is called in the hot path (e.g., metrics for number of messages) in order to favor performance.
Just removed a log message, no actual code changed. All tests should be passing as before. We have validated that performance now is similar to what it was …
> Issue 5478: Performance regression due to wrong logging on metrics

- controller/src/main/java/io/pravega/controller/server/eventProcessor/requesthandlers/UpdateReaderGroupTask.java
- controller/src/main/java/io/pravega/controller/store/stream/InMemoryStream.java
- controller/src/main/java/io/pravega/controller/store/stream/PravegaTablesStream.java
- controller/src/main/java/io/pravega/controller/task/Stream/StreamMetadataTasks.java
- controller/src/test/java/io/pravega/controller/task/Stream/StreamMetadataTasksTest.java
- shared/controller-api/src/main/java/io/pravega/shared/controller/event/UpdateReaderGroupEvent.java
- shared/controller-api/src/test/java/io/pravega/shared/controller/event/ControllerEventSerializerTests.java
- test/integration/src/test/java/io/pravega/test/integration/controller/server/ControllerServiceTest.java
updateReaderGroup() API requires handling stream subscriptions when a ReaderGroup Configuration has stream changes and/or when the Config changes Retention.Type from a non-subscriber or a subscriber or vice-versa. 
These multiple combinations were not handled correctly leading to the 'updating' flag in ReaderGroupConfigRecord staying "true" and never changing to "false" when a ReaderGroup config is changed from subscriber to non-subscriber.
Fixes #5467
1. Added code to check for transition from subscriber or non-subscriber or vice versa and handle stream subscriptions accordingly in StreamMetadataTasks.updateReaderGroup and updateReaderGroupTask.execute() …
> Issue: 5467 updateReaderGroup hangs when changing configuration from subscriber to non-subscriber

- segmentstore/server/src/main/java/io/pravega/segmentstore/server/tables/ContainerKeyIndex.java
- segmentstore/server/src/test/java/io/pravega/segmentstore/server/tables/ContainerKeyIndexTests.java
Fixed flaky test ContainerKeyIndexTests.testRecoveryTimeout.
Fixes #4193.
Rewrote the part of the test using Mockito to eliminate randomness due to thread scheduling.
Reordered some instructions in ContainerKeyIndex.setupRecoveryTask.lambda2 to cancel the timeout future after unregistering it. While this has no effect on the actual behavior of the code, it enables the test code to "hook into" those callbacks to it knows when it is safe to proceed (i.e., when its assumptions about the state of the index are true).
> Issue 4193: Fixed ContainerKeyIndexTests.testRecoveryTimeout

- controller/src/test/java/io/pravega/controller/store/stream/StreamMetadataStoreTest.java
The api call `store.addReaderGroupToScope(scopeRGTest, rgName, rgConfig.getReaderGroupId())` in the test was not followed by join() and hence this future did not complete prior to the following createReaderGroup() call in some cases. 
Hence the failure.
Fixes #5498 
added join() after `store.addReaderGroupToScope(scopeRGTest, rgName, rgConfig.getReaderGroupId())`
Also added some more assertions to confirm the created completed successfully.
All Unit and Integration tests should pass.
Test `PravegaTablesStreamMetadataStoreTest.testReaderGroups()` should always pass.
> Issue 5498: Fix flaky unit test PravegaTablesStreamMetadataStoreTest.testReaderGroups

- test/integration/src/test/java/io/pravega/test/integration/ReadTest.java
Fix incorrect atTail assertion  in the test ReadTest > testReceivingReadCall
Fixes #5507 
Fix incorrect atTail assertion  in the test ReadTest > testReceivingReadCall
The test should cease being flaky.
> Issue 5507: Fix the atTail check in integration test testReceivingReadCall 

- test/system/src/test/java/io/pravega/test/system/DynamicRestApiTest.java
Fix NPE in DynamicRestApiTest system test.
Fixes #5546 
The constructor for `DefaultCredentaials ` follows the pattern ` public DefaultCredentials(@NonNull String password, @NonNull String userName)` 
and the current code 
- does not pass the password but username twice
- and the property is not set for a system test run without auth.
This has been fixed by using the helper method `Utils.buildClientConfig(..)`
The system tests should pass.
> Issue 5546:  Fix NPE in DynamicRestApiTest

- .github/workflows/gradle.yml
- .travis.yml
- README.md
- Disabled .travis.yml as we will no longer be using Travis CI. This file will be deleted in a subsequent PR.
- Set up GitHub Actions workflow as follows:
- Triggers on master branch and release branch pushes, on every pull request (regardless of branch) and release publish.
- Has a compile and static analysis job, followed by a few parallel test jobs, then a check and a snapshot (only for master branch and release branches).
- Check job is called `CI Complete`.
- Bonus features: 
- Build output is cached after the `Build` step and reused for subsequent jobs. This speeds up the overall workflow run.
- Test execution output, history and reports is cached on a per workflow-job basis. If a workflow is re-run for whatever reason (such as one job failing), the …
> Issue 5523: Enabling GithubActions and Disabling Travis CI

- controller/src/main/java/io/pravega/controller/server/eventProcessor/ControllerEventProcessors.java
- controller/src/test/java/io/pravega/controller/eventProcessor/impl/SerializedRequestHandlerTest.java
- controller/src/test/java/io/pravega/controller/fault/ControllerClusterListenerTest.java
- controller/src/test/java/io/pravega/controller/server/eventProcessor/ControllerEventProcessorsTest.java
- Issue 5496: Sporadic failure in SerializedRequestHandlerTest
- Issue 5544: Sporadic failure in ControllerClusterListenerTest
- Issue 5483: Sporadic failure in ControllerEventProcessors.testTruncate
Fixes #5483, #5496, #5544
1. SerializedRequestHandlerTest.testCancellation: make sure that the first event is picked for processing before issuing a shutdown so that we wait for it to complete. 
2. Sporadic failure in ControllerClusterListenerTest: UnfinishedStubbingException comes if we modify the mock while it is being used by some component. If that happens then we could get the aforesaid error. So the fix is to move all the mocking to the initial part of the test and manage any transition via flags. 
3. …
> Issue 5483, 5496, 5544: Flakey tests among controller unit tests

- .github/workflows/gradle.yml
Fix typo preventing release branches from publishing snapshot builds.
Fixes #5576
Fixes typo in "refs/head/r0." and "refs/head/r1.". Git branches live at "refs/heads".
v0.9 release branch should publish a snapshot on next attempt.
> Issue 5576: fix typo 'refs/head'->'refs/heads' in snapshot build

- .github/workflows/gradle.yml
Fix a typo causing snapshot publish step to be skipped for release branches.
Fixes #5578
Allows snapshots to publish for r0.* and r1.* branches.
Merge this PR and confirm r0.9 publishes a snapshot.
> Issue 5578: Cherry pick PR 5577 into r0.9

- common_server/src/test/java/io/pravega/common/util/btree/BTreeIndexTests.java
- segmentstore/server/src/main/java/io/pravega/segmentstore/server/attributes/SegmentAttributeBTreeIndex.java
- segmentstore/server/src/main/java/io/pravega/segmentstore/server/containers/StreamSegmentContainer.java
- segmentstore/server/src/main/java/io/pravega/segmentstore/server/tables/SegmentKeyCache.java
- segmentstore/server/src/main/java/io/pravega/segmentstore/server/writer/AttributeAggregator.java
- segmentstore/server/src/test/java/io/pravega/segmentstore/server/TestStorage.java
- segmentstore/server/src/test/java/io/pravega/segmentstore/server/attributes/AttributeIndexTests.java
- segmentstore/server/src/test/java/io/pravega/segmentstore/server/tables/ContainerKeyCacheTests.java
- segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/AsyncStorageWrapper.java
- segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/Storage.java
- segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/cache/CacheFullException.java
- segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/chunklayer/ChunkedSegmentStorage.java
- segmentstore/storage/src/test/java/io/pravega/segmentstore/storage/AsyncStorageWrapperTests.java
- segmentstore/storage/src/test/java/io/pravega/segmentstore/storage/chunklayer/ChunkedSegmentStorageTests.java
- Updated SegmentAttributeBTreeIndex to recover a BTreeIndex using solely the information encoded in the index file if the LTS adapter used supports atomic writes.
- Fixed a bug in SegmentAttributeBTreeIndex where it would corrupt in-memory state (and require a process restart) if unable to store entries in the cache after an update.
- Improved SegmentAttributeBTreeIndex to handle cache insertion exceptions (do not bubble up and log accordingly).
- Fixed a bug in StreamSegmentContainer where it would not be closing the Attribute Indices upon shutdown.
Fixes #5519.
Fixes #5575.
- Root Pointers
- The Segment Attribute Index (in the format of a BTreeIndex) is highly sensitive to the format of the data written …
> Issue 5519: (SegmentStore) SegmentAttributeIndex bug fixes.

- docker/bookkeeper/Dockerfile
[BookKeeper Dockerfile](https://github.com/pravega/pravega/blob/master/docker/bookkeeper/Dockerfile) uses  `apache/bookkeeper:4.11.1` as a base image. The Dockerfile downloads [pip bootstrap script](https://github.com/pravega/pravega/blob/master/docker/bookkeeper/Dockerfile#L40) whose installation is failing since it uses newer, Python 3 syntax. Thus, BookKeeper image build fails as well.
`pip` is installed in order to install `zk-shell` into the image, however, `zk-shell` is already available within base image `apache/bookkeeper:4.11.1`, thus both pip and zk-shell installations could be removed from the Dockerfile.
Fixes https://github.com/pravega/pravega/issues/5587
**What the code does** 
Removes `pip` and `zk-shell` references …
> Issue 5587: BookKeeper Docker Image build failure.

- segmentstore/server/host/src/main/java/io/pravega/segmentstore/server/host/stat/SegmentStatsRecorderImpl.java
- segmentstore/server/host/src/test/java/io/pravega/segmentstore/server/host/stat/SegmentStatsRecorderTest.java
Avoids prematurely closing SEGMENT_WRITE_BYTE metrics on segments due to eviction of transaction segment SimpleCache entries (multiple entries reference the same MetricProxy).
Signed-off-by: co-jo <colin.hryniowski@dell.com>
* See above.
* Cherry-pick in #5584 
* See above.
> Issue 5584 - r0.9 Cherry Pick

- client/src/test/java/io/pravega/client/connection/impl/ConnectionFactoryImplTest.java
- client/src/test/java/io/pravega/client/control/impl/ControllerImplTest.java
- ConnectionFactoryImplTests: added short shutdown timeout to prevent waiting 10s for thread pools to shut down.
- ControllerImplTests: split `testKeepAlive` into two tests and adjusted parameters.
- Also fixes their "Secure" counterparts (since they inherit from base).
Fixes #5604.
- ConnectionFactoryImplTests: added a shutdown timeout to speed up the `tearDown`
- ControllerImplTests`
- Split `testKeepAlive` into 2 tests as it was testing 2 different things
- Adjusted Controller configuration (both client-side and server-side) to test the same thing but without having to wait 40s for it (which was likely calculated based on config defaults).
- The new args are proportional to the old ones, but reduced by a …
> Issue 5604: Speed up Client Unit Tests

- common/src/main/java/io/pravega/common/io/BoundedInputStream.java
- common/src/test/java/io/pravega/common/io/BoundedInputStreamTests.java
Issue 5606: BoundedInputStream::markSupported() should always return false.
BoundedInputStream::markSupported() should always return false.
Fixes #5606 
Issue 5606: BoundedInputStream::markSupported() should always return false.
Tests should pass
> Issue 5606: BoundedInputStream::markSupported() should always return false.

- bindings/src/main/java/io/pravega/storage/extendeds3/ExtendedS3ChunkStorage.java
- bindings/src/main/java/io/pravega/storage/extendeds3/ExtendedS3SimpleStorageFactory.java
- bindings/src/main/java/io/pravega/storage/extendeds3/ExtendedS3Storage.java
- bindings/src/main/java/io/pravega/storage/extendeds3/ExtendedS3StorageFactory.java
- bindings/src/test/java/io/pravega/storage/extendeds3/ExtendedS3SimpleStorageTests.java
- bindings/src/test/java/io/pravega/storage/extendeds3/ExtendedS3StorageTest.java
- docker/bookkeeper/Dockerfile
- segmentstore/server/host/src/test/java/io/pravega/segmentstore/server/host/ExtendedS3IntegrationTest.java
- segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/chunklayer/ChunkedSegmentStorage.java
ExtendedS3ChunkStorage and ExtendedS3Storage should close S3Client
ExtendedS3ChunkStorage and ExtendedS3Storage should close S3Client
Fixes #5597 
ChunkedSegmentStorage closes chunkStorage. 
ExtendedS3ChunkStorage and ExtendedS3Storage close S3Client.
> Issue 5597 : ExtendedS3ChunkStorage and ExtendedS3Storage should close S3Client.

- build.gradle
- gradle/maven.gradle
project pom files generated during the gradle publish task are missing information that is required for successful publishing of artifacts to mavenCentral.
This causes validation failure on sonatype.
`failureMessage Invalid POM: /io/pravega/pravega-cli-admin/0.9.0/pravega-cli-admin-0.9.0.pom: Project name missing, Project description missing, Project URL missing, License information missing, SCM URL missing, Developer information missing`
It seems like following commit introduced the problem 0c98b91cd1be4ffd0d0fdc45da9a3e0c1da626ee.
This reverts commit 0c98b91cd1be4ffd0d0fdc45da9a3e0c1da626ee.
This reverts commit 0c98b91cd1be4ffd0d0fdc45da9a3e0c1da626ee.
Fixes #5630
**What the code …
> Issue 5630: Missing required information from pom file during publish task.

- segmentstore/server/src/main/java/io/pravega/segmentstore/server/containers/MetadataCleaner.java
- segmentstore/server/src/test/java/io/pravega/segmentstore/server/containers/MetadataCleanerTests.java
- segmentstore/server/src/test/java/io/pravega/segmentstore/server/containers/StreamSegmentContainerTests.java
Fixed a bug in MetadataCleaner where it did not respect the configuration value that was determining how many extended attributes should be kept in the memory cache.
Fixes #5636.
The MetadataCleaner is responsible with both _triggering_ the eviction of segments from the memory cache and the eviction of extended attributes from segments that are still active (the actual eviction is done in the metadata itself, based on several criteria) - that's out of scope for this PR.
The MetadataCleaner is responsible with telling the Metadata eviction  how many extended attributes per segment are desired to remain in memory. Currently it was passing `0`, which meant that it would always try to evict all of them. That …
> Issue 5636: (SegmentStore) (BugFix) Excessive eviction of Extended Attributes

- client/src/main/java/io/pravega/client/admin/impl/ReaderGroupManagerImpl.java
- client/src/main/java/io/pravega/client/control/impl/Controller.java
- client/src/main/java/io/pravega/client/control/impl/ControllerImpl.java
- client/src/main/java/io/pravega/client/control/impl/ModelHelper.java
- client/src/main/java/io/pravega/client/stream/ReaderGroupConfig.java
- client/src/test/java/io/pravega/client/admin/impl/ReaderGroupManagerImplTest.java
- client/src/test/java/io/pravega/client/control/impl/ControllerImplTest.java
- client/src/test/java/io/pravega/client/stream/mock/MockController.java
- controller/src/main/java/io/pravega/controller/server/ControllerService.java
- controller/src/main/java/io/pravega/controller/server/eventProcessor/LocalController.java
- controller/src/main/java/io/pravega/controller/server/eventProcessor/requesthandlers/CreateReaderGroupTask.java
- controller/src/main/java/io/pravega/controller/server/rest/ModelHelper.java
- controller/src/main/java/io/pravega/controller/server/rpc/grpc/v1/ControllerServiceImpl.java
- controller/src/main/java/io/pravega/controller/store/PravegaTablesScope.java
- controller/src/main/java/io/pravega/controller/store/stream/PravegaTablesStreamMetadataStore.java
- controller/src/main/java/io/pravega/controller/task/Stream/StreamMetadataTasks.java
- controller/src/test/java/io/pravega/controller/server/ControllerServiceWithStreamTest.java
- controller/src/test/java/io/pravega/controller/server/eventProcessor/LocalControllerTest.java
- controller/src/test/java/io/pravega/controller/server/rpc/auth/ControllerGrpcAuthFocusedTest.java
- controller/src/test/java/io/pravega/controller/server/rpc/grpc/v1/ControllerServiceImplTest.java
- controller/src/test/java/io/pravega/controller/task/Stream/StreamMetadataTasksTest.java
- shared/controller-api/src/main/proto/Controller.proto
- test/integration/src/test/java/io/pravega/test/integration/StreamMetricsTest.java
- test/integration/src/test/java/io/pravega/test/integration/controller/server/ControllerServiceTest.java
createReaderGroup API in Controller is not idempotent when trying to recreate a partially created ReaderGroup
Fixes #5650
Makes createReaderGroup() API Idempotent and it would now return the `ReaderGroupId` and `Generation` for the existing/new Reader Group so that State-Synchronizer can persist these values on client.
All Unit and Integration Tests should pass.
> Issue 5650: Fix for Controller CreateReaderGroup API race condition

- segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/chunklayer/ChunkedSegmentStorage.java
- segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/chunklayer/ConcatOperation.java
- segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/chunklayer/DefragmentOperation.java
- segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/chunklayer/SystemJournal.java
- segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/chunklayer/TruncateOperation.java
- segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/chunklayer/WriteOperation.java
- segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/metadata/ChunkMetadata.java
- segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/metadata/SegmentMetadata.java
Use Collections.synchronized /synchronized to force memory barrier
Use volatile for mutable variables
Fixes #5664 
There are couple of places in SLTS code where arrays and other data structures are protected from concurrent modifications yet could still potentially show thread visibility issue.
Use Collections.synchronized /synchronized to force memory barrier
Use volatile for mutable variables
> Issue 5664: (SLTS)  fix possible thread visibility issues..

- segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/chunklayer/AsyncBaseChunkStorage.java
- segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/chunklayer/BaseChunkStorage.java
AsyncBaseChunkStorage latency should not include time spent in waiting to be executed. 
Fixes https://github.com/pravega/pravega/issues/5570
_Problem fixed_
Currently the latency includes two wait times.
- Wait time until IO operation is scheduled
- Additional wait time for running task to record metrics
This gives inaccurate information.
_Solution_
BaseChunkStorage should record latencies and return them.
> Issue 5570: (SLTS) AsyncBaseChunkStorage latency should not include time spent in waiting to be executed.

- client/src/main/java/io/pravega/client/state/SynchronizerConfig.java
Ensure the segment writer spawned by the StateSyncrhonizer attempt to establish a connection with the SegmentStore in the background until the StateSyncrhonizer is closed.
Fixes #5667 
Improve the default values for `SynchronizerConfig`.
> Issue 5667: Fix the default configuration for StateSynchronizer.

- segmentstore/server/src/main/java/io/pravega/segmentstore/server/logs/SegmentMetadataUpdateTransaction.java
- segmentstore/server/src/test/java/io/pravega/segmentstore/server/logs/ContainerMetadataUpdateTransactionTests.java
- test/testcommon/src/main/java/io/pravega/test/common/TestUtils.java
Fixed a bug in SegmentMetadataUpdateTransaction where the StreamSegmentAppendOperation's offset would be inadvertently updated if that operation was rejected for other reasons.
Fixes #5679.
See #5679 for a scenario where this can occur.
The `SegmentMetadataUpdateTransaction` is responsible for validating (`preProcess****`) any operations for a segment and incorporating (`accept****`) their effects into the segment's metadata.
For `StreamSegmentAppendOperation` validation, there was a a bug where the given operation would be modified (`setStreamSegmentOffset`) even if it was about to be rejected (for another reason). In case of an internal retry (with the same operation), that append would actually be treated …
> Issue 5679: (SegmentStore) (BugFix) Appends may be erroneously rejected with BadOffsetException

- client/src/main/java/io/pravega/client/connection/impl/FlowHandler.java
- client/src/test/java/io/pravega/client/connection/impl/FlowHandlerTest.java
- segmentstore/server/host/src/main/java/io/pravega/segmentstore/server/host/handler/AppendProcessor.java
- segmentstore/server/host/src/test/java/io/pravega/segmentstore/server/host/handler/AppendProcessorTest.java
- shared/protocol/src/main/java/io/pravega/shared/protocol/netty/FailingReplyProcessor.java
- shared/protocol/src/test/java/io/pravega/shared/protocol/netty/FailingReplyProcessorTest.java
Ensure the SegmentStore responds to the KeepAlive messages from the Client. 
Fixes #5653 
The client currently configures a socket timeout of 3 mins. This implies that if there is no data received on a socket for more than 3 mins the client drops the connection and tries to re-establish a connection. 
It should be noted that the SegmentStore does not respond to `READ_SEGMENT `call unless it has data. This can leads to a situation where a given socket has no traffic being recieved from the Segmentstore . This is a rare occurence given that connection pooling is enabled by default.
In a scenario where there is no data recieved by the client for 3 mins a `SocketTimeOutException` is thrown by the Socket and the …
> Issue 5653 : Ensure SegmentStore responds to the KeepAlive wirecommand from Client.

- segmentstore/server/src/main/java/io/pravega/segmentstore/server/tables/ContainerKeyIndex.java
- segmentstore/server/src/main/java/io/pravega/segmentstore/server/tables/ContainerTableExtensionImpl.java
- segmentstore/server/src/test/java/io/pravega/segmentstore/server/tables/ContainerTableExtensionImplTests.java
Fixed a bug in ContainerKeyIndex where conditional update validation would fail if the update key has recently been relocated to a new position and the old key has been truncated away.
Fixes #5647.
The steps for a table segment compaction are as follows:
1. A group of Table Entries is copied from the head of the segment to the tail.
2. (Later) Those entries are re-indexed and the index now points to the new locations.
3. The old entries are truncated away.
Sometime after 2), the SegmentKeyCache should be updated with the new location. If not, we might be trying to access the old location. The ContainerTableExtensionImpl already handles this for reads and iterators, however this functionality has not been …
> Issue 5647: (SegmentStore) (BugFix) Table Segment Conditional Updates may fail if Compaction occurrs simultaneously

- NOTICE
* Updates NOTICE file the new year range `2017-2021`
* Adds Pravega Authors at the top to comply with CNCF guidelines 
Fixes #5683 
No code change is done, just an update in NOTICE file 
No special verification is required, build should pass though
> Issue 5683: Update the year and include Pravega Authors in NOTICE file

- NOTICE
*    Updates NOTICE file the new year range 2017-2021
*   Adds Pravega Authors at the top to comply with CNCF guidelines
Fixes #5704 
Cherry pick #5683 to r0.9
all tests should pass
> Issue 5704: Cherry pick 5683 to r0.9

- segmentstore/contracts/src/main/java/io/pravega/segmentstore/contracts/StreamSegmentStore.java
- segmentstore/server/src/main/java/io/pravega/segmentstore/server/logs/SegmentMetadataUpdateTransaction.java
- segmentstore/server/src/test/java/io/pravega/segmentstore/server/logs/ContainerMetadataUpdateTransactionTests.java
Changed validation order within SegmentMetadataUpdateTransaction.preProcessOperation(StreamSegmentAppendOperation).
`BadAttributeUpdateException` now takes precedence over `BadOffsetException` if both would be a cause for rejection.
Fixes #5709.
See description.
> Issue 5709: (SegmentStore) Swap validation order for BadAttributeUpdateException and BadOffsetException for conditional appends

- client/src/main/java/io/pravega/client/byteStream/impl/ByteStreamClientImpl.java
Ensure ByteStreamWriter attempts connecting to SSS until the writer is closed.
Related to #5667 
The SegmentWriter created by the ByteStreamWriter should attempt to establish a connection with SegmentSegment store
until the ByteStreamWriter is closed.
All the existing steps should continue to pass.
> Issue 5667: (Bug) Ensure ByteStreamWriter attempts connecting to SSS until it is closed.

- segmentstore/contracts/src/main/java/io/pravega/segmentstore/contracts/StreamSegmentStore.java
- segmentstore/server/src/main/java/io/pravega/segmentstore/server/logs/SegmentMetadataUpdateTransaction.java
- segmentstore/server/src/test/java/io/pravega/segmentstore/server/logs/ContainerMetadataUpdateTransactionTests.java
Cherry-pick #5709 into 0.9.
- Issue 5709: (SegmentStore) Swap validation order for BadAttributeUpdateException and BadOffsetException for conditional appends #5710
Fixes #5715.
Cherry-pick.
> Issue 5715: Cherry-pick #5709 into r0.9

- segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/chunklayer/ChunkedSegmentStorageConfig.java
- segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/chunklayer/GarbageCollector.java
- segmentstore/storage/src/test/java/io/pravega/segmentstore/storage/chunklayer/ChunkedSegmentStorageConfigTests.java
Change unit from seconds to milliseconds.
Also change log.info to log.debug to reduce noise.
Fixes #5673
- Change default settings from 60 seconds to 10 milliseconds. (Note that - Every 10 millisecond, new iteration starts and waits for items to be available for GC on its dedicated thread, and deletes 10 chunks max per iteration. We need small wait time between iterations.)
- Fix spelling mistake.
- Also change log.info to log.debug to reduce noise.
No regression
> Issue 5673: (SLTS) Fix wrong GC config

- test/integration/src/test/java/io/pravega/test/integration/ReadWriteTest.java
Reduced the number of events written and read in the test, as well as do not log per-event messages.
Fixes #5659.
The main reason for this test to fail sporadically is the load it imposes, which may be too much for low CPU instances, considering the 60s timeout set. Due to this reason, the `TimeoutException`s seen in this tests could come from any point during of after the IO phase. To prevent this type of issues, this PR does the following:
- It reduces the number of written events to the half (20K -> 10K).
- It changes the log level of per-event messages from `info` to `debug`, so we do not overload the system with logging activity without need. This makes things worse in slow/small instances..
**How to …
> Issue 5659: Sporadic test failure in ReadWriteTest.readWriteTest

- build.gradle
Modifies javadoc tasks by adding license files into a set of files to be packaged as a distribution bundle
Fixes #5729
javadocDistZip and javadocDistTar gradle tasks are modified to include license files into a resulting distribution bundle
Verify that upon unpacking the javadoc distribution LICENSE and NOTICE files are present
> Issue 5729: Add LICENSE and NOTICE files into javadoc distribution

- build.gradle
Modifies javadoc tasks by adding license files into a set of files to be packaged as a distribution bundle
Cherry-picks #5729 into `r0.9` branch
Fixes #5733
See details in PR #5731 
See details in PR #5731
> Issue 5729: Add LICENSE and NOTICE files into javadoc distribution #5731

- client/src/main/java/io/pravega/client/connection/impl/RawClient.java
- client/src/main/java/io/pravega/client/segment/impl/ConditionalOutputStreamImpl.java
- client/src/main/java/io/pravega/client/state/SynchronizerConfig.java
- client/src/main/java/io/pravega/client/stream/impl/EventStreamReaderImpl.java
- client/src/main/java/io/pravega/client/stream/impl/ReaderGroupStateManager.java
- client/src/test/java/io/pravega/client/connection/impl/RawClientTest.java
- client/src/test/java/io/pravega/client/segment/impl/ConditionalOutputStreamTest.java
- client/src/test/java/io/pravega/client/stream/impl/ReaderGroupStateManagerTest.java
- common/src/main/java/io/pravega/common/util/Retry.java
- segmentstore/server/host/src/test/java/io/pravega/segmentstore/server/host/handler/AppendProcessorTest.java
* Allows ConditionalOutputStream to internally retry InvalidEventNumber exceptions
* Changes reader group updates to double check the assumptions they make before updating the reader group.
Fixes #5712
Makes ConditionalOutputStream retry InvalidEventNumber replies from the server as introduced in https://github.com/pravega/pravega/pull/5710 which will allow the retry to resolve the ambiguity of whether or not a conditional append was successful if the connection drops before an ack can be received.
> Issue 5712: Internally idempotent conditional append 

- segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/bookkeeper/BookKeeperServiceRunner.java
- segmentstore/storage/impl/src/test/java/io/pravega/segmentstore/storage/impl/bookkeeper/BookKeeperLogTests.java
Pause and resume processing in Bookies instead of restarting the whole process to simulate transient failures in testAppendTransientBookieFailure.
Fixes #5656.
This test was normally failing due to a `RetriesExhaustedException`. The reason for that could be related to a problem shutting down and restarting again a Bookie process within the test, as it could take too long sporadically, thus leading the test to fail. The fix proposed basically provides an alternative way of simulating the transient failure: instead of completely restarting the Bookie process, it uses the `suspendProcessing()` and `resumeProcessing()` methods available in the test Bookie process. With these methods we can simulate a transient …
> Issue 5656: Sporadic failure in test SecureBookKeeperLogTests.testAppendTransientBookieFailure

- client/src/main/java/io/pravega/client/connection/impl/RawClient.java
- client/src/main/java/io/pravega/client/segment/impl/ConditionalOutputStreamImpl.java
- client/src/main/java/io/pravega/client/stream/impl/EventStreamReaderImpl.java
- client/src/main/java/io/pravega/client/stream/impl/ReaderGroupStateManager.java
- client/src/test/java/io/pravega/client/connection/impl/RawClientTest.java
- client/src/test/java/io/pravega/client/segment/impl/ConditionalOutputStreamTest.java
- client/src/test/java/io/pravega/client/stream/impl/ReaderGroupStateManagerTest.java
- common/src/main/java/io/pravega/common/util/Retry.java
- segmentstore/server/host/src/test/java/io/pravega/segmentstore/server/host/handler/AppendProcessorTest.java
Pulls #5712 into the r0.9 branch.
Allows ConditionalOutputStream to internally retry InvalidEventNumber exceptions
Changes reader group updates to double check the assumptions they make before updating the reader group.
> Cherry-pick #5712 into r0.9 branc

- client/src/main/java/io/pravega/client/segment/impl/SegmentOutputStreamImpl.java
- client/src/test/java/io/pravega/client/segment/impl/SegmentOutputStreamTest.java
Fix the reconnection logic with a sealed segment on the Segment writer.
Fixes #5736 
Segment Writers attempt to connect to SegmentStore in the background and a connection setup is treated as complete only post a successful AppendSetup response from the SSS.  In the case of a sealed segment it is observed that the writer does not complete the connection process which can potentially block any new writes even though the SSS has responded to the `SETUP_APPEND` wirecommand.
> Issue 5736: Ensure segment writers handles a race between SegmentIsSealed and reconnection to Segmentstore

- controller/src/main/java/io/pravega/controller/store/checkpoint/ZKCheckpointStore.java
- controller/src/test/java/io/pravega/controller/eventProcessor/impl/ZKCheckpointStoreTests.java
Fixes a bug where if RG-Data znode has the information about readers but the child znode for reader was not created then attempting to delete readergroup fails.
Fixes #5750 
The readergroup's readers positions should return readers if they are part of readergroup data even if their child znode with position was not present. 
Unit test added.
> Issue 5750: EventProcessor's readergroup failover fails if there are readers without a position in the zookeeper

- bindings/src/main/java/io/pravega/storage/extendeds3/ExtendedS3SimpleStorageFactory.java
- bindings/src/main/java/io/pravega/storage/filesystem/FileSystemSimpleStorageFactory.java
- bindings/src/main/java/io/pravega/storage/hdfs/HDFSSimpleStorageFactory.java
- segmentstore/server/src/main/java/io/pravega/segmentstore/server/SegmentStoreMetrics.java
- segmentstore/server/src/main/java/io/pravega/segmentstore/server/store/ServiceBuilder.java
- segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/chunklayer/AsyncBaseChunkStorage.java
- segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/chunklayer/ChunkStorage.java
- segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/chunklayer/ChunkStorageMetrics.java
- segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/chunklayer/ChunkedSegmentStorage.java
- segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/chunklayer/GarbageCollector.java
- segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/chunklayer/ReadIndexCache.java
- segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/chunklayer/ReadOperation.java
- segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/chunklayer/StatsReporter.java
- segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/metadata/BaseMetadataStore.java
- segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/metadata/ChunkMetadataStore.java
- segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/metadata/StorageMetadataMetrics.java
- segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/metadata/TableBasedMetadataStore.java
- segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/mocks/InMemorySimpleStorageFactory.java
- segmentstore/storage/src/test/java/io/pravega/segmentstore/storage/chunklayer/ChunkedRollingStorageTests.java
- segmentstore/storage/src/test/java/io/pravega/segmentstore/storage/chunklayer/ChunkedSegmentStorageTests.java
- segmentstore/storage/src/test/java/io/pravega/segmentstore/storage/chunklayer/SimpleStorageTests.java
- segmentstore/storage/src/test/java/io/pravega/segmentstore/storage/metadata/TableBasedMetadataStoreTests.java
- segmentstore/storage/src/test/java/io/pravega/segmentstore/storage/mocks/InMemorySimpleStorageTests.java
- shared/metrics/src/main/java/io/pravega/shared/MetricsNames.java
Improve SLTS metrics by adding more metrics.
Fixes #5737
Improve SLTS metrics by adding more metrics.
Visual verification.
> Issue 5737: (SLTS) Improve metrics

- test/integration/src/test/java/io/pravega/test/integration/AppendTest.java
- test/integration/src/test/java/io/pravega/test/integration/ReadTest.java
- test/integration/src/test/java/io/pravega/test/integration/ReadWriteTest.java
*  Test : ReadWriteTest.readWriteTest  - ensure the reader thread pool is shutdown once the readers have read all the written data.
* Test : ReadTest.testReceivingReadCall - Fix the atTail assertion by the test and ensure ByteBuf deallocation.
Fixes #5659 
Fixes #5714 
*  Test : ReadWriteTest.readWriteTest  - ensure the reader thread pool is shutdown once the readers have read all the written data. The older code would try to forcibly cancel the tasks on the threadpool if they are not completed in 5seconds.
* Test : ReadTest.testReceivingReadCall 
a.  Fix the atTail assertion by the test. The segment store can return a SEGMENT_READ with
atTail flag as true even though the test has read less than 100 bytes. …
> Issue 5659, Issue 5714: Fix Sporadic failure for tests testReceivingReadCall and readWriteTest.

- test/system/src/main/java/io/pravega/test/system/framework/services/kubernetes/AbstractService.java
Fixed Bookkeeper journal path in AbstractService class.
Fixes #5753.
Fixes a wrong path for the Bookkeeper journal 0 that could lead to data loss.
System tests are working with this PR. However, the main reason for the correlated failures in our setting needs to be fixed in https://github.com/apache/bookkeeper/issues/2612.
> Issue 5753: Correlated system test failure due to wrong BK journal directories configuration

- controller/src/test/java/io/pravega/controller/store/client/StoreClientFactoryTest.java
This flaky test fails intermittently because SessionExpiration is not done soon enough by the Curator Client.
This is possibly because of this issue with the Curator Client: https://issues.apache.org/jira/browse/CURATOR-405
which was fixed in version `4.1.0`, while currently use version `4.0.1`
The checks made by this test, do not verify any Pravega functionality and only verify behavior of curator client post session expiration. Hence this test can be removed.
Fixes #3699
Removed this test from class `StoreClientFactoryTest` as it fails intermittently but does not infact validate any Pravega functionality or behavior.
All tests in this class should pass.
> Issue 3699 : Fix flaky test StoreClientFactoryTest.testZkSessionExpiryRetry

- segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/metadata/BaseMetadataStore.java
- segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/metadata/StorageMetadataMetrics.java
- segmentstore/storage/src/test/java/io/pravega/segmentstore/storage/metadata/ChunkMetadataStoreTests.java
- shared/metrics/src/main/java/io/pravega/shared/MetricsNames.java
Fix bug that prevented BaseMetadataStore from evicting entries from buffer. 
Fix #5772 
Fix bug that prevented BaseMetadataStore from evicting entries from buffer. 
Metrics should show entries being evicted regularly.
> Issue 5772: (SLTS) - BaseMetadataStore does not evict entries from buffer. 

- client/src/main/java/io/pravega/client/control/impl/Controller.java
- client/src/main/java/io/pravega/client/control/impl/ControllerImpl.java
- client/src/main/java/io/pravega/client/control/impl/ReaderGroupConfigRejectedException.java
- client/src/main/java/io/pravega/client/stream/impl/ReaderGroupImpl.java
- client/src/test/java/io/pravega/client/control/impl/ControllerImplTest.java
- client/src/test/java/io/pravega/client/stream/impl/ReaderGroupImplTest.java
- controller/src/main/java/io/pravega/controller/server/eventProcessor/LocalController.java
- controller/src/test/java/io/pravega/controller/server/eventProcessor/LocalControllerTest.java
- test/integration/src/test/java/io/pravega/test/integration/endtoendtest/EndToEndReaderGroupTest.java
Signed-off-by: anirudhkovuru <anirudhkovuru@gmail.com>
`resetReaderGroup` now makes sure to update the `ReaderGroupState` when necessary in order to keep consistent with the controller.   
Fixes #5776 
- Added new exception `ReaderGroupConfigRejectedException` to indicate when the controller returns an `INVALD_CONFIG`.
- When this new exception is encountered, the code updates its config to the one on the controller and then tries the update again.
All tests pass and build should succeed.
> Issue 5776: resetReaderGroup fails if there are pending updates

- segmentstore/server/host/src/main/java/io/pravega/segmentstore/server/host/handler/AppendProcessor.java
- segmentstore/server/host/src/main/java/io/pravega/segmentstore/server/host/handler/WriterState.java
- segmentstore/server/host/src/test/java/io/pravega/segmentstore/server/host/handler/AppendProcessorTest.java
Ensure the WriterState object contains the updated last event number for the given writer.
Fixes #5767 
**What the code does** 
The segment writers reconnect to the SegmentStore on a connection drop. Post a connection drop the writers perform a setup append operation. As part of the setup append operation the data from the segment attributes are used to return the last store event number. In the current code, since this is a reconnect, the `WriterState `for this writer already exists;  this WriterState is used to fetch the `lasteventnumber` for the attribute update operation via `io.pravega.segmentstore.contracts.StreamSegmentStore#append`. Since this event number need not be the latest event number the SSS returns an exception due …
> Issue 5767: Ensure the WriterState object contains the updated last event number for the given writer.

- common/src/main/java/io/pravega/common/util/AbstractBufferView.java
- common/src/main/java/io/pravega/common/util/BufferView.java
- common/src/main/java/io/pravega/common/util/ByteArraySegment.java
- common/src/main/java/io/pravega/common/util/CompositeBufferView.java
- common/src/main/java/io/pravega/common/util/CompositeByteArraySegment.java
- common/src/test/java/io/pravega/common/util/AbstractBufferViewTests.java
- common/src/test/java/io/pravega/common/util/BufferViewTestBase.java
- common/src/test/java/io/pravega/common/util/CompositeBufferViewTests.java
- segmentstore/contracts/src/main/java/io/pravega/segmentstore/contracts/ReadResult.java
- segmentstore/server/src/main/java/io/pravega/segmentstore/server/reading/AsyncReadResultHandler.java
- segmentstore/server/src/main/java/io/pravega/segmentstore/server/reading/AsyncReadResultProcessor.java
- segmentstore/server/src/main/java/io/pravega/segmentstore/server/reading/StreamSegmentReadResult.java
- segmentstore/server/src/main/java/io/pravega/segmentstore/server/tables/AsyncTableEntryReader.java
- segmentstore/server/src/test/java/io/pravega/segmentstore/server/reading/StreamSegmentReadResultTests.java
- segmentstore/server/src/test/java/io/pravega/segmentstore/server/tables/AsyncTableEntryReaderTests.java
- segmentstore/server/src/test/java/io/pravega/segmentstore/server/tables/ReadResultMock.java
- shared/protocol/src/main/java/io/pravega/shared/protocol/netty/ByteBufWrapper.java
- shared/protocol/src/test/java/io/pravega/shared/protocol/netty/ByteBufWrapperTests.java
- test/integration/src/main/java/io/pravega/test/integration/selftest/adapters/TruncateableArray.java
Reduced memory consumption when reading from Table Segments by making more focused reads.
Fixes #5771.
SInce we do not know the size of the Table Entry to read (keys or values), we usually request to read 1MB of data from the Segment at the Table Entry offset, and then slice the Key and the Value out of that buffer. This poses two problems: 1) slicing still points to the whole buffer, even if we use a small portion of it and 2) most keys/values are much, much smaller than 1MB, which means we're reading and loading extra data into the heap for no good reason.
Added the ability to `ReadResult` to fine-tune the amount of data that an invocation to `next()` would fetch.  Wired this into …
> Issue 5771: (SegmentStore) Reducing the amount of heap memory used when doing Table Segment Reads.

- test/integration/src/test/java/io/pravega/test/integration/RestoreBackUpDataRecoveryTest.java
`FlushToStorage` is parallelized for multiple containers to flush in parallel.
Using `InMemoryDurableDataLog`.
Fixes #5627 
Improves test time of execution.
Time should be reduced.
> Issue 5627: Speed up RestoreBackUpDataRecoveryTest

- build.gradle
- test/system/src/main/java/io/pravega/test/system/framework/Utils.java
This PR allows user to pass customized Pravega configs. The configs are in a line separated file, e.g., a file called `pravegaConfigs` and the file content looks like below
```
pravegaservice.storage.layout=CHUNKED_STORAGE
storage.appends.enable=false
```
Run `./gradlew startK8SystemTests -DconfigFile=/path/to/pravegaConfigs` will run system tests using this config file.
Fix #5763 
Gradle parses the file into a string and pass to the test as a system property. Test framwork reads this property if it exists and put it into the option section of the Pravega manifest and use it to deploy Pravega cluster.
Manual test passed
> Issue 5763: System test custom config

- segmentstore/server/src/main/java/io/pravega/segmentstore/server/writer/StorageWriter.java
- segmentstore/server/src/main/java/io/pravega/segmentstore/server/writer/WriterState.java
- segmentstore/server/src/test/java/io/pravega/segmentstore/server/writer/StorageWriterTests.java
- segmentstore/server/src/test/java/io/pravega/segmentstore/server/writer/WriterStateTests.java
Fixed a bug in StorageWriter where it could lose already read Operations if an operation that had to be processed required the initialization of SegmentAggregator, but that initialization ended up throwing an error (i.e., from getting segment info from Storage).
Fixes #5810.
See #5810 for context on this.
The fix for this was to store the last read sequence of operations inside the `WriterState` object (as a reference) and clean it up upon a successful completion of `processReadResult`. If any sort of exception occurred during `processReadResult`, the operation on which it failed would still remain the first one in that read queue (we now `peek` it vs `poll`-ing it), and it will be attempted next time. For …
> Issue 5810: (SegmentStore) Fixed a StorageWriter bug that could lead to data loss

- segmentstore/server/src/test/java/io/pravega/segmentstore/server/containers/StreamSegmentContainerTests.java
Single line fix to call join on the list of future tasks which was missing.
Fixes #5820 
Waits for the future tasks to be completed before forcing flush and closing the container.
> Issue 5820: Missing line to wait for Future tasks to be completed

- test/integration/src/test/java/io/pravega/test/integration/StreamMetricsTest.java
* Use the proper tag set when reading various meters.
Fixes #5803.
* Minor clean-ups.
* Instead of relying on chance that we will return the expected metric, supply the *exact* tag set required to ensure the proper meter is returned.
Because we do not supply any tags, during this call `return Metrics.globalRegistry.find(metricsName).tags(tags).counter();` micrometer will fetch *all* meters (belonging to the appropriate type) with id `metricsName`. It has to make a choice which to return if there are several, so it simply chooses one at random:
```
public Counter counter() {
return findOne(Counter.class);
}
...
private <M extends Meter> M findOne(Class<M> clazz) {
return meterStream() …
```
> Issue 5803: Flakey StreamMetrics test.

- standalone/src/test/java/io/pravega/local/AuthEnabledInProcPravegaClusterTest.java
- standalone/src/test/java/io/pravega/local/InProcPravegaClusterTest.java
- standalone/src/test/java/io/pravega/local/PravegaEmulatorResource.java
- standalone/src/test/java/io/pravega/local/PravegaSanityTests.java
- standalone/src/test/java/io/pravega/local/SecurePravegaClusterTest.java
- standalone/src/test/java/io/pravega/local/TlsEnabledInProcPravegaClusterTest.java
- Ensure standalone is not started for every test, this speeds up tests.
- Disable the REST server for the tests.
Fixes #5726 
- Ensure standalone is not started for every test
The older tests brought up Pravega standalone for every @Test method. This PR ensures standalone is brought up per test file.
- Disable REST server on the standalone.
- Speeds up the standalone tests due to this logic.
The tests should pass reliably.
> Issue 5726 : Fix TimeoutException in AuthEnabledInProcPravegaClusterTest

- test/integration/src/test/java/io/pravega/test/integration/PravegaResource.java
- test/integration/src/test/java/io/pravega/test/integration/WatermarkingTest.java
Speed up WatermarkingTest
Fixes #5628 
Speed up WatermarkingTest. With these changes the test executes
```
WatermarkingTest » recreateStreamWatermarkTest | 37.475s |  
WatermarkingTest » watermarkTest | 26.793s |  
WatermarkingTest » progressingWatermarkWithWriterTimeouts | 25.281s |  
WatermarkingTest » watermarkTxnTest | 25.069s |  
```
All the existing test should continue to pass.
> Issue 5628: Speed up WatermarkingTest

- segmentstore/server/src/main/java/io/pravega/segmentstore/server/CacheUtilizationProvider.java
- segmentstore/server/src/main/java/io/pravega/segmentstore/server/ReadIndex.java
- segmentstore/server/src/main/java/io/pravega/segmentstore/server/logs/ContainerMetadataUpdateTransaction.java
- segmentstore/server/src/main/java/io/pravega/segmentstore/server/logs/DurableLog.java
- segmentstore/server/src/main/java/io/pravega/segmentstore/server/logs/MemoryStateUpdater.java
- segmentstore/server/src/main/java/io/pravega/segmentstore/server/logs/OperationProcessor.java
- segmentstore/server/src/main/java/io/pravega/segmentstore/server/logs/RecoveryProcessor.java
- segmentstore/server/src/main/java/io/pravega/segmentstore/server/logs/SegmentMetadataUpdateTransaction.java
- segmentstore/server/src/main/java/io/pravega/segmentstore/server/logs/Throttler.java
- segmentstore/server/src/main/java/io/pravega/segmentstore/server/logs/ThrottlerCalculator.java
- segmentstore/server/src/main/java/io/pravega/segmentstore/server/reading/ContainerReadIndex.java
- segmentstore/server/src/main/java/io/pravega/segmentstore/server/reading/StreamSegmentReadIndex.java
- segmentstore/server/src/test/java/io/pravega/segmentstore/server/SegmentMetadataComparer.java
- segmentstore/server/src/test/java/io/pravega/segmentstore/server/logs/DurableLogTests.java
- segmentstore/server/src/test/java/io/pravega/segmentstore/server/logs/MemoryStateUpdaterTests.java
- segmentstore/server/src/test/java/io/pravega/segmentstore/server/logs/OperationLogTestBase.java
- segmentstore/server/src/test/java/io/pravega/segmentstore/server/logs/ThrottlerCalculatorTests.java
- segmentstore/server/src/test/java/io/pravega/segmentstore/server/reading/ContainerReadIndexTests.java
- segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/bookkeeper/BookKeeperLog.java
- segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/ThrottlerSourceListenerCollection.java
- segmentstore/storage/src/test/java/io/pravega/segmentstore/storage/ThrottlerSourceListenerCollectionTests.java
- Added a new throttler (`OperationLog`) that limits the maximum number of outstanding operations in the Tier 1 Operation Log to 1 million. The throttler will kick in gradually at 95% of that value and apply full backpressure when it hits 1 million. This is to prevent lengthy recoveries.
- Cleaning up inactive or deleted Segments during recovery - we may end up accumulating much more than we need since we may be loading up multiple checkpoints. This helps situations when we could exceed the max allowed segment count even though a previous instance of that container was never close to that limit.
- Cleaning up the Read Index cache during recovery after processing `MetadataCheckpointOperations` or `StorageCheckpointOperations`. Only essential data is preserved …
> Issue 5789: (SegmentStore) Improving stability during Segment Container Recoveries

- segmentstore/server/src/main/java/io/pravega/segmentstore/server/WriterFlushResult.java
- segmentstore/server/src/main/java/io/pravega/segmentstore/server/tables/WriterTableProcessor.java
- segmentstore/server/src/test/java/io/pravega/segmentstore/server/tables/WriterTableProcessorTests.java
Fixed a bug in WriterTableProcessor where it would incorrectly try to flush if the flush conditions were not met - including if the segment had already been deleted.
Fixes #5850.
Fixes the `WriterTableProcessor` to not attempt a flush if the segment has already been deleted. This should prevent repeated attempts to modify a deleted segment - reduces log noise. This could also prevents the writer from making progress in some cases.
Unit test updated to verify the flush is not invoked.
> Issue 5850: (SegmentStore) Fixed a bug in WriterTableProcessor where it would attempt to flush to a deleted segment.

- standalone/src/test/java/io/pravega/local/AuthEnabledInProcPravegaClusterTest.java
- standalone/src/test/java/io/pravega/local/InProcPravegaClusterTest.java
- standalone/src/test/java/io/pravega/local/PravegaEmulatorResource.java
- standalone/src/test/java/io/pravega/local/SecurePravegaClusterTest.java
- standalone/src/test/java/io/pravega/local/TlsEnabledInProcPravegaClusterTest.java
- standalone/src/test/resources/logback-test.xml
Ensure the Pravega standalone is up and running before attempting to run tests.
Fixes #5726 
- Ensure the Pravega standalone is up and running before attempting to run tests.
- Enable test logs 
The test should consistently pass. 
Verified this by running standalone tests in a docker container with limited resources.
> Issue 5726: Ensure the Pravega standalone is up and running before attempting to run tests.

- segmentstore/server/src/main/java/io/pravega/segmentstore/server/tables/SegmentKeyCache.java
- segmentstore/server/src/test/java/io/pravega/segmentstore/server/tables/AsyncTableEntryReaderTests.java
- segmentstore/server/src/test/java/io/pravega/segmentstore/server/tables/ContainerKeyCacheTests.java
Fixed a thread deadlock in SegmentKeyCache that could be triggered by a callback from a `CacheFullException`.
Fixes #5840.
See #5840 for deadlock stack traces.
The situation that lead to this was:
1. Thread A: attempt to insert/update an entry in the cache (acquire Entry lock E1)
2. Thread B: CacheManager requests Cache Status From SegmentKeyCache. SegmentKeyCache acquires its own lock (S1).
3. Thread A: cache insert failed. Invoke failure callback (attempt to acquire acquire parent SegmentKeyCache lock S1)
4. Thread B: SegmentKeyCache queries Entry for status (attempts to acquire Entry lock E1)
This is a typical deadlock scenario. 
This has been fixed as follows:
- `CacheEntry.generation` and …
> Issue 5840: (SegmentStore) Fixed a deadlock in SegmentKeyCache.

- segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/chunklayer/ChunkedSegmentStorage.java
- segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/metadata/BaseMetadataStore.java
- segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/mocks/InMemoryMetadataStore.java
- segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/mocks/MockStorageMetadata.java
- segmentstore/storage/src/test/java/io/pravega/segmentstore/storage/chunklayer/ChunkedSegmentStorageTests.java
- segmentstore/storage/src/test/java/io/pravega/segmentstore/storage/metadata/ChunkMetadataStoreTests.java
- segmentstore/storage/src/test/java/io/pravega/segmentstore/storage/metadata/TableBasedMetadataStoreMockTests.java
- Fix bug where during reloading key after previous eviction, mistakenly a deep copy of wrong object was returned.
- Additional tests to repro problem.
Fixes #5853
- Fix bug where during reloading key after previous eviction, mistakenly a deep copy of wrong object was returned.
- Additional tests
> Issue 5853: SLTS - BaseMetadataStore.get does not return deep copy when loading from store.

- client/src/main/java/io/pravega/client/connection/impl/FlowHandler.java
- controller/src/conf/logback.xml
- controller/src/main/java/io/pravega/controller/server/SegmentHelper.java
- dist/conf/logback.xml
Segment Helper and Flow Handler APIs get invoked multiple times during a single Controller operation, esp. during transaction processing.
Info Logs explaining the details of each operation cause too many logs to be written and sometimes cause Controller to run our of disk space.
Fixes #5823
Changed the log level, from "INFO" to "DEBUG", for low-level operations in Segment Helper and Flow Handler, since these logs are only needed for debugging.
Changed `logback.xml` to include a new _SizeAndTimeBasedRollingPolicy_ for logs with a cap on the size of Controller logs. That way we can be sure that the disk space occupied by Controller logs never exceeds a …
> Issue 5823: Cherrypick fix for 5393 to r0.9

- test/integration/src/test/java/io/pravega/test/integration/StreamRecreationTest.java
Reduce load in testStreamRecreation to prevent sporadic timeout exceptions to occur when running in slow instances.
Fixes #5890.
The change basically reduces the number of test iterations (load) and increases the test timeout. The reason for this is that it has been seen failing once on a slow Jenkins instance. In the logs, the test was progressing correctly but slowly, which caused the timeout to occur.
Test should pass reliably on slow instances.
> Issue 5890: Sporadic failure in test StreamRecreationTest.testStreamRecreation

- standalone/src/test/java/io/pravega/local/AuthEnabledInProcPravegaClusterTest.java
- standalone/src/test/java/io/pravega/local/InProcPravegaClusterTest.java
- standalone/src/test/java/io/pravega/local/SecurePravegaClusterTest.java
- standalone/src/test/java/io/pravega/local/TlsEnabledInProcPravegaClusterTest.java
- Increase timeout for Standalone tests.
Workaround for #5895 
Increase the timeout of the tests to mitigate the issue of slow readergroup creation on the controller.
The tests should reliably pass.
> Issue 5895: Increase timeout for Standalone tests.

- client/src/main/java/io/pravega/client/ClientConfig.java
- client/src/main/java/io/pravega/client/SynchronizerClientFactory.java
- client/src/main/java/io/pravega/client/admin/ReaderGroupManager.java
- client/src/main/java/io/pravega/client/admin/impl/ReaderGroupManagerImpl.java
- client/src/main/java/io/pravega/client/connection/impl/ConnectionPoolImpl.java
- client/src/main/java/io/pravega/client/stream/impl/ClientFactoryImpl.java
- client/src/test/java/io/pravega/client/ClientConfigTest.java
- client/src/test/java/io/pravega/client/admin/impl/ReaderGroupManagerImplTest.java
- client/src/test/java/io/pravega/client/state/impl/SynchronizerTest.java
- gradle/java.gradle
Reduce threads spawned while creating a StateSynchronizer and ReaderGroupManager.
Fixes #5880 .
Reduce threads spawned while creating a StateSynchronizer and ReaderGroupManager.
- Configure connection pooling to use a max of 1 connection per segment store.
- Reduce the number of internal thread pools to 1.
Note: Verification is in progress.
> Issue 5880: Reduce threads spawned while creating a StateSynchronizer and ReaderGroupManager.

- segmentstore/server/src/main/java/io/pravega/segmentstore/server/containers/TableMetadataStore.java
- segmentstore/server/src/main/java/io/pravega/segmentstore/server/tables/ContainerTableExtensionImpl.java
- segmentstore/server/src/test/java/io/pravega/segmentstore/server/containers/TableMetadataStoreTests.java
Cherry-picking #5908 into this branch. An actual cherry-pick was not possible because of significant changes between the branches; select code has been picked and adapted instead.
Fixes #5919.
This is not your typical cherry-pick. There is significant difference in the code between r0.9 and the current master so a pure cherry-pick was not possible (needed to add several other classes and touch a lot of unrelated code). I have only picked select lines of code and brought them into this branch.
Build must pass. A cursory check against the current master branch for affected files may be done to verify appropriate code has been cherrypicked.
> Issue 5919: Cherry-pick #5908 into r0.9

- .github/workflows/gradle.yml
Uploads artifacts from github actions even in the event of build failure.
Fixes #5928
No code changes
> Issue 5928: Always upload logs from github actions builds.

- build.gradle
- test/system/kubernetes/setupTestPod.sh
Signed-off-by: Colin Hryniowski <colin.hryniowski@dell.com>
* Provides the already defined `testPodImage` system property as an environment variable to the `setupTestPod.sh` script.
Fixes #5950 
* See above.
> Issue 5950: Use `testPodImage` system property within `setupTestPod.sh`

- .github/workflows/gradle.yml
Uses latest v1 release of codecov-action to always pull in latest bug fixes. SHA commit hash detection bugs have been fixed since the previous version of codecov-action that we were pegged to.
Fixes #5955
Uses v1 catchall of codecov-action instead of fixed v1.0.15.
May allow failing PRs to succeed in processing their unit test coverage reports after upload to codecov, where final "CI Complete" build step fails to detect commit SHA during codecov upload.
> Issue #5955: Use codecov-action@v1 instead of @v1.0.15

- gradle/java.gradle
Explicitly use text colors in test build failure output.
Fixes #5953.
Replaces the undefined variable `styler` by the actual text color expected in a failure output. Also, the text color is reset after the output for a failed build has been printed.
Observed a failed build and the original error does not appear in Jenkins.
> Issue 5953: Missing "styler" property in java.gradle

- segmentstore/server/src/main/java/io/pravega/segmentstore/server/containers/StreamSegmentContainer.java
- segmentstore/server/src/main/java/io/pravega/segmentstore/server/containers/TableMetadataStore.java
- segmentstore/server/src/main/java/io/pravega/segmentstore/server/writer/AttributeAggregator.java
- segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/chunklayer/ChunkedSegmentStorage.java
- segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/chunklayer/ReadOperation.java
- segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/chunklayer/SystemJournal.java
- segmentstore/storage/src/test/java/io/pravega/segmentstore/storage/chunklayer/SystemJournalOperationsTests.java
- segmentstore/storage/src/test/java/io/pravega/segmentstore/storage/chunklayer/SystemJournalTests.java
Cherry-pick #5964 into r0.9
- Issue 5963: SLTS - writeSnapshotInfo should not block in case of cache throttle. (#5964)
Closes #5977
Cherry picks following change into r0.9 branch
- Issue 5963: SLTS - writeSnapshotInfo should not block in case of cache throttle. (#5964)
> SLTS - Cherry-pick #5964 into r0.9 branch

- segmentstore/server/src/main/java/io/pravega/segmentstore/server/writer/SegmentAggregator.java
- segmentstore/server/src/test/java/io/pravega/segmentstore/server/writer/SegmentAggregatorTests.java
If SegmentMetadata.isDeleted() returns true while SegmentAggregator.initialize() is called, then the segment is deleted from LTS and the SegmentAggregator should ignore any further operations on it.
Fixes #5994.
See description.
Existing unit tests already covered this partially. New unit tests added to verify this explicitly.
> Issue 5994: (SegmentStore) Auto-deleting LTS segments if marked as deleted in metadata

- segmentstore/server/src/main/java/io/pravega/segmentstore/server/writer/SegmentAggregator.java
- segmentstore/server/src/test/java/io/pravega/segmentstore/server/writer/SegmentAggregatorTests.java
Issue 5996: Cherry-pick #5994 to r0.9
- Issue 5994: (SegmentStore) Auto-deleting LTS segments if marked as deleted in metadata 
Fixes #5996.
Cherry-pick.
Cherry-pick.
> Issue 5996: Cherry-pick #5994 to r0.9

- client/src/test/java/io/pravega/client/connection/impl/TcpClientConnectionTest.java
Fix flakiness in the TcpClientConnection test.
Fixes #6003 
Fixes the flaky test by ensuring we invoke `ConnectionReader.stop() ` before the last byte is read from the Socket InputStream.
The test should pass reliably.
> Issue 6003:  Fix a flaky test in TcpClientConnection.

- .codecov.yml
- segmentstore/server/src/main/java/io/pravega/segmentstore/server/SegmentContainer.java
- segmentstore/server/src/main/java/io/pravega/segmentstore/server/containers/ReadOnlySegmentContainer.java
- segmentstore/server/src/main/java/io/pravega/segmentstore/server/containers/StreamSegmentContainer.java
- segmentstore/server/src/main/java/io/pravega/segmentstore/server/logs/Throttler.java
- segmentstore/server/src/main/java/io/pravega/segmentstore/server/logs/operations/CachedStreamSegmentAppendOperation.java
- segmentstore/server/src/main/java/io/pravega/segmentstore/server/logs/operations/Operation.java
- segmentstore/server/src/main/java/io/pravega/segmentstore/server/tables/ContainerTableExtensionImpl.java
- segmentstore/server/src/test/java/io/pravega/segmentstore/server/containers/StreamSegmentContainerTests.java
- segmentstore/server/src/test/java/io/pravega/segmentstore/server/store/StreamSegmentContainerRegistryTests.java
- segmentstore/server/src/test/java/io/pravega/segmentstore/server/tables/TableContext.java
All WriterTableProcessor updates now have OperationPriority.Critical, which should help them bypass throttling and help avoid a deadlock (writer blocked by throttling, but throttling because writer can't process operations).
Fixes #5999.
Added an overload to SegmentContainer.forSegment to specify a desired priority for all operations via that wrapper. That only applies to that instance. Changed ContainerTableExtensionImpl to request this with a Critical priority for WriterTableProcessor alone (not for any other operations it may execute, such as put or remove).
Tests must pass.
> Issue 5999: (SegmentStore) Increasing priority of WriterTableProcessor indexer operations

- controller/src/main/java/io/pravega/controller/server/ControllerService.java
- controller/src/test/java/io/pravega/controller/server/v1/ControllerServiceTest.java
Exception handling for commit and abort transaction is changed.  Only specific errors are thrown and the default way of handling exceptions is to fail the transaction so that the client can get retry.
Fixes #5900 
For exceptions encountered during commit and abort transaction, they are checked against DataNotFound , IllegalState and  UnknownExceptions. For these the exception is thrown. For all other exceptions,  the transaction is failed for the client to retry.
Build Pravega. Run the unit tests. Directly relevant ones are server/ControllerServiceTest.java and v1/ControllerServerTest.java.
> Issue5900: Modify Handling of Exceptions in Commit and Abort Transactions.

- controller/src/main/java/io/pravega/controller/server/eventProcessor/requesthandlers/ScaleOperationTask.java
- controller/src/main/java/io/pravega/controller/server/eventProcessor/requesthandlers/UpdateStreamTask.java
- controller/src/main/java/io/pravega/controller/store/stream/AbstractStreamMetadataStore.java
- controller/src/main/java/io/pravega/controller/store/stream/PersistentStreamBase.java
- controller/src/main/java/io/pravega/controller/store/stream/Stream.java
- controller/src/main/java/io/pravega/controller/store/stream/StreamMetadataStore.java
- controller/src/main/java/io/pravega/controller/task/Stream/StreamMetadataTasks.java
- controller/src/test/java/io/pravega/controller/server/eventProcessor/RequestHandlersTest.java
- controller/src/test/java/io/pravega/controller/task/Stream/StreamMetadataTasksTest.java
- test/integration/src/test/java/io/pravega/test/integration/ControllerRestApiTest.java
- test/integration/src/test/java/io/pravega/test/integration/controller/server/ControllerServiceTest.java
- test/integration/src/test/java/io/pravega/test/integration/controller/server/StreamMetadataTest.java
- test/integration/src/test/java/io/pravega/test/integration/endtoendtest/EndToEndUpdateTest.java
Applies configuration change and enforces minimum number of segments. Scales stream if the stream has lesser number of segments (for auto scaling) and different number of segments (for fixed policy). 
Fixes #2887 
Abstracts out scaling logic from ScaleOperationTask into StreamMetadataTask and uses that in UpdateStreamTask.
A stream can be scaled as part of update workflow if the active segments in the stream are different.
Unit tests added
> Issue 2887: AutoScale stream if configuration changes the minNumberOfSegments

- controller/src/main/java/io/pravega/controller/server/eventProcessor/requesthandlers/ScaleOperationTask.java
- controller/src/main/java/io/pravega/controller/server/eventProcessor/requesthandlers/UpdateStreamTask.java
- controller/src/main/java/io/pravega/controller/store/stream/AbstractStreamMetadataStore.java
- controller/src/main/java/io/pravega/controller/store/stream/PersistentStreamBase.java
- controller/src/main/java/io/pravega/controller/store/stream/Stream.java
- controller/src/main/java/io/pravega/controller/store/stream/StreamMetadataStore.java
- controller/src/main/java/io/pravega/controller/task/Stream/StreamMetadataTasks.java
- controller/src/test/java/io/pravega/controller/server/eventProcessor/RequestHandlersTest.java
- controller/src/test/java/io/pravega/controller/task/Stream/StreamMetadataTasksTest.java
- test/integration/src/test/java/io/pravega/test/integration/ControllerRestApiTest.java
- test/integration/src/test/java/io/pravega/test/integration/controller/server/ControllerServiceTest.java
- test/integration/src/test/java/io/pravega/test/integration/controller/server/StreamMetadataTest.java
- test/integration/src/test/java/io/pravega/test/integration/endtoendtest/EndToEndUpdateTest.java
Cherry pick #2887 into r0.9.
Applies configuration change and enforces minimum number of segments. Scales stream if the stream has lesser number of segments (for auto scaling) and different number of segments (for fixed policy).
Fixes #6026 
Cherry picks the fix into r0.9
unit tests added
> Issue 6026: Cherry pick fix for 2887 in r0.9

- segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/bookkeeper/Ledgers.java
- segmentstore/storage/impl/src/test/java/io/pravega/segmentstore/storage/impl/bookkeeper/BookKeeperLogTests.java
During the BookKeeperLog initialization phase, we are now ignoring ledgers that we cannot open-fence due to them missing but have been previously identified as being Empty.
Fixes #6030.
If a ledger has been marked as Empty, it means that we absolutely know it has no data. As such, during recovery we will auto-delete it. However, if we crash at one point in this process, it may be possible for the ledger to actually be deleted but we didn't have a chance to update the metadata accordingly. A subsequent recovery would attempt to re-open-fence this ledger and fail because it doesn't exist.
This change handles missing ledger exceptions during open-fencing and, if that ledger has been marked as empty previously, …
> Issue 6030: (SegmentStore) Ignoring missing ledgers that were previously marked as Empty.

- segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/bookkeeper/Ledgers.java
- segmentstore/storage/impl/src/test/java/io/pravega/segmentstore/storage/impl/bookkeeper/BookKeeperLogTests.java
Cherry-pick #6030 into r0.9.
Issue 6030: (SegmentStore) Ignoring missing ledgers that were previously marked as Empty. (#6031)
During the BookKeeperLog initialization phase, we are now ignoring ledgers that we cannot open-fence due to them missing but have been previously identified as being Empty.
Fixes #6034.
Cherry-pick.
> Issue 6034: Cherry-pick #6030 into r0.9

- segmentstore/server/src/main/java/io/pravega/segmentstore/server/reading/StorageReadManager.java
- segmentstore/server/src/test/java/io/pravega/segmentstore/server/reading/StorageReadManagerTests.java
Correctly handle failures in Storage::openRead when initializing StorageReadManager by caching handle only when openRead call is successful.
Fixes #6045 
Cache handle only when openRead call is successful.
Failures in openRead are rare and may include mostly transient but also non-transient errors.  The best course of action here is to not cache exception state.
Existing unit test has been modified for given scenario.
> Issue 6045: Storage - StorageReadManager does not correctly handle failures in Storage::openRead

- segmentstore/server/src/main/java/io/pravega/segmentstore/server/reading/StorageReadManager.java
- segmentstore/server/src/test/java/io/pravega/segmentstore/server/reading/StorageReadManagerTests.java
Co-authored-by: Andrei Paduroiu <andreipaduroiu@users.noreply.github.com>
Cherry pick #6048 to r0.9 branch
Fixes #6050 
Cherry pick following change 
> Issue 6045: Storage - StorageReadManager does not correctly handle failures in Storage::openRead (#6048)
> 
> Correctly handle failures in Storage::openRead when initializing StorageReadManager by caching handle only when openRead call is successful
> 
> SLTS: cherry-pick 6045 to r0.9

- segmentstore/server/src/main/java/io/pravega/segmentstore/server/containers/StreamSegmentMetadata.java
- segmentstore/server/src/test/java/io/pravega/segmentstore/server/containers/StreamSegmentMetadataTests.java
Cherry-pick PR #6039 into 0.9.
Fixes #6053.
See #6039 for details.
See #6039 for details.
> Issue 6053: Cherry-pick PR 6039 into 0.9

- config/config.properties
- segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/chunklayer/ChunkedSegmentStorageConfig.java
- segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/chunklayer/SystemJournal.java
- segmentstore/storage/src/test/java/io/pravega/segmentstore/storage/chunklayer/ChunkedSegmentStorageConfigTests.java
- segmentstore/storage/src/test/java/io/pravega/segmentstore/storage/chunklayer/ChunkedSegmentStorageMockTests.java
- segmentstore/storage/src/test/java/io/pravega/segmentstore/storage/chunklayer/ChunkedSegmentStorageTests.java
- segmentstore/storage/src/test/java/io/pravega/segmentstore/storage/chunklayer/SystemJournalTests.java
Issue 6041: Default value of storage.metadata.rollover.size.bytes.max is too big. Change it to 128MB
Fixes #6041
Default value of storage.metadata.rollover.size.bytes.max is too big. Change it to 128MB
Rename the variable to a more meaningful name and update the comment.
> Issue 6041: Default value of storage.metadata.rollover.size.bytes.max is too big. Change it to 128MB

- common_server/src/main/java/io/pravega/common/util/btree/BTreeIndex.java
- common_server/src/main/java/io/pravega/common/util/btree/BTreePage.java
- common_server/src/main/java/io/pravega/common/util/btree/PageEntry.java
- common_server/src/main/java/io/pravega/common/util/btree/PageWrapper.java
- common_server/src/main/java/io/pravega/common/util/btree/Statistics.java
- common_server/src/main/java/io/pravega/common/util/btree/UpdateablePageCollection.java
- common_server/src/test/java/io/pravega/common/util/btree/BTreeIndexTests.java
- common_server/src/test/java/io/pravega/common/util/btree/BTreePageTests.java
- common_server/src/test/java/io/pravega/common/util/btree/StatisticsTests.java
- segmentstore/server/src/main/java/io/pravega/segmentstore/server/attributes/SegmentAttributeBTreeIndex.java
- segmentstore/server/src/test/java/io/pravega/segmentstore/server/attributes/AttributeIndexTests.java
- test/testcommon/src/main/java/io/pravega/test/common/AssertExtensions.java
Keeping track of the number of Extended Attributes per Segment (if enabled)
Fixes #6042.
BTreeIndex has a new option named `maintainStatistics`. If enabled, it will keep track of the number of Entries and Pages (nodes) within it. This feature only works if the BTreeIndex has been originally created with this option (so upgrading existing indices will not work - nor is it required). 
The Statistics are stored immediately after the Root Page (and implicitly below the Index Footer/Root Pointer) every time the index persists an update. This is loaded in the `initialize` method (if it exists) and maintained in memory for quick reference.
This is not yet wired up into upstream code. When implemented in a …
> Issue 6042: (KVT Beta2) Keeping track of the number of extended attributes per Segment

- client/src/main/java/io/pravega/client/stream/impl/TransactionalEventStreamWriterImpl.java
- client/src/test/java/io/pravega/client/stream/impl/TransactionalEventStreamWriterTest.java
Ensure getTxn API starts the Transaction Pinger.
Fixes #6063 
Ensure getTxn API starts the Transaction Pinger.
All the existing and modified tests should pass.
> Issue 6063: Ensure getTxn API starts the Transaction Pinger.

- config/config.properties
- segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/chunklayer/ChunkedSegmentStorageConfig.java
- segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/chunklayer/SystemJournal.java
- segmentstore/storage/src/test/java/io/pravega/segmentstore/storage/chunklayer/ChunkedSegmentStorageConfigTests.java
- segmentstore/storage/src/test/java/io/pravega/segmentstore/storage/chunklayer/ChunkedSegmentStorageMockTests.java
- segmentstore/storage/src/test/java/io/pravega/segmentstore/storage/chunklayer/ChunkedSegmentStorageTests.java
- segmentstore/storage/src/test/java/io/pravega/segmentstore/storage/chunklayer/SystemJournalTests.java
Cherry-pick 6058 to r0.9
Closes #6073 
Cherry-picks #6058 
Cherry-pick following change #6058 to r0.9
> Issue 6041: Change default value of storage.metadata.rollover.size.bytes.max to 128MB (#6058)
> 
> Change default value of storage.metadata.rollover.size.bytes.max to 128MB.
> Rename the variable to a more meaningful name and update the comment.
> 
> Issue 6073: Cherry-pick #6058 to r0.9

- cli/admin/src/test/java/io/pravega/cli/admin/controller/SecureControllerCommandsTest.java
- controller/src/main/java/io/pravega/controller/server/ControllerServiceStarter.java
- controller/src/main/java/io/pravega/controller/server/rest/RESTServer.java
- controller/src/main/java/io/pravega/controller/server/rest/resources/StreamMetadataResourceImpl.java
- controller/src/test/java/io/pravega/controller/rest/v1/FailingSecureStreamMetaDataTests.java
- controller/src/test/java/io/pravega/controller/rest/v1/PingTest.java
- controller/src/test/java/io/pravega/controller/rest/v1/StreamMetaDataAuthFocusedTests.java
- controller/src/test/java/io/pravega/controller/rest/v1/StreamMetaDataTests.java
- test/integration/src/test/java/io/pravega/test/integration/SecureControllerRestApiTest.java
The fix allows for readergroup properties to be queried through the REST API when TLS is enabled.
Fixes #5196 
- The class `StreamMetadataResourceImpl` now has a new field for `ClientConfig` which is to be passed through its constructor.
- When generating a `ClientFactory` in order to get the readergroup properties, the above `ClientConfig` is passed. 
All tests should pass and build should succeed.
> Issue 5196: REST call for fetching readergroup properties does not work when TLS is enabled in the standalone

- controller/src/main/java/io/pravega/controller/store/stream/PersistentStreamBase.java
- controller/src/test/java/io/pravega/controller/store/stream/StreamMetadataStoreTest.java
Fixes the issue that was causing Max batch count for txn to exceed the max limit.
Fixes #6069 
the issue was that whenever we had collected 100 txns we thought we were breaking from the loop (but the loop had a switch case and the [break](https://github.com/pravega/pravega/blob/fe8a2a3dbfcef518b2749ab46cdcbf75a16bdae0/controller/src/main/java/io/pravega/controller/store/stream/PersistentStreamBase.java#L2260) actually applied to the switch case and not to the for loop. which meant that we could end up going up to 2 x limit -1 the batch count in case where we did not get limit items from first iteration and end up picking up to limit elements from …
> Issue 6069: Max batch size not being honoured sometimes

- client/src/main/java/io/pravega/client/ClientConfig.java
Remove @param and @return tag from a variable in ClientConfig.java
Fixes #6094
Remove @param tag from an instance variable `maxConnectionsPerSegmentStore` which doesn't have a getter or setter. Delombok generates Javadoc with `@param` tag to this variable which gives a warning during execution of gradle task.
running task `./gradlew :client:javadoc` gives a warning message:- 
`/pravega/client/build/delombok/io/pravega/client/ClientConfig.java:67: warning - Tag @param cannot be used in field documentation.  It can only be used in the following types of documentation: class/interface, constructor, method.
1 warning`
> Issue 6094: Remove unnecessary Param tag causing javadoc warning

- segmentstore/server/src/main/java/io/pravega/segmentstore/server/logs/ContainerMetadataUpdateTransaction.java
- segmentstore/server/src/test/java/io/pravega/segmentstore/server/logs/ContainerMetadataUpdateTransactionTests.java
Fixed a bug where it was possible to subtract 1 from the StartOffset of the segment if the previous StartOffset was set to the Length of the segment.
Fixes #6118.
Bug Fix. Removed the "subtract 1" from length when re-mapping a segment. See issue for details.
Unit test updated with check.
> Issue 6118: (SegmentStore) Bugfix for StartOffset decremented by 1 upon segment remapping

- shared/health/src/main/java/io/pravega/shared/health/HealthServiceManager.java
- shared/health/src/main/java/io/pravega/shared/health/impl/AbstractHealthContributor.java
- shared/health/src/main/java/io/pravega/shared/health/impl/HealthServiceUpdaterImpl.java
Signed-off-by: Colin Hryniowski <colin.hryniowski@dell.com>
* Makes the `close` method of `AbstractHealthContributor` synchronized.
* Add a synchronized block gated on the child `contributor`.
* Fix extra white space and fix log message.
Fixes #6130 
* The `synchronized` block protects against the case where a `HealthContributor` is closed after the `contributor.isClosed()` is called but before `Exceptions.checkNotClosed(isClosed(), this);` in the child `HealthContributor`s `getHealthSnapshot` call.
Execute the unit tests.
* Verified no errors after ~5000 iterations.
> Issue 6130: Fix HealthServiceManager Race Condition

- client/src/main/java/io/pravega/client/stream/EventWriterConfig.java
- client/src/test/java/io/pravega/client/stream/impl/PingerTest.java
- controller/src/main/java/io/pravega/controller/util/Config.java
- test/integration/src/test/java/io/pravega/test/integration/endtoendtest/EndToEndTxnWithTest.java
Default timeout at controller config.java increased to 300s from 120s and pingtxn increased to 270s from 90s to recover from the failure due to slowness or failed pingTxn API
Fixes #6117
Increases the default timeout of transaction from 2 to 5 minutes and pingtxn from 90S to 270s
> Issue 6117: Transactions get aborted due to lease expiry on failure or slowness of pingTxn API

- client/src/main/java/io/pravega/client/segment/impl/AsyncSegmentInputStreamImpl.java
- client/src/main/java/io/pravega/client/state/impl/RevisionedStreamClientImpl.java
- client/src/main/java/io/pravega/client/state/impl/StateSynchronizerImpl.java
- client/src/main/java/io/pravega/client/stream/impl/EventStreamReaderImpl.java
Ensure RevisionedStreamClient logs the fact that no new updates are present to read post a revision.
Fixes #6128 
Ensure RevisionedStreamClient logs the fact that no new updates are present to read post a revision. Improve logging for scnearios where the client observes Segment truncation. These logs will simplify debugging of scenarios where readers do not progress due to segment truncation.
No Changes in functionality. All the existing tests should continue to pass.
> Issue 6128: Ensure RevisionedStreamClient logs the fact that no new updates are present to read post a revision.

- segmentstore/server/src/main/java/io/pravega/segmentstore/server/logs/ContainerMetadataUpdateTransaction.java
- segmentstore/server/src/test/java/io/pravega/segmentstore/server/logs/ContainerMetadataUpdateTransactionTests.java
Cherry-pick:
- Issue #6118: (SegmentStore) Bugfix for StartOffset decremented by 1 up on segment remapping
- Fixed a bug where it was possible to subtract 1 from the StartOffset of the segment if the previous StartOffset was set to the Length of the segment.
Fixes #6166.
Cherry-pick.
Cherry-pick.
> Issue: 6166: Cherry-pick #6118 into r0.9

- documentation/src/docs/pravega-concepts.md
Grammar fix by removing the "a" in a sentence in Transactions session.
Fixes #6164 
N/A
Visually see the changes.
> Issue 6164: Typo in Pravega concepts Transactions section

- segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/chunklayer/SystemJournal.java
- segmentstore/storage/src/test/java/io/pravega/segmentstore/storage/chunklayer/SystemJournalOperationsTests.java
- segmentstore/storage/src/test/java/io/pravega/segmentstore/storage/chunklayer/SystemJournalTests.java
Old system journal files are now added garbage collector queue after new snapshot is saved.
Fixes #5699
Keeps track of all journal files added since last snapshot and then after new snapshot is created these file are added to GC queue.
Note - This code will not clean up previously created garbage. It just prevents GC leaks in future. 
System tests should be green.
> Issue 5699: SLTS - Old system journal files should be garbage collected.

- documentation/src/docs/pravega-concepts.md
Removed all extra spaces in pravega-concepts.md to keep the spacing consistent among the sentences. 
Fixes #6162 
N/A
Ctrl-F for double spaces on https://pravega.io/docs/nightly/pravega-concepts/. There should be 0 results for the ctrl-f after the fix.
> Issue 6162: Extra spaces on Pravega.io docs -> Understanding Pravega -> Concepts

- documentation/src/docs/pravega-concepts.md
Removed an extra space in pravega.concepts.md.
Nitpick. Fixes #6159 
N/A
Visually see the changes.
> Issue 6159: Extra space on Pravega.io docs -> Understanding Pravega -> Concepts -> Transactions

- docker/pravega/scripts/init_controller.sh
- docker/pravega/scripts/init_segmentstore.sh
Signed-off-by: anishakj <anisha.kj@dell.com>
Currently, influxdb credentails are set as part of java options in plain text.  Made change in pravega-operator to pass those credentials as secret and mount in a volume. Changes are done to read the credentials from file and populate in java options.
Fixes #5525
Modified controller and segment store initscripts to read credentials from a file and add to java options
Verified that java options are set correctly
> Issue 5525: Adding support for reading influxdb credentials from a file

- segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/chunklayer/SystemJournal.java
- segmentstore/storage/src/test/java/io/pravega/segmentstore/storage/chunklayer/SystemJournalOperationsTests.java
- segmentstore/storage/src/test/java/io/pravega/segmentstore/storage/chunklayer/SystemJournalTests.java
Old system journal files are now added garbage collector queue after new snapshot is saved.
Cherry pick https://github.com/pravega/pravega/pull/6154
Issue 5699: SLTS - Old system journal files should be garbage collected. (#6154)
Fix #6174 
Cherry pick https://github.com/pravega/pravega/pull/6154
> Cherry-pick 5699: SLTS - Old system journal files should be garbage collected. (#6154)

- cli/admin/src/main/java/io/pravega/cli/admin/dataRecovery/DurableLogRecoveryCommand.java
- common/src/main/java/io/pravega/common/util/TypedProperties.java
- common/src/test/java/io/pravega/common/util/TypedPropertiesTests.java
- segmentstore/server/src/main/java/io/pravega/segmentstore/server/store/ServiceBuilder.java
- segmentstore/server/src/main/java/io/pravega/segmentstore/server/tables/ContainerKeyIndex.java
- segmentstore/server/src/main/java/io/pravega/segmentstore/server/tables/ContainerTableExtensionImpl.java
- segmentstore/server/src/main/java/io/pravega/segmentstore/server/tables/TableExtensionConfig.java
- segmentstore/server/src/main/java/io/pravega/segmentstore/server/tables/TableWriterConnector.java
- segmentstore/server/src/main/java/io/pravega/segmentstore/server/tables/WriterTableProcessor.java
- segmentstore/server/src/test/java/io/pravega/segmentstore/server/containers/DebugStreamSegmentContainerTests.java
- segmentstore/server/src/test/java/io/pravega/segmentstore/server/containers/StreamSegmentContainerTests.java
- segmentstore/server/src/test/java/io/pravega/segmentstore/server/containers/TableMetadataStoreTests.java
- segmentstore/server/src/test/java/io/pravega/segmentstore/server/tables/ContainerKeyIndexTests.java
- segmentstore/server/src/test/java/io/pravega/segmentstore/server/tables/HashTableSegmentLayoutTests.java
- segmentstore/server/src/test/java/io/pravega/segmentstore/server/tables/TableEntryDeltaIteratorTests.java
- segmentstore/server/src/test/java/io/pravega/segmentstore/server/tables/TableExtensionConfigTests.java
- segmentstore/server/src/test/java/io/pravega/segmentstore/server/tables/TableSegmentLayoutTestBase.java
- segmentstore/server/src/test/java/io/pravega/segmentstore/server/tables/TableServiceTests.java
- segmentstore/server/src/test/java/io/pravega/segmentstore/server/tables/WriterTableProcessorTests.java
- Made `TableExtensionConfig` externally-configurable. This should allow us to properly tweak this if we have to (for debugging/repair purposes).
- Changed `ContainerKeyIndex` pre-caching to execute in batches, no bigger than 128MB. This will enable precaching of larger segments without the risk of running out of memory.
- Changed `WriterTableProcessor` to index a maximum of 128MB at once, even if the backlog is bigger. Remaining unindexed data will be processed in later iterations.
Fixes #6139.
- `TableExtensionConfig` 
- This defines the major config points for the `ContainerTableExtensionConfig` component. The original purpose was to make unit testing easier.
- This change converts it to an …
> Issue 6139: (SegmentStore) Improving Table Segment Pre-Caching and Background Indexing

- cli/admin/src/main/java/io/pravega/cli/admin/segmentstore/ReadSegmentRangeCommand.java
- cli/admin/src/test/java/io/pravega/cli/admin/segmentstore/AbstractSegmentStoreCommandsTest.java
- cli/admin/src/test/java/io/pravega/cli/admin/segmentstore/SegmentStoreCommandsTest.java
The CLI command `segmentstore read-segment` has been tweaked to write the obtained segment data into a specified file. The file will contain a byte array. 
Fixes #5560 
- `ReadSegmentRangeCommand` now has a new argument pertaining to the filename where the segment byte array will be written.
- If the file exists then a `FileAlreadyExistsException` is thrown to ensure that files are not accidentally overwritten by the user using the command.
- The contents are written into the file using the `java.io.FileOutputStream` class.
> Issue 5560: Read the contents of a segment from the storage

- client/src/main/java/io/pravega/client/connection/impl/ConnectionPoolImpl.java
- controller/src/main/java/io/pravega/controller/server/eventProcessor/requesthandlers/AbstractRequestProcessor.java
- controller/src/main/java/io/pravega/controller/server/eventProcessor/requesthandlers/CommitRequestHandler.java
- controller/src/main/java/io/pravega/controller/server/eventProcessor/requesthandlers/StreamRequestHandler.java
- controller/src/test/java/io/pravega/controller/server/eventProcessor/ControllerEventProcessorTest.java
- controller/src/test/java/io/pravega/controller/server/eventProcessor/RequestHandlersTest.java
- controller/src/test/java/io/pravega/controller/server/eventProcessor/ScaleRequestHandlerTest.java
- controller/src/test/java/io/pravega/controller/server/eventProcessor/requesthandlers/StreamRequestProcessorTest.java
- controller/src/test/java/io/pravega/controller/task/Stream/StreamMetadataTasksTest.java
This PR temporarily reverts PR #6064 as it shows instability in system tests.
Fixes #6193 
Temporarily reverts changes in #6064 .
This reverts commit 3de28524f02fb7b3f8c677237e1c5d7fa3d09e43.
System tests should pass consistently.
> Issue 6193: Temporarily revert of Retry predicate change for Controller Events(#6064)

- client/src/main/java/io/pravega/client/tables/impl/KeyValueTableImpl.java
- client/src/test/java/io/pravega/client/tables/impl/KeyValueTableTestBase.java
Fixed a bug in KeyValueTableImpl where exists() would throw an unexpected exception instead of returning true.
Also properly covering this method in unit tests.
Fixes #6195.
Unwrapping the exception from the conditional remove method.
The KeyValueTableImpl.exists() method was not previously covered by unit tests. This has been resolved and this method is properly tested now.
> Issue 6195: Bug fix for KeyValueTableImpl.exists() when the key actually exists.

- segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/chunklayer/ChunkedSegmentStorage.java
- segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/chunklayer/SystemJournal.java
- segmentstore/storage/src/test/java/io/pravega/segmentstore/storage/chunklayer/ChunkedSegmentStorageTests.java
- segmentstore/storage/src/test/java/io/pravega/segmentstore/storage/chunklayer/SystemJournalTests.java
- shared/protocol/src/main/java/io/pravega/shared/NameUtils.java
SLTS - SystemJournal - Fix concurrency issue with inconsistent metadata during snapshot creation.
Cherry pick 6185 to 0.9.2 
- SLTS - SystemJournal - Fix concurrency issue with inconsistent metadata during snapshot creation.
Fix #6189
Backport https://github.com/pravega/pravega/pull/6185 to 0.9.2 
> Cherry-pick 6184: SLTS - Fix generation of inconsistent snapshots (#6185)

- controller/src/main/java/io/pravega/controller/store/PravegaTablesScope.java
- controller/src/main/java/io/pravega/controller/store/PravegaTablesStoreHelper.java
- controller/src/test/java/io/pravega/controller/store/PravegaTablesScopeTest.java
Fix incorrect handling of empty value during listStreams
Fixes #6198 
The code fixes the following
* Due to the incorrect isEmptyRecord condition an empty value is being written into the KVT.  This caused the EOFException while attempting to read from this empty record.  
* Improve the robustness of check for last tag index chunk.
The system tests should pass reliably.
> Issue 6198: (Bugfix) Fix incorrect handling of empty value during listStreams

- client/src/main/java/io/pravega/client/connection/impl/ConnectionPoolImpl.java
- controller/src/main/java/io/pravega/controller/store/PravegaTablesScope.java
- controller/src/main/java/io/pravega/controller/store/kvtable/PravegaTablesKVTMetadataStore.java
- controller/src/test/java/io/pravega/controller/server/eventProcessor/PravegaTablesScaleRequestHandlerTest.java
- controller/src/test/java/io/pravega/controller/store/kvtable/PravegaTablesKVTMetadataStoreTest.java
- controller/src/test/java/io/pravega/controller/store/stream/TestStreamStoreFactory.java
This issue is noticed when deleteScope is invoked on a scope and during this invocation the metadataTable `keyValueTablesInScope-%s` is deleted and later deleteScope is invoked again on the same scope, which causes Client to invoke `listKeyValueTablesInScope` API on Controller, so the scope can be deleted after all KeyValueTables inside this scope have been deleted. However, during the first invocation, since the metadata table storing list of KVTs in this scope is deleted, we get a NullPointerException. This happens becuase we return a null value as token when this table is not found, 
This PR changes the code so that instead of null we now return the same continuation token as was passed by the user along …
> Issue 6205: ListKeyValueTables API throws NullPointerException if metadataTable storing list of KVTs in Scope is deleted.

- segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/chunklayer/ChunkedSegmentStorageConfig.java
- segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/chunklayer/GarbageCollector.java
- segmentstore/storage/src/test/java/io/pravega/segmentstore/storage/chunklayer/ChunkedSegmentStorageConfigTests.java
- segmentstore/storage/src/test/java/io/pravega/segmentstore/storage/chunklayer/GarbageCollectorTests.java
Issue 6223: SLTS - GC deleteSegment delete/update metadata in small batches.
Fixes #6223 
Instead of modifying all metadata for deleted segment in a single transaction, break the delete/update into multiple small batches.
> Issue 6223: SLTS - GC deleteSegment delete/update metadata in small batches.

- segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/chunklayer/DefragmentOperation.java
- segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/chunklayer/SystemJournal.java
- segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/chunklayer/TruncateOperation.java
- segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/chunklayer/WriteOperation.java
- segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/metadata/SegmentMetadata.java
- segmentstore/storage/src/test/java/io/pravega/segmentstore/storage/chunklayer/SystemJournalOperationsTests.java
- segmentstore/storage/src/test/java/io/pravega/segmentstore/storage/chunklayer/SystemJournalRecordsTests.java
- segmentstore/storage/src/test/java/io/pravega/segmentstore/storage/chunklayer/SystemJournalTests.java
- segmentstore/storage/src/test/java/io/pravega/segmentstore/storage/chunklayer/TestUtils.java
Immediately after bootstrap, persist extra snapshot to journals and use it for identification/elimination of zombie journal records.
Cherry pick #6200 
Cherry pick #6200 
Cherry pick #6200 
> Cherry-pick 6200 to r0.9

- standalone/src/main/java/io/pravega/local/InProcPravegaCluster.java
Change the rest listening port from 9092 to the default 6061 in Pravega standalone
Fixes #6150 
Remove the specification for rest listening port to let it fall back to the default value 6061.
new docker image  can work together with schema registry
> Issue 6150: Change Health Check REST port in Pravega standalone

- build.gradle
Enforce junit version 4.12
Fixes #6265 .
Enforce junit version to 4.12.
A recent upgrade of fasterxml.jackson caused an upgrade of junit dependency to 4.13.1. This causes multiple test failures.
```
+--- com.fasterxml.jackson.core:jackson-databind:2.10.5.1 -> 2.12.4
|    |    +--- com.fasterxml.jackson.core:jackson-annotations:2.12.4
|    |    |    \--- com.fasterxml.jackson:jackson-bom:2.12.4
|    |    |         +--- junit:junit:4.13.1 (c)
```
All the existing tests hould pass reliably.
> Issue 6265:  Enforce junit version 4.12

- segmentstore/contracts/src/main/java/io/pravega/segmentstore/contracts/Attributes.java
- segmentstore/contracts/src/main/java/io/pravega/segmentstore/contracts/SegmentType.java
- segmentstore/contracts/src/test/java/io/pravega/segmentstore/contracts/SegmentTypeTests.java
- segmentstore/server/host/src/main/java/io/pravega/segmentstore/server/host/handler/AppendProcessor.java
- segmentstore/server/host/src/main/java/io/pravega/segmentstore/server/host/handler/ServerConnectionInboundHandler.java
- segmentstore/server/host/src/main/java/io/pravega/segmentstore/server/host/handler/TrackedConnection.java
- segmentstore/server/host/src/test/java/io/pravega/segmentstore/server/host/handler/AppendProcessorTest.java
- segmentstore/server/src/main/java/io/pravega/segmentstore/server/containers/ContainerConfig.java
- segmentstore/server/src/main/java/io/pravega/segmentstore/server/containers/MetadataCleaner.java
- segmentstore/server/src/main/java/io/pravega/segmentstore/server/containers/MetadataStore.java
- segmentstore/server/src/main/java/io/pravega/segmentstore/server/logs/SegmentMetadataUpdateTransaction.java
- segmentstore/server/src/main/java/io/pravega/segmentstore/server/writer/StorageWriter.java
- segmentstore/server/src/test/java/io/pravega/segmentstore/server/containers/MetadataCleanerTests.java
- segmentstore/server/src/test/java/io/pravega/segmentstore/server/containers/MetadataStoreTestBase.java
- segmentstore/server/src/test/java/io/pravega/segmentstore/server/logs/ContainerMetadataUpdateTransactionTests.java
- segmentstore/server/src/test/java/io/pravega/segmentstore/server/writer/StorageWriterTests.java
- shared/protocol/src/main/java/io/pravega/shared/NameUtils.java
- shared/protocol/src/main/java/io/pravega/shared/protocol/netty/DelegatingRequestProcessor.java
- shared/protocol/src/main/java/io/pravega/shared/protocol/netty/FailingRequestProcessor.java
- shared/protocol/src/main/java/io/pravega/shared/protocol/netty/RequestProcessor.java
- shared/protocol/src/test/java/io/pravega/shared/NameUtilsTest.java
- shared/protocol/src/test/java/io/pravega/shared/StreamSegmentNameUtilsTests.java
- shared/protocol/src/test/java/io/pravega/shared/protocol/netty/DelegatingRequestProcessorTest.java
- shared/protocol/src/test/java/io/pravega/shared/protocol/netty/FailingRequestProcessorTest.java
- shared/protocol/src/test/java/io/pravega/shared/segment/SegmentToContainerMapperTests.java
* Adds new `TransientSegment` type/role. 
* Adds `createTransientSegment` call in the `AppendProcessor`.
* Overload the `close` call on a `TrackedConnection` to allow for a call back.
* Adds a `close` call on the `AppendProcessor`, which will be called on the closure of its `TrackedConnection`.
* Create according `NameUtils` methods for new `TransientSegment` type.
* Setup boilerplate code for deleting unused transient segements.
Partially completes #6137.
* See above.
* Run unit tests (TBD).
> Issue 6137: Large Appends SegmentStore

- docker/pravega/Dockerfile
- docker/pravega/scripts/init_kubernetes.sh
Added installation of `jq` tool 
Fixes #6278 
Modified Pravega Dockerfile to include installation of `jq` tool on top of the base image 
Run the docker image in K8s environment and have External Access enabled
> Issue 6278: Add missing jq tool

- test/system/kubernetes/fluentBitSetup.sh
* Add variable at start of script to avoid any unbound variable errors.
Fixes #6284.
* See above.
* Run `./fluentBitSetup.sh fetch-all-logs`.
> Issue 6284: Log Collection Unbound Variable Fix.

- docker/bookkeeper/Dockerfile
- docker/bookkeeper/entrypoint.sh
Removing JAVA_HOME from entrypoint.sh and adding it to Dockerfile, so that bookkeeper OSS and branch builds can use different java runtime.
Previously thought of bundling this change with another issue, but as it is taking time to review it committing this separately.
Fixes #6272 
sets JAVA_HOME
We should be able to substitute bookkeeper image (either bookkeeper OSS or branch build)
> Issue 6272: Removing JAVA_HOME from entrypoint.sh and adding it to Dockerfile

- test/system/src/main/java/io/pravega/test/system/framework/services/kubernetes/AbstractService.java
Added memory limits for JVM heap size and Direct Memory in Kubernetes system test pods.
Fixes #6294.
Sets some reasonable memory limits to pods, specially to Segment Store pods which could go OOM in some situations as no heap or direct memory limits are set. Specifically, the Segment Store defines a 4GB cache size by default and 5GB of direct memory are allocated. The pod size is 6GB and the JVM heap size is set to 1GB. Given the load in our system tests, this should me more than sufficient.
Have not found OOM issues with this change.
> Issue 6294: Need for setting memory limits in Kubernetes system test pods

- gradle.properties
- segmentstore/server/src/main/java/io/pravega/segmentstore/server/containers/ContainerEventProcessorImpl.java
- segmentstore/server/src/test/java/io/pravega/segmentstore/server/containers/StreamSegmentContainerTests.java
Replace call to `super.close()` by `super.stopAsync()` in `EventProcessorImpl.close()` method to avoid locking threads until the service is stopped.
Fixes #6314.
Use `super.stopAsync()` in `EventProcessorImpl.close()` to stop the `EventProcessorImpl` service. Before, the `close()` method in `EventProcessorImpl` called `super.close()`, which contains a `Futures.await()` call that blocks a thread until the service is stopped. Now, there are no blocking calls in the `close()` call of `EventProcessorImpl`.
Modified test to validate that the `EventProcessorImpl` service is actually stopped. All other tests should pass.
> Issue 6314: ContainerEventProcessor close method may exhaust threads if executed in bursts

- segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/chunklayer/ChunkedSegmentStorage.java
- segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/chunklayer/ConcatOperation.java
- segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/chunklayer/SystemJournal.java
- segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/chunklayer/TruncateOperation.java
- segmentstore/storage/src/test/java/io/pravega/segmentstore/storage/chunklayer/SystemJournalTests.java
Issue 6306 : SLTS - avoid deadlock in truncate on system segments and improve logs.
Fixes #6306 and #6297
- In case of system segments do not attempt to delete block read index entries.
- Add debug logs for openRead, openWrite and getStreamSegmentInfo methods.
- reduce log noise in system journals
Tests must pass
> Issue 6306 : SLTS - avoid deadlock in truncate

- segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/chunklayer/ChunkedSegmentStorage.java
- segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/chunklayer/ConcatOperation.java
- segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/chunklayer/SystemJournal.java
- segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/chunklayer/TruncateOperation.java
- segmentstore/storage/src/test/java/io/pravega/segmentstore/storage/chunklayer/SystemJournalTests.java
Issue 6306: SLTS - avoid deadlock in truncate (#6307)
In case of system segments, do not attempt to delete block read index entries. Add debug logs for openRead, openWrite and getStreamSegmentInfo methods. Reduce log noise in system journals
Fix #6327 Cherry-pick #6307 to r0.10
Cherry-pick #6307 to r0.10
Tests should pass
> Issue 6327: Cherry pick #6307 to r0.10 #6327

- controller/src/main/java/io/pravega/controller/server/SegmentHelper.java
- controller/src/test/java/io/pravega/controller/server/SegmentHelperTest.java
- segmentstore/server/host/src/main/java/io/pravega/segmentstore/server/host/handler/PravegaRequestProcessor.java
- segmentstore/server/host/src/test/java/io/pravega/segmentstore/server/host/handler/PravegaRequestProcessorTest.java
Added entries for expected and failing replies for WireCommands.GetTableSegmentInfo in SegmentHelper.
Cherry pick for PR #6316 to r0.10
Fixes #6332 
> Issue 6332: Cherry pick for PR #6316 to r0.10

- controller/src/main/java/io/pravega/controller/server/eventProcessor/requesthandlers/StreamRequestHandler.java
- controller/src/main/java/io/pravega/controller/server/eventProcessor/requesthandlers/UpdateReaderGroupTask.java
- controller/src/test/java/io/pravega/controller/task/Stream/StreamMetadataTasksTest.java
- controller/src/test/java/io/pravega/controller/task/Stream/ZkStreamMetadataTasksTest.java
The processing of UpdateReaderGroupEvent involves making one or more metadata updates on Segment Store using the PravegaTablesStoreHelper APIs. These APIs can throw WireCommandFailedException (all Retryable exceptions) or a ConnectionFailedException which is thrown when an unexpected response is returned by Segment Store.
The existing code for update event processing does not retry on ConnectionFailedException and so in a rare case when this response is returned, event processing would not be retried leaving the ReaderGroupUpdateRecord in "updating" state forever.
Fixes #6334
This PR makes the following changes to UpdateReaderGroupEvent processing:
1. Adds …
> Issue 6334: Defensive fix for update Reader Group remaining in stuck state

- common/src/main/java/io/pravega/common/concurrent/ExecutorServiceHelpers.java
- common/src/main/java/io/pravega/common/concurrent/ThreadPoolScheduledExecutorService.java
- common/src/test/java/io/pravega/common/concurrent/ExecutorServiceHelpersTests.java
- segmentstore/server/src/main/java/io/pravega/segmentstore/server/SegmentStoreMetrics.java
- segmentstore/server/src/test/java/io/pravega/segmentstore/server/SegmentStoreMetricsTests.java
`getSnapshot()` in `ExecutiveServiceHelpers` can now get values for executor type `ThreadPoolScheduledExecutorService`
Fixes #6335 
Segment store creates executors of type `ThreadPoolScheduledExecutorService` for dealing with thread pool data. So, added another check in `ExecutiveServiceHelpers` to make sure the following metrics are published:
- THREAD_POOL_QUEUE_SIZE
- THREAD_POOL_ACTIVE_THREADS
- STORAGE_THREAD_POOL_QUEUE_SIZE
- STORAGE_THREAD_POOL_ACTIVE_THREADS
Run `testTreadPoolMetrics()` in `SegmentStoreMetricsTest`
> Issue 6335: Segment storage and core threads stats always have zero values

- gradle.properties
As part of the release process, the version needs to be changed to X.Y.(Z+1)-SNAPSHOT on the release branch. 
Fixes #6325
Change pravegaVersion in gradle.properties to 0.10.1-SNAPSHOT
> Issue 6325: Change pravega version to 0.10.1-SNAPSHOT

- segmentstore/server/src/main/java/io/pravega/segmentstore/server/containers/ContainerEventProcessorImpl.java
- segmentstore/server/src/test/java/io/pravega/segmentstore/server/containers/StreamSegmentContainerTests.java
Make sure to always call `registerPinnedSegment` when loading/creating the internal segment for `ContainerEventProcessor`.
Fixes #6356.
This PR simplifies the supplier function in `ContainerEventProcessorImpl` and makes sure that the segment loaded/created by `ContainerEventProcessorImpl` is always a result of invoking `registerPinnedSegment`. Otherwise, there may be a chance that the internal segment is not registered as pinned and could be evicted from memory.
Added a test to validate the idempotent behavior of `ContainerEventProcessorImpl.getOrCreateInternalSegment`. All other test should pass.
> Issue 6356: ContainerEventProcessor internal segment could be evicted from memory

- bindings/src/main/java/io/pravega/storage/s3/S3SimpleStorageFactory.java
- bindings/src/main/java/io/pravega/storage/s3/S3StorageConfig.java
- bindings/src/test/java/io/pravega/storage/StorageFactoryTests.java
- bindings/src/test/java/io/pravega/storage/s3/S3SimpleStorageTests.java
- bindings/src/test/java/io/pravega/storage/s3/S3StorageConfigTest.java
- bindings/src/test/java/io/pravega/storage/s3/S3TestContext.java
Enable STS temp tokens with S3 Binding.
Fix #6391 
- While initializing SDK client use credential provider based on STS token
- Assumes predefined role and identity (provided in config) and that access key and secret are assumed to be passed as env variables 
- Minor unit test fixes to make it more generic.
System tests should pass with AWS
> Issue 6391: LTS - Enable STS temp tokens with S3 Binding.

- standalone/src/main/java/io/pravega/local/InProcPravegaCluster.java
Issue #6060: Use default published IP in standalone (#6397)
Signed-off-by: Derek Moore <derek.moore@dell.com>
Co-authored-by: Andrei Paduroiu <andreipaduroiu@users.noreply.github.com>
Cherry pick PR #6397 into r0.10
Fixes #6409
Removes a blanket override on Published IP config from standalone.
See #6397
> Issue 6409: Cherry pick PR 6397 into r0.10

- segmentstore/server/src/test/java/io/pravega/segmentstore/server/tables/AsyncTableEntryReaderTests.java
Changed the problematic assert statement in the test to better account for the behavior of the `AsyncTableEntryReader` when processing a `ReadResult`.
Fixes #5843 
- The error seems to be due to the completion of a background (async) task not being accounted for during one of the checks.
- Added to this is also the fact that that check did not account for `ReadResult`'s `maxReadAtOnce` being **non-zero**. During the check, the minimum of the `ReadResult.maxResultLength` and the `AsyncTableEntryReader.maxReadAtOnce` can become zero once the `AsyncTableEntryReader` finishes processing.
- This leads to an erroneous check where the ReadResult.maxReadAtOnce (non zero value) is compared to a potentially zero …
> Issue 5843: Sporadic failure in test AsyncTableEntryReaderTests.testReadKey

- segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/metadata/BaseMetadataStore.java
- segmentstore/storage/src/test/java/io/pravega/segmentstore/storage/chunklayer/ChunkStorageTests.java
- segmentstore/storage/src/test/java/io/pravega/segmentstore/storage/chunklayer/ChunkedSegmentStorageTests.java
- segmentstore/storage/src/test/java/io/pravega/segmentstore/storage/chunklayer/SimpleStorageTests.java
- segmentstore/storage/src/test/java/io/pravega/segmentstore/storage/metadata/ChunkMetadataStoreTests.java
Issue 5886: SLTS - Fix several flaky tests. Use multiple threads in tests to uncover more thread/timing related issues.
Fixes https://github.com/pravega/pravega/issues/5886 , https://github.com/pravega/pravega/issues/6024
Fix possible null exception.
Use multiple threads in tests to uncover more thread/timing related issues.
Fix issues where test were not waiting on futures
Tests must pass
> Issue 5886: SLTS - Fix several flaky tests. Use multiple threads in tests to uncover more thread/timing related issues.

- segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/chunklayer/ChunkStorageMetrics.java
- segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/chunklayer/ChunkedSegmentStorage.java
- segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/chunklayer/ChunkedSegmentStorageConfig.java
- segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/chunklayer/TruncateOperation.java
- segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/chunklayer/WriteOperation.java
- segmentstore/storage/src/test/java/io/pravega/segmentstore/storage/chunklayer/ChunkedSegmentStorageConfigTests.java
- segmentstore/storage/src/test/java/io/pravega/segmentstore/storage/chunklayer/ChunkedSegmentStorageMockTests.java
- segmentstore/storage/src/test/java/io/pravega/segmentstore/storage/chunklayer/ChunkedSegmentStorageTests.java
- shared/metrics/src/main/java/io/pravega/shared/MetricsNames.java
Efficient space reclamation after truncation by relocating first chunk when existing size of first chunk is more than certain limit and percentage wasted space is beyond set threshold. In such cases a smaller chunk is created with copy of valid portion of old chunk and then the old chunk is marked deleted.
This feature is relevant only to append mode.
Fixes #4912
Relocating first chunk when existing size of first chunk is more than certain limit and percentage wasted space is beyond threshold. In such cases we create a smaller chunk, copy valid portion of old chunk to it and then delete the old chunk.
This feature is relevant only to append mode.
**How to …
> Issue 4912 : LTS - Efficient space reclamation after truncation by relocating first chunk.

- segmentstore/storage/src/test/java/io/pravega/segmentstore/storage/chunklayer/GarbageCollectorTests.java
Issue 6040: Fix sporadic failure in GarbageCollectorTests.testIOException
Fixes #6040 
Add missing join on one of the test setup step. 
> Issue 6040: Fix sporadic failure in GarbageCollectorTests.testIOException

- controller/src/main/java/io/pravega/controller/eventProcessor/impl/EventProcessorCell.java
- controller/src/main/java/io/pravega/controller/eventProcessor/impl/EventProcessorGroupImpl.java
- controller/src/main/java/io/pravega/controller/store/checkpoint/CheckpointStore.java
- controller/src/main/java/io/pravega/controller/store/checkpoint/InMemoryCheckpointStore.java
- controller/src/main/java/io/pravega/controller/store/checkpoint/ZKCheckpointStore.java
- controller/src/test/java/io/pravega/controller/eventProcessor/impl/ZKCheckpointStoreTests.java
- controller/src/test/java/io/pravega/controller/eventprocessor/EventProcessorGroupTest.java
- test/integration/src/main/java/io/pravega/test/integration/demo/ControllerWrapper.java
This PR fixes the problem created by removing readers from the checkpoint store prior to declaring them offline. In rare cases when the Controller fails after removing a reader from the ZKCheckpointStore but before invoking reader.readerOffline , this issue manifests. It causes an old reader to stay in the ReaderGroup and continue to hold segments due to which they cannot be assigned to a reader created by the new Controller.
Fixes #6419
Changed method EventProcessorGroupImpl.notifyProcessFailure() to first seal the Reader Group then mark each reader Offline and remove the Reader from checkpoint store only after it has been successfully marked offline on …
> Issue 6419: Internal Reader Groups cannot read events on Controller restart

- build.gradle
- controller/src/main/java/io/pravega/controller/server/bucket/ZooKeeperBucketManager.java
- controller/src/main/java/io/pravega/controller/server/bucket/ZooKeeperBucketService.java
- controller/src/main/java/io/pravega/controller/store/ZKStoreHelper.java
- controller/src/main/java/io/pravega/controller/store/host/ZKHostStore.java
- controller/src/main/java/io/pravega/controller/store/stream/ZKGarbageCollector.java
- controller/src/main/java/io/pravega/controller/store/stream/ZookeeperBucketStore.java
- gradle.properties
- segmentstore/server/host/src/main/java/io/pravega/segmentstore/server/host/ZKSegmentContainerMonitor.java
- segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/bookkeeper/ZooKeeperServiceRunner.java
- shared/cluster/src/main/java/io/pravega/common/cluster/zkImpl/ClusterZKImpl.java
Upgraded Zookeeper (3.6.3) and Curator (4.3.0) dependencies.
Fixes #6129.
Upgrades Zookeeper (3.6.3) dependency to the same major version as Bookkeeper 4.14. Adapted a couple of calls in `ZooKeeperServiceRunner` to the new API.
Upgraded Curator (4.3.0) version as well.
All tests should be passing as before.
> Issue 6129: Bookkeeper upgrade causes API mismatch from its transitive dependencies in pravega-standalone

- controller/src/test/java/io/pravega/controller/eventprocessor/EventProcessorGroupTest.java
Test EventProcessorGroupTest.testFailingCellShutdown used to fail intermittently with a mockito exception. Fixed this by removing the `Mockito.doThrow()` as the exception did not help with testing additional code paths in EventProccessorGroup.shutdown()
Fixes #6437
Removed the doThrow() for reader.closeAt() since it was anyways not help with throwing an exception on `cell.awaitTerminated()`
All tests should pass and EventProcessorGroupTest.testFailingCellShutdown should consistently pass.
> Issue 6437: Fix flaky test EventProcessorGroupTest.testFailingCellShutdown

- gradle.properties
Change the pravegaVersion on branch `r0.10` from `0.10.2-SNAPSHOT` to `0.10.2`
Fixes #6448
> Issue 6448: pravega version change to 0.10.2 on r0.10

- cli/admin/README.md
- cli/admin/src/main/java/io/pravega/cli/admin/AdminCLIRunner.java
- cli/admin/src/main/java/io/pravega/cli/admin/AdminCommand.java
- cli/admin/src/main/java/io/pravega/cli/admin/controller/metadata/ControllerMetadataCommand.java
- cli/admin/src/main/java/io/pravega/cli/admin/controller/metadata/ControllerMetadataGetEntryCommand.java
- cli/admin/src/main/java/io/pravega/cli/admin/controller/metadata/ControllerMetadataListEntriesCommand.java
- cli/admin/src/main/java/io/pravega/cli/admin/controller/metadata/ControllerMetadataListKeysCommand.java
- cli/admin/src/main/java/io/pravega/cli/admin/controller/metadata/ControllerMetadataUpdateEntryCommand.java
- cli/admin/src/main/java/io/pravega/cli/admin/json/ControllerMetadataJsonSerializer.java
- cli/admin/src/main/java/io/pravega/cli/admin/segmentstore/ReadSegmentRangeCommand.java
- cli/admin/src/main/java/io/pravega/cli/admin/serializers/controller/ControllerMetadataSerializer.java
- cli/admin/src/main/java/io/pravega/cli/admin/utils/FileHelper.java
- cli/admin/src/test/java/io/pravega/cli/admin/controller/AbstractControllerMetadataCommandsTest.java
- cli/admin/src/test/java/io/pravega/cli/admin/json/ControllerMetadataJsonSerializerTest.java
- cli/admin/src/test/java/io/pravega/cli/admin/serializers/controller/ControllerMetadataSerializerTest.java
- cli/admin/src/test/java/io/pravega/cli/admin/utils/FileHelperTest.java
Implements the following command:
- `controller-metadata update <table-name> <key> <new-value-json-file> <segmentstore-endpoint>`
An update to an existing one:
- `controller-metadata get <table-name> <key> <[OPTIONAL] json-file> <segmentstore-endpoint>`
Fixes #6406
***Commands***
- For the `update` command.
- Added a new class for the `update` command.
- The command attempts a conditional update by querying the current version and then performing the update to the table using that.
- The new value to be updated in the table is provided as a JSON file of the record.
- The necessary segmentstore calls are made through the `AdminSegmentHelper`.
- For the `get` command.
- The `get` command is now updated to have …
> Issue 6406: Pravega CLI commands that allow updating values in Controller Metadata tables

- segmentstore/server/src/main/java/io/pravega/segmentstore/server/tables/ContainerKeyIndex.java
- segmentstore/server/src/main/java/io/pravega/segmentstore/server/tables/TableExtensionConfig.java
- segmentstore/server/src/test/java/io/pravega/segmentstore/server/tables/ContainerKeyIndexTests.java
- segmentstore/server/src/test/java/io/pravega/segmentstore/server/tables/TableExtensionConfigTests.java
Adds a new property for KVTables named "systemcritical.unindexed.bytes.max" that defines the amount of unindexed data we allow to system-critical KVTable Segments (defaulted to 256MB, 2x the amount of unindexed data we allow to regular segments).
Fixes #6451 .
In some cases, when LTS is faulty or unavailable for some time, a single Segment Container can accumulate around 1M Operations before the throttler starts inducing max delays. However, we have seen that, in practice, this can lead to an accumulation of a lot of updates on KVTable Segments, and specially on system-critical ones. If the system gets to this state, it may happen that the `StorageWriter` cannot start upon a container recovery, as during its …
> Issue 6451: ContainerKeyIndex may be throttling updates to system critical segments

- controller/src/main/java/io/pravega/controller/server/SegmentHelper.java
- controller/src/main/java/io/pravega/controller/server/eventProcessor/requesthandlers/CommitRequestHandler.java
- controller/src/main/java/io/pravega/controller/task/Stream/StreamMetadataTasks.java
- controller/src/test/java/io/pravega/controller/mocks/SegmentHelperMock.java
- controller/src/test/java/io/pravega/controller/server/SegmentHelperTest.java
- controller/src/test/java/io/pravega/controller/server/eventProcessor/RequestHandlersTest.java
- segmentstore/server/host/src/main/java/io/pravega/segmentstore/server/host/handler/PravegaRequestProcessor.java
- segmentstore/server/host/src/test/java/io/pravega/segmentstore/server/host/handler/PravegaRequestProcessorTest.java
- shared/protocol/src/main/java/io/pravega/shared/protocol/netty/DelegatingRequestProcessor.java
- shared/protocol/src/main/java/io/pravega/shared/protocol/netty/FailingReplyProcessor.java
- shared/protocol/src/main/java/io/pravega/shared/protocol/netty/FailingRequestProcessor.java
- shared/protocol/src/main/java/io/pravega/shared/protocol/netty/ReplyProcessor.java
- shared/protocol/src/main/java/io/pravega/shared/protocol/netty/RequestProcessor.java
- shared/protocol/src/main/java/io/pravega/shared/protocol/netty/WireCommandType.java
- shared/protocol/src/main/java/io/pravega/shared/protocol/netty/WireCommands.java
- shared/protocol/src/test/java/io/pravega/shared/protocol/netty/WireCommandsTest.java
- test/integration/src/main/java/io/pravega/test/integration/demo/EndToEndAutoScaleUpWithTxnTest.java
Changes to Controller for pipelining & batch merging of transactional segments to a target Stream segment during commit processing.
Fixes #6110
_Classes with major changes:_
1. CommitRequestHandler - changes to `commitTransaction` method to enable batch merge of transactional segments.
2. WireCommands - Added a new wire command `MergeSegmentsBatch` and its response command `SegmentsMergedBatch`.
3. PravegaPrequestProcessor - A new method `mergeSegmentsBatch` added that enables merging of a batch of segments **in-order** to a target segment.
4. SegmentHelper - A new `commitTransactions` method added for batch merging of transactional segments.
**How to …
> Issue 6110: Pipeline and batch merge transactional segments

- client/src/main/java/io/pravega/client/admin/ReaderGroupManager.java
- client/src/main/java/io/pravega/client/admin/StreamManager.java
- client/src/main/java/io/pravega/client/stream/StreamCut.java
- shared/cluster/src/main/java/io/pravega/common/cluster/Cluster.java
- test/system/src/main/java/io/pravega/test/system/framework/services/Service.java
Remove redundant keywords on method declaration in few interface definitions.
- client/src/main/java/io/pravega/client/admin/ReaderGroupManager.java
- client/src/main/java/io/pravega/client/admin/StreamManager.java
- client/src/main/java/io/pravega/client/stream/StreamCut.java
- shared/cluster/src/main/java/io/pravega/common/cluster/Cluster.java
- test/system/src/main/java/io/pravega/test/system/framework/services/Service.java
Fixes #6469
- Improve code style
- Remove redundant keywords on method declaration in few interface definitions.
- Improve code style
There is already test cases for the relevant part.
> Issue 6469: Remove redundant keywords on method declaration in few interface definitions.

- .github/workflows/gradle.yml
Explicitly set `actions/setup-java@v2` in the Git Actions configuration file. Also, explicitly set AdoptJDK 11 as the JDK to use.
Fixes #6534.
Explicitly sets to use AdoptJDK 11 in our builds, as some change in the underlying Git Actions environment could inadvertently switch it to Java 8, which causes compilation errors.
> Issue 6534: Git Actions seems to be picking wrong Java version

- cli/admin/src/test/java/io/pravega/cli/admin/AbstractAdminCommandTest.java
- gradle.properties
Signed-off-by: Bhupender-Y <Bhupender.Y@dell.com>
ClusterCommandTest getting failed because of mismatching of clusterName. To resolve it,  Update clusterName in config file before running admin cli testcases.
Fixes: #6537 
Update clusterName in config file before running admin cli testcases.
Run admin cli testcases.
> Issue 6537: Fix flakey test: ClusterCommandsTest.

- config/config.properties
- segmentstore/server/src/main/java/io/pravega/segmentstore/server/writer/WriterConfig.java
Signed-off-by: Aditi Jadhav Aditi.Jadhav@dell.com
The current default value of **writer.rollover.size.bytes.max** is max long and which exceeds the maximum supported size of a single file/object in most of storage systems out there. So setting the default value to **1 TB**.
Fixes issue #6078
Updates the default config value
> Issue 6078: LTS update config

- cli/admin/README.md
- cli/admin/src/main/java/io/pravega/cli/admin/AdminCommand.java
- cli/admin/src/main/java/io/pravega/cli/admin/controller/metadata/ControllerMetadataCommand.java
- cli/admin/src/main/java/io/pravega/cli/admin/controller/metadata/ControllerMetadataViewReaderInfoCommand.java
- cli/admin/src/main/java/io/pravega/cli/admin/utils/ZKHelper.java
- cli/admin/src/test/java/io/pravega/cli/admin/controller/AbstractControllerMetadataCommandsTest.java
Signed-off-by: Bhupender-Y <Bhupender.Y@dell.com>
Add a command `controller-metadata getReader <host-id> <reader-group> <reader-id>` in admin-cli to view metadata of reader of a particular controller instance.
Fixes #6311
Created  `controller-metadata getReader <host-id> <reader-group> <reader-id>`  command in admin cli to view reader metadata.
- Navigate to pravega-admin cli.
- Use `controller-metadata getReader <host-id> <reader-group> <reader-id>`. It should print reader metadata.
> Issue 6311 : Admin CLI Commands to view Reader Information in zookeeper for a specific Controller host

- segmentstore/server/src/main/java/io/pravega/segmentstore/server/tables/ContainerKeyIndex.java
- segmentstore/server/src/test/java/io/pravega/segmentstore/server/containers/StreamSegmentContainerTests.java
- segmentstore/server/src/test/java/io/pravega/segmentstore/server/tables/ContainerKeyIndexTests.java
- segmentstore/server/src/test/java/io/pravega/segmentstore/server/tables/EntrySerializerTests.java
Ensures that `TableEntry` versions are considered when populating the tail-cache of a hash-based Table Segment during recovery. When triggering tail-caching, starts scanning Table Entries from the highest value between start segment offset and last compaction offset to make sure that we are not missing last value of any key (still, the tail-cache is only populated with elements beyond `lastIndexedOffset` as before).
Fixes https://github.com/pravega/pravega/issues/6539.
When a hash-based Table Segment is used for the first time, it checks whether there is data stored in tier 1 but not yet indexed (which depends on the progress of moving data to LTS). If there is a delta, the Table Segment starts a blocking …
> Issue 6539: Table Segment tail-caching may populate tail cache with stale data

- segmentstore/server/src/main/java/io/pravega/segmentstore/server/tables/ContainerKeyIndex.java
- segmentstore/server/src/test/java/io/pravega/segmentstore/server/containers/StreamSegmentContainerTests.java
- segmentstore/server/src/test/java/io/pravega/segmentstore/server/tables/ContainerKeyIndexTests.java
- segmentstore/server/src/test/java/io/pravega/segmentstore/server/tables/EntrySerializerTests.java
Cherry-pick #6538 to r0.10
Fixes #6557.
More details here #6538
> Ensures that TableEntry versions are considered when populating the tail-cache of a hash-based Table Segment during recovery. When triggering tail-caching, starts scanning Table Entries from the highest value between start segment offset and last compaction offset to make sure that we are not missing last value of any key (still, the tail-cache is only populated with elements beyond lastIndexedOffset as before).
> Issue 6557: Cherry-pick 6538 to r0.10

- client/src/main/java/io/pravega/client/state/SynchronizerConfig.java
- client/src/main/java/io/pravega/client/stream/EventWriterConfig.java
- client/src/test/java/io/pravega/client/state/SynchronizerConfigTest.java
- client/src/test/java/io/pravega/client/stream/EventWriterConfigTest.java
Signed-off-by: SrishT <Srishti.Thakkar@emc.com>
Creating a custom Serializer instead of relying on Java Serializion for the SynchronizerConfig and the EventWriterConfig.
Fixes #4097 
Adds a SynchronizerConfigSerializer and an EventWriterConfigSerializer for serializing the SynchronizerConfig and the EventWriterConfig objects respectively.
> Issue 4097: Serialization Framework for Synchronizer Config

- segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/chunklayer/ChunkedSegmentStorage.java
- segmentstore/storage/src/test/java/io/pravega/segmentstore/storage/chunklayer/SystemJournalTests.java
Reduce noise in SystemJournalTests that generates java.util.concurrent.CompletionException: java.lang.IllegalStateException: taskQueue must not be null.
Fixes #6565 
Initialize garbage collector in tests.
No more noise of java.lang.IllegalStateException: taskQueue must not be null
> Issue 6565 : LTS - Reduce noise in SystemJournalTests that generates java.lang.IllegalStateException: taskQueue must not be null

- segmentstore/server/src/main/java/io/pravega/segmentstore/server/SegmentStoreMetrics.java
- segmentstore/server/src/main/java/io/pravega/segmentstore/server/logs/DurableLog.java
- segmentstore/server/src/main/java/io/pravega/segmentstore/server/logs/OperationProcessor.java
- segmentstore/server/src/test/java/io/pravega/segmentstore/server/SegmentStoreMetricsTests.java
Signed-off-by: Abhin Balur <Abhin_Balur@dell.com>
Fixes the OpeartionLog size metric in Grafana dashboard for SegmentStore.
Fixes #6563 
Fixes the OpeartionLog size metric in Grafana dashboard for SegmentStore. This metric was originally a 
counter which was leading to wrong operation log sizes being reported when in actuality it should have been a guage.
Bring up Grafana dashboards for SegmentStore. View the operationlog size graph while writing data to Pravega.
> Issue 6563: Fix operationlogsize metric

- bindings/src/test/java/io/pravega/storage/extendeds3/ExtendedS3StorageTest.java
- cli/admin/src/main/java/io/pravega/cli/admin/dataRecovery/StorageListSegmentsCommand.java
- segmentstore/server/src/main/java/io/pravega/segmentstore/server/containers/ContainerRecoveryUtils.java
- segmentstore/server/src/test/java/io/pravega/segmentstore/server/TestStorage.java
- segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/AsyncStorageWrapper.java
- segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/Storage.java
- segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/chunklayer/ChunkedSegmentStorage.java
- segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/metadata/BaseMetadataStore.java
- segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/metadata/ChunkMetadataStore.java
- segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/metadata/TableBasedMetadataStore.java
- segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/mocks/InMemoryMetadataStore.java
- segmentstore/storage/src/test/java/io/pravega/segmentstore/storage/StorageTestBase.java
- segmentstore/storage/src/test/java/io/pravega/segmentstore/storage/chunklayer/ChunkedRollingStorageTests.java
- segmentstore/storage/src/test/java/io/pravega/segmentstore/storage/chunklayer/ChunkedSegmentStorageMockTests.java
- segmentstore/storage/src/test/java/io/pravega/segmentstore/storage/metadata/ChunkMetadataStoreTests.java
- segmentstore/storage/src/test/java/io/pravega/segmentstore/storage/metadata/TableBasedMetadataStoreMockTests.java
- segmentstore/storage/src/test/java/io/pravega/segmentstore/storage/mocks/InMemoryTableStore.java
Issue 6526: LTS - Implement ChunkedSegmentStorage::listSegments
Fixes #6526 
- Make `Storage::listSegments()` return `CompletableFuture`
- Add `getAllEntries() `and `getAllKeys()` methods to `ChunkMetadataStoare`
- Implement `ChunkedSegmentStorage::listSegments`
- Update in memory table mock used in chunked segment storage tests to implement `getAllEntries() `and `getAllKeys()`
> Issue 6526: LTS - Implement ChunkedSegmentStorage::listSegments

- gradle/java.gradle
- segmentstore/server/src/main/java/io/pravega/segmentstore/server/ContainerEventProcessor.java
- segmentstore/server/src/main/java/io/pravega/segmentstore/server/SegmentMetadata.java
- segmentstore/server/src/main/java/io/pravega/segmentstore/server/containers/ContainerConfig.java
- segmentstore/server/src/main/java/io/pravega/segmentstore/server/containers/ContainerEventProcessorImpl.java
- segmentstore/server/src/main/java/io/pravega/segmentstore/server/containers/StorageEventProcessor.java
- segmentstore/server/src/main/java/io/pravega/segmentstore/server/containers/StreamSegmentContainerMetadata.java
- segmentstore/server/src/main/java/io/pravega/segmentstore/server/containers/StreamSegmentMetadata.java
- segmentstore/server/src/main/java/io/pravega/segmentstore/server/logs/ContainerMetadataUpdateTransaction.java
- segmentstore/server/src/test/java/io/pravega/segmentstore/server/containers/ContainerEventProcessorTests.java
- segmentstore/server/src/test/java/io/pravega/segmentstore/server/containers/StreamSegmentContainerTests.java
Adds the possibility to configure the truncation data side to `ContainerEventProcessor`. Set to 128KB the default truncation size for SLTS GC. Also, refresh the internal `DirectSegmentAccess` on each processing iteration of `ContainerEventProcessor`. Increased `ContainerEventProcessor` timeout from 100ms to 1 second, to reduce log noise when there are no items to process.
Fixes #6523.
Fixes #6509.
This PR adds the ability to `ContainerEventProcessor` to configure length at which processed data is truncated. This can help to induce too frequent truncation in the internal Segment of the `ContainerEventProcessor`, which leads the `StorageWriter` to not  be able to batch operations on that Segment. This PR …
> Issue 6523: ContainerEventProcessor internal segment continuous truncations prevent StorageWriter batching

- test/system/src/main/java/io/pravega/test/system/framework/services/kubernetes/AbstractService.java
- test/system/src/test/resources/pravega.properties
- test/system/src/test/resources/pravega_withAuth.properties
- test/system/src/test/resources/pravega_withTLS.properties
Signed-off-by: Abhin Balur <Abhin_Balur@dell.com>
This change corrrects the memory configuration for system tests, without which system tests are currently failing. 
Fixes #6580
The code puts in the right values for memory related configuration of SegmentStore, without which we see errors as described in #6580.
System tests should pass
> Issue 6580: Fix system test memory config on r0.10

- segmentstore/server/src/test/java/io/pravega/segmentstore/server/SegmentStoreMetricsTests.java
Fix operationlogsize metric based test.
Fixes #6593 
There was an issue with how the gauge is retrieved in the test. Basically in the test while reporting the gauge we report the OperationLog Size metric/gauge  for a specific container. However while retrieving the gauge we query the MetricRegistryUtils which return the operationlogsize for all containers. There is a precondition check where we expect only one gauge to be retrieved(since we are querying for only one container). However this container id wasnt passed resulting in gauges for all containers to be retrieved thereby failing the Precondition Check. 
The fix passes the right container id while retrieving the gauge.
Unit tests …
> Issue 6593: Fix operationlogsize metric based test

- bindings/src/main/java/io/pravega/storage/filesystem/FileSystemChunkStorage.java
- bindings/src/main/java/io/pravega/storage/filesystem/FileSystemStorageConfig.java
- bindings/src/main/java/io/pravega/storage/filesystem/FileSystemWrapper.java
- bindings/src/test/java/io/pravega/storage/filesystem/FileSystemChunkStorageMockTest.java
- bindings/src/test/java/io/pravega/storage/filesystem/FileSystemWrapperTests.java
The aim is to make expiration of cache configurable for the  recently added FileChannel cache in FileSystemWrapper.
Adding a new config value for the FileChannel cache expiration.
Instead of having no expiration or hardcoding the time out which is not really preferred, the code:
- Adds two new config values to FileSystemStorageConfig "write.channel.cache.expiration.sec" and "read.channel.cache.expiration.sec" each of these with 600 as default and passing it to the FileSystemWrapper constructor
- And then use them during CacheBuilder.newBuilder().maximumSize(...).expireAfterAccess(...) --> using Duration value passed to constructor.
Changes can be verified by running the testcases.
> Issue-6570: LTS - Make FileChannel cache expiration configurable

- client/src/main/java/io/pravega/client/byteStream/impl/ByteStreamClientImpl.java
- client/src/main/java/io/pravega/client/segment/impl/SegmentInputStreamFactoryImpl.java
Make fetching tokens on segment reader creation async
Fixes #6620 
Makes the token fetching upon creation of a new segment reader asynchronous.
> Issue 6620: Make fetching tokens on segment reader creation async

- segmentstore/storage/src/test/java/io/pravega/segmentstore/storage/chunklayer/ChunkedSegmentStorageMockTests.java
LTS - Remove flakiness from ChunkedSegmentStorageMockTest::testReport
LTS - Remove flakiness from ChunkedSegmentStorageMockTest::testReport
Fixes #6625 
This test asserts that metrics are updated - which is an optional check. However the update to guage is async and hard to control often resulting in test failure.
Remove flakiness from io.pravega.segmentstore.storage.chunklayer.ChunkedSegmentStorageMockTests::testReport
Test should pass
> Issue 6625: LTS - Remove flakiness from ChunkedSegmentStorageMockTest::testReport

- controller/src/main/java/io/pravega/controller/server/ControllerService.java
- controller/src/test/java/io/pravega/controller/server/ControllerServiceWithStreamTest.java
- documentation/src/docs/beginner_dev_guide.md
Signed-off-by: Shashwat Sharma <shashwat_sharma@dell.com>
Currently if the server is on the latest version and client is of any previous version older than Pravega 0.10.0, with the updated validation for `createStream()`, it fails as the call to create internal stream goes to `createStream()` method of `ControllerService.java` while creating a reader group. This breaks backward compatibility. So, in order to keep the compatibility intact, update the validation for the stream name is `createStream()` method.
Fixes #6629 
Use Pravega 0.9.0 or any earlier version as client and use this version of master to run Pravega in standalone mode and create a reader group and the create should be successful.
> Issue 6629: Reader creation failed in Standalone mode

- segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/chunklayer/UtilsWrapper.java
- segmentstore/storage/src/test/java/io/pravega/segmentstore/storage/chunklayer/UtilsWrapperTests.java
Adding a new method checkChunkSegmentStorageSanity to the UtlilsWrapper class that performs sanity operations on chunk like create chunk, write to the chunk, check if the chunk exists, read back contents to the chunk and delete the chunk. 
Implements the UtilsWrapper functionality for #6657 
1 . The code adds following method to UtlisWrapper class.
```
public CompletableFuture<Void> checkChunkSegmentStorageSanity() {
// Create globally unique name for chunk
// Create + Write a chunk 
// Check chunk exists 
// Read back chunk contents
// Delete chunk
// Check chunk doesn't exist
}
```
2. Further, it tests the chunk sanity in the UtilsWrapperTest for chunk creation, correctly retrieving the chunk info, …
> Issue 6657 : Admin CLI : Run sanity test against LTS

- segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/chunklayer/TruncateOperation.java
- segmentstore/storage/src/test/java/io/pravega/segmentstore/storage/chunklayer/ChunkedSegmentStorageTests.java
- segmentstore/storage/src/test/java/io/pravega/segmentstore/storage/mocks/InMemorySimpleStorageTests.java
Fix integer overflow in TruncateOperation.
Fixes #6688 
Fix integer overflow in TruncateOperation.
Unit tests should pass.
> Issue 6688: LTS - Fix integer overflow in TruncateOperation.

- segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/chunklayer/ChunkedSegmentStorageConfig.java
- segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/chunklayer/TruncateOperation.java
- segmentstore/storage/src/test/java/io/pravega/segmentstore/storage/chunklayer/ChunkedSegmentStorageConfigTests.java
- segmentstore/storage/src/test/java/io/pravega/segmentstore/storage/chunklayer/ChunkedSegmentStorageTests.java
Issue 6699: LTS - Prevent relocation of huge data with truncate when cluster is configured with very large max chunk size.
Fixes #6699 
Adds config value for maximum size of chunk after which it is not eligible for relocation.
> Issue 6699: LTS - Prevent relocation of huge data with truncate when cluster is configured with very large max chunk size.

- segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/chunklayer/ChunkedSegmentStorageConfig.java
- segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/chunklayer/TruncateOperation.java
- segmentstore/storage/src/test/java/io/pravega/segmentstore/storage/chunklayer/ChunkedSegmentStorageConfigTests.java
- segmentstore/storage/src/test/java/io/pravega/segmentstore/storage/chunklayer/ChunkedSegmentStorageTests.java
Cherry-pick #6700 
Fixes #6702 
See #6700 
Issue 6699: LTS - Prevent relocation of huge data with truncate when cluster is configured with very large max chunk size.
> Issue 6702: cherry pick #6700 to r0.11

- gradle/wrapper/gradle-wrapper.properties
Upgrades Gradle wrapper to version 6.8.3.
Fixes #6710.
Upgrades gradle to the last stable 6.x version to fix a problem that hits when building Pravega via IDE.
With this change I can work with Pravega project in IDE.
> Issue 6711: Gradle fails when building Pravega locally in the IDE

- test/integration/src/test/java/io/pravega/test/integration/WatermarkingTest.java
- test/testcommon/src/main/java/io/pravega/test/common/AssertExtensions.java
- test/testcommon/src/main/java/io/pravega/test/common/TestUtils.java
Signed-off-by: SrishT <Srishti.Thakkar@emc.com>
The integration test WatermarkingTest.progressingWatermarkWithTimestampAggregationTimeout has been failing intermittently because of its dependency on the timeout values, which is being fixed here.
Fixes #6713 
Tries to overcome the dependence on a random timeout value for the generation of the subsequent watermark by making use of assertEventuallyEquals instead.
> Issue 6713: Fixing flakiness in progressingWatermarkWithTimestampAggregationTimeout Test

- controller/src/main/java/io/pravega/controller/store/client/StoreClientFactory.java
- controller/src/test/java/io/pravega/controller/store/client/StoreClientFactoryTest.java
Signed-off-by: Shashwat Sharma <shashwat_sharma@dell.com>
Updated the code to return a new instance of Curator client in case of zk restarts.
Fixes #6745 
Currently the controller doesn't create a new instance of the curator client if the client is not null and it uses the same client to re-establish the connection which is not correct as the system may assign a new IP to the hostname of the new ZooKeeper instance. We see the below log line and the controller doesn't get re-connected
`Input argument for new ZooKeeper client (ip:port, ip:port, ip:port, 10000, false) changed with respect to existing client (cluster-zookeeper-client:port, 10000, false)`
Jenkins builds are passing …
> Issue 6745: Handle Controller connectivity with ZK

- gradle.properties
As `r0.12` has been created, upgrade Pravega version in `gradle.properties` to `0.13.0-SNAPSHOT`.
Fixes #6754.
Upgrade Pravega version in `gradle.properties`.
> Issue 6754: Change version on master branch to 0.13

- cli/user/src/main/java/io/pravega/cli/user/UserCLIRunner.java
- cli/user/src/main/java/io/pravega/cli/user/config/InteractiveConfig.java
- cli/user/src/test/java/io/pravega/cli/user/UserCLIRunnerTest.java
- cli/user/src/test/java/io/pravega/cli/user/config/InteractiveConfigCommandTest.java
The Pravega CLI currently has a hard-coded log level of `ERROR`.  This makes it difficult to debug certain connection issues as useful logging is suppressed.  This PR introduces a new configuration value, `log-level`, allowing the user to set the log level interactively before issuing a command.
Fixes #6810 
- Adds `log-level` to the `InteractiveConfig` with the default set to `ERROR` to make it backwards compatible.
- `UserCLIRunner` applies the log level to the environment before processing an interactive command
- Updates `InteractiveConfigCommandTest` to validate the log level config.
- Updates the interactive loop to be more testable but passing in the InputStream (rather than assuming `System.in`) and …
> Issue 6810 user cli log level config

- client/src/main/java/io/pravega/client/admin/StreamManager.java
- client/src/main/java/io/pravega/client/admin/impl/StreamManagerImpl.java
- client/src/test/java/io/pravega/client/admin/impl/StreamManagerImplTest.java
- client/src/test/java/io/pravega/client/stream/mock/MockStreamManager.java
- test/integration/src/test/java/io/pravega/test/integration/BatchClientTest.java
- test/integration/src/test/java/io/pravega/test/integration/StreamRecreationTest.java
- test/system/src/test/java/io/pravega/test/system/BatchClientSimpleTest.java
- `getStreamInfo()` sounds like a api call but it's a network call.
- As the name is ambiguous and API is still in beta so renaming it to `fetchStreamInfo()` and changed the return type to Completable Future.
Fixes #6748 
- Renamed `getStreamInfo()` to `fetchStreamInfo()` and returns a Completable Future.
- All tests should pass.
> Issue 6748: Renaming getStreaminfo() and changing return type

- cli/user/src/main/java/io/pravega/cli/user/Command.java
- cli/user/src/main/java/io/pravega/cli/user/UserCLIRunner.java
- cli/user/src/main/java/io/pravega/cli/user/config/InteractiveConfig.java
- cli/user/src/test/java/io/pravega/cli/user/TestUtils.java
- cli/user/src/test/java/io/pravega/cli/user/UserCLIRunnerTest.java
- cli/user/src/test/java/io/pravega/cli/user/config/ConfigCommandTest.java
- cli/user/src/test/java/io/pravega/cli/user/config/InteractiveConfigCommandTest.java
Added a conditional check to read the environment values and populate the same for controller-uri for tls
Fixes: [#6817](https://github.com/pravega/pravega/issues/6817)
This PR adds the default values for the tls based configurations.
On a tls environment, connect to pravega-cli and look for controller-uri and tls-enabled fields, it should display the default values as per the environment
> Issue 6817 : Pravega-cli should pick up the default environment values from tls based configuration

- gradle.properties
Gradle fails to build in git-less release source bundles because Mkdocs plugin always assumes a valid git working tree.
Mkdocs plugin can be enabled on the command line with `./gradlew -PenableMkdocs=true mkdocsBuild` or `./gradlew -PenableMkdocs=true mkdocsServe`.
Fixes #6864
Sets gradle property `enableMkdocs` to `false`.
Make a new release tarball that lacks git and run a gradle task. For example: `git archive --format=zip v0.12.0-rc1 > /tmp/pravega.zip`, unzip and run a gradle task such as `./gradlew build`.
> Issue 6864: Disable Mkdocs gradle plugin by default

- controller/src/test/java/io/pravega/controller/task/Stream/StreamMetadataTasksTest.java
Fixed assertions in readerGroupsTest.
Fixes #6874.
The test was asserting that 3 metrics were present (`CONTROLLER_EVENT_PROCESSOR_CREATE_READER_GROUP_LATENCY`, `CONTROLLER_EVENT_PROCESSOR_DELETE_READER_GROUP_LATENCY`, and `CONTROLLER_EVENT_PROCESSOR_UPDATE_READER_GROUP_LATENCY`), and the last latency value recorded for them was strictly higher than 0ms. While this was normally the case for latency related to delete and create Reader Groups, for Reader Group update operations latency could be lower than 1ms (i.e., 0ms). This was making the assertion to fail, despite taking 0ms for some operation is a perfectly valid case. Note that if the latency was not reported, `MetricsTestUtil.getTimerMillis()` would …
> Issue 6874: Flaky test SecureStreamMetadataTasksTest.readerGroupsTest is failing

- gradle.properties
Set Pravega version to 0.12.1-SNAPSHOT in branch r0.12.
Fixes #6894.
Set Pravega version to 0.12.1-SNAPSHOT in branch r0.12.
> Issue 6894: Bump r0.12 to 0.12.1-SNAPSHOT

- client/src/main/java/io/pravega/client/stream/ScalingPolicy.java
- client/src/test/java/io/pravega/client/stream/ScalingPolicyTest.java
Fix the wrong ScaleType value in the `ScalingPolicy.ScaleType`
Fixes #6891
```java
/**
* Scale based on the rate in bytes specified in {@link ScalingPolicy#targetRate}.
*/
BY_RATE_IN_KBYTES_PER_SEC(io.pravega.shared.segment.ScaleType.NoScaling.getValue()),
/**
* Scale based on the rate in events specified in {@link ScalingPolicy#targetRate}.
*/
BY_RATE_IN_EVENTS_PER_SEC(io.pravega.shared.segment.ScaleType.NoScaling.getValue());
```
the enum value error, should `Throughput` 、`EventRate`.
Build must pass with the new added testcase.
> Issue 6891: Fix the wrong ScaleType value

- segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/chunklayer/ChunkedSegmentStorage.java
- segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/chunklayer/GarbageCollector.java
- segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/chunklayer/SystemJournal.java
- segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/metadata/SegmentMetadata.java
- segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/metadata/StatusFlags.java
- segmentstore/storage/src/test/java/io/pravega/segmentstore/storage/chunklayer/ChunkedSegmentStorageTests.java
- segmentstore/storage/src/test/java/io/pravega/segmentstore/storage/chunklayer/SystemJournalTests.java
- segmentstore/storage/src/test/java/io/pravega/segmentstore/storage/chunklayer/TestUtils.java
Issue 6811: LTS - Disable lazy commit for all segments. Support rollback by porting serializers and flags to 0.12 branch.
Fix #6811
Support rollback by porting serializers and flags to 0.12 branch.
Append records are skipped over.
explicitly set `isAtomic `to false to avoid unexpected state transitions with this version.
All tests should pass. Upgrade and rollback should pass.
> Issue 6811: LTS - Disable lazy commit. Support rollback by porting serializers and flags to 0.12 branch.

- build.gradle
- gradle.properties
Cherry-pick PR #6923 into branch r0.12.
Fixes #6925.
See #6923.
(not added upgrades to GCP libraries, as Pravega 0.12 does not have GCP storage binding).
See #6923.
> Issue 6925: Cherry-pick PR 6923 into branch r0.12

- gradle.properties
As `r0.13` has been created, upgrade Pravega version in `gradle.properties` to `0.14.0-SNAPSHOT`.
Fixes #6940.
Upgrade Pravega version in `gradle.properties`.
> Issue 6940: Change version on master branch to 0.14

- client/src/main/java/io/pravega/client/stream/impl/EventStreamWriterImpl.java
- client/src/main/java/io/pravega/client/stream/impl/SegmentSelector.java
- client/src/test/java/io/pravega/client/stream/impl/EventStreamWriterTest.java
Failing outstanding writes when stream is sealed. 
To fix [#1684](https://github.com/pravega/pravega/issues/1684)
The code Checks if Stream is sealed then it will fail the outstanding writes and throws IllegalStateException("Resend of Events cannot proceed since the stream is sealed").
Otherwise it will resend and retry for write the event to the stream. 
The stream status is being set in refreshSegmentEventWritersUponSealed method in SegmentSelecter class. what this method is doing its checking if getSuccessor for any stream is empty then it will set sealed flag to true and that flag we are checking inside resend method through the isStreamSealed() in EventStreamWriterImpl.
And also added a Unit test for …
> Issue 1684: Fail outstanding writes when stream is sealed. 

- common/src/main/java/io/pravega/common/util/AbstractDrainingQueue.java
- common/src/test/java/io/pravega/common/util/PriorityBlockingDrainingQueueTests.java
- segmentstore/server/src/main/java/io/pravega/segmentstore/server/logs/OperationProcessor.java
- segmentstore/server/src/test/java/io/pravega/segmentstore/server/logs/OperationProcessorTests.java
Fixed a bug in which OperationProcessor could be left stuck not able to shut down if the operationQueue is closed while a maximum throttling delay is being induced.
Fixes #6969.
See #6943.
See #6943.
> Issue 6969: Cherry-pick PR 6943 to r0.13

- build.gradle
- gradle.properties
Fixed the security related CVEs which were reported for 0.13.
Fixes https://github.com/pravega/pravega/issues/6975.
See https://github.com/pravega/pravega/issues/6975.
See https://github.com/pravega/pravega/issues/6975.
> Issue 6978 : Cherry-pick PR 6976 to r0.13

- client/src/main/java/io/pravega/client/stream/impl/CheckpointState.java
- client/src/main/java/io/pravega/client/stream/impl/EventStreamReaderImpl.java
- client/src/main/java/io/pravega/client/stream/impl/ReaderGroupImpl.java
- client/src/test/java/io/pravega/client/stream/impl/CheckpointStateTest.java
- client/src/test/java/io/pravega/client/stream/impl/ReaderGroupImplTest.java
Signed-off-by: Shwetha N <shwetha.n1@dell.com>
Maximum outstanding checkpoint warning message gives info only about blocked checkpoints not on the readers who are actually blocking it.
In one of use case, we could see that though all readers successfully acknowledge the checkpoints, while triggering new initiate checkpoint call it still complains with checkpoints being blocked but here, we have lack of info on the readers who is actually blocking these checkpoints
#6977 
Added logs which gives more clarity on readers who are blocking the checkpoints.
> Issue 2166: Improve logging for outstanding checkpoint

- client/src/main/java/io/pravega/client/stream/impl/CheckpointState.java
- client/src/main/java/io/pravega/client/stream/impl/EventStreamReaderImpl.java
- client/src/main/java/io/pravega/client/stream/impl/ReaderGroupImpl.java
- client/src/test/java/io/pravega/client/stream/impl/CheckpointStateTest.java
- client/src/test/java/io/pravega/client/stream/impl/ReaderGroupImplTest.java
see #6974 
Fixes #6993
see #6974 
> Issue 6993: Cherry-pick PR #6974 to master

- segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/chunklayer/ChunkedSegmentStorageConfig.java
Need to increase the default value of storage.readindex.block.size to 1 GB from 1 MB. 
Fixes #7002 
The code sets the default value of storage.readindex.block.size which is 1 MB to 1 GB. The purpose of the change is that the previous default value was too small and did lead to too many index entries which is unnecessary, wasteful and also led to OOM in certain conditions.
All the tests should pass.
> LTS - Set default value of storage.readindex.block.size to 1 GB.

- client/src/main/java/io/pravega/client/state/RevisionedStreamClient.java
- client/src/main/java/io/pravega/client/state/impl/RevisionedStreamClientImpl.java
- client/src/test/java/io/pravega/client/state/impl/RevisionedStreamClientTest.java
- client/src/test/java/io/pravega/client/state/impl/SynchronizerTest.java
- controller/src/test/java/io/pravega/controller/server/bucket/WatermarkWorkflowTest.java
This PR introduces a new method that allows reading data between two specific revisions - a start revision and an end revision.
Fixes #1886
Reads all data from  a given start revision to the end revision and also adds unit test for the newly added method.
All test should pass
**Note :-**  This PR is related to this draft PR https://github.com/pravega/pravega/pull/6942. for more context please have a look to this.
> Issue 1886: Introduces readRange method in RevisionStreamClient

- test/system/src/main/java/io/pravega/test/system/framework/services/kubernetes/K8SequentialExecutor.java
This PR adds a fix for Unsupported Operation exception seen in System Test Framework when TLS is enabled.
Fixes #7009 
Instead of directly adding Volume and VolumeMount to the ImmutableList in PodSpec, we are first creating a List of Volumes `List<V1Volume> volumes` and List of VolumeMounts `List<V1VolumeMounts> volumeMounts` and then using `.setVolume(volumes)` and `.setVolumeMount(volumeMounts)` methods of podSpec.
- QE tests didn't show any Unsupported Operation Exception after adding this piece of code.
- Currently dev side System tests (STF) doesn't have support for TLS. 
- Verified that Volume and VolumeMounts are getting created in the test pod.
```
Mounts:
/data from …
```
> Issue 7009: Fix for Unsupported Operation exception in STF

- client/src/main/java/io/pravega/client/connection/impl/FlowHandler.java
In one of the issues raised against pravega it was seen that some 2400+ virtual connections were getting created and destroyed in a duration of 10 seconds.
And even after having too many readers there were failures observed in system. And could see OOM issues. we went through the call flow in Flowhandler and traced that assigning the channel object to null after closing will help reclaim all the unwanted memory and will also drastically reducing the memory. 
closes https://github.com/pravega/pravega/issues/7016
test should run fine
> Issue 7016: Reclaiming memory of channel object in FlowHandler

- common/src/main/java/io/pravega/common/concurrent/ThreadPoolScheduledExecutorService.java
- common/src/test/java/io/pravega/common/concurrent/ThreadPoolScheduledExecutorServiceTest.java
keep the current scheduled task reference in ScheduleLoop, so that it can be canceled and removed from the delayed queue in cancellation before the first task being fired. In some cases, a lot of FixedRateTasks are created in shot time (2000+ within 10s), if the first tasks are accumulated in the delayed queue, it could cause memory pressue and lead to OOM before they are released after the initial delay (e.g. 20s)
Fixes https://github.com/pravega/pravega/issues/7023
Keep a reference of the first task scheduled and remove it if cancel is called on the ScheduleLoop
Restart pravega pods until it triggers alot of client connection drops, and do heap dump to see if many keepAliveTask …
> Issue 7023 remove canceled task from queue

- build.gradle
Handling Build time warnings which were caused due to the usage of deprecated properties and configurations in build.gradle.
Fixes #7017  
There were 13 warnings from build.gradle and were handled by
Changing Runtime configuration to RuntimeOnly.
Changing AbstractArchiveTask.archiveName property to archieveFileName.
Changing AbstractArchiveTask.destinationDir property to destinationDirectory.
Changing AbstractArchiveTask.extension property to archieveExtension.
Changing Distribution.baseName property to distributionBaseName.
Changing runtime configuration to runtimeClasspath.
There should be no build time warnings from build.gradle
> Issue 7017: Build time warnings present in build.gradle 

- test/system/src/test/java/io/pravega/test/system/ConsumptionBasedRetentionWithMultipleReaderGroupsTest.java
- Testing Consumption Based Retention with Multiple Controllers
- Testing Consumption Based Retention with Controller and Segment Store Failover
closes #5555
closes #5556
- The test case "multipleControllerFailoverAndRestartCBRTest" verifies the consumption based retention with multiple instances of controller. Three instances of controller are deployed. Stream S is created with fixed segment =1, min = 90 and max = 180. One reader group(subscribers) with AUTOMATIC_RELEASE_AT_LAST_CHECKPOINT is created. Stream 'S' is filled with 3 events. Subscriber 1 initiates checkpoint at 0/30(SLB) and stream is again filled with 2 more events. Retention Set has one stream cut at 0/150. Subscriber Lower Bound (SLB) is 0/30 …
> Issue 5555: Consumption based retention with multiple controllers and controller and segment store failover

- segmentstore/server/src/main/java/io/pravega/segmentstore/server/reading/StreamSegmentReadIndex.java
The changes are to put a synchronization block in the `StreamSegmentReadIndex` for `cacheStorage`. This needs to be done for every update, write, append operations.
Fixes #7042 
Fixes #6785
Inside of `StreamSegmentReadIndex` it is attempting to do some sophisticated synchronization which is critical to get right to prevent this sort of error. In particular the `cacheStorage` member is accessed both inside and outside of a lock. In order to do this, it is using some double checked operations so as to not always hold a lock when accessing the data-structure. In particular when `addToCacheAndIndex` is invoked there could be a concurrent `insertEntriesToCacheAndIndex` and the append which is calling it. There …
> Issue 7042: Fix DataCorruptionException due to race condition in Cache

- test/system/src/test/java/io/pravega/test/system/ConsumptionBasedRetentionWithMultipleReaderGroupsTest.java
Consumption Based Retention with Stream Scaling system test
closes #5557 
The test "streamScalingCBRTest" verifies the consumption based retention with stream scaling. Stream S is created with initially 1 segment and with size retention policy defined as min= 90 and max =180. One subscriber with MANUAL_RELEASE_AT_USER_STREAMCUT is created. Stream S is filled with 2 events of same size (30) and the subscriber reads the 2 events. After that stream scale api is called to scale up the stream with two segments. And then 7 more events are filled to the stream. Subscriber reads 3 more events from the stream and generates a stream cut at this point (150) . Retention set has one stream cut at 270. Since truncating at …
> Issue 5557: cbr with stream scaling

- segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/chunklayer/ChunkedSegmentStorage.java
- segmentstore/storage/src/test/java/io/pravega/segmentstore/storage/chunklayer/ChunkedSegmentStorageMockTests.java
Fix ChunkedSegmentStorage.close by correctly calling chunkStorage.close
Previously this line was mistakenly deleted in old PR #6108 .
Fixes https://github.com/pravega/pravega/issues/7062
ChunkedSegmentStorage.close does not close chunkStorage anymore.
This change (https://github.com/pravega/pravega/commit/d680043da7299efa360887294dae4d8782e5244f#r110569766) mistakenly deleted the line closing chunkStorage.
This specifically causes leaks in ExtenededS3ChunkStorage. The client is supposed to be destroyed but becuase of this bug the zombie client will keep pinging the ECS server.
> Issue 7062: SLTS - Fix ChunkedSegmentStorage.close by calling chunkStorage.close

- segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/chunklayer/ChunkedSegmentStorage.java
- segmentstore/storage/src/test/java/io/pravega/segmentstore/storage/chunklayer/ChunkedSegmentStorageMockTests.java
Fix ChunkedSegmentStorage.close by correctly calling chunkStorage.close
Fixes #7064 
See #7062 .
See #7062 .
> Issue 7064: CHerry-pick PR 7063 to r0.13

- controller/src/main/java/io/pravega/controller/server/eventProcessor/ControllerEventProcessors.java
- controller/src/test/java/io/pravega/controller/server/eventProcessor/ControllerEventProcessorsTest.java
The log messages are incorrect for a few of the process which can be misleading sometimes.
During the creation of abort event processors the warn message prints Error creating commit event processor group which should be Error creating abort event processor group and same for kvt event processor.
(Fixes #7077)
Code will print the exact error message.
Check the logs once controller fail to create reader group.
> Issue 7077 : Incorrect log message in ControllerEventProcessors

- controller/src/conf/controller.config.properties
- controller/src/main/java/io/pravega/controller/task/Stream/StreamMetadataTasks.java
- controller/src/main/java/io/pravega/controller/util/Config.java
- controller/src/test/java/io/pravega/controller/task/Stream/StreamMetadataTasksTest.java
Temporarily revert the PR #7013 as it brings truncation to the streams which are not meant to be truncated like the internal streams.
This PR reverts the changes for bringing in the global retention policy as the global retention policy sets up the retention for the user created streams which are not meant to be truncated. At server side while creating a stream the call goes to the same method and hence there is no way to identify those streams. These user streams are used by statesyncronizer and few others and hence should not be truncated.
> Issue-7089: Revert PR 7013

- controller/src/conf/controller.config.properties
- controller/src/main/java/io/pravega/controller/task/Stream/StreamMetadataTasks.java
- controller/src/main/java/io/pravega/controller/util/Config.java
- controller/src/test/java/io/pravega/controller/task/Stream/StreamMetadataTasksTest.java
Reverts the changes from #7013 as the global retention should not be applied to few streams which are associated with statesynchronizer or revisionclient
Fixes #7093 
#7089 
#7089
> Issue 7093: Cherry-pick PR#7090 to r0.13

- test/system/src/test/java/io/pravega/test/system/ConsumptionBasedRetentionWithMultipleReaderGroupsTest.java
System test for multipleControllerFailoverAndRestartCBRTest failing intermittently.
Fixes #7094 
The failing system test is having multiple scaling up and down of controller and segment store instances and then validating the cbr feature, so at times due to the pods taking some time to come up or go down the test is unable to get completed within the timeout range and getting timed out. In order to fix the intermittent timeout issue, we have split the test case into two test cases.
> Issue 7094: fix cbr test failure

- config/config.properties
- segmentstore/server/host/src/main/java/io/pravega/segmentstore/server/host/handler/ConnectionTracker.java
- segmentstore/server/src/main/java/io/pravega/segmentstore/server/store/ServiceConfig.java
Moving DEFAULT_ALL_CONNECTIONS_MAX_OUTSTANDING_BYTES and DEFAULT_SINGLE_CONNECTION_MAX_OUTSTANDING to config.properties which can be configured depending on the installation.
Fixes #7083
Moving hardcoded values such as DEFAULT_ALL_CONNECTIONS_MAX_OUTSTANDING_BYTES and DEFAULT_SINGLE_CONNECTION_MAX_OUTSTANDING to config.properties
> Issue 7083: Move hardcoded parameters to config file

- cli/admin/src/main/java/io/pravega/cli/admin/segmentstore/FlushToStorageCommand.java
Call FlushToStorage parallelly in FlushToStorageCommand.
Fixes #7109 
Makes the flush to storage command execute parallelly.
Run longevity on pravega and call flush to storage. It should execute parallelly.
> Issue 7109: parallelize flush to storage

- client/src/test/java/io/pravega/client/stream/impl/LargeEventWriterTest.java
- segmentstore/server/host/src/test/java/io/pravega/segmentstore/server/host/FileSystemIntegrationTest.java
- segmentstore/server/src/main/java/io/pravega/segmentstore/server/containers/StreamSegmentContainer.java
- segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/chunklayer/ChunkedSegmentStorage.java
- segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/chunklayer/ChunkedSegmentStorageConfig.java
- segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/chunklayer/SnapshotInfo.java
- segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/chunklayer/SystemJournal.java
- segmentstore/storage/src/test/java/io/pravega/segmentstore/storage/chunklayer/FlakyChunkStorage.java
- segmentstore/storage/src/test/java/io/pravega/segmentstore/storage/chunklayer/SystemJournalOperationsTests.java
- segmentstore/storage/src/test/java/io/pravega/segmentstore/storage/chunklayer/SystemJournalRecordsTests.java
- segmentstore/storage/src/test/java/io/pravega/segmentstore/storage/chunklayer/SystemJournalTests.java
- shared/protocol/src/main/java/io/pravega/shared/NameUtils.java
- shared/protocol/src/test/java/io/pravega/shared/NameUtilsTest.java
---This is PR for feature branch---
Issue 7113: LTS - Save snapshot info to LTS and boot from it in case of migration/recovery.
Fixes #7113 
- Save snapshot info to a well-known LTS location at the same time it is written to snapshot info store. 
- During bootstrap use snapshot info from this well-known location on LTS when BK and ZK are empty.
- Also, slight adjustment to boot sequence to initialize SLTS GC task queue as late as possible.
Note that this code assumes following. 
- that underlying LTS provides read after create consistency. And consistency of creation of chunk with same name after delete. In other words, it is NOT eventually consistent.
-  Write by zombie is still prevented by fencing of …
> Issue 7113: LTS - Save snapshot info to LTS and boot from it in case of migration/recovery.

- segmentstore/contracts/src/main/java/io/pravega/segmentstore/contracts/Attributes.java
- segmentstore/contracts/src/main/java/io/pravega/segmentstore/contracts/SegmentType.java
- segmentstore/server/host/src/main/java/io/pravega/segmentstore/server/host/handler/AppendProcessor.java
- segmentstore/server/host/src/main/java/io/pravega/segmentstore/server/host/handler/PravegaRequestProcessor.java
- segmentstore/server/host/src/main/java/io/pravega/segmentstore/server/host/handler/WriterState.java
- segmentstore/server/host/src/test/java/io/pravega/segmentstore/server/host/handler/AppendProcessorTest.java
- segmentstore/server/host/src/test/java/io/pravega/segmentstore/server/host/handler/WriterStateTests.java
- shared/protocol/src/main/java/io/pravega/shared/NameUtils.java
- shared/protocol/src/test/java/io/pravega/shared/NameUtilsTest.java
- test/integration/src/test/java/io/pravega/test/integration/AppendTest.java
create shadow segment for event streams and related APIs to support functioning with shadow segment.
Fixes (https://github.com/pravega/pravega/issues/7149)
- creates a new shadow segment for event streams. Initialize an "event number" attribute on the segment that can be checked and updated at append time.
- Binds the lifecycle of the shadow segment with parent segment.
- Enforce that appends to this segment are fixed size records.
- If the main segment is deleted, then shadow segment associated with it is also deleted.
> Shadow segment creation

- client/src/main/java/io/pravega/client/BatchClientFactory.java
- client/src/main/java/io/pravega/client/batch/impl/BatchClientFactoryImpl.java
- client/src/main/java/io/pravega/client/segment/impl/SearchFailedException.java
- client/src/test/java/io/pravega/client/batch/impl/BatchClientImplTest.java
- segmentstore/server/host/src/main/java/io/pravega/segmentstore/server/host/handler/PravegaRequestProcessor.java
- shared/protocol/src/main/java/io/pravega/shared/protocol/netty/FailingReplyProcessor.java
- shared/protocol/src/main/java/io/pravega/shared/protocol/netty/ReplyProcessor.java
- shared/protocol/src/main/java/io/pravega/shared/protocol/netty/WireCommandType.java
- shared/protocol/src/main/java/io/pravega/shared/protocol/netty/WireCommands.java
- test/integration/src/test/java/io/pravega/test/integration/BatchClientTest.java
Added a new api in the BatchClientFactory to get the NextStreamCut which is at a bounded location from the current streamcut.
Spark attempts to load the whole batch of data into Ram before it processes any of it. This means that if for some reason the readers are slow on one batch and a lot of data is written while it is being processed, and when the workers attempt to load the next batch they will OOM.
The goal is to create a way to create a streamCut that is in a location that has not yet been read but is a bounded distance from the reader's current location.
When the current streamcut is passed with an approx distance in bytes to get the next streamcut, this new api calls the new wire command iteratively …
> Client side changes to get next stream cut

- client/src/main/java/io/pravega/client/stream/ReaderGroup.java
- client/src/main/java/io/pravega/client/stream/impl/CheckpointState.java
- client/src/main/java/io/pravega/client/stream/impl/ReaderGroupImpl.java
- client/src/main/java/io/pravega/client/stream/impl/ReaderGroupState.java
- client/src/test/java/io/pravega/client/stream/impl/CheckpointStateTest.java
- client/src/test/java/io/pravega/client/stream/impl/ReaderGroupImplTest.java
- client/src/test/java/io/pravega/client/stream/impl/SerializationTest.java
- test/integration/src/test/java/io/pravega/test/integration/CheckpointTest.java
Adding a new client API, which will cancel all outstanding checkpoints.
Fixes #7147 
Addition of cancelOutstandingCheckpoints() in ReaderGroup which calls removeOutstandingCheckpoints() in checkpointState class to remove the outstanding checkpoints.
When cancelOutstandingCheckpoints() is called, it must clear the outstanding checkpoints.
> Issue 7147: New client API to cancel all outstanding checkpoints

- docker/pravega/scripts/lts_recovery_backup.sh
The nautilus-cli has an issue with some output being posted to the error channel.
Fixes #7202 
Redirect stderr to stdout in the lts_recovery_backup.sh
Log in to segment-store container and execute lts_backup_recovery script i.e `./scripts/lts_recovery_backup.sh`
> Issue 7202: Redirecting stderr to stdout

- controller/src/main/java/io/pravega/controller/store/task/ZKTaskMetadataStore.java
- controller/src/test/java/io/pravega/controller/task/TaskTest.java
The changes are to remove the if condition during the transfer lock method. If the lock is acquired by a dead host, the sweeper task will try to transfer lock of the persistent node to the new host, however if during this process the controller dies and a new controller comes up then because of the condition the lock transfer will never take place and hence the stream creation will be impacted and the client application will always be in a stuck mode. 
Fixes #7213 
A simple change to remove the `if` block from two places 
one during the transfer lock and second during the get task method.
Build should pass and system test should pass
> Issue 7213: Handle lock transfer in case of unreliable network

- segmentstore/server/host/src/main/java/io/pravega/segmentstore/server/host/handler/AppendProcessor.java
- segmentstore/server/host/src/main/java/io/pravega/segmentstore/server/host/handler/PravegaRequestProcessor.java
- segmentstore/server/host/src/test/java/io/pravega/segmentstore/server/host/handler/PravegaRequestProcessorTest.java
Remove blocking call from setupAppend. Currently we are using **join()** in createIndexSegmentIfNotExists method.
Remove blocking call from setupAppend.
All existing test cases should pass.
> Remove blocking call from setupAppend.

- cli/admin/src/main/java/io/pravega/cli/admin/segmentstore/FlushToStorageCommand.java
- cli/admin/src/test/java/io/pravega/cli/admin/segmentstore/AbstractSegmentStoreCommandsTest.java
Fix for Admin CLI port with externalAccessEnabled.
Fixes #7264
Gets the correct port for every ss host retrieved from ZK.
Run FlushTOStorageCommand with the change.
> Issue 7264: Fix for admin cli port

- client/src/main/java/io/pravega/client/batch/SegmentIterator.java
- client/src/main/java/io/pravega/client/batch/impl/BatchClientFactoryImpl.java
- client/src/main/java/io/pravega/client/batch/impl/SegmentIteratorImpl.java
- client/src/test/java/io/pravega/client/batch/impl/SegmentIteratorTest.java
- test/integration/src/test/java/io/pravega/test/integration/BatchClientTest.java
Update valid offset on SegmentIterator next TruncatedDataException case, so that iterator next call can start reading from valid offset
Fixes #7269 
It updates the valid offset when TruncateddataException is catched.
After setting Truncation policy Longevity read should not due to TruncatedDataException.
> Issue 7269: Update valid offset on SegmentIterator next TruncatedDataException case

- segmentstore/server/src/main/java/io/pravega/segmentstore/server/containers/StreamSegmentContainer.java
Fixes the cases where we see "Unsupported format version" serialization exception after a container recovers in restore-from-lts mode. 
Fixes #7282
The issue was occurring due to there being difference in lengths recorded between container and storage metadata after the backup is done for the container event processor segments. This can happen on the container event processor segments especially due to them being constantly updated internally for GC purposes. This change basically takes the storage metadata length of the container event processor segments as the source of truth post a container restores and updates them in container metadata which results in correct reads/deserialization of events.
**How to …
> Fix for Unsupported Format version post backup-restore

- README.md
- documentation/src/docs/join-community.md
Added self-registration Slack link and updated developer mailing list.
Fixes #7296.
Updates the information in "Join the Community" documentation page.
A new user has been able to register in the Pravega Slack space with the provided link.
> Issue 7296: Fixes in community joining documentation

- docker/pravega/Dockerfile
* Update OpenJDK to 11.0.13
Closes #7294 
Updates OpenJDK to minimal working version with containerd ([see](https://github.com/kubernetes/kubernetes/issues/103944#issuecomment-1016898798))
> Issue 7294: Update OpenJDK from 11.0.11 to 11.0.13

- segmentstore/server/src/main/java/io/pravega/segmentstore/server/containers/EpochInfo.java
- segmentstore/server/src/main/java/io/pravega/segmentstore/server/containers/StreamSegmentContainer.java
- segmentstore/server/src/main/java/io/pravega/segmentstore/server/containers/StreamSegmentContainerMetadata.java
- segmentstore/server/src/main/java/io/pravega/segmentstore/server/writer/AttributeAggregator.java
- segmentstore/server/src/test/java/io/pravega/segmentstore/server/containers/StreamSegmentContainerMetadataTests.java
- segmentstore/server/src/test/java/io/pravega/segmentstore/server/containers/StreamSegmentContainerTests.java
This changeset fixes the case where Pravega Backup-Restore fails as described in #7314 .  #7314 is caused due to a gap in the backup-restore process. Elaborating further. Pravega internal Tables save the operation sequence numbers running inside a Segment Store Container, into them trough a attribute called "PERSIST_SEQ_NO". It so happens that when we restore PRavega using the Backup-Resotre procedure, we install Pravega afresh, causing the operation sequence numbers to reset inside container. Due to a check present on the internal Tables, If this number hasnt run-up more than the "PERSIST_SEQ_NO", the operations on the Table will get rejected causing keys to not get stored in the tables.
Fixes #7314
Backs …
> Issue 9207: Backup container operation seq no

- bindings/src/main/java/io/pravega/storage/azure/AzureStorageConfig.java
- bindings/src/main/java/io/pravega/storage/gcp/GCPStorageConfig.java
- bindings/src/test/java/io/pravega/storage/azure/AzureTestContext.java
- config/config.properties
- segmentstore/server/host/src/test/java/io/pravega/segmentstore/server/host/AzureIntegrationTest.java
Added configuration parameters and default values for new bindings in `config.properties` file.
Fixes #7311.
Improves documentation in `config.properties` file to help users configuring the new storage bindings (S3, Azure, GCP).
Also, it removes one unused property (`accesskey`) in Azure binding configuration file, as apparently the security information is expected in the storage url itself.
> Issue 7311: Add new storage bindings configuration examples in Pravega configuration file

- segmentstore/server/src/main/java/io/pravega/segmentstore/server/store/ServiceConfig.java
Loads the `DEFAULT_SINGLE_CONNECTION_MAX_OUTSTANDING_BYTES` property from the Segmentstore properly. 
This commit fixes issue #7325.
It reads the `default.single.connections.max.outstanding.bytes` key from the `config.properties` file to load the `DEFAULT_SINGLE_CONNECTION_MAX_OUTSTANDING_BYTES` in `ServiceConfig` class. 
1. Add two different values for `default.single.connections.max.outstanding.bytes` and `default.all.connections.max.outstanding.bytes` in the `config.properties` file.
2. Run the segmentstore, and check the first lines of the log, where the loaded properties are logged. 
3. Verify that the values printed in the log correspond to the values assigned in step 1. 
In my …
> Issue 7325: Segment store property not loaded

- client/src/main/java/io/pravega/client/segment/impl/EventSegmentReader.java
- client/src/main/java/io/pravega/client/segment/impl/EventSegmentReaderImpl.java
- client/src/main/java/io/pravega/client/segment/impl/SegmentInputStreamImpl.java
- client/src/main/java/io/pravega/client/stream/impl/Orderer.java
- client/src/test/java/io/pravega/client/segment/impl/SegmentInputStreamTest.java
It has been observed that for a stream having multiple segments and retention policy set, after some retention cycle, a slow reader is not able to read the data from the segments.
Fixes #7343 
When the data is truncated in the segment and the bytesInBuffer is having partial data which is less than WireCommands.TYPE_PLUS_LENGTH_SIZE then the reader is consistently getting segment as not ready to be read. As part of this PR, modified the condition of isSegmentReady which should return true if data is present in the buffer.
All the test cases should pass.
> Issue 7343: Fixing reader issue when data truncated

- test/integration/src/test/java/io/pravega/test/integration/AppendTest.java
Integration test for io.pravega.test.integration.AppendTest is failing consistently.
(Fixes #7414 )
After reading the data using ReadSegment  wire command, we have to release the bytebuff. Currently we are not releasing the bytebuff, this change will release bytebuff from SegmentRead once it used.
All integration test should pass.
> Issue 7414: Integration test for io.pravega.test.integration.AppendTest is failing consistently.

- client/src/main/java/io/pravega/client/stream/EventStreamWriter.java
- client/src/main/java/io/pravega/client/stream/impl/EventStreamWriterImpl.java
- client/src/test/java/io/pravega/client/stream/impl/ClientFactoryTest.java
- client/src/test/java/io/pravega/client/stream/impl/EventStreamWriterTest.java
- controller/src/test/java/io/pravega/controller/mocks/ControllerEventStreamWriterMock.java
- controller/src/test/java/io/pravega/controller/mocks/ControllerEventTableWriterMock.java
- controller/src/test/java/io/pravega/controller/mocks/EventStreamWriterMock.java
- controller/src/test/java/io/pravega/controller/server/eventProcessor/ScaleRequestHandlerTest.java
- controller/src/test/java/io/pravega/controller/task/KeyValueTable/TableMetadataTasksTest.java
- controller/src/test/java/io/pravega/controller/task/Stream/StreamMetadataTasksTest.java
- controller/src/test/java/io/pravega/controller/task/Stream/StreamTransactionMetadataTasksTest.java
- segmentstore/server/host/src/test/java/io/pravega/segmentstore/server/host/stat/AutoScaleProcessorTest.java
We need to create a client api, calling which should exclude the writer from timestamp aggregation calculation without having it to wait for timeout.
Fixes #7387 
An api is created in EventStreamWriterImpl, which accepts the user defined writerId and Stream and calls the controllers remove writer api. Also as part of this, we are calling the remove writer in the EventStreamWriter's close method.
All test case should pass.
> Issue 7387: Client api to exclude writer from timestamp aggregation calculation.

- segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/bookkeeper/ZooKeeperServiceRunner.java
- standalone/src/main/java/io/pravega/local/InProcPravegaCluster.java
- standalone/src/test/java/io/pravega/local/AuthEnabledInProcPravegaClusterTest.java
- standalone/src/test/java/io/pravega/local/InProcPravegaClusterTest.java
- standalone/src/test/java/io/pravega/local/SecurePravegaClusterTest.java
- standalone/src/test/java/io/pravega/local/TlsEnabledInProcPravegaClusterTest.java
- standalone/src/test/java/io/pravega/local/TlsProtocolVersion12Test.java
- standalone/src/test/java/io/pravega/local/TlsProtocolVersion13Test.java
In Pravega master junit test for InProcPravegaClusterTest failing consistently.
Fixes #7428.
This change will clear secure ZKClient properties from system properties so that next test subsequent test will not have stale client properties. I have also removed `@RunWith(SerializedClassRunner.class)` from standalone tests as it will improve standalone test execution time (i found that running tests in parallel is not causing any issue).
Run **./gradlew clean :standalone:test**, all tests should succeed.
> Issue 7428: Fix junit test failure for InProcPravegaClusterTest.

- client/src/main/java/io/pravega/client/admin/impl/StreamManagerImpl.java
- client/src/main/java/io/pravega/client/stream/StreamConfiguration.java
- client/src/test/java/io/pravega/client/control/impl/ModelHelperTest.java
- client/src/test/java/io/pravega/client/stream/StreamConfigurationTest.java
- controller/src/main/java/io/pravega/controller/server/bucket/PeriodicWatermarking.java
- controller/src/test/java/io/pravega/controller/rest/v1/ModelHelperTest.java
- test/integration/src/test/java/io/pravega/test/integration/WatermarkingTest.java
- test/integration/src/test/java/io/pravega/test/integration/controller/server/ControllerServiceTest.java
Currently in the StreamConfiguration if TimestampAggrigationTimeout is not specified it defaults to 0ms which is a non-sensical value which is interpreted to mean that all writer's a perpetually inactive, and hence ignored for watermarking purposes.
Closes #7408
In the StreamConfiguration if the TimestampAggrigationTimeout is not specified, the default value of 60sec is being set and if the value is specified it should be greater than 0 check is set. Also in the PeriodicWatermarking, for the streams created before, if the TimestampAggrigationTimeout is set to 0, we are considering the default value of 60sec
All the test cases should pass.
> Issue 7408: Provide a default and minimum value for TimestampAggrigationTimeout

- test/system/src/test/java/io/pravega/test/system/ConsumptionBasedRetentionWithMultipleReaderGroupsTest.java
Hi,
We found a typo in the logging messages.
It's an incremental commit but it can improve the quality of logging messages.
> Fix typos in logging messages

- .github/workflows/gradle.yml
- segmentstore/server/src/test/java/io/pravega/segmentstore/server/tables/AsyncTableEntryReaderTests.java
Update GitHub Actions to use V4 artifacts.
Should fix some errors related to #7438.
As can be seen in #7434, Pravega builds failed because of deprecated artifacts in GH actions. 
Uses the V4 artifacts for GitHub Actions in this repo. 
Run GH Actions
> Issue 7438: Upgrade GH actions to v4
